Add debug symbols support #9792
quarkusio/quarkus pull request #10093
Opened 2020-06-18 13:15 UTC by galderz

Closes #9792. 

This PR adds:
* A new debug symbol enable option called `quarkus.native.debug.enabled`.
* A new option has been added instead of breaking existing users that might rely on `quarkus.native.debugSymbols` flag. This flag adds `-g` to the `native-image` invocation which is a GraalVM EE only flag. Should it eventually deprecated? 
* After creating the native image, if `objcopy` is found, it uses it to split the debug symbols from the binary executable. The debug symbols are put in a file called `<executable>.debug` at the same level as the binary.
* This new option is disabled by default. See [quarkus-dev](https://groups.google.com/forum/#!topic/quarkus-dev/VOSQ6zhy_vI) discussion for details.

Q. What can I debug with this?
* User code in Quarkus project.
* JDK code.
* Some of the `com.oracle.svm` code.

Q. What can't I debug?
* Library dependencies. Further work on Quarkus build code needs to be done to enable source jars to be found. I'll create a follow up issue for this.
* `org.graalvm` code. Some sources are missing from latest GraalVM CE downloads. @adinn already spotted this and reported it in https://github.com/oracle/graal/issues/2551.

Q. What I do need to do native debugging?
* `gdb` version 8.x or 9.x. I tried with 7.6 but gdb itself gave me a segmentation fault (working with @adinn to figure out what's wrong there).
* (optional) emacs so that you can have nice integration between gdb and source navigation.

Q. Can I give this a try? 
Sure! 

I've been using this sample project called `debug-info` to test things out. This is how it works:

1. Build this Quarkus branch locally.
2. Go into debug-info project and call (assumes you're using GraalVM CE 20.1.0 as `JAVA_HOME`):
```
./mvnw clean package -DskipTests \
	-Pnative \
	-Dquarkus.platform.version=999-SNAPSHOT \
	-Dquarkus-plugin.version=999-SNAPSHOT \
	-Dquarkus.platform.artifact-id=quarkus-bom \
	-Dquarkus.native.debug.enabled=true
```
3. Fire up `emacs` (or any other tool that has gdb integration).
4. Call `M-x gud-gdb`
5. Invoke `gdb`: `gdb --fullname target/debug-info-1.0.0-SNAPSHOT-runner`
6. Verify that debug symbols are present, e.g. `info func greeting`
7. Put a breakpoint in the code, e.g. `break debug.info.GreetingService::greeting`
8. Make `gdb` execute the program, e.g. `run`
9. From a separate shell exercise the app, e.g. `curl localhost:8080/hello/greeting/quarkus`. The debugger should stop in the breakpoint.
10. Type `s` or `n` to jump around the code.

2020-06-18 13:57 UTC, jerboaa reviewed
Have you considered also to run the `--strip-debug` option on the produced image even when `-H:GenerateDebugInfo=0`? This is not for the application's debug symbols to get stripped, but for potential debug symbols in linked in static libraries to get removed. Smaller binaries and all that ;-)

2020-06-18 13:57 UTC, jerboaa commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java
> +        objcopy("--strip-debug", executable.toString());
I'd suggest to run this `objcopy("--strip-debug", executable.toString());` also when no debug symbols are being requested.  The reason for this is that OpenJDK's static libraries might contain debug symbols which in turn might end up in the native image binary and you could get rid of them in the produced native image by stripping them via `objcopy --strip-debug`.

2020-06-18 14:51 UTC, galderz commented
@jerboaa Updated the PR with your suggestion. Can you have another look? I assumed it's fine to strip debug symbols after adding the gnu debug link?

2020-06-18 15:40 UTC, jerboaa commented
> @jerboaa Updated the PR with your suggestion. Can you have another look? I assumed it's fine to strip debug symbols after adding the gnu debug link?

This seems fine to me. Thanks for the update.

2020-06-25 01:44 UTC, jaikiran commented
Just curious - is this planned to be available for 1.6 release? Would be a good thing to have, I think.

2020-06-25 15:07 UTC, gsmet requested changes
Spotted a small typo and forgot to post my review yesterday :/

2020-06-25 15:08 UTC, gsmet commented
@galderz where are we on this? Did anyone agree with this approach or are there still ongoing discussions?

2020-06-30 08:08 UTC, gsmet commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java
> +                // Strip debug symbols regardless, because the the underlying JDK might contain them
I just pushed a fix.

2020-06-30 08:10 UTC, gsmet commented
@galderz can you confirm me that we should merge this?

2020-06-30 16:00 UTC, gsmet approved these changes

2020-06-30 19:46 UTC, galderz commented
@gsmet All looks good after [this discussion](https://groups.google.com/g/quarkus-dev/c/VOSQ6zhy_vI/m/56xzfbTMBwAJ). I'm working on further enhancements that cannot make it this release (e.g. support third party library source code navigation).

2020-07-01 10:48 UTC, gsmet commented
Ok, let's merge it then, thanks!

2020-07-01 10:48 UTC, merged