Add a section about the redirection to the OIDC web-app docs
quarkusio/quarkus pull request #10321
Opened 2020-06-27 16:23 UTC by sberyozkin

This update follows the discussion on the forum, some clarification about the way `quarkus-oidc` handles the redirection will help the users. CC @emmanuelbernard

2020-06-28 14:57 UTC, gastaldi requested changes
Added some minor fixes

2020-06-28 14:57 UTC, gastaldi commented on docs/src/main/asciidoc/security-openid-connect-web-authentication.adoc
> +When the user is redirected to the OpenID Connect Provider to authenticate, the redirect URL includes a `redirect_uri` query parameter which indicates to the Provider where the user has to be redirec
```suggestion
When the user is redirected to the OpenID Connect Provider to authenticate, the redirect URL includes a `redirect_uri` query parameter which indicates to the Provider where the user has to be redirected to once the authentication has been completed.
```

2020-06-28 14:57 UTC, gastaldi commented on docs/src/main/asciidoc/security-openid-connect-web-authentication.adoc
> +Quarkus will set this parameter to the current request URL by default. For example, if the user is trying to access a Quarkus service endpoint at `http://localhost:8080/service/1` then the `redirect_
```suggestion
Quarkus will set this parameter to the current request URL by default. For example, if the user is trying to access a Quarkus service endpoint at `http://localhost:8080/service/1` then the `redirect_uri` parameter will be set to `http://localhost:8080/service/1`. Similarly, if the request URL is `http://localhost:8080/service/2` then the `redirect_uri` parameter will be set to `http://localhost:8080/service/2`, etc.
```

2020-06-28 14:57 UTC, gastaldi commented on docs/src/main/asciidoc/security-openid-connect-web-authentication.adoc
> +OpenID Connect Providers may be configured to require that the `redirect_uri` parameter has the same value such as `http://localhost:8080/service/callback` for all the redirect URLs.
```suggestion
OpenID Connect Providers may be configured to require the `redirect_uri` parameter to have the same value (eg. `http://localhost:8080/service/callback`) for all the redirect URLs.
```

2020-06-28 14:57 UTC, gastaldi commented on docs/src/main/asciidoc/security-openid-connect-web-authentication.adoc
> +In such cases a `quarkus.oidc.authentication.redirect-path` property has to be set, for example, `quarkus.oidc.authentication.redirect-path=/service/callback`, and Quarkus will set the `redirect_uri`
```suggestion
In such cases a `quarkus.oidc.authentication.redirect-path` property has to be set, for example, `quarkus.oidc.authentication.redirect-path=/service/callback`, and Quarkus will set the `redirect_uri` parameter to an absolute URL such as `http://localhost:8080/service/callback` which will be the same regardless of the current request URL.
```

2020-06-28 20:30 UTC, sberyozkin commented
Hi @gastaldi Thanks for cleaning it up. cheers

2020-06-29 12:41 UTC, gastaldi approved these changes
LGTM. Please squash your commits before merging it :+1:

2020-06-30 08:02 UTC, gsmet commented
I squashed the commits, let's merge.

2020-06-30 08:02 UTC, merged