Basic support for AWS Lambdas
quarkusio/quarkus pull request #1042
Opened 2019-02-25 20:08 UTC by evanchooly

Running in native mode doesn't quite work yet but this is functional enough for folks to start playing with.  There are some limitations in terms of input and output (incoming POJOs work but necessarily returning them yet) but these bits can be iterated on depending on how far down this road we want to go.

2019-02-25 21:18 UTC, dmlloyd submitted a review, later dismissed
Looks OK but really needs to be squashed down to probably one commit.

2019-02-25 22:38 UTC, dmlloyd approved these changes

2019-02-25 22:44 UTC, gsmet requested changes
I added a few comments inline, mostly about the pom files and the structure.

2019-02-25 23:00 UTC, stuartwdouglas requested changes

2019-02-28 01:11 UTC, stuartwdouglas approved these changes

2019-02-28 02:11 UTC, stuartwdouglas approved these changes

2019-02-28 02:11 UTC, merged