Update Docs for native-image Commons Logging
quarkusio/quarkus pull request #10474
Opened 2020-07-04 12:21 UTC by oztimpower

PR to update docs for #10128

`JBoss Logging` implementations are required when using dependencies that use `Apache Commons Logging` as detailed in #10128 demonstrating the working solution. Native image will fail with `ClassNotFoundException` when looking for the implementation class. 

Updated documentation so this information is available.

2020-07-04 12:28 UTC, jaikiran commented on docs/src/main/asciidoc/logging.adoc
> +            <version>1.0.0.Final</version>
Hello @oztimpower, Should users be mentioning these versions here? Or does our bom file for Quarkus manage these versions? I think it's better to not have these versions specified here.

2020-07-06 21:29 UTC, gastaldi submitted a review, later dismissed

2020-07-06 21:29 UTC, gastaldi commented on docs/src/main/asciidoc/logging.adoc
> +If you are using libraries that have dependencies on `Apache Commons Logging` and experience complications building the native image such as class not found, you can resolve this by integrating the `
```suggestion
If you are using libraries that have dependencies on `Apache Commons Logging` and are experiencing complications building the native image due to missing logging classes, you can resolve this by integrating the `JBoss Logging` dependency.
```

2020-07-06 21:29 UTC, gastaldi commented on docs/src/main/asciidoc/logging.adoc
> +Caused by java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl)
```suggestion
Caused by java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl
```

2020-07-06 21:29 UTC, gastaldi commented on docs/src/main/asciidoc/writing-native-applications-tips.adoc
> +If you are using dependencies that require `Apache Commons Logging` and experience a `ClassNotFoundException` when building the native-image, you can resolve this by adding the `JBoss Loggging` imple
```suggestion
If you are using dependencies that require `Apache Commons Logging` and are experiencing a `ClassNotFoundException` when building the native-image, you can resolve this by adding the corresponding `JBoss Loggging` implementation.
```

2020-07-07 09:45 UTC, gsmet requested changes
I know it's a minor detail but please remove the backticks for `Apache Commons Logging` and `JBoss Logging`. I don't see the value of them, we should keep them for class names and similar things.

Thanks!

2020-07-07 14:17 UTC, oztimpower commented
Request changes done, please review.

2020-07-10 14:05 UTC, gsmet commented
@oztimpower I think the problem is more general than what you stated so I tweaked things a bit. Could you have a look?

2020-07-11 07:08 UTC, oztimpower commented
Yep, that needs to be mentioned, thanks.  Squashed the commits.

2020-07-13 10:58 UTC, gsmet approved these changes

2020-07-13 10:59 UTC, merged