Use JBoss Commons Logging Implementation - Amazon Alexa
quarkusio/quarkus pull request #10655
Opened 2020-07-11 07:31 UTC by oztimpower

Enforce the use of the JBoss Apache Commons Logging Implementation by default for use with native image compilation of Amazon Alexa #10589, as explained in the documentation update #10474 

The Amazon ASK SDK v2 uses Commons Logging, and an SL4J implementation, which is excluded by the Quarkus Amazon Alexa extension.

2020-07-12 14:27 UTC, gsmet requested changes
Question: should we add the SLF4J connector too?

2020-07-13 11:43 UTC, oztimpower commented
I would probably need help on what the JBoss Logging SL4J-impl is, as I had looked in the Maven Repo and couldn't find it (hence didn't add).

My understanding is that SL4J will do "no-op" logging if an implementation is not found, though I suspect there may be some order preference being used, just like JBoss Logging does.

2020-07-13 13:10 UTC, dmlloyd commented
All of these adapters should be added to the core IMO.  It was just an error on my part that they were left off.  But probably it should be `commons-logging-jboss-logmanager`, `slf4j-jboss-logmanager`, `log4j-jboss-logmanager`, and `log4j2-jboss-logmanager`.

2020-07-13 14:43 UTC, gsmet commented
I think I listed most of them here: https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/logging.adoc#logging-adapters .

2020-07-13 14:44 UTC, gsmet commented
But yeah, either we add them when we exclude the implementation or we add them all to the core artifacts.

2020-07-15 07:49 UTC, oztimpower commented
Thanks @dmlloyd @gsmet for the SL4J details, apologies for missing it in the docs

I've updated the pom to include both, however I probably think it makes also to have this driven from the core.

2020-07-15 08:04 UTC, gsmet approved these changes

2020-07-15 14:10 UTC, merged

2020-07-15 14:10 UTC, gsmet commented
Thanks!