Fix resource filtering in amazon-lambda archetypes
quarkusio/quarkus pull request #10829
Opened 2020-07-18 17:16 UTC by famod

Fixes #10825

I compared the two affected archetypes to the one of `azure-functions-http` (which does not have this problem) and it turned out that the two lamda modules were replacing property placeholder pre-maturely.

I left the `gradle.properties` filtering in `amazon-lambda` untouched but that might need to be adjusted as well (I have only little experience with Gradle).

PS: The `maven-archetype-plugin` definitions did not make sense to me since there no integration tests.

2020-07-18 17:19 UTC, famod commented
@gsmet AFAICT, this filtering problem is _not_ a 1.6 regression but with the addition of  `maven.home` in 1.6, this can actually be considered a regression.

2020-07-18 21:13 UTC, famod commented
The funqy archetype is also affected. Will push an update tomorrow.

2020-07-20 08:58 UTC, gsmet requested changes
Please don't merge yet, I would favor the approach in https://github.com/quarkusio/quarkus/pull/10845 .

2020-07-20 13:47 UTC, gsmet commented
Superseded by https://github.com/quarkusio/quarkus/pull/10845 .

2020-07-20 13:47 UTC, closed without merging