Align archetype generated pom.xml to to quarkus:create
quarkusio/quarkus pull request #10836
Opened 2020-07-19 14:07 UTC by famod

Fixes #10826, at least for the creation of new projects.

⚠️ **This is based on the currently unmerged PR #10829 (see first commit)!** I'll rebase as soon as PR #10829 is merged.

Currently this block does not match for the archetype generated pom.xml: https://github.com/quarkusio/quarkus/blob/master/independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/buildfile/MavenBuildFile.java#L81-L83
AFAICT, this is a regression caused by a larger refactoring: https://github.com/quarkusio/quarkus/commit/97f9981d7091c6355121c33b9aa333d9b81a4e12 (/cc @ia3andy).
Since I did/do not question this extended check, I aligned all four archetype pom.xml files to what `quarkus:create` is doing.
Some notable and maybe debatable "side effects":
- Java level is now 11 instead of 8
- `quarkus-universe-bom` is used instead of `quarkus-bom`, so for testing you either need a matching `999-SNAPSHOT` of universe or you have to define `-Dquarkus.platform.artifact-id=quarkus-bom` (in conrast, `mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create` is generating a `1.6.0.Final` project...)

Theoretically we could (additionally?) soften the check. But again, I did not question that for this fix.

2020-07-19 14:12 UTC, famod commented
@gsmet This is a regression in 1.6.0. Users could fix it themselves but they would first need to know what to change in `pom.xml`.
Certainly not beneficial for developer joy.

2020-07-19 22:38 UTC, famod commented
> Theoretically we could (additionally?) soften the check. But again, I did not question that for this fix.

Come to think of it, the current very strict check is denying the users the possibility to restructure their `pom.xml` (in terms of the bom).
Do we really want to do that?

2020-07-19 22:55 UTC, famod commented on extensions/amazon-lambda-http/maven-archetype/src/main/resources/archetype-resources/pom.xml
> +        <assembly-plugin.version>3.1.0</assembly-plugin.version>
Defining version properties for some plugins but directly setting versions for other plugins seemed inconsistent, so I introduced this property.
Not sure why it has to be 3.1.0, though. The latest version is 3.3.0.

2020-07-20 07:22 UTC, ia3andy commented
Hey guys, sorry, I was in PTO. 

Maybe we need to change the check which seems a bit too strict.. the idea is that our tooling should only works when the pom.xml contains a valid Quarkus bom (cc @aloubyansky)

2020-07-20 08:06 UTC, gsmet commented
I'm a bit worried about the usage of the quarkus-universe-bom in the core project. I don't really see a better solution though. Maybe @aloubyansky would have some input.

2020-07-20 09:42 UTC, famod commented
@ia3andy I'd suggest to adjust the check in a sperate PR.
I won't have time to do that since I am back from PTO and have to take care of my commercial project.

2020-07-20 10:01 UTC, ia3andy commented
> @ia3andy I'd suggest to adjust the check in a sperate PR.
> I won't have time to do that since I am back from PTO and have to take care of my commercial project.

no problem and thanks!! I am waiting for @aloubyansky take on it, and could provide a PR.

2020-07-20 12:58 UTC, patriot1burke commented
FYI, azure functions does not support Java 11.

2020-07-20 12:59 UTC, patriot1burke requested changes

2020-07-20 12:59 UTC, patriot1burke commented on extensions/azure-functions-http/maven-archetype/src/main/resources/archetype-resources/pom.xml
> +    <maven.compiler.source>11</maven.compiler.source>
azure functions does not support Java 11.

2020-07-20 13:01 UTC, patriot1burke commented
I worry that you have not testesd these changes.  For instance, azure functions does not support Java 11.  Much of this is my fault for not having automated testing of the archetypes.

2020-07-20 13:46 UTC, gsmet commented
@patriot1burke it's under control here: https://github.com/quarkusio/quarkus/pull/10845 .

2020-07-20 13:46 UTC, closed without merging

2020-07-20 14:06 UTC, famod commented
@patriot1burke 

> I worry that you have not testesd these changes.

Yes and no. 😉 
I have create new projects with the adjusted archetypes, I have run `mvn clean install` and I have run `mvn quarkus:add-extension -Dextensions="smallrye-jwt"`.
But I had not deployed to Azure.

That's also why I highlighted this notable change in the PR description.

But as @gsmet already said: It's under control! 🙂