Change to align UI to Health UI
quarkusio/quarkus pull request #10890
Opened 2020-07-21 18:50 UTC by phillip-kruger

As discussed in #10828, this PR aligns the config to be similar to Health UI.

Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>

2020-07-21 18:59 UTC, gsmet requested changes
Added a small suggestion regarding the javadoc.

2020-07-21 18:59 UTC, gsmet commented on extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLConfig.java
> +     * Configuration properties for UI
This javadoc will be the title of the section so maybe just "User interface" or "UI configuration" would be better.

2020-07-21 19:41 UTC, gastaldi commented
LGTM after @gsmet's suggestion is addressed :+1:

2020-07-22 07:35 UTC, gsmet approved these changes

2020-07-22 20:18 UTC, gastaldi approved these changes

2020-07-23 01:25 UTC, merged