Feature/azure app config
quarkusio/quarkus pull request #11106
Opened 2020-07-30 19:11 UTC by dabloem

@geoand  @maxandersen please review. thx.

2020-07-30 19:21 UTC, geoand commented
Thanks for this.

One thing I can say right off the bat, is that we'll need to have this rebased onto master so the PR can have your commit only.

As for a review, it might take a while as we are in the midst of getting 1.7 out and PTO is coming up.

Nevertheless, we'll do our best to get you feedback ASAP

2020-07-30 19:41 UTC, dabloem commented
@geoand  rebase done

2020-07-30 20:12 UTC, geoand requested changes
I made a very quick (first) pass at this and I would like to see the commented out code removed and the references to Spring Cloud Config removed and replaced with the proper comments.

I'll hopefully do a further review soon

2020-07-30 20:13 UTC, geoand commented
What I would also like to see, is a README describing how to test this against a real instance of Azure Config

2020-07-31 07:00 UTC, geoand commented on docs/src/main/asciidoc/azure-app-config-client.adoc
> +    @ConfigProperty(name = "application/config.message", defaultValue="hello default")
`"application/config.message"` is something we don't want. All configuration properties should only use `.` as a delimiter

2020-07-31 07:14 UTC, geoand requested changes
This is great work, thanks!

I added a bunch of comments that definitely need to be addressed.

We will also absolutely need an integration (similar to Spring Cloud Config) that shows this working end to end (in native mode as well)

2020-07-31 07:14 UTC, geoand commented on extensions/azure-app-config-client/deployment/src/main/java/io/quarkus/spring/cloud/config/client/AzureAppConfigProcessor.java
> +        feature.produce(new FeatureBuildItem("azure-app-config"));
The constant should be part of `Feature` enum as is done in other extensions.

2020-07-31 07:14 UTC, geoand commented on extensions/azure-app-config-client/deployment/src/main/java/io/quarkus/spring/cloud/config/client/AzureAppConfigProcessor.java
> +        extensionSslNativeSupport.produce(new ExtensionSslNativeSupportBuildItem("azure-app-config"));
Same here

2020-07-31 07:14 UTC, geoand commented on extensions/azure-app-config-client/deployment/src/main/java/io/quarkus/spring/cloud/config/client/AzureAppConfigProcessor.java
> +        // reflectiveClass.produce(new ReflectiveClassBuildItem(true, false, false, Response.PropertySource.class));
Please remove all commented out code

2020-07-31 07:14 UTC, geoand commented on extensions/azure-app-config-client/runtime/src/main/java/io/quarkus/azure/app/config/client/runtime/Item.java
> +public class Item {
Maybe just make this a static inner class of `Response`?

2020-07-31 07:14 UTC, geoand commented on extensions/azure-app-config-client/runtime/src/main/java/io/quarkus/azure/app/config/client/runtime/AzureAppConfigClientConfig.java
> +     * If enabled, will try to read the configuration from a Spring Cloud Config Server
Please remove all references to Spring Cloud Config

2020-07-31 07:14 UTC, geoand commented on extensions/azure-app-config-client/runtime/src/main/java/io/quarkus/azure/app/config/client/runtime/AzureAppConfigClientConfig.java
> +    @ConfigItem //(defaultValue = "http://localhost:8888")
What is the proper default?

2020-07-31 07:14 UTC, geoand commented on extensions/azure-app-config-client/runtime/src/main/java/io/quarkus/azure/app/config/client/runtime/AzureAppConfigServerClientConfigSourceProvider.java
> +            items.forEach(i -> props.put(i.getKey(), i.getValue()));
We try and not use lambdas in code that is executed at runtime

2020-07-31 07:14 UTC, geoand commented on extensions/azure-app-config-client/runtime/src/main/java/io/quarkus/azure/app/config/client/runtime/AzureAppConfigServerClientConfigSourceProvider.java
> +            // final List<Response.PropertySource> propertySources = response.getPropertySources();
Please remove all commented out code

2020-07-31 07:14 UTC, geoand commented on extensions/azure-app-config-client/runtime/src/main/java/io/quarkus/azure/app/config/client/runtime/DefaultAzureAppConfigClientGateway.java
> +                //proxy?
If we are going to support proxy, then please add the code. Otherwise please remove the field from `AzureAppConfigClientConfig`

2020-07-31 07:14 UTC, geoand commented on extensions/azure-app-config-client/runtime/pom.xml
> +        <dependency>
IIUC, you only need this for the IOUtils method. If so, I would suggest to remove and perform the necessary operation manually. We really want to minimize runtime footprint as much as possible

2020-07-31 07:14 UTC, geoand commented on extensions/azure-app-config-client/runtime/src/main/java/io/quarkus/azure/app/config/client/runtime/DefaultAzureAppConfigClientGateway.java
> +class DefaultAzureAppConfigClientGateway implements AzureAppConfigClientGateway {
I would like to have some good comments on this class as it's the meat of the interaction with Azure Config and it's probably the one that will need more maintenance than anything else

2020-07-31 16:04 UTC, dabloem commented
@geoand I verified manually it also works in native mode now

2020-07-31 16:24 UTC, geoand commented
That's nice 👍, but we really need an integration test for it

2020-07-31 16:28 UTC, dabloem commented
@geoand sure, I don't see any for spring-cloud-config, right?
Can you point me to a similar integration test?

2020-07-31 16:29 UTC, geoand commented
https://github.com/quarkusio/quarkus/tree/master/integration-tests/spring-cloud-config-client

2020-08-03 08:16 UTC, geoand commented
The integration test itself looks good, thanks! We would however need to add it to https://github.com/quarkusio/quarkus/blob/3da056de7b340bd5aa7dd4495ad10148420e0945/.github/workflows/ci-actions.yml#L540

Also, once you have addressed the rest of the comments, please ping me or @gsmet or @gastaldi (as I will likely be out for a couple of weeks)

2020-08-03 09:38 UTC, geoand commented
> What I would also like to see, is a README describing how to test this against a real instance of Azure Config

This would likely be in the root of the integration test directory

2020-08-03 09:39 UTC, geoand commented on extensions/azure-app-config-client/runtime/src/main/java/io/quarkus/azure/app/config/client/runtime/AzureAppConfigServerClientConfigSourceProvider.java
> +        azureAppConfigClientGateway = new DefaultAzureAppConfigClientGateway(appCfgClientConfig);
Let's keep it consistent and use `this` here as well

2020-08-03 09:39 UTC, geoand commented on extensions/azure-app-config-client/runtime/src/main/java/io/quarkus/azure/app/config/client/runtime/DefaultAzureAppConfigClientGateway.java
> +            // HttpClientContext context = setupContext(finalURI);
Is this leftover?

2020-08-03 09:39 UTC, geoand commented on extensions/azure-app-config-client/runtime/src/main/java/io/quarkus/azure/app/config/client/runtime/DefaultAzureAppConfigClientGateway.java
> +        // result.setParameter("label", "value");
What is this?

2020-08-03 09:40 UTC, geoand commented on extensions/azure-app-config-client/runtime/src/main/java/io/quarkus/azure/app/config/client/runtime/DefaultAzureAppConfigClientGateway.java
> +    static DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEE, dd MMM yyyy HH:mm:ss O");
I assume this can be `final`?

2020-08-04 18:49 UTC, geoand commented
I'll be on PTO for a while, so I might be a little late to respond to updates

2020-08-27 11:09 UTC, gsmet commented
@geoand could you have another look at this one?

2020-08-27 11:15 UTC, geoand commented
Seems like some of my comments still haven't been addressed

2020-09-01 12:20 UTC, geoand commented
@dabloem do you want me to take over this PR?

2020-09-03 05:19 UTC, geoand commented
Seems like there are still some unaddressed comments (for example https://github.com/quarkusio/quarkus/pull/11106/files#r463443162).

Can you please take a look @dabloem ?

2021-02-23 00:19 UTC, radcortez commented
@dabloem are you still interested in moving this PR forward? Thanks!

2021-02-23 22:08 UTC, dabloem commented
@radcortez  yes, I am! But let's review the open comments, and give me clear guidance what to do.
My open questions are:
- do we need a proxy?
- do we use "https://{config-name}.azconfig.io" or just the full url ?
- what do we do with the label?
- do we comply to the referenced Azure quickstart documentation or not?
Regards,
Duncan

2021-02-24 20:05 UTC, radcortez commented
> @radcortez yes, I am! But let's review the open comments, and give me clear guidance what to do.

Great! Lets try to move this forward :)

> My open questions are:
> 
> * do we need a proxy?

For a first version, maybe we should make it simple and leave proxy out. If required we can add it later.

> * do we use "https://{config-name}.azconfig.io" or just the full url ?

Not sure about this, since I'm not familiar how Azure app config works. But if {config-name} is something configurable to retrieve your own configuration I think it makes sense to use it.

> * what do we do with the label?

Can you clarify please? Which label?

> * do we comply to the referenced Azure quickstart documentation or not?

Ideally, I think we should try to comply to it, so the user experience is similar and we can point to their documentation. On the other hand, if there areas that we can simplify and improve the user experience from our side we should do them, but it can be done in a later version.

Thanks!

2021-02-26 11:53 UTC, dabloem commented
A label is a key differentiator. E.g. it can be used to indicate the environment 'key:staging-label' = some-value or  'key:production-label' = other-value.  However, the label is optional and may contain null.  (see https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-key-value)

ps, regarding the azure documentation. The docs state the property as " application/config.message" , which does not comply to the quarkus way of defining property keys.

2021-04-01 08:54 UTC, gsmet commented
@geoand should we try to revive this one, either as a core extension or as Quarkiverse one? It looks interesting?

2021-04-01 09:10 UTC, geoand commented
Yeah, I would definitely want this in the Quarkiverse

2021-04-01 09:14 UTC, dabloem commented
Gents,
If you want, please taken over and finish this nice feature as you would
see fit.

Regards,
Duncan

Op do 1 apr. 2021 11:10 schreef Georgios Andrianakis <
***@***.***>:

> Yeah, I would definitely want this in the Quarkiverse
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/quarkusio/quarkus/pull/11106#issuecomment-811770546>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABJFFDAZAZBJJLJXVIER2TTGQ2APANCNFSM4POOH7LQ>
> .
>

2021-04-01 09:37 UTC, geoand commented
@radcortez is this something you are interested in moving forward?

2021-04-01 10:17 UTC, radcortez commented
Sure. This should align with https://github.com/quarkusio/quarkus/issues/16124 and move to a single Quarkiverse extension to host all custom config sources.

@gastaldi can you create a project in Quarkiverse? Maybe `config-sources`? Or `config-extensions`? Someone with a better name ? :)

2021-04-01 10:22 UTC, geoand commented
> Maybe `config-sources`? Or `config-extensions`? Someone with a better name ? :)

I am terrible at naming, but both sound find with me

2021-04-01 10:39 UTC, radcortez commented
> > Maybe `config-sources`? Or `config-extensions`? Someone with a better name ? :)
> 
> I am terrible at naming, but both sound find with me

Me too :)

2021-04-01 10:47 UTC, dabloem commented
Haha, okay let's start. ;-)

My pref is config-extensions.

Because config-sources is too similar to the mp naming and therefor leads
to speech problems/miscommunication.
(Maybe it leads to 'config-sources-extensions' naming in discussions to
distinguish.)

Duncan

Op do 1 apr. 2021 12:39 schreef Roberto Cortez ***@***.***>:

> Maybe config-sources? Or config-extensions? Someone with a better name ?
> :)
>
> I am terrible at naming, but both sound find with me
>
> Me too :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/quarkusio/quarkus/pull/11106#issuecomment-811820255>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABJFFCCEO3STHTUBKPFZXLTGREPLANCNFSM4POOH7LQ>
> .
>

2021-04-01 13:31 UTC, gastaldi commented
> Sure. This should align with #16124 and move to a single Quarkiverse extension to host all custom config sources.
> 
> @gastaldi can you create a project in Quarkiverse? Maybe `config-sources`? Or `config-extensions`? Someone with a better name ? :)

Just so I can understand it better: This new extension is meant to support [Azure App Config](https://azure.microsoft.com/en-us/services/app-configuration/#features) or to support any `ConfigSource` implementations (like https://github.com/microprofile-extensions/config-ext/)?

2021-04-01 13:56 UTC, radcortez commented
> > Sure. This should align with #16124 and move to a single Quarkiverse extension to host all custom config sources.
> > @gastaldi can you create a project in Quarkiverse? Maybe `config-sources`? Or `config-extensions`? Someone with a better name ? :)
> 
> Just so I can understand it better: This new extension is meant to support [Azure App Config](https://azure.microsoft.com/en-us/services/app-configuration/#features) or to support any `ConfigSource` implementations (like https://github.com/microprofile-extensions/config-ext/)?

To support any `ConfigSource` implementation. We may also use it to move current Quarkus extensions from the core into this one.

2021-04-01 13:59 UTC, gastaldi commented
> To support any `ConfigSource` implementation. We may also use it to move current Quarkus extensions from the core into this one.

Ok, so I have to ask: why not put them in the https://github.com/microprofile-extensions/config-ext/ repository? Or is this intended to contain ConfigSources that would work only in Quarkus?

2021-04-01 15:23 UTC, radcortez commented
> > To support any `ConfigSource` implementation. We may also use it to move current Quarkus extensions from the core into this one.
> 
> Ok, so I have to ask: why not put them in the https://github.com/microprofile-extensions/config-ext/ repository? Or is this intended to contain ConfigSources that would work only in Quarkus?

So the main ConfigSource implementation may either live in `microprofile-extensions` or `smallrye-config`. From my experience, we usually require to wrap each dependency in a Quarkus Extension. For instance, even with the simple `yaml` config source, we added the extension to support `application.yaml` and to hook the HotDeployment watcher.

2021-04-01 17:02 UTC, gastaldi commented
Repository created in https://github.com/quarkiverse/quarkus-config-extensions. 

@dabloem I added you to the https://github.com/orgs/quarkiverse/teams/quarkiverse-config-extensions team, which should give you write permission in that repository and pushed a sample multimodule Quarkus extension structure there. Feel free to go wild :)

Once you feel you have a stable code, release it by following the instructions in https://github.com/quarkiverse/quarkiverse/wiki/Release  

Let me know how that goes.

2021-04-01 17:19 UTC, radcortez commented
Thanks!

2021-06-30 20:59 UTC, gastaldi commented
Replaced by Quarkiverse extension in https://github.com/quarkiverse/quarkus-config-extensions

2021-06-30 20:59 UTC, closed without merging

2021-06-30 21:43 UTC, knutwannheden commented
> Replaced by Quarkiverse extension in https://github.com/quarkiverse/quarkus-config-extensions

Cool. But it looks like that repo doesn't contain any code or PR for the Azure App Config extension yet.

@dabloem Are you still working on this?