Hibernate Validator: status 400 instead of 500 if JAX-RS method is defined in interface
quarkusio/quarkus pull request #11506
Opened 2020-08-20 23:21 UTC by famod

Follow up to #11429, fixes https://github.com/quarkusio/quarkus/issues/11341#issuecomment-673146350.
See also: https://github.com/quarkusio/quarkus/pull/11429#discussion_r471786768

I basically just gather all JAX-RS methods (whether or not defined in interfaces).

This is my first time working with the Quarkus deployment framework so please bear with me in case I did something stupid or inefficient. 😉

2020-08-21 03:51 UTC, jaikiran commented
Failure looks related:

```
2020-08-21T01:07:48.2222974Z [INFO] Running io.quarkus.it.spring.web.ExceptionHandlingTest
2020-08-21T01:07:53.2554499Z [ERROR] Tests run: 18, Failures: 0, Errors: 1, Skipped: 17, Time elapsed: 5.016 s <<< FAILURE! - in io.quarkus.it.spring.web.ExceptionHandlingTest
2020-08-21T01:07:53.2555409Z [ERROR] io.quarkus.it.spring.web.ExceptionHandlingTest.testUnhandledAnnotatedException  Time elapsed: 0.013 s  <<< ERROR!
2020-08-21T01:07:53.2556172Z java.lang.RuntimeException: 
2020-08-21T01:07:53.2561661Z java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
2020-08-21T01:07:53.2563752Z 	[error]: Build step io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor#build threw an exception: java.lang.IllegalArgumentException: Not a method
2020-08-21T01:07:53.2564427Z 	at org.jboss.jandex.ClassInfo.asMethod(ClassInfo.java:611)
2020-08-21T01:07:53.2566323Z 	at io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor.gatherJaxRsMethods(HibernateValidatorProcessor.java:362)
2020-08-21T01:07:53.2568112Z 	at io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor.build(HibernateValidatorProcessor.java:251)
2020-08-21T01:07:53.2568861Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-08-21T01:07:53.2570134Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-08-21T01:07:53.2571713Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-08-21T01:07:53.2572370Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-08-21T01:07:53.2573493Z 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
2020-08-21T01:07:53.2574286Z 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
2020-08-21T01:07:53.2575744Z 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
2020-08-21T01:07:53.2576915Z 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
2020-08-21T01:07:53.2578307Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
2020-08-21T01:07:53.2579587Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
2020-08-21T01:07:53.2580052Z 	at java.lang.Thread.run(Thread.java:748)
2020-08-21T01:07:53.2581294Z 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
2020-08-21T01:07:53.2581607Z 
```

2020-08-21 08:16 UTC, gsmet requested changes
I think this is mostly right, thanks!

I added some comments inline.

2020-08-21 08:16 UTC, gsmet commented on extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/MethodValidatedAnnotationsTransformer.java
> +                        .orElse(false));
Please use standard imperative code. This is far less readable.

2020-08-21 08:16 UTC, gsmet commented on extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java
> +        effectiveJaxRsMethodDefiningAnnotations.addAll(Arrays.asList(JAXRS_METHOD_ANNOTATIONS));
I think it would be better conceptually to pass the full list to the method rather than building it inside.

2020-08-21 08:16 UTC, gsmet commented on extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java
> +            }
You also need to check that the kind of the target is a method.

2020-08-21 08:16 UTC, gsmet commented on extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java
> +                        .add(method.name().toString());
The name is not sufficient, you need to build the signature.

2020-08-21 08:16 UTC, gsmet commented on extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/MethodValidatedAnnotationsTransformer.java
> +                        .map(methodNames -> methodNames.contains(method.name()))
Same here, you need to use the signature.

2020-08-21 08:16 UTC, gsmet commented on extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java
> +    };
I have another patch moving `ResteasyDotNames` to a common SPI so we will be able to use the constants there rather than have a copy.

2020-08-21 08:16 UTC, gsmet commented on extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/MethodValidatedAnnotationsTransformer.java
> +        return Stream.concat(Stream.of(clazz.name()), clazz.interfaceNames().stream())
Don't you also need to consider the superclasses?

2020-08-21 08:21 UTC, gsmet commented on extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java
> +                        .add(method.name().toString());
Getting the `parameters()` then building something with the `name()` of the type should be good enough.

2020-08-23 18:35 UTC, famod commented
CI has been really flaky in the last days. Latest failures don't look related.

2020-08-25 08:29 UTC, gsmet approved these changes

2020-08-25 08:30 UTC, gsmet commented
It needs some more tweaking as we discussed on Zulip but it's already a very good step in the right direction so let's merge it! Thanks!

2020-08-25 08:30 UTC, merged

2020-08-25 08:45 UTC, famod commented
Thanks for merging!

> It needs some more tweaking as we discussed on Zulip

I'll extend #11536.