Gradle: support direct file dependencies
quarkusio/quarkus pull request #11669
Opened 2020-08-27 12:44 UTC by aloubyansky

Fixes #3066

2020-08-27 13:20 UTC, gsmet requested changes, later dismissed
Spotted a small typo, please dismiss when fixed.

2020-08-27 13:20 UTC, gsmet commented on devtools/gradle/src/main/java/io/quarkus/gradle/builder/QuarkusModelBuilder.java
> +        // if the number of artifacts is less then the number of files then probably
```suggestion
        // if the number of artifacts is less than the number of files then probably
```

2020-08-27 13:31 UTC, glefloch approved these changes
LGTM

2020-08-28 06:26 UTC, aloubyansky commented
@gsmet it's waiting on you now. Thanks.

2020-08-28 17:45 UTC, gastaldi approved these changes
LGTM

2020-08-28 17:47 UTC, gastaldi commented
@aloubyansky can you rebase this PR just to make CI happy?

2020-08-31 08:03 UTC, merged