added gradle-tooling doc. splitted up the tooling into maven/gradle/cli
quarkusio/quarkus pull request #1194
Opened 2019-03-04 23:32 UTC by stalep

2019-03-05 07:28 UTC, emmanuelbernard submitted a review, later dismissed
Looks good overall. I think I preferred a single tooling doc but it would have made for a verbose solution.
The main problem is the missing CLI adoc file.

2019-03-05 11:21 UTC, gsmet requested changes
@stalep I added additional comments.

Please ping me when you applied the changes and added the CLI guide. I will review it again.

2019-03-05 21:12 UTC, gsmet submitted a review, later dismissed
@stalep even if we don't include the CLI guide tomorrow, I added a few comments. I think the most important one is the s/MICRONAUT/QUARKUS/ one.

It would be nice if you could amend the commit so that it doesn't appear in the history.

2019-03-06 06:47 UTC, starksm64 approved these changes

2019-03-06 06:50 UTC, merged