Add CDI name to named Mongo client connections
quarkusio/quarkus pull request #11998
Opened 2020-09-09 09:53 UTC by geoand

cc @lburgazzoli @squakez

2020-09-09 09:55 UTC, lburgazzoli commented
@squakez do you have time to validate this PR for camel-quarkus ?

2020-09-09 10:07 UTC, gsmet requested changes
Added some questions.

2020-09-09 10:07 UTC, gsmet commented on extensions/mongodb-client/deployment/src/test/java/io/quarkus/mongodb/DefaultAndNamedMongoClientConfigTest.java
> +        assertThat(Arc.container().instance("cluster3").get()).isNull();
If we need uniqueness for all the types across the CDI container, that won't fly. We need to qualify the name with the type.

Also we should probably provide an API util to generate the names.

2020-09-09 10:07 UTC, gsmet commented on extensions/mongodb-client/deployment/src/test/java/io/quarkus/mongodb/NamedReactiveMongoClientConfigTest.java
> +        assertThat(Arc.container().instance("cluster3reactive").get()).isNull();
Could use a separator for the `reactive` part, maybe?

2020-09-09 10:11 UTC, geoand commented
@gsmet good points, unfortunately we have already been using these names so what you suggest would break backward compatibility

2020-09-09 10:16 UTC, squakez approved these changes
Good for the "named" use cases we discussed. Tested and now the client can be retrieved just by passing the name to CDI.

2020-09-09 10:21 UTC, gsmet commented
Yeah, well, to be clear: I'm against this PR if the names are not made properly unique as it could break existing applications and make things very brittle for new ones.

And I don't understand why you say the name was already defined? It was neither set or used? Do we need it to be exactly the same as the one for `@Named`?

2020-09-09 10:24 UTC, geoand commented
> And I don't understand why you say the name was already defined? It was neither set or used? Do we need it to be exactly the same as the one for `@Named`?

I am pretty sure we do (and those names are the ones that are already used - hence my comment about backward compatibility).

Pinging @mkouba @manovotn about whether a bean's name (if specified) needs to be the same as the value of the `@Named` qualifier

2020-09-09 10:27 UTC, mkouba commented
> Pinging @mkouba @manovotn about whether a bean's name (if specified) needs to be the same as the value of the `@Named` qualifier

For class-based beans `@Named#value()` is used to specify the bean name (if not value is present then the name is defaulted)... but I'm not sure this will answer your question?

2020-09-09 10:29 UTC, geoand commented
> > Pinging @mkouba @manovotn about whether a bean's name (if specified) needs to be the same as the value of the `@Named` qualifier
> 
> For class-based beans `@Named#value()` is used to specify the bean name (if not value is present then the name is defaulted)... but I'm not sure this will answer your question?

So if `@Named("someBean")` is used, then following lookups are expected to work, correct?

```
Arc.container().instance(SomeType.class, NamedLiteral.of("someBean"));
Arc.container().instance("someBean");
```

2020-09-09 10:39 UTC, gsmet commented
Frankly, I think we need Camel/Camel Quarkus to be able to get a proper typed bean with the `NamedLiteral`.

Relying on just the name is very brittle and is a recipe for disaster IMHO.

2020-09-09 10:43 UTC, mkouba commented
> So if @Named("someBean") is used, then following lookups are expected to work, correct?

Well, both are expected to work but I haven't tested the `Arc.container().instance(SomeType.class, NamedLiteral.of("someBean"))` approach... `Named` is a special qualifier and requires special handling, e.g. if declared on a bean class it does not "remove" the `@Default` qualifier which normal qualifiers do...

2020-09-09 10:46 UTC, mkouba commented
And it seems that it does not work, debugging why...

2020-09-09 10:52 UTC, geoand commented
> UPDATE: It does not work if the bean name is defaulted, i.e. if `Named#value()` is an empty string. I'm not quite sure whether it's a bug though. @manovotn WDYT?

Yeah, I've never used it on a defaulted bean, only on beans where `@Named#value()` is set and there it works fine

2020-09-09 13:05 UTC, geoand commented
If we are going to break backward compatibility and use better names (I'm fine with that happening for 1.9, then we could go with `mongo-${name}` and `mongo-${name}-reactive`).

We would probably also want to do that for DataSource as well.

2021-02-23 13:15 UTC, geoand commented
Closing for now. We can revisit if needed

2021-02-23 13:15 UTC, closed without merging