Provides a @Blocking annotation for gRPC
quarkusio/quarkus pull request #12008
Opened 2020-09-09 13:36 UTC by cescoffier

This is a follow up of #11535.
With @Blocking the service implementation is called on a worker thread instead of an IO thread.
This support is experimental.

2020-09-09 19:49 UTC, michalszynkiewicz approved these changes

2020-09-09 21:51 UTC, stuartwdouglas requested changes
@cescoffier can we have some common @Blocking and @NonBlocking quarkus annotation, and have everything re-use the same ones? I think it will get super confusing if every extension ends up defining its own, users will accidentally import the wrong ones if there are multiple on the ClassPath.

2020-09-10 07:23 UTC, cescoffier commented
@stuartwdouglas Reactive Messaging already has its own. So, while we can have global ones, there will be at least 2. Note that the attributes may differ too. The reactive messaging one has one (optional) attribute, this one does not. 

So, let's create common ones - with no attribute. gRPC can use it.
For reactive messaging, we would need to update the extension to support both. 

Maybe we need to also add support for this new "global" one in reactive routes, which right now has a `blocking` attribute.

2020-09-10 08:11 UTC, stuartwdouglas commented
If we do non-blocking JAX-RS we will likely need one there as well, and websockets could also use one (at the moment this is a global setting, but there will likely be demand for it at some point).

I think we should add a global one and attempt to unify on it early. 

Also I am not sure if we should go with @Blocking as the name, different frameworks may have different defaults. Maybe something like @WorkerThread(true)/@WorkerThread(false).

2020-09-10 08:45 UTC, cescoffier commented
`@RunOnWorkerThread(true/false)` maybe? 

I actually prefer `RunOnWorkerThread` to `Blocking`, as you may be non-blocking and still want to run on a worker thread (for whatever reason).

2020-09-30 16:07 UTC, cescoffier commented
Closing in favor of #12418

2020-09-30 16:07 UTC, closed without merging