Add a hint to OIDC and Hibernate Multitenancy docs about passing a tenant id
quarkusio/quarkus pull request #12014
Opened 2020-09-09 17:51 UTC by sberyozkin

Fixes #11949. 

This PR updates OIDC and Hibernate Multitenancy docs to suggest a simple way of passing a tenant id across 2 resolvers. This can be very obvious anyway, but adding this hint won't harm as 1) some users may be copy-pasting from the docs and may not realize `RoutingContext` can be used as a medium to pass this id around. 2) Highlights that both OIDC and Hibernate multitenancy can work in tandem

2020-09-10 20:34 UTC, gsmet requested changes
Spotted a few typos, case issues. Nice addition otherwise.

2020-09-10 20:34 UTC, gsmet commented on docs/src/main/asciidoc/hibernate-orm.adoc
> +If you also use link:security-openid-connect-multitenancy[OIDC MultiTenancy] and both OIDC and Hibernate tenant IDs are the same and must be extracted from the Vertx `RoutingContext` then you can pas
```suggestion
If you also use link:security-openid-connect-multitenancy[OIDC multitenancy] and both OIDC and Hibernate ORM tenant IDs are the same and must be extracted from the Vert.x `RoutingContext` then you can pass the tenant id from the OIDC Tenant Resolver to the Hibernate ORM Tenant Resolver as a `RoutingContext` attribute, for example:
```

2020-09-10 20:34 UTC, gsmet commented on docs/src/main/asciidoc/security-openid-connect-multitenancy.adoc
> +If you also use link:hibernate-orm#multitenancy[Hibernate MultiTenancy] and both OIDC and Hibernate tenant IDs are the same and must be extracted from the Vertx `RoutingContext` then you can pass the
```suggestion
If you also use link:hibernate-orm#multitenancy[Hibernate ORM multitenancy] and both OIDC and Hibernate ORM tenant IDs are the same and must be extracted from the Vert.x `RoutingContext` then you can pass the tenant id from the OIDC Tenant Resolver to the Hibernate ORM Tenant Resolver as a `RoutingContext` attribute, for example:
```

2020-09-11 09:30 UTC, sberyozkin commented
@gsmet thanks, committed the suggestions

2020-09-11 14:50 UTC, sberyozkin commented
Squashing now...

2020-09-12 12:13 UTC, gsmet approved these changes

2020-09-12 12:13 UTC, merged