More security documentation updates
quarkusio/quarkus pull request #12032
Opened 2020-09-10 17:51 UTC by sberyozkin

This PR:
- updates the main `security.adoc` page with references to HTTP `SSL`, `CORS` and `Running behind a reverse proxy` guides
- updates `Running behind a reverse proxy` section to use the new property names.

2020-09-10 18:10 UTC, gastaldi commented on docs/src/main/asciidoc/security-openid-connect-web-authentication.adoc
> +`quarkus.oidc.authentication.force-redirect-https-scheme` property may also be used when the Quarkus application is running behind an SSL terminating reverse proxy.
```suggestion
`quarkus.oidc.authentication.force-redirect-https-scheme` property may also be used when the Quarkus application is running behind a SSL terminating reverse proxy.
```

2020-09-10 18:11 UTC, gastaldi approved these changes
LGTM, found a minor typo

2020-09-10 20:24 UTC, gsmet requested changes
Nice work @sberyozkin . I just spotted two small typos.

2020-09-10 20:24 UTC, gsmet commented on docs/src/main/asciidoc/security-openid-connect-web-authentication.adoc
> +In such cases configuring Quarkus to recognize the original headers forwarded by the proxy will be required, see link:vertx#reverse-proxy[Running behind a reverse proxy] Vertx documentation section f
```suggestion
In such cases configuring Quarkus to recognize the original headers forwarded by the proxy will be required, see link:vertx#reverse-proxy[Running behind a reverse proxy] Vert.x documentation section for more information.
```

2020-09-10 20:24 UTC, gsmet commented on docs/src/main/asciidoc/security.adoc
> +See link:http-reference#ssl[Supporting secure connections with SSL] guide for more information.
```suggestion
See the link:http-reference#ssl[Supporting secure connections with SSL] guide for more information.
```

2020-09-11 09:33 UTC, sberyozkin commented
Hi @gastaldi @gsmet thanks, I'll certainly remember now that `Vertx` is not correct and it should be `Vert.x` :-)

2020-09-11 13:09 UTC, gsmet commented
@sberyozkin could you squash the commits?

2020-09-11 14:49 UTC, sberyozkin commented
@gsmet sure, sorry, missed your ping

2020-09-11 15:55 UTC, gsmet approved these changes

2020-09-11 15:55 UTC, merged