Allow configuring the RestAssured timeouts and provide sensible defaults.
quarkusio/quarkus pull request #12127
Opened 2020-09-16 09:17 UTC by cescoffier

At the moment, we do not configure the RestAssured timeout. ﻿As a consequence, some test can  _wait_ up to 45 minutes before failing.

This PR configures the timeout to 30 seconds and allows provide a way to the user to configure them from the application properties.

2020-09-16 09:19 UTC, cescoffier commented
CC @galderz

2020-09-16 10:45 UTC, stuartwdouglas approved these changes

2020-09-16 11:19 UTC, machi1990 reviewed
Should we add something like: 

https://github.com/quarkusio/quarkus/blob/23e1543d2201bafe63574feccbcaf3f5c4716bdf/core/runtime/src/main/java/io/quarkus/runtime/CommandLineRuntimeConfig.java#L10

To avoid warnings when `quarkus.http.test-timeout` is used?

2020-09-16 20:01 UTC, gsmet requested changes
Added a small suggestion for the doc.

2020-09-16 20:01 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-testing.adoc
> +When using RestAssured in your test, a connection and response timeout are set to 30s.
```suggestion
When using REST Assured in your test, the connection and response timeouts are set to 30 seconds.
```

2020-09-17 08:08 UTC, cescoffier commented
Thanks @gsmet, merged, and rebased.

2020-09-17 13:13 UTC, gsmet approved these changes

2020-09-17 13:13 UTC, merged

2020-09-23 04:43 UTC, galderz commented
Thx @cescoffier! 👍