Allow a different binary when running docker
quarkusio/quarkus pull request #12157
Opened 2020-09-17 05:28 UTC by geoand

This would be the first simple step to supporting podman

Fixes: #12135

2020-09-17 11:21 UTC, gsmet submitted a review, later dismissed
I'm approving just to test something, will remove my approval afterwards.

2020-09-17 12:12 UTC, maxandersen requested changes

2020-09-17 12:13 UTC, geoand commented on extensions/container-image/container-image-docker/deployment/src/main/java/io/quarkus/container/image/docker/deployment/DockerConfig.java
> +    public String binaryName;
Good point. I'll go with the later suggestion

2020-09-21 06:48 UTC, geoand commented
@maxandersen are you OK with this now?

2020-09-21 07:11 UTC, maxandersen approved these changes
All good.

2020-09-21 07:18 UTC, merged