Micrometer Vert.x HTTP request propagation
quarkusio/quarkus pull request #12180
Opened 2020-09-18 01:26 UTC by ebullient

2020-09-18 15:06 UTC, kenfinnigan requested changes

2020-09-18 15:06 UTC, kenfinnigan commented on extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/vertx/VertxHttpServerMetrics.java
> +        RequestMetric metricContext = new RequestMetric();
Am I correct in saying `metricContext` just returns a new `RequestMetric` that isn't hooked into anything? Could the method just return a new instance?

2020-09-18 15:06 UTC, kenfinnigan commented on extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/vertx/VertxHttpServerMetrics.java
> +        RequestMetric metricContext = new RequestMetric();
Should this be using `retrieveRequestMetric` ?

2020-09-18 15:21 UTC, ebullient commented on extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/vertx/VertxHttpServerMetrics.java
> +        RequestMetric metricContext = new RequestMetric();
you are correct in that it creates and returns a RequestMetric ... but Vertx uses that returned object for later things. In the case of push, that's HTTP2/Stream, and it is difficult to follow where that is used.

Note that any of the objects passed to/from these methods aren't interpreted by Vert.x .. it just takes them, and passes them back later. The responsePushed callback is especially weird re: parameters. 

setRequestMetric/retrieveRequestMetric are specific to synchronous requests that go through handlers to work around a disconnect between the HttpServerRequest and the RoutingContext. HttpServerRequest has no storage in it, and requestBegin is called before the response is created (which is where cookies are stored.. ), so you can't even cheat and use cookies to pass the RequestMetric along to have RoutingContext added to it. As @stuartwdouglas says (quoted in javadoc): YUCK.

2020-09-18 17:11 UTC, kenfinnigan approved these changes

2020-09-19 11:42 UTC, stuartwdouglas approved these changes

2020-09-19 11:42 UTC, merged