Adds new property to configure "hibernate.format_sql" in the application.properties
quarkusio/quarkus pull request #12206
Opened 2020-09-19 09:37 UTC by dfbadawi

`quarkus.hibernate-orm.log.formatted-sql=false`

This allows to configure hibernate's `hibernate.format_sql` property in the application.properties.

Fixes: #12204

2020-09-19 09:57 UTC, gsmet requested changes
Thanks! I added some suggestions.

2020-09-19 09:57 UTC, gsmet commented on extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfigPersistenceUnit.java
> +        public Optional<Boolean> formattedSql;
```suggestion
        @ConfigItem(defaultValue = "true")
        public boolean formatSql;
```

2020-09-19 09:57 UTC, gsmet commented on extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java
> +            descriptor.getProperties().setProperty(AvailableSettings.FORMAT_SQL, formattedSql.toString());
This will need to be adjusted in respect to the other change I suggested.

2020-09-19 09:57 UTC, gsmet commented on extensions/hibernate-orm/deployment/src/test/resources/application-log-sql-formatted.properties
> +quarkus.hibernate-orm.log.formatted-sql=false
Same here.

2020-09-19 09:57 UTC, gsmet commented on extensions/hibernate-reactive/deployment/src/main/java/io/quarkus/hibernate/reactive/deployment/HibernateReactiveProcessor.java
> +            desc.getProperties().setProperty(AvailableSettings.FORMAT_SQL, formattedSql.toString());
Same here.

2020-09-19 09:57 UTC, gsmet commented on extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfigPersistenceUnit.java
> +
It needs to be taked into account in `isAnyPropertySet`.

2020-09-19 10:27 UTC, dfbadawi commented
@gsmet suggestions applied :)

2020-09-30 14:29 UTC, gsmet approved these changes
Thanks! I squashed everything and will wait for CI to merge.

2020-10-01 13:44 UTC, merged

2020-10-01 13:44 UTC, gsmet commented
Merged, thanks!

2020-10-01 14:09 UTC, Sanne commented
thanks!