Adding an IAM Amazon-service extension
quarkusio/quarkus pull request #12372
Opened 2020-09-28 09:33 UTC by oscerd

2020-09-29 06:28 UTC, gsmet requested changes
Spotted a small issue.

@marcinczeczko could you have a look at this one?

2020-09-29 06:28 UTC, gsmet commented on docs/src/main/asciidoc/amazon-iam.adoc
> +include::{generated-dir}/config/quarkus-amazon-sqs.adoc[opts=optional, leveloffset=+1]
This is incorrect.

2020-09-29 06:32 UTC, oscerd commented on docs/src/main/asciidoc/amazon-iam.adoc
> +include::{generated-dir}/config/quarkus-amazon-sqs.adoc[opts=optional, leveloffset=+1]
Yeah, I'll update.

2020-09-29 06:37 UTC, oscerd commented on docs/src/main/asciidoc/amazon-iam.adoc
> +include::{generated-dir}/config/quarkus-amazon-sqs.adoc[opts=optional, leveloffset=+1]
It should be ok now.

2020-09-29 09:17 UTC, sberyozkin commented
@oscerd is it related to #10663 ? Thanks

2020-09-29 09:20 UTC, oscerd commented
@sberyozkin no, it's a different service. 

https://aws.amazon.com/iam/?nc1=h_ls
https://aws.amazon.com/secrets-manager/?nc1=h_ls

2020-10-06 13:32 UTC, oscerd commented
Any feedback on this?

2020-10-06 13:38 UTC, marcinczeczko commented
From my perspective it looks fine.

2020-10-07 18:37 UTC, oscerd commented
I think this should be ok to merge

2020-10-08 10:37 UTC, sberyozkin commented
@oscerd Hi, a quick question, how does it sync with the current authenticated Quarkus user ? I.e, can anyone who has authenticated call IAM ? thanks

2020-10-08 10:43 UTC, oscerd commented
> @oscerd Hi, a quick question, how does it sync with the current authenticated Quarkus user ? I.e, can anyone who has authenticated call IAM ? thanks

Authenticated to AWS? What do you mean with authenticated Quarkus user? Thanks

2020-10-08 11:01 UTC, sberyozkin commented
> Authenticated to AWS? What do you mean with authenticated Quarkus user? Thanks

No, the user who has authenticated to the Quarkus endpoint (via Basic Auth or OIDC) which makes an outbound call to AWS IAM.
For example, what if a user access a Quarkus endpoint after authenticating via AWS SSO (I haven't tried but `quarkus-oidc` would handle it).

2020-10-08 11:04 UTC, oscerd commented
You'll always need to use the AWS credentials to interact with IAM service.
The IAM exposed API are for management, so you can create a user or add a
group etc

Il gio 8 ott 2020, 13:02 sberyozkin <notifications@github.com> ha scritto:

> Authenticated to AWS? What do you mean with authenticated Quarkus user?
> Thanks
>
> No, the user who has authenticated to the Quarkus endpoint (via Basic Auth
> or OIDC) which makes an outbound call to AWS IAM.
> For example, what if a user access a Quarkus endpoint after authenticating
> via AWS SSO (I haven't tried but quarkus-oidc would handle it).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/quarkusio/quarkus/pull/12372#issuecomment-705495419>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABG6XVZMZWKDO44MOIVNUXLSJWL27ANCNFSM4R4I2JOQ>
> .
>

2020-10-08 11:07 UTC, oscerd commented
So you won't authenticated through it. It's just an exposed API for doing stuff related to the IAM service

2020-10-08 11:16 UTC, sberyozkin commented
@oscerd 
> So you won't authenticated through it. It's just an exposed API for doing stuff related to the IAM service
I understand, thanks, the question was, can any authenticated Quarkus user access this IAM service :-) ?

2020-10-08 11:17 UTC, oscerd commented
I think so.

2020-10-08 11:21 UTC, sberyozkin commented
@oscerd Thanks, yeah, that looks similar to a service account approach with Google Cloud services which Loic is working upon.

That is fine, going forward, if it is possible with IAM, we can link AWS SSO + IAM with `quarkus-oidc` (something which is also proposed for the Google services), so only the users who authenticate into Quarkus via AWS SSO can invoke. Ping us please if it will be of interest

2020-10-08 11:26 UTC, sberyozkin approved these changes
LGTM, but waiting for Guillaume to double check as well

2020-10-08 11:33 UTC, sberyozkin commented
@oscerd Please squash the commits

2020-10-08 11:57 UTC, oscerd commented
@sberyozkin done

2020-10-09 12:10 UTC, sberyozkin commented
@oscerd thanks, waiting for @gsmet to confirm the requested change looks good for him.
In meantime, please also rebase and force push as Stuart has done some fixes to do with timeouts (JDK8 build is failing here)

2020-10-09 12:15 UTC, gsmet approved these changes

2020-10-09 12:15 UTC, merged