Create Logging JSON Codestart
quarkusio/quarkus pull request #12386
Opened 2020-09-29 05:14 UTC by jantosi

2020-09-30 14:12 UTC, gsmet commented
/cc @ia3andy

2020-10-01 14:07 UTC, ia3andy requested changes
You can't use `application.properties`, you need to use `application.yml`, I described why in the doc: https://github.com/quarkusio/quarkus/blob/master/independent-projects/tools/codestarts/README.adoc#tips-for-writing-extension-example-code

Comments are going to be ignored, so I suggest you to document those configuration keys in the readme instead :)

2020-10-05 09:46 UTC, ia3andy requested changes

2020-10-05 09:46 UTC, ia3andy commented on devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/examples/logging-json/codestart.yml
> +      - io.quarkus:quarkus-logging-json
```suggestion
      - io.quarkus:quarkus-resteasy
      - io.quarkus:quarkus-logging-json
```

2020-10-05 09:46 UTC, ia3andy commented on devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/examples/logging-json/codestart.yml
> +      - io.quarkus:quarkus-logging-json
This should fix the test which are not passing.

2020-10-07 10:52 UTC, gsmet submitted a review, later dismissed
The history needs to be cleaned up.

2020-10-10 07:31 UTC, ia3andy requested changes

2020-10-10 07:31 UTC, ia3andy commented on integration-tests/devtools/src/test/java/io/quarkus/devtools/codestarts/QuarkusCodestartRunSingleIT.java
> +class QuarkusCodestartRunSingleIT extends PlatformAwareTestBase {
You can remove that class, your codestart is already automatically tested by the  `QuarkusCodestartRunIT`. I am currently creating a tool to easily generate a codestart in development which will remove the need of using the tests for this..

2020-10-12 07:07 UTC, ia3andy approved these changes
🚀

2020-10-12 07:08 UTC, merged