Avoid copying sources directly in the source cache
quarkusio/quarkus pull request #12405
Opened 2020-09-29 21:04 UTC by zakkak

This has the following benefits:
1. Quarkus code doesn't make any assumptions about the source-cache
structure or its name. Previously it assumed that the source-cache is
called sources and it contains a subfolder src with the applicatino
sources, which no longer holds for Mandrel 20.1.0.2 and won't hold for
GraalVM CE 20.3+.
2. The source-cache doesn't need to contain all the source files of the
application, only the ones being referenced by the debug info. As a
result, letting Graal construct the source cache we might end up with
less files in the source-cache.

cc: @Karm @galderz @rsvoboda

2020-10-01 06:47 UTC, rsvoboda commented
> which no longer holds for Mandrel 20.1.0.2 and won't hold for GraalVM CE 20.3+.

@zakkak So the fix which went into 1.7 is not proper fix as it won't work with latest public Mandrel?
https://github.com/quarkusio/quarkus/commit/8fec64bcdfafc3b9abdb7932e9ca1b76eb05ac32

2020-10-01 07:15 UTC, rsvoboda commented
Ah, there is https://issues.redhat.com/browse/QUARKUS-453 with details about this

2020-10-01 07:31 UTC, rsvoboda requested changes
https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/building-native-image.adoc#debugging-native-executable needs update



`The location of source cache is target/{project.name}-{project.version}-native-image-source-jar/sources folder.` is no longer valid with this PR in mind

2020-10-01 12:25 UTC, zakkak commented
> https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/building-native-image.adoc#debugging-native-executable needs update
> 
> `The location of source cache is target/{project.name}-{project.version}-native-image-source-jar/sources folder.` is no longer valid with this PR in mind

No, the source cache will still be in `target/{project.name}-{project.version}-native-image-source-jar/sources`.
This PR creates `target/{project.name}-{project.version}-native-image-source-jar/app-sources` at build time. `native-image` uses this folder to access the application sources and copy the reachable ones to `target/{project.name}-{project.version}-native-image-source-jar/sources` which is then used by `gdb`.
After `native-image` completes `target/{project.name}-{project.version}-native-image-source-jar/app-sources` gets removed and we only keep `target/{project.name}-{project.version}-native-image-source-jar/sources`

2020-10-01 12:29 UTC, zakkak commented
> > which no longer holds for Mandrel 20.1.0.2 and won't hold for GraalVM CE 20.3+.
> 
> @zakkak So the fix ([8fec64b](https://github.com/quarkusio/quarkus/commit/8fec64bcdfafc3b9abdb7932e9ca1b76eb05ac32)) which went into 1.7 is not proper fix as it won't work with the latest public Mandrel?

FTR (since https://issues.redhat.com/browse/QUARKUS-453 is internal) it will still work but requires an extra step to let `gdb` know that it should look into `sources/src` in addition to `sources`.

2020-10-01 14:26 UTC, rsvoboda approved these changes

2020-10-01 14:27 UTC, rsvoboda commented
@zakkak thanks for explanation, PR approved

2020-10-05 06:18 UTC, galderz approved these changes

2020-10-06 09:30 UTC, merged