support liquibase changelog parameters
quarkusio/quarkus pull request #12502
Opened 2020-10-04 10:29 UTC by tisoft

Adds support for setting [liquibase changelog parameters](https://docs.liquibase.com/concepts/basic/changelog-parameters.html).

Usage in `application.properties`:

```
quarkus.liquibase.params."table.prefix"=MY_CUSTOM_PREFIX
quarkus.liquibase.params.someParam=Some Value
```

Would replace the expressions `${table.prefix}` and `${someParam}` with the given values inside the liquibase changelog.

2020-10-04 10:38 UTC, tisoft commented
Usage example:

Using this changelog:

```
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd">

    <property name="table.prefix" value=""/>

    <changeSet author="dev (generated)" id="id-1">
        <createTable tableName="${table.prefix}TEST">
            <column name="ID" type="VARCHAR(255)">
                <constraints nullable="false"/>
            </column>
            <column name="NAME" type="VARCHAR(255)"/>
        </createTable>
    </changeSet>

</databaseChangeLog>

```

together with a custom hibernate naming strategy:

```
import org.eclipse.microprofile.config.ConfigProvider;
import org.hibernate.boot.model.naming.Identifier;
import org.hibernate.boot.model.naming.PhysicalNamingStrategy;
import org.hibernate.engine.jdbc.env.spi.JdbcEnvironment;

public class PrefixNamingStrategy implements PhysicalNamingStrategy {

   private final String tablePrefix;

   public PrefixNamingStrategy () {
      this.tablePrefix = ConfigProvider.getConfig ().getValue ("table.prefix", String.class);
   }

   @Override
   public Identifier toPhysicalCatalogName (Identifier name, JdbcEnvironment jdbcEnvironment) {
      return name;
   }

   @Override
   public Identifier toPhysicalSchemaName (Identifier name, JdbcEnvironment jdbcEnvironment) {
      return name;
   }

   @Override
   public Identifier toPhysicalTableName (Identifier name, JdbcEnvironment jdbcEnvironment) {
      return Identifier.toIdentifier (tablePrefix + name.getText (), name.isQuoted ());
   }

   @Override
   public Identifier toPhysicalSequenceName (Identifier name, JdbcEnvironment jdbcEnvironment) {
      return Identifier.toIdentifier (tablePrefix + name.getText (), name.isQuoted ());
   }

   @Override
   public Identifier toPhysicalColumnName (Identifier name, JdbcEnvironment jdbcEnvironment) {
      return name;
   }
}
```

and the following config:

```
table.prefix=FC_
quarkus.liquibase.database-change-log-lock-table-name=${table.prefix}DATABASECHANGELOGLOCK
quarkus.liquibase.database-change-log-table-name=${table.prefix}DATABASECHANGELOG
quarkus.liquibase.params."table.prefix"=${table.prefix}

quarkus.hibernate-orm.physical-naming-strategy=PrefixNamingStrategy
```

allows me to have a custom table prefix.

I do need this, since my application uses a shared database, and there are overlaps in table names with another application.

2020-10-06 08:54 UTC, gsmet requested changes
Interesting, thanks! I added some minor comments.

2020-10-06 08:54 UTC, gsmet commented on extensions/liquibase/runtime/src/main/java/io/quarkus/liquibase/runtime/LiquibaseDataSourceRuntimeConfig.java
> +    public Map<String, String> params = new HashMap<>();
I would make it `changelogParameters`. `params` is too generic.

2020-10-06 08:54 UTC, gsmet commented on extensions/liquibase/runtime/src/main/java/io/quarkus/liquibase/LiquibaseFactory.java
> +                config.params.forEach((k, v) -> liquibase.getChangeLogParameters().set(k, v));
We avoid lambdas in runtime code as they have a cost.

The map should never be null.

2020-10-06 19:32 UTC, famod commented
/cc @andrejpetras

2020-10-07 10:27 UTC, gsmet commented
I'm closing this PR as it shouldn't target 1.8 but master.

I will move the commit to a new PR targeting master and adjust a few things. I will ping you in the PR so you can check that things are ok for you.

2020-10-07 10:27 UTC, closed without merging