Change default media type to JSON
quarkusio/quarkus pull request #12566
Opened 2020-10-06 23:13 UTC by stuartwdouglas

This adds a new RESTEasy provider that will produce
JSON by default. This removes the need to add
@Produces(MediaType.APPLICATION_JSON) and
@Consumes(MediaType.APPLICATION_JSON) everywhere.

The old behaviour can be retained by setting:

quarkus.resteasy-json.default-json=false

in application.properties.

2020-10-07 13:48 UTC, FroMage approved these changes
Great idea!

2020-10-08 06:30 UTC, Ladicek commented on docs/src/main/asciidoc/rest-json.adoc
> +If you don't want JSON my default you can set `quarkus.resteasy-json.default-json=false` and the default will change back to `application/octet-stream`. If you set this
```suggestion
If you don't want JSON by default you can set `quarkus.resteasy-json.default-json=false` and the default will change back to `application/octet-stream`. If you set this
```

2020-10-12 14:46 UTC, gsmet requested changes, later dismissed
Looks like I forgot to post my review... You added the Jackson impl so that's one less thing to add but there are still a few details that needs fixing.

I can do it if you have better things to do, just ping me!

2020-10-12 14:46 UTC, gsmet commented on extensions/resteasy-jsonb/runtime/src/main/java/io/quarkus/resteasy/jsonb/QuarkusJSONBSerializer.java
> +package io.quarkus.resteasy.jsonb;
And same for the Jackson one.

2020-10-13 00:13 UTC, stuartwdouglas commented
Done

2020-10-13 20:10 UTC, gastaldi approved these changes

2020-10-13 20:11 UTC, merged

2020-10-14 03:17 UTC, gastaldi commented
@stuartwdouglas apparently this PR does not support this:

```java
    @GET
    public Map<String,String> hello() {
        Map<String,String> t = new HashMap<>();
        t.put("Hey", "Ho");
        return t;
    }
```

I get the following error while hitting the endpoint: 
```
2020-10-14 00:15:35,726 ERROR [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002005: Failed executing GET /greeting: org.jboss.resteasy.core.NoMessageBodyWriterFoundFailure: Could not find MessageBodyWriter for response object of type: java.util.HashMap of media type: application/octet-stream
	at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$3(ServerResponseWriter.java:125)
	at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:404)
	at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:594)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:131)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

```

2020-10-14 03:18 UTC, gastaldi commented
I created https://github.com/quarkusio/quarkus/issues/12701

2020-10-14 03:28 UTC, gastaldi commented
Ignore it, I forgot to add `quarkus-resteasy-jackson` to my sample project