Support additional JDBC properties for a DataSource
quarkusio/quarkus pull request #12639
Opened 2020-10-09 18:54 UTC by gastaldi

Some environments use these properties for additional metadata (eg. in Google CloudSQL)

Closes #6634

2020-10-10 08:25 UTC, loicmathieu approved these changes
LGTM

2020-10-10 09:08 UTC, gsmet requested changes, later dismissed
Looks good to me except for a very minor nitpick.

2020-10-10 09:08 UTC, gsmet commented on extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSourceJdbcRuntimeConfig.java
> +     * Other unspecified properties to be passed into the JDBC driver when creating new connections
```suggestion
     * Other unspecified properties to be passed to the JDBC driver when creating new connections.
```

2020-10-11 13:32 UTC, Sanne commented
LGTM, thanks!

2020-10-12 01:30 UTC, merged

2020-10-16 01:47 UTC, binojvr commented
Any update on when this will be available

2020-10-16 01:58 UTC, gastaldi commented
It's available in 1.9.0.Final (to be announced soon)