Add an @Managed scope
quarkusio/quarkus pull request #12650
Opened 2020-10-12 03:36 UTC by stuartwdouglas

This scope is essentually stateless, and allows for
injectable objects that don't exactly match the built
in scopes.

2020-10-12 05:24 UTC, gastaldi commented on docs/src/main/asciidoc/cdi-reference.adoc
> +This allows you to create injectable objects that have a lifecycle that does not match the existing build in scopes.
```suggestion
This allows you to create injectable objects that have a lifecycle that does not match the existing built-in scopes.
```

2020-10-12 05:26 UTC, gastaldi commented on docs/src/main/asciidoc/cdi-reference.adoc
> +allows you to have another object manage the bean lifecycle. Every time the bean is invoked upon the relevant producer
```suggestion
allows you to have another object manage the bean lifecycle. Every time the bean is invoked, the relevant producer
```

2020-10-12 06:29 UTC, stuartwdouglas commented
There are a few different uses for this:
- We could replace our EntityManager proxy with an @Managed scope bean (at the moment there is a non-CDI proxy that is used to emulate this)
- Injection of the current user, this is not actually request scoped as the user can potentially change if a login is performed, or if you do some kind of RunAs operation. At the moment the Principal that is injected is also a manually created proxy.
- If we want to allow injection of JAX-RS @Context object this can be used to select the correct object (RequestScoped is not correct here, as when using the client the objects should refer to the current client request, not the server request).

I also just think

2020-10-12 07:39 UTC, FroMage commented
> I also just think

The suspense is killing me

2020-10-12 07:41 UTC, FroMage approved these changes
That looks useful indeed, but let's wait for @mkouba 's review.

2020-10-12 08:07 UTC, mkouba commented
I think that the ida is OK and I can understand that it might be very useful for some specific use cases. However, there are few drawbacks:

1. The name is confusing because the injection site does not manage anything. The bean has effectively "no scope"; it's more something like a pass-through proxy, delegating all invocations to some non-contextual instace. The name could be also confused with `@javax.annotation.ManagedBean`.
2. Scope only applicable to producers is something very non-standard and might confuse regular CDI users a lot; not to mention that you don't validate the usage, so for example synthetic beans could try to use it (which can be useful but should be documented).
3. `@Managed` is a normal scope and requires client proxies but it does not align with the [spec definition](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#normal_scope). Again, something we can live with but another non-standard behavior for "old-school" CDI users.
4. If you declare such a producer on a `@Dependent` bean you'll end up with very poor performance and massive allocations if used in a hot path (we should at least log a warning or something like that)

So I think that we should:

- rename the scope annotation (maybe something like `@PassThrough`; we should try to avoid using "delegating" in the name because of `@javax.decorator.Delegate`)
- remove the `@NormalScope` -> make it a pseudo-scope
- log a warning for declaring `@Dependent` bean
- fail for existing disposer methods
- add some example to the javadoc

CC @manovotn

2020-10-12 08:10 UTC, mkouba requested changes
See https://github.com/quarkusio/quarkus/pull/12650#issuecomment-706954868

2020-10-12 08:54 UTC, manovotn requested changes
I get the idea and the usage we want this for and I am +1 for it. However, we need to align it with spec at least to whatever degree it's possible. Here' what I think we should do:

* Add validation - eager failure when used elsewhere than producers (not sure if we want this on synth beans?) and also fail if you find a disposer method for it
* Make it pseudo-scope + proxied - this let's us avoid limitations on normal scope
* We need different name for the annotation to avoid confusion - `@PassThrough` or `@NoState` would both be fine I think. Alternatively, we could append the name with `Scope` suffix too.

The ability to use the scope on producers only will remain non-standard but something we can live with given that we document and validate it properly.
Strictly speaking, the specification doesn't like the notion of [pseudo-scope + proxy either](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#normal_scope), however I would still argue that pseudo + proxy is better than normal scoped for this case.

2020-10-13 22:32 UTC, stuartwdouglas commented
- I don't think any CDI users really care about the strict definition of a normal scope. Technically @TransactionScoped also does not meet the requirements as the spec says "per thread" which is kinda silly. For most users if they know at all they would think 'normal scoped' == proxy, 'pseudo scope' == no proxy. I also don't want to have to mess around adding support for proxied pseusdo scopes. 

- Synthetic beans are fine. You can't use it on a class because it is only allowed on methods or fields

I am not sure about the name, I went for @Managed as the life cycle is managed by another object. I also like @Stateless but there is too much baggage from EJB.

@CustomScoped maybe.

2020-10-14 06:32 UTC, mkouba commented
> @CustomScoped maybe.

Any scope that is not built-in is usually called "custom scope" in CDI lingo. Yes, `@Stateless` would be a good match but EJB :-(. Maybe something like `@Transitive` or `@TransientScoped` or `@TemporaryScoped`?

2020-10-14 07:22 UTC, Ladicek commented
When I see "managed", I think "container-managed". This is "managed manually" it seems?

2020-10-14 07:44 UTC, mkouba commented
> When I see "managed", I think "container-managed". This is "managed manually" it seems?

The thing is that you don't "manage" anything, you only "trigger Contextual#create()" every time a method is invoked upon the proxy.

2020-10-14 07:50 UTC, stuartwdouglas commented
The class containing the producer manages the lifecycle of the object, which is why I picked that name

2020-10-14 08:16 UTC, mkouba commented
> The class containing the producer manages the lifecycle of the object, which is why I picked that name

I see. It's still confusing though. Anyway, there are points other than name that need to be addressed...

2020-10-29 13:18 UTC, Ladicek commented
I just got an idea -- you say that the producer manages the lifecycle of the object, so why not `@ProducerScoped`? (I can also think of `@ProducerBound` or `@ProducerManaged`, but the idea is to put the producer front and center.)

2020-11-17 23:35 UTC, stuartwdouglas commented
We did not end up needing this in Quarkus REST, and we don't seem to be able to decide on a name so I am just going to close this for now.

2020-11-17 23:35 UTC, closed without merging