Inject any number of gRPC stubs per configured client
quarkusio/quarkus pull request #12793
Opened 2020-10-19 14:14 UTC by djnalluri

There is currently a limit of injecting a single blocking stub class and one Mutiny stub class per configured gRPC channel/client across an entire application. This PR removes the limitation and allows the injection of any number of stub classes.

2020-10-20 06:18 UTC, cescoffier requested changes
It looks good to me. Could you add a test checking that we can inject multiple stubs in multiple beans?

2020-10-20 18:55 UTC, djnalluri commented
I tweaked the existing test for multiple injection to include a new service on the same channel. I also edited the original comment to better describe the problem as it may have been poorly worded.

2020-10-21 06:36 UTC, cescoffier approved these changes

2020-10-21 06:36 UTC, cescoffier commented on extensions/grpc/deployment/src/test/java/io/quarkus/grpc/client/MutipleStubsInjectionTest.java
> +                            HelloReplyOrBuilder.class, HelloRequestOrBuilder.class,
FYI (and I found it recently), you can use `.addPackage(HelloService.class.getPackage())`, which avoid a long list of classes (not something to change)

2020-10-21 06:37 UTC, cescoffier commented
LGTM, thanks! 

I've relaunched the CI build.

2020-10-21 14:59 UTC, merged