fix: catch and log when project and container image info can't be cre…
quarkusio/quarkus pull request #12865
Opened 2020-10-21 18:32 UTC by iocanel

…ated.

Fixes: 12858

2020-10-21 18:50 UTC, gastaldi commented
Build failed with:

```
 File '/home/runner/work/quarkus/quarkus/extensions/container-image/deployment/src/main/java/io/quarkus/container/image/deployment/ContainerImageProcessor.java' has not been previously formatted.  Please format file and commit before running validation!
```

2020-10-23 10:13 UTC, gsmet requested changes, later dismissed
Spotted a typo in a constant name.

2020-10-23 10:13 UTC, gsmet commented on extensions/container-image/deployment/src/main/java/io/quarkus/container/image/deployment/ContainerImageProcessor.java
> +    private static final String UNKNONW_USER = "?";
```suggestion
    private static final String UNKNOWN_USER = "?";
```

2020-10-23 10:48 UTC, iocanel commented
> Spotted a typo in a constant name.

Thanks for spotting it

2020-10-26 08:49 UTC, aloubyansky commented
@iocanel the CI failed to compile
```
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/home/runner/work/quarkus/quarkus/extensions/container-image/deployment/src/main/java/io/quarkus/container/image/deployment/ContainerImageProcessor.java:[39,13] cannot find symbol
  symbol:   variable UNKNONW_USER
  location: class io.quarkus.container.image.deployment.ContainerImageProcessor
```

2020-10-26 09:29 UTC, aloubyansky commented
I was just able to compile it locally and it does fix my issue.

2020-10-26 09:30 UTC, aloubyansky approved these changes

2020-10-26 09:31 UTC, aloubyansky commented
@gsmet could review it again please? Thanks.

2020-10-27 10:08 UTC, merged