Add RuntimeInitializedPackageBuildItem
quarkusio/quarkus pull request #12995
Opened 2020-10-27 23:24 UTC by zachgk

Some packages have too many classes to runtime initialize to be practical to list. This exposes the package runtime initialization to extension developers through a `BuildItem` in addition to the configuration.

2020-10-28 09:38 UTC, gsmet requested changes
Makes totally sense and looks handy, thanks!

Could you make use of it here: https://github.com/quarkusio/quarkus/tree/master/core/test-extension ?

I would create a new package in the runtime part of the extension and use it.

I don't think we need to test the result of it but just be sure the generated code is exercised somewhere.

Thanks!

2020-10-28 11:58 UTC, sberyozkin commented
It should help with the BC runtime initialization, etc, nice

2020-10-28 12:32 UTC, dmlloyd commented
The code looks OK.  I'd be a little concerned that we're mass-runtime-initializing packages instead of fixing the underlying problems that necessitate it.  The more we runtime-initialize, the slower application startup will be and the larger the footprint of the resultant binary; in an ideal application, we would not runtime-initialize *any* classes.  In practice, many cases that are handled with runtime initialization can be solved in other ways which could enable significantly better optimization at run time.

2020-10-29 14:41 UTC, gastaldi commented on core/deployment/src/main/java/io/quarkus/deployment/builditem/nativeimage/RuntimeInitializedPackageBuildItem.java
> +public final class RuntimeInitializedPackageBuildItem extends MultiBuildItem {
Please add some Javadoc to this class to appear nicely in https://quarkus.io/guides/all-builditems

2020-10-30 04:36 UTC, zachgk commented
I added the javadoc to both `RuntimeInitializedPackageBuildItem` and `RuntimeInitializedClassBuildItem`.

@gsmet I am not quite sure what you are looking for with the test extension. I wrote the `RuntimeInitializedPackageBuildItem` using the existing `RuntimeInitializedClassBuildItem` as an example. However, it doesn't seem to be used in the test extension. I also can't find examples of other similar classes used in the test extension. Can you point me to some code to use a basis for expanding the test extension?

@dmlloyd I agree that it is not optimal. I am trying to add an extension to support [DJL](https://djl.ai) right now. It involves a number of C libraries loaded through JNI/JNA/JavaCPP and trying to track down the classes to runtime initialize based on the build errors gave me over 200 without even reaching the end. Is there a better strategy for dealing with this that I should look into?

2020-10-30 12:03 UTC, dmlloyd commented
> @dmlloyd I agree that it is not optimal. I am trying to add an extension to support [DJL](https://djl.ai) right now. It involves a number of C libraries loaded through JNI/JNA/JavaCPP and trying to track down the classes to runtime initialize based on the build errors gave me over 200 without even reaching the end. Is there a better strategy for dealing with this that I should look into?

I am not specifically familiar with that code base but many times this kind of trail starts with a few key locations.  This is mainly due to the fact that to runtime initialize a class, all of its direct dependents must also be runtime initialized, leading to this kind of cascade which can degrade startup performance, not to mention making life difficult in terms of integration.

Because of this cascading effect, one can sometimes find the root-most class that is reporting an error, and try to resolve the error condition in a different way.  For example if a class is trying to call some native code during static initialization, try substituting that method specifically with an alternative implementation.  If successful, many many errors end up being resolved because the aforementioned cascade does not occur.

2020-11-03 01:43 UTC, zachgk commented
Thanks. I will look into this for the longer term, but try to pass this PR for an initial version. Most of the bigger problems were not in DJL itself, but in dependencies that we don't own.

@gsmet I am not quite sure what you are looking for with the test extension. I wrote the `RuntimeInitializedPackageBuildItem` using the existing `RuntimeInitializedClassBuildItem` as an example. However, it doesn't seem to be used in the test extension. I also can't find examples of other similar classes used in the test extension. Can you point me to some code to use a basis for expanding the test extension?

2020-11-05 13:42 UTC, gsmet approved these changes

2020-11-05 13:42 UTC, gsmet commented
I rebased and squashed. Let's wait for CI.

2020-11-05 14:15 UTC, dmlloyd commented
I still think this is not the best idea.  Use of this build item will be directly followed by the question: "Why is startup so slow?" and the answer will be difficult.

2020-11-05 14:30 UTC, gsmet commented
@dmlloyd Well, I wouldn't use it in Quarkus itself but it can make sense when you're struggling with an external library you want to integrate as native.

Would it work for you if I add a big warning in the Javadoc?

2020-11-05 15:03 UTC, dmlloyd commented
> @dmlloyd Well, I wouldn't use it in Quarkus itself but it can make sense when you're struggling with an external library you want to integrate as native.
> 
> Would it work for you if I add a big warning in the Javadoc?

Maybe a big warning in the code/log if the build item is consumed... or make it an error unless they set a disclaimer property to true :)

2020-11-09 20:45 UTC, zachgk commented
The class is also not really mentioned anywhere (specifically in the docs at https://quarkus.io/guides/writing-native-applications-tips#delay-class-initialization)

2020-11-13 23:15 UTC, zachgk commented
What are the next steps to get this PR merged? It is a dependency for the DJL extension (https://github.com/aws-samples/djl-demo/pull/113) and I was hoping to refer to the quarkus snapshot for using it

2020-12-03 18:02 UTC, zachgk commented
@gsmet What is the status for this PR?

2020-12-04 08:40 UTC, gsmet commented
I discussed this yesterday with Sanne and Jason. We think it's important for external extensions.

I will add a big warning and also use it in the test extension later today. I need to finish something first.

2020-12-07 17:55 UTC, gsmet commented
I pushed an additional commit with the warning and some code to exercise the bytecode in the test extension. I will merge as soon as CI is green.

2020-12-08 10:13 UTC, merged

2020-12-08 10:13 UTC, gsmet commented
Merged, sorry for the delay. It will be available in the snapshots tomorrow.

2020-12-08 22:56 UTC, zachgk commented
Awesome! Thanks @gsmet