Support multiple datasources for reactive SQL clients
quarkusio/quarkus pull request #13118
Opened 2020-11-04 14:51 UTC by gsmet

In passing, also removed the long time deprecated Axle and Rx wrappers (I checked with @cescoffier first).

/cc @Sanne @cescoffier @tsegismont

2020-11-04 14:54 UTC, gsmet commented
Still draft while running a full CI run in my fork.

2020-11-04 18:51 UTC, gsmet commented
CI all green in my fork, this is ready for review!

2020-11-04 19:22 UTC, machi1990 requested changes, later dismissed
Mostly nitpicks and one feedback about changing configuration knob for DB2 database from `reactive.myql` to `reactive.db2`.

2020-11-04 19:22 UTC, machi1990 commented on extensions/reactive-db2-client/runtime/src/main/java/io/quarkus/reactive/db2/client/runtime/DataSourcesReactiveDB2Config.java
> +    @ConfigItem(name = "reactive.mysql")
```suggestion
    @ConfigItem(name = "reactive.db2")
```

2020-11-04 19:22 UTC, machi1990 commented on extensions/reactive-datasource/runtime/src/main/java/io/quarkus/reactive/datasource/runtime/DataSourcesReactiveRuntimeConfig.java
> + */
This is no longer true. I noticed it throughout.

2020-11-04 19:22 UTC, machi1990 commented on extensions/reactive-db2-client/runtime/src/main/java/io/quarkus/reactive/db2/client/runtime/health/ReactiveDB2DataSourcesHealthCheck.java
> +public class ReactiveDB2DataSourcesHealthCheck implements HealthCheck {
```suggestion 
class ReactiveDB2DataSourcesHealthCheck implements HealthCheck {
```

2020-11-04 19:22 UTC, machi1990 commented on extensions/reactive-mysql-client/runtime/src/main/java/io/quarkus/reactive/mysql/client/runtime/health/ReactiveMySQLDataSourcesHealthCheck.java
> +public class ReactiveMySQLDataSourcesHealthCheck implements HealthCheck {
```suggestion 
class ReactiveMySQLDataSourcesHealthCheck implements HealthCheck {
```

2020-11-04 19:22 UTC, machi1990 commented on extensions/reactive-pg-client/runtime/src/main/java/io/quarkus/reactive/pg/client/runtime/health/ReactivePgDataSourcesHealthCheck.java
> +public class ReactivePgDataSourcesHealthCheck implements HealthCheck {
```suggestion 
class ReactivePgDataSourcesHealthCheck implements HealthCheck {
```

2020-11-04 20:32 UTC, gsmet commented
@machi1990 thanks for checking. I fixed a few other minor details based on your comments and added a paragraph in the doc in a second commit.

2020-11-05 08:59 UTC, tsegismont commented
@gsmet thanks for pinging adding me in cc. I will review the PR this morning.

2020-11-05 10:21 UTC, tsegismont approved these changes
LGTM, thank you for taking care of this @gsmet !

2020-11-07 21:22 UTC, merged

2020-11-07 21:26 UTC, Sanne commented
That's great! thanks all