Bump supported-maven-versions to 3.6.3 as that's required by jbang-maven-plugin
quarkusio/quarkus pull request #13128
Opened 2020-11-05 07:47 UTC by rsvoboda

Bump supported-maven-versions to 3.6.3 as that's required by jbang-maven-plugin

otherwise you get `[ERROR] Failed to execute goal dev.jbang:jbang-maven-plugin:0.0.5:run (generate-build-item-doc) on project quarkus-documentation: The plugin dev.jbang:jbang-maven-plugin:0.0.5 requires Maven version 3.6.3 -> [Help 1]`

@maxandersen fyi

Once this is merged I will update https://github.com/quarkusio/quarkusio.github.io/blob/develop/_data/versions.yaml#L6 and https://github.com/quarkusio/quarkusio.github.io/blob/develop/_guides/attributes.adoc#L6

2020-11-05 15:27 UTC, gsmet requested changes
Is 3.6.3 really required by the jbang-maven-plugin or could we make it support 3.6.2 with little effort?

Because I don't see the point requiring everyone to upgrade if we can avoid it (except for a very good reason, of course).

2020-11-05 16:24 UTC, maxandersen commented
Where are we even wanting to use jbang maven plugin ? 

that said, I don't think there should be a problem downgrading in jbang maven plugin. do you want to give that fix a test run @rsvoboda  ?

2020-11-06 13:46 UTC, rsvoboda commented
@maxandersen please release new version of the plugin, I will update the PR then.

2020-11-09 15:22 UTC, gsmet commented
I'm closing this PR. The new one will have an entirely different purpose.

2020-11-09 15:22 UTC, closed without merging