Add MP Fault Tolerance guide
quarkusio/quarkus pull request #1318
Opened 2019-03-07 17:16 UTC by TomasHofman

2019-03-07 23:13 UTC, gsmet requested changes
Really nice work Tomas.

I added some comments, mostly very minor things.

Could you wrap that into a quickstart project (against the `development` branch of the quickstarts)?

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +So what else have we've got in MicroProfile Fault Tolerance? Let's look into timeouts.
s/have we've got/have we got/

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +Since we allowed 4 retries, it would require 5 invocations to fail in row, in order for the user to be actually exposed
s/in row/in a row/ ?

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +In your browser, go to `http://localhost:8080/coffee/2/recommendations` and hit refresh couple of times.
**a** couple of times?

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +You should see some requests timeout with `org.eclipse.microprofile.faulttolerance.exceptions.TimeoutException`.
I think it would be `time out` the verb here?

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +Requests that do not timeout should show two recommended coffee samples in JSON.
same here.

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +of failed invocations reaches specified threshold, the circuit breaker _opens_ and blocks all further invocations
maybe **the** specified threshold?

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +Add following code into the `CoffeeRepositoryService` bean, so that we can demonstrate a circuit breaker in action:
**the** following code, maybe?

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +And following into the `CoffeeResource` endpoint:
s/following/inject the code below/ ?

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +We added another functionality - the application can return amount of remaining packages of given coffee on our store
**the** amount

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +This time an artificial failure was introduced in the CDI bean: `CoffeeRepositoryService#getAvailability()` method is
**the** `CoffeeRepositoryService#getAvailability()` method

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +4. Refresh couple more times. Unless you waited too long, you should again see exception, but this time it's
**a** couple more times

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +MicroProfile Fault Tolerance allows to improve resiliency of your application, without having impact on the complexity
**an** impact

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +of our busyness logic.
s/busyness/business/

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +* adding `smallrye-fault-tolerance` Quarkus extension to your project using `quarkus-maven-plugin`:
adding **the**

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +* or simply adding following Maven dependency:
**the** following

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +      <version>${quarkus.version}</version>
2 things: you need to drop the `-deployment` suffix now (it's a last minute change we made to Quarkus) and you can drop the version, people should use the BOM.

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +    -Dextensions="smallrye-fault-tolerance, resteasy-jsonb, arc"
You don't need to add `arc`

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +This command generates a Maven structure importing the extensions for RESTEasy/JAX-RS, Dependency Injection (Arc)
you can drop ArC here

2019-03-07 23:13 UTC, gsmet commented on docs/src/main/asciidoc/fault-tolerance-guide.adoc
> +and Smallrye Fault Tolerance, which is an implementation of MicroProfile Fault Tolerance spec that Quarkus uses.
of **the** MicroProfile Fault Tolerance spec

2019-03-08 09:08 UTC, TomasHofman commented
@gsmet thanks so much for corrections, I agree with everything. Oy, the articles...

The quickstart project PR is here: https://github.com/quarkusio/quarkus-quickstarts/pull/79

2019-03-09 09:53 UTC, gsmet approved these changes

2019-03-09 09:53 UTC, merged