Enable quarkus native debug process ip/host to be configured
quarkusio/quarkus pull request #13282
Opened 2020-11-13 14:58 UTC by galderz

As discussed in [Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/quarkus.2Enative.2Edebug-build-process).

2020-11-17 15:57 UTC, gastaldi commented
Caused by: org.apache.maven.plugin.MojoFailureException: File '/home/runner/work/quarkus/quarkus/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java' has not been previously formatted.  Please format file and commit before running validation!

2020-11-24 13:26 UTC, gsmet requested changes

2020-11-24 13:26 UTC, gsmet commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java
> +    public String debugBuildProcessAddress;
This should be `Optional<String>` if it's optional.

2021-01-13 07:15 UTC, galderz commented
Fixed formatting and address `Optional` comment.

2021-03-18 09:18 UTC, closed without merging