Getter document end reactive routes
quarkusio/quarkus pull request #13366
Opened 2020-11-18 18:14 UTC by loicmathieu

2020-11-18 18:20 UTC, cihati commented on extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/RoutingExchange.java
> +     * YYou must call <code>HttpServerResponse.end()</code> afterwards to end the response.
You

2020-11-18 18:20 UTC, cihati commented on extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/RoutingExchange.java
> +     * Set the response status code to 200, write a chunck of data to the response then ends it.
chunk

2020-11-18 19:25 UTC, gsmet requested changes, later dismissed
Spotted a small typo, I will let @mkouba review this.

2020-11-18 19:25 UTC, gsmet commented on docs/src/main/asciidoc/reactive-routes.adoc
> +NOTE: Methods that return `void` must __end__ the response or the HTTP request to this route will never ends.
```suggestion
NOTE: Methods that return `void` must __end__ the response or the HTTP request to this route will never end.
```

2020-11-18 19:25 UTC, gsmet commented on docs/src/main/asciidoc/reactive-routes.adoc
> +Some methods of the `RoutingExchange` do it for you, others not and you must call the `end()` method of the response by yourself, please refer to its JavaDoc for more information.
```suggestion
Some methods of `RoutingExchange` do it for you, others not and you must call the `end()` method of the response by yourself, please refer to its JavaDoc for more information.
```

2020-11-19 08:23 UTC, loicmathieu commented on extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/RoutingExchange.java
> +     * YYou must call <code>HttpServerResponse.end()</code> afterwards to end the response.
Corrected

2020-11-19 08:23 UTC, loicmathieu commented on extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/RoutingExchange.java
> +     * Set the response status code to 200, write a chunck of data to the response then ends it.
Corrected

2020-11-19 09:19 UTC, mkouba approved these changes
Looks good. Thanks!

2020-11-19 09:22 UTC, mkouba commented
@loicmathieu It seems that we need to format the `RoutingExchange`, i.e. just run `mvn clean install` in `quarkus/extensions/vertx-web`...
```
Caused by: org.apache.maven.plugin.MojoFailureException: File '/home/runner/work/quarkus/quarkus/extensions/vertx-web/runtime/src/main/java/io/quarkus/vertx/web/RoutingExchange.java' has not been previously formatted
```

2020-11-19 10:18 UTC, loicmathieu commented
@mkouba sorry, forgot to launch a build to format the class. 

Done, should be good now

2020-11-23 10:01 UTC, merged