Build time minimum log level #12938
quarkusio/quarkus pull request #13376
Opened 2020-11-19 11:22 UTC by galderz

FAO @dmlloyd @Sanne. This is a follow up to #13102 PR. Closes #12938. 

It adds a new optional build time per category configuration called `min-level`. It controls the minimum level of logging defined at build time. 

By default all categories' `min-level` is set to `INFO`, in which case the code generates an substratevm substitution that folds `isTraceEnabled` and `isDebugEnabled` calls to return `false`.

To keep things simple, the moment any `min-level` is configured, a different substitution is created that computes whether a given log level is enabled based on a combination of both the `min-level` set and the runtime log `level`. So, as an example, if you want to get `TRACE` on a given category, say `org.example.table`, you need to provide both:

* Build time `quarkus.log.category."org.example.table".min-level=TRACE`
* Run time `quarkus.log.category."org.example.table".level=TRACE`

When deciding the logic 👆, I pondered about the need for the runtime log level to be set, but it felt awkward to have code that had been built with `min-level` set to TRACE, and runtime log level to be say `INFO` and for `isTraceEnabled` to return true but nothing be logged when calling `log.trace`.

To exercise this, I've been using [this project](https://github.com/galderz/mendrugo/tree/master/quarkus-logging/no-min-level) to test the behaviour when no `min-level` has been set, and [this other](https://github.com/galderz/mendrugo/tree/master/quarkus-logging/min-level) with the example above. I'd like to convert these two into Quarkus integration tests, but first I'd like to make sure we have agreement on the logic.

Further optimisations are also applicable:

1. If all `min-level` set in config are `INFO` or above, the same logic as with no `min-level` set could be applied. The moment `min-level` is configured, the current logic does attempt to fold any calls.
2. If all `min-level` set in config are `WARN` or above and the logic in 👆 was applied, one could also fold `isInfoEnabled` calls to false.

Unit testing wise, I had the following doubt: to test both the branches of the logic (no `min-level` set and a `min-level` set to TRACE or some other), it seems to me that I'd need 2 maven integration test projects. Is that right? Could it be somehow done in a single one? Not sure...

Aside from unit testing, and possible further optimisations, documentation needs to be updated.

2020-11-25 09:53 UTC, danberindei commented
One problem with setting the default `min-level` to `INFO` is that it's not obvious why DEBUG messages are not logged when a user changes only the runtime `level` to `DEBUG`.

Maybe you can log a warning when the runtime level is lower than the build-time min-level.

2020-11-25 09:59 UTC, Sanne commented
> One problem with setting the default `min-level` to `INFO` is that it's not obvious why DEBUG messages are not logged when a user changes only the runtime `level` to `DEBUG`.
> 
> Maybe you can log a warning when the runtime level is lower than the build-time min-level.

Agreed!

To be fair that's the kind of warning you get when  attempting to changinge a build-time option in Quarkus at runtime; this should be consistent with that.

I believe there also was a recent PR to make such a warning ugpraded to a failure to start - which greatly helps in certain testing and IT tests. @ppalaga , I don't seem able to find it - could you point @galderz to the right code?

2020-11-25 11:14 UTC, ppalaga commented
It is in this PR https://github.com/quarkusio/quarkus/pull/13154

2020-12-02 07:12 UTC, galderz commented
@danberindei Agreed, I'll look into adding that warning.

I'm working to finish up this PR (add unit tests and documentation) next few days. I did some benchmarking with Infinispan native server and this change had a consistent positive impact. In Infinispan's case, it was combined with removing static and instance level cache of static calls to isTraceEnabled/isDebugEnabled. This calls are fast and can just be done in the code directly.

2020-12-02 10:20 UTC, galderz commented
Ignore CI failures until done, I'm pushing temporary commits to add unit testing :)

2020-12-03 11:29 UTC, galderz commented
@danberindei @Sanne I've looked at the warning, but I'm hesitant to add it at this stage since I'm unsure how to best deal with it. I don't want to have the gizmo generated code for the substituted `isLoggable` method having to print such a warning, it'd be very noisy. You could try to maybe do it in `LoggingResourceProcessor` but this is just a warning that should be printed for native mode and I don't know how that could be done. Maybe the feature needs to be present for jvm mode too, but that's beyond the scope of this right now... any ideas @dmlloyd?

2020-12-03 12:17 UTC, Sanne commented
> To be fair that's the kind of warning you get when attempting to changinge a build-time option in Quarkus at runtime; this should be consistent with that.

Did you check my previous suggestion? ^ 

I don't remember where this code lives and how it works, but I believe we already have a similar check for build-time configuration properties - including JVM mode.

Please have a look at that and try making this consistent with it?

2020-12-03 13:03 UTC, dmlloyd commented
> @danberindei @Sanne I've looked at the warning, but I'm hesitant to add it at this stage since I'm unsure how to best deal with it. I don't want to have the gizmo generated code for the substituted `isLoggable` method having to print such a warning, it'd be very noisy. You could try to maybe do it in `LoggingResourceProcessor` but this is just a warning that should be printed for native mode and I don't know how that could be done. Maybe the feature needs to be present for jvm mode too, but that's beyond the scope of this right now... any ideas @dmlloyd?

The warning should probably happen as a config validation when logging sets up each log category and handler at run time.  That code already needs to clamp the log level to the `min-level` in order to be consistent between JVM and native mode, so adding a warning there should be trivial.

2020-12-04 13:30 UTC, galderz commented
This is ready now.

I've ended up creating 2 integration test projects. One tests the logic when no `min-level` config is present (where we can fold `isTraceEnabled`/`isDebugEnabled` to `false`) and the other tests when a variety of `min-level` setups are tried and complicated gizmo generated code is exercised.

Also added some light touches to the logging documentation.

2020-12-04 13:30 UTC, galderz commented
Once it's been approved I'll go ahead and squash the commits.

2020-12-11 08:01 UTC, galderz commented
Looking into CI results, the failures seem to be caused by the PR itself.

2020-12-15 14:17 UTC, galderz commented
CI passed 🥳. Anything else to change? Shall I go ahead and squash things?

2020-12-15 14:30 UTC, Sanne commented
@galderz yes please squash it. I must say.. I'm interested in the topic but I really need to focus on my own deadlines for this week - while it would be great to have this in by tomorrow.

@danberindei @dmlloyd could one of you review?

@galderz can we assume you already tested it enough in terms of impact on the native image?

2020-12-15 16:22 UTC, galderz commented
@Sanne I did test it with Infinispan, which was a heavy user of isTraceEnabled/isDebugEnabled. I posted numbers in the Infinispan [PR](https://github.com/infinispan/infinispan/pull/8921).

I'll go ahead and squash it.

2020-12-15 16:27 UTC, galderz commented
It's squashed.

2020-12-15 16:28 UTC, Sanne commented
why closed?

2020-12-15 16:29 UTC, galderz commented
Sorry, guess I closed it by mistake 🤦‍♂️

2020-12-16 10:16 UTC, gsmet requested changes
I added some minor comments that needs fixing.

Now, I have a concern about the principle itself. Is it worth it making our user experience worse? We have users already complaining about our logging configuration. This doesn't make it easier. I won't block it but I think it needs to be carefully pondered.

/cc @gavinking

2020-12-16 10:16 UTC, gsmet commented on core/runtime/src/main/java/io/quarkus/runtime/logging/CategoryBuildTimeConfig.java
> +     * The minimum log level level for this category.
```suggestion
     * The minimum log level for this category.
```

2020-12-16 10:16 UTC, gsmet commented on core/runtime/src/main/java/io/quarkus/runtime/logging/CategoryConfig.java
> +     * The log level level for this category.
```suggestion
     * The log level for this category.
```

2020-12-16 10:16 UTC, gsmet commented on core/deployment/src/main/java/io/quarkus/deployment/logging/LoggingResourceProcessor.java
> +    private static void generateFalseFoldMethod(String name, ClassCreator cc) {
This requires a comment to explain why it's there?

2020-12-16 10:16 UTC, gsmet commented on integration-tests/pom.xml
> +        <module>logging-min-level-set</module>
If you want these modules to be tested on CI in native, they need to be added there: https://github.com/quarkusio/quarkus/blob/master/.github/native-tests.json .

2020-12-16 10:16 UTC, gsmet commented on docs/src/main/asciidoc/logging.adoc
> +either globally via `quarkus.log.min-level` property or per-category as show in the example above,
```suggestion
either globally via the `quarkus.log.min-level` property or per-category as shown in the example above,
```

2020-12-16 11:42 UTC, gavinking commented
Let me understand if I have this correct. The issue description doesn't clearly explain the _motivation_ for this work. So I'm going to try and guess what's going on here.

1. `TRACE` level (and even `DEBUG` level) logging is rarely or never useful in a running production system, but there's at least _some_ cost to calling `isTraceEnabled()` all over the place at a very fine grain.
2. Since Quarkus offers the useful facility to be able to build-time code transformations, we can avoid those calls by simply compiling them out of the code (or at least doing something that lets them be eliminated by dead code analysis, I have not quite followed this bit).
3. But of course that comes with the downside that if you _do_ turn on `TRACE`-level logging at runtime, you might be surprised to find that it has no effect. We have a `WARN` that lets you know about this situation so you aren't scratching your head for too long.

Honestly this sounds fine to me. But I gotta be honest and say that never once in my entire life have I ever used `TRACE` or `DEBUG` logging for anything, and I struggle to visualize a circumstance in which I _would_ use it, and so I consider them essentially useless. I no longer use them in code I write. So I suppose my suggested remedy would in fact be more extreme than the one proposed here.

Question: has anyone here ever actually run into a case where they needed to ask a user/customer for a `TRACE`-level log in order to identify the source of an issue?

2020-12-16 12:20 UTC, Sanne commented
hi @gavinking , yes you guessed it all right I think. A bit more context: many of our frameworks actually do include a significant amount of "trace" level messages; and sometimes there's some work being performed depending on the log level to collect the data to be passed on to the logger.
We do have cases in which this has shown to have an outrageous performance cost (orders of magnitude performance loss).
Part of the impact is caused by the nature of ahead of time compilation: lacking a real JIT, the native code compiler can't optimise for the common case (of having no such logging level enabled) while also allowing it to be enabled dynamically.

And yes in the case of Infinispan we regularly do need to ask user/customers to enable trace logging to diagnose issues (more with Infinispan and such than others); the discussion with such teams came to an agreement that such support situations will need to be handled by re-compiling, or having a "debug" build of the binary run as drop-in replacement. Products which build up-front binaries will likely have to build two flavours per platform - and this is a common practice with code in other languages.

2020-12-16 13:01 UTC, gavinking commented
> never once in my entire life have I ever used `TRACE` or `DEBUG` logging for anything

This is of course complete nonsense. I use `DEBUG` all the time to see SQL as it's executed against the database. To clarify, its `TRACE` that I think is useless. There are of course legitimate uses for `DEBUG`.

2020-12-16 13:05 UTC, gavinking commented
> We do have cases in which this has shown to have an outrageous performance cost (orders of magnitude performance loss).

OK, I believe you. Like I said, my remedy would be more extreme.

> And yes in the case of Infinispan we regularly do need to ask user/customers to enable trace logging to diagnose issues

`TRACE`, not just `DEBUG`?

I mean the reason I want to stress the difference is that verbose method entry/exit type logging is not usually useful, and by nature imposes a much more severe cost in terms of performance than "expired an entry from the cache" or "executed an insert statement" type logging.

(Sorry for writing the wrong thing above.)

2020-12-16 13:38 UTC, Sanne commented
yes, both `TRACE` and `DEBUG - depending on context.

Of course it all depends on the habits & practices of the team so certainly YMMV, but in the specific case of Infinispan the lack of this optimisations was flagged as critical.

I should add Hibernate ORM also has some trace messages. We don't have as many instances of them as their use is limited, but they are present in code areas which are extremely hot under load - so I'm looking forward to measure some benefits in the Hibernate use as well.

2020-12-16 14:09 UTC, gavinking commented
Fine, then this change seems like a good idea.

2020-12-21 09:57 UTC, galderz commented
@gsmet Addressed comments, squashed and pushed.

2021-01-04 17:29 UTC, gsmet commented
Rebased to fix a conflict and get CI to run again.

2021-01-05 17:16 UTC, gsmet approved these changes

2021-01-05 17:17 UTC, gsmet commented
OK let's get this in then. Thanks.

2021-01-05 17:17 UTC, merged

2021-01-06 07:14 UTC, galderz commented
Thx all!

2021-01-15 17:13 UTC, loicmathieu commented
I just try Quarkus 1.11 and now my debug logs didn't show anymore due to this PR.
Normally, as console log is at level ALL by default, if I configure a category to log at DEBUG it will shows up.
Now, as I understand it, I also need to configure a new `min-level` build property.

Logging level is something that everybody set at runtime to have different log levels on different environements, so it feels wrong to me that this is a build time property.
Setting a log at DEBUG is really common (on dev env for example, or during a pilote phase of an application), so it may surpise a lot of people that after 1.11 all there DEBUG log disapear.

I understand that it causes an issue on native but maybe a native only solution could has been found (like a specific native build prop).

Sorry to give feedback late but I really think this change will surprised a lot of people and I wanted to give awardeness to it.

2021-01-18 12:52 UTC, galderz commented
> I just try Quarkus 1.11 and now my debug logs didn't show anymore due to this PR.
> Normally, as console log is at level ALL by default, if I configure a category to log at DEBUG it will shows up.
> Now, as I understand it, I also need to configure a new `min-level` build property.

Right, but you should have seen a warning message in the console saying that the DEBUG level was promoted to INFO because the min-level is INFO.

> Logging level is something that everybody set at runtime to have different log levels on different environements, so it feels wrong to me that this is a build time property.

It's quite common to have debug builds of native executables. The idea is that you have a production one with no debug, and one that has been built with debug/trace min-level for when you want to debug things.

> Setting a log at DEBUG is really common (on dev env for example, or during a pilote phase of an application), so it may surpise a lot of people that after 1.11 all there DEBUG log disapear.

Surprise that DEBUG is not there yeah, but the warning message should be there.

> I understand that it causes an issue on native but maybe a native only solution could has been found (like a specific native build prop).

Doing this creates the opposite problem: for native I need to pass extra X property whereas for jvm mode I don't. With the information we have so far, we decided to keep things as consistent as possible between the two modes.

2021-01-18 13:54 UTC, maxandersen commented
@galderz I assume this change has some memory/cpu impact - can we quantify it a bit as otherwise this does seem like a bit unfortunate UX wise.

2021-01-19 12:29 UTC, galderz commented
@maxandersen You can find numbers [in this Infinispan PR](https://github.com/infinispan/infinispan/pull/8921). The optimisations introduced by this PR increase throughput around 10-15%.

2021-01-19 12:44 UTC, maxandersen commented
Excellent, thanks @galderz ! 10-15% is worth it and we seem to log/warn where ever detectable.

2021-01-19 12:53 UTC, loicmathieu commented
@maxandersen 

> Excellent, thanks @galderz ! 10-15% is worth it and we seem to log/warn where ever detectable.

This is only when running with Infinispan or other extensions that uses TRACE level logs. Most applications should suffer no performance penaly.

> Right, but you should have seen a warning message in the console saying that the DEBUG level was promoted to INFO because the min-level is INFO.

This log message should at least provides the right configuration option to use (in my case it was quarkus.log.console.min-level I think).

> It's quite common to have debug builds of native executables. 

True, but it's very un-common to have debug builds of JVM applications ...

> Doing this creates the opposite problem: for native I need to pass extra X property whereas for jvm mode I don't.

I would prefere this one as most application / developer I've talk about Quarkus with still deploy Quarkus on JVM (80 to 90% of them I think) but maybe my experience is not significative.

2021-01-19 14:32 UTC, Sanne commented
We use TRACE extensively in many libraries, including Hibernate ORM,
transaction manager, drivers.

Galder's patches are very welcome as they fix several long standing
performance issues which we identified since during the early Protean
prototypes.


On Tue, 19 Jan 2021, 12:54 Loïc Mathieu, <notifications@github.com> wrote:

> @maxandersen <https://github.com/maxandersen>
>
> Excellent, thanks @galderz <https://github.com/galderz> ! 10-15% is worth
> it and we seem to log/warn where ever detectable.
>
> This is only when running with Infinispan or other extensions that uses
> TRACE level logs. Most applications should suffer no performance penaly.
>
> Right, but you should have seen a warning message in the console saying
> that the DEBUG level was promoted to INFO because the min-level is INFO.
>
> This log message should at least provides the right configuration option
> to use (in my case it was quarkus.log.console.min-level I think).
>
> It's quite common to have debug builds of native executables.
>
> True, but it's very un-common to have debug builds of JVM applications ...
>
> Doing this creates the opposite problem: for native I need to pass extra X
> property whereas for jvm mode I don't.
>
> I would prefere this one as most application / developer I've talk about
> Quarkus with still deploy Quarkus on JVM (80 to 90% of them I think) but
> maybe my experience is not significative.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/quarkusio/quarkus/pull/13376#issuecomment-762822110>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAKMTNTTNMXJAUJCEFGYL3S2V6GTANCNFSM4T3IOJSA>
> .
>

2021-01-19 16:38 UTC, maxandersen commented
I think the argument is not necessarily for including trace in min-level but make it DEBUG. 

Would that be a compromise that removes trace from hotspots but still allow easy debugging while users who can benefit than set min-level to info ?

Or is the belief the majority of 10-15% gain was from stripping out debug ?

2021-01-19 16:54 UTC, loicmathieu commented
> I think the argument is not necessarily for including trace in min-level but make it DEBUG.

Each level would be arbitrary, I usually use INFO on production and turn on DEBUG only when needed (local for some part of the code, at the moment also on our integration env because we are in the rampdown phase of our apps).

But I now some people use DEBUG in production, and other uses WARNING !

And some people never use TRACE (like myself) and other logs everything at INFO ...

For me, DEBUG is better but it's only my usage of log level.

2021-02-02 12:24 UTC, danberindei commented
From the perspective of Infinispan, changing the default min-level to DEBUG doesn't impact performance at all: we don't log a lot of DEBUG messages, and all per-request log messages are TRACE. However, I am aware of libraries we use/have used that use DEBUG/FINE as we use TRACE, e.g. okhttp.

@galderz since we no longer use a `trace` constant, I wonder if it's possible to keep the `log.isTraceEnabled()` check in the native code when min-level is set to TRACE (or maybe you're already doing it?). It would still add bloat to the native executable and it may even add measurable overhead when the runtime level is higher, but it might make a better default because any runtime level would work OOTB.  I know this wasn't an option when you started working on this, and I'm not sure if all the other projects that were using a `trace` constant (e.g. Hibernate) have also made the change.

2021-02-04 11:41 UTC, galderz commented
> @galderz since we no longer use a trace constant, I wonder if it's possible to keep the log.isTraceEnabled() check in the native code when min-level is set to TRACE (or maybe you're already doing it?).

@danberindei When `min-level` is set to `TRACE`, the `log.isTraceEnabled()` remains because we don't know what the runtime log levels will be. This means that when `min-level` is `TRACE`, the code works as it'd normally: `log.isTraceEnabled()` is called, the runtime log levels are checked to see if the given category has trace enabled...etc.

>  It would still add bloat to the native executable and it may even add measurable overhead when the runtime level is higher, but it might make a better default because any runtime level would work OOTB. I know this wasn't an option when you started working on this, and I'm not sure if all the other projects that were using a trace constant (e.g. Hibernate) have also made the change.

That's an interesting angle. TBH, I don't really mind what the default value for `min-level` is. As I said @maxandersen a couple of days back, it's up to the Quarkus UX overlords to decide what the best default is. 

When it comes to Infinispan Native Server POV perspective, you're free to set the default `min-level` to `DEBUG` or `INFO` when you build it to get extra speed. Then you can have a debug download with `min-level` set to `TRACE`.