Add some debug
quarkusio/quarkus pull request #13388
Opened 2020-11-19 17:52 UTC by glefloch

DO NOT MERGE

I am not able to reproduce the test failure locally nor in CI on my repo. This aims to add some debug.

close #13382

2020-11-20 09:36 UTC, aloubyansky approved these changes

2020-11-22 17:53 UTC, gsmet requested changes
Sorry to be that guy :).

2020-11-22 17:53 UTC, gsmet commented on integration-tests/gradle/src/test/java/io/quarkus/gradle/QuarkusGradleWrapperTestBase.java
> +        System.err.println("Command : " + String.join(" ", command) + " failed with the following output :");
```suggestion
        System.err.println("Command: " + String.join(" ", command) + " failed with the following output:");
```

2020-11-22 19:16 UTC, glefloch commented on integration-tests/gradle/src/test/java/io/quarkus/gradle/QuarkusGradleWrapperTestBase.java
> +        System.err.println("Command : " + String.join(" ", command) + " failed with the following output :");
oh nice one! fixed.

2020-11-23 07:49 UTC, glefloch commented
I rebased my branch last night, the failure is not related to GELF anymore but it does not looks related..

2020-11-23 09:59 UTC, gsmet approved these changes

2020-11-23 09:59 UTC, merged