Load Kotlin parent first
quarkusio/quarkus pull request #13445
Opened 2020-11-24 01:30 UTC by stuartwdouglas

Also change to 1.4, which I am not sure if want just yet or if it should be a different PR (although this is all inter-related, as you can't do 1.4 upgrade without these changes)

Fixes #11549

2020-11-24 13:31 UTC, evanchooly requested changes
questions aside, this looks great.  the load parent first was the missing piece in my own work so this cleans that all up.  It *does* look like the mongodb modules need an update, too, as they are failing with the same "can't find kotlin.Any" error.

2020-11-24 13:31 UTC, evanchooly commented on extensions/kotlin/deployment/src/main/java/io/quarkus/kotlin/deployment/KotlinCompilationProvider.java
> +        //kotlin 1.3 version
smart.  i'd removed that in my PR...

2020-11-24 13:31 UTC, evanchooly commented on extensions/kotlin/runtime/pom.xml
> +                    <parentFirstArtifacts>
I had started to realize late yesterday the answer probably lay in loading parent first.  I was going to hit you up for input today actually.  But i had no idea this mechanism existed.    Pretty brilliant.

2020-11-24 13:31 UTC, evanchooly commented on extensions/kotlin/runtime/pom.xml
> +                        <parentFirstArtifact>org.jetbrains.kotlin:kotlin-stdlib-jdk7</parentFirstArtifact>
I don't know that we need the `-jdk8` and `-jdk7` deps any more.  The kotlin docs suggest that 1.4 doesn't need those and we can just dep on `stdlib`.

2020-11-24 13:31 UTC, evanchooly commented on extensions/panache/hibernate-orm-panache-kotlin/runtime/pom.xml
> +        <dependency>
do the `mongodb-panache-kotlin` poms need updating or do they already dep on `quarkus-kotlin`?

2020-11-24 17:13 UTC, evanchooly commented
I tried pushing changes to the PR but they ended up on my fork instead.  https://github.com/evanchooly/quarkus/tree/11549

The diff is pretty light.  i'll take another swing at getting them in right place (if I have rights) after lunch.

2020-11-24 22:45 UTC, stuartwdouglas commented
There is some weirdness here, as I can't reproduce these failures locally (even though I could originally). 

I then thought my changes had fixed them, but it turns out somehow those tests just started working on their own for me locally, which I still don't understand.

2020-11-25 02:19 UTC, evanchooly commented
did you see my PR on your PR?  just a handful of changes on what's here and all seems to be well.

2020-11-25 03:07 UTC, stuartwdouglas commented
I have updated it

2020-11-25 06:27 UTC, evanchooly commented
@geoand i'm already on the review.  :)  I think we're just waiting for CI (which looks like it might be hung with that job already taking 2.5h) and we're good to go.  i tested the PR with the reproducer project the OP submitted and it passed.

2020-11-25 06:38 UTC, geoand commented
> @geoand i'm already on the review. :) I think we're just waiting for CI (which looks like it might be hung with that job already taking 2.5h) and we're good to go. i tested the PR with the reproducer project the OP submitted and it passed.

:+1: 

I only re-requested the review because you had requested changes and Stuart seems to have addressed them

2020-11-25 13:27 UTC, evanchooly commented
Got it.   He merged a PR i filed against his.  Provided the tests pass in all thumbs up.

2020-11-25 13:43 UTC, evanchooly approved these changes

2020-11-27 19:18 UTC, merged