fix: update doc to account for new environment variable options
quarkusio/quarkus pull request #13501
Opened 2020-11-26 19:24 UTC by metacosm

2020-11-26 22:02 UTC, gsmet requested changes, later dismissed
Apparently, you don't like spaces after a dot :).

2020-11-26 22:02 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-openshift.adoc
> +Previous versions of the OpenShift extension supported a different syntax to add environment variables.The older syntax is still supported but is deprecated and it's advised that you migrate to the n
```suggestion
Previous versions of the OpenShift extension supported a different syntax to add environment variables. The older syntax is still supported but is deprecated and it's advised that you migrate to the new syntax.
```

2020-11-26 22:02 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-openshift.adoc
> +NOTE: If you redefine the same variable using the new syntax while keeping the old syntax, **ONLY** the new version will be kept and a warning will be issued to alert you of the problem.For example,
```suggestion
NOTE: If you redefine the same variable using the new syntax while keeping the old syntax, **ONLY** the new version will be kept and a warning will be issued to alert you of the problem. For example, if you define both
```

2020-11-27 06:54 UTC, metacosm commented
That is weird…

2020-11-27 07:49 UTC, geoand commented
Some IDE setting maybe?

2020-11-27 07:52 UTC, metacosm commented
> Some IDE setting maybe?

More like a bug in the IDEA asciidoc plugin because it's not really consistent… Not sure what's going on there but that is weird.

2020-11-27 07:57 UTC, geoand commented
> Another weird thing is that it doesn't even show me that one of these lines was modified in the last commit so there's something funky going on…

Maybe you have configured it to not show whitespace changes?

2020-11-27 07:58 UTC, metacosm commented
> > Another weird thing is that it doesn't even show me that one of these lines was modified in the last commit so there's something funky going on…
> 
> Maybe you have configured it to not show whitespace changes?

No, it's not that, it won't even show the line was changed when using `Annotate with git blame`.

2020-11-27 17:34 UTC, gsmet approved these changes

2020-11-27 17:34 UTC, merged