Let kubernetes-client to use the quarkus-config-yaml extension
quarkusio/quarkus pull request #13555
Opened 2020-11-30 09:45 UTC by mrizzi

I'm working on windup's rules (https://github.com/windup, downstream Migration Toolkit for Applications https://red.ht/mta) to support users in applications modernization path toward Quarkus.
I created a rule to suggest adopting Quarkus Config YAML extension and running this rule against Quarkus' extensions itself, the rule suggested to "modernize" Quarkus Kubernetes Client suggestion to replace SmallRye Config YAML dependency with Quarkus Config YAML extension.

2020-11-30 09:55 UTC, gsmet requested changes
Hmmm. I'm not sure about this.

First we need to understand why the Kubernetes Client extension is using `smallrye-config-source-yaml`.

2020-11-30 10:22 UTC, gsmet commented
Cancelling CI run for now. I need the resources for the release. Will restart after the backport PR has been processed.

2020-11-30 11:02 UTC, mrizzi commented
Yep, sure, it makes perfectly sense to me to better understand this and this will help me as well in understanding how to make the rule more effective.
Before pushing, I've tested `integration-tests/kubernetes-client/` and everything was fine and I had the same outcome as running with `smallrye-config-source-yaml` artifact.
Basically the rule is based on this guide https://quarkus.io/guides/config#yaml where Quarkus config-yaml extensions seems to be able to fully replace SmallRye Config YAML features.

2020-11-30 11:36 UTC, gsmet commented
So the Quarkus extension will bring SmallRye Config Source Yaml but... I'm not sure we want to bring the whole Quarkus extension for the Kubernetes Client in this case. It probably uses SmallRye Config Source Yaml for its own purpose.

2020-11-30 16:26 UTC, gastaldi commented
> First we need to understand why the Kubernetes Client extension is using `smallrye-config-source-yaml`.

+1, IMHO they don't really relate but I may be missing something, I'll investigate when I get back from PTO

2020-12-01 07:30 UTC, geoand commented
Yeah, I don't really think this is needed. 

For a Quarkus application the rule that @mrizzi talks about makes perfect sense, but for an extension it may or may not. In this case, I don't think it does.

2020-12-01 08:35 UTC, mrizzi commented
Thanks a lot for your comments @gsmet, @gastaldi and @geoand 

I keep the windup's rule as it is, which is a very good information for me :+1: 

Feel free to close this issue if, in the end, you agreed this change doesn't make sense for this extension.

2020-12-01 09:35 UTC, closed without merging