Add RESTEasy Reactive example codestart
quarkusio/quarkus pull request #13793
Opened 2020-12-10 07:08 UTC by geoand

Relates to: #13753

2020-12-10 08:51 UTC, ia3andy commented
Cool @geoand :) don't you feel we should add another reactive endpoint?

2020-12-10 08:52 UTC, geoand commented
Sure :)

2020-12-10 10:08 UTC, geoand commented
We can do that latter, let's just get the basics in for now - I have a lot of stuff to take care of and this is pretty minimal TBH :).

If you want to add one however, be my guest :)

2020-12-10 10:10 UTC, ia3andy requested changes
LGTM beside the name, what about the CI failing?

2020-12-10 10:10 UTC, ia3andy commented on devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/core/examples/resteasy-reactive-example/codestart.yml
> +        class-name: GreetingResource
We need to change this to avoid conflict with RESTEasy:
```suggestion
        class-name: ReactiveGreetingResource
```

2020-12-10 10:20 UTC, ia3andy approved these changes

2020-12-10 10:23 UTC, geoand commented
Let's hope CI will be happy this time :)

2020-12-10 10:27 UTC, ia3andy commented
> We can do that latter, let's just get the basics in for now - I have a lot of stuff to take care of and this is pretty minimal TBH :).
> 
> If you want to add one however, be my guest :)

I believe that learning material is often as important as the feature itself. I think merging that is a first step, but I think you (or anyone you can find) should iterate before the release. 

TBH I would gladly do it, but I am forcing myself not to add new Extension codestarts, because that is not a sustainable approach for it..

2020-12-10 10:34 UTC, geoand commented
Sure I understand.

Just like you, I have a ton of other stuff to attend to. Hopefully I'll get to it before the next release but there is no guarantee

2020-12-10 16:58 UTC, geoand commented
I am not sure why the tests are failing...

I mean I know it's due to the is PR, but I have no idea why

2020-12-10 19:00 UTC, ia3andy commented
@geoand There is a test making sure extension codestarts can work together, well it's seems this one is not friend with RESTEasy.. I think that instead of having an error, we should prioritize `resteasy-reactive` when both are present..
```
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
2020-12-10T10:59:48.3864976Z             	[error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: java.lang.IllegalStateException: The 'quarkus-resteasy-reactive' and 'quarkus-resteasy' extensions cannot be used at the same time.
```

CC @maxandersen

2020-12-10 19:06 UTC, geoand commented
The extensions do not work together - it's one or the either (which is why we throw an error at build time).

So IIUC from what you mention, currently there is no way to have the prioritization you mention and you would have to add that feature?

2020-12-11 07:57 UTC, ia3andy commented
@geoand  I will push a workaround to make it tested separately. 

My concern is that we have lot of extension that are named with `resteasy-..` prefix and it used to imply that it needed `resteasy`..

- best effort, we should add this in the extension description (if that's not already the case)?
- If that's not supported, maybe we should also create an issue for prioritization? It would be the best solution IMO..

2020-12-11 16:03 UTC, ia3andy commented
Ok my commit should fix the CI :)

2020-12-11 16:04 UTC, geoand commented
Cool, thanks

2020-12-11 16:07 UTC, ia3andy commented
Adding a test to the RUN_ALONE is really expensive because it tests maven/gradle/kotlindsl x java/kotlin/scala, maybe I should only test maven? is there a risk that an example would work on maven and not gradle?

2020-12-11 16:09 UTC, geoand commented
Sure that's a good idea.

If it works in Maven, it will work in Gradle

2020-12-11 16:09 UTC, ia3andy commented
I'll add another commit for this then

2020-12-11 16:34 UTC, ia3andy commented
Ok done, we should keep the same level of reliability but removing 6 (on 9) (generate&build&run) tests per run alone codestart. That's significant

2020-12-11 16:46 UTC, ia3andy commented
@geoand do you mind squashing it? I can't do it..

2020-12-11 17:00 UTC, geoand commented
Done

2020-12-14 07:21 UTC, merged