Update SmallRye GraphQL, adding more test cases for reactive
quarkusio/quarkus pull request #13820
Opened 2020-12-10 17:31 UTC by phillip-kruger

Upgrade the SmallRye GraphQL version, adding some more Test cases for reactive and adding a small section in the guide about reactive

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

2020-12-10 22:09 UTC, gsmet requested changes
Added a couple suggestions for the doc.

2020-12-10 22:09 UTC, gsmet commented on docs/src/main/asciidoc/microprofile-graphql.adoc
> +Queries can be made reactive by using `Uni`, or `CompletionStage` as a return type, in example:
```suggestion
Queries can be made reactive by using `Uni`, or `CompletionStage` as a return type, for example:
```

2020-12-10 22:09 UTC, gsmet commented on docs/src/main/asciidoc/microprofile-graphql.adoc
> +Using `Uni` or `CompletionStage` means that when a request contains more than one query, they will be executed concurrently, in example:
```suggestion
Using `Uni` or `CompletionStage` means that when a request contains more than one query, they will be executed concurrently.

For instance, the query below will fetch `film0` and `film1` concurrently:
```

2020-12-10 22:09 UTC, gsmet commented on docs/src/main/asciidoc/microprofile-graphql.adoc
> +Above will fetch `film0` and `film1` concurrently.
And I would remove this line.

2020-12-11 06:17 UTC, phillip-kruger commented
Thanks @gsmet - Changes made as suggested.

2020-12-11 10:23 UTC, gsmet approved these changes

2020-12-11 10:24 UTC, merged