WIP - Create Picoli example codestart for Quarkus JBang project type
quarkusio/quarkus pull request #13828
Opened 2020-12-10 22:24 UTC by nicobao

Now it's better ^^'

Closes #13208

2020-12-11 21:10 UTC, nicobao commented
Hi,
I used "WIP" but actually, on my side it's all working - waiting for review.
In my local fork, build is passing except for JDK 11 Windows. For some reasons the build lasts for more than 3 hours and GitHub simply cancels it: https://github.com/nicobao/quarkus/actions/runs/414103123
/cc @ia3andy

2020-12-14 07:09 UTC, ia3andy commented on devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus-jbang/code/jbang-picocli-code/codestart.yml
> +      resource:
That maybe better since it's not a resource:
```suggestion
      command:
```

2020-12-14 07:09 UTC, ia3andy commented on devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus-jbang/code/jbang-picocli-code/codestart.yml
> +      resource:
You will need to update when using it of course..

2020-12-14 07:10 UTC, ia3andy commented on devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus-jbang/code/jbang-resteasy-code/base/README.tpl.qute.md
> +./jbang src/GreetingResource.java
`./jbang src/GreetingCommand.java`

2020-12-14 07:12 UTC, ia3andy commented on devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus-jbang/code/jbang-picocli-code/codestart.yml
> +        class-name: EntryCommand
Wdyt of?
```suggestion
        class-name: GreetingCommand
```

2020-12-14 07:15 UTC, ia3andy commented on devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus-jbang/code/jbang-picocli-code/base/README.tpl.qute.md
> +## Greet the world!
Maybe we can make the doc a bit simpler by showing one command to say hello and another to show the help.

2020-12-14 07:15 UTC, ia3andy requested changes
Very good!! Thanks a lot :) I added a few suggestions..

2020-12-14 19:18 UTC, nicobao commented
Hi @ia3andy
Just rebased and added your suggestion. Let me know if I can remove the "WIP"!

2020-12-15 08:11 UTC, ia3andy approved these changes
Nice :) thanks!! Waiting for CI..

2020-12-17 19:51 UTC, nicobao commented
Hi!
I think, for some reasons, the CI didn't started? All tests passed in my fork at least.
Do you need me to rebase btw?

2021-01-04 08:31 UTC, ia3andy commented
I've tried to restart it, but it still skips the build @gsmet any thoughts?

in the meantime, @nicobao you could maybe force push a tiny change to re-trigger the CI?

2021-01-04 21:06 UTC, nicobao commented
Hi,
Happy New Year :).
Rebasing was enough to trigger a build!

2021-01-05 09:03 UTC, merged