Add client metrics to rest client extension
quarkusio/quarkus pull request #13884
Opened 2020-12-14 21:18 UTC by oscarfh

This is my take (with a lot of support from @ebullient ) on how to add metrics to the rest-clients automatically. 

Please let me know of the improvements, or also feel free to make it yourselves.

2020-12-14 21:31 UTC, ebullient commented
I'd like to see if we can streamline things.. but this is a good start. Catch you on Zulip. ;)

2020-12-15 09:47 UTC, gsmet submitted a review, later dismissed
Thanks! I will let @ebullient drive this, just a note that this needs to be squashed before merging. Please dismiss when done!

2020-12-15 17:59 UTC, ebullient requested changes
I've made a PR against the original branch w/ updates to move the http client metrics extension closer to http server metrics collection (as reactive rest is going to influence both paths across multiple extensions.. )

2020-12-15 19:34 UTC, kenfinnigan approved these changes
Couple of notes about imports that don't appear to be used, but otherwise looks good!

2020-12-15 19:34 UTC, kenfinnigan commented on extensions/rest-client/deployment/src/main/java/io/quarkus/restclient/deployment/RestClientProcessor.java
> +import io.quarkus.deployment.metrics.MetricsCapabilityBuildItem;
Imports added that don't appear to be used, is that right?

2020-12-15 19:34 UTC, kenfinnigan commented on extensions/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/RestClientRecorder.java
> +import io.quarkus.runtime.metrics.MetricsFactory;
Again with added imports

2020-12-15 21:23 UTC, ebullient approved these changes

2020-12-17 21:29 UTC, merged