Basic ClientHeadersFactory documentation
quarkusio/quarkus pull request #13891
Opened 2020-12-15 08:53 UTC by jtama-op

Fixes #13750

2020-12-15 20:05 UTC, gsmet requested changes
Very useful addition, thanks!

I added some suggestions.

2020-12-15 20:05 UTC, gsmet commented on docs/src/main/asciidoc/rest-client.adoc
> +And the RequestUUIDHeaderFactory` :
```suggestion
And the `RequestUUIDHeaderFactory` would look like:
```

2020-12-15 20:05 UTC, gsmet commented on docs/src/main/asciidoc/rest-client.adoc
> +Any CDI bean matching the declared factory will be picked-up and can of course benefit from quarkus features.
```suggestion
Any CDI bean matching the declared factory class will be picked up and can of course benefit from the usual CDI infrastructure.
```

2020-12-15 20:05 UTC, gsmet commented on docs/src/main/asciidoc/rest-client.adoc
> +    public MultivaluedMap<String, String> update(MultivaluedMap<String, String> multivaluedMap, MultivaluedMap<String, String> multivaluedMap1) {
```suggestion
    public MultivaluedMap<String, String> update(MultivaluedMap<String, String> incomingHeaders, MultivaluedMap<String, String> clientOutgoingHeaders) {
```

2020-12-16 10:20 UTC, jtama-op commented
I accepted your changes request, I probably need to squash commits now, don't I ?

2020-12-16 16:07 UTC, gsmet approved these changes
I just did the squash :).

Thanks, will merge as soon as CI is green.

2020-12-16 21:55 UTC, merged