Disable XML mapping by default and allow Hibernate ORM integrations to re-enable it if necessary
quarkusio/quarkus pull request #13929
Opened 2020-12-16 16:03 UTC by yrodiere

Based on #13924 , which should be merged first.

cc @gsmet @Sanne

2020-12-16 16:11 UTC, Sanne commented
Looks good.  I've been wondering about the listener approach: do we need to check they don't request conflicting options?

For this reason I previously preferred an opt-in boolean for specific flags only - but I can see how your approach has much more flexibility.

2020-12-16 16:13 UTC, Sanne approved these changes

2020-12-16 16:21 UTC, yrodiere commented
> Looks good. I've been wondering about the listener approach: do we need to check they don't request conflicting options?

If suppose we could do that for ORM properties, but keep in mind we also use these listeners for Hibernate Search to register its own properties, so this is not *only* about Hibernate ORM configuration.

2020-12-16 21:40 UTC, gsmet commented
The tests failed:
```
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$setupPersistenceProvider1531751146.deploy_0(HibernateOrmProcessor$setupPersistenceProvider1531751146.zig:269)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$setupPersistenceProvider1531751146.deploy(HibernateOrmProcessor$setupPersistenceProvider1531751146.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:478)
	... 47 more
```

2020-12-17 09:14 UTC, yrodiere commented
The failure was caused by a problem in `BytecodeRecorderImpl`. I sent a PR: #13938 and rebased this PR on #13938.

2020-12-17 12:50 UTC, yrodiere commented
#13938 was merged, I rebased on master.

2020-12-17 15:25 UTC, gsmet requested changes

2020-12-17 15:25 UTC, gsmet commented on extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/FastBootHibernatePersistenceProvider.java
> +                descriptor.getInitListener().ifPresent(l -> l.contributeRuntimeProperties(runtimeSettingsBuilder::put));
We try to avoid lambdas at runtime.

2020-12-17 15:25 UTC, gsmet commented on extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/boot/FastBootMetadataBuilder.java
> +                    .ifPresent(listener -> listener.onMetadataInitialized(fullMeta, metamodelBuilder.getBootstrapContext(),
Same here.

2020-12-17 15:38 UTC, yrodiere commented
Well that's a shame... done.

2020-12-17 16:31 UTC, gsmet approved these changes

2020-12-17 19:53 UTC, merged

2020-12-17 19:53 UTC, gsmet commented
Thanks!