ArC - make it possible to exclude interceptors, bindings, qualifiers...
quarkusio/quarkus pull request #13923
Opened 2020-12-16 13:46 UTC by mkouba

and stereotypes from discovery via "quarkus.arc.exclude-types"
- currently only bean classes are excluded

2020-12-16 13:47 UTC, mkouba commented
See also https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/CDI.20interceptor/near/220102926

2020-12-17 11:36 UTC, manovotn requested changes

2020-12-17 11:36 UTC, manovotn commented on independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java
> +                    continue;
Container annotations are not bindings/qualifiers themselves. This should be left untouched.

2020-12-17 13:16 UTC, manovotn approved these changes

2020-12-18 13:52 UTC, merged