Extend Kafka documentation
quarkusio/quarkus pull request #14120
Opened 2021-01-05 16:32 UTC by cescoffier

- Add a section about testing
- Add a section about OAuth authentication

2021-01-05 17:00 UTC, gsmet requested changes
Suggested a few minor changes.

2021-01-05 17:00 UTC, gsmet commented on docs/src/main/asciidoc/kafka.adoc
> +OAuth authentication works for both JVM and native mode.
```suggestion
OAuth authentication works for both JVM and native modes.
```

2021-01-06 07:04 UTC, cescoffier commented on docs/src/main/asciidoc/kafka.adoc
> +OAuth authentication works for both JVM and native mode.
Fixed

2021-01-06 07:05 UTC, cescoffier commented on docs/src/main/asciidoc/kafka.adoc
> +    @Inject  @Any
Not needed anymore.

2021-01-06 07:05 UTC, cescoffier commented on docs/src/main/asciidoc/kafka.adoc
> +    @Inject  @Any
It's actually required. 

It's because the bean has a qualifier the (@Connector annotation).

2021-01-06 07:06 UTC, cescoffier commented on docs/src/main/asciidoc/kafka.adoc
> +The following snippet shows a test resource starting a Kafka broker using https://www.testcontainers.org/modules/kafka/[Test Containers]:
Fixed

2021-01-06 09:14 UTC, gsmet approved these changes

2021-01-06 09:14 UTC, merged