Allow to start the Quartz scheduler halted
quarkusio/quarkus pull request #14122
Opened 2021-01-05 16:49 UTC by gsmet

Supersedes https://github.com/quarkusio/quarkus/pull/14043

/cc @nragon @machi1990

2021-01-05 17:05 UTC, machi1990 approved these changes

2021-01-06 07:49 UTC, mkouba requested changes

2021-01-06 07:49 UTC, mkouba commented on extensions/quartz/deployment/src/test/java/io/quarkus/quartz/test/HaltedScheduleJobTest.java
> +                    .addAsResource(new StringAsset("quarkus.quartz.enabled=true\n" +
I believe that there is no such config property like `quarkus.quartz.enabled`...

2021-01-06 07:49 UTC, mkouba commented on extensions/quartz/deployment/src/test/java/io/quarkus/quartz/test/HaltedScheduleJobTest.java
> +    Instance<org.quartz.Scheduler> quartzScheduler;
Is there a reason to use `javax.enterprise.inject.Instance` here?

2021-01-06 07:49 UTC, mkouba commented on extensions/quartz/deployment/src/test/java/io/quarkus/quartz/test/HaltedScheduleJobTest.java
> +        assertEquals(expectedState, Starter.LATCH.await(3, TimeUnit.SECONDS),
Hm, so this test will always take at least 3 seconds... Maybe `HaltedSchedulerTest` that asserts the return value of `org.quartz.Scheduler.isInStandbyMode()` is enough and we could remove this test completely?

2021-01-06 07:49 UTC, mkouba commented on extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java
> +            forceStart = runtimeConfig.forceStart.isPresent() && runtimeConfig.forceStart.get();
`runtimeConfig.forceStart.orElse(false)`?

2021-01-06 09:46 UTC, gsmet commented
@mkouba I applied your suggestions and renamed `halted` to `standby`. Should be good to go now.

2021-01-06 09:49 UTC, mkouba approved these changes

2021-01-06 09:54 UTC, nragon commented
@gsmet not to be confused with quartz standby mode (which can affect behavior on resuming a trigger)

2021-01-06 10:00 UTC, gsmet commented
@nragon so you're saying renaming it to `standby` is a bad idea?

From my tests, the Quartz scheduler was in standby mode on startup.

2021-01-06 10:04 UTC, mkouba commented
> @gsmet (note) not to be confused with quartz standby mode (which can affect behavior on resuming a trigger)

Hm, that's actually a good point. So `standby` means started but temporarily halted.

By the way, the current `io.quarkus.quartz.runtime.QuartzScheduler.isRunning()` implementation does not reflect the new start mode because previously an enabled scheduler was always started.

2021-01-06 10:06 UTC, mkouba commented
> @nragon so you're saying renaming it to `standby` is a bad idea?
> 
> From my tests, the Quartz scheduler was in standby mode on startup.

It's paused by default: https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/java/org/quartz/core/QuartzSchedulerThread.java#L123

2021-01-06 10:14 UTC, gsmet commented
> By the way, the current io.quarkus.quartz.runtime.QuartzScheduler.isRunning() implementation does not reflect the new start mode because previously an enabled scheduler was always started.

Not sure I understand that? `isRunning()` returns false if we set the start mode to `halted`.

2021-01-06 10:17 UTC, gsmet commented
Got back to `halted` then.

2021-01-06 10:17 UTC, mkouba commented
> > By the way, the current io.quarkus.quartz.runtime.QuartzScheduler.isRunning() implementation does not reflect the new start mode because previously an enabled scheduler was always started.
> 
> Not sure I understand that? `isRunning()` returns false if we set the start mode to `halted`.

Yeah, it works because `isInStandbyMode()` returns true by default - see https://github.com/quarkusio/quarkus/pull/14122#issuecomment-755207595

2021-01-06 12:12 UTC, nragon commented
I was just mentioning that the standby action on quartz implies notifying both job store and listeners.
For me halted means that scheduler was not put on hold but the start was delayed for some reason.

2021-01-06 12:13 UTC, gsmet commented
@nragon yes, makes sense. I went back to your original proposal, sorry for the noise.

2021-01-06 12:59 UTC, merged