Funqy Google Cloud Functions codestart
quarkusio/quarkus pull request #14279
Opened 2021-01-13 12:18 UTC by loicmathieu

2021-01-13 12:19 UTC, loicmathieu commented
/cc @ia3andy the last codestart for Google Cloud Functions that gives example on the third way to build a function: via Funqy.

2021-01-13 13:21 UTC, ia3andy requested changes
Cool!

2021-01-13 13:21 UTC, ia3andy commented on devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/singleton-examples/funqy-google-cloud-functions-example/base/README.md
> +Two examples have been generated under `src/main/java/org/acme/fuqygooglecloudfunctions`, you must remove them before deploying to
```suggestion
Two examples have been generated under `src/main/java/org/acme/funqygooglecloudfunctions`, you must remove them before deploying to 
```

2021-01-13 14:01 UTC, loicmathieu commented on devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/singleton-examples/funqy-google-cloud-functions-example/base/README.md
> +Two examples have been generated under `src/main/java/org/acme/fuqygooglecloudfunctions`, you must remove them before deploying to
Nice catch, fixed!

2021-02-04 17:59 UTC, gsmet commented
@ia3andy could you have another look?

2021-02-08 08:13 UTC, ia3andy commented
I added a new `metadata` section in the codestart.yml, and added a template for the readme. I will push a commit today to update this PR with it..

2021-02-09 11:26 UTC, loicmathieu commented
> I added a new metadata section in the codestart.yml, and added a template for the readme. I will push a commit today to update this PR with it..

@ia3andy do you have time to do it today . 1.12 will be cut off tomorrow I would like to have this one included inside it

2021-02-09 11:37 UTC, ia3andy commented
Ok! I will :)

2021-02-09 12:26 UTC, ia3andy commented
@loicmathieu could you rebase the PR from master please?

2021-02-09 13:22 UTC, ia3andy commented
I created a new PR from yours https://github.com/quarkusio/quarkus/pull/14942

2021-02-09 13:22 UTC, closed without merging