Update mailer guide documentation
quarkusio/quarkus pull request #14452
Opened 2021-01-20 19:28 UTC by glefloch

First attempt to update the docs. 

@cescoffier, @rsvoboda what do you think? 

close #14399

2021-01-20 19:32 UTC, cescoffier requested changes

2021-01-20 19:32 UTC, cescoffier commented on docs/src/main/asciidoc/mailer.adoc
> +        .onItem().map(x -> Response.accepted().build()); <2>
Transform and not map

2021-01-20 21:20 UTC, glefloch commented on docs/src/main/asciidoc/mailer.adoc
> +        .onItem().map(x -> Response.accepted().build()); <2>
Right! I fixed it.

2021-01-21 06:34 UTC, cescoffier approved these changes

2021-01-21 06:34 UTC, merged

2021-01-21 06:34 UTC, cescoffier commented
Thanks!