Apply tiny polish to RESTEasy Reactive startup code
quarkusio/quarkus pull request #14663
Opened 2021-01-28 07:15 UTC by geoand

2021-01-28 09:41 UTC, gsmet requested changes, later dismissed
Spotted a small (but preexisting) inconsistency.

2021-01-28 09:41 UTC, gsmet commented on independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/startup/RuntimeDeploymentManager.java
> +        for (int i = 0; i < info.getGlobalHandlerCustomers().size(); i++) {
Hmmm, customer or customizer?

2021-01-28 11:32 UTC, geoand commented on independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/startup/RuntimeDeploymentManager.java
> +        for (int i = 0; i < info.getGlobalHandlerCustomers().size(); i++) {
Good eye! Fixed

2021-02-01 19:36 UTC, geoand commented
@gsmet mind giving this a quick review since you already took a look at it?

2021-02-01 21:26 UTC, gsmet approved these changes

2021-02-01 21:26 UTC, merged