Prevent ISE duplicate key when checking if instrumentation can be used
quarkusio/quarkus pull request #14765
Opened 2021-02-02 13:17 UTC by geoand

2021-02-02 21:53 UTC, gsmet requested changes
Added a question that (I think) needs an answer before merging.

2021-02-02 21:53 UTC, gsmet commented on core/deployment/src/main/java/io/quarkus/deployment/dev/ClassComparisonUtil.java
> +                .collect(Collectors.toMap(AnnotationInstance::name, Function.identity(), (i1, i2) -> i1));
Do you really want to ignore the second one?

2021-02-02 22:06 UTC, stuartwdouglas commented
What actually causes this? There should not be a situation where there are duplicate annotations.

2021-02-02 22:13 UTC, gsmet commented
Is it with latest Quarkus? Because we had a bug in method comparisons triggering exactly this. Martin fixed it and I believe it’s in 1.11.1.Final.

2021-02-03 09:13 UTC, evacchi commented
I had this issue with one of the examples with Quarkus 1.11.x IIRC -- sorry couldn't come up with a stand-alone reproducer yet. Had two separate issues, this one with

- https://github.com/kiegroup/kogito-examples/tree/stable/process-scripts-quarkus -- while updating the BPMN file
- the other (different nature, still related to instrumentation) https://github.com/kiegroup/kogito-examples/tree/stable/dmn-quarkus-example -- while updating the DMN file

2021-02-04 17:42 UTC, gsmet commented
Could someone have a look at this? I won't have the time to check it and PRs are piling up. Looks like something we would want fixed for 1.11.2.Final.

2021-02-04 17:47 UTC, geoand commented
I'll try tomorrow but I can make no guarantees as there is a ton of (high priority) work pilling up

2021-02-04 17:48 UTC, geoand commented
In any case, https://github.com/quarkusio/quarkus/pull/14775 provides a way to disable instrumentation altogether so we should definitely get that one in

2021-02-04 20:18 UTC, evacchi commented
yesterday I could not reproduce this on our master, so no need to rush it. Moreover, the flag to disable instrumentation should be helpful as well.

2021-02-12 13:43 UTC, geoand commented
@evacchi have you had any more troubles with this?

If not, I can close this

2021-02-15 09:44 UTC, evacchi commented
let's close it for now @geoand

2021-02-15 09:46 UTC, closed without merging