Set keycloak-authorization proxy url
quarkusio/quarkus pull request #14778
Opened 2021-02-02 18:06 UTC by sberyozkin

This PR sets it as for example `localhost:80`.

Keycloak adapter code checks it like this:
```
URI uri = URI.create(adapterConfig.getProxyUrl());
this.proxyHost = new HttpHost(uri.getHost(), uri.getPort(), uri.getScheme());
```

where the scheme is defaulted to `http` which users can override by setting the host to `https://localhost` etc

2021-02-02 18:08 UTC, gastaldi commented on extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerAuthorizer.java
> +            adapterConfig.setProxyUrl(oidcConfig.defaultTenant.proxy.host.get() + ":" + oidcConfig.defaultTenant.proxy.port);
No checks against proxy.port?

2021-02-02 19:37 UTC, pedroigor requested changes
@sberyozkin LGTM, except for @gastaldi comment.

Did you define a default port for `quarkus-oidc`?

2021-02-02 22:23 UTC, sberyozkin commented on extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerAuthorizer.java
> +            adapterConfig.setProxyUrl(oidcConfig.defaultTenant.proxy.host.get() + ":" + oidcConfig.defaultTenant.proxy.port);
@gastaldi It is defaulted to 80

2021-02-02 22:23 UTC, sberyozkin commented
@pedroigor Yeah :-) OidcCommonConfig.proxy

2021-02-02 22:24 UTC, sberyozkin commented
MP tests have failed, not related

2021-02-03 20:25 UTC, pedroigor approved these changes

2021-02-03 21:23 UTC, sberyozkin commented
Thanks, since it was only MP related build which failed I'll merge, CI seems unstable right now otherwise...

2021-02-03 21:24 UTC, merged