Add mutiny-test-utils to Quarkus bom
quarkusio/quarkus pull request #14773
Opened 2021-02-02 16:51 UTC by cescoffier

Fix #14755

2021-02-02 16:51 UTC, cescoffier commented
@lordofthejars FIY.

2021-02-02 21:51 UTC, gsmet requested changes

2021-02-02 21:51 UTC, gsmet commented on bom/application/pom.xml
> +                <scope>test</scope>
You should not include the scope in the BOM.

2021-02-03 10:55 UTC, gsmet approved these changes

2021-02-03 10:55 UTC, merged