Improve Quarkus extension codestarts
quarkusio/quarkus pull request #14797
Opened 2021-02-03 14:46 UTC by ia3andy

2021-02-03 15:28 UTC, gastaldi approved these changes
LGTM

2021-02-04 10:35 UTC, gsmet requested changes, later dismissed
Spotted two small things that should be changed.

2021-02-04 10:35 UTC, gsmet commented on devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/singleton-examples/funqy-knative-events-example/base/README.tpl.qute.md
> +You'll need to read the guide to learn how to deploy and run this example within a full Knative Kubernetes or Openshift
```suggestion
You'll need to read the guide to learn how to deploy and run this example within a full Knative Kubernetes or OpenShift
```

2021-02-04 10:35 UTC, gsmet commented on devtools/platform-descriptor-json/src/main/resources/codestarts/quarkus/core/examples/resteasy-example/codestart.yml
> +  description: Rest is easy peasy with this Hello World RESTEasy resource.
```suggestion
  description: REST is easy peasy with this Hello World RESTEasy resource.
```
otherwise it has another meaning :).

2021-02-08 07:54 UTC, merged