Fix Qute namespace extensions with no parameters
quarkusio/quarkus pull request #15238
Opened 2021-02-22 15:44 UTC by mkouba

- resolves #15160

2021-02-22 20:31 UTC, gsmet requested changes

2021-02-22 20:31 UTC, gsmet commented on independent-projects/qute/generator/src/main/java/io/quarkus/qute/generator/ExtensionMethodGenerator.java
> +>>>>>>> Fix Qute namespace extensions with no parameters
This doesn't compile.

2021-02-23 07:03 UTC, mkouba commented on independent-projects/qute/generator/src/main/java/io/quarkus/qute/generator/ExtensionMethodGenerator.java
> +>>>>>>> Fix Qute namespace extensions with no parameters
Yup, some leftovers after rebase...

2021-02-23 16:53 UTC, gsmet approved these changes

2021-02-23 16:54 UTC, merged