Artemis core synthetic bean
quarkusio/quarkus pull request #15350
Opened 2021-02-26 11:01 UTC by middagj

Similar to #14351, but then for core component.

I also upgraded Artemis to 2.17.0 in the same PR. If you prefer a separate PR, let me know.

2021-02-26 11:09 UTC, gsmet requested changes

2021-02-26 11:09 UTC, gsmet commented on extensions/artemis-core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisCoreRecorder.java
> +        };
Thanks!

We prefer to avoid lambdas in runtime code as they have a memory cost. Could you adjust this one and the one below?

2021-02-26 11:11 UTC, gsmet commented
@famod good example of how parallel execution makes it harder to find the error messages. The enforcer rules errors are somewhere in the logs but not at the end.

2021-02-26 11:13 UTC, gsmet commented
I /think/ the error is the following:
```
2021-02-26T11:07:07.9818034Z [WARNING] Rule 2: org.apache.maven.plugins.enforcer.BannedDependencies failed with message:
2021-02-26T11:07:07.9850394Z Found Banned Dependency: org.checkerframework:checker-qual:jar:2.5.2
2021-02-26T11:07:07.9854462Z Use 'mvn dependency:tree' to locate the source of the banned dependencies.
```
in `quarkus-test-artemis`.

2021-02-26 12:13 UTC, famod commented
> @famod good example of how parallel execution makes it harder to find the error messages. The enforcer rules errors are somewhere in the logs but not at the end.

@gsmet yeah, parallel execution can maken it harder to find the root cause. But even with a single thread it's not that easy to find the violation, see last paragraph here: https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md#frequently-asked-questions
What we could do though is to have Maven print the actual thread when logging something...?
But that would not solve the problem that you have to scroll (way) up to find out what's going on.

2021-03-02 12:24 UTC, gsmet approved these changes
Thanks!

2021-03-02 12:24 UTC, merged