Fix confusion between native image name and executable name
quarkusio/quarkus pull request #15475
Opened 2021-03-04 16:17 UTC by gsmet

This confusion broke the native executable build on Windows in
1.12.1.Final.

Fixes #15459

2021-03-04 16:37 UTC, gsmet commented
@zakkak @jonathan-meier I would be interested in you having a look. It's related to your latest refactorings: you confuse the native image name with the executable name so we end up generating a native executable with a `.exe.exe` suffix on Windows.

2021-03-04 17:16 UTC, geoand commented
`Faster CI` doesn't sounds like a great commit message 😆

2021-03-04 17:21 UTC, gsmet commented
Yeah I will remove it as soon as I have validated the Windows build in my fork. It basically removes most of the CI builds :).

2021-03-04 17:22 UTC, geoand commented
I thought so, just making sure :)

2021-03-04 17:35 UTC, jonathan-meier commented
Ouch! Yes, of course, on Windows, `native-image` appends `.exe` to the provided image name by itself, but the refactoring changed this to wrongly provide an image name already having a `.exe` suffix, so we end up with the duplicate extension `.exe.exe`. Mea culpa, sorry about that!

Your changes look good to me, though I couldn't test them since I don't have a GraalVM setup handy on Windows.

2021-03-04 18:16 UTC, zakkak requested changes
Looks good to me, except for the change in the error message.

2021-03-04 18:30 UTC, gsmet commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildRemoteContainerRunner.java
> +        copyFromBuilder(resultingExecutableName, "Failed to copy native executable from container back to the host.");
We decided to call it `native executable` in our docs. It might not be consistent everywhere but that's what we decided.

2021-03-04 19:12 UTC, gsmet commented
FWIW, there's a good chance I will just revert the changes backported to 1.12 in the 1.12 branch. I was already leaning towards rejecting them for 1.12, I should have.

(backporting is a pain as there were a ton of changes there)

2021-03-04 20:52 UTC, zakkak approved these changes

2021-03-08 10:38 UTC, gsmet commented
I added a native test on Windows. Hopefully, it will help us catch this sort of issues in the future.

2021-03-08 18:19 UTC, gsmet commented
@geoand it's now ready (and tested), could you have a look? I will need to work on backporting this to 1.12 and it won't be a piece of cake.

2021-03-08 20:00 UTC, geoand commented
> I added a native test on Windows. Hopefully, it will help us catch this sort of issues in the future.

That's great! I'm surprised we didn't have any...

2021-03-08 20:01 UTC, geoand approved these changes
LGTM!

2021-03-09 07:39 UTC, rsvoboda commented
Nice, I spotted the problem yesterday when looking into fix for Windows native case I filed some time ago.
I had these changes - https://github.com/rsvoboda/quarkus/commit/23e68ef3601f0abc32ec70ec983e1c78116a28c4
Will check the PR too.

2021-03-09 07:43 UTC, rsvoboda approved these changes

2021-03-09 09:38 UTC, merged