Add documentation for containerized native builds on remote daemons
quarkusio/quarkus pull request #15591
Opened 2021-03-09 22:31 UTC by jonathan-meier

Doc for PR #14635.

2021-03-09 23:12 UTC, zakkak requested changes
Thanks for the PR @jonathan-meier :)
Please see my comments for a couple of typos and a suggestion.

2021-03-10 20:28 UTC, jonathan-meier commented on docs/src/main/asciidoc/building-native-image.adoc
> +If your application JAR builds fine but you get an invalid path error for the JAR when trying to create a native executable using a container build, you're most likely using a remote daemon for your
Good suggestion, I reworded this part a bit to fluently include a copy of the error.

2021-03-10 20:28 UTC, jonathan-meier commented
Thanks for the feedback! I fixed the typos and addressed your suggestion.

2021-03-10 20:51 UTC, zakkak approved these changes
Thanks for the fixes!

It looks good to me.

2021-03-12 09:09 UTC, gsmet approved these changes

2021-03-12 09:09 UTC, merged

2021-03-12 09:09 UTC, gsmet commented
Thanks!