More visibility to SmallRye.
quarkusio/quarkus pull request #15650
Opened 2021-03-11 23:10 UTC by radcortez

2021-03-12 01:08 UTC, gastaldi approved these changes
LGTM

2021-03-12 08:58 UTC, gsmet requested changes, later dismissed
What's the rationale of this? I read a lot of things about people being happy to have Quarkus compatible with MicroProfile. Will it be visible enough after this change?

Also, you will need to install redirects in the website.

2021-03-12 14:08 UTC, kenfinnigan requested changes

2021-03-12 14:08 UTC, kenfinnigan commented on docs/src/main/asciidoc/config-reference.adoc
> +specification. Moreover, there are several additional features which are made available by Quarkus itself.
Would be good to link to the MP Config spec like was done before

2021-03-12 14:08 UTC, kenfinnigan commented on docs/src/main/asciidoc/micrometer.adoc
> -== Support for the MicroProfile Metrics API
These changes should be reverted.

This section is specifically about enabling the use of MP Metrics APIs with Micrometer, nothing to do with SmallRye Metrics.

cc @ebullient

2021-03-12 14:09 UTC, kenfinnigan commented
@gsmet There was a discussion yesterday around making it clearer that Quarkus is using SmallRye projects, which does implement MicroProfile specifications, to make it easier to highlight when SmallRye goes beyond a specification

2021-03-13 11:10 UTC, gsmet commented
There are now conflicts due to the master -> main change.

2021-03-15 14:19 UTC, radcortez commented
> There are now conflicts due to the master -> main change.

Fixed.

Also added the redirects in https://github.com/quarkusio/quarkusio.github.io/pull/925. Do we need to add an initial version of the renamed guides or everything is synced automatically?

2021-03-18 12:33 UTC, gsmet commented
@radcortez no, they will be added automatically. I just need to think about merging the PR after the release :).

@kenfinnigan could you have another look?

2021-03-18 13:18 UTC, kenfinnigan approved these changes

2021-03-18 13:22 UTC, merged

2021-03-18 13:23 UTC, radcortez commented
Thanks!