use application name as default Kafka consumer group.id
quarkusio/quarkus pull request #15678
Opened 2021-03-12 14:57 UTC by Ladicek

Resolves #15632

2021-03-12 15:00 UTC, cescoffier approved these changes
Looks good to me! 

I just made a small comment.

2021-03-12 15:01 UTC, cescoffier requested changes

2021-03-12 15:01 UTC, cescoffier commented on extensions/kafka-client/runtime/src/main/java/io/quarkus/kafka/client/runtime/KafkaRuntimeConfigProducer.java
> +            properties.put(GROUP_ID, app.name.get());
Should we "kafka.group.id" not just "group.id"

2021-03-12 15:02 UTC, Ladicek commented
Draft to let CI run in my fork.

I was thinking how to add a test for this, but couldn't find anything. I don't think SmallRye Reactive Messaging lets me access the internals, through which I could verify if the group ID is really set. I did verify it manually with a simple example application though.

Also, #15632 says that a generated ID is only used in dev mode -- I couldn't find that anywhere in Quarkus code, and the SmallRye Reactive Messaging code generated a UUID unconditionally. So I think #15632 is just mistaken.

2021-03-12 15:03 UTC, Ladicek commented on docs/src/main/asciidoc/kafka.adoc
> +If that is not set either, a unique, generated id is used.
Makes sense, I'll add something like that.

2021-03-12 15:09 UTC, geoand commented
Interesting coincidence, I just opened https://github.com/quarkusio/quarkus/pull/15680 :)

2021-03-12 15:12 UTC, Ladicek commented on docs/src/main/asciidoc/kafka.adoc
> +If that is not set either, a unique, generated id is used.
Done.

2021-03-12 15:12 UTC, Ladicek commented
@geoand I'm fine with rebasing this on top of #15680 as well, so if you get to merging your first, please do :-)

2021-03-12 15:14 UTC, geoand commented
No need, I'll wait :)

2021-03-12 16:27 UTC, Ladicek commented
CI passed in my fork.

2021-03-12 20:07 UTC, merged

2021-04-02 17:08 UTC, wernert75 commented
In principle, I think that the change is good. 
However, it now contradicts the doc: 

"A unique string that identifies the consumer group the application belongs to. If not set, a unique, generated id is used
Type: string"

In a special case I need the previous behavior of a randomly generated group.id. How can I restore this behavior?

2021-04-06 06:41 UTC, Ladicek commented
It shouldn't contradict the doc, as I updated the doc in the same commit :-)

If you want your group ID random, you can manually generate a random string and put it into an env var (`KAFKA_GROUP_ID`), for example.

2021-04-06 08:06 UTC, cescoffier commented
As I said on zulip, using a generated UUID needs to be a conscientious decision.

2021-04-06 08:23 UTC, wernert75 commented
Thank you for your answer. 

I agree with you. I think it's a good change. And using a generated UUID schould be a conscientious decision.

But the doc seems to be not updated on the website
https://quarkus.io/guides/kafka 

And a mention in the Migration Guide would have saved me a lot of time. ;)  

Thanks again. I will solve it via the configuration. 

Perhaps you will also consider again whether an explicit configuration variable that activates the explicit use of a UUID is possible.

Basically, the issue is that several replicas of one and the same microservice get different Group.IDs, to broadcast a message.

It would be ideal if there could be a kind of "pool" for Group.ids. For example, MyApplication1 ... MyApplication5. If someone has an idea how to solve the problem of assigning exactly one of these GroupIds to each replica via a configuration, I would be very happy to hear about it. 

Translated with www.DeepL.com/Translator (free version)

2021-04-06 08:28 UTC, Ladicek commented
Hmm I wonder how that website is updated, maybe I updated a wrong file? Humm...

2021-04-06 08:38 UTC, Ladicek commented
Ah ah, now I know who to blame: https://github.com/quarkusio/quarkus/commit/8a56a30b516f72ac7ed7e177ac118a831ef6d46a

2021-04-06 08:39 UTC, Ladicek commented
I'll submit a PR to re-add the new docs.

2021-04-06 08:47 UTC, Ladicek commented
Submitted #16262.