Move all RESTEasy Reactive configuration under 'quarkus.resteasy-reactive'
quarkusio/quarkus pull request #16310
Opened 2021-04-07 09:31 UTC by geoand

For the time being, the old `quarkus.rest` config root is still supported,
but that support will be removed once the `vertx-4` branch has been merged
into main (at which point the TCK will be updated to use the new values).

However the old `quarkus.security.jaxrs.deny-unannotated-endpoints` is not
supported

2021-04-07 09:57 UTC, FroMage approved these changes
LGTM

2021-04-07 11:22 UTC, gsmet requested changes, later dismissed
Let's wait for the merge of 2.0 before merging that, please.

2021-04-07 11:25 UTC, geoand commented
> Let's wait for the merge of 2.0 before merging that, please.

Sure yeah

2021-04-07 14:40 UTC, geoand commented
> ## Failing Jobs
> Status 	Name 	Failing step 	Test failures 	Logs 	Raw logs
> hourglass 	Gradle Tests - JDK 11 Linux 	`Build` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286412436?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286412436/logs)
> hourglass 	Gradle Tests - JDK 11 Windows 	`Verify dependencies` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286412467?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286412467/logs)
> hourglass 	JVM Tests - JDK 11 	`Build` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286412234?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286412234/logs)
> hourglass 	JVM Tests - JDK 11 Windows 	`Build` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286412323?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286412323/logs)
> hourglass 	JVM Tests - JDK 15 	`Build` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286412247?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286412247/logs)
> hourglass 	JVM Tests - JDK 8 	`Build` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286412212?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286412212/logs)
> hourglass 	MicroProfile TCKs Tests 	`Verify with Maven` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286413494?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286413494/logs)
> hourglass 	Native Tests - Amazon 	`` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286413155?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286413155/logs)
> hourglass 	Native Tests - Cache 	`` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286413219?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286413219/logs)
> hourglass 	Native Tests - Data1 	`Build` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286412708?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286412708/logs)
> hourglass 	Native Tests - Data2 	`Build` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286412749?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286412749/logs)
> hourglass 	Native Tests - Data3 	`Build` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286412790?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286412790/logs)
> hourglass 	Native Tests - Data4 	`Build` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286412855?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286412855/logs)
> hourglass 	Native Tests - Data5 	`Build` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286412916?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286412916/logs)
> hourglass 	Native Tests - HTTP 	`` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286413256?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286413256/logs)
> hourglass 	Native Tests - Messaging 	`` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286413195?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286413195/logs)
> hourglass 	Native Tests - Misc1 	`` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286413297?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286413297/logs)
> hourglass 	Native Tests - Misc2 	`` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286413322?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286413322/logs)
> hourglass 	Native Tests - Misc3 	`` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286413349?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286413349/logs)
> hourglass 	Native Tests - Misc4 	`` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286413374?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286413374/logs)
> hourglass 	Native Tests - Security2 	`` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286413079?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286413079/logs)
> hourglass 	Native Tests - Security3 	`` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286413115?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286413115/logs)
> hourglass 	Native Tests - Spring 	`` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286413394?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286413394/logs)
> hourglass 	Native Tests - gRPC 	`` 		[Logs](https://github.com/quarkusio/quarkus/runs/2286413423?check_suite_focus=true) 	[Raw logs](https://github.com/quarkusio/quarkus/commit/68fcdea45cb75eb4d8412ef3e3a29ce6cc3e3778/checks/2286413423/logs)

^ doesn't look like it corresponds to what actually happened @gsmet @gastaldi

2021-04-08 06:54 UTC, geoand commented
For good measure, I'll rebase this PR onto main

2021-04-08 06:57 UTC, gsmet commented
@geoand yeah for the bot, it's because I cancelled the build to prioritize the 1.13.1 backport PR. I should probably handle this at the bot level.

2021-04-08 06:57 UTC, merged

2021-04-08 06:59 UTC, geoand commented
@gsmet Gotcha.

I was going to rebase the PR, but since you merged it, no need :)