Ensure that Vert.x runs in its dev-mode when Quarkus is started in dev-mode
quarkusio/quarkus pull request #16527
Opened 2021-04-14 18:38 UTC by geoand

This prevents Vert.x from caching static resources

Fixes: #16524

2021-04-14 19:30 UTC, cescoffier approved these changes
Funny, didn't know that trick.

2021-04-14 19:36 UTC, geoand commented
Neither did I 🙈

2021-04-14 23:22 UTC, stuartwdouglas requested changes
Can we just do System.setProperty() in VertxHttpHotReplacementSetup (which should happen before any Vert.x classes are loaded).

This way it will work from the IDE as well, and is in the extension where it belongs.

2021-04-15 05:14 UTC, geoand commented
> Can we just do System.setProperty() in VertxHttpHotReplacementSetup (which should happen before any Vert.x classes are loaded).
> 
> This way it will work from the IDE as well, and is in the extension where it belongs.

Sure thing. After I made the change I remembered that my change won't affect remote-dev so was planning on doing what you mention anyway

2021-04-15 06:52 UTC, stuartwdouglas approved these changes

2021-04-15 08:01 UTC, merged

2021-04-16 13:22 UTC, famod commented
FTR, I had to reopen #16524.

2021-04-16 13:29 UTC, geoand commented
Okay 👌