Fixed commented highlighted points
quarkusio/quarkus pull request #1653
Opened 2019-03-23 14:47 UTC by ppatierno

The commented highlighted points in the `GreetingResourceTest` file aren't rendered as comments so a copy/paste from web site to the IDE drives to a not buildable source.

2019-03-23 15:11 UTC, dmlloyd requested changes
According to [the manual](https://asciidoctor.org/docs/user-manual/#copy-and-paste-friendly-callouts), if the callouts are being included in copy/paste, then there's an error with the highlighter.

That said - what kind of problem are you seeing?  `//` is a valid comment in Java.

2019-03-23 15:16 UTC, ppatierno commented
I noticed that the source adoc already had `//` but the rendered source on the web site is not useful for copy/paste because it won't include the `//` so the source is wrong from a syntax point of view.
After paste I have something like:

```
@Test    (1)
    public void testHelloEndpoint() {
        given()
          .when().get("/hello")
          .then()
             .statusCode(200)    (2)
             .body(is("hello"));
    }

```

which of course due to (1) and (2) is not compilable.

2019-03-23 15:21 UTC, cescoffier commented
@ppatierno just check from the web site... you are right... 
So, we need to fix this.

2019-03-23 15:23 UTC, dmlloyd commented
OK, so this means that the AsciiDoc syntax highlighter that we're using is rendering wrongly again, or there's a new CSS problem.  I'll file an issue for it.

2019-03-23 15:25 UTC, cescoffier commented
@dmlloyd I guess we missed the "Asciidoctor uses CSS to prevent callouts from being selected." :-D

2019-03-23 15:26 UTC, ppatierno commented
of course mine is not the right solution but at least we won't have copy/paste problem. I am going to close this one. now you know the problem ;)
FYI it's everywhere of course, even here : https://quarkus.io/guides/maven-tooling.html (Maven Configuration section).

2019-03-23 15:26 UTC, closed without merging

2019-03-23 15:28 UTC, dmlloyd commented
I've filed https://github.com/quarkusio/quarkusio.github.io/issues/146 for this issue.

2019-03-23 15:32 UTC, cescoffier commented
I've a fix:

```
i.conum + b {
  user-select: none
}
```

2019-03-25 12:47 UTC, cescoffier commented
The web site has been updated.