adding a small note about Kubernetes Client configuration properties.
quarkusio/quarkus pull request #16593
Opened 2021-04-16 19:57 UTC by rafaeltuelho

Small doc PR based on this thread https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/openshift-extension/near/234538945

2021-04-16 20:34 UTC, machi1990 commented on docs/src/main/asciidoc/deploying-to-kubernetes.adoc
> +Note that the full list of Kubernetes client properties is available in the https://github.com/quarkusio/quarkus/blob/main/extensions/kubernetes-client/runtime-internal/src/main/java/io/quarkus/kuber
We can use the generated documentation reference 
```suggestion
{generated-dir}/config/quarkus-kubernetes-client.adoc
```

2021-04-16 20:35 UTC, machi1990 commented on docs/src/main/asciidoc/deploying-to-kubernetes.adoc
> +Note that the full list of Kubernetes client properties is available in the https://github.com/quarkusio/quarkus/blob/main/extensions/kubernetes-client/runtime-internal/src/main/java/io/quarkus/kuber
See https://github.com/quarkusio/quarkus/blob/7a4201a057c3c52ac428db19b14594ee9824fe61/docs/src/main/asciidoc/datasource.adoc#reactive-datasource-configuration-reference for example on how to include it

2021-04-17 09:09 UTC, geoand commented on docs/src/main/asciidoc/deploying-to-kubernetes.adoc
> +The underline Kubernetes client connection can be configured through properties defined by the Kubernetes Client runtime.
Underlying?

2021-04-17 09:11 UTC, geoand reviewed
Thanks for this!

I added a small note

2021-04-19 14:14 UTC, cescoffier requested changes

2021-04-19 14:14 UTC, cescoffier commented on docs/src/main/asciidoc/deploying-to-kubernetes.adoc
> +The underline Kubernetes client connection can be configured through properties defined by the Kubernetes Client runtime.
I would say something like:

```
You may need to configure the connection to your Kubernetes cluster.
By default, it automatically uses the active _context_ used by `kubectl`. 
...
```

2021-04-19 15:24 UTC, geoand commented
When you are done, please squash the commits.

Thanks!

2021-04-19 16:01 UTC, rafaeltuelho commented
> When you are done, please squash the commits.
> 
> Thanks!

Done!

2021-04-19 16:05 UTC, geoand approved these changes

2021-04-20 04:31 UTC, cescoffier approved these changes

2021-04-20 04:31 UTC, merged