added Amazon SSM extension based on pattern of KMS extension
quarkusio/quarkus pull request #16857
Opened 2021-04-28 00:21 UTC by emattheis

Just like the title says, I created an extension for exposing the Amazon SSM SDK following the existing Amazon KMS extensions as a blueprint. I added a minimal test case and have done some integration in my own products to verify functionality, but there is no new functionality to speak of - it follows the same pattern as all the uniform Amazon clients.

This API is especially useful for those of us looking to store/retrieve dynamic parameters (including encrypted secrets) using the parameter store, and  my testing has focused exclusively on that aspect of the SSM client.

2021-04-28 18:40 UTC, emattheis commented
I created a quickstart for the extension as well: https://github.com/quarkusio/quarkus-quickstarts/pull/849

2021-04-29 03:57 UTC, emattheis commented
I've created a guide for the extension as well

2021-05-02 08:22 UTC, oscerd approved these changes

2021-05-03 16:10 UTC, emattheis commented
Thanks for the approval @oscerd ! What's the process for getting this merged?  I rebased against `main` and the checks were [all successful on my fork](https://github.com/emattheis/quarkus/actions/runs/806852974), but the JDK 11 Windows check still fails on the PR...

2021-05-03 17:15 UTC, oscerd commented
This is a question for the maintainers. I worked on the iam extension and i just wanted to vote up your work by approving :-)

2021-05-11 09:23 UTC, gsmet requested changes
This looks very good, thanks (and sorry for the delay!).

I added some suggestions for the documentation. I'm not sure about the callouts but could you check the generated output to make sure things are OK (the numbers should appear in small circles)?

2021-05-11 09:23 UTC, gsmet commented on docs/src/main/asciidoc/amazon-ssm.adoc
> +One of the more useful features of SSM for microservices is the https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html[Parameter Store], which provides secu
```suggestion
One of the most useful features of SSM for microservices is the https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html[Parameter Store], which provides secure, hierarchical storage for configuration data management and secrets management..
```

2021-05-11 09:23 UTC, gsmet commented on docs/src/main/asciidoc/amazon-ssm.adoc
> +In this example, we will create an application that allows us to store a retrieve parameters to and from SSM parameter store using a RESTful API.
```suggestion
In this example, we will create an application that allows us to store and retrieve parameters to and from SSM parameter store using a RESTful API.
```

2021-05-11 16:11 UTC, emattheis commented on docs/src/main/asciidoc/amazon-ssm.adoc
> +1. Inject a configured path under which to store parameters
cool, I didn't know you could use that notation outside the code blocks, but it does look better that way 👍

2021-05-11 16:22 UTC, emattheis commented
Thanks @gsmet! I update the PR with your suggested changes and rebased against main.

2021-05-11 16:52 UTC, gsmet approved these changes
Cool, thanks. I'll wait for CI and merge!

2021-05-12 12:23 UTC, merged

2021-05-12 12:23 UTC, gsmet commented
Merged, thanks!