Disable DevService if docker is not running
quarkusio/quarkus pull request #16959
Opened 2021-05-03 20:51 UTC by glefloch

This branch adds a check that looks for a running docker daemon. If it's not present, the `DevServicesDatasourceProcessor` build step is not triggered. 

close #16904

2021-05-03 22:38 UTC, stuartwdouglas requested changes
Can we also get a better error message that mentions that docker is an option: https://github.com/stuartwdouglas/quarkus/blob/e7fc52bf892d4507a42cacf1e418feb81c570b39/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSources.java#L126

Basically if you are in dev or test mode with a DS that supports it it should say 'configure the URL or get a working docker', while for prod mode or for DB's that don't support it the message should stay the same.

2021-05-03 22:41 UTC, gastaldi commented on core/deployment/src/main/java/io/quarkus/deployment/util/DockerWorking.java
>  public class DockerWorking implements BooleanSupplier {
Can you rename this class to `IsDockerRunning` to match the existing `BooleanSupplier` classes?

2021-05-03 22:42 UTC, gastaldi commented on core/deployment/src/main/java/io/quarkus/deployment/util/DockerWorking.java
>  public class DockerWorking implements BooleanSupplier {
Also move it to the `io.quarkus.deployment` package

2021-05-04 08:56 UTC, glefloch commented
Thanks for your reviews, I updated the code to address them :)

2021-05-04 08:59 UTC, machi1990 requested changes
Let's also disable it for the mongo extension dev services https://github.com/quarkusio/quarkus/blob/ba39f5d9fe4452294b70d727a2e1dccb7da21853/extensions/mongodb-client/deployment/src/main/java/io/quarkus/mongodb/deployment/DevServicesMongoProcessor.java#L39

2021-05-04 09:12 UTC, glefloch commented
@machi1990 done!

2021-05-04 09:13 UTC, geoand approved these changes
Looks nice, thanks!

2021-05-04 09:53 UTC, machi1990 approved these changes
LGTM

2021-05-04 11:51 UTC, gastaldi approved these changes
Great job!

2021-05-04 13:00 UTC, stuartwdouglas approved these changes

2021-05-04 13:00 UTC, glefloch commented
I'm not sure the CI failure is related..

2021-05-04 13:07 UTC, gastaldi commented
> I'm not sure the CI failure is related..

Doesn't seem to be

2021-05-04 13:08 UTC, merged