Create the structure to handle ADRs
quarkusio/quarkus pull request #16996
Opened 2021-05-05 09:29 UTC by cescoffier

- Create the structure as discussed on https://groups.google.com/d/msgid/quarkus-dev/CB395F5B-5A01-464C-8008-A0E8E7E247E6%40redhat.com?utm_medium=email&utm_source=footer
- Update the template to MADR

2021-05-05 09:32 UTC, gsmet commented
I was wondering if it should be in a specific repo? Frankly the GH search engine is a massive pain and I'm afraid it will be hard to find a decision in the middle of the rest.

2021-05-05 09:44 UTC, gastaldi commented on adr/README.adoc
> +**IMPORTANT:** Once _accepted_, and ADR is immutable. Only its status and date can be updated.
```suggestion
**IMPORTANT:** Once _accepted_, an ADR is immutable. Only its status and date can be updated.
```

2021-05-05 09:48 UTC, gastaldi commented
If these files are supposed to be here, better fix the CI to not run the full build too

2021-05-05 12:39 UTC, cescoffier commented
I'm not against moving them to another repo. However, it would mean that only some people aware of such a repo will follow the PR and evolution. 

About the search engine, the file type may help, but I agree, not the best search engine.

2021-05-05 12:52 UTC, cescoffier commented on adr/README.adoc
> +**IMPORTANT:** Once _accepted_, and ADR is immutable. Only its status and date can be updated.
Fixed, thanks!

2021-05-05 12:53 UTC, cescoffier commented
I've excluded the ADR directory from the build.

2021-05-05 15:23 UTC, FroMage commented
To me they belong in this repo, and can be found by checking it out and using an IDE or file exporer, or by using the explorer view of github and Ctrl-F, no need to use the search box. Or are we expecting hundreds of such ADRs?

2021-05-05 15:33 UTC, FroMage requested changes
This mostly looks good, and I'm in favour of ADRs.

But I see no explanation as to what the process is that leads from `proposed` to either `accepted` or `rejected`.

Is it a vote? What sort? By whom? Time-boxed?

Same for `deprecated`: what's the process to deprecate an ADR? A PR changing its status? Where do we document why it was deprecated and what to use/do instead?

For superceded, I guess the process is that there's a new ADR in the same PR that supercedes the other, right? In the case of RFCs it helps tremendously if the new ADR links to the deprecated ones. We'll probably also have to document why it became superceded (in the old or new ADR?)

2021-05-05 16:38 UTC, cescoffier commented
> But I see no explanation as to what the process is that leads from proposed to either accepted or rejected.
> Is it a vote? What sort? By whom? Time-boxed?

I agree we need some kind of process, but not a heavy one, that would kill everything. 
It should work like the other PRs, the relevant extension maintainer should discuss and decide the outcome. 

> Same for deprecated: what's the process to deprecate an ADR? A PR changing its status? Where do we document why it was deprecated and what to use/do instead?

That's a good question. It's actually interesting as no other ADR describe this process. The status is changed, but no reason given. We should include a reason.

> For superceded, I guess the process is that there's a new ADR in the same PR that supercedes the other, right? In the case of RFCs it helps tremendously if the new ADR links to the deprecated ones. We'll probably also have to document why it became superceded (in the old or new ADR?)

Yes, that should be the same PR, and the status links to the new document. 

I will update the PR with these changes.

2021-05-05 17:22 UTC, cescoffier commented
@FroMage PR udpated. I've added more details about the process.

2021-05-06 08:55 UTC, gsmet commented
I'm more talking about having pull requests lost in the middle of the rest. Not about being able to search files in a specific directory.

Please at least add a triage rule to attach a label to the PRs.

2021-05-06 11:10 UTC, cescoffier commented
+1 for the label. I already created an area/adr label, so I just need to update the bot rules, right?

2021-05-06 11:11 UTC, cescoffier commented
(BTW, I don't expect hundreds of ADR PRs, at least that's my hope)

2021-05-06 12:21 UTC, maxandersen commented
+1 on this. just one suggestion:

I love *adoc* but may I suggest we use markdown for the .adrs as then we can use hackmd.io for collaborative editing (think google doc editing but without the google doc part) on these ? 

btw. what is MADR?

2021-05-07 06:46 UTC, cescoffier commented
@maxandersen I'm not against markdown, but the lack of admonition and xref is a bit annoying. But I don't have a strong opinion (Except that I need to check the link syntax every single time).

MADR is the name of the structure I used as base: https://github.com/adr/madr

2021-05-07 14:53 UTC, FroMage approved these changes

2021-05-07 14:53 UTC, FroMage commented on adr/README.adoc
> +When the participant agrees, the ADR is marked as _accepted_, and the PR is merged.
```suggestion
When the participants agree, the ADR is marked as _accepted_, and the PR is merged.
```

2021-05-07 14:53 UTC, FroMage commented
LGTM, but I think more than just us four should vote on this.

2021-05-07 16:17 UTC, maxandersen requested changes
Missing the auto label rules as @gsmet suggested. 

With respect to .md we can just try hackmd on some as experiment and see if great or not worth jt. Let's not hold back this pr because of that.

2021-05-10 06:12 UTC, cescoffier commented
I added the auto-label rule.

2021-05-10 08:45 UTC, FroMage approved these changes

2021-05-10 08:45 UTC, FroMage commented on adr/README.adoc
> +https://adr.github.io/[ADR] stands _Architectural Decision Records_  and is a way to capture architectural decisions over time.
```suggestion
https://adr.github.io/[ADR] stands for _Architectural Decision Records_  and is a way to capture architectural decisions over time.
```

2021-05-10 16:15 UTC, merged

2021-05-10 16:16 UTC, cescoffier commented
Moving forward, structure and process will be revisited if needed.