Support providing explicit options to VaultTransitSecretEngine sign & verifySignature
quarkusio/quarkus pull request #17032
Opened 2021-05-06 02:32 UTC by kdubb

The `VaultTransitSecretEngine.sign` and `VaultTransitSecretEngine.verifySignature` now have variants that take a `SignVerifyOptions` value.

`SignVerifyOptions` allows specifying the following options from the Vault API:
* `hashAlgorithm` (aka `hash_algorithm`)
* `signatureAlgorithm` - (aka `signature_algorithm`)
* `prehashed`
* `marshalingAlgorithm` - (aka `marshaling_algorithm`)

Some of these options (e.g. `hashAlgorithm`, `signatureAlgorithm` and `prehashed`) can be configured for specific transit keys via Quarkus config. The explicit options provided via `SignVerifyOptions` take precedence over any conifgured values.

2021-05-06 08:59 UTC, sberyozkin commented
LGTM, waiting for Vincent's review

2021-05-06 17:43 UTC, vsevel requested changes

2021-05-06 20:42 UTC, kdubb commented on extensions/vault/runtime/src/main/java/io/quarkus/vault/transit/SignVerifyOptions.java
> +    public Optional<String> getSignatureAlgorithm() {
Done. Returns (possibly null) values now, not optional

2021-05-06 20:44 UTC, kdubb commented on extensions/vault/runtime/src/main/java/io/quarkus/vault/runtime/VaultTransitManager.java
> +            hashAlgorithm = options.getHashAlgorithm().orElse(hashAlgorithm);
Instead of Optional or ternary, I created a simple function `defaultIfNull` method to make it easier to read.

2021-05-06 20:44 UTC, kdubb commented
@vsevel Should be good to go!

2021-05-07 11:07 UTC, sberyozkin commented
@kdubb Can you squash please

2021-05-07 14:45 UTC, kdubb commented
@sberyozkin squashed & updated

2021-05-07 15:45 UTC, vsevel approved these changes

2021-05-07 15:46 UTC, vsevel commented
@kdubb did you rebase on master?
@sberyozkin I think we can mrge. ok for you?

2021-05-07 15:58 UTC, kdubb commented
@vsevel Yes, rebased on master and squashed

2021-05-10 11:57 UTC, merged

2021-05-11 04:33 UTC, vsevel commented
@kdubb thanks for this improvement