Update SmallRye Config to 2.3.0
quarkusio/quarkus pull request #17073
Opened 2021-05-07 16:22 UTC by radcortez

- Fixes #15081
- Fixed #14847

https://github.com/smallrye/smallrye-config/releases/tag/2.3.0

2021-05-13 18:46 UTC, gastaldi approved these changes
LGTM

2021-05-13 18:47 UTC, gastaldi commented
@radcortez can you rebase just so CI can be triggered again and we can certify that the failed test is not caused by this PR?

2021-05-14 11:12 UTC, radcortez commented
> @radcortez can you rebase just so CI can be triggered again and we can certify that the failed test is not caused by this PR?

Sure.

2021-05-17 09:12 UTC, gsmet requested changes
@radcortez I spotted a small thing, could you adjust? Then we will merge.

2021-05-17 09:12 UTC, gsmet commented on extensions/arc/runtime/src/main/java/io/quarkus/arc/config/ConfigPrefix.java
>  @Qualifier
Can you add `@Deprecated` here too?

2021-05-17 10:03 UTC, radcortez commented on extensions/arc/runtime/src/main/java/io/quarkus/arc/config/ConfigPrefix.java
>  @Qualifier
Sure.

2021-05-17 16:55 UTC, gsmet approved these changes

2021-05-17 16:55 UTC, merged