Introduce UberJarResourceMergedBuildItem
quarkusio/quarkus pull request #17077
Opened 2021-05-07 18:30 UTC by gastaldi

Fixes #5677

2021-05-07 18:38 UTC, gsmet submitted a review, later dismissed
I haven't looked at it in detail but it would be better to name it `UberJarMergedResourceBuildItem`.

The way it is right now, it looks like an event that is triggered once resources are merged.

2021-05-08 07:02 UTC, geoand reviewed
It would be nice to have some kind of test for this

2021-05-08 13:45 UTC, gastaldi commented
> It would be nice to have some kind of test for this

Definitely! Can you point me to a test that uses Build Items  for reference?

2021-05-08 15:01 UTC, gastaldi commented
More specifically, this test doesn't work:

```java
package io.quarkus.deployment.pkg.builditem;

import java.io.IOException;
import java.net.URL;
import java.util.Collections;
import java.util.Enumeration;
import java.util.function.Consumer;

import io.quarkus.bootstrap.model.AppArtifact;
import io.quarkus.builder.BuildChainBuilder;
import io.quarkus.test.QuarkusUnitTest;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.JavaArchive;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;

import static org.assertj.core.api.Assertions.assertThat;

class UberJarMergedResourceBuildItemTest {

    @RegisterExtension
    static QuarkusUnitTest runner = new QuarkusUnitTest()
            .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class))
            .withConfigurationResource("application-uber-jar.properties")
            .setForcedDependencies(
                    Collections.singletonList(
                            new AppArtifact("org.apache.cxf", "cxf-rt-transports-http", "3.4.3")
                    ))
            .addBuildChainCustomizer(buildCustomizer());

    @Test
    public void testResourceWasMerged() throws IOException {
        Enumeration<URL> resources = getClass().getClassLoader().getResources("META-INF/cxf/bus-extensions.txt");
        assertThat(resources.hasMoreElements()).isTrue();
        assertThat(resources.nextElement()).isNotNull();
        assertThat(resources.hasMoreElements()).isFalse();
    }

    static Consumer<BuildChainBuilder> buildCustomizer() {
        return (buildChainBuilder ->
                buildChainBuilder
                        .addBuildStep(context ->
                                              context.produce(new UberJarMergedResourceBuildItem("META-INF/cxf/bus-extensions.txt")))
                        .produces(UberJarMergedResourceBuildItem.class)
                        .build()
        );
    }
}
```

2021-05-08 15:05 UTC, geoand commented
Ah darn, you are right.

We would likely need to add the same capability to the prod mode test.

2021-05-08 15:30 UTC, gastaldi commented
Hm, `QuarkusProdModeTest` doesn't seem to work either. I'm adding my test to the `core/test-extension/deployment` because I can't add it to `core/deployment` (it would introduce a circular reference to quarkus-junit5-internal) but then it breaks other build steps 😛  
This is painful.

2021-05-10 12:49 UTC, geoand commented on core/test-extension/deployment/src/test/java/io/quarkus/deployment/pkg/builditem/UberJarIgnoredResourceBuildItemTest.java
> +            System.out.println("RESOURCES: " + resources.size());
Can we assert the content of the file?

2021-05-10 12:57 UTC, gsmet requested changes, later dismissed
The imports need a fix and the tests could be improved a bit. If this is done before tomorrow evening, I can backport it. Thanks!

2021-05-10 13:42 UTC, geoand approved these changes

2021-05-11 02:00 UTC, merged