Basic changes to integrate the new platform model based on the decomposed 'universe' BOM
quarkusio/quarkus pull request #17252
Opened 2021-05-16 14:24 UTC by aloubyansky

Most of this code isn't going to be actually used until we introduce the new platform model in 2.0.
Some parts of these changes are going to change in perspective but they already allow creating projects that use extensions from multiple platform BOMs.
The PR also includes a BOM import alignment checks, i.e. whether the imported platform BOMs belong to the same platform release. In this PR, the detected misalignment results in an error. This should be controlled by a config option though.

2021-05-16 15:19 UTC, famod commented
I cancelled and restarted CI after: https://www.githubstatus.com/incidents/zbpwygxwb3gw

2021-05-18 12:27 UTC, ia3andy requested changes
Added a few comment ;)

2021-05-18 12:27 UTC, ia3andy commented on devtools/gradle/src/main/java/io/quarkus/devtools/project/buildfile/GradleGroovyProjectBuildFile.java
> +    protected boolean importBom(ArtifactCoords coords) {
why not `addBom`?

2021-05-18 12:27 UTC, ia3andy commented on independent-projects/bootstrap/app-model/src/test/java/io/quarkus/bootstrap/model/PlatformImportsTest.java
> +    }
You should start using AssertJ it's so much nicer :) (and also fails logs are nicer)

2021-05-18 12:27 UTC, ia3andy commented on independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/buildtool/gradle-kotlin-dsl/base/build-layout.include.qute
>      implementation(enforcedPlatform("$\{quarkusPlatformGroupId}:$\{quarkusPlatformArtifactId}:$\{quarkusPlatformVersion}"))
so we keep the legacy platform bom for now?

2021-05-18 12:27 UTC, ia3andy commented on independent-projects/tools/codestarts/src/main/java/io/quarkus/devtools/codestarts/core/CodestartSpec.java
> +                @JsonProperty("boms") List<CodestartDep> boms,
Do you see a case were a bom could be declared by a codestart? if not I would drop this, the using the inputData should be enough..

2021-05-18 12:27 UTC, ia3andy commented on independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/commands/handlers/CreateProjectCommandHandler.java
> +        invocation.setValue(BOM_GROUP_ID, bom.getGroupId());
could we move that logic somewhere else?

2021-05-18 12:27 UTC, ia3andy commented on independent-projects/tools/registry-client/src/main/java/io/quarkus/registry/union/Playground.java
> +    public static void main(String[] args) throws Exception {
Why not a test instead?

2021-05-18 12:30 UTC, ia3andy commented on independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/commands/handlers/CreateProjectCommandHandler.java
> +        invocation.setValue(BOM_GROUP_ID, bom.getGroupId());
and test it

2021-05-19 08:06 UTC, aloubyansky commented
@glefloch fyi, I am moving the gradle model interfaces and impl from `gradle-resolver` to `app-model`. Apparently, it looks like, Gradle fails to locate model API if it's not in the same jar. It's weird. But we could perhaps benefit from this move and unify some of model API between Gradle and Maven.

2021-05-19 11:32 UTC, ia3andy approved these changes
Cool :)

2021-05-19 11:45 UTC, merged