Qute - introduce Eval section
quarkusio/quarkus pull request #17276
Opened 2021-05-17 10:38 UTC by mkouba

- to parse and evaluate templates dynamically
- resolves #12792

2021-05-17 12:12 UTC, ia3andy commented
Wow, that's pretty cool! Thanks @mkouba

2021-05-17 12:17 UTC, ia3andy approved these changes
Very nice!

2021-05-18 11:31 UTC, gsmet requested changes

2021-05-18 11:31 UTC, gsmet commented on docs/src/main/asciidoc/qute-reference.adoc
> +1. The template contents is passed directly, i.e. not obtained via an `io.quarkus.qute.TemplateLocator`,
```suggestion
1. The template content is passed directly, i.e. not obtained via an `io.quarkus.qute.TemplateLocator`,
```

2021-05-18 12:02 UTC, gsmet approved these changes
I squashed the commits, looks good now.

2021-05-18 20:19 UTC, merged