Check for WebSocket Upgrade in `hotReplacementHandler`
quarkusio/quarkus pull request #17370
Opened 2021-05-19 17:24 UTC by phillip-kruger

Fix #17327

The handler currently block WebSockets Upgrade requests in Dev Mode. This change basically just check for that.

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

2021-05-19 17:33 UTC, gastaldi approved these changes
LGTM

2021-05-19 18:03 UTC, cescoffier approved these changes

2021-05-19 18:03 UTC, cescoffier commented
Great catch!

2021-05-19 19:09 UTC, michalszynkiewicz commented on extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java
> +                            Thread.currentThread().setContextClassLoader(currentCl);
don't we need TCCL setting in the WS UPGRADE branch too?

2021-05-19 19:59 UTC, tsegismont reviewed
Good job @phillip-kruger 

Since the issue comes from the `hotReplacementHandler`, perhaps you could move the guard to the handler implementation? That would avoid to duplication.

Also, I think you should keep the context class loader setter call in all cases.

2021-05-19 20:00 UTC, phillip-kruger commented
Thanks! I'll update in the morning.

2021-05-19 21:47 UTC, stuartwdouglas requested changes
I don't thinks this is the correct fix, this handler should be updated to not result in 'request already read'

2021-05-19 22:40 UTC, stuartwdouglas commented
Superseded by https://github.com/quarkusio/quarkus/pull/17377

2021-05-19 22:40 UTC, closed without merging

2021-05-19 22:41 UTC, stuartwdouglas commented
The reason why this by itself is not sufficent is that you can get a similar scenario if blocking authentication is in use.

2021-05-20 06:27 UTC, phillip-kruger commented
Thanks @stuartwdouglas !