Update to GraphQL client user guide
quarkusio/quarkus pull request #17590
Opened 2021-06-01 11:54 UTC by jmartisk

Update to reflect the changes performed in https://github.com/quarkusio/quarkus/pull/17556 
If using the typesafe client, the rest client dependency must now be added explicitly.

2021-06-01 12:07 UTC, gsmet requested changes
I think we should add a paragraph about the client you need to use depending on the flavor of RESTEasy stack you are using.

That's not exactly easy to understand.

2021-06-02 09:06 UTC, jmartisk commented
I've added a NOTE explaining the dependency in more detail

2021-06-02 10:04 UTC, gsmet commented on docs/src/main/asciidoc/smallrye-graphql-client.adoc
> +your application depends on it (you can't have both at the same time). If you're only going to use the
It's a bit more complicated than that.
```suggestion
your application depends on the non-reactive RESTEasy stack (you can't mix reactive and non-reactive RESTEasy). If you're only going to use the
```

2021-06-02 12:02 UTC, jmartisk commented
Applied @gsmet 's suggested wording :)

2021-06-02 12:08 UTC, phillip-kruger approved these changes

2021-06-02 13:14 UTC, gsmet approved these changes

2021-06-02 13:14 UTC, merged

2021-06-02 13:14 UTC, gsmet commented
Thanks!