Split out the WebSocket client
quarkusio/quarkus pull request #17751
Opened 2021-06-08 04:35 UTC by stuartwdouglas

This allows the client to be used without
pulling in vertx-http.

2021-06-08 06:16 UTC, cescoffier requested changes
The main question is whether WebSocket should be singular or plural.

2021-06-08 06:16 UTC, cescoffier commented on bom/application/pom.xml
> +                <artifactId>quarkus-websockets-client</artifactId>
why websockets (plural) for the client and websocket (singular) for the server? 
I would go with singular everywhere, but maybe I'm missing the reason.

2021-06-08 06:16 UTC, cescoffier commented on core/deployment/src/main/java/io/quarkus/deployment/Feature.java
> +    WEBSOCKETS_CLIENT,
So here, both are plural.

2021-06-08 06:16 UTC, cescoffier commented on docs/src/main/asciidoc/websockets.adoc
> +artifact includes both client and server support however if you only want the client you can include `quarkus-websockets-client` instead.
Minor - there is a new line that is not required (wrapping probably).

2021-06-08 06:16 UTC, cescoffier commented on extensions/websockets/client/deployment/src/test/java/io/quarkus/undertow/websockets/test/WebSocketClientTestCase.java
> +        server.listen(8081);
you may want to block until the server is started.

2021-06-08 06:16 UTC, cescoffier commented on extensions/websockets/client/deployment/src/test/java/io/quarkus/undertow/websockets/test/WebSocketClientTestCase.java
> +                    vertx.close();
You may want to wait until the instance is closed.
Without you can have leaks and reach the max file descriptor limit.

2021-06-08 06:16 UTC, cescoffier commented on extensions/websockets/client/runtime/src/main/resources/META-INF/quarkus-extension.yaml
> +  - "web-sockets"
Never see this variant... But ok.

2021-06-09 01:19 UTC, stuartwdouglas commented on core/deployment/src/main/java/io/quarkus/deployment/Feature.java
> +    WEBSOCKETS_CLIENT,
The Quarkus artifacts are all plural.

2021-06-09 01:24 UTC, stuartwdouglas commented on extensions/websockets/client/runtime/src/main/resources/META-INF/quarkus-extension.yaml
> +  - "web-sockets"
This was copied from the existing one.

2021-06-09 05:43 UTC, cescoffier approved these changes

2021-06-09 08:31 UTC, merged