Update the SmallRye GraphQL Extension documentation
quarkusio/quarkus pull request #17847
Opened 2021-06-10 20:36 UTC by phillip-kruger

Fix #17827

> Showing some large Film and Hero DTOs using lots of “dumb” accessors, when replacing them with public fields would work just as well and make the docs shorter and easier to read.

I have changed this to rather use Objects with public fields with a note that Objects with private fields and public getters/setter will also work

> Showing @Name("filmId") when it's actually optional and we could use the parameter name, inducing me to falsly believe this was required.

I the example the parameter name and the value in the `@Name` annotation is actually different, so I added a note on that. I also removed the `@Name` annotations on other examples 

> I'm told I need to use @Inject Context by https://quarkus.io/guides/smallrye-graphql#context when trying to add it as a query method parameter appeared to Just Work.

`@Inject` is still useful when using it downstream, i.e in another class, so I added a note on method injection when used within the `@GraphQLApi` class

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

2021-06-10 21:37 UTC, gsmet requested changes
I suggested a few improvements.

2021-06-10 21:37 UTC, gsmet commented on docs/src/main/asciidoc/smallrye-graphql.adoc
> +or as a parameter in you method if you are in the `GraphQLApi` class, example:
```suggestion
or as a parameter in your method if you are in the `GraphQLApi` class, for instance:
```

2021-06-10 21:37 UTC, gsmet commented on docs/src/main/asciidoc/smallrye-graphql.adoc
> +change the parameter name to `filmId` rather than the default `id` that it would be if you omit the `Name` annotation
```suggestion
changes the parameter name to `filmId` rather than the default `id` that it would be if you omit the `@Name` annotation.
```

2021-06-10 21:37 UTC, gsmet commented on docs/src/main/asciidoc/smallrye-graphql.adoc
> +NOTE: For readability we use Objects with public fields, but Objects with private fields with public getters/setters will also work
```suggestion
NOTE: For readability we use classes with public fields, but classes with private fields and getters/setters will also work.
```

2021-06-11 06:26 UTC, phillip-kruger commented
Thanks @gsmet !

2021-06-11 07:19 UTC, gsmet approved these changes

2021-06-11 08:17 UTC, merged

2021-06-11 09:05 UTC, FroMage commented
Thanks!