Improve MongoDB with Panache guide
quarkusio/quarkus pull request #18010
Opened 2021-06-18 16:14 UTC by loicmathieu

- Update link to the latest driver version
- Improve wording
- Add a section about the PojoCodecProvider

Fixes #16399

2021-06-21 07:38 UTC, gsmet requested changes

2021-06-21 07:38 UTC, gsmet commented on docs/src/main/asciidoc/mongodb-panache.adoc
> +== The PojoCodecProvider : easy object to BSON document conversion.
```suggestion
== The PojoCodecProvider: easy object to BSON document conversion.
```

2021-06-21 07:38 UTC, gsmet commented on docs/src/main/asciidoc/mongodb-panache.adoc
> +If you class didn't obey these rules (for example by including a method that starts with `get` but is not a setter),
```suggestion
If your class doesn't obey these rules (for example by including a method that starts with `get` but is not a setter),
```

2021-06-21 08:45 UTC, loicmathieu commented
@gsmet thanks for your review, I applied your suggested changes.

2021-06-23 08:00 UTC, loicmathieu commented
@gsmet can we merge this one ?

2021-06-28 09:00 UTC, gsmet approved these changes

2021-06-28 09:00 UTC, merged

2021-06-28 09:00 UTC, gsmet commented
Yes :).