Fix native error with OTLP exporter for OpenTelemetry
quarkusio/quarkus pull request #18364
Opened 2021-07-02 17:34 UTC by kenfinnigan

Fixes #18314

2021-07-02 18:37 UTC, gsmet requested changes
Nice! Added some small comments.

2021-07-02 18:37 UTC, gsmet commented on extensions/opentelemetry/opentelemetry-exporter-otlp/runtime/src/main/java/io/quarkus/opentelemetry/exporter/otlp/runtime/graal/OtlpExporterSubstitutions.java
> +                            "TLS cerificate configuration only supported with Netty. "
```suggestion
                            "TLS certificate configuration only supported with Netty. "
```

2021-07-02 18:37 UTC, gsmet commented on extensions/opentelemetry/opentelemetry-exporter-otlp/runtime/src/main/java/io/quarkus/opentelemetry/exporter/otlp/runtime/graal/OtlpExporterSubstitutions.java
> +final class Target_io_opentelemetry_exporter_otlp_trace_OtlpGrpcSpanExporterBuilder {
I think it would be nice to have a class level comment explaining why this substitution.

2021-07-02 19:00 UTC, kenfinnigan commented
Thanks for the review @gsmet, made the requested changes

2021-07-02 20:12 UTC, ebullient approved these changes

2021-07-03 09:09 UTC, gsmet approved these changes

2021-07-03 09:09 UTC, merged