Test that the classpath in tests does not contain duplicate entries
quarkusio/quarkus pull request #18484
Opened 2021-07-07 13:21 UTC by yrodiere

Hey @stuartwdouglas , do you think could you have a look at this reproducer? It fails when running tests through failsafe, but not when running tests through failsafe.

## The problem

When running an integration test in native mode and calling `ClassLoader#getResources`, it ends up returning two entries for the same source file: `[file:.../integration-tests/my-project/target/classes/the-resource.xml, jar:file:.../integration-tests/my-project/target/my-project-999-SNAPSHOT.jar!the-resource.xml]`. This is problematic because I have code checking for the unicity of resources, for various reasons beyond the scope of this issue, and that duplication causes a false positive and ultimately an exception. So I'm unable to run some tests in native mode (see https://github.com/quarkusio/quarkus/pull/18417#issuecomment-875586522).

## The cause

From what I can see, the problem is actually that we sometime add some classpath elements to our classloaders even though the corresponding resources are already accessible through the parent classloader.

For surefire tests this does not matter, because the parent classloader uses the same URL for the problematic classpath element (`file:.../target/classes/the-resource.xml`) and ultimately `ClassLoader#getResources` will only return one unique URL.

But for failsafe tests it causes problems because the parent classloader uses the JAR  (`jar:file:.../target/classes/...!the-resource.xml`) while the `QuarkusClassLoader` use the `classes` directory (`file:.../target/classes/the-resource.xml`). So `getResources` end up returning several different URLs for the same underlying resource.

## The fix

I'm not sure how to fix this, however... I've tried removing a few things, but removing [this code in `IntegrationTestUtil`](https://github.com/quarkusio/quarkus/blob/d7bc322026ea16ff1ca67fdb884d8926d04bf1a6/test-framework/junit5/src/main/java/io/quarkus/test/junit/IntegrationTestUtil.java#L218-L222) was not enough, and removing [this code in `CuratedApplication`](https://github.com/quarkusio/quarkus/blob/d7bc322026ea16ff1ca67fdb884d8926d04bf1a6/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java#L278-L280) caused unit tests to fail for some reason.

Evidently, there are multiple classloaders involved, used during different phases, and I'm afraid I'm not familiar enough with this code to make the right changes.

2021-07-07 14:19 UTC, yrodiere commented
For your convenience, here are the test results in native mode (with failsafe):

```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClasspathTestCase.testAugmentationMainClassNoDuplicate:22 1 expectation failed.
Response body doesn't match expectation.
Expected: is "OK"
  Actual: java.lang.AssertionError: during phase 'AUGMENTATION', classpath resources for name 'io/quarkus/it/extension/ClasspathTestEndpoint.class' are not unique as expected; got: [file:/home/yrodiere/workspaces/main/quarkus/integration-tests/test-extension/target/classes/io/quarkus/it/extension/ClasspathTestEndpoint.class, jar:file:/home/yrodiere/workspaces/main/quarkus/integration-tests/test-extension/target/quarkus-test-extension-nativetests-999-SNAPSHOT.jar!/io/quarkus/it/extension/ClasspathTestEndpoint.class]
        at io.quarkus.it.extension.ClasspathTestEndpoint.checkUniqueResource(ClasspathTestEndpoint.java:38)
        at io.quarkus.it.extension.ClasspathTestEndpoint.doGet(ClasspathTestEndpoint.java:26)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:589)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:119)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:290)
        at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:415)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:481)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)

        

[ERROR]   ClasspathTestCase.testAugmentationMainResourceNoDuplicate:30 1 expectation failed.
Response body doesn't match expectation.
Expected: is "OK"
  Actual: java.lang.AssertionError: during phase 'AUGMENTATION', classpath resources for name 'some-resource-for-classpath-test.txt' are not unique as expected; got: [file:/home/yrodiere/workspaces/main/quarkus/integration-tests/test-extension/target/classes/some-resource-for-classpath-test.txt, jar:file:/home/yrodiere/workspaces/main/quarkus/integration-tests/test-extension/target/quarkus-test-extension-nativetests-999-SNAPSHOT.jar!/some-resource-for-classpath-test.txt]
        at io.quarkus.it.extension.ClasspathTestEndpoint.checkUniqueResource(ClasspathTestEndpoint.java:38)
        at io.quarkus.it.extension.ClasspathTestEndpoint.doGet(ClasspathTestEndpoint.java:26)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handle [...]

2021-07-08 00:31 UTC, stuartwdouglas commented
The weirdest thing about this is it only happens in the native build, not the jar file build, and the CL setup should be the same for both.

2021-07-08 01:11 UTC, stuartwdouglas requested changes
I have pushed some fixes to make this build properly, and marked it ready to see if it passes on CI. I saw the double resources once in the debugger, then did not see them again.

2021-07-08 09:42 UTC, yrodiere commented
Thanks for the feedback. Indeed the reproducer was not enough; I was getting the same error as in #18417 when I executed the tests locally, but it turns out I was just using incorrect arguments in my maven command. Really sorry about that.

I changed the reproducers a bit, and **now** you can see the error. Could you please have another look, @stuartwdouglas?

Just run:

```
mvn -T C1 -DskipDocs -DskipTests -DskipITs -DskipExtensionValidation -Dskip.gradle.tests clean install
./mvnw clean install -f integration-tests/test-extension/ -Dnative
```

And you will get:

```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClasspathInGraalITCase>ClasspathTestCase.testAugmentationMainClassNoDuplicate:22 1 expectation failed.
Response body doesn't match expectation.
Expected: is "OK"
  Actual: java.lang.AssertionError: during phase 'AUGMENTATION', classpath resources for name 'io/quarkus/it/extension/ClasspathTestEndpoint.class' are not unique as expected; got: [file:/home/yrodiere/workspaces/main/quarkus/integration-tests/test-extension/target/classes/io/quarkus/it/extension/ClasspathTestEndpoint.class, jar:file:/home/yrodiere/workspaces/main/quarkus/integration-tests/test-extension/target/quarkus-test-extension-nativetests-999-SNAPSHOT.jar!/io/quarkus/it/extension/ClasspathTestEndpoint.class]
        at io.quarkus.it.extension.ClasspathTestEndpoint.checkUniqueResource(ClasspathTestEndpoint.java:45)
        at io.quarkus.it.extension.ClasspathTestEndpoint.doGet(ClasspathTestEndpoint.java:31)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:589)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:119)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:290)
        at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:415)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:481)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

        

[ERROR]   ClasspathInGraalITCase>ClasspathTestCase.testAugmentationMainResourceNoDuplicate:30 1 expectation failed.
Response body doesn't match expectation.
Expected: is "OK"
  Actual: java.lang.AssertionError: during phase 'AUGMENTATION', classpath resources for name 'some-resource-for-classpath-test.txt' are not unique as expected; got: [file:/home/yrodiere/workspaces/main/quarkus/integration-tests/test-extension/target/classes/some-resource-for-classpath-test.txt, jar:file:/home/yrodiere/workspaces/main/quarkus/integration-tests/test-extension/target/quarkus-test-extension-nativetests-999-SNAPSHOT.jar!/some-resource-for-classpath-test.txt]
        at io.quarkus.it.extension.ClasspathTestEndpoint.checkUniqueResource(ClasspathTestEndpoint.java:45)
        at io.quarkus.it.extension.ClasspathTestEndpoint.doGet(ClasspathTestEndpoint.java:31)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.secu [...]

2021-07-09 03:51 UTC, stuartwdouglas commented
The issue with the test was that you were using the same file name for the JVM tests and the native build. The JVM tests run and pass, and write the file:// URL's to the file (as the jar is not built yet), then the native image build runs and appends additional paths to the file.

2021-07-09 03:55 UTC, stuartwdouglas commented
I am having a look at your Hibernate PR.

2021-07-09 04:23 UTC, closed without merging

2021-07-09 06:29 UTC, yrodiere commented
> The issue with the test was that you were using the same file name for the JVM tests and the native build. The JVM tests run and pass, and write the file:// URL's to the file (as the jar is not built yet), then the native image build runs and appends additional paths to the file.

I don't think that's true, because I check each line separately. I.e. if there are two lines, each with a different classpath entry, the assertion won't fail. I will only fail if there is a single line with two entries, demonstrating that a classloader had two entries for the same resource.

> I am having a look at your Hibernate PR.

Thanks.

2021-07-09 06:31 UTC, stuartwdouglas commented
I pushed a commit to the hibernate PR that should fix it.