Add all system properties to args for dev mode.
quarkusio/quarkus pull request #1852
Opened 2019-04-04 03:46 UTC by soul2zimate

User input VM argument is ignored in development mode because it only takes argument starts with **quarkus.**

2019-04-04 06:32 UTC, stalep commented
Looks reasonable, but we should also make the same change to QuarkusDev for Gradle as well.

2019-04-04 09:59 UTC, Sanne commented on devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java
> +                args.add("-D" + i.getKey() + "=" + i.getValue());
Please see comment on line 226: not sure if this is a good idea?

But if we decide to apply the patch, the comment should be updated.

2019-04-04 10:12 UTC, gsmet requested changes
Please don't merge it now. We need to discuss this and we are about to release a new version.

Marking it as "Request changes" so it's not merged blindly.

2019-04-04 10:17 UTC, Sanne commented
Thanks @gsmet , was about to say the same.

We need to find a good balance here, I can see @soul2zimate 's point: it should be really easy to pass such properties transparently, and possibly even automatically as people shouldn't be bothered by this, and be able to expect this to just work.

Maybe by inspecting the properties which were set on the spwaning JVM command line?

2019-04-04 10:22 UTC, gsmet commented
Yes, I agree we need to find a solution and the status quo is not satisfying.

@dmlloyd @stuartwdouglas pretty sure you will have some interesting insights on this one.

2019-04-12 04:54 UTC, geoand commented
I think this is now out of date after the latest changes about dev mode merged to master, right?

2019-04-12 13:46 UTC, stalep commented
yes, this should be fixed now.

2019-04-12 13:46 UTC, closed without merging