Fix Encoding and implement Accept header requirement from spec
quarkusio/quarkus pull request #18551
Opened 2021-07-09 08:00 UTC by phillip-kruger

Fix #18521
And also allow setting of the required encoding in the `Accept` header as per spec:

https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#body

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

2021-07-09 10:02 UTC, jmartisk requested changes
I verified clients providing/requesting specific charsets in JVM mode, but it's not working in native mode - when I send a request with CP1250 encoding, I get

```
java.nio.charset.UnsupportedCharsetException: cp1250
	at java.nio.charset.Charset.forName(Charset.java:529)
	at io.vertx.core.buffer.impl.BufferImpl.toString(BufferImpl.java:100)
	at io.vertx.ext.web.impl.RoutingContextImpl.getBodyAsString(RoutingContextImpl.java:286)
	at io.vertx.ext.web.impl.RoutingContextDecorator.getBodyAsString(RoutingContextDecorator.java:166)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.readBody(SmallRyeGraphQLExecutionHandler.java:182)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.getJsonObjectFromBody(SmallRyeGraphQLExecutionHandler.java:163)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handlePost(SmallRyeGraphQLExecutionHandler.java:88)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doHandle(SmallRyeGraphQLExecutionHandler.java:69)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handleWithIdentity(SmallRyeGraphQLAbstractHandler.java:66)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:48)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:23)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:160)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:158)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:481)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

```

This can be fixed by producing a `NativeImageEnableAllCharsetsBuildItem`. Not sure how much of a performance impact it has (it seems to increase the native binary size by ~6 MB for me), so maybe this could be controlled by a build-time config property? And if that property is false, we would only support UTF8, and if the client wants to work with something else, then reject it?

Also I could imagine a test where a client requests something with a non-UTF8 charset (in the Accept header) and then verifies that the response is encoded that way..

2021-07-09 10:04 UTC, phillip-kruger commented
I wonder if cp1250 is supported at all ?? (in java ?) Did you try any others ?

2021-07-09 10:06 UTC, jmartisk commented
In JVM mode, CP1250 works.
Aaaa, I missed that there is a general `quarkus.native.add-all-charsets` property, that should resolve the problem I mentioned

2021-07-09 10:09 UTC, jmartisk approved these changes
Ok, no need for a new config property, setting `quarkus.native.add-all-charsets` resolves the problem. In that case the only thing missing for me is a small test, I'm +1'ing this

2021-07-09 10:11 UTC, phillip-kruger commented
A test for another encoding ?

2021-07-09 10:12 UTC, jmartisk commented
Yes, like something where a client calls a Query with `Accept: application/json;charset=CP1250`, the server responds with something simple but containing special characters, and the client then verifies that it has the right encoding?

2021-07-09 10:13 UTC, phillip-kruger commented
Ok fair, let me add that

2021-07-09 12:43 UTC, phillip-kruger commented
@jmartisk - added tests, once ci complete I think we can merge ?

2021-07-09 16:03 UTC, jmartisk requested changes

2021-07-09 16:03 UTC, jmartisk commented on extensions/smallrye-graphql/deployment/src/test/java/io/quarkus/smallrye/graphql/deployment/GraphQLTest.java
> +        m.put("quarkus.native.add-all-charsets", "true");
If I'm not mistaken unit tests don't support native mode, this would be only needed inside `integration-tests`

2021-07-09 18:23 UTC, phillip-kruger commented
Thanks @jmartisk !

2021-07-12 06:45 UTC, jmartisk approved these changes

2021-07-12 06:45 UTC, merged