Enable the registry client by default in the dev tools
quarkusio/quarkus pull request #18561
Opened 2021-07-09 10:57 UTC by aloubyansky

This PR shows the minimal changes necessary to switch the dev tools to the registry client as the default source of extension metadata and using the `io.quarkus:quarkus-bom` platform for the tests.

2021-07-09 10:58 UTC, aloubyansky commented
fyi @maxandersen @ebullient @gastaldi @ia3andy

2021-07-12 16:42 UTC, ebullient requested changes

2021-07-12 16:42 UTC, ebullient commented on devtools/cli/src/main/java/io/quarkus/cli/common/RegistryClientMixin.java
> +    boolean useRegistryClient = true;
will need to add a test (using --dry-run) to make sure the behavior is the same once the default flips. See #18625

2021-07-12 19:19 UTC, maxandersen commented
I want to enable this but we need to make sure registry is stable/scaled and no matter what have well defined fallback. 

The first part is Ongoing - but what is the fallback we currently have in case registry is not reachable ?

2021-07-20 15:08 UTC, ebullient approved these changes

2021-07-20 16:07 UTC, ebullient approved these changes

2021-07-20 20:54 UTC, ebullient approved these changes

2021-07-21 05:13 UTC, merged