Use code instead of provides-code as extension tag
quarkusio/quarkus pull request #18568
Opened 2021-07-09 13:39 UTC by ia3andy

2021-07-09 13:46 UTC, aloubyansky approved these changes

2021-07-12 08:11 UTC, gsmet requested changes
Tests should also be updated.

2021-07-12 15:49 UTC, ia3andy commented
> Tests should also be updated.

Sometime I am wondering if you are not a Quarkus bot 😂

2021-07-13 07:54 UTC, gsmet approved these changes

2021-07-13 07:54 UTC, merged