Document quarkus.uuid usage in the kafka reference guide
quarkusio/quarkus pull request #18619
Opened 2021-07-12 15:05 UTC by cescoffier

Document the usage of ${quarkus.uuid} to get a unique Kafka consumer group every time

2021-07-12 20:33 UTC, ozangunalp requested changes

2021-07-12 20:33 UTC, ozangunalp commented on docs/src/main/asciidoc/kafka.adoc
> +To always process the records from a topic from the first one, you need a unique consumer group.
I suggest :
```suggestion
If you want to process records from a topic from its beginning, you need to set `auto.offset.reset = earliest` **and** create a new consumer group, with an unused `group.id`. 
Quarkus generates a UUID that changes between two executions (including in dev mode). 
So you are sure no other consumer group uses it and you receive a new unique group id every time your application starts.
```

2021-07-13 11:26 UTC, gsmet requested changes
The text is a bit weird, typically you have `Quarkus generates a UUID that changes between two executions (including in dev mode).` twice.

And having `So, you are sure no other consumer uses it` just after `So you are sure no other consumer group uses it` also reads funny.

2021-07-13 11:43 UTC, ozangunalp requested changes
@gsmet true :) 

I think @cescoffier applied my change suggestion as is. I was thinking of removing the following lines.

2021-07-13 11:43 UTC, ozangunalp commented on docs/src/main/asciidoc/kafka.adoc
> +So, you are sure no other consumer uses it (so your consumer is the only one in the group).
```suggestion
```

2021-07-13 11:43 UTC, ozangunalp commented on docs/src/main/asciidoc/kafka.adoc
> +You also need to receive a new value every time you start your application.
```suggestion
```

2021-07-13 11:43 UTC, ozangunalp commented on docs/src/main/asciidoc/kafka.adoc
> +Quarkus generates a UUID that changes between two executions (including in dev mode).
```suggestion
```

2021-07-19 06:34 UTC, cescoffier commented
I've reformatted the paragraph to avoid duplications.

2021-07-19 06:42 UTC, ozangunalp approved these changes

2021-07-20 12:30 UTC, gsmet approved these changes

2021-07-20 12:30 UTC, merged