CLI: Add debugPort to DevModeLauncher
quarkusio/quarkus pull request #18687
Opened 2021-07-14 16:39 UTC by ebullient

Allow specification of a debugPort (old debug={port} will have precedence) to allow specification of host:port for connecting to a remote debugger (client-mode).

2021-07-14 21:32 UTC, stuartwdouglas requested changes

2021-07-14 21:32 UTC, stuartwdouglas commented on core/deployment/src/main/java/io/quarkus/deployment/dev/QuarkusDevModeLauncher.java
> +        if (debug != null && debug.toLowerCase().equals("client")) {
What if debug=false?

2021-07-14 21:32 UTC, stuartwdouglas commented on core/deployment/src/main/java/io/quarkus/deployment/dev/QuarkusDevModeLauncher.java
> +    final Pattern valid_debug = Pattern.compile("^(true|false|client|[0-9]+)$");
I know it's minor but can you make this validDebug.

2021-07-15 10:46 UTC, ebullient commented on core/deployment/src/main/java/io/quarkus/deployment/dev/QuarkusDevModeLauncher.java
> +        if (debug != null && debug.toLowerCase().equals("client")) {
d'oh! =) Yes. I'll fix that.

2021-07-15 11:46 UTC, stuartwdouglas approved these changes

2021-07-16 11:41 UTC, merged