add support for GraalVM RuntimeReflection's 'finalIsWritable' parameter
quarkusio/quarkus pull request #1881
Opened 2019-04-05 07:11 UTC by devauxbr

# Rationale

I'm a heavy user of [JanusGraph database](https://janusgraph.org/) integrated with the [TinkerPop](http://tinkerpop.apache.org/) [gremlin-driver](http://tinkerpop.apache.org/docs/current/reference/#gremlin-java). The driver makes heavy use of reflections in order to deserialize requests and response from JanusGraph DB. It relies on a shaded version of [Kryo](https://github.com/EsotericSoftware/kryo) for the plumbing.

Since the announcement of Quarkus a few weeks ago, I've been working on a POC on my spare time for creating a quarkus extension for the gremlin-driver, registering necessary classes for reflection, etc. 

Today I am stuck as I discovered that in order to deserialize a [RelationIdentifier](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/RelationIdentifier.java) instance, Kryo needs to set final fields. Therefore it faces the dreadful SubstrateVM error `java.lang.IllegalAccessException: Cannot set final field: org.janusgraph.graphdb.relations.RelationIdentifier.inVertexId. Enable by specifying "allowWrite" for this field in the reflection configuration.`

# Solution

The [SubstrateVM reflection guide](https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md#manual-configuration) states that 

> In order to write a field that is declared final, the `allowWrite` attribute must be specified for that field

Problem is : this statement refers to the manual configuration based on a JSON file, and Quarkus does not rely on this file, but automatically generates a [Feature](https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/Feature.java) instead. This generated Feature registers classes for reflection via the [RuntimeReflection](https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/RuntimeReflection.java) static utility methods.

I've been digging through this API and figured that the `register(Field... fields)` method has an overloaded version which accepts a `finalIsWritable` boolean parameter, which has the exact same effect as the `allowWrite` attribute stated above

# Implementation

This PR adds a new optional `finalIsWritable` boolean parameter to the existing Quarkus `ReflectiveClassBuildItem` constructors with a default value of `false`, and uses its value when calling the `register(boolean finalIsWritable, Field... fields)` in the generated `Feature`.

It successfully resolves the previous `IllegalAccessException` at native runtime when I produces a `new ReflectiveClassBuildItem(true, true, true, true, RelationIdentifier.class.getName())` in my POC extension.

If required, I can create and submit a small showcase project along this PR that would demonstrate the whole thing (my POC extension is far from being finalized though...)

2019-04-05 09:16 UTC, Sanne commented
Hi, thanks for this! The rationale and code look reasonable.

Could you just add a test?
You could add some verifications to `io.quarkus.example.test.CoreReflectionInGraalITCase`, or add a dedicated one in the same package.

2019-04-05 09:16 UTC, Sanne requested changes
Looking good but is missing automated tests.

2019-04-05 09:20 UTC, gsmet commented
I wonder if we should use additional methods to set the booleans. We now have four of them and it's not very easy to see what's a call to one of the constructors is supposed to do.

I would keep the existing constructors for compatibility but I think I wouldn't add more and have a `finalWritable(boolean)` method (name and prototype to further refine) returning `this` for chaining.

@stuartwdouglas WDYT?

2019-04-05 09:24 UTC, Sanne commented
@gsmet +1 I wondered the same, but I'd not consider it a blocker to merge the feature.

2019-04-05 09:31 UTC, Sanne commented
A scope question: I see the capability to register `finalIsWritable` of GraalVM is scoped to individual fields.

This PR is applying a flag to classes registered for reflection, so it's applied to all fields of the class.

I'm assuming it could be desireable to have more fine grained control but there's no need to improve this if there's no use case for such detailed control.

@devauxbr I assume that the Kryo use case would just register them all anyway, correct?

2019-04-05 13:00 UTC, dmlloyd commented
I agree that we might want to revisit the scope and granularity here, in this case especially because writable final fields can invalidate many compiler optimizations.

2019-04-05 13:38 UTC, Sanne commented
@dmlloyd you're considering that a requirement for merging?

Personally I'd be fine with how this is proposed as a first step, because we don't have a use case for needing the finer grained option.

2019-04-06 11:48 UTC, devauxbr commented
Hi, thanks for the feedback !

> Could you just add a test?
You could add some verifications to io.quarkus.example.test.CoreReflectionInGraalITCase, or add a dedicated one in the same package.

Sure thing, quickly looking at this module I can see a small issue: the capability added by this PR is required to be used in a quarkus extension, and as it is not used yet in any existing extension (but only in my POC) I cannot test it "as is" in this module.
Nevertheless I have noticed that there is a [quarkus-test-extension](https://github.com/quarkusio/quarkus/tree/master/core/test-extension) in the core module, and it is used in the [integration-tests/test-extension](https://github.com/quarkusio/quarkus/tree/master/integration-tests/test-extension) module. If that's OK I will add my testing logic in both these modules

> I wonder if we should use additional methods to set the booleans. We now have four of them and it's not very easy to see what's a call to one of the constructors is supposed to do.

> I would keep the existing constructors for compatibility but I think I wouldn't add more and have a finalWritable(boolean) method (name and prototype to further refine) returning this for chaining.

I agree that having 4 boolean parameters for a constructor is far from [Uncle Bob's Clean Code standard](https://www.matheus.ro/2018/01/29/clean-code-avoid-many-arguments-functions/) :) I will refactor this to use a Builder in the same way as the one used in [RuntimeBeanBuildItem](https://github.com/quarkusio/quarkus/blob/master/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/RuntimeBeanBuildItem.java) if that's OK

> This PR is applying a flag to classes registered for reflection, so it's applied to all fields of the class.

> I'm assuming it could be desireable to have more fine grained control but there's no need to improve this if there's no use case for such detailed control.

> @devauxbr I assume that the Kryo use case would just register them all anyway, correct?

Correct, at least from my understanding of how Kryo behaves for this use case. If we would want a more fine grained control as you suggest I guess we could add the finalIsWritable parameter to [ReflectiveFieldBuildItem](https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/builditem/substrate/ReflectiveFieldBuildItem.java). But then it would require to enrich the [ReflectionInfo](https://github.com/quarkusio/quarkus/blob/ddf0bbe08a606bd2e8442fd117308d4332df8d44/core/deployment/src/main/java/io/quarkus/deployment/steps/SubstrateAutoFeatureStep.java#L343) data structure and how it is used when building the final Feature. I would leave this to another PR

If you agree with my proposals I should commit the changes by the end of the weekend

2019-04-06 14:28 UTC, devauxbr commented
I have committed the changes 👍

2019-04-10 08:43 UTC, gsmet submitted a review, later dismissed
It all looks good to me but I think the `finalIsWritable` name is not clear enough. Could you change it globally to `finalFieldsWritable`?

The getter would be `areFinalFieldsWritable()`.

WDYT?

2019-04-10 19:32 UTC, devauxbr commented
> It all looks good to me but I think the `finalIsWritable` name is not clear enough. Could you change it globally to `finalFieldsWritable`?
> 
> The getter would be `areFinalFieldsWritable()`.
> 
> WDYT?

I agree 👍 I have committed the change

2019-04-16 09:24 UTC, devauxbr commented
Hi 

Any chance this one could hit 0.14.0 ?

Thanks !

2019-04-16 11:09 UTC, Sanne commented
Hi Bruno, so sorry for the delay, I've been travelling.

I will find some time to review this tomorrow.

On Tue, 16 Apr 2019, 11:24 Bruno Devaux, <notifications@github.com> wrote:

> Hi
>
> Any chance this one could hit 0.14.0 ?
>
> Thanks !
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/quarkusio/quarkus/pull/1881#issuecomment-483582241>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AACmTUHm7mZRRsdMPHJeEBiyZgd1AnCIks5vhZa9gaJpZM4ceTUc>
> .
>

2019-04-16 16:46 UTC, devauxbr commented
Thank you for the prompt reply ! there is no rush, I just wanted to make sure it would be merged before the next release scheduled in 2 weeks :)

2019-04-18 04:59 UTC, stuartwdouglas approved these changes

2019-04-18 09:39 UTC, Sanne approved these changes

2019-04-18 09:39 UTC, merged

2019-04-18 09:41 UTC, Sanne commented
Merged! thanks @devauxbr