Update Keycloak DevConsole to use the authorization code grant by default
quarkusio/quarkus pull request #18902
Opened 2021-07-21 15:28 UTC by sberyozkin

This PR updates KC dev console to use the authorization code grant by default, implicit is not having a good reputation (it was easier to start with), and even though it is a test SPA, it still makes sense to use the code flow by default since it is recommended for SPAs/public clients and KC clients have to be configured to allow the implicit flow - hence a possible mismatch between the real realm configuration and what Dev Console for KC offers by default.
 
Quarkus `web-app` itself uses it too.

2021-07-21 16:20 UTC, gsmet requested changes, later dismissed

2021-07-21 16:20 UTC, gsmet commented on docs/src/main/asciidoc/security-openid-connect-dev-services.adoc
> +If you set `quarkus.keycloak.devservices.grant.type=code` in `applicatin.properties` (this is a default value) then an `authorization_code` grant will be used to acquire both access and ID tokens. Us
```suggestion
If you set `quarkus.keycloak.devservices.grant.type=code` in `applicatin.properties` (this is a default value) then an `authorization_code` grant will be used to acquire both access and ID tokens. Using this grant is recommended to emulate a typical flow where a `Single Page Application` acquires the tokens and uses them to access Quarkus services.
```

2021-07-21 16:20 UTC, gsmet commented on docs/src/main/asciidoc/security-openid-connect-dev-services.adoc
> +If you set `quarkus.keycloak.devservices.grant.type=implicit` in `applicatin.properties` (this is a default value) then an `implicit` grant will be used to acquire both access and ID tokens. Use this
> (this is a default value)

I suppose it is not the default value anymore?

2021-07-21 18:26 UTC, gsmet reviewed
Doc looks good, I'll let @phillip-kruger approve the rest.

2021-07-22 07:13 UTC, phillip-kruger approved these changes
Nice. After this is merge I'll start looking into how we can add the swagger-ui requirements.

2021-07-22 08:07 UTC, merged