Test Mailer NTML authentication
quarkusio/quarkus pull request #18901
Opened 2021-07-21 15:11 UTC by cescoffier

Just a test verifying the NTML authentication support of the mailer.

2021-07-21 16:45 UTC, cescoffier commented
I have tested in native. It works. But I can't use my fake smtp server in a native test.

2021-07-27 23:33 UTC, stuartwdouglas approved these changes

2021-07-27 23:34 UTC, stuartwdouglas commented
I think you could by just running the fake server in the test JVM and having the native image connect to it.

2021-07-27 23:37 UTC, stuartwdouglas requested changes
Actually I just noticed a thread safety issue

2021-07-27 23:37 UTC, stuartwdouglas commented on extensions/mailer/deployment/src/test/java/io/quarkus/mailer/FakeSmtpServer.java
> +            CountDownLatch latch = new CountDownLatch(1);
This latch is not used

2021-07-27 23:37 UTC, stuartwdouglas commented on extensions/mailer/deployment/src/test/java/io/quarkus/mailer/FakeSmtpServer.java
> +    private String[][] dialogue;
I think these should be volatile, as they are set from the test thread but read from the IO thread.

2021-08-01 07:34 UTC, closed without merging