KOGITO-5289 Kogito DRL guide
quarkusio/quarkus pull request #19025
Opened 2021-07-27 15:05 UTC by lucamolteni

2021-07-28 08:59 UTC, jstastny-cz reviewed
Just minor wording comments. I still need to verify the steps using the actual quickstart, will update on that shortly.

2021-08-03 14:13 UTC, gsmet requested changes
Thanks! Spotted a couple of minor things.

2021-08-03 14:13 UTC, gsmet commented on docs/src/main/asciidoc/kogito-drl.adoc
> +This application will approve Loan Applications so we have a class with all the details of the wanted Loan
```suggestion
This application will approve Loan Applications so we have a class with all the details of the wanted Loan:
```

2021-08-03 14:13 UTC, gsmet commented on docs/src/main/asciidoc/kogito-drl.adoc
> +And another class with the details of the Applicant
```suggestion
And another class with the details of the Applicant:
```

2021-08-03 14:13 UTC, gsmet commented on docs/src/main/asciidoc/kogito-drl.adoc
> +To run the microservice in dev mode, use `./mvnw clean compile quarkus:dev`.
```suggestion
To run the microservice in dev mode, use `./mvnw clean quarkus:dev`.
```
compile shouldn't be necessary.

2021-08-03 14:13 UTC, gsmet commented on docs/src/main/asciidoc/kogito-drl.adoc
> +When you're done playing with "dev-mode" you can run it as a standard Java application.
```suggestion
When you're done playing with dev mode you can run it as a standard Java application.
```

2021-08-03 14:13 UTC, gsmet commented on docs/src/main/asciidoc/kogito-drl.adoc
> +To test your application, just send request to the service with giving the person as JSON
```suggestion
To test your application, just send a request to the service with giving the person as JSON
```

2021-08-03 14:13 UTC, gsmet commented on docs/src/main/asciidoc/kogito-drl.adoc
> +In the response, the list of the approved applications will be returned
```suggestion
In the response, the list of the approved applications will be returned:
```

2021-08-03 15:13 UTC, tarilabs reviewed
as spotted by https://github.com/quarkusio/quarkus/pull/18904#issuecomment-891883313

2021-08-03 15:13 UTC, tarilabs commented on docs/src/main/asciidoc/kogito-drl.adoc
> +:extension-status: preview
```suggestion
```

2021-08-03 15:13 UTC, gsmet commented
All my comments are minor, I will finalize this one. Please don't push to it, thanks!

2021-08-03 15:15 UTC, gsmet commented
Everything fixed, let's wait for CI and merge.

2021-08-03 15:15 UTC, gsmet approved these changes

2021-08-03 15:37 UTC, merged

2021-08-03 15:37 UTC, gsmet commented
Thanks!