Fix ClassLoader issue in test mode with Multipart in multi-module project
quarkusio/quarkus pull request #19068
Opened 2021-07-28 15:43 UTC by geoand

Fixes: #19037

2021-07-28 15:55 UTC, geoand commented on extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/MultipartTransformer.java
> -
I debated whether to keep this around for launch modes that are not test, but I think there isn't too much benefit in doing so...

2021-07-28 16:06 UTC, geoand commented on extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/MultipartTransformer.java
> +                    "(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;", false);
I obviously didn't come up with all this myself... I used the Bytecode Viewer plugin (on a sample class I wrote) in IntelliJ which has the capability to "ASM-ify" bytecode

2021-07-28 21:43 UTC, stuartwdouglas requested changes
Let me have a look at what is going on here before we go down this route.

2021-07-29 00:00 UTC, stuartwdouglas commented
Superseded by https://github.com/quarkusio/quarkus/pull/19070

2021-07-29 00:00 UTC, closed without merging