Add ability to clean the DB in DevUI
quarkusio/quarkus pull request #19312
Opened 2021-08-10 06:57 UTC by stuartwdouglas

Fixes #583
Fixes #19303

2021-08-10 07:05 UTC, gsmet requested changes, later dismissed
Let's wait for https://github.com/quarkusio/quarkus/pull/16764#issuecomment-895777440 to land before doing something with this one.

It will probably require a bit more work to be integrated with @TomasHofman 's work.

/cc @TomasHofman @yrodiere

2021-08-10 07:05 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-testing.adoc
> +and recreate the schema. Quarkus can use Liqibase, FlyWay or Hibernate ORM to reset the schema, depending on what is configured.
```suggestion
and recreate the schema. Quarkus can use Liquibase, Flyway or Hibernate ORM to reset the schema, depending on what is configured.
```

2021-08-16 21:38 UTC, stuartwdouglas commented
@gsmet should be all good now.

2021-08-17 14:36 UTC, gsmet requested changes
@stuartwdouglas I rebased and pushed a few small changes to improve the UI.

BUT... there is something very weird, I'm trying it with the `hibernate-orm-quickstart` and when I do:
- mvn clean quarkus:dev
- then `q`

I get:
```
2021-08-17 16:35:05,135 WARN  [io.qua.hib.orm.run.JPAConfig] (Shutdown thread) Unable to close the EntityManagerFactory: io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit@23937bf7: java.lang.IllegalStateException: EntityManagerFactory is closed
	at org.hibernate.internal.SessionFactoryImpl.validateNotClosed(SessionFactoryImpl.java:539)
	at org.hibernate.internal.SessionFactoryImpl.getProperties(SessionFactoryImpl.java:533)
	at io.quarkus.hibernate.orm.runtime.schema.SchemaManagementIntegrator.defaultName(SchemaManagementIntegrator.java:61)
	at io.quarkus.hibernate.orm.runtime.schema.SchemaManagementIntegrator.disintegrate(SchemaManagementIntegrator.java:45)
	at org.hibernate.internal.SessionFactoryImpl$1IntegratorObserver.sessionFactoryClosed(SessionFactoryImpl.java:283)
	at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryClosed(SessionFactoryObserverChain.java:61)
	at org.hibernate.internal.SessionFactoryImpl.close(SessionFactoryImpl.java:846)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.close(JPAConfig.java:161)
	at io.quarkus.hibernate.orm.runtime.JPAConfig.destroy(JPAConfig.java:120)
	at io.quarkus.hibernate.orm.runtime.JPAConfig_Subclass.destroy$$superforward1(JPAConfig_Subclass.zig:282)
	at io.quarkus.hibernate.orm.runtime.JPAConfig_Subclass$$function$$5.apply(JPAConfig_Subclass$$function$$5.zig:32)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.hibernate.orm.runtime.JPAConfig_Subclass.destroy(JPAConfig_Subclass.zig:711)
	at io.quarkus.hibernate.orm.runtime.JPAConfig_Observer_destroy_4d75ae0cbe7e61a766b92c59cd8bbdeb2c1debf7.notify(JPAConfig_Observer_destroy_4d75ae0cbe7e61a766b92c59cd8bbdeb2c1debf7.zig:189)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:307)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:295)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:237)
	at io.quarkus.arc.impl.ArcContainerImpl.shutdown(ArcContainerImpl.java:359)
	at io.quarkus.arc.Arc.shutdown(Arc.java:49)
	at io.quarkus.arc.runtime.ArcRecorder$1.run(ArcRecorder.java:44)
	at io.quarkus.runtime.StartupContext.runAllInReverseOrder(StartupContext.java:83)
	at io.quarkus.runtime.StartupContext.close(StartupContext.java:72)
	at io.quarkus.runner.ApplicationImpl.doStop(ApplicationImpl.zig:924)
	at io.quarkus.runtime.Application.stop(Application.java:203)
	at io.quarkus.runtime.Application.stop(Application.java:155)
	at io.quarkus.runtime.ApplicationLifecycleManager$ShutdownHookThread.run(ApplicationLifecycleManager.java:401)
```

I tried to reproduce it with latest `main` and latest `main` do not seem to have the same issue (I tried 3 times each and I get the error every time with your branch and never with `main`).

No idea how your code could trigger this though...

2021-08-18 00:20 UTC, stuartwdouglas commented
@gsmet looks like something I added for HR caused issues with blocking hibernate. Should be fixed now.

2021-08-18 01:58 UTC, stuartwdouglas commented
@gsmet I think I accidentally pushed this over your changes

2021-08-18 04:40 UTC, stuartwdouglas commented
Never mind, I realized I could manually fetch the commit and apply it from the history on this page.

2021-08-18 07:49 UTC, gsmet commented
OK, cool, let me retest this.

2021-08-18 08:19 UTC, gsmet approved these changes
Looks good now!

2021-08-18 08:19 UTC, merged