config-mapping mocking docs need @InjectMock
quarkusio/quarkus pull request #19421
Opened 2021-08-16 15:14 UTC by edeandrea

In the mocking section it says that the `Server` can be injected as a mock into a Quarkus test class with `@InjectMock`, yet the following code snippet just shows `@Inject`.

2021-08-16 15:36 UTC, gsmet submitted a review, later dismissed
Not sure that's the right fix given https://github.com/quarkusio/quarkus/commit/ad7ca52b5c92a08889f96dcbadaa948bff5ed428#diff-bee9d271f62f1f712b0e5a946ac2504713f9b16c7eee474cf90449367a109812 .

@radcortez WDYT?

2021-08-16 15:39 UTC, edeandrea commented
@gsmet In this example (from that doc)

```java
public class ServerMockProducer {
    @Inject
    Config config;

    @Produces
    @ApplicationScoped
    @io.quarkus.test.Mock
    Server server() {
        return config.unwrap(SmallRyeConfig.class).getConfigMapping(Server.class);
    }
}
```

Are you saying that because `server()` has the `@Mock` annotation that it is already mocked and therefore can be injected simply with `@Inject`?

If so, then the documentation still needs updating, but in the note just below that code snippet rather than in the code snippet itself.

2021-08-18 16:20 UTC, radcortez commented
Yes, it is the text that needs to be updated from `@InjectMock` to just `@Inject`. Do you mind doing the change @edeandrea ? Thanks!

There is also a test here: https://github.com/quarkusio/quarkus/blob/7fd5e0463ebdb06b32a80bbbd713e03997624508/integration-tests/smallrye-config/src/test/java/io/quarkus/it/smallrye/config/AppConfigMockTest.java

2021-08-18 16:21 UTC, radcortez requested changes
Yes, it is the text that needs to be updated from `@InjectMock` to just `@Inject`. Do you mind doing the change @edeandrea ? Thanks!

There is also a test here: https://github.com/quarkusio/quarkus/blob/7fd5e0463ebdb06b32a80bbbd713e03997624508/integration-tests/smallrye-config/src/test/java/io/quarkus/it/smallrye/config/AppConfigMockTest.java

2021-08-23 13:00 UTC, edeandrea commented
@radcortez That test you mention is a test of the spy. In that test you do

```java
AppConfig appConfigSpy = Mockito.spy(appConfig);
```

and then you return `appConfigSpy`, which is already spied upon. In the example I modified it is just doing `return config.unwrap(SmallRyeConfig.class).getConfigMapping(Server.class);`. There is no `Mockito.mock` nor `Mockito.spy`, so is the returned object already a mock? I don't see a test for that use case (unless I'm just not looking in the correct place).

2021-09-06 15:08 UTC, radcortez commented
> In the example I modified it is just doing `return config.unwrap(SmallRyeConfig.class).getConfigMapping(Server.class);`. There is no `Mockito.mock` nor `Mockito.spy`, so is the returned object already a mock? I don't see a test for that use case (unless I'm just not looking in the correct place).

In that example, yes the returned object is already a mock, but is completely empty so you need to fill in the values. What we found out is that developers want to start with their current configuration and then change the values, so I added the spy approach.

2021-09-08 17:01 UTC, radcortez commented
Interesting. I'll have to check this. 

For now, lets just go with use `@InjectMock`in this case.

Thanks!

2021-09-08 17:01 UTC, radcortez approved these changes

2021-09-08 17:02 UTC, merged

2021-09-08 17:03 UTC, edeandrea commented
Thanks @radcortez ! Let me know if you need/want help testing it out. Happy to help!

2021-09-08 17:04 UTC, radcortez commented
> Thanks @radcortez ! Let me know if you need/want help testing it out. Happy to help!

Thanks! You already helped :)