gRPC: support per service interceptors
quarkusio/quarkus pull request #19443
Opened 2021-08-17 08:24 UTC by michalszynkiewicz

fixes #19229

This is a breaking change. With it, global gRPC interceptors have to be annotated with `@GlobalInterceptor`. 
Without it, every CDI bean implementing `ServerInterceptor` was a global interceptor.

2021-08-17 11:44 UTC, cescoffier requested changes
LGTM, but this should be considered as a breaking change and documented. 
So, documentation needs to be updated and the migration guide too.

2021-08-17 12:45 UTC, michalszynkiewicz commented
👍🏻
I'm wondering if it's okay to add it to 2.2 or it should rather be postponed to 2.3

2021-08-17 12:53 UTC, cescoffier commented
I would say 2.3 to be on the safe side.

2021-08-19 14:30 UTC, michalszynkiewicz commented
migration guide update: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.3

2021-08-19 14:30 UTC, michalszynkiewicz commented
I'll also add info to the guides

2021-08-19 18:58 UTC, michalszynkiewicz commented
guides updated

2021-08-20 11:18 UTC, cescoffier approved these changes

2021-08-20 11:19 UTC, merged