Move to JLine 3.x to avoid Jansi 1.x dependency/usage
quarkusio/quarkus pull request #19510
Opened 2021-08-19 14:31 UTC by jaikiran

Potential fix for https://github.com/quarkusio/quarkus/issues/19491

As noted in that discussion, the JLine 2.x is EOLed and its usage it leading to issues described in that bug.

I've done absolutely zero testing of this change. I have only ensured that the whole build compiles and builds fine. I want to make sure there are no basic issues with this change and see how CI reacts. Tomorrow, I will try and get hold of the Windows box again and see if this fixes that original issue.

In the meantime, there are a couple of things to sort out:

-  I see there's a `CreateProjectMojoIT` testcase in the project. I wonder why it didn't catch this issue on our Windows CI setup
- I see that @gastaldi noted in the issue that he might have a way to get rid of the JLine usage in this code altogether, which I think would be the best/ideal thing. I have no historical knowledge of this code, so if that's possible, then I will close this PR and let's go with @gastaldi's approach. One less library dependency to maintain.

2021-08-19 14:39 UTC, gsmet commented
There's a good chance we will want to backport this so I would be in favor of not making too big changes here (and maybe have a followup PR later to remove JLine support). I have no idea how to test that this works though. I'll let @gastaldi chime in.

2021-08-19 14:42 UTC, jaikiran commented
> I have no idea how to test that this works though

This `Prompter` gets used only in 2 Mojos (the CreateProjectMojo and CreateExtensionMojo), so I will run a basic manual test on the Windows box once I get access to it tomorrow.

I'll also check tomorrow why our automated test(s) didn't catch this.

2021-08-19 14:43 UTC, gastaldi commented
I'm building this PR in my Windows VirtualBox and will let you know

2021-08-19 14:53 UTC, jaikiran commented
>I'll also check tomorrow why our automated test(s) didn't catch this.

Ha! Turns out our CI (rightly) uses Maven 3.8.1[1]. I just downloaded this version to do a basic check and turns out 3.8.1 version of Maven ships with `jansi-1.71.1` of Jansi, which is why I believe we didn't see this issue in our CI. It looks like 3.8.2 of Maven brought in this new jansi-2.x version. Release notes don't show anything related to this https://maven.apache.org/docs/3.8.2/release-notes.html. I will have to dig more into their complete changes to see if this is intentional upgrade.

[1] https://github.com/quarkusio/quarkus/blob/main/.mvn/wrapper/maven-wrapper.properties#L1

2021-08-19 15:05 UTC, gastaldi commented
> Release notes don't show anything related to this

@jaikiran looks like it's only mentioned in JIRA: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12316922&version=12349965

2021-08-19 15:09 UTC, jaikiran commented
Yes, it looks like it first got upgrade in Maven 4.x and then was backported into 3.8.2 for this https://issues.apache.org/jira/browse/MNG-6239.

It's probably not a bad thing though. This gives us a chance to move away from JLine 2.x.

2021-08-19 15:18 UTC, jaikiran commented
> I can confirm this works:

Excellent. Thank you for running the tests with this PR. I'll let the GitHub action jobs complete and in a separate personal branch of mine will trigger a GitHub job by upgrading to Maven 3.8.2 to see if there are any other issues that we need to be aware of.

2021-08-19 15:21 UTC, gastaldi commented on independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/utils/Prompter.java
>      public Prompter() throws IOException {
`IOException` is no longer thrown here

2021-08-19 17:20 UTC, gastaldi approved these changes

2021-08-19 23:45 UTC, famod commented
FWIW, I'm working on updating to Maven 3.8.2. This is currently waiting for the Uograde to Gradle 7.2 (sic!).

Btw, we could add `jline:jline` to `bannedDependencies`.

2021-08-20 01:30 UTC, jaikiran commented
The failures in this PR look unrelated. 

As for adding jline:jline as a banned dependency, is that a common thing we do for outdated libraries? Given that the new version of JLine that we are using in this PR uses a completely different package namespace, is banning necessary?

Hello @famod, I'll let you continue with the 3.8.2 work. I was merely interested in a complete run of this PR against 3.8.2, but it doesn't look straightforward given certain other unrelated dependency issues.

2021-08-20 02:20 UTC, gastaldi commented
It makes sense to ban it because it is incompatible with Maven 3.8.2, so +1 to that

2021-08-20 02:48 UTC, jaikiran commented
Done. I've updated the PR to ban `jline:jline`

2021-08-20 05:20 UTC, gastaldi approved these changes

2021-08-20 10:16 UTC, gsmet requested changes
Thanks for this but I really think that we should try to get rid of the warning `WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)`. We fight hard to get our output as clean as possible.

2021-08-21 04:23 UTC, jaikiran commented
> Thanks for this but I really think that we should try to get rid of the warning `WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)`. We fight hard to get our output as clean as possible.

I'll take a look what this warning is about.

2021-08-21 04:41 UTC, jaikiran commented
@gsmet, Done. I've now updated this PR with a change that should prevent that warning message.

2021-08-21 11:52 UTC, jaikiran commented
These latest Microprofile TCK job failures with `NullPointerException` is surprising. My guess is they are not related to the change in this PR. Have these failed before with this exception? I can trigger a fresh run for this PR to see if they go away but I don't want to lose the logs and context from this current failed run, so just checking.

2021-08-21 12:34 UTC, gsmet commented
Yeah, I have seen them failing many times. /cc @radcortez

2021-08-21 12:35 UTC, gsmet approved these changes
Perfect, thanks.

2021-08-21 12:35 UTC, merged