Allow use of PEM certificates in Kafka Streams extension
quarkusio/quarkus pull request #19553
Opened 2021-08-20 22:11 UTC by scholzj

The Kafka Streams extension supports to configure some of the SSL properties at runtime. However, it does not match all the options in latest Kafka Streams API version. In particular the options which can be used for using PEM certificates are missing:
* The `ssl.truststore.certificates` option
* The `ssl.keystore.certificate.chain` and `ssl.keystore.key` options

Using PEM certificates directly is handy, especially in environments such as Kubernetes, where PEM certificates are (unlike PKCS or JKS certificate stores) much more common. This PR adds the missing options so that they can be configured at runtime and used.

In addition to this, the `ssl.key.*` supports some options which do not exist in Kafka - `ssl.key.location` and `ssl.key.type`. This PR removes them.

2021-10-01 12:57 UTC, scholzj commented
Any chance to get this reviewed? I think it is useful addition for anyone running on Kubernetes and other platforms which do not use JKS as standard for certificates.

2021-10-01 13:45 UTC, ozangunalp requested changes
The change seems complete to me. Can we replace config key strings with `SslConfigs.SSL_*_CONFIG` counterparts?

2021-10-01 13:45 UTC, ozangunalp commented
@scholzj I am sorry, I must have missed this while on vacation.

2021-10-01 15:23 UTC, scholzj commented
> The change seems complete to me. Can we replace config key strings with SslConfigs.SSL_*_CONFIG counterparts?

@ozangunalp Should be fixed now, thanks.

2021-10-01 15:48 UTC, ozangunalp approved these changes

2021-10-02 09:37 UTC, cescoffier approved these changes

2021-10-02 09:37 UTC, merged