support cleanup of deleted classes during live reload #1963
quarkusio/quarkus pull request #1966
Opened 2019-04-09 19:11 UTC by machi1990

PR [#1872](https://github.com/quarkusio/quarkus/pull/1872) added support to cleanup deleted config files during live reload. This is a followup PR to enable cleanup of deleted source files (classes). 

See #1772 and #1963 

@gsmet @Sanne @stuartwdouglas

2019-04-10 08:46 UTC, gsmet commented
@machi1990 there are test failures AFAICS:
```
[ERROR] Tests run: 11, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 240.347 s <<< FAILURE! - in io.quarkus.maven.it.DevMojoIT
[ERROR] testThatClassAppCanRun  Time elapsed: 74.619 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in io.quarkus.maven.it.MojoTestBase that uses java.lang.String, java.lang.Stringboolean, booleanjava.util.concurrent.atomic.AtomicReference was not fulfilled within 1 minutes.
	at io.quarkus.maven.it.DevMojoIT.testThatClassAppCanRun(DevMojoIT.java:48)
```
Usually, to debug this sort of things, I run the tests and then go in the project directory created by the test and run things manually to see what's going on.

2019-04-10 08:49 UTC, gsmet commented
Apart from the test failure, I initially asked for a separate issue as I foresee a few issues with classes: typically how do we deal with inner classes?

They should be removed too... but `$` is a valid character in a class name so you can't really drop all the classes with `ClassName$.*\.class`.

We potentially also have an issue with the generated classes, I wonder if we should just drop them all as they will be regenerated anyway.

@stuartwdouglas any thoughts on this?

2019-04-10 09:37 UTC, machi1990 commented
> We potentially also have an issue with the generated classes, I wonder if we should just drop them all as they will be regenerated anyway.

+:1 I wanted to try this approach too.  Would interesting to hear what others think about it.

2019-04-10 10:28 UTC, machi1990 commented
> @machi1990 there are test failures AFAICS:
> 
> ```
> [ERROR] Tests run: 11, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 240.347 s <<< FAILURE! - in io.quarkus.maven.it.DevMojoIT
> [ERROR] testThatClassAppCanRun  Time elapsed: 74.619 s  <<< ERROR!
> org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in io.quarkus.maven.it.MojoTestBase that uses java.lang.String, java.lang.Stringboolean, booleanjava.util.concurrent.atomic.AtomicReference was not fulfilled within 1 minutes.
> 	at io.quarkus.maven.it.DevMojoIT.testThatClassAppCanRun(DevMojoIT.java:48)
> ```
> Usually, to debug this sort of things, I run the tests and then go in the project directory created by the test and run things manually to see what's going on.

Indeed I saw that the build is failing. Thanks for the tip. I'll debug the issue.

2019-04-10 11:39 UTC, machi1990 commented
> Apart from the test failure, I initially asked for a separate issue as I foresee a few issues with classes: typically how do we deal with inner classes?
> 
> They should be removed too... but `$` is a valid character in a class name so you can't really drop all the classes with `ClassName$.*\.class`.

@gsmet Indeed your concern about inner classes being a tricky case (hence not properly handled in this PR) is what caused the test failure. 

The PR proposes to delete all `.class` that are not part of the "current" `source files`. Except that for an inner `.class` file, the source code is never a file in itself hence its deletion. I have a rough idea of what needs to be done in this case but additional input is welcomed.

2019-04-12 00:18 UTC, stuartwdouglas commented
There are two ways you could do this:
- Just assume that anything with the pattern prefix$suffix is from prefix.java. This will likely be fine for java based apps, not sure about other languages.
- Use ASM to parse any 'unmatched' .class files and check their SourceFileAttribute to see which source file they actually came from.

2019-04-12 07:43 UTC, machi1990 commented
Thanks @stuartwdouglas for the inputs.

> * Use ASM to parse any 'unmatched' .class files and check their SourceFileAttribute to see which source file they actually came from.

I'll look into this option.

2019-04-13 19:19 UTC, machi1990 commented
I have gone with the second option as suggested above.  The implementation looks up for the source file attribute and check for the file existence before deciding to delete or not the corresponding class file. 

However I am running into an issue with the CI, I wonder why it times out for Windows and Linux JDK builds. Native Linux build passes and I see no issue with the tests that fails for the other two builds: 

```
2019-04-13T17:56:07.6962915Z [INFO] Total time:  1.994 s
2019-04-13T17:56:07.6971959Z [INFO] Finished at: 2019-04-13T17:56:07Z
2019-04-13T17:56:07.6983057Z [INFO] ------------------------------------------------------------------------
2019-04-13T17:56:07.7410471Z [INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 42.289 s - in io.quarkus.maven.it.CreateProjectMojoIT
2019-04-13T17:56:07.7413954Z [INFO] Running io.quarkus.maven.it.DevMojoIT
2019-04-13T17:58:34.6520046Z [INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 146.844 s - in io.quarkus.maven.it.DevMojoIT
2019-04-13T17:58:34.6520617Z [INFO] Running io.quarkus.maven.it.PackageIT
2019-04-13T17:58:48.8512032Z [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.254 s - in io.quarkus.maven.it.PackageIT
2019-04-13T17:58:48.8515528Z [INFO] Running io.quarkus.maven.it.RemoteDevMojoIT
2019-04-13T18:01:00.1917668Z [INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 131.337 s - in io.quarkus.maven.it.RemoteDevMojoIT  
``` 

I do not have any issue when running `mvn clean install` on my machine, I am on OSX.  

Would you have an idea?

2019-06-04 11:07 UTC, machi1990 commented
> I have gone with the second option as suggested above. The implementation looks up for the source file attribute and check for the file existence before deciding to delete or not the corresponding class file.
> 
> However I am running into an issue with the CI, I wonder why it times out for Windows and Linux JDK builds. Native Linux build passes and I see no issue with the tests that fails for the other two builds:
> 
> ```
> 2019-04-13T17:56:07.6962915Z [INFO] Total time:  1.994 s
> 2019-04-13T17:56:07.6971959Z [INFO] Finished at: 2019-04-13T17:56:07Z
> 2019-04-13T17:56:07.6983057Z [INFO] ------------------------------------------------------------------------
> 2019-04-13T17:56:07.7410471Z [INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 42.289 s - in io.quarkus.maven.it.CreateProjectMojoIT
> 2019-04-13T17:56:07.7413954Z [INFO] Running io.quarkus.maven.it.DevMojoIT
> 2019-04-13T17:58:34.6520046Z [INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 146.844 s - in io.quarkus.maven.it.DevMojoIT
> 2019-04-13T17:58:34.6520617Z [INFO] Running io.quarkus.maven.it.PackageIT
> 2019-04-13T17:58:48.8512032Z [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.254 s - in io.quarkus.maven.it.PackageIT
> 2019-04-13T17:58:48.8515528Z [INFO] Running io.quarkus.maven.it.RemoteDevMojoIT
> 2019-04-13T18:01:00.1917668Z [INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 131.337 s - in io.quarkus.maven.it.RemoteDevMojoIT  
> ```
> 
> I do not have any issue when running `mvn clean install` on my machine, I am on OSX.
> 
> Would you have an idea?

@stuartwdouglas @gsmet not to interrupt in your flow but have you had some time to check the CI issue I described above?  I have not been able to debug it as all the tests are passing in my machine.

Any pointers will be much appreciated.

2019-06-04 13:47 UTC, gsmet commented
@machi1990 yeah sorry, didn't have the time to check that one yet. Could you rebase it and I'll try to see if I can reproduce the issue on my machine.

2019-06-05 20:07 UTC, machi1990 commented
> @machi1990 yeah sorry, didn't have the time to check that one yet. Could you rebase it and I'll try to see if I can reproduce the issue on my machine.

@gsmet thanks for getting back. Rebase done.

2019-06-26 14:57 UTC, emmanuelbernard commented
ping @gsmet

2019-07-05 12:47 UTC, geoand commented
Is this still in progress? I see the tests are failing

2019-07-05 13:22 UTC, gsmet commented
Yes... so I tested that yesterday and I was able to reproduce the failures with JDK 11. I haven't had the time to investigate further, that's why I didn't post.

@machi1990 could you try to run it with JDK 11 and see if you also have the failures.

Then we will need to understand what's going on with Windows but we can do that one step at a time.

2019-07-05 17:45 UTC, machi1990 commented
> Is this still in progress? I see the tests are failing

Hey, @geoand thanks for the ping. It is indeed in progress, I have been rebasing and trying things locally.

> Yes... so I tested that yesterday and I was able to reproduce the failures with JDK 11. I haven't had the time to investigate further, that's why I didn't post.
> 
> @machi1990 could you try to run it with JDK 11 and see if you also have the failures.
> 
> Then we will need to understand what's going on with Windows but we can do that one step at a time.
 
@gsmet 👍  I am on it. Wonder why I did not think of testing on JDK11 before.

2019-07-05 19:35 UTC, geoand commented
Thanks for the update!

2019-07-06 15:32 UTC, machi1990 commented
> Then we will need to understand what's going on with Windows but we can do that one step at a time.

I don't have a Windows machine which could have helped me in figuring out what's going on. I'll probably have to log the invoker output to understand what's going on for the windows tests on CI.

2019-07-06 21:11 UTC, machi1990 commented
@gsmet CI is green :-)  I think we are good for a review now. Thanks for the JDK11 pointer. I managed to pinpoint some few issues I was initially having.

2019-07-10 19:31 UTC, dmlloyd commented
Any updates?  Maybe @stuartwdouglas should take a look here too (if you have time)?

2019-07-11 11:03 UTC, stuartwdouglas requested changes
Other than the minor comment this looks good to me.

2019-07-11 11:03 UTC, stuartwdouglas commented on core/devmode/src/main/java/io/quarkus/dev/RuntimeUpdatesProcessor.java
> +                        final Set<Path> changedPaths = changedSourceFiles.parallelStream()
This should not be using parallelStream(). parallelStream is a win if you have thousands of items, for small collections it is not worth it, especially when just calling .toPath

2019-07-11 11:25 UTC, machi1990 commented
> Other than the minor comment this looks good to me.

Thanks for the review. Comment addressed.

2019-07-11 11:33 UTC, stuartwdouglas approved these changes

2019-07-11 14:12 UTC, merged

2019-07-11 14:13 UTC, gsmet commented
Great work, thanks!

2019-08-07 12:31 UTC, antoniomacri commented
How have you dealt with generated classes?

We have Rocker generating a .class from an html template. The generated class is deleted every time the live reload is issued.

2019-08-07 12:45 UTC, stuartwdouglas commented
@antoniomacri can you file an issue with the details (and ideally a minimal reproducer)?

2019-08-07 14:03 UTC, antoniomacri commented
@stuartwdouglas Done, see https://github.com/quarkusio/quarkus/issues/3448