Support for provider-neutral OIDC Dev UI
quarkusio/quarkus pull request #19969
Opened 2021-09-07 16:23 UTC by sberyozkin

Fixes #18427.

This PR simply makes Dev UI page which is currently only shown when `Dev Services for Keycloak` is started visible when `quarkus.oidc.auth-server-url` already points to a started Keycloak or indeed any other OpenId Connect provider which support the auto-discovery.

As far as the `provider.html` is concerned I just had to do a few `ifs/elses` as a provider like `Auth0` does not return a logout URL, and also does not support returning the code as URL fragment, and do a few minor updates to avoid assuming that all provider URLs are Keycloak based.

Finally I had to move a few handlers to the `quarkus.oidc.devservices` package to reuse between `Dev Services for Keycloak` and generic `OpenId Connect Dev Console` - both are supported by the same `provider.html`. 

Tested with `Keycloak` and `Auth0`.
In a follow up PR I'll do a bit more work to support more token grants with non-Keycloak providers.

2021-09-07 17:57 UTC, phillip-kruger requested changes
LGTM, just some Tests cases failing ? I think the tests needs updating ?

2021-09-07 19:11 UTC, sberyozkin commented
@phillip-kruger Hi Phillip, thanks, yes, just fixed it - as the title is now set dynamically, `Keycloak` is only set as a title if `keycloak.url` is set, `OpenId Connect Dev Console` otherwise - the latter might work better for both cases...

2021-09-07 19:18 UTC, phillip-kruger approved these changes

2021-09-07 23:15 UTC, stuartwdouglas approved these changes

2021-09-08 08:24 UTC, sberyozkin commented
@phillip-kruger @stuartwdouglas thanks, I've been thinking since yesterday about experimenting with the way it is all named depending on whether it is Keycloak or not, but I'll give it a try a bit later

2021-09-08 08:24 UTC, merged