Fix issue with default beans resolution
quarkusio/quarkus pull request #20263
Opened 2021-09-20 05:30 UTC by stuartwdouglas

If there is more than one Foo for Instance<Foo> then default beans are
included in the result list. This result in HTTP basic auth always being
enabled if there is more than one authenticator.

2021-09-20 07:45 UTC, mkouba commented
Well, the behavior of `javax.enterprise.inject.Instance#iterator()` is a bit unclear, esp. when it comes to ambiguous dependencies. The `iterator()` method should "resolve ambiguities", but it's not 100% what this actually means.

Use case 1 - ambiguous dependency exists, but no alternative beans, e.g. `Foo implements Bar` and `Baz implements Bar`
 and `@Inject Instance<Bar>`. It's a common practice that `Instance#iterator()` returns both `Foo` and `Baz`, i.e. no `AmbiguousResolutionException` is thrown even though the dependency is not resolvable. But if we return `[Foo,Baz]` then ambiguities were not truly resolved...

Use case 2 - ambiguous dependency exists, some alternative beans, e.g. `Foo implements Bar` and `@Alternative Baz implements Bar` and `@Alternative Alpha implements Bar` and `@Inject Instance<Bar>`. Should `Instance#iterator()` return `[Foo,Baz,Alpha]` or `[Baz,Alpha]`?

Now if `@DefaultBean` gets into the mix things are even more complicated.

My point is that we should probably define the desired behavior first and document this in the `io.quarkus.arc.InjectableInstance` javadoc as well.

CC @manovotn @Ladicek

2021-09-20 08:08 UTC, stuartwdouglas commented
Well at the moment the behavior is inconsistent. If you have 2 beans, one a default and one not then only the non-default bean will be returned. If you have 3 beans, one default and 2 not then all 3 are returned. 

Security relies on this behavior to allow things to be overridden by the user, however in all the tests we were only adding a single new implementation so this was not picked up.

2021-09-20 08:17 UTC, manovotn commented
@mkouba @stuartwdouglas 
I agree that the spec text is not helping here as it sounds contradictory.
However, looking at CDI TCKs, there are two tests covering this, one without alternatives and one with alternatives.
See https://github.com/eclipse-ee4j/cdi-tck/blob/2.0/impl/src/main/java/org/jboss/cdi/tck/tests/lookup/dynamic/DynamicLookupTest.java#L139-L191

If you go over them, you'll see that the general idea is that you don't throw unsatisfied/ambig exception but you perform bean resolution taking alternatives into consideration. Therefore:

> Use case 1

This should return `[Foo,Baz]`.

> Use case 2

This should return `[Baz,Alpha]` is and only if they have equal priority. Otherwise, you only return the one with highest priority.

> Now if @DefaultBean gets into the mix things are even more complicated.

This can IMO logically follow the train of thoughts above. E.g. you only ever list default bean if it hasn't been replaced by either standard bean or enabled alternative.

2021-09-20 08:18 UTC, mkouba commented
> Well at the moment the behavior is inconsistent...

Yes, it is. My point is that this fix will make it "less inconsistent" but still inconsistent.

I think that we should copy the behavior from Weld, i.e. return the set of "disambiguated beans". I.e. attempt to resolve ambiguities and return the "best" result we have.

2021-09-20 08:21 UTC, mkouba commented
@stuartwdouglas Let me just try to show what I mean on top of your commit...

2021-09-20 08:40 UTC, Ladicek commented
I personally think that this PR makes sense, but I wonder -- is it possible to have more than 1 default bean for given bean type? :-)

2021-09-20 09:04 UTC, mkouba commented
> I personally think that this PR makes sense, but I wonder -- is it possible to have more than 1 default bean for given bean type? :-)

In theory yes, or at least it's not forbidden. And I will have this use case covered in my commit.

2021-09-20 13:40 UTC, manovotn approved these changes
This is now IMO behaving accordingly to specification plus takes care of default beans in a sensible way.

2021-09-21 06:55 UTC, mkouba commented
@stuartwdouglas Why did you remove my commit? Anyway, those test failures are probably not related - e.g. I wasn't able to reproduce the `SpringControllerTest.testInvalidJsonInputAndResult()` failure locally.

2021-09-21 07:45 UTC, mkouba requested changes
The current fix is not entirely correct.

2021-09-21 07:57 UTC, stuartwdouglas commented
oops, I must have screwed up the rebase, sorry, I have fixed.

2021-09-21 08:00 UTC, mkouba approved these changes

2021-09-21 17:35 UTC, gastaldi commented
Test failure is unrelated and flaky (it passes locally for me)

2021-09-21 17:35 UTC, merged