Fix spring-web test failure
quarkusio/quarkus pull request #20291
Opened 2021-09-21 04:12 UTC by stuartwdouglas

2021-09-21 05:59 UTC, geoand approved these changes

2021-09-21 06:43 UTC, geoand commented
Was this intended to fix the `SpringControllerTest.testInvalidJsonInputAndResult` failure?

Asking because it was fixed with https://github.com/quarkusio/quarkus/pull/20271

2021-09-21 06:47 UTC, stuartwdouglas commented
I did not notice that, but do we really want to be adding a resteasy-classic SPI artifact to a resteasy-reactive module?

2021-09-21 06:55 UTC, geoand commented
Damn it, you are right... 

It's just too hard to review all the RESTEasy stuff in the Github UI... It's just too hard to get mixed up regarding the module that is affected... Now I know to pay much more attention.

Would you like to update this PR with a commit that reverts https://github.com/quarkusio/quarkus/pull/20271?

2021-09-21 07:06 UTC, geoand commented
Otherwise, I can do it. I just don't want to have the build broken again before the proper fix is in

2021-09-21 07:32 UTC, yrodiere commented
> I did not notice that, but do we really want to be adding a resteasy-classic SPI artifact to a resteasy-reactive module?

I though that was fine, because the SPI does not depend on resteasy-classic, and it also is very specific to Quarkus. So AFAICS, we could use the same SPI for both.

2021-09-21 07:36 UTC, geoand commented
> I though that was fine, because the SPI does not depend on resteasy-classic, and it also is very specific to Quarkus. So AFAICS, we could use the same SPI for both.

Technically yeah, it's not a problem. But we really want to the two to be totally separate.

2021-09-21 07:58 UTC, stuartwdouglas commented
Should we just have a common SPI module for stuff like this (where it does not actually depend on anything specific to one or the other)?

2021-09-21 08:06 UTC, geoand commented
Yeah, for things that are common, that makes sense.

I'll looke into it after `2.3.0.CR1` is out.

2021-09-22 02:10 UTC, stuartwdouglas commented
I have added an SPI module just with this class as a starting point.

2021-09-22 06:29 UTC, yrodiere requested changes
I think the reason tests are still failing is an import that wasn't updated; see below.

2021-09-22 06:29 UTC, yrodiere commented on extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java
>          }
I know it's a detail, but if you're going to amend the commit anyway...

```suggestion
        jaxRsMethodDefiningAnnotations.addAll(additionalJaxRsResourceMethodAnnotations);
```

2021-09-22 06:29 UTC, yrodiere commented on extensions/hibernate-validator/deployment/src/main/java/io/quarkus/hibernate/validator/deployment/HibernateValidatorProcessor.java
> +        additionalJaxRsResourceMethodAnnotations.forEach((s) -> additional.addAll(s.getAnnotationClasses()));
I think you forgot to update the import of `AdditionalJaxRsResourceMethodAnnotationsBuildItem` from the old SPI (it should import the one from the new SPI).

Maybe you could also remove that class from the old SPI, just to be sure it doesn't get used again by mistake?

2021-09-22 06:31 UTC, yrodiere approved these changes
Damn that was fast.

2021-09-22 08:02 UTC, geoand approved these changes

2021-09-24 00:54 UTC, merged