gRPC: don't start HTTP server
quarkusio/quarkus pull request #20367
Opened 2021-09-23 21:10 UTC by michalszynkiewicz

fixes #20334

2021-09-24 06:57 UTC, michalszynkiewicz commented
the test failures don't look relevant

2021-09-24 12:31 UTC, kenfinnigan approved these changes
Seems ok, but it's been a while since I've looked at this area. Might be worth @ebullient and @stuartwdouglas taking a look to confirm as well.

Is this an approach that Reactive Messaging extensions could take as well? /cc @cescoffier

2021-09-24 12:38 UTC, ebullient commented
NonApplicationRoutePathBuildItem is closely related to the others.. should they move as a set, or do we only consider this one SPI? @stuartwdouglas ?

2021-09-24 21:52 UTC, michalszynkiewicz commented
just a note, I'm not moving `NonApplicationRoutePathBuildItem` here, I just created a way to configure it bringing in vertx-http, the build item stayed where it was.

2021-09-29 13:41 UTC, michalszynkiewicz commented on extensions/vertx-http/deployment-spi/src/main/java/io/quarkus/vertx/http/deployment/spi/NonApplicationRootPathConfigurerBuildItem.java
> +public final class NonApplicationRootPathConfigurerBuildItem extends MultiBuildItem {
as far as I understand they both mean the same, and the former is shorter :)

2021-09-30 01:09 UTC, stuartwdouglas requested changes
We already have devconsole SPI artifacts: https://github.com/quarkusio/quarkus/pull/20465

2021-09-30 08:37 UTC, closed without merging