Simplify the multi-stage Dockerfiles and fix typos
quarkusio/quarkus pull request #20379
Opened 2021-09-24 10:14 UTC by d3473r

Hi,

this PR is one part of two PRs, the other is: https://github.com/quarkusio/quarkus-images/pull/172
These PRs simplify and fix the maven and gradle native multi-stage docker builds.

After the other PR is merged and the base images `ubi-quarkus-native-image` and `ubi-quarkus-mandrel` are updated these simplifications and fixes of the sample Dockerfiles are possible.

Regards,
Fabian

2021-09-26 15:15 UTC, cescoffier requested changes

2021-09-26 15:15 UTC, cescoffier commented on docs/src/main/asciidoc/building-native-image.adoc
> +COPY pom.xml pom.xml
Why did you remove the owner change?

2021-09-26 15:15 UTC, cescoffier commented on docs/src/main/asciidoc/building-native-image.adoc
> +COPY pom.xml pom.xml
Also, do not use "/", it causes issues before (on some systems). You need to be under a new directoyr.

2021-09-26 15:15 UTC, cescoffier commented on docs/src/main/asciidoc/building-native-image.adoc
> +COPY --from=build /project/target/*-runner /work/application
Why /project?

2021-09-26 15:15 UTC, cescoffier commented on docs/src/main/asciidoc/building-native-image.adoc
> +RUN ./gradlew -b /project/build.gradle buildNative
you run it from /project, but the copy is in root. (or do I miss something?)

2021-10-11 10:09 UTC, gsmet commented
I'm closing this one as the OP didn't provide any feedback. Please reopen if needed.

2021-10-11 10:09 UTC, closed without merging