Make sure compile classpath is resolved before test classpath
quarkusio/quarkus pull request #20389
Opened 2021-09-24 19:03 UTC by glefloch

Adds an explicit dependency between `generateCode` and `generateCodeTest` tasks to make sure the compile classpath is resolve before the test classpath. That will avoid to have duplicate variant of dependencies.

close #20315

2021-09-24 19:53 UTC, asodja commented
Alternative that might also work is to set something like that when you set other before resolve actions :
```
project.configurations.findByName("testCompileClasspath").getIncoming().beforeResolve(() -> {
    project.configurations.findByName("compileClasspath").resolve()
});
```

2021-09-26 19:36 UTC, geoand commented
Thanks for this, unfortunately `MultiModuleIncludedBuildTest` is still failing.

2021-09-26 19:38 UTC, glefloch commented
Yes, I’m trying different things as locally it is hard to reproduce..

2021-09-26 22:21 UTC, stuartwdouglas requested changes
This does not actually do what it says in the title, and does not really change the behavior. 

The test classpath can still be created first, and the deployment dependency added twice.

2021-09-26 22:27 UTC, stuartwdouglas commented
I think https://github.com/quarkusio/quarkus/pull/20401 is the correct fix.

2021-09-27 07:06 UTC, geoand commented
Should we now close this?

2021-09-27 07:12 UTC, glefloch commented
closing this in favor of #20401

2021-09-27 07:12 UTC, closed without merging