Integration test for Kafka Oauth with Keycloak
quarkusio/quarkus pull request #20563
Opened 2021-10-06 13:33 UTC by ozangunalp

Creates both a Kafka container and a Keycloak to test OAuth configuration using `io.strimzi:kafka-oauth-client` with the specified version.

2021-10-06 13:47 UTC, cescoffier requested changes

2021-10-06 13:47 UTC, cescoffier commented on integration-tests/kafka-oauth-keycloak/src/test/java/io/quarkus/it/kafka/KafkaKeycloakTestResource.java
> +        keycloak.start();
Does `start` wait for keycloak to be ready?

2021-10-06 13:47 UTC, cescoffier commented on integration-tests/kafka-oauth-keycloak/src/test/java/io/quarkus/it/kafka/KafkaKeycloakTestResource.java
> +            kafka.stop();
Pretty sure that both methods do the same thing.

2021-10-06 13:47 UTC, cescoffier commented on integration-tests/kafka-oauth-keycloak/src/test/java/io/quarkus/it/kafka/containers/KeycloakContainer.java
> +                "/opt/jboss/keycloak/standalone/configuration/certs/ca-truststore.p12");
We would need the complete set of instructions to regenerate the certs.

2021-10-06 13:47 UTC, cescoffier commented on integration-tests/pom.xml
> +                <module>kafka-oauth-keycloak</module>
We need to extend the CI configuration to add that module.

2021-10-06 16:00 UTC, ozangunalp commented on integration-tests/kafka-oauth-keycloak/pom.xml
> +            <version>${strimzi.oauth.version}</version>
I've omitted this because it was contested in #18605. But I guess now that we have a usage in a test we can add it to the BOM.

2021-10-12 09:08 UTC, cescoffier requested changes
One very small thing: extending the CI timeout.
The rest looks good!

2021-10-12 11:19 UTC, cescoffier approved these changes

2021-10-12 17:49 UTC, merged