1774 : Incomplete Maven Goal descriptions
quarkusio/quarkus pull request #2060
Opened 2019-04-14 08:17 UTC by Dufgui

2019-04-14 10:54 UTC, geoand commented
Thanks for the PR @dufgui!

I am guessing that CI is failing because of formatting (I'm on a mobile so it's hard to check), so I propose you do `mvn install -DskipTests -Dno-native` to allow formatting to be fixed automatically.

2019-04-15 08:06 UTC, gsmet requested changes
I added some comments inline. Thanks for the PR.

2019-04-15 08:06 UTC, gsmet commented on devtools/maven/src/main/java/io/quarkus/maven/RemoteDevMojo.java
> + * You can launch forked app directly with {@code dev}
I don't think I would add this sentence. I would just add a final dot to the former one and remove the `<p>`

2019-04-15 08:06 UTC, gsmet commented on devtools/maven/src/main/java/io/quarkus/maven/NativeImageMojo.java
> + * You can build the application before with {@code build}
I think you should just keep `Build a native executable of your application.`. The rest is too verbose and is not really useful IMHO.

2019-04-15 08:06 UTC, gsmet commented on devtools/maven/src/main/java/io/quarkus/maven/ExampleConfigMojo.java
> + * This goal helps in configuring Quarkus Maven project with quarkus-maven-plugin, with an example of configuration file
I would go with just a simple `Creates an example configuration file.`.

2019-04-15 22:14 UTC, Dufgui commented
> This one actually does more than just "build." It actually creates an uber-jar for the application. Be good to mention that in the description.

just if we use the option: uberJar no ?

2019-04-24 09:53 UTC, gsmet approved these changes

2019-04-24 09:53 UTC, merged