gRPC Stork integration without gathering statistics
quarkusio/quarkus pull request #20762
Opened 2021-10-14 10:15 UTC by michalszynkiewicz

2021-10-15 06:56 UTC, mkouba reviewed
I have zero knowledge of Stork and so I'm probably not the best candidate to review this PR...

2021-10-15 09:04 UTC, cescoffier requested changes

2021-10-15 10:19 UTC, aureamunoz approved these changes
LGTM

2021-10-20 14:38 UTC, cescoffier approved these changes

2021-10-20 14:38 UTC, merged