Fix resolution of MediaType when validation errors using Accept headers
quarkusio/quarkus pull request #20863
Opened 2021-10-19 09:34 UTC by Sgitario

The solution is to inject the HttpHeaders to have access to the HTTP headers in the exception mappers for Resteasy Classic and Reactive:

```java
@Context
HttpHeaders headers;
```

And then use a new utility that I called `ValidatorMediaTypeUtil` with some share functionality to get the list of media types from the `@Produces` annotation and to find the matching media type to serialize the validation reports.

Fix https://github.com/quarkusio/quarkus/issues/20859

2021-10-19 10:30 UTC, yrodiere requested changes
Thanks! The solution looks good to me overall. I added a few suggestions, though.

2021-10-19 11:29 UTC, yrodiere approved these changes

2021-10-19 13:43 UTC, yrodiere approved these changes

2021-10-19 13:46 UTC, geoand requested changes
I suggest limiting the change to RESTEasy Classic for now. 
We don't want to have to do reflection in the case of RESTEasy Reactive.
Let's get this on for now and talk about the proper RESTEasy Reactive solution after

2021-10-20 05:29 UTC, geoand approved these changes

2021-10-20 18:59 UTC, merged