Add the Hibernate with Panache in kotlin quickstart and make kotlin package explicit in the doc
quarkusio/quarkus pull request #20877
Opened 2021-10-19 15:06 UTC by sixdouglas

2021-10-19 15:26 UTC, loicmathieu requested changes

2021-10-20 08:10 UTC, loicmathieu approved these changes
LGTM

2021-10-20 08:11 UTC, loicmathieu commented
@gsmet @geoand maybe one of you two wants to make a second review ?

2021-10-20 09:59 UTC, geoand approved these changes

2021-10-20 16:06 UTC, merged