Add support for Amazon lambda tests
quarkusio/quarkus pull request #2097
Opened 2019-04-16 03:27 UTC by stuartwdouglas

2019-04-16 09:54 UTC, gsmet requested changes
I'll let Justin review it but I added one comment.

2019-04-16 09:54 UTC, gsmet commented on extensions/amazon-lambda/runtime/src/main/java/io/quarkus/amazon/lambda/runtime/AmazonLambdaTemplate.java
> +                        e.printStackTrace();
We really should use a logger here and a few lines below (`ex.printStackTrace();`)

2019-04-18 13:35 UTC, mkouba commented
Looks good. @gsmet ok to merge?

2019-04-18 13:37 UTC, gsmet approved these changes

2019-04-18 13:37 UTC, merged

2019-04-18 13:38 UTC, gsmet commented
@mkouba done, thanks for the reminder.

I'm a bit worried about us having hardcoded URLs such as `/2018-06-01/runtime/init/error` but I suppose it can be considered API from the Lambda POV.

In any case, they were already present so it shouldn't block this PR.

2019-04-18 13:40 UTC, mkouba commented
> I'm a bit worried about us having hardcoded URLs

Yes, I'd like to have it configurable or at least use shared constants.