Fix named queries with reactive panache
quarkusio/quarkus pull request #21158
Opened 2021-11-03 00:54 UTC by gilvansfilho

@loicmathieu Here are fix to named queries with reactive panache.

Tests are skipped and I can't realize why. Could you help me with this? 
I am using this command `.\mvnw test -f .\integration-tests\hibernate-reactive-panache\` and having this output [maven.log](https://github.com/quarkusio/quarkus/files/7464756/maven.log)

2021-11-03 06:19 UTC, geoand commented
If you execute `mvn test -f integration-tests/hibernate-reactive-panache -Dstart-containers -Dtest-containers` you should be able to run the tests locally

2021-11-03 08:13 UTC, loicmathieu commented
@gilvansfilho this looks promising, as soon as you successfully launch the tests and mark this PR as ready I'll do a closer review.

2021-11-04 08:27 UTC, loicmathieu requested changes

2021-11-04 08:27 UTC, loicmathieu commented on docs/src/main/asciidoc/hibernate-reactive-panache.adoc
> +    }
```suggestion
    public static Uni<Long> countByStatus(Status status) {
        return count("#Person.countByStatus", Parameters.with("status", status).map());
    }

    public static Uni<Long> updateStatusById(Status status, Long id) {
        return update("#Person.updateStatusById", Parameters.with("status", status).and("id", id));
    }

    public static Uni<Long> deleteById(Long id) {
        return delete("#Person.deleteById", id);
    }
```

2021-11-04 15:54 UTC, loicmathieu approved these changes
LGTM, thanks a lot !

2021-11-05 08:48 UTC, merged