Flyway Dev UI cosmetic updates
quarkusio/quarkus pull request #21223
Opened 2021-11-05 11:58 UTC by phillip-kruger

As discussed here https://github.com/quarkusio/quarkus/pull/20222#issuecomment-957328732, this just adds an info icon, and a modal popup before the migration script is being created.

![flyway_dev_ui](https://user-images.githubusercontent.com/6836179/140507093-de3ae423-00c4-4bc2-aff5-454b67fc8a66.gif)

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

2021-11-05 12:58 UTC, geoand approved these changes
Nice!

2021-11-05 13:13 UTC, gsmet requested changes
I added a few suggestions. I'm not sure `basic files` is explicit enough. I think we need to state that we generate the initial migration file from the schema generated by Hibernate ORM. But I couldn't find a good wording (even the suggestion for the dialog is not very good, I think we can come up with something better).

@Sanne do you have some suggestions for the wording, I know you're good at that :).

2021-11-05 13:13 UTC, gsmet commented on extensions/flyway/deployment/src/main/resources/dev-templates/datasources.html
> +                                and you can then add additional migration files <a href="https://quarkus.io/guides/flyway">as documented</a>
Also I'm usually not for `target="_blank"` but I think it makes sense in this case as it can break the workflow.

2021-11-08 06:10 UTC, phillip-kruger commented
Thanks @gsmet - Changes made

2021-11-08 08:58 UTC, gsmet approved these changes
OK, let's merge, we can tweak the messages later if we have better ideas.

2021-11-08 10:32 UTC, merged