Fix Kerberos module use in Java 17
quarkusio/quarkus pull request #21550
Opened 2021-11-18 20:42 UTC by Sanne

Fixes #21359 

Didn't add a test, but since this should fix the build on GraalVM/Mandrel Java17 I assume we'll get it covered when we'll be able to enable those tests.

2021-11-18 23:56 UTC, gastaldi approved these changes

2021-11-19 07:29 UTC, zakkak requested changes
Hi @Sanne, thanks for taking care of this.

I suggest:
1. adding a comment making clear that this is a work-around for https://github.com/quarkusio/quarkus/issues/21359 and not an actual fix as mentioned by @jerboaa in https://github.com/quarkusio/quarkus/issues/21359#issuecomment-966157244
2. making the addition of the `add-exports` conditional based on whether we are using Java 17 or Java 11 (you can use [`isJava17`](https://github.com/quarkusio/quarkus/pull/21408/files#diff-3c5bfd64ba207dff5858bb31cfabd72c8817eef064e9541a8b8715dff77669ffR108) once https://github.com/quarkusio/quarkus/pull/21408 gets merged)

2021-11-19 09:40 UTC, jerboaa commented
Has this issue been reported to the pg Java driver folks upstream? I'd suggest to also add a reference to such an upstream issue here. I agree, it should be noted it's a work-around.

2021-11-19 09:56 UTC, Sanne commented
@jerboaa I haven't done it yet but yes I'll let them know. Just want to check first if it's not documented already, and I'm not sure it's their problem.

In general, let's bear in mind that:

- Quarkus doesn't leverage Java modularity
- I see GraalVM already does expose a large number of JDK modules in the same way; these parameters are all generated by native-image by default:

```
--add-exports=java.base/com.sun.crypto.provider=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.access.foreign=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.event=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.loader=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.logger=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.module=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.org.xml.sax.helpers=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.perf=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.platform=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.util.xml.impl=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.util.xml=ALL-UNNAMED \
--add-exports=java.base/sun.invoke.util=ALL-UNNAMED \
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.annotation=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.repository=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.tree=ALL-UNNAMED \
--add-exports=java.base/sun.security.jca=ALL-UNNAMED \
--add-exports=java.base/sun.security.provider=ALL-UNNAMED \
--add-exports=java.base/sun.security.util=ALL-UNNAMED \
--add-exports=java.base/sun.text.spi=ALL-UNNAMED \
--add-exports=java.base/sun.util.calendar=ALL-UNNAMED \
--add-exports=java.base/sun.util.locale.provider=ALL-UNNAMED \
--add-exports=java.base/sun.util.resources=ALL-UNNAMED \
--add-exports=java.xml.crypto/org.jcp.xml.dsig.internal.dom=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.events=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.consumer=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.handlers=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal=ALL-UNNAMED \
```

(got this list by using `--native-image-info --verbose`)

So this approach is not particularly new - perhaps GraalVM should add this one to the list?

More in general, even while we add the explicit `--add-exports` during the native-image compilation, end users not adding it explicitly to their project will still get the visibility constraints applied to their code, e.g. the package not being available gets you a compilation failure.

Adding the flag here merely allows to transform existing bytecode into native; such bytecode was suppposedly already validated by javac & the module system, so it's either valid or *intended* to use these modules.

So rather than considering it a workaround I'm inclined to consider this a reasonable solution, but I agree we might want to improve on it if GraalVM introduces something better to deal with modules.

Feel free to change my mind, you are the experts :) Wondering also what @n1hility and @adinn think about this.

2021-11-19 09:58 UTC, merged

2021-11-19 10:40 UTC, zakkak commented
>     * Quarkus doesn't leverage Java modularity

The export is about an internal Java module, so to me this is not about whether Quarkus leverages Java modularity or not, but more about whether Quarkus should **by default** break the stronger encapsulation provided by Java 17, for internal modules, for all Quarkus applications.

You cover this nicely in your reply though so it's not an issue :)

>     * I see GraalVM already does expose a large number of JDK modules in the same way; these parameters are all generated by native-image by default:
> 
> [snip]
> 
> (got this list by using `--native-image-info --verbose`)
> 
> So this approach is not particularly new - perhaps GraalVM should add this one to the list?

Please note that the list you got is for the needs of the Native Image generator itself, not for the application.
If you build a module with `native-image` using `-m` you will get the following:

```
--add-exports=java.base/com.sun.crypto.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.event=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.loader=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.logger=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.misc=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.module=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=java.base/jdk.internal.org.objectweb.asm=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.org.xml.sax.helpers=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.perf=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.ref=org.graalvm.nativeimage.objectfile \
--add-exports=java.base/jdk.internal.reflect=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.util.xml.impl=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.util.xml=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.invoke.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.nio.ch=org.graalvm.nativeimage.objectfile \
--add-exports=java.base/sun.reflect.annotation=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.repository=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.tree=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.jca=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.text.spi=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.calendar=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.locale.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.resources=org.graalvm.nativeimage.builder \
--add-exports=java.xml.crypto/org.jcp.xml.dsig.internal.dom=org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.sparc=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.sparc=jdk.internal.vm.compiler \
--add-exports=jdk.jfr/jdk.jfr.events=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.consumer=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.handlers=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal=org.graalvm.nativeimage.builder \
```

So IMO GraalVM shouldn't add the export we are talking about as it's not being used by GraalVM itself. The export at hand appears to be a prerequisite of the postgres library and should ideally only be exported as needed for applications using this library.

2021-11-19 10:59 UTC, gsmet commented
FTR, I just merged #21408 .

2021-11-19 11:02 UTC, Sanne commented
@zakkak right good points :) But while GraalVM "itself" doesn't need it, it seems clear that many existing libraries need such modules and expect them to be exposed.

What I mean by "Quarkus doesn't leverage the module system" is that we don't need/expect to constrain access to particular modules by selected libraries only - so it's fine to export to ALL-UNNAMED.

Of course I agree that ideally libraries shouldn't have any such dependency, but they do.

2021-11-19 11:04 UTC, jerboaa commented
@Sanne Yes, native-image adds those `add-exports` clauses all over the place, which isn't ideal (as it might hide other JDK compat issues). So it's not a good example to be looking at.

The reason why I think this is a work-around is that it must be possible to trigger a similar issue when *running* some code using the PG driver without said `--add-exports` on JDK 17. Here is the module description of `java.security.jgss`:

```
java.security.jgss@17.0.1
exports javax.security.auth.kerberos
exports org.ietf.jgss
requires java.base mandated
requires java.naming
provides java.security.Provider with sun.security.jgss.SunProvider
qualified exports sun.security.jgss to jdk.security.jgss
qualified exports sun.security.jgss.krb5 to jdk.security.auth
qualified exports sun.security.jgss.krb5.internal to jdk.security.jgss
qualified exports sun.security.krb5 to jdk.security.auth
qualified exports sun.security.krb5.internal to jdk.security.jgss
qualified exports sun.security.krb5.internal.ktab to jdk.security.auth
qualified opens sun.net.www.protocol.http.spnego to java.base
contains sun.security.jgss.spi
contains sun.security.jgss.spnego
contains sun.security.jgss.wrapper
contains sun.security.krb5.internal.ccache
contains sun.security.krb5.internal.crypto
contains sun.security.krb5.internal.crypto.dk
contains sun.security.krb5.internal.rcache
contains sun.security.krb5.internal.util
platform linux-amd64
```

Package `sun.security.krb5` isn't an exported package, yet it's used outside the the exported to modules in https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/util/internal/Unsafe.java#L17..L18

This yields me to believe that usage in the PG driver will end up hitting somebody sometime in the future (latent bug).

2021-11-19 11:06 UTC, Sanne commented
> Quarkus should by default break the stronger encapsulation provided by Java 17, for internal modules, for all Quarkus applications.

BTW I don't think we do this. IF any user code were to refer to any such internal module, you'd get a compilation failure.

These exports only allow existing libraries which have been designed with <17 Java SDK in mind to be compatible. And given the security benefits of the "closed world" mantra I'm not too concerned about it.

But good point for sure, to be considered in the future.

2021-11-19 11:08 UTC, Sanne commented
@jerboaa yes agreed. This code is most likely broken in JVM mode as well (on JDK 17), unless the users export the module explicitly. Which makes me think that the use case is expecting the users to use the export.

Many thanks for the details, I'll forward to the pg team.

2021-11-19 11:13 UTC, jerboaa commented
> These exports only allow existing libraries which have been designed with <17 Java SDK in mind to be compatible.

This makes no sense to me. The PG driver is using JDK internal API to do something. It has no relevance whether it was designed for some older JDK. It's still internal API. It shouldn't be doing it for older JDKs and it will provoke a runtime error (without the `add-exports`) for JDK 17. If they absolutely need that in an exported API, then this can be discussed with OpenJDK folks. So that a future release will have a *public* replacement. This way, the whole ecosystem wins.

2021-11-19 11:18 UTC, Sanne commented
It seems to be tracked at https://github.com/pgjdbc/pgjdbc/issues/2023

I wonder if someone from OpenJDK could help them figure out a better solution?

@jerboaa +1 yes absolutely I agree. Yet it was accessible so "in practice" it was public API and I'm sure many libraries will have similar issues, even if we don't like it.

2021-11-19 13:33 UTC, jerboaa commented
> I wonder if someone from OpenJDK could help them figure out a better solution?

Happy to help them upstream.