Sending Multi<Byte> as files in multipart in REST Client Reactive
quarkusio/quarkus pull request #21569
Opened 2021-11-19 13:17 UTC by michalszynkiewicz

2021-12-01 06:46 UTC, cescoffier requested changes
Looks very good. I would need to test it more.

There are some complicated classes that would deserve a bit of doc.

2021-12-01 06:46 UTC, cescoffier commented on independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/multipart/QuarkusMultipartFormDataPart.java
> +    public Multi<Byte> multiByteContent() {
Something we could improve (later) is to also support Multi<byte[]>, because it's what you receive most of the time (chunks, not bytes one by one).

2021-12-02 08:15 UTC, michalszynkiewicz commented on independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/multipart/MultiByteHttpData.java
> +public class MultiByteHttpData extends AbstractHttpData implements FileUpload {
I added some javadoc.

2021-12-03 11:27 UTC, cescoffier approved these changes

2021-12-06 11:19 UTC, merged