Fix RestClientFallbackConfigSourceInterceptor#iterateNames()
quarkusio/quarkus pull request #21620
Opened 2021-11-22 16:36 UTC by TomasHofman

The fallback interceptor shouldn't do any conversions on properties that are
prefixed with the "%profile." prefixes. The fact that the profile prefix
is present means the property belongs to an inactive profile. The active
profile property names should be already normalized by the
ProfileConfigSourceInterceptor interceptor.

This fixes https://github.com/quarkusio/quarkus/issues/21533

2021-11-22 22:25 UTC, radcortez commented
@TomasHofman you need to run the formatter :)

2021-11-22 22:26 UTC, radcortez requested changes
@TomasHofman you need to run the formatter :)

2021-11-23 08:09 UTC, geoand commented
I force-pushed the formatter change.

2021-11-23 08:09 UTC, geoand commented
Should this be backported to `2.5`?

2021-11-23 09:08 UTC, TomasHofman commented
> Should this be backported to 2.5?

@geoand I think this should be backported, it's a functional fix. Anything I should do regarding backport?

Thanks for fixing the formatting :).

2021-11-23 09:10 UTC, geoand commented
> > Should this be backported to 2.5?
> 
> @geoand I think this should be backported, it's a functional fix. Anything I should do regarding backport?
> 

You don't need to do anything, I'll add the proper label.

> Thanks for fixing the formatting :).

NP!

2021-11-23 11:11 UTC, radcortez approved these changes

2021-11-23 11:12 UTC, merged