gRPC - per-client interceptors
quarkusio/quarkus pull request #21891
Opened 2021-12-02 15:38 UTC by mkouba

- resolves #21648
- make the RegisterInterceptor annotaion repeatable
- refactor server interceptors

2021-12-02 15:42 UTC, mkouba commented
It was a little bit more complex than I thought but the PR is ready now ;-).

@michalszynkiewicz I've replaced the generated `InterceptorStorage` impl with a synthetic bean initialized through a recorder method. It should be a little bit easier to maintain...

IMPL NOTE: `@RegisterClientInterceptor` is currently implemented as a CDI qualifier, otherwise we wouldn't be able to use a shared `@Singleton` synthetic beans for the injected clients. However, this decision may be revisited in the future.

2021-12-02 15:44 UTC, mkouba commented
Note to myself - add a test with multiple `@RegisterClientInterceptor` annotations declared on an injected client.

2021-12-03 13:29 UTC, michalszynkiewicz commented on docs/src/main/asciidoc/grpc-service-consumption.adoc
> +    @RegisterClinetInterceptor(MySpecialInterceptor.class) <1>
```suggestion
    @RegisterClientInterceptor(MySpecialInterceptor.class) <1>
```

2021-12-03 14:54 UTC, cescoffier requested changes

2021-12-03 14:54 UTC, cescoffier commented on docs/src/main/asciidoc/grpc-service-consumption.adoc
> +This annotation is repetable.
```suggestion
This annotation is repeatable.
```

2021-12-03 14:54 UTC, cescoffier commented on docs/src/main/asciidoc/grpc-service-consumption.adoc
> +You can also register the interceptor per injected client with `@io.quarkus.grpc.RegisterClientInterceptor`.
You should mention that this annotation is used on the client (on the injection site), while GlobalInterceptor is on the interceptor.

2021-12-03 14:54 UTC, cescoffier commented on extensions/grpc/deployment/src/test/java/io/quarkus/grpc/client/interceptors/MySecondClientInterceptor.java
> +                                System.out.println("ONMESSAHE - #2");
Shoudl be removed.

2021-12-03 14:54 UTC, cescoffier commented on extensions/grpc/deployment/src/test/java/io/quarkus/grpc/client/interceptors/MyFirstClientInterceptor.java
> +                                System.out.println("ONMESSAHE - #1");
Should be removed.

2021-12-06 08:39 UTC, cescoffier approved these changes

2021-12-06 11:00 UTC, michalszynkiewicz approved these changes

2021-12-06 11:00 UTC, merged