Update tests with coverage docs with Gradle examples
quarkusio/quarkus pull request #21896
Opened 2021-12-02 21:11 UTC by brianwyka

Reference: https://docs.gradle.org/7.3/userguide/jacoco_plugin.html

2021-12-03 03:19 UTC, brianwyka commented
I think this needs some more work on my end.  Thought I had it working, but maybe not yet...  Still seeing some issues when running a combination of plain unit tests and tests with `@QuarkusTest` annotation

2021-12-03 03:31 UTC, brianwyka commented
I'm struggling to get a combined report and the coverage verification to be aligned with the combination of plain unit tests and `@QuarkusTest`

2021-12-03 04:39 UTC, brianwyka commented
Perhaps the `excludes` are not taken into account for the verification.  I think that may be the disconnect here.

2021-12-03 10:41 UTC, glefloch requested changes
Thanks for this @brianwyka. The overall looks good to me. I left some comments about titles and applying the `jacoco` plugin

2021-12-03 10:41 UTC, glefloch commented on docs/src/main/asciidoc/tests-with-coverage.adoc
> +.Maven
I think this can be removed

2021-12-03 10:41 UTC, glefloch commented on docs/src/main/asciidoc/tests-with-coverage.adoc
> +.Gradle
I would more add a sentence like `If you are using Gradle, add the following dependency to our `build.gradle` file: `

2021-12-03 10:41 UTC, glefloch commented on docs/src/main/asciidoc/tests-with-coverage.adoc
> +.Maven
I would also remove the title here

2021-12-03 10:41 UTC, glefloch commented on docs/src/main/asciidoc/tests-with-coverage.adoc
> +.Gradle
I would remove the title here. 
And in the snippet, we also need to add the jacoco plugin in the `plugins` block

2021-12-03 10:41 UTC, glefloch commented on docs/src/main/asciidoc/tests-with-coverage.adoc
> +.Example Configuration
I think I would remove the title here too

2021-12-03 10:41 UTC, glefloch commented on docs/src/main/asciidoc/tests-with-coverage.adoc
> +.Example Configuration
Here I would also remove the title and add the application of the jacoco plugin in the snippet

2021-12-03 12:18 UTC, brianwyka commented
Thanks for the review @glefloch .  I'll make the changes.  However, I think the section on the verification is still inaccurate since it does not work correctly at the moment.  Is there any idea there?

2021-12-03 14:02 UTC, brianwyka commented
I believe I found a workaround to the issue (reported on Gradle):
https://github.com/gradle/gradle/issues/14760

Is it okay to document this workaround until its fixed on Gradle side?

2021-12-03 14:18 UTC, glefloch commented
If it's working, I think we can with a reference to the issue

2021-12-06 14:47 UTC, brianwyka commented
@glefloch , updated docs.

2021-12-06 19:57 UTC, glefloch reviewed
just left few comments. Should be good after that.

2021-12-06 19:57 UTC, glefloch commented on docs/src/main/asciidoc/tests-with-coverage.adoc
> +If you have any exclusions that you would like to apply to the verification task, that are outside the scope of `@QuarkusTest`, you will need the following in your `build.gradle` file:
```suggestion
Excluding classes from the verification task can be configured as following: 
```

2021-12-06 19:57 UTC, glefloch commented on docs/src/main/asciidoc/tests-with-coverage.adoc
> +.Example Configuration
Could you also remove these title ?

2021-12-06 19:57 UTC, glefloch commented on docs/src/main/asciidoc/tests-with-coverage.adoc
> +.Example Configuration
and this one too.

2021-12-06 21:18 UTC, brianwyka commented
Should be all set now @glefloch

2021-12-07 07:41 UTC, glefloch approved these changes
Thanks @brianwyka

2021-12-07 21:49 UTC, gsmet commented
I force pushed a rebase + squash. Will merge as soon as CI is green.

2021-12-08 05:56 UTC, glefloch commented
Thanks @gsmet and @brianwyka !

2021-12-08 05:56 UTC, merged