Fix #2096 Maven archetype does not generate/include .gitignore file
quarkusio/quarkus pull request #2201
Opened 2019-04-24 13:42 UTC by ppalaga

2019-04-24 22:11 UTC, gsmet requested changes
Nice work. Thanks for taking care of it.

I just added a comment about useful additions to the `.gitignore` file, otherwise it looks good. Could you include them and squash everything? I'll merge then. Thanks!

2019-04-24 22:11 UTC, gsmet commented on devtools/common/src/main/resources/templates/gitignore.ftl
> +.DS_Store
If you can add the Vim temporary files
```
*.swp
*.swo
```
that would be nice.

And maybe the diff conflicts:
```
*.orig
*.rej
```
too.

2019-04-25 05:24 UTC, machi1990 commented on devtools/common/src/main/java/io/quarkus/templates/rest/BasicRest.java
> +        generate("templates/gitignore.ftl", context, gitignore, "docker ignore");
I think we have a typo: `resourceType` should be `"git ignore"` and not `"docker ignore"`.

2019-04-25 07:38 UTC, ppalaga commented
Thanks for the review, in 6066907 : 

* `*.swp, *.swo, *.orig, *.rej` were added to gitignore.ftl and
* `"docker ignore"` was replaced with `"git ignore"`

2019-04-25 16:27 UTC, gsmet approved these changes

2019-04-25 16:27 UTC, merged

2019-04-25 16:27 UTC, gsmet commented
Nice contribution, thanks!