Added Dynamic and Static Config keys in extension-codestart.adoc
quarkusio/quarkus pull request #22052
Opened 2021-12-09 06:42 UTC by johurul000

2021-12-09 06:42 UTC, johurul000 commented
@ia3andy

2022-02-12 07:30 UTC, johurul000 commented
hi @ia3andy  is there any improvement needed

2022-02-14 08:44 UTC, ia3andy commented on docs/src/main/asciidoc/extension-codestart.adoc
> +
Instead of having the legacy enum like `BOM_GROUP_ID`, just add the key and description (like above)

2022-02-14 08:44 UTC, ia3andy requested changes
Added a change request, thanks for this :)

2022-03-08 13:24 UTC, ia3andy commented on docs/src/main/asciidoc/extension-codestart.adoc
> +MAVEN_SUREFIRE_PLUGIN_VERSION("maven-surefire-plugin.version"),
Why not those two?

2022-03-08 13:27 UTC, johurul000 commented on docs/src/main/asciidoc/extension-codestart.adoc
> +MAVEN_SUREFIRE_PLUGIN_VERSION("maven-surefire-plugin.version"),
sorry I missed them

2022-03-08 13:43 UTC, johurul000 commented on docs/src/main/asciidoc/extension-codestart.adoc
> +MAVEN_SUREFIRE_PLUGIN_VERSION("maven-surefire-plugin.version"),
@ia3andy

2022-03-08 13:54 UTC, ia3andy approved these changes
LGTM. thanks!

2022-06-22 10:42 UTC, Sanne commented
@ia3andy I've rebased it - but I see this PR has been lingering for months.  Could you confirm we still want it, and merge assuming CI is happy?

2022-06-22 10:45 UTC, ia3andy commented
Oupsy, some way, it slipped.. We can merge it when CI is OK..

Thanks @Sanne!

2022-06-22 10:49 UTC, Sanne commented
np :)

2022-06-22 12:43 UTC, merged