Add shared attribute to the Reactive Rest Client
quarkusio/quarkus pull request #22291
Opened 2021-12-16 15:21 UTC by cescoffier

Expose the `shared` attribute introduced in Vert.x 4.2.2.

2021-12-20 14:20 UTC, gsmet requested changes
Spotted a small typo. The s is important for the understanding IMO.

2021-12-20 14:20 UTC, gsmet commented on extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientConfig.java
> +     * Set to true to share the HTTP client between rest client.
```suggestion
     * Set to true to share the HTTP client between REST clients.
```

2021-12-20 22:50 UTC, michalszynkiewicz approved these changes

2021-12-23 19:42 UTC, gastaldi commented on independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/api/QuarkusRestClientProperties.java
> +     * Set to true to share the HTTP client between rest client.
```suggestion
     * Set to true to share the HTTP client between REST clients.
```

2022-01-12 13:10 UTC, gsmet approved these changes

2022-01-12 13:10 UTC, merged