Add the ability to set custom converters to avro compiler
quarkusio/quarkus pull request #22315
Opened 2021-12-17 08:47 UTC by glefloch

* This add the `UUIDConversion` converter to the avro compiler
* This allows to set custom conversion classes to the avro compiler

closes #21529

2021-12-17 10:44 UTC, cescoffier requested changes
Looks great! I just added a very small comment.

2021-12-17 10:44 UTC, cescoffier commented on extensions/avro/deployment/src/main/java/io/quarkus/avro/deployment/AvroCodeGenProviderBase.java
> +            this.customConversions = "".equals(conversions) ? EMPTY : conversions.split(",");
We should trim the values.

2021-12-17 13:52 UTC, glefloch commented on extensions/avro/deployment/src/main/java/io/quarkus/avro/deployment/AvroCodeGenProviderBase.java
> +            this.customConversions = "".equals(conversions) ? EMPTY : conversions.split(",");
Sure, done :)

2021-12-17 14:26 UTC, cescoffier approved these changes

2021-12-20 08:35 UTC, glefloch commented
@michalszynkiewicz could you have a look ?

2021-12-20 08:49 UTC, michalszynkiewicz approved these changes

2021-12-20 08:49 UTC, merged