Hibernate Search 6.1: Extension for the outbox-polling coordination strategy
quarkusio/quarkus pull request #22904
Opened 2022-01-14 14:09 UTC by yrodiere

Fixes #22695

@gsmet As discussed together, I did test locally with the Hibernate Search codestart and it works.

I will submit other PRs later to add more tests.

2022-01-14 14:46 UTC, yrodiere commented
Looks like `./update-extension-dependencies.sh` no longer works now that we have relocation artifacts: it adds dependencies for the relocation artifacts...

I'll edit the result by hand.

2022-01-14 20:51 UTC, gsmet requested changes
Spotted a small issue with the doc. Otherwise, it looks good to go.

2022-01-14 20:51 UTC, gsmet commented on docs/src/main/asciidoc/hibernate-search-orm-elasticsearch.adoc
> +./mvnw quarkus:add-extension -Dextensions="hibernate-search-orm-elasticsearch-aws"
Hmmm, looks like the wrong extension.

2022-01-17 07:50 UTC, yrodiere commented
Right, thanks. I addressed your comment and rebased on main.

2022-01-17 10:10 UTC, gsmet approved these changes

2022-01-17 12:16 UTC, yrodiere commented
I think the devtools/grpc errors are unrelated, this time. @gsmet can you confirm these tests are known to be flaky?

2022-01-17 13:54 UTC, merged

2022-01-17 13:54 UTC, gsmet commented
Yeah, they go berserk from time to time (and quite often these days).

2022-01-21 19:36 UTC, gsmet commented
@yrodiere can you write a small something that I could include in the 2.7 announcement to present Hibernate Search 6.1 new features? A comment here is perfect.

2022-01-24 09:37 UTC, yrodiere commented
Here you go. The links to the guides are dead for now, they'll only work when 2.7 becomes the default version in the documentation.

```
The Hibernate Search extension now uses Hibernate Search 6.1:

* Hibernate Search is now tested to work up to and including Elasticsearch 7.16
* Hibernate Search is now able to work with OpenSearch 1.0 to 1.2, with [just a single change in your configuration properties](https://quarkus.io/guides/hibernate-search-orm-elasticsearch#opensearch).
* Hibernate Search can now push entity change events to an outbox table in the database and coordinate between multiple instances of the application to process these events and reindex entities. This opt-in, **preview** feature allows for safer concurrent index updates with lower overhead on commit. Learn more in [this section of the guide](https://quarkus.io/guides/hibernate-search-orm-elasticsearch#coordination).
* Hibernate Search 6.1 also includes many smaller improvements, such as new search predicates or the ability to provide Elasticsearch index settings or mappings as JSON; see [the official Hibernate Search 6.1 webpage](https://hibernate.org/search/releases/6.1/) for more details.
```