Warn when Resource method returns JSON but no JSON provider exists
quarkusio/quarkus pull request #22980
Opened 2022-01-18 15:53 UTC by geoand

Resolves: #22970

2022-01-18 16:02 UTC, gsmet requested changes, later dismissed
Spotted a small typo.

Don't we need the same for the client?

2022-01-18 16:02 UTC, gsmet commented on extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/QuarkusServerEndpointIndexer.java
> +            LOGGER.warnf("Quarkus detected the use of JSON is JAX-RS method '" + info.declaringClass().name() + "#"
```suggestion
            LOGGER.warnf("Quarkus detected the use of JSON in JAX-RS method '" + info.declaringClass().name() + "#"
```

2022-01-18 16:04 UTC, geoand commented
> Don't we need the same for the client?

Yeah, but that might need some extra changes

2022-01-18 16:04 UTC, geoand commented on extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/QuarkusServerEndpointIndexer.java
> +            LOGGER.warnf("Quarkus detected the use of JSON is JAX-RS method '" + info.declaringClass().name() + "#"
Fixes

2022-01-18 17:35 UTC, gsmet commented
CI is not happy about this:
```
Error: ]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: java.lang.RuntimeException: java.lang.RuntimeException: Failed to process method 'io.quarkus.resteasy.reactive.server.test.customproviders.UniFiltersResource#filters'
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:278)
	at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.setupEndpoints(ResteasyReactiveProcessor.java:525)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.RuntimeException: Failed to process method 'io.quarkus.resteasy.reactive.server.test.customproviders.UniFiltersResource#filters'
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:639)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:366)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:249)
	... 12 more
Caused by: java.lang.NullPointerException
	at io.quarkus.resteasy.reactive.common.deployment.JsonDefaultProducersHandler.handle(JsonDefaultProducersHandler.java:26)
	at io.quarkus.resteasy.reactive.server.deployment.QuarkusServerEndpointIndexer.isDefaultJson(QuarkusServerEndpointIndexer.java:171)
	at io.quarkus.resteasy.reactive.server.deployment.QuarkusServerEndpointIndexer.warnAboutMissingJsonProviderIfNeeded(QuarkusServerEndpointIndexer.java:163)
	at io.quarkus.resteasy.reactive.server.deployment.QuarkusServerEndpointIndexer.handleAdditionalMethodProcessing(QuarkusServerEndpointIndexer.java:156)
	at io.quarkus.resteasy.reactive.server.deployment.QuarkusServerEndpointIndexer.handleAdditionalMethodProcessing(QuarkusServerEndpointIndexer.java:32)
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createResourceMethod(EndpointIndexer.java:631)
	... 14 more

	at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:613)
```

2022-01-18 17:43 UTC, geoand commented
Should be an easy fix. I'll fix it in the morning

2022-01-19 16:24 UTC, gsmet approved these changes

2022-01-20 08:09 UTC, mamadaliev approved these changes

2022-01-20 08:56 UTC, merged