Use "full" OpenJDK image
quarkusio/quarkus pull request #23176
Opened 2022-01-25 12:57 UTC by cescoffier

and switch back to run-java to start the JVM application

2022-01-25 20:15 UTC, gsmet commented
Marking this ready for review to trigger CI.

2022-01-25 20:15 UTC, gsmet requested changes, later dismissed
We are waiting for @maxandersen 's green light on this one.

2022-01-25 22:00 UTC, maxandersen commented on independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/tooling/dockerfiles/base/Dockerfile-layout.include.qute
> +# This image uses the `run-java.sh` script to run the application.
These docs are fine by now but really should consider putting this in a guide somewhere and link to it instead.

2022-01-25 22:08 UTC, maxandersen commented on independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/tooling/dockerfiles/base/Dockerfile-layout.include.qute
> +ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
JAVA_OPTIONS is standard Java vm env var.

What is the semantics of JAVA_OPTS here?

2022-01-25 23:50 UTC, maxandersen approved these changes
lgtm - I can't find fault in these changes; but I found issues in openshift and container image deploy that made it hard/impossible to 100% verify - but afaics this specific change is in a good enough state to merge. if issues it would also be present with the current one in main.

2022-01-26 07:02 UTC, merged

2022-02-02 15:19 UTC, jorsol commented
I'm curious to know the reasoning about using the full OpenJDK image instead of the runtime... is the runtime image not compatible/supported with Quarkus?

On a side note, the [Migration-Guide-2.7](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.7) should also be updated.

2022-02-03 06:34 UTC, maxandersen commented
It is. It's just that the runtime image was planned to have run-java by now to simplify /unify how debug and memory settings were handled. 

That unfortunately didn't make it in yet so instead of breaking "apis" for a period we moved to the full image. 

Intention is 100% to move to smaller image by default when we can. 

You can in your own customization of container build choose to just use the runtime image or some other image that has a java runtime.