add warning if no registry set
quarkusio/quarkus pull request #23207
Opened 2022-01-26 10:38 UTC by ashwinair

Fixes #21905

2022-01-26 18:32 UTC, ebullient requested changes

2022-01-26 18:32 UTC, ebullient commented on devtools/cli/src/main/java/io/quarkus/cli/RegistryAddCommand.java
> +            output.warn("There is no registry set in the config file.");
I would move this warning a few lines down.

AFTER adding registries, let's see if the count == 1, and the registry id is not equal to `io.quarkus.registry.Constants.DEFAULT_REGISTRY_ID`. If you look at the example add commands, they could add two registries out of the gate, which would avoid this warning.

So. IFF this is a new config (!existing) AND they have only one registry AND it is not the default registry, we should warn them that "whatever-id-they-used" is the only registry configured, and that it replaced the default.

2022-01-28 13:42 UTC, ebullient approved these changes
Squash into one commit, please.. but it LGTM. Thank you!

2022-01-28 18:49 UTC, ashwinair commented
> Squash into one commit, please.. 

Done 👍 

>but it LGTM. Thank you!

Thnak you :)

2022-01-31 07:35 UTC, merged