Add oidc-token-reactive-propagation extension
quarkusio/quarkus pull request #23210
Opened 2022-01-26 11:23 UTC by sberyozkin

Fixes #22216

This PR introduces a very light weight `oidc-token-reactive-propagation` extension with a very simple reactive client filter, as an alternative to `oidc-token-propagation`. This new extension does not add yet a more complex code dealing with the token exchange/resign before the propagation which is available in `oidc-token-propagation` as I'd like to see some evidence that such features are used before duplicating them in `oidc-token-reactive-propagation`.

With this extension, and the OIDC code flow where a user is authenticating for ex to GitHub, and an extra remote call is required using the returned access token, one would just attach the filter to the reactive client and it will pick up and propagate the GitHub access token, without the users having to inject that token in the endpoint, manually set it on the client, etc.

`integration-tests/oidc-token-propagation` does test the propagation of the bearer tokens, those coming into the endpoint with `HTTP Authorization`.

So for this extension I've added the tests which does show the propagation of the code flow access tokens (returned from Keycloak) - while the docs have been saying it is possible it was not tested.

The test uses `Dev Services For Keycloak`. It uses a `Client` -> `Auth with Code Flow` -> `FrontendResource` -> Propagate token -> `Protected Resource` sequence. OIDC `web-app` configuration is used to secure `FrontendResource` (all the required properties are provided by `Dev Services`) but since `ProtectedResource` receives a propagated bearer token it has to be secured using the OIDC `service` configuration to avoid redirecting, so this is why a custom `TenantResolver` switches to the `bearer` tenant in this case.

Also, since it is a new extension, I think, if it feels one extension too many, then I'd propose to consider relocating a non-reactive `oidc-token-propagation` extension later, CC @gsmet.

2022-01-26 13:23 UTC, FroMage submitted a review, later dismissed
LGTM, except I'm unsure about the rules for the module name, so asking @cescoffier and @gsmet for consistency: should it be the current `quarkus-oidc-token-reactive-propagation` or `quarkus-oidc-token-propagation-reactive`?

2022-01-26 13:28 UTC, sberyozkin commented
Hi @FroMage yeah, I was thinking about it but ended up naming it as `quarkus-oidc-token-reactive-propagation` to make it consistent with `quarkus-oidc-client-reactive-filter` :-) where `reactive` is not trailing. I don't mind much if it will have to be renamed

2022-01-26 14:22 UTC, geoand commented on extensions/oidc-token-reactive-propagation/runtime/pom.xml
> +    <description>Use Reactive RestClient to propagate the incoming Bearer access token or token acquired from Authorization Code Flow as HTTP Authorization Bearer token</description>
```suggestion
    <description>Use Reactive REST Client to propagate the incoming Bearer access token or token acquired from Authorization Code Flow as HTTP Authorization Bearer token</description>
```

2022-01-26 14:23 UTC, geoand reviewed
👍🏼

2022-01-27 09:15 UTC, FroMage commented
So, let's ask @cescoffier and @gsmet again, and if we don't hear back from them we can just accept this as-is.

2022-01-27 14:48 UTC, cescoffier approved these changes
LGTM!

2022-01-27 14:49 UTC, cescoffier commented
|About the module name, let's ask @gsmet, I don't have a strong opinion. The current one does not shock me.

2022-01-27 16:59 UTC, sberyozkin commented
@cescoffier Hi Clement

> About the module name, let's ask @gsmet, I don't have a strong opinion. The current one does not shock me.

LOL :-). Sure, lets see what Guillaume's preference is. I nearly went ahead yesterday and renamed it to `oidc-token-propagation-reactive` but then hesitated again, thinking about having `oidc-client-reactive-filter` and `oidc-token-propagation-reactive` name misalignment. I guess the fact I did not follow a convention when I named `oidc-client-reactive-client` does not mean all next OIDC reactive aware extensions should follow the same pattern with the non-trailing `reactive` qualifier, but this pattern is already here with `oidc-client-reactive-client` and I guess it is not too bad. That said, I'm open to renaming if preferred

2022-01-31 12:15 UTC, gsmet commented
For me the question is: is it the propagation that is reactive? I think what you are doing here is having a reactive version of token propagation so it makes no sense IMHO to have reactive in the middle.

So I would rather go with `oidc-token-propagation-reactive` as the reactive flavor of OIDC token propagation.

But that is if I have understood the purpose of this extension, which is not a given :).

2022-01-31 12:24 UTC, sberyozkin commented
@gsmet 

> So I would rather go with oidc-token-propagation-reactive as the reactive flavor of OIDC token propagation.

+1. As I said I just followed the earlier convention I introduced for `oidc-client-reactive-filter` - but there it is in fact truly reactive; here, the only thing which is happening at the moment is that a reactive filter is used to do a simple propagation - later the token exchange can get added which will be reactive in nature but it is not there now, and I'm fine with not continuing with the same pattern and instead stick to the established convention; thanks

2022-01-31 14:15 UTC, sberyozkin commented
@FroMage Steph, I've renamed it to `oidc-token-propagation-reactive` - can you please check if all is good and re-approve if all looks good ?

2022-02-01 14:17 UTC, FroMage submitted a review, later dismissed
Looks like two rename mistakes slipped through, otherwise +1

2022-02-01 14:17 UTC, FroMage commented on docs/src/main/asciidoc/security-openid-connect-client.adoc
> + - `quarkus-oidc-token-propagation` and `quarkus-oidc-token-reactive-propagation` extensions to propagate the current `Bearer` or `Authorization Code Flow` access tokens
```suggestion
 - `quarkus-oidc-token-propagation` and `quarkus-oidc-token-propagation-reactive` extensions to propagate the current `Bearer` or `Authorization Code Flow` access tokens
```

2022-02-01 19:52 UTC, gsmet requested changes, later dismissed
Added a few suggestions.

I suspect it's something we want in 2.7, right?

2022-02-01 19:52 UTC, gsmet commented on integration-tests/oidc-token-propagation-reactive/pom.xml
> +    <name>Quarkus - Integration Tests - OpenID Connect Token Reactive Propagation</name>
```suggestion
    <name>Quarkus - Integration Tests - OpenID Connect Token Propagation Reactive</name>
```

2022-02-01 19:52 UTC, gsmet commented on integration-tests/oidc-token-propagation-reactive/pom.xml
> +    <description>Module that contains OpenID Connect Token Reactive Propagation tests</description>
```suggestion
    <description>Module that contains OpenID Connect Token Propagation Reactive tests</description>
```

2022-02-01 19:52 UTC, gsmet commented on docs/src/main/asciidoc/security-openid-connect-client.adoc
> +`quarkus-oidc-token-propagation-reactive` extension provides `io.quarkus.oidc.token.propagation.reactive.AccessTokenRequestReactiveFilter` which can be used to propagate the current `Bearer` or `Auth
```suggestion
The `quarkus-oidc-token-propagation-reactive` extension provides `io.quarkus.oidc.token.propagation.reactive.AccessTokenRequestReactiveFilter` which can be used to propagate the current `Bearer` or `Authorization Code Flow` access tokens.
```

2022-02-01 19:52 UTC, gsmet commented on docs/src/main/asciidoc/security-openid-connect-client.adoc
> +`quarkus-oidc-token-propagation-reactive` extension (as opposed to the non-reactive `quarkus-oidc-token-propagation` extension) does not currently support the exchanging or resigning the tokens befor
```suggestion
The `quarkus-oidc-token-propagation-reactive` extension (as opposed to the non-reactive `quarkus-oidc-token-propagation` extension) does not currently support the exchanging or resigning the tokens before the propagation.
However these features may be added in the future.
```

2022-02-01 22:45 UTC, sberyozkin commented
Hi @gsmet Thanks for reviewing it as well, it should be safe to get in 2.7, let me add a backport label, cc @FroMage

2022-02-02 10:05 UTC, merged