Document OpenTelemetry @WithSpan
quarkusio/quarkus pull request #23319
Opened 2022-01-31 16:31 UTC by radcortez

2022-01-31 17:27 UTC, gastaldi requested changes
It would be nice if the guide explained (or had some links pointing to) what a Span and a Trace are. As a newbie, I have no idea what that is :)

2022-01-31 17:27 UTC, gastaldi commented on docs/src/main/asciidoc/opentelemetry.adoc
> +annotation. This will create a new Span and establish any required relationships with the current Trace context.
```suggestion
annotation will create a new Span and establish any required relationships with the current Trace context.
```

2022-02-01 10:52 UTC, radcortez commented
> It would be nice if the guide explained (or had some links pointing to) what a Span and a Trace are. As a newbie, I have no idea what that is :)

Hum, for that I think we need to rewrite the guide. Let me do that on a separate PR.

2022-02-01 12:11 UTC, gastaldi approved these changes

2022-02-01 12:33 UTC, geoand commented
Best squash the commits before merging

2022-02-01 16:09 UTC, merged