Fix setting of JAEGER_SAMPLER_MANAGER_HOST_PORT system property
quarkusio/quarkus pull request #23712
Opened 2022-02-15 10:37 UTC by sophokles73

Originally, the property had been set to the value returned by
InetAddress.toString(), which always includes the resolved IP address
(or the string "unresolved") in addition to the original host name.
For example, setting "quarkus.jaeger.sampler-manager-host-port" to
"my-jaeger-host:5778" would result in a system property value of
"my-jaeger-host/<unresolved>:5778" which cannot be used by the Jaeger
client to retrieve the sampler strategies.

The property isno set to the original host string + ":" + port instead.

Fixes #23711

Signed-off-by: Kai Hudalla <sophokles.kh@gmail.com>

2022-02-15 13:06 UTC, radcortez requested changes
Thanks for the PR @sophokles73 

Any chance to also add a test? You can have a look into https://github.com/quarkusio/quarkus/blob/9b49525d47b10bc50eb96efaa8e2b5c204a44878/extensions/jaeger/deployment/src/test/java/io/quarkus/jaeger/test/CommaParseJaegerConfigurationTest.java and use Jaeger programmatic API to make sure the value is correct.

2022-02-15 13:53 UTC, sophokles73 commented
I'll give it a shot ...

2022-02-15 14:14 UTC, sophokles73 commented
@radcortez is it normal that I cannot even successfully run the existing tests? I am running
```sh
./mvnw install -f extensions/jaeger/
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Quarkus - Jaeger                                                   [pom]
[INFO] Quarkus - Jaeger - Runtime                                         [jar]
[INFO] Quarkus - Jaeger - Deployment                                      [jar]
[INFO] 
[INFO] ------------------< io.quarkus:quarkus-jaeger-parent >------------------
[INFO] Building Quarkus - Jaeger 999-SNAPSHOT                             [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce) @ quarkus-jaeger-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-test-deps-scope) @ quarkus-jaeger-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-test-deps-junit-scope) @ quarkus-jaeger-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-java-version) @ quarkus-jaeger-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-maven-version) @ quarkus-jaeger-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-no-runtime-deps) @ quarkus-jaeger-parent ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ quarkus-jaeger-parent ---
[INFO] Executing: /bin/sh -c cd '/home/hak8fe/git/quarkus/extensions/jaeger' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /home/hak8fe/git/quarkus/extensions/jaeger
[INFO] Storing buildNumber: e2209092818d8060cd84898f0e88261f74c2ada5 at timestamp: 1644933981128
[INFO] Storing buildScmBranch: fix_setting_of_sampler_manager_host_property
[INFO] 
[INFO] --- formatter-maven-plugin:2.17.1:format (default) @ quarkus-jaeger-parent ---
[INFO] 
[INFO] --- impsort-maven-plugin:1.6.2:sort (sort-imports) @ quarkus-jaeger-parent ---
[INFO] Processed 0 files in 00:00.001 (Already Sorted: 0, Needed Sorting: 0)
[INFO] 
[INFO] --- maven-source-plugin:3.1.0:jar-no-fork (attach-sources) @ quarkus-jaeger-parent ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ quarkus-jaeger-parent ---
[INFO] Installing /home/hak8fe/git/quarkus/extensions/jaeger/pom.xml to /home/hak8fe/.m2/repository/io/quarkus/quarkus-jaeger-parent/999-SNAPSHOT/quarkus-jaeger-parent-999-SNAPSHOT.pom
[INFO] 
[INFO] ---------------------< io.quarkus:quarkus-jaeger >----------------------
[INFO] Building Quarkus - Jaeger - Runtime 999-SNAPSHOT                   [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce) @ quarkus-jaeger ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-test-deps-scope) @ quarkus-jaeger ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-test-deps-junit-scope) @ quarkus-jaeger ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-java-version) @ quarkus-jaeger ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-maven-version) @ quarkus-jaeger ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-no-runtime-deps) @ quarkus-jaeger ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ quarkus-jaeger ---
[INFO] 
[INFO] --- formatter-maven-plugin:2.17.1:format (default) @ quarkus-jaeger ---
[INFO] Processed 16 files in 565ms (Formatted: 0, Unchanged: 16, Failed: 0, Readonly: 0)
[INFO] 
[INFO] --- impsort-maven-plugin:1.6.2:sort (sort-imports) @ quarkus-jaeger ---
[INFO] Processed 16 files in 00:00.023 (Already Sorted: 16, Needed Sorting: 0)
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ quarkus-jaeger ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- quarkus-bootstrap-maven-plugin:999-SNAPSHOT:extension-descriptor (generate-extension-descriptor) @ quarkus-jaeger ---
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ quarkus-jaeger ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ quarkus-jaeger ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ quarkus-jaeger ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ quarkus-jaeger ---
[INFO] 
[INFO] --- maven-jar-plugin:3.1.2:jar (default-jar) @ quarkus-jaeger ---
[INFO] Building jar: /home/hak8fe/git/quarkus/extensions/jaeger/runtime/target/quarkus-jaeger-999-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-source-plugin:3.1.0:jar-no-fork (attach-sources) @ quarkus-jaeger ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ quarkus-jaeger ---
[INFO] Installing /home/hak8fe/git/quarkus/extensions/jaeger/runtime/target/quarkus-jaeger-999-SNAPSHOT.jar to /home/hak8fe/.m2/repository/io/quarkus/quarkus-jaeger/999-SNAPSHOT/quarkus-jaeger-999-SNAPSHOT.jar
[INFO] Installing /home/hak8fe/git/quarkus/extensions/jaeger/runtime/pom.xml to /home/hak8fe/.m2/repository/io/quarkus/quarkus-jaeger/999-SNAPSHOT/quarkus-jaeger-999-SNAPSHOT.pom
[INFO] Installing /home/hak8fe/git/quarkus/extensions/jaeger/runtime/target/quarkus-jaeger-999-SNAPSHOT-sources.jar to /home/hak8fe/.m2/repository/io/quarkus/quarkus-jaeger/999-SNAPSHOT/quarkus-jaeger-999-SNAPSHOT-sources.jar
[INFO] 
[INFO] ----------------< io.quarkus:quarkus-jaeger-deployment >----------------
[INFO] Building Quarkus - Jaeger - Deployment 999-SNAPSHOT                [3/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce) @ quarkus-jaeger-deployment ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-test-deps-scope) @ quarkus-jaeger-deployment ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-test-deps-junit-scope) @ quarkus-jaeger-deployment ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-java-version) @ quarkus-jaeger-deployment ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-maven-version) @ quarkus-jaeger-deployment ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-no-runtime-deps) @ quarkus-jaeger-deployment ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ quarkus-jaeger-deployment ---
[INFO] 
[INFO] --- formatter-maven-plugin:2.17.1:format (default) @ quarkus-jaeger-deployment ---
[INFO] Processed 8 files in 39ms (Formatted: 0, Unchanged: 8, Failed: 0, Readonly: 0)
[INFO] 
[INFO] --- impsort-maven-plugin:1.6.2:sort (sort-imports) @ quarkus-jaeger-deployment ---
[INFO] Processed 8 files in 00:00.001 (Already Sorted: 8, Needed Sorting: 0)
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ quarkus-jaeger-deployment ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/hak8fe/git/quarkus/extensions/jaeger/deployment/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ quarkus-jaeger-deployment ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ quarkus-jaeger-deployment ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ quarkus-jaeger-deployment ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M [...]

2022-02-15 16:29 UTC, sophokles73 commented
@radcortez I have added the unit test

2022-02-16 12:52 UTC, radcortez commented
Great! Thanks!

2022-02-16 12:58 UTC, radcortez approved these changes

2022-02-16 12:58 UTC, merged

2022-02-16 13:17 UTC, sophokles73 commented
@radcortez could you mark this PR for consideration to be back ported? I would love to see this fixed in 2.7.x ...

2022-02-16 18:03 UTC, radcortez commented
Yes, it should be fine.