Fix autoscaling Knative properties
quarkusio/quarkus pull request #23834
Opened 2022-02-21 11:44 UTC by Sgitario

This PR the following issues:
- The generated `config-autoscaler` configmap does not set the namespace which should always be `knative-serving` (see for example https://knative.dev/docs/serving/autoscaling/scale-to-zero/#enable-scale-to-zero).
- Some properties do add the annotations at Knative service metadata level, and it should add them at Knative service spec template metadata level.
- The property `quarkus.knative.global-auto-scaling.containerConcurrency` (hard limit option) wrongly uses the `config-autoscaler` configmap and it should use `config-defaults` configmap (see https://knative.dev/docs/serving/autoscaling/concurrency/#hard-limit)

Moreover, add the autoscaling Knative properties to the Knative documentation.

Fix https://github.com/quarkusio/quarkus/issues/23786

2022-02-21 12:13 UTC, gsmet commented
@iocanel could you have a look at this one today? It looks like something we want in 2.7.2. Thanks!

2022-02-22 13:10 UTC, iocanel requested changes
Overall, looks good.
Some test classes need to be aligned with the rest of the tests (we can have some using the 'Test'  suffix and others not). Other than that looks great!

2022-02-22 13:11 UTC, Sgitario commented on integration-tests/kubernetes/quarkus-standard-way/src/test/java/io/quarkus/it/kubernetes/KnativeWithRevisionAutoscaling.java
> +public class KnativeWithRevisionAutoscaling {
ops, my bad, adding it.

2022-02-22 13:25 UTC, Sgitario commented on integration-tests/kubernetes/quarkus-standard-way/src/test/java/io/quarkus/it/kubernetes/KnativeWithGlobalAutoscaling.java
> +public class KnativeWithGlobalAutoscaling {
Renamed

2022-03-01 07:08 UTC, iocanel approved these changes
Lgtm

2022-03-01 07:09 UTC, merged