Quarkiverse build on Windows
quarkusio/quarkus pull request #23889
Opened 2022-02-22 20:45 UTC by gastaldi

This PR introduces some improvements to Quarkiverse extensions' build script:

- Build on Windows 
- Use actions/setup-java's cache

2022-02-23 06:29 UTC, maxandersen approved these changes
Assuming tests passes lgtm

2022-02-23 06:29 UTC, maxandersen commented on independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus-extension/code/quarkiverse/java/.github/workflows/build.yml
> +        os: [ubuntu-latest, windows-latest]
Why Windows but not osx ?

2022-02-23 08:37 UTC, gastaldi commented on independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus-extension/code/quarkiverse/java/.github/workflows/build.yml
> +        os: [ubuntu-latest, windows-latest]
Sure

2022-02-23 11:55 UTC, gsmet requested changes
Just want to open a debate, please dismiss if you think it's useless.

Is it really a good thing to multiply our CI usage by 3, when in most cases this will have little value?

Also, we wanted to enable native testing by default for Quarkiverse extensions and it will require some non trivial work with Windows in the matrix.
So if we decide to do that, I think we should add native testing on Linux (and I would limit it to Linux for the default behavior) because it might not be easy for the Quarkiverse contributor to do it afterwards with this new setup.

2022-02-23 11:57 UTC, gsmet commented
Btw this question: `Is it really a good thing to multiply our CI usage by 3, when in most cases this will have little value?` has 3 dimensions:
- GitHub Actions resources in general
- The planet
- Our GitHub Actions limited resources -> we multiply by 3 our GitHub Actions usage and I know some of you were already worried about the day when we would hit the limit

2022-02-23 11:59 UTC, gsmet commented on independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus-extension/code/quarkiverse/java/.github/workflows/build.yml
> +    strategy:
You need to disable `fail-fast`: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

2022-02-23 12:00 UTC, gsmet commented
I wouldn't be against having this matrix setup with Linux by default and a commented line with Linux/Windows.

I see little value in testing with macOS in the Java world, except in very specific cases.

2022-02-23 12:17 UTC, maxandersen commented
You are right @gsmet it does not make sense to enable This for All by default. 

Maybe parameteriZe the matrix and let users enable whats needed. 

Osx is relevant for native but yes; not by default.

2022-02-23 13:39 UTC, gastaldi commented
@gsmet The reason why I am doing this is because some Quarkiverse builds were reported to fail in Windows (see https://github.com/quarkiverse/quarkus-openapi-generator/issues/7). 

But I agree that it wouldn't be necessary from day one. I like your suggestion of having the matrix setup with Linux by default and some commented out lines for Windows. I also agree that testing in macOS is not very valuable (perhaps if one likes to investigate `too many open files` errors, but that's another story) :)

2022-02-23 15:40 UTC, gsmet commented
> some Quarkiverse builds were reported to fail in Windows (see https://github.com/quarkiverse/quarkus-openapi-generator/issues/7).

Yes, I have seen that, that's the one occurrence I was referencing to. I'm just unsure we should generalize this based on a few occurrences where it makes absolutely sense.

CI has a cost, even if it appears free to us, and I think we should try to be good citizens about it when we can.

2022-03-04 13:59 UTC, gsmet approved these changes

2022-03-04 13:59 UTC, merged