fix m2e war launcher lifcycle
quarkusio/quarkus pull request #2401
Opened 2019-05-10 16:59 UTC by Dufgui

2019-05-10 22:04 UTC, aloubyansky requested changes
Hey, thanks a lot for the contribution! Looks like the formatting got messed up there. Could you please restore the original one and add your changes following that style? It'll be easier to review. Also please add a little description of the issue you've fixed. Thanks again!

2019-05-11 07:31 UTC, Dufgui commented
done @aloubyansky

2019-05-11 20:32 UTC, aloubyansky commented
Thanks a lot! That's a lot cleaner.

> _No description provided._

Please describe the issue itself. Thanks.

2019-05-12 21:14 UTC, aloubyansky commented
@stuartwdouglas what's the status of war launcher? Are we keeping it? Thanks.

2019-05-13 11:45 UTC, aloubyansky approved these changes

2019-05-13 11:45 UTC, merged