Bump Keycloak version to 17.0.0
quarkusio/quarkus pull request #24108
Opened 2022-03-04 16:59 UTC by sberyozkin

Keycloak 17.0.0 is now based on Quarkus. Wildfly-based distro has a `-legacy` version qualifier. So I had to tweak a bit the way `DevServices for Keycloak` detect that it is a non WildFly based Keycloak image.

Most of the integration tests still use the WildFly based KC for tests since RH SSO will be based on it for a bit longer.
`integration-tests/oidc` is totally Keycloak(-X), and so all 3 quickstarts, but I'll follow with the related quickstart doc updates

2022-03-05 11:48 UTC, sberyozkin commented
The failures are not related, but in any case I'll update the quickstart docs in this PR

2022-03-07 14:42 UTC, sberyozkin commented
A corresponding Qucikstarts PR: https://github.com/quarkusio/quarkus-quickstarts/pull/1073
Starting a container will be simpler once the certs are generated in a dev mode

2022-03-07 21:12 UTC, sberyozkin commented
I only did a minor doc update to restart the build, the container test was fine locally:
```
[INFO] [INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Created container image sberyozkin/container-build-with-keycloak:0.1-SNAPSHOT (sha256:9db26e0eca1354d8f2fe2c5dedd6e903230d8648ce6a9b6ae09f5bcb4e20a7ca)
[INFO] 
[INFO] [INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 14790ms
[INFO] [INFO] 
[INFO] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ container-build-with-keycloak ---
[INFO] [INFO] 
[INFO] [INFO] -------------------------------------------------------
[INFO] [INFO]  T E S T S
[INFO] [INFO] -------------------------------------------------------
[INFO] [INFO] Running org.acme.security.openid.connect.NativeBearerTokenAuthenticationIT
[INFO] 2022-03-07 21:09:49,152 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
[INFO] 2022-03-07 21:09:49,476 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-3) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
[INFO] 2022-03-07 21:09:49,852 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-3) Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
[INFO] 2022-03-07 21:09:49,853 INFO  [org.tes.DockerClientFactory] (build-3) Docker host IP address is localhost
[INFO] 2022-03-07 21:09:49,869 INFO  [org.tes.DockerClientFactory] (build-3) Connected to docker: 
[INFO]   Server Version: 18.06.1-ce
[INFO]   API Version: 1.38
[INFO]   Operating System: Fedora 27 (Workstation Edition)
[INFO]   Total Memory: 31542 MB
[INFO] 2022-03-07 21:09:49,872 INFO  [org.tes.uti.ImageNameSubstitutor] (build-3) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
[INFO] 2022-03-07 21:09:51,082 INFO  [org.tes.DockerClientFactory] (build-3) Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
[INFO] 2022-03-07 21:09:51,276 INFO  [io.qua.oid.dep.dev.key.KeycloakDevServicesProcessor] (build-3) Using Quarkus powered Keycloak distribution
[INFO] 2022-03-07 21:09:51,300 INFO  [🐳 .io/.0.0]] (build-3) Creating container for image: quay.io/keycloak/keycloak:17.0.0
[INFO] 2022-03-07 21:09:51,515 INFO  [🐳 .io/.0.0]] (build-3) Container quay.io/keycloak/keycloak:17.0.0 is starting: f7976c5e368065d2b1df9a0bc862cc645779335160ee6b1b51449cec7fc438cf
[INFO] 2022-03-07 21:10:02,515 INFO  [🐳 .io/.0.0]] (build-3) Container quay.io/keycloak/keycloak:17.0.0 started in PT11.237372S
[INFO] 2022-03-07 21:10:04,420 INFO  [io.qua.oid.dep.dev.key.KeycloakDevServicesProcessor] (build-3) Dev Services for Keycloak started.
[INFO] Executing "docker run --name quarkus-integration-test-kgKDr --rm -p 8081:8081 -p 8444:8444 --net=ea18d09c135a206c676662c7894f10f35c95dcb766f8f836d692ad192d23de4d --env QUARKUS_HTTP_PORT=8081 --env QUARKUS_HTTP_SSL_PORT=8444 --env TEST_URL=http://localhost:8081 --env QUARKUS_OIDC_CLIENT_ID=backend-service --env CLIENT_QUARKUS_OIDC_AUTH_SERVER_URL=http://localhost:39411/realms/quarkus --env KEYCLOAK_URL=http://keycloak-YaTBt:8080 --env QUARKUS_OIDC_AUTH_SERVER_URL=http://keycloak-YaTBt:8080/realms/quarkus --env QUARKUS_OIDC_APPLICATION_TYPE=service --env QUARKUS_OIDC_CREDENTIALS_SECRET=secret sberyozkin/container-build-with-keycloak:0.1-SNAPSHOT"
[INFO] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.707 s - in org.acme.security.openid.connect.NativeBearerTokenAuthenticationIT
[INFO] [INFO] 
[INFO] [INFO] Results:
[INFO] [INFO] 
[INFO] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0

```

2022-03-08 08:48 UTC, gsmet requested changes
Can you have a quick look at the suggestions? They are minor but let's be consistent.

2022-03-08 08:48 UTC, gsmet commented on docs/src/main/asciidoc/security-openid-connect-dev-services.adoc
> +The `quay.io/keycloak/keycloak:17.0.0` image which contains a `Keycloak` distribution powered by `Quarkus` is used to start a container by default.
```suggestion
The `quay.io/keycloak/keycloak:17.0.0` image which contains a Keycloak distribution powered by Quarkus is used to start a container by default.
```
Let's be more reasonable on the backticks :).

2022-03-08 08:48 UTC, gsmet commented on docs/src/main/asciidoc/security-openid-connect-dev-services.adoc
> +`quarkus.keycloak.devservices.image-name` can be used to change the Keycloak image name. For example, set it to `quay.io/keycloak/keycloak:17.0.0-legacy` to use a `Keycloak` distribution powered by `
```suggestion
`quarkus.keycloak.devservices.image-name` can be used to change the Keycloak image name. For example, set it to `quay.io/keycloak/keycloak:17.0.0-legacy` to use a Keycloak distribution powered by WildFly.
```

2022-03-08 11:50 UTC, pedroigor approved these changes

2022-03-08 12:10 UTC, gsmet approved these changes

2022-03-08 17:51 UTC, merged

2022-03-15 14:12 UTC, rsvoboda commented
@sberyozkin I think https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.8 should be enhanced with Keycloak section.

It's a noticeable change, base image changed, URL of the service changed, docker commands and admin/password properties are different, ...