Add misfireThreshold default to QuartzRuntimeConfig.java
quarkusio/quarkus pull request #24253
Opened 2022-03-10 18:45 UTC by VanillaSpoon

### Add misfireThreshold default to QuartzRuntimeConfig.java

This enables the misfireThreshold configuration to be overridden by the user.

Issue #42105.

2022-03-10 19:05 UTC, machi1990 requested changes
Thanks for the PR @VanillaSpoon 

See the suggestion about making the property a `Duration` type and the modified comment on top of it.

2022-03-10 19:05 UTC, machi1990 commented on extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzRuntimeConfig.java
> +    public long misfireThreshold;
```suggestion
    /**
     * Defines how late the schedulers should be to be considered misfired..
     */
    @ConfigItem(defaultValue = "60")
    public Duration misfireThreshold;
```
let's make it a duration type.

2022-03-10 19:05 UTC, machi1990 commented on extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java
> +                        "" + quartzSupport.getRuntimeConfig().misfireThreshold);
```suggestion
            props.put(StdSchedulerFactory.PROP_JOB_STORE_PREFIX + ".misfireThreshold",
                        "" + quartzSupport.getRuntimeConfig().misfireThreshold.toMillis());
```

once the config item has been changed to a `Duration` time, we can convert it to long like this.

2022-03-10 19:10 UTC, machi1990 commented
> ## Failing Jobs - Building [de6d0ab](https://github.com/quarkusio/quarkus/commit/de6d0ab81d62db7aa859af53939294cce95b65fd)
> Status	Name	Step	Failures	Logs	Raw logs
> 	Initial JDK 11 Build	`Build`	[Failures](#user-content-test-failures-job-5500906205)	[Logs](https://github.com/quarkusio/quarkus/runs/5500906205?check_suite_focus=true)	[Raw logs](https://github.com/quarkusio/quarkus/commit/de6d0ab81d62db7aa859af53939294cce95b65fd/checks/5500906205/logs)
> ## Failures
> ###  Initial JDK 11 Build [#](#user-content-test-failures-job-5500906205)
> ```diff
> - Failing: extensions/quartz/runtime 
> ! Skipped: devtools/bom-descriptor-json docs extensions/quartz/deployment and 2 more
> ```
> 
> ####  extensions/quartz/runtime
> heavy_multiplication_x `` Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.18.0:validate (default) on project quarkus-quartz: File '/home/runner/work/quarkus/quarkus/extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzScheduler.java' has not been previously formatted. Please format file (for example by invoking `mvn -f extensions/quartz/runtime net.revelc.code.formatter:formatter-maven-plugin:2.18.0:format`) and commit before running validation! ``

@VanillaSpoon CI is failing because of a formatting problem. Please see https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#ide-config-and-code-style or https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#formatting on how to properly setup your IDE for auto formatting or the command to run to fix the format issue

2022-03-10 19:24 UTC, machi1990 commented on extensions/quartz/runtime/src/main/java/io/quarkus/quartz/runtime/QuartzRuntimeConfig.java
> +    public Duration misfireThreshold;
let's make sure that the type is imported

2022-03-10 19:28 UTC, VanillaSpoon commented
Thanks @machi1990, I'll get back to you :)

2022-03-11 05:47 UTC, geoand commented
@VanillaSpoon thanks for this.

See the bot's message for the exact command you need to run into order to format the file.

2022-03-11 18:04 UTC, machi1990 approved these changes

2022-03-11 22:09 UTC, merged