Fixes #2200
quarkusio/quarkus pull request #2427
Opened 2019-05-13 21:09 UTC by LightGuard

Adding some documentation about the different JDBC URLs for databases.

2019-05-13 21:09 UTC, LightGuard commented
@FroMage @gsmet

2019-05-14 12:35 UTC, gsmet requested changes
I added several comments inline.

I think it would be nice to have a practical example for each database. Not an example containing all the options but something that makes sense in a typical setup. The URL used in our integration tests might make sense.

2019-05-14 12:35 UTC, gsmet commented on docs/src/main/asciidoc/datasource-guide.adoc
> +As noted above, {project-name} currently supports four databases.
I would avoid saying that because I'm pretty sure we will forget to update it, next time we add a supported database.

2019-05-14 12:35 UTC, gsmet commented on docs/src/main/asciidoc/datasource-guide.adoc
> +You can find more information, visit the https://h2database.com/html/features.html?highlight=url&search=url#database_url[official documentation].
This sentence seems weird to me (but I'm not a native speaker). Maybe `To find more information, visit...`?

2019-05-14 12:35 UTC, gsmet commented on docs/src/main/asciidoc/datasource-guide.adoc
> +MySQL/MariaDB allow for setting the user name and password as part of the host.
We don't really want that. User and password should be set as Agroal properties. So I would remove that sentence.

2019-05-14 12:35 UTC, gsmet commented on docs/src/main/asciidoc/datasource-guide.adoc
> +Mssql takes a connection URL in the following form:
s/MsSQL/Microsoft SQL Server/

2019-05-14 12:35 UTC, gsmet commented on docs/src/main/asciidoc/datasource-guide.adoc
> +The mssql jdbc works essentially the same as the others.
s/mssql jdbc/Microsoft SQL Server JDBC driver/

2019-05-14 12:35 UTC, gsmet commented on docs/src/main/asciidoc/datasource-guide.adoc
> +More details can be found on the https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-to-sql-server-with-the-jdbc-driver?view=sql-server-2017[official docs].
**in** the official **documentation** ?

2019-05-14 12:35 UTC, gsmet commented on docs/src/main/asciidoc/datasource-guide.adoc
> +==== MySQL/MariaDB
As we primarily support MariaDB, I would go with `MariaDB/MySQL`.

2019-05-14 12:35 UTC, gsmet commented on docs/src/main/asciidoc/datasource-guide.adoc
> +You can find more information about this feature and others detailed in the https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-jdbc-url-format.html[official documentation].
We should point to the MariaDB documentation if possible.

2019-05-14 13:22 UTC, machi1990 commented on docs/src/main/asciidoc/datasource-guide.adoc
> +`database`:: same name as the user
We might also want to add `username` default value as database default is `same name as the user` while username default value is not provided.

2019-05-14 20:10 UTC, LightGuard commented
@gsmet updated

2019-05-14 20:16 UTC, dmlloyd submitted a review, later dismissed
Could you please change the commit message and PR title to actually say what the change is?  You could add "Fixes #2200" into the body of the commit message.

2019-05-14 21:17 UTC, LightGuard commented
@dmlloyd @gsmet better?

2019-05-14 21:19 UTC, dmlloyd commented
No, the title of the commit and PR is still just "Fixes #2200", which is not ideal when looking at the commit log or PR queue.

2019-05-14 23:54 UTC, LightGuard commented
@dmlloyd sorry, I misread your message. I changed the commit message, missed the PR title.

2019-05-15 08:15 UTC, gsmet requested changes
I added another round of (minor) comments.

Could you take care of them? Once it's done, I think we can merge.

2019-05-15 08:15 UTC, gsmet commented on docs/src/main/asciidoc/datasource-guide.adoc
> +Going into each of those options is beyond the scope of this document, but it give an overview of each database URL and link to the official documentation.
s/give/gives/

2019-05-15 08:15 UTC, gsmet commented on docs/src/main/asciidoc/datasource-guide.adoc
> +The https://jdbc.postgresql.org/documentation/head/connect.html[official docs] go into more detail and list optional parameters as well.
missed it the first time but same here: let's go for `official documentation`. Then s/go/goes/ and s/list/lists/.

2019-05-15 08:15 UTC, gsmet commented on docs/src/main/asciidoc/datasource-guide.adoc
> +Example:: `jdbc:sqlserver://localhost:1433;databaseName=AdventureWorks;user=MyUserName`
We don't want the username in the example. It should be set with an Agroal property.

2019-05-15 08:15 UTC, gsmet commented on docs/src/main/asciidoc/datasource-guide.adoc
> +WARNING: There is no default username, it must be specified as a property.
I don't think this has any value?

2019-05-15 16:21 UTC, LightGuard commented
@gsmet okay, take five

2019-05-16 07:31 UTC, gsmet approved these changes

2019-05-16 07:31 UTC, merged

2019-05-16 07:31 UTC, gsmet commented
Merged, thanks!