Escaped inner class to avoid shell interpolation
quarkusio/quarkus pull request #2435
Opened 2019-05-14 11:12 UTC by idiotwithalaptop

Fixes the issue described at https://github.com/quarkusio/quarkus/issues/2414

2019-05-14 11:54 UTC, gsmet commented
Looks like it's not as simple as it seemed: we have the following error on our CI:
```
Error: policy 'com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime' does not exist. It must be a fully qualified class name.
com.oracle.svm.core.util.UserError$UserException: policy 'com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime' does not exist. It must be a fully qualified class name.
```

2019-05-15 00:43 UTC, idiotwithalaptop commented
Hmm, this is odd.  I've tried running the exact same command in the test `docker run -v /home/vsts/work/1/s/integration-tests/hibernate-validator/target:/project:z --rm --user 1001:117 quay.io/quarkus/centos-quarkus-native-image:graalvm-1.0.0-rc16 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -H:InitialCollectionPolicy="com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime" -jar quarkus-integration-test-hibernate-validator-999-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -J-Xmx6g -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-SpawnIsolates -H:-JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace` locally and didn't get the same issue.  This difference might have something to do with being a different host OS, so will have to look at a cross-platform alternative.

2019-05-15 08:04 UTC, gsmet commented
I think what the error message states is that we still have the single quotes when trying to find the class. Thus the issue.

I wonder if the whole option should be quoted instead. Could you try that?

2019-05-15 11:23 UTC, dmlloyd requested changes
Shell escaping is not correct.

2019-05-15 11:23 UTC, dmlloyd commented on core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java
> +            command.add("-H:InitialCollectionPolicy=\"com.oracle.svm.core.genscavenge.CollectionPolicy\\$BySpaceAndTime\""); //the default collection policy results in full GC's 50% of the time
This is not necessary. These arguments are used by `ProcessBuilder` which does not use a shell to execute commands.

2019-05-15 11:25 UTC, dmlloyd commented on core/creator/src/main/java/io/quarkus/creator/phase/nativeimage/NativeImagePhase.java
> +            command.add("-H:InitialCollectionPolicy=\"com.oracle.svm.core.genscavenge.CollectionPolicy\\$BySpaceAndTime\""); //the default collection policy results in full GC's 50% of the time
Since the problem is related to Docker, maybe there should be a second escaping pass when docker is used?

2019-05-15 11:32 UTC, dmlloyd commented
This approach is never going to work because process builder is not a shell mechanism, it's an OS mechanism.  The OS is always going to send the program and arguments in to the destination process with no interpolation.  The problem here is that Docker is apparently performing a round of interpolation on its arguments - which is bad and incorrect, but maybe there's nothing we can do about it.  So we will need to quote things but *only* if Docker is in use and *only* the arguments that actually are passed in to Docker.

2019-06-19 08:45 UTC, FroMage commented
OK, we need to ask our docker expert @cescoffier to participate.

2019-09-20 02:09 UTC, dmlloyd commented
This PR hasn't been updated since May or so, can it be closed?

2019-10-14 10:26 UTC, machi1990 commented
@idiotwithalaptop hi, what's the status of this PR? I am seeing that it has not been updated since May, do you plan to continue working on this issue?

2019-11-12 15:07 UTC, cescoffier commented
Closing due to inactivity.

2019-11-12 15:07 UTC, closed without merging