Provide a new `ApplicationNotRunning` predicate for `@Scheduled`
quarkusio/quarkus pull request #24605
Opened 2022-03-29 14:35 UTC by knutwannheden

The `@Scheduled` annotation's `skipExecutionIf` attribute can be used to skip individual executions in a schedule. Currently, Quarkus only provides the `Never` implementation, which is also the default (never skips an execution).

Since the scheduler is initialized very early (priority `PLATFORM_BEFORE`) it can happen that executions get scheduled before the application has been fully started. An application can solve this by itself waiting to get notified with the `StartupEvent` or it can now use this new predicate: `@Scheduled(..., skipExecutionIf = ApplicationNotRunning.class)`.

2022-03-30 10:35 UTC, mkouba requested changes
Looks good! I've added two minor comments.

2022-03-30 10:35 UTC, mkouba commented on extensions/scheduler/runtime/src/main/java/io/quarkus/scheduler/Scheduled.java
> +    @ApplicationScoped
I think that `@Singleton` would be a better match as no client proxy is required here...

2022-03-30 10:35 UTC, mkouba commented on extensions/scheduler/deployment/src/test/java/io/quarkus/scheduler/test/ApplicationNotRunningPredicateTest.java
> +    static SuccessfulExecution successfulExecution;
These fields should be `volatile`.

2022-04-05 08:28 UTC, josephearl commented
As a user I wonder if this should become the default at some point (I was unaware the scheduler could start tasks before the application is started, and I wonder how useful that is or why I might want that)

2022-04-05 08:47 UTC, mkouba approved these changes

2022-04-05 08:51 UTC, mkouba commented
> As a user I wonder if this should become the default at some point (I was unaware the scheduler could start tasks before the application is started, and I wonder how useful that is or why I might want that)

Well, it depends on how you define _"application is started"_. The only "hard requirement" for scheduled methods is that the CDI container must be running. And in many cases, it's OK to execute a scheduled method before the `StartupEvent` is fired.

2022-04-05 08:51 UTC, merged