Add container-name configuration for kubernetes extension
quarkusio/quarkus pull request #24708
Opened 2022-04-02 00:09 UTC by Yelzhasdev

Resolves #24676

2022-04-02 13:02 UTC, geoand commented
Hi thanks for this.

I would prefer there was a separate commit addressing the issue that the PR is closing and another for the fix you mentioned was lost

2022-04-02 13:17 UTC, Yelzhasdev commented
> Hi thanks for this.
> 
> I would prefer there was a separate commit addressing the issue that the PR is closing and another for the fix you mentioned was lost

Hi! Done👍

2022-04-02 13:23 UTC, geoand commented
Thanks.

@iocanel can you please review?

2022-04-08 14:59 UTC, iocanel requested changes
What I see here is good.
However, I think that there is something missing.
We need to make sure that setting a custom container name does not break all other dekorators. 

We should either make force this decorator to run before all other Application Container Decorators and then pass the custom container name to the rest, all to force it last. The latter seems simpler.

However, we do need to test using the custom name with at least a couple other container related changes to make sure everything plays nicely together.

2022-04-08 15:00 UTC, iocanel commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ChangeContainerNameInDeploymentTriggerDecorator.java
> +    public void andThenVisit(DeploymentConfigSpecFluent<?> deploymentConfigSpecFluent, ObjectMeta objectMeta) {
Respect!

2022-04-08 17:35 UTC, Yelzhasdev commented
> What I see here is good. However, I think that there is something missing. We need to make sure that setting a custom container name does not break all other dekorators.
> 
> We should either make force this decorator to run before all other Application Container Decorators and then pass the custom container name to the rest, all to force it last. The latter seems simpler.
> 
> However, we do need to test using the custom name with at least a couple other container related changes to make sure everything plays nicely together.

Hi! I added all decorators that extend ApplicationContainerDecorator to perform before that new decorator, also added couple tests that change container to verify that everything is correct

2022-04-08 19:40 UTC, iocanel commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/ChangeContainerNameDecorator.java
> +    public Class<? extends Decorator>[] after() {
We need to find a better way to deal with it, but there are not much we can do atm.

2022-04-08 19:40 UTC, iocanel approved these changes
LGTM

2022-04-11 05:23 UTC, merged