Update Vert.x to version 4.2.6
quarkusio/quarkus pull request #24937
Opened 2022-04-14 11:39 UTC by cescoffier

Also update the mutiny bindings (the version 2.21.0 uses Vert.x 4.2.6).

2022-04-14 11:44 UTC, gsmet commented
Shouldn't it be 4.2.7 in PR title and commit message?

2022-04-14 18:32 UTC, gsmet requested changes
Looks good but title and commit message need to refer to 4.2.7.

2022-04-14 19:09 UTC, cescoffier commented
Yes, sorry. I will amend.
The test need to be investigated, it became flaky recently.

2022-04-15 05:49 UTC, cescoffier commented
Commit amended and title updated. Thanks @gsmet (multi-tasking is bad)

2022-04-15 10:32 UTC, gsmet approved these changes

2022-04-15 10:32 UTC, merged

2022-05-12 08:36 UTC, gsmet commented
@cescoffier could you expand a bit on what this update is about? We are working on the 2.7 backports and we usually try to understand what the PRs do. Thanks!

2022-05-12 08:38 UTC, gsmet commented
It's because of this one right: https://github.com/eclipse-vertx/vert.x/commit/a9a840844e2796aa50bac7c89d1047d4c2c3d2ef ?

2022-05-12 08:39 UTC, cescoffier commented
It contains fixes fro the Oracle client (the reactive one) such as the very annoying transaction demarcation issue.

It also fixes a websocket handshake timeout issue, and missing duplicated contexts when using pipelined http requests.