Reactive Kotlin Panache
quarkusio/quarkus pull request #25015
Opened 2022-04-19 19:56 UTC by nenros

I'm trying to write it second time. I still have problem with persist I need to write like this `person2.persist<Person>()`. There is still need to write proper deployment module to enhance companion object.

I would be really grateful for some comments and advices how should I write that. Even more I would be grateful If someone can finish that.

2022-04-20 07:06 UTC, geoand commented
@nenros thanks a lot for this work!

@evanchooly can you help out with this one? 
It would be great to have this if it fits our needs.

2022-05-23 16:48 UTC, evanchooly requested changes
The docs need a good scrubbing to make sure they're all what dokka needs.  And the nested flatMaps in the test need a good justification, imo, to remain as they are.

2022-05-23 16:48 UTC, evanchooly commented on extensions/panache/hibernate-reactive-panache-kotlin/runtime/src/main/kotlin/io/quarkus/hibernate/reactive/panache/kotlin/PanacheRepositoryBase.kt
> + * @param <Entity> The type of entity to operate on
update for dokka

2022-05-23 16:48 UTC, evanchooly commented on extensions/panache/hibernate-reactive-panache-kotlin/runtime/src/main/kotlin/io/quarkus/hibernate/reactive/panache/kotlin/PanacheRepositoryBase.kt
> + * @param <Entity> The type of entity to operate on
also the author tag is wrong.  should be updated but I would just remove it.

2022-05-23 16:58 UTC, evanchooly submitted a review, later dismissed

2022-05-23 16:58 UTC, evanchooly commented on extensions/panache/hibernate-reactive-panache-kotlin/runtime/src/main/kotlin/io/quarkus/hibernate/reactive/panache/kotlin/PanacheCompanion.kt
> +        query: String?,
The query should not be null here.

2022-05-23 16:58 UTC, evanchooly commented on extensions/panache/hibernate-reactive-panache-kotlin/runtime/src/main/kotlin/io/quarkus/hibernate/reactive/panache/kotlin/PanacheCompanion.kt
> +    fun persist(entities: Iterable<*>): Uni<Void> {
this method is bound to `Entity` on the other impls.  same for the overloads as well.

2022-05-23 20:16 UTC, nenros commented
Thank you @evanchooly I will take a look and try to fix. I'm not sure that I'm able to finish that because of my lack of knowledge, but I will try.

2022-05-23 20:18 UTC, evanchooly commented
I'm happy to answer any questions that come up.

2022-06-13 16:43 UTC, evanchooly commented
any progress @nenros ?

2022-06-15 13:51 UTC, nenros commented
@evanchooly sorry, I don't have time for that at the moment

2022-07-24 13:07 UTC, stephan-strate commented
@nenros would you mind me taking over this pull request and fixing the change requests?

2022-07-25 08:12 UTC, nenros commented
@stephan-strate no problem for me, iy would be great if you could finish it!

2022-08-15 17:14 UTC, evanchooly commented
I'm going to finish this one up since it's been a while.

2022-08-22 17:42 UTC, GavinRay97 commented
Out of curiosity, what does this enable?

Is it mostly about better integration with Kotlin, instead of the Java API's?

2022-08-23 04:37 UTC, evanchooly commented
Essentially.  Provides a more idiomatic API.  At least, that's the idea.

2022-08-23 17:51 UTC, evanchooly commented
Actually I found some issues reviewing my earlier comments. I want to take the time now and add some more tests from the java side.  Shouldn't take too long.

2022-08-24 05:21 UTC, geoand commented
> Actually I found some issues reviewing my earlier comments. I want to take the time now and add some more tests from the java side. Shouldn't take too long.

Let me know when it's ready :)

2022-08-25 15:21 UTC, evanchooly commented
It doesn't look like the test failures are related. It's hard to tell.  It seems that all the failures over the lifetime of the PR are included and not just the ones in the last run.  The code is ready to review at least and if we need to create a whole new PR to get a clean slate, I can do that, too.

2022-08-26 06:12 UTC, geoand commented
The Kotlin test failures do seem related, no?

2022-09-13 20:18 UTC, evanchooly commented
So i've poked and prodded at everything I can think. I can not for the life of me figure out why the deployment module tests fail while the java versions work just fine.  The extension itself works just fine: the integration tests run like a champ. But something is off with the deployment module's set up and I can't find it. I'm sure it's something simple and stupid and I'll look foolish when someone points it out.  But I'm moving on.  So we can either just remove these tests (because the ITs work just find and validate that all works) or if someone else wants to take a peek and see if they can find what's up, I'm ok with that plan, too.  But I have other things to work on so I'm going to focus on those now.  Thoughts?

2022-09-14 06:38 UTC, geoand commented
I fixed the tests.

There were two problems:

* Maven resource filtering was not set so the DB URL was not being properly propagated
* The Dev Mode test can't really work with Kotlin sources so I just deleted it.

On that note, I strongly urge for more tests to be added to the `deployment` module instead of relying too much on the integration-tests.
The are various reasons for this, but the most important one is that folks making changes to the extension should get test feedback as fast as possible - something which is not possible with the integration tests.

2022-09-14 11:20 UTC, geoand commented
We'll still need to address the Windows issue, but I think it will be rather simple (we are likely just missing some property in the pom)

2022-09-14 14:34 UTC, evanchooly commented
> I fixed the tests.
> 
> There were two problems:
> 
> * Maven resource filtering was not set so the DB URL was not being properly propagated
> * The Dev Mode test can't really work with Kotlin sources so I just deleted it.
> 
> On that note, I strongly urge for more tests to be added to the `deployment` module instead of relying too much on the integration-tests. The are various reasons for this, but the most important one is that folks making changes to the extension should get test feedback as fast as possible - something which is not possible with the integration tests.

This was my suspicion, too, but wanted some external confirmation so thanks for that.  And i agree about the tests. I think most of the integration tests could be moved in to the extensions' modules instead.

2022-09-14 14:34 UTC, evanchooly commented
> We'll still need to address the Windows issue, but I think it will be rather simple (we are likely just missing some property in the pom)

Looking at those failure messages, I have no idea how to address them.

2022-09-14 14:36 UTC, geoand commented
My guess is that the test-containers maven profile is not properly configured - I think other modules disable it for windows

2022-09-14 15:54 UTC, evanchooly commented
> My guess is that the test-containers maven profile is not properly configured - I think other modules disable it for windows

I think i found it. By default surefire and failsafe are disabled but then reenabled if the containers properties are set which they won't be on the windows builds.  we'll see what CI makes of my last push.

2022-09-15 18:54 UTC, evanchooly commented
I think this one's ready to merge, no?

2022-09-16 03:39 UTC, geoand commented
I really don't have an opinion on the Panache stuff, so it's probably best that someone who does have a look

2022-09-20 15:19 UTC, evanchooly commented
None of the test failures seem to be related.  What's left to do to get this one merged?

2022-09-20 15:27 UTC, geoand commented
A review 🙂.

cc @FroMage @loicmathieu

2022-10-04 08:23 UTC, loicmathieu commented
@geoand @evanchooly @nenros I waited to review it in case Stephan have time to do the review before me but it seems not so I'll review it.

2022-10-04 08:31 UTC, geoand commented
cc @FroMage now that is back from PTO :)

2022-10-04 09:52 UTC, loicmathieu approved these changes
LGTM, thanks !

I didn't check in details all test cases nor all PanacheEntity/Repository impl, I assume you copy/paste them from the Java part so they should be good.

2022-10-04 09:52 UTC, loicmathieu commented on integration-tests/hibernate-reactive-panache-kotlin/pom.xml
> +    -->
This comment is irrelevant here (it was for the parameter name property for the compiler)

2022-10-04 16:11 UTC, evanchooly commented on extensions/panache/hibernate-reactive-panache-kotlin/pom.xml
> +  <name>Quarkus - Hibernate Reactive with Panache and Kotlin - JPA</name>
as it is, it matches the java version of this so I'm inclined to keep it as is.  but i don't feel strongly about it.

2022-10-04 16:44 UTC, evanchooly commented on extensions/panache/hibernate-reactive-panache-kotlin/deployment/src/main/java/io/quarkus/hibernate/reactive/panache/kotlin/deployment/ReactiveKotlinJpaTypeBundle.java
> +import io.quarkus.hibernate.reactive.panache.kotlin.*;
are they, though?  I personally hate them but the linter doesn't complain.

2022-10-04 16:54 UTC, evanchooly commented on extensions/panache/hibernate-reactive-panache-kotlin/deployment/src/main/java/io/quarkus/hibernate/reactive/panache/kotlin/deployment/HibernateReactivePanacheKotlinProcessor.java
> +        for (ClassInfo classInfo : index.getIndex().getAllKnownImplementors(TYPE_BUNDLE.entityBase().dotName())) {
done

2022-10-04 17:02 UTC, evanchooly commented on extensions/panache/hibernate-reactive-panache-kotlin/deployment/src/main/java/io/quarkus/hibernate/reactive/panache/kotlin/deployment/ReactiveKotlinJpaTypeBundle.java
> +import io.quarkus.hibernate.reactive.panache.kotlin.*;
fixed either way.  ;)

2022-10-04 17:06 UTC, evanchooly commented on extensions/panache/hibernate-reactive-panache-common/runtime/src/main/java/io/quarkus/hibernate/reactive/panache/common/runtime/CommonPanacheQueryImpl.java
> +                .onFailure(CompletionException.class).transform(t -> t.getCause()));
i didn't make this change so I don't know the reasoning but since it's just a style change (and in common code), I've reverted it.

2022-10-06 11:35 UTC, loicmathieu commented on extensions/panache/hibernate-reactive-panache-kotlin/deployment/src/main/java/io/quarkus/hibernate/reactive/panache/kotlin/deployment/ReactiveKotlinJpaTypeBundle.java
> +import io.quarkus.hibernate.reactive.panache.kotlin.*;
Well, I am surprised that the linter didn't complain, maybe this rules changed but I remember having to update a bunch of PR due to this so better do it.
Thanks !

2022-10-06 11:42 UTC, loicmathieu approved these changes
Sorry for my previous comment about changing `index.getIndex()` to `index.getComputingIndex()` but I reverted it in my pending PR about Java 17 support for Kotlin step processors as it causes NPE. If it's not the case for you, you can keep it.

Anyway, I'm OK with the PR as is (even if I make a small suggestion).
Good work, very nice addition !

2022-10-06 11:42 UTC, loicmathieu commented on extensions/kotlin/runtime/pom.xml
> +            </exclusions>
Now that the version is in the BOM it may not be needed to exlude and re-import it, our BOM should have precendence.

2022-10-07 15:05 UTC, merged