Initial Support for SunPKCS11 provider in native image
quarkusio/quarkus pull request #25068
Opened 2022-04-21 13:57 UTC by sberyozkin

At the moment this PR only registers `SunPKCS11` as an additional security provider (which ensures it is available in native image) and starts with a simple integration test. I'm not sure yet if it sufficient to address #21099 as it is hard to automate such tests. In general it is worth starting investing more time into `SunPKCS11`, as it can be used for default FIPS configuration as well.

2022-04-21 18:54 UTC, gsmet requested changes

2022-04-21 20:55 UTC, sberyozkin commented on integration-tests/sunpkcs11/pom.xml
> +    <name>Quarkus - Integration Tests - Sun PKCS 11</name>
I was hoping to expand but it does not seem possible to add various cryptoki PKCS11 implementations, I can probably update a bouncycastle test to register both BC and SunPKCS11 for a simple test like this one.

2022-04-22 11:08 UTC, sberyozkin commented on integration-tests/sunpkcs11/pom.xml
> +    <name>Quarkus - Integration Tests - Sun PKCS 11</name>
I updated the BC test, it is actually better this way as it also tests more than one configured provider value, in fact this specific combination of providers is used in this [tutorial](https://techglimpse.com/install-softhsm-source-compilation/).

2022-04-22 15:18 UTC, sberyozkin commented
@gsmet I'm doing a minor follow up update to support configuring such providers but it won't work in the native mode, I'll ask Foivos if something can be done (re https://github.com/oracle/graal/issues/2552)

2022-04-26 09:59 UTC, gsmet commented
@sberyozkin I'm not sure if we should merge this or if you want us to wait?

2022-04-26 13:20 UTC, sberyozkin commented
@gsmet, Hi, I'd not mind it going into 2.9.0 CR1 if you are OK with it, it won't work in native yet, but there was an earlier query about configuring `SunPKCS11-NSS-FIPS` and I think this is how it will be done, so we can ask SMEs to give it a try in JVM mode

2022-04-26 13:53 UTC, gsmet approved these changes

2022-04-26 13:53 UTC, merged