Document behavior of `@QuarkusIntegrationTest` w/ container networks
quarkusio/quarkus pull request #25242
Opened 2022-04-29 06:45 UTC by snazy

* Enhance text + example for `@QuarkusIntegrationTest` in `getting-started-testing.adoc`
* Add a note to `security-openid-connect.adoc`

Fixes #25010

2022-05-03 17:22 UTC, gsmet requested changes
Thanks. I suggested a few micro changes.

2022-05-03 17:22 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-testing.adoc
> +The testcontainers library usually return connection strings without respecting the container network, so additional code is needed to provide Quarkus the "correct" connection string using the contai
```suggestion
The Testcontainers library usually return connection strings without respecting the container network, so additional code is needed to provide Quarkus the "correct" connection string using the container's IP on the container network and the _unmapped_ port number.
```

2022-05-03 17:22 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-testing.adoc
> +The container running the resource to test against, for example PostgreSQL via testcontainers, is assigned an IP address from the container's network.
```suggestion
The container running the resource to test against, for example PostgreSQL via Testcontainers, is assigned an IP address from the container's network.
```

2022-05-06 11:56 UTC, snazy commented
Gentle ping @gsmet

2022-05-09 14:04 UTC, gsmet approved these changes

2022-05-09 14:04 UTC, merged

2022-05-09 14:05 UTC, gsmet commented
Thanks!