Fix CONTRIBUTION regarding configuration properties generation
quarkusio/quarkus pull request #25316
Opened 2022-05-02 21:20 UTC by michalvavrik

Fixes: #25315

2022-05-03 12:42 UTC, gsmet requested changes
Thanks. Indeed it looks like it's not working.

I added a few suggestions.

2022-05-03 12:42 UTC, gsmet commented on CONTRIBUTING.md
> +This will generate the configuration properties documentation included in the root `target/asciidoc/generated/config/` directory and will avoid a lot of warnings when building the documentation modul
This one should be kept as is. We are talking about the `includes`.

2022-05-03 12:42 UTC, gsmet commented on CONTRIBUTING.md
> +./mvnw -DskipTests -DskipITs -DskipExtensionValidation -Dskip.gradle.tests clean install
Could we maybe create another profile that would be activated by `-DquicklyDocs`? That would be easier.

2022-05-04 20:38 UTC, michalvavrik commented
@gsmet thank you for suggestions, I pushed changes

2022-05-09 08:17 UTC, gsmet approved these changes

2022-05-09 08:17 UTC, merged

2022-05-09 08:17 UTC, gsmet commented
Thanks!