Add doc: how to use custom Kotlin version (Gradle)
quarkusio/quarkus pull request #25566
Opened 2022-05-13 15:12 UTC by GavinRay97

I don't know how to do this for Maven, I think I've tried once and it was harder than this
If anyone knows, would be great to add for Maven as well

2022-05-19 14:38 UTC, gsmet commented
@glefloch could you have a look at this proposal? Thanks!

2022-05-19 19:30 UTC, glefloch requested changes
Thanks for this @GavinRay97 I left a comment.

2022-05-19 19:30 UTC, glefloch commented on docs/src/main/asciidoc/kotlin.adoc
> +
I think we should leverage resolution for all configurations with the following configuration :

    configurations.all {
        resolutionStrategy {
            force "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.0-Beta"
            force "org.jetbrains.kotlin:kotlin-reflect:1.7.0-Beta"
        }
    }

2022-06-21 15:29 UTC, glefloch commented
Yes I will apply the fix in the PR

2022-06-21 19:57 UTC, GavinRay97 commented
Apologies, I didn't notice the reply in my inbox 😬

2022-06-21 20:00 UTC, glefloch approved these changes

2022-06-21 20:00 UTC, merged