Kubernetes Client: Allow to disable the RBAC resources generation
quarkusio/quarkus pull request #25756
Opened 2022-05-24 13:22 UTC by Sgitario

To access the API server from within a Kubernetes cluster, some RBAC related resources are required (e.g. a ServiceAccount, a RoleBinding etc.).
So, when the `kubernetes-client` extension is present, the `kubernetes` extension is going to create those resources automatically, so that application will be granted the `view` role.

With these changes, we can disable the generation using the property `quarkus.kubernetes-client.generate-rbac=false`.

2022-05-24 13:23 UTC, Sgitario commented
/cc @edeandrea @iocanel

2022-05-24 13:42 UTC, edeandrea commented
Thanks for the quick work @Sgitario!

2022-06-03 08:00 UTC, iocanel approved these changes
LGTM

2022-06-03 08:05 UTC, iocanel requested changes
The `quarkus.kubernetes-client` is for configuring the client. (
I don't think that it should be used for controlling manifest generation.
This configuration option needs to move to the PlatformConfiguration implemented by KubernetesConfig, OpenshfitConfig & KnativeConfig.

2022-06-07 04:20 UTC, Sgitario commented
> The `quarkus.kubernetes-client` is for configuring the client. ( I don't think that it should be used for controlling manifest generation. This configuration option needs to move to the PlatformConfiguration implemented by KubernetesConfig, OpenshfitConfig & KnativeConfig.

This property would not make sense without the `kubernetes-client` extension which is the extension that is triggering this configuration.

At first, it was weird to me that the `kubernetes-client` extension was generating the RBAC manifests and this is how it was done. This change is only about disabling this feature by a property.

2022-06-07 06:05 UTC, iocanel approved these changes

2022-06-07 06:13 UTC, merged