[doc] Document how to build fully static native executables
quarkusio/quarkus pull request #25890
Opened 2022-05-31 15:49 UTC by andreaTP

Following up on this discussion:
https://groups.google.com/g/quarkus-dev/c/aYJQjXyVlpc/m/AYQTEPheAgAJ

Here you have minimal documentation for building fully static binaries and Docker images from `scratch`.

2022-06-03 08:06 UTC, cescoffier requested changes

2022-06-03 09:25 UTC, andreaTP commented on docs/src/main/asciidoc/building-native-image.adoc
> +
Done here: https://github.com/quarkusio/quarkus/pull/25890/commits/0057fd328a0d077682edfc440e6dc908a4dfa382
let me know if you prefer a different wording.

2022-06-03 09:44 UTC, andreaTP commented
@cescoffier thanks a lot for your feedback!

For context, I have been shipping production applications as fully statically linked binaries for quite some time now, in practice, I have never faced issues caused by the swap `musl` / `glibc`.

Examples are in:
- [`codacy-coverage-reporter`](https://github.com/codacy/codacy-coverage-reporter) switched to fully static binaries to enable running the binary on "stripped down" Alpine Docker images [reference](https://github.com/codacy/codacy-coverage-reporter/issues/212)
- [`kubectl-clowdflow`](https://github.com/lightbend/cloudflow) has been shipped as a fully static binary since day 0 and I [blogged about](https://www.lightbend.com/blog/writing-kubectl-plugins-with-scala-or-java-with-fabric8-kubernetes-client-on-graalvm)

> It would be interesting to try with that approach (with the words of caution I mentioned in my review).

Do I understand correctly that you would like to experiment with statically linking `glibc`? In this case, it looks like there are serious issues in doing that: https://stackoverflow.com/a/57478728
I noticed that they added support for Bionic LibC if there is any interest in it.

Last note, this documentation improvement comes after my experiments for statically linking using `zig cc` as a drop-in replacement for `gcc` which dramatically simplifies the setup for static linking [reference](https://github.com/andreaTP/quarkus_fully_static/blob/main/Dockerfile.zig).

2022-06-03 09:56 UTC, cescoffier commented
We have seen issues especially when your application uses native libraries (which is not as rare as people thinks).

About distroless, I was thinking about using your approach and removing glibc from the base image (as an alternative). I believe it should work for most applications (except with the limits I mentioned above)

2022-06-03 10:23 UTC, andreaTP commented
Got it, thanks for explaining!
Regarding distroless it should work out of the box 👍

2022-06-03 11:17 UTC, andreaTP commented
@cescoffier I'm not an expert in distroless images but changing `FROM scratch` to `FROM gcr.io/distroless/static` generates a working container image (tested only with a basic hello world program).

2022-06-07 08:50 UTC, cescoffier approved these changes

2022-06-07 08:50 UTC, cescoffier commented on docs/src/main/asciidoc/building-native-image.adoc
> +
thanks!

2022-06-07 08:50 UTC, cescoffier commented
Can you squash your commits?

2022-06-07 11:23 UTC, andreaTP commented
Sure!

2022-06-07 11:36 UTC, andreaTP commented
@cescoffier done, thanks for the review!

2022-06-07 13:44 UTC, merged

2022-06-07 14:17 UTC, cescoffier commented
Awesome! Thanks!