Native reference updates
quarkusio/quarkus pull request #26133
Opened 2022-06-14 18:23 UTC by zakkak

2022-06-15 06:26 UTC, galderz requested changes
Looks good, just a small comment around combining commands to produce flamegraphs.

2022-06-15 06:26 UTC, galderz commented on docs/src/main/asciidoc/native-reference.adoc
> +${FG_HOME}/flamegraph.pl out.perf-folded > flamegraph.svg
For even easier copying, we could convert these two commands into a single one. E.g. 

```
perf script -i perf.data | ${FG_HOME}/stackcollapse-perf.pl > out.perf-folded \ 
    && ${FG_HOME}/flamegraph.pl out.perf-folded > flamegraph.svg
```

2022-06-16 05:46 UTC, galderz commented on docs/src/main/asciidoc/native-reference.adoc
> +${FG_HOME}/flamegraph.pl out.perf-folded > flamegraph.svg
Even better indeed :)

2022-06-16 05:47 UTC, galderz approved these changes

2022-06-16 10:52 UTC, merged

2023-01-13 10:03 UTC, gsmet commented
Doesn't apply cleanly to 2.7 and probably not worth the hassle of fixing the conflicts. Skipping.