Improve Web Links doc
quarkusio/quarkus pull request #26163
Opened 2022-06-15 15:02 UTC by ia3andy

- Improve description
- Add guide links
- Links is already included in rest data panache (no need to have it in the doc dependencies)

2022-06-15 15:04 UTC, ia3andy commented
I can't find information about the annotation for Web Links with Resteasy Classic

2022-06-15 19:22 UTC, gsmet requested changes

2022-06-15 19:22 UTC, gsmet commented on extensions/resteasy-reactive/quarkus-resteasy-reactive-links/runtime/pom.xml
> +    <description>Quarkus RESTEast Reactive resource linking support (Web Links). This module will allow injecting web links into the response HTTP headers by just annotating your endpoint resources.<
```suggestion
    <description>Quarkus RESTEasy Reactive resource linking support (Web Links). This module will allow injecting web links into the response HTTP headers by annotating your endpoint resources.</description>
```

2022-06-15 19:41 UTC, ia3andy commented on docs/src/main/asciidoc/rest-data-panache.adoc
> -    </dependency>
It's already a dependency of rest data panache (and reactive)

2022-06-16 07:26 UTC, ia3andy commented on docs/src/main/asciidoc/rest-data-panache.adoc
> -    </dependency>
https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-reactive-rest-data-panache/runtime/pom.xml#L31

2022-06-16 07:27 UTC, ia3andy commented on docs/src/main/asciidoc/rest-data-panache.adoc
> -    </dependency>
https://github.com/quarkusio/quarkus/blob/main/extensions/panache/rest-data-panache/runtime/pom.xml#L39

2022-06-16 10:52 UTC, gsmet approved these changes

2022-06-16 10:52 UTC, merged