Fix and improve javadoc in extensions projects
quarkusio/quarkus pull request #26239
Opened 2022-06-20 12:43 UTC by marcwrobel

2022-06-20 12:47 UTC, marcwrobel commented
@gsmet sorry, another big PR. But it is only modifying javadoc / comments so it should be safe.

I have also noted a few empty `@return` in javadoc (e.g. io/quarkus/amazon/lambda/http/DefaultLambdaIdentityProvider.java:42) : do you think these should be removed ?

2022-06-21 10:42 UTC, gsmet requested changes
I added a small suggestion, otherwise it looks good, thanks!

As for the empty `@return`, we can remove them but it's no big deal.

2022-06-21 10:42 UTC, gsmet commented on extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java
> +        // add the @FlywayDataSource class otherwise it won't register as a qualifier
```suggestion
        // add the @FlywayDataSource class otherwise it won't be registered as a qualifier
```

2022-06-22 11:30 UTC, gsmet approved these changes
I applied my suggestion and rebased.
I want to merge this one ASAP as it's potential conflict nest.

2022-06-22 13:18 UTC, marcwrobel commented
> I applied my suggestion and rebased. I want to merge this one ASAP as it's potential conflict nest.

You did well, I wouldn't have had time to do it before next week.

2022-06-22 15:53 UTC, merged

2022-06-22 15:54 UTC, gsmet commented
Merged, thanks a lot!