Add documentation about parent profile with profile aware files
quarkusio/quarkus pull request #26350
Opened 2022-06-24 14:21 UTC by p1ass

### Summary

This pull request adds documentation of confusing behavior about parent profiles with parent-aware files.

### Issue

we discussed it in issue #24586.

2022-06-29 13:36 UTC, radcortez requested changes

2022-06-29 13:36 UTC, radcortez commented
Hi @p1ass 

Thank you for the PR. I've left a small comment, to also add Environment Variable as an option.

2022-07-01 13:34 UTC, p1ass commented
@radcortez I added it and rebased.

2022-07-01 13:50 UTC, radcortez approved these changes

2022-07-01 14:10 UTC, merged