Fix for missing default java.security.Principal producer
quarkusio/quarkus pull request #2641
Opened 2019-05-29 14:54 UTC by starksm64

Fix for #2528, Missing default java.security.Principal producer

2019-05-29 23:39 UTC, stuartwdouglas approved these changes

2019-05-29 23:47 UTC, stuartwdouglas requested changes
Actually after thinking about this some more I think this approach has some limitations, it particular:

- it won't work with the 'login' method
- It won't work with something like @RunAs where the identity is changed

I think to do things the elyron way it should be using SecurityDomain.getCurrent().getCurrentSecurityIdentity().getPrincipal() although I don't know if this is set up correctly at the moment.

2019-05-30 00:42 UTC, stuartwdouglas commented
Actually those changes will probably be fairly large, it might be better to just merge this now, and worry about using the security identity stuff after the netty router is in.

2019-05-30 00:43 UTC, stuartwdouglas approved these changes

2019-05-30 00:43 UTC, merged

2019-05-30 18:34 UTC, starksm64 commented
I'll add your comment to the security arch discussion doc as I do have an item for ensuring a common handling of the CDI security principal is established.