Introduce a general way to prevent container image push in k8s extension
quarkusio/quarkus pull request #26460
Opened 2022-06-30 06:04 UTC by geoand

Before this change, we handled Minikube in a special way in order to
take advantage of the fact that the Minikube docker daemon already
contained the built container image.

This change introduces a way for users to opt in to this same feature
by setting quarkus.kubernetes.prevent-container-image-push

Resolves: #26385

2022-06-30 13:47 UTC, geoand commented
@iocanel WDYT about this?

2022-07-04 12:07 UTC, geoand commented
> @iocanel WDYT about this?

ping :)

2022-07-04 12:31 UTC, gastaldi approved these changes
Makes sense to me

2022-07-04 14:54 UTC, iocanel reviewed
I think that this is redundant. Using `-Dquarkus.container-image.push=false` should produce the same result. This is something that I recently (sometime in 2022) verified that is working.

2022-07-04 14:59 UTC, iocanel requested changes
I would just make sure that `-Dquarkus.container-image.push=false` is working. I don't see why we should introduce a new property, let alone as part of the kubernetes extension.

2022-07-05 05:24 UTC, geoand commented
@iocanel PR overhauled as per your suggestion

2022-07-05 10:45 UTC, iocanel approved these changes
Thanks @geoand. Looks great!

2022-07-05 10:48 UTC, merged