Display information about datasources that are "up" in Agroal healthcheck
quarkusio/quarkus pull request #26534
Opened 2022-07-04 07:49 UTC by tmihalac

Fixes https://github.com/quarkusio/quarkus/issues/26431

Added data up when datasource is valid

2022-07-04 14:22 UTC, gsmet requested changes

2022-07-04 14:22 UTC, gsmet commented on extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/health/DataSourceHealthCheck.java
> +                    String dsName = isDefault ? "<default>" : dataSource.getKey();
You can drop this entirely and use `dataSource.getKey()` directly. It will be `<default>` for the default datasource.

2022-07-04 14:22 UTC, gsmet commented on extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/health/DataSourceHealthCheck.java
> +                String dsName = isDefault ? "<default>" : dataSource.getKey();
Same here.

2022-07-05 07:51 UTC, gsmet approved these changes
Looks good, thanks!

2022-07-05 11:40 UTC, mamadaliev approved these changes

2022-07-05 16:02 UTC, gsmet commented
I rebased once more. Please avoid pushing merge commits in pull requests. They are very problematic when we want to backport things to older branches.

2022-07-06 18:01 UTC, merged