Quarkus extension is stable
quarkusio/quarkus pull request #26709
Opened 2022-07-13 12:14 UTC by gastaldi

This promotes the extension status from preview to stable

2022-07-13 12:17 UTC, gsmet commented
Probably a good idea to check with @mkouba before promoting it.

2022-07-13 12:42 UTC, geoand commented
Makes sense to me, but let's let @mkouba and @machi1990 weigh in here

2022-07-19 07:56 UTC, machi1990 requested changes, later dismissed
+1 on my side.

The API has been stable for quite some time now. 

On top of the change in the extensin config yaml, we'll also need to remove the preview status from the doc: https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/quartz.adoc.

2022-07-19 07:56 UTC, machi1990 commented on extensions/quartz/runtime/src/main/resources/META-INF/quarkus-extension.yaml
>    - "quarkus.quartz."
```suggestion
  - "quarkus.quartz."

```

2022-07-19 12:57 UTC, gsmet submitted a review, later dismissed

2022-07-25 15:00 UTC, gsmet commented
@mkouba we waited for you on this one :).

2022-07-26 08:12 UTC, mkouba commented
> @mkouba we waited for you on this one :).

@gsmet I'm personally +0 on this one. It's true that our API can be considered stable but there are some Quartz features which are not extensively tested (such as clustering) and thus our support is "limited".

OTOH if @machi1990 thinks that it's stable then I'm in as well :-)

2022-07-26 14:13 UTC, gsmet approved these changes
OK, let's proceed then.

2022-07-26 14:13 UTC, merged