update smallrye-graphql to add support for GraphQL unions
quarkusio/quarkus pull request #26865
Opened 2022-07-21 15:47 UTC by craig-day

Updating SmallRye GraphQL to get support for GraphQL unions.

2022-07-21 15:48 UTC, craig-day commented on bom/application/pom.xml
> +        <smallrye-graphql.version>1.6.2-SNAPSHOT</smallrye-graphql.version>
This is my testing locally and will be changed before this PR is marked as ready for review.

2022-07-22 00:50 UTC, phillip-kruger approved these changes
LGTM. Let's add the guide too.

2022-07-22 00:52 UTC, phillip-kruger commented
@craig-day Thanks a lot for this. The Guide source is here: https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/smallrye-graphql.adoc

I'll go ahead and release 1.6.2 in the mean time.

2022-07-22 17:25 UTC, craig-day commented
Thanks @phillip-kruger, I added a rather lengthy section to the guide for interfaces and unions. Let me know if it's too verbose or if you want the examples to be different.

2022-07-22 17:37 UTC, phillip-kruger approved these changes
This looks great!! Thanks @craig-day . Can you squash your commits and then we should be good to go.

2022-07-22 18:11 UTC, craig-day commented
@phillip-kruger done! squashed and rebased on latest main

2022-07-22 22:31 UTC, phillip-kruger commented
Thanks @craig-day ! There are some related test failures. I'll also have a look at them a bit later

2022-07-25 04:56 UTC, craig-day commented
@phillip-kruger Looks like some more class loading problems because I added a reference to `TestUnion` in the `TestResource` class, so I had to add the new classes anywhere `TestResource` was used.

2022-07-25 05:01 UTC, phillip-kruger commented
Awesome ! Thanks @craig-day ! Let's see what CI is doing

2022-07-25 11:54 UTC, gsmet requested changes
@phillip-kruger can you release a Jakarta version and update the version here:
https://github.com/quarkusio/quarkus/blob/main/jakarta/rewrite.yml#L429
in this PR?

Otherwise the Jakarta build will fail.

Thanks!

2022-07-25 12:01 UTC, phillip-kruger commented
@jmartisk is already on it :)

2022-07-26 08:16 UTC, jmartisk commented
The Jakarta upgrade is in now.

2022-07-26 08:28 UTC, gsmet approved these changes

2022-07-26 12:40 UTC, phillip-kruger commented
@gsmet The test failures seem unrelated ?

2022-07-26 14:11 UTC, merged

2022-07-26 14:11 UTC, gsmet commented
Better wait for the report :).