Bump to GraalVM 22.2.0
quarkusio/quarkus pull request #26943
Opened 2022-07-26 17:46 UTC by gastaldi

2022-07-26 19:05 UTC, gsmet requested changes
I think some of the changes are missing. See https://github.com/quarkusio/quarkus/pull/25366/files for reference.

2022-07-26 20:50 UTC, zakkak requested changes

2022-07-26 20:50 UTC, zakkak commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java
> +    public static final String DEFAULT_MANDREL_BUILDER_IMAGE = "quay.io/quarkus/ubi-quarkus-mandrel:22.2-java17";
Mandrel 22.2 has not been released yet and is also not covered by https://github.com/quarkusio/quarkus-images/pull/201

2022-07-27 08:14 UTC, zakkak requested changes, later dismissed

2022-07-27 08:14 UTC, zakkak commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java
> +                GraalVM.Version.CURRENT));
This should not change. It says that the export should be done for GraalVM >= 22.1

2022-07-27 08:14 UTC, zakkak commented on core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageFeatureStep.java
> +                new JPMSExportBuildItem("org.graalvm.sdk", "org.graalvm.nativeimage.impl", GraalVM.Version.CURRENT));
This should not change. It says that the export should be done for GraalVM >= 22.1

2022-07-27 08:14 UTC, zakkak commented on core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageFeatureStep.java
> +                    GraalVM.Version.CURRENT));
This should not change. It says that the export should be done for GraalVM >= 22.1

2022-07-27 08:14 UTC, zakkak commented on core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageFeatureStep.java
> +                    GraalVM.Version.CURRENT));
This should not change. It says that the export should be done for GraalVM >= 22.1

2022-07-27 08:14 UTC, zakkak commented on core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageFeatureStep.java
> +                    GraalVM.Version.CURRENT));
This should not change. It says that the export should be done for GraalVM >= 22.1

2022-07-27 08:14 UTC, zakkak commented on core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageFeatureStep.java
> +                            GraalVM.Version.CURRENT));
This should not change. It says that the export should be done for GraalVM >= 22.1

2022-07-27 08:14 UTC, zakkak commented on core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageFeatureStep.java
> +                            GraalVM.Version.CURRENT));
This should not change. It says that the export should be done for GraalVM >= 22.1

2022-07-27 08:14 UTC, zakkak commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/GraalVM.java
> -        public static final Version VERSION_22_1_0 = new Version("GraalVM 22.1.0", "22.1.0", Distribution.ORACLE);
We need to keep this around as well (see my later comments)

2022-07-29 13:35 UTC, gastaldi commented
Marking as a draft until the build in https://github.com/quarkusio/quarkus-images is fixed

2022-08-03 17:28 UTC, gastaldi commented
Yay! Green CI 🎆 🎉 🎉 🎉

2022-08-04 08:00 UTC, gsmet approved these changes
Looks good to me but let's wait for @zakkak before merging.

2022-08-04 13:17 UTC, galderz approved these changes

2022-08-04 13:22 UTC, gastaldi commented
@gsmet Since @zakkak is away all of august and @galderz approved it, maybe we can merge this?

2022-08-04 13:30 UTC, merged