Introduce a new set of test callbacks used right before and after test execution
quarkusio/quarkus pull request #27019
Opened 2022-07-29 05:28 UTC by geoand

These callbacks essentially offer similar funtionality to JUnit's
`org.junit.jupiter.api.extension.BeforeTestExecutionCallback` and
`org.junit.jupiter.api.extension.AfterTestExecutionCallback`

Closes: #26999

2022-07-29 09:40 UTC, Cs4r commented
Thanks for your work @geoand.

However, how can I build a jar with these changes? 😅

2022-07-29 09:47 UTC, geoand commented
You can do the following:

```bash
git clone -b #26999 --single-branch git@github.com:geoand/quarkus.git
cd quarkus
mvn -Dquickly -Dformat.skip=true
```

Then use the following BOM:

```xml
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-bom</artifactId>
        <version>999-SNAPSHOT</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

2022-07-29 10:31 UTC, Cs4r commented
@geoand:

if I do a `git clone -b #26999 --single-branch git@github.com:geoand/quarkus.git` I get the error: 

```
error: switch `b' requires a value
```

If I do a `git clone -b 26999 --single-branch git@github.com:geoand/quarkus.git`  (without hash) I get the error: 

```
Cloning into 'quarkus'...
warning: Could not find remote branch 26999 to clone.
fatal: Remote branch 26999 not found in upstream origin
```

Thanks in advance.

2022-07-29 10:38 UTC, geoand commented
Can you try `git clone -b '#26999' --single-branch git@github.com:geoand/quarkus.git`?

2022-08-01 09:58 UTC, Cs4r commented
@geoand :

Apparently, this feature doesn't work yet.


I have created a simple class implementing `io.quarkus.test.junit.callback.QuarkusTestBeforeTestCallback`:

```
package cs4r;

import io.quarkus.test.junit.callback.QuarkusTestBeforeTestCallback;
import io.quarkus.test.junit.callback.QuarkusTestMethodContext;

public class MyQuarkusTestBeforeTestCallback implements QuarkusTestBeforeTestCallback {

    @Override
    public void beforeTest(QuarkusTestMethodContext context) {
        System.out.println("beforeTest");
    }
}
```

Then (as https://quarkus.io/guides/getting-started-testing#enrichment-via-quarkustestcallback says) I have created the file  `src/main/resources/META-INF/services/io.quarkus.test.junit.callback.QuarkusTestBeforeTestCallback` with the following content:

```
cs4r.MyQuarkusTestBeforeTestCallback
```

but for some reason I am not aware of yet, the callback is never executed.  

This is also happening with `io.quarkus.test.junit.callback.QuarkusTestAfterTestCallback`, therefore I reckon it might be that the algorithm for parsing the files:

- `src/main/resources/META-INF/services/io.quarkus.test.junit.callback.QuarkusTestBeforeTestCallback` 
- `src/main/resources/META-INF/services/io.quarkus.test.junit.callback.QuarkusTestAfterTestCallback` 


is missing.

2022-08-01 10:10 UTC, geoand commented
Can you share the example project you used?

2022-08-01 10:12 UTC, geoand commented
PR updated, it should work now

2022-08-01 14:08 UTC, Cs4r commented
@geoand this time it works like a charm 😄 

Will this be added in the next release?

Thanks in advance.

2022-08-01 14:30 UTC, geoand commented
Thanks a lot for checking!

It will be included in `2.12.0.CR1` onwards, but I am wondering if we can add it to `2.11.2.Final` - WDYT @gsmet?

2022-08-01 14:30 UTC, geoand commented
I'll finish the PR tomorrow by adding tests

2022-08-02 05:22 UTC, gastaldi requested changes
Small naming suggestion change to match the same hooks JUnit provides

2022-08-02 05:22 UTC, gastaldi commented on test-framework/junit5/src/main/java/io/quarkus/test/junit/callback/QuarkusTestAfterTestCallback.java
> +public interface QuarkusTestAfterTestCallback {
```suggestion
public interface QuarkusTestAfterTestExecutionCallback {
```

2022-08-02 05:22 UTC, gastaldi commented on test-framework/junit5/src/main/java/io/quarkus/test/junit/callback/QuarkusTestAfterTestCallback.java
> +    void afterTest(QuarkusTestMethodContext context);
```suggestion
    void afterTestExecution(QuarkusTestMethodContext context);
```

2022-08-02 05:22 UTC, gastaldi commented on test-framework/junit5/src/main/java/io/quarkus/test/junit/callback/QuarkusTestBeforeTestCallback.java
> +public interface QuarkusTestBeforeTestCallback {
```suggestion
public interface QuarkusTestBeforeTestExecutionCallback {
```

2022-08-02 05:22 UTC, gastaldi commented on test-framework/junit5/src/main/java/io/quarkus/test/junit/callback/QuarkusTestBeforeTestCallback.java
> +    void beforeTest(QuarkusTestMethodContext context);
```suggestion
    void beforeTestExecution(QuarkusTestMethodContext context);
```

2022-08-02 05:28 UTC, geoand commented
Good point! Fixed

2022-08-02 05:43 UTC, gastaldi approved these changes
Missing doc changes, but the rest looks okay, approved ;)

2022-08-02 05:43 UTC, gastaldi commented on docs/src/main/asciidoc/getting-started-testing.adoc
> +* `io.quarkus.test.junit.callback.QuarkusTestBeforeTestCallback`
```suggestion
* `io.quarkus.test.junit.callback.QuarkusTestBeforeTestExecutionCallback`
```

2022-08-02 05:43 UTC, gastaldi commented on docs/src/main/asciidoc/getting-started-testing.adoc
> +* `io.quarkus.test.junit.callback.QuarkusTestAfterTestCallback`
```suggestion
* `io.quarkus.test.junit.callback.QuarkusTestAfterTestExecutionCallback`
```

2022-08-02 05:45 UTC, geoand commented
I knew I would miss something :)

2022-08-02 13:43 UTC, merged

2022-08-02 13:43 UTC, gsmet commented
Will backport it to the next 2.11 micro.

2022-08-02 13:46 UTC, geoand commented
Great, thanks!