Fixes #2707: Use Files.newInputStream instead of FileInputStream directly
quarkusio/quarkus pull request #2708
Opened 2019-06-04 13:26 UTC by gastaldi

2019-06-04 13:27 UTC, gsmet commented
@gastaldi any chance you could work on a test?

That's what prevented me from fixing this one right away :).

2019-06-04 13:28 UTC, geoand commented
I was doing the same thing, but it's not enough unfortunately :) since it will blow up here: https://github.com/quarkusio/quarkus/blob/b046194de00415ebcf53207919b3fd805c18bf74/extensions/undertow/deployment/src/main/java/io/quarkus/undertow/deployment/WebXmlParsingBuildStep.java#L116

2019-06-04 13:32 UTC, gastaldi commented
@gsmet yeah, I'm going through the ShrinkWrap API to figure out how to do that.
@geoand you seem to be in a more advanced stage than me, feel free to reject/close this PR if you find a solution faster than me :)

2019-06-04 13:34 UTC, geoand commented
@gastaldi no worries, go ahead since I am sure you'll figure out the testing part before I do, so feel free to use the info I posted above about the problem I mentioned :)

2019-06-04 13:34 UTC, gsmet commented
@geoand yes, exactly. It doesn't need to be a separate one if all the Undertow tests are in the main integration tests.

As stated in the issue, we already do that for Hibernate ORM with the `common-jpa-entities` artifact.

2019-06-04 13:36 UTC, geoand commented
Then we just need to find a jar that contains `web-fragment.xml`. The one I tested unfortunately is myfaces from `master` so it's not released. If someone has a jar in mind, that would be great.

2019-06-04 13:37 UTC, gsmet commented
You two are so cute :).

2019-06-04 13:39 UTC, gastaldi commented
@geoand my idea is to generate this JAR using ShrinkWrap and add it to the JAR that's managed by Quarkus.

2019-06-04 13:40 UTC, geoand commented
@gastaldi I'm looking forward to seeing that in action :wink:

2019-06-04 13:45 UTC, gsmet commented
Not preventing you to do it if you want to have fun but we really need to be as close to real life as possible.

At first, the external jar approach had my preference for this very reason.

2019-06-04 16:31 UTC, geoand commented
@gastaldi should we add the `coding in progress` label?

2019-06-05 05:57 UTC, geoand commented on integration-tests/main/pom.xml
> +        <dependency>
Perhaps there should be a comment explaining why this dependency is added?

2019-06-05 07:10 UTC, gsmet requested changes
Looks mostly good to me. Could you adjust the type of the `Set` and squash everything into one commit?

Thanks!

2019-06-05 07:10 UTC, gsmet commented on extensions/undertow/deployment/src/main/java/io/quarkus/undertow/deployment/WebXmlParsingBuildStep.java
> +        Set<WebFragmentMetaData> webFragments = new HashSet<>();
Let's use a `Linked` one here.

2019-06-05 12:23 UTC, gsmet approved these changes

2019-06-05 12:23 UTC, merged