Bump smallrye-open-api from 2.1.23 to 2.2.0
quarkusio/quarkus pull request #27206
Opened 2022-08-09 13:25 UTC by MikeEdgar

Changes from 2.1.23 includes back-ported PRs listed in https://github.com/smallrye/smallrye-open-api/pull/1210

Fixes #27058
Fixes #26546
Fixes #26848

2022-08-10 00:52 UTC, MikeEdgar commented
Researching test failures

2022-08-17 08:04 UTC, gsmet commented
@radcortez it seems `HelloRouterTest` is failing nearly consistently now. Did you have any chance tracking the cause?

2022-08-17 08:05 UTC, gsmet requested changes
We need a Jakarta version of this one and an update here: https://github.com/quarkusio/quarkus/blob/main/jakarta/rewrite.yml#L560 in this very PR.

/cc @radcortez

2022-08-18 14:25 UTC, gsmet approved these changes

2022-08-18 14:25 UTC, merged