ubi8 based container for native mode application
quarkusio/quarkus pull request #2723
Opened 2019-06-05 07:42 UTC by rsvoboda

ubi8 based container for native mode application

Size benefit:
```
docker images | grep minimal
registry.access.redhat.com/ubi8/ubi-minimal   latest               3bfa511b67f8        5 weeks ago         90MB
registry.fedoraproject.org/fedora-minimal     latest               f0c38118c459        3 months ago        105MB
```

@johnaohara do you see any performance drawbacks of using ubi8 image ?

2019-06-05 11:53 UTC, cescoffier commented
@rsvoboda did you test it? 
Nicola reported a native library missing in ubi-minimal (libcrypt 2).

2019-06-05 12:04 UTC, rsvoboda commented
I tried, but probably too simple scenario.

2019-06-05 12:13 UTC, rsvoboda commented
Any candidate app to see this ?

Anyway, I think we should be based on ubi due to RH strategy.

If we miss something we should push to include it to -minimal or to have GraalVM friendly image.

2019-06-05 12:29 UTC, rsvoboda commented
```
docker run -i -t registry.access.redhat.com/ubi8/ubi-minimal bash
bash-4.4# rpm -ql libxcrypt
/lib64/.libcrypt.so.1.1.0.hmac
/lib64/.libcrypt.so.1.hmac
/lib64/libcrypt.so.1
/lib64/libcrypt.so.1.1.0
/usr/lib/.build-id
/usr/lib/.build-id/34
/usr/lib/.build-id/34/1fa4ebb1da9cbc83f3baf3522d288c29b3b460
/usr/share/doc/libxcrypt
/usr/share/doc/libxcrypt/NEWS
/usr/share/doc/libxcrypt/README
/usr/share/doc/libxcrypt/THANKS
/usr/share/licenses/libxcrypt
/usr/share/licenses/libxcrypt/AUTHORS
/usr/share/licenses/libxcrypt/COPYING.LIB
/usr/share/licenses/libxcrypt/LICENSING
/usr/share/man/man5/crypt.5.gz

bash-4.4# ls -l /lib64/libcrypt.so.1
lrwxrwxrwx 1 root root 17 Aug 12  2018 /lib64/libcrypt.so.1 -> libcrypt.so.1.1.0
```

2019-06-05 13:13 UTC, rsvoboda commented
BTW, we already suggest ubi minimal image in our guide - https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/openshift-s2i-guide.adoc

2019-06-05 13:18 UTC, lburgazzoli commented
So here the problem I'm facing:

- my host is Fedora 30
- I'm using quarkus 0.16.0
- I have libxcrypt-compat-4.4.6-1.fc30.x86_64, libxcrypt-4.4.6-1.fc30.x86_64 and libxcrypt-devel-4.4.6-1.fc30.x86_64 installed

Then when I build a native-image, I see that it links against libxcrypt.so.2:

```
$ ldd target/camel-k-runtime-example-quarkus-runner
    linux-vdso.so.1 (0x00007ffd33fff000)
    libm.so.6 => /lib64/libm.so.6 (0x00007fcacc590000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fcacc56f000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00007fcacc569000)
    libz.so.1 => /lib64/libz.so.1 (0x00007fcacc54f000)
    libcrypt.so.2 => /lib64/libcrypt.so.2 (0x00007fcacc514000)
    librt.so.1 => /lib64/librt.so.1 (0x00007fcacc50a000)
    libc.so.6 => /lib64/libc.so.6 (0x00007fcacc342000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fcacc6f2000)
```

Now when I run my binary in a docker container built using ubi8 (minimal or not does make any difference), I have the binary complaining about missing library:

```
$ docker run --rm -ti lburgazzoli/camel-k-quarkus:1
/deployment/runner: error while loading shared libraries: libcrypt.so.2: cannot open shared object file: No such file or directory
```

Looking at the libraries provided  by ubi8, I do not see `libcrypt.so.2`

2019-06-05 13:23 UTC, rsvoboda commented
The problem is not present in `fedora-minimal` based image ?

`camel-k-runtime-quarkus` module from https://github.com/lburgazzoli/apache-camel-k-runtime/tree/quarkus-runtime/camel-k-runtime-quarkus ?

2019-06-05 13:26 UTC, lburgazzoli commented
> The problem is not present in `fedora-minimal` based image ?

For sure not on fedora:30, will test against fedora mininmal

> `camel-k-runtime-quarkus` module from https://github.com/lburgazzoli/apache-camel-k-runtime/tree/quarkus-runtime/camel-k-runtime-quarkus ?

[Yes]( https://github.com/lburgazzoli/apache-camel-k-runtime/tree/quarkus-runtime/camel-k-runtime-examples/camel-k-runtime-example-quarkus), this is the example I'm using

2019-06-05 13:29 UTC, lburgazzoli commented
It happens also on fedora minimal as it appears to be based on fedora 29

2019-06-05 13:33 UTC, rsvoboda commented
https://fedoramagazine.org/building-smaller-container-images/
`FROM registry.fedoraproject.org/fedora-minimal:30`

You should be able to force version 30

2019-06-05 13:34 UTC, lburgazzoli commented
on fedora-minimal:30 it works out of the box

2019-06-05 13:44 UTC, cescoffier commented
@rsvoboda so, what about adding a note in the doc about the issue.

2019-06-05 13:49 UTC, rsvoboda commented
Something like "If you application requires libcrypt.so.2 you may consider registry.fedoraproject.org/fedora-minimal as base image" ?

2019-06-05 13:50 UTC, cescoffier commented
`fedoral-minimal:30` (or later) maybe?

2019-06-05 13:56 UTC, rsvoboda commented
PR updated

2019-06-05 14:11 UTC, cescoffier requested changes
a very very small comment.

2019-06-05 14:11 UTC, cescoffier commented on docs/src/main/asciidoc/building-native-image-guide.adoc
> +If your application requires libcrypt.so.2 you may consider registry.fedoraproject.org/fedora-minimal:30 (or later) as base image.
should the image name be between `` ?

2019-06-06 07:56 UTC, cescoffier approved these changes

2019-06-06 07:56 UTC, cescoffier commented
Waiting for CI.

2019-06-06 10:45 UTC, merged