Fix inconsitentcy in kubernetes commands / arguments handling between jvm and native
quarkusio/quarkus pull request #27733
Opened 2022-09-05 16:28 UTC by iocanel

The pull request addresses the inconsitencies between jvm and native mode when it comes to command / arguments handling.

With this change the s2i builder image is no longer taken into consideration.
The command may still be `generated` if the user provides arguments without command.

2022-09-05 16:31 UTC, gsmet submitted a review, later dismissed
Spotted some typos in variable names. Use your IDE to fix them as I only suggested the first occurrence.

2022-09-05 16:31 UTC, gsmet commented on extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftProcessor.java
> +        boolean hasCustomJvmArugments = config.jvmArguments.isPresent();
```suggestion
        boolean hasCustomJvmArguments = config.jvmArguments.isPresent();
```

2022-09-05 16:31 UTC, gsmet commented on extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftProcessor.java
> +        boolean hasCustomNativeArugments = config.nativeArguments.isPresent();
```suggestion
        boolean hasCustomNativeArguments = config.nativeArguments.isPresent();
```

2022-09-06 08:31 UTC, Sgitario requested changes
Other necessary changes could be to remove the `OpenshiftConfig.getEffectiveJvmArguments` method which is confusing and does not add much value. 
Also, we have this `getEffectiveJvmArguments` method in JIBConfig and S2IConfig because we had a default value for the jvmArguments, so had two properties `jvmArguments` and `jvmAdditionalArguments`. We should validate that this default value in `jvmArguments` and the `jvmAdditionalArguments` are respected after these changes.
Finally, I'm missing some tests to verify the actual change. As far I understand, before these changes, we only generated a command if we didn't know about the base image. Now, we're always generating the command if a custom jar path or the arguments are set by the user, regardless the base image we're using.
Another last note, this could be a breaking change that should be noted in the release notes.

2022-09-06 08:31 UTC, Sgitario commented on extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftProcessor.java
> +                commandProducer.produce(new KubernetesCommandBuildItem(cmd, config.jvmArguments.get()));
This is not correct. One thing is the JVM arguments (for example: `-Dprop=key`), and another thing is the program arguments which is addressed with `quarkus.kubernetes.arguments`.

2022-09-12 07:35 UTC, Sgitario approved these changes
The changes look good to me.
Moreover, I checked the reproducer in the linked issue and now the generated `DeploymentConfig` resource is the same for JVM and Native. So, the app should behave the same.

2022-09-12 07:45 UTC, merged