Update mvn commands in docs to much the ones ran by quarkus-cli
quarkusio/quarkus pull request #27748
Opened 2022-09-06 09:12 UTC by zakkak

`quarkus build` runs `mvn install` not `mvn package`

The main noticeable difference when it come to the guides is that
`mvn install` also runs tests while `mvn package` doesn't, though
some guides imply that the tests are being run even with `mvn package`.

2022-09-06 10:28 UTC, Sanne commented
hum but we don't want to actualy `install` the artifacts in the repository ?

2022-09-06 10:30 UTC, Sanne commented
Please consider: https://andresalmiray.com/maven-verify-or-clean-install/

2022-09-06 10:41 UTC, zakkak commented
> hum but we don't want to actualy `install` the artifacts in the repository ?
> Please consider: https://andresalmiray.com/maven-verify-or-clean-install/

In that case we will also need a different quarkus-cli command that will run `mvn verify` instead of `mvn install` behind the scenes. I am not familiar with quarkus CLI though so I am not sure what that command would be (if available at all). I guess we will also need to find the equivalent for gradle (which again I am not familiar with)?

2022-09-06 11:34 UTC, Sanne commented
Right, not sure why `quarkus-cli` is doing something odd, but I think our docs should state `verify`. And no need for `clean`.

2022-09-06 14:49 UTC, gsmet requested changes
I just added a suggestion to make it less of a mouthful.

Also personally, I would rather have the CLI compile the tests even if not executing it but that will probably end up in endless discussions so let's keep it that way :).

2022-09-06 14:49 UTC, gsmet commented on docs/src/main/asciidoc/includes/devtools/build-native-container.adoc
> +./mvnw install -Dnative -DskipTests -Dmaven.test.skip=true -Dquarkus.native.container-build=true {build-additional-parameters}
```suggestion
./mvnw install -Dnative -DskipTests -Dquarkus.native.container-build=true {build-additional-parameters}
```

2022-09-06 14:49 UTC, gsmet commented on docs/src/main/asciidoc/includes/devtools/build-native-container.adoc
> +./mvnw install -Dnative -DskipTests -Dmaven.test.skip=true -Dquarkus.native.container-build=true
```suggestion
./mvnw install -Dnative -DskipTests -Dquarkus.native.container-build=true
```

2022-09-07 08:36 UTC, gsmet approved these changes

2022-09-07 08:36 UTC, merged