Improve Reactive Route guide
quarkusio/quarkus pull request #27765
Opened 2022-09-06 15:38 UTC by loicmathieu

2022-09-06 15:40 UTC, cescoffier approved these changes

2022-09-06 18:52 UTC, gsmet requested changes
Thanks, I spotted a few things.

2022-09-06 18:52 UTC, gsmet commented on docs/src/main/asciidoc/reactive-routes.adoc
> +by example, adding header info, or specifying the return type on `void` methods might be useful:
```suggestion
for instance, adding header info, or specifying the return type on `void` methods might be useful:
```
(or for example)

2022-09-06 18:52 UTC, gsmet commented on docs/src/main/asciidoc/reactive-routes.adoc
> +<1> If the `accept` header matches `text/html` we set the content type automatically to `text/html`.
```suggestion
<1> If the `accept` header matches `text/html`, we set the content type automatically to `text/html`.
```

2022-09-06 18:52 UTC, gsmet commented on docs/src/main/asciidoc/reactive-routes.adoc
> +If no content-type header is set,  then we will try to use the most acceptable content type by matching the accept header with the value of the `Route` produces attribute as defined by `io.vertx.ext.
```suggestion
If no content-type header is set, then we will try to use the most acceptable content type by matching the accept header with the value of the `Route` produces attribute as defined by `io.vertx.ext.web.RoutingContext.getAcceptableContentType()`.
```

2022-09-06 18:52 UTC, gsmet commented on docs/src/main/asciidoc/reactive-routes.adoc
> +<7> The path define a parameter `name` which can be injected inside the method parameters using the annotation `@Param`.
```suggestion
<7> The path defines a parameter `name` which can be injected inside the method parameters using the annotation `@Param`.
```

2022-09-07 07:43 UTC, loicmathieu commented
Thanks @gsmet, team works ;), I applied your changes.

2022-09-07 07:55 UTC, gsmet approved these changes

2022-09-07 08:05 UTC, merged