Upgrade SmallRye Health to 3.3.0
quarkusio/quarkus pull request #27829
Opened 2022-09-09 09:24 UTC by xstefank

2022-09-09 09:24 UTC, xstefank commented
@gsmet let me know please how should I port this to jakarta branch. There is a matching 4.0.0 jakarta release to 3.3.0.

2022-09-09 14:35 UTC, gsmet commented
@xstefank just update: https://github.com/quarkusio/quarkus/blob/main/jakarta/rewrite.yml#L520-L522 in the same commit and it's good to go!

2022-09-09 14:36 UTC, gsmet requested changes
Let's wait for the Jakarta update before merging.

2022-09-09 14:43 UTC, gastaldi commented on extensions/smallrye-health/deployment/src/main/java/io/quarkus/smallrye/health/deployment/SmallRyeHealthConfig.java
> +    Optional<Integer> maxGroupRegistriesCount;
Use `OptionalInt` instead

2022-09-09 14:44 UTC, gastaldi commented on extensions/smallrye-health/deployment/src/main/java/io/quarkus/smallrye/health/deployment/SmallRyeHealthProcessor.java
> +                        "io.smallrye.health.maxGroupRegistriesCount", String.valueOf(count))));
Better avoid lambdas in here

2022-09-12 11:24 UTC, gastaldi approved these changes

2022-09-12 11:25 UTC, gsmet approved these changes

2022-09-13 09:21 UTC, xstefank commented
@gsmet personally, I think the failures are not related.

2022-09-13 12:20 UTC, merged