Fix bot notifications for extension proposals
quarkusio/quarkus pull request #27964
Opened 2022-09-15 14:55 UTC by gastaldi

- Issues with `[Extension Proposal]` in the title are properly labeled
- Add repository topics format explanation

2022-09-15 15:07 UTC, gastaldi commented on .github/quarkus-github-bot.yml
> +    - labels: [kind/extension-proposal, area/quarkiverse]
Hm, sorry. How do I ping those people when these labels are added?

2022-09-15 16:10 UTC, gsmet commented on .github/quarkus-github-bot.yml
> +    - labels: [kind/extension-proposal, area/quarkiverse]
Yeah for now you can't. Not hard to implement, the most difficult part would be to define how to express it in the configuration file.

2022-09-15 16:11 UTC, gsmet requested changes

2022-09-15 16:11 UTC, gsmet commented on .github/quarkus-github-bot.yml
> +      title: "[Extension Proposal]"
This is interpreted as a regex so better not make it a character class so either that fix, or you have to escape the regex properly (I don't think it's worth the hassle):
```suggestion
      title: "Extension Proposal"
```

2022-09-19 08:42 UTC, gsmet approved these changes

2022-09-19 08:42 UTC, merged