Avoid using internal API from package `org.graalvm.nativeimage.impl`
quarkusio/quarkus pull request #28093
Opened 2022-09-20 12:56 UTC by zakkak

As discussed in https://github.com/quarkusio/quarkus/pull/27728#discussion_r971970749

2022-09-27 09:27 UTC, zakkak commented
The removal of the remaining usages requires upstream changes, see https://github.com/oracle/graal/issues/5013.

2022-09-28 06:28 UTC, zakkak commented
@jerboaa can you please review this?

2022-09-28 11:04 UTC, galderz approved these changes
LGTM but @jerboaa should have a second look since he was involved in the original discussions.

2022-09-28 12:58 UTC, jerboaa requested changes
Looks mostly good. I think one unintentional change from runtime->buildtime sneaked in, though.

2022-09-28 12:58 UTC, jerboaa commented on extensions/awt/runtime/src/main/java/io/quarkus/awt/runtime/graal/DarwinAwtFeature.java
> +            RuntimeClassInitialization.initializeAtBuildTime("sun.lwawt.macosx");
Typo? `s/initializeAtBuildTime/initializeAtRunTime/`

2022-09-28 13:23 UTC, zakkak commented on extensions/awt/runtime/src/main/java/io/quarkus/awt/runtime/graal/DarwinAwtFeature.java
> +            RuntimeClassInitialization.initializeAtBuildTime("sun.lwawt.macosx");
Good catch. Thanks @jerboaa

2022-09-28 14:51 UTC, jerboaa approved these changes
LGTM

2022-09-29 06:13 UTC, merged