Register the StorkClientRequestFilter when we detect a URI starting with stork:// or storks://
quarkusio/quarkus pull request #28296
Opened 2022-09-29 13:46 UTC by cescoffier

Fix https://github.com/quarkusio/quarkus/issues/28292

2022-09-29 13:50 UTC, geoand approved these changes
We should probably move this logic to build time as a next step, but it's fine for now to overcome the original issue

2022-09-29 14:04 UTC, Sgitario reviewed
The changes look good to me, however I think it can easily be covered by reusing this test: https://github.com/quarkusio/quarkus/blob/main/extensions/resteasy-reactive/rest-client-reactive/deployment/src/test/java/io/quarkus/rest/client/reactive/stork/StorkDevModeTest.java

2022-09-29 14:30 UTC, aureamunoz approved these changes
I don't know very well this part about filters so this LGTM.
Shouldn't we add a test also?

2022-09-29 15:53 UTC, aureamunoz requested changes

2022-09-29 15:53 UTC, aureamunoz commented on independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/WebTargetImpl.java
> +        if (actualUri.getScheme().startsWith("stork") && !isStorkAlreadyRegistered(configuration)) {
```suggestion
        if (actualUri.getScheme() != null && actualUri.getScheme().startsWith("stork") && !isStorkAlreadyRegistered(configuration)) {
```

2022-09-29 15:53 UTC, aureamunoz commented on independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/WebTargetImpl.java
> +        if (actualUri.getScheme().startsWith("stork") && !isStorkAlreadyRegistered(configuration)) {
This fixes the InvalidURITest failing currently

2022-09-29 17:52 UTC, cescoffier commented
Sorry got caught up by another urgent matter. I will have a look at the issues tomorrow morning.

(And here goes my blog post...)

2022-09-30 07:31 UTC, cescoffier commented
@Sgitario I added some tests.

2022-09-30 07:43 UTC, Sgitario approved these changes
lgtm!

2022-09-30 08:25 UTC, merged