Update kotlin.version 1.7.20
quarkusio/quarkus pull request #28338
Opened 2022-10-01 11:42 UTC by andreas-eberle

Replaces #28332. It seems dependabot missed a couple of occurences of the kotlin version.

2022-10-01 12:41 UTC, andreas-eberle commented
It looks like the M1 Job fails during setup. Is this to be expected? Is there something I can do about it?

2022-10-01 14:20 UTC, gsmet requested changes
I need to prepare the 1.7.20 branch for Jakarta before we merge this.

2022-10-04 13:03 UTC, andreas-eberle commented
@gsmet : When you think you can provide the branch? If you want, I might be able to send you a PR. 

In general: Why does Quarkus need a separate branch of Kotlin? Could it make sense to try to get these changes into upstream Kotlin?

2022-10-04 13:46 UTC, gsmet commented
Ah thanks, it slipped my mind.

We need a Kotlin branch for the Jakarta transformation script: https://github.com/gsmet/kotlin/commit/4c8859612ba51f4d4755283342c026f01fa40750 . I need to be able to run a build without compiling anything and Kotlin was in the way. It's just for the transformation, the runtime version is still stock 1.7.20.

I think it should be contributed back to Kotlin but I never found the time (the patch is simple but I have to idea if they expect tests or things like that). If you can do it, that would be awesome.

2022-10-04 13:46 UTC, gsmet commented
I prepared the branch and squashed the commits.

2022-10-04 13:47 UTC, merged