Go offline project
quarkusio/quarkus pull request #28463
Opened 2022-10-10 06:25 UTC by Noonchi1004

@aloubyansky implemented the changes, but wasn't able to test them properly

2022-10-10 06:31 UTC, aloubyansky commented
@Noonchi1004 thanks! Looks good. Please squash your (3) commits into one. And add `Fix #27615` to the PR description. GitHub will automatically close that issue once this PR has been merged.

2022-10-10 06:51 UTC, Noonchi1004 commented
Fix #27615

2022-10-10 11:24 UTC, aloubyansky requested changes
This change is currently including an unrelated commit and needs a proper rebase. We discussed it with @Noonchi1004 already.

2022-10-12 04:49 UTC, aloubyansky approved these changes

2022-10-12 04:49 UTC, merged