Promote quarkus-hibernate-orm-rest-data-panache to stable
quarkusio/quarkus pull request #28569
Opened 2022-10-13 13:05 UTC by FroMage

Fixes QUARKUS-2390

2022-10-13 13:07 UTC, geoand approved these changes

2022-10-13 13:36 UTC, rsvoboda approved these changes

2022-10-13 16:39 UTC, gsmet requested changes
I think the status probably needs to be clarified here too: https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/rest-data-panache.adoc .

I have no idea if they have all the same status or if we should include the status in the table.

2022-10-14 15:01 UTC, FroMage commented
Ah yes, thanks, I removed that status.

2022-10-15 17:00 UTC, gsmet approved these changes

2022-10-15 17:00 UTC, gsmet commented
Force pushed a small adjustment to remove the extension status include.

2022-10-15 22:29 UTC, merged