Propagate the javax.annotation.security annotations in REST Data
quarkusio/quarkus pull request #29009
Opened 2022-11-02 13:48 UTC by Sgitario

With these changes, the REST Data with Panache extension will propagate the Security annotations within the package `javax.annotation.security` that are defined on your resource interfaces:

```java
import javax.annotation.security.DenyAll;
import javax.annotation.security.RolesAllowed;

@DenyAll
@ResourceProperties
public interface PeopleResource extends PanacheEntityResource<Person, Long> {
    @RolesAllowed("superuser")
    boolean delete(Long id);
}
```

Additionally, if you are only interested in specifying the roles that are allowed to use the resources, the `@ResourceProperties` and `@MethodProperties` annotations have the field `rolesAllowed` to list the security roles permitted to access the resource or operation.

Fix https://github.com/quarkusio/quarkus/issues/28995

2022-11-02 13:49 UTC, Sgitario commented
cc @geoand @punkratz312

2022-11-02 13:52 UTC, geoand approved these changes

2022-11-02 14:32 UTC, sberyozkin commented
@Sgitario Hi Jose, can you please add a small section to the main `security.adoc` to link back to the rest-panache doc, for example, just next to https://quarkus.io/guides/security#secure-serialization

2022-11-02 14:47 UTC, gsmet requested changes

2022-11-02 14:47 UTC, gsmet commented on extensions/panache/rest-data-panache/deployment/src/main/java/io/quarkus/rest/data/panache/deployment/properties/ResourcePropertiesProvider.java
> +    private static final List<String> ANNOTATIONS_TO_COPY = List.of("javax.annotation.security");
Could you make it `RolesAllowed.class.getPackageName()`. I'd like to make sure it's rewritten by the Jakarta scripts.

2022-11-02 15:21 UTC, Sgitario commented
> @Sgitario Hi Jose, can you please add a small section to the main `security.adoc` to link back to the rest-panache doc, for example, just next to https://quarkus.io/guides/security#secure-serialization

Added

2022-11-02 15:25 UTC, gsmet approved these changes

2022-11-02 17:08 UTC, sberyozkin commented
Thanks @Sgitario, we have various security features supported across different extensions, so it makes sense to have a map of all of them in one place :-)

2022-11-02 20:53 UTC, punkratz312 commented
thanks for fast response

2022-11-03 03:59 UTC, geoand approved these changes

2022-11-03 03:59 UTC, merged