Fix concurrency bug
quarkusio/quarkus pull request #29159
Opened 2022-11-09 19:32 UTC by imperatorx

Fix #29157 

Introduced locking to prevent initialization of TransactionScoped beans when called from different threads concurrently (think virtual threads and StucturedTaskScope forks). 

ReentrantLock is used instead of synchronized blocks to make the locking virtual thread friendly. The computeIfAbsent usage of the ConcurrentHashMap in TransactionContextState would also be problematic (uses synchronized blocks internally) when bean creation does IO, like establishing a TCP connection, thus pinning the virtual threads carrier thread.

2022-11-10 13:17 UTC, gastaldi commented
/cc @mmusgrov

2022-11-10 13:34 UTC, gsmet commented
/cc @sanne too

2022-11-22 12:41 UTC, mmusgrov requested changes
The changes look ok but it'd be good if someone with CDI experience (mine is in transactions) could take a look, maybe @mkouba or @manovotn .

But we need a test for this because the MP CP TCK @Ignore`s the test [1] for the feature (the SmallRye implementation did pass the test before it was ignored). Can a similar test be added to this PR.

[1] https://github.com/eclipse/microprofile-context-propagation/blob/master/tck/src/main/java/org/eclipse/microprofile/context/tck/cdi/JTACDITest.java#L250

2022-11-22 12:56 UTC, mmusgrov commented
Do we have a feel for the performance overhead added by the extra locking? Is the performance hit only on the first request for a contextual instance (jakarta.enterprise.context.spi.Context.get(...))?

2022-11-22 14:47 UTC, manovotn commented
> Do we have a feel for the performance overhead added by the extra locking? Is the performance hit only on the first request for a contextual instance (jakarta.enterprise.context.spi.Context.get(...))?

[As per CDI documentation](https://github.com/jakartaee/cdi/blob/master/api/src/main/java/jakarta/enterprise/context/spi/Context.java#L64-L75), `Context#get()` is called whenever you need to obtain a bean instance. It either returns an existing one, or creates a new one.
How and when you choose to perform locking is up to the context implementation. Obviously, you ideally want to only lock when you find out there is no instance and you are about to create a new one store it into context before returning it.

2022-11-22 15:56 UTC, Sanne commented
Hi @imperatorx , thanks - it looks good at high level but there's some details I'd like to clarify.

You seem to have wrapped within the lock also the acces to the `TransactionSynchronizationRegistry` (the invocation of `transactionSynchronizationRegistry.get()`, which is a `LazyValue`.

`LazyValue` already provides concurrent initialization safeguards - but it's relying on `synchronization`. 
Is that something that should be fixed as well? There's more access to it beyond the block you've just protected; in general I wonder how any of this code could work safely with virtual threads.

2022-11-22 19:07 UTC, imperatorx commented
I updated the PR:

- Added a test
- Removed the LazyValue.get() from the synchronized block as @Sanne suggested.
- Removed the double-checked locking from the first lock, since uncontended locking (single threaded regular use case) uses a simple compare-and-set operation (see NonfairSync.initialTryLock in ReentrantLock), but the two `getResource` calls do a lot of things. So IMHO one compare-and-set is better performance-wise than an additional `getResource` call (calls TransactionManager.getTransaction(), accessess a synhronized hashmap, etc.)

As for refactoring LazyValue: Syncronized blocks work well with virtual threads if there is no blocking done inside them (IO, native calls, sleep, etc.), and the TransactionContext use case has none of it, it just returns a new instance. If other LazyValue use cases have blocking work in the creation part of the new instance, the synhronized block should be changed to a ReentrantLock.

2022-11-22 19:47 UTC, Sanne commented
Excellent, thanks :+1: and I agree with the decision regarding, `LazyValue` I asked because in the previous revision of the patch is seemed like you intentetionally included that in the critical section.

Could you squash the changes together and avoid the `import javax.transaction.*;` please? It's a very minor nitpick, but we prefer listing all individual imports.

2022-11-22 19:48 UTC, Sanne requested changes
Suggested two minor changes, however even in current state I think it's good.

2022-11-22 20:27 UTC, Sanne approved these changes

2022-11-24 10:44 UTC, mmusgrov approved these changes
Thanks for adding the test and for answering my performance question.

2022-11-24 12:01 UTC, manovotn commented
@mmusgrov FYI, the very same problem is in Narayana codebase, see https://github.com/jbosstm/narayana/blob/master/ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/TransactionContext.java

2022-11-24 12:07 UTC, manovotn commented
@mmusgrov Also how does this solution link into the discussion in https://github.com/quarkusio/quarkus/issues/29157#issuecomment-1311786983?
Does Narayna support that or not? This PR makes sure there is no bean creation race but IMO doesn't answer the MP CP question and we still lack test that would verify it either way.

2022-11-24 12:12 UTC, imperatorx commented
> @mmusgrov Also how does this solution link into the discussion in [#29157 (comment)](https://github.com/quarkusio/quarkus/issues/29157#issuecomment-1311786983)? Does Narayna support that or not? This PR makes sure there is no bean creation race but IMO doesn't answer the MP CP question and we still lack test that would verify it either way.

No, sadly Narayana does not fully support this workload: in case an exception is thrown inside a child virtual thread, the unwinding of the context propagation causes the transaction on the parent thread to get deactivated. I'll look into that if I have time, the culprit seems to be https://github.com/smallrye/smallrye-context-propagation/blob/main/jta/src/main/java/io/smallrye/context/jta/context/propagation/JtaContextProvider.java#L65

2022-11-24 15:13 UTC, mmusgrov commented
> @mmusgrov FYI, the very same problem is in Narayana codebase, see https://github.com/jbosstm/narayana/blob/master/ArjunaJTA/cdi/classes/com/arjuna/ats/jta/cdi/TransactionContext.java

That code was added to support the wildfly-mp-reactive-feature-pack (https://github.com/wildfly-extras/wildfly-mp-reactive-feature-pack) which we did at the request of the WildFly team. I'll check with Kabir to see if there is any mechanism to get some concurrency testing (with respect to transaction propagation) added to the feature pack.

2022-11-24 15:47 UTC, manovotn commented
> That code was added to support the wildfly-mp-reactive-feature-pack (https://github.com/wildfly-extras/wildfly-mp-reactive-feature-pack) which we did at the request of the WildFly team. 

The `Context` impl class must have been present (in one form or another) since JTA wanted to integrate with CDI and have their own custom `@TransactionalScoped`.

2022-11-24 16:47 UTC, mmusgrov commented
@manovotn Yes but isn't this bug only present when used with MP CP with parallel threads sharing the same transaction and we aren't testing that in narayana and the code was requested by WildFly as an incubator for reactive messaging, reactive streams operators and context propagation and, it turns out, is not used after all by WildFly, I'm checking to see who else might use it.

So if nobody is using it then I'd prefer to either send users to the Quarkus JTA extension for the functionality or ask them to raise an RFE.

And if nobody is using the feature in narayana and we remove it would we still need to protect the Context (I don't see any other code protecting the CDI Context in this way).

But that said, I will still look into how easy it would be for us to add the testing of MP CP to our own testsuite even if there is every chance it never get used!!

2022-11-24 16:50 UTC, merged

2022-11-24 17:48 UTC, manovotn commented
I was simply pointing out that it might make sense to keep the `TransactionalContext` code/behavior identical (or as identical as possible) between both codebases. Whether you do it is ultimately up to you :)

2022-11-25 09:13 UTC, mmusgrov commented
Ok it may make sense to keep them aligned and thanks for pointing it out. I will report back if/when we decide to include SmallRye testing in the Naryana CDI module.

2022-11-27 12:46 UTC, imperatorx commented
@Sanne @mmusgrov @manovotn 

I've investigated the multiple child thread exception handling issue, and found the reason:

Good news: if users will use JEP-428 StructuredTaskScope, Quarkus and smallyre-context-propagation will work as expected. 

In other cases, special care needs to be taken to await cancellation of child threads in case of errors, as simply interrupting them makes a way for a race condition to occur when smallyre-context-propagation does not unwind the transaction before the parent thread enters the rollback phase. 

I think this is not something that has to be "fixed" in smallrye or quarkus, but user code must make sure that by the time the parent thread completes or throws (so that commit or rollback can happen) all child threads are completed, not just cancelled or marked for interruption.

Examples:

I've shared the source and test for a proof-of-concept `quarkus-foundationdb` quarkus module:

1. JEP-428: Here your can see that the `Forker` class just wraps the `Callable` into a `ThreadContext.contextualCallable(callable)` and calls `join().throwIfFailed()` in the `AutoClosable` interface. Everyting works as expected. https://gitlab.com/qfoundation/quarkus-foundationdb/-/blob/5b7a05c26f0eb5116f983e902ce12f2b5acd5668/sample/src/test/java/io/gitlab/qfoundation/JtaTest.java#L132
2. Naive cancellation of children using simple `Future.cancel(true)` interrupts: The parent thread catches the error, cancels the children and rolls back the exception. However, smallrye-context-propagation has not yet finished after the interrupt, so the transaction rollback sees multiple active threads for the transaction and fails. https://gitlab.com/qfoundation/quarkus-foundationdb/-/blob/5b7a05c26f0eb5116f983e902ce12f2b5acd5668/sample/src/test/java/io/gitlab/qfoundation/JtaTest.java#L233 You can see the test fail if your remove `@Disabled`
3. Added synchronization points to the later case: The suppliers wrapped by smallyre-context-propagation are once more wrapped with syncronization barriers so that the parent thread can make sure that all child tasks have completed and the unwinding of the transaction context completed (see semaphore usage): https://gitlab.com/qfoundation/quarkus-foundationdb/-/blob/5b7a05c26f0eb5116f983e902ce12f2b5acd5668/sample/src/test/java/io/gitlab/qfoundation/JtaTest.java#L353

In my opinion, when JEP-428 comes out of incubation, users can use ` smallyre-context-propagation` with multiple concurrent threads in a trivial manner.