Fixed error in Stork guide
quarkusio/quarkus pull request #29204
Opened 2022-11-11 12:24 UTC by hbelmiro

PR to update the quickstart: https://github.com/quarkusio/quarkus-quickstarts/pull/1210

2022-11-11 14:01 UTC, aureamunoz approved these changes
Yes! LGTM. Thank you

2022-11-15 10:12 UTC, gsmet requested changes

2022-11-15 10:12 UTC, gsmet commented on docs/src/main/asciidoc/stork.adoc
> +    @ConfigProperty(name = "blue-service-port", defaultValue = "9001") int blue;
Minor comment but given we are changing the order here, could we also change the order in which the services are registered a few lines below? That would be less confusing IMHO.

2022-11-16 12:55 UTC, gsmet approved these changes
I force pushed the adjustment I was asking for so that we can merge.

2022-11-16 13:46 UTC, merged