update latest brew openjdk package
quarkusio/quarkus pull request #29220
Opened 2022-11-11 20:34 UTC by spolti

latest openjdk is now 19: 

$ brew info openjdk
==> openjdk: stable 19.0.1 (bottled) [keg-only]

2022-11-14 08:07 UTC, geoand commented
I think we intentionally want Java 17 there instead of the latest JDK, but I'll let @maxandersen decide

2022-11-15 10:04 UTC, gsmet requested changes

2022-11-16 12:57 UTC, gsmet approved these changes
I rebased and squashed the commits.

2022-11-16 13:46 UTC, merged

2022-11-16 13:47 UTC, gsmet commented
Thanks!