Add HTTPS port configuration in the HTTP reference guide
quarkusio/quarkus pull request #29356
Opened 2022-11-18 17:27 UTC by loicmathieu

There is no mention of the value of the HTTPS port in the HTTP reference guide, nor the way to configure it.

This PR add a small section for this issue.

2022-11-18 17:42 UTC, gsmet requested changes, later dismissed
Thanks! Added some suggestions.

2022-11-18 17:42 UTC, gsmet commented on docs/src/main/asciidoc/http-reference.adoc
> +By default, Quarkus listen to port 8443 for SSL secured connection and 8444 when running tests.
```suggestion
By default, Quarkus listens to port 8443 for SSL secured connections and 8444 when running tests.
```

2022-11-18 17:42 UTC, gsmet commented on docs/src/main/asciidoc/http-reference.adoc
> +These ports can be configured in your `application.properties` thanks to the properties `quarkus.http.ssl-port` and `quarkus.http.test-ssl-port`.
```suggestion
These ports can be configured in your `application.properties` with the properties `quarkus.http.ssl-port` and `quarkus.http.test-ssl-port`.
```

2022-11-19 15:05 UTC, loicmathieu commented
@gsmet I applied you suggestions.

2022-11-21 07:43 UTC, geoand approved these changes
Thanks!

2022-11-21 07:43 UTC, merged