Javadoc Warnings in the Gradle plugin
quarkusio/quarkus pull request #29371
Opened 2022-11-20 17:16 UTC by abhishekS14

2022-11-20 17:42 UTC, gastaldi approved these changes, later dismissed

2022-11-20 18:10 UTC, abhishekS14 commented
@gastaldi Hi, squashed a change, seems to be some formatting issue during the build

2022-11-20 18:13 UTC, gastaldi commented
@abhishekS14 you need to run `mvn process-sources` to have the format applied properly to your changes

2022-11-20 18:22 UTC, abhishekS14 commented
@gastaldi I have made the changes in the squashed PR, checked locally using the mvn process-sources, does not reflect any new changes after the squashed pr
Should pass the checks

2022-11-20 19:22 UTC, glefloch requested changes
Thanks for this work @abhishekS14. I just left two minor comments.

2022-11-20 19:22 UTC, glefloch commented on .gitattributes
> -# ./mvnw fails on Windows in git bash if -Xmx in that file has a trailing CRLF
Could you revert this file? It looks like EOL changed.

2022-11-20 19:22 UTC, glefloch commented on independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus-extension/code/extension-codestart/java/runtime/src/main/codestarts/quarkus/{extension.id}-codestart/base/src/main/resources/META-INF/resources/index.entry.qute.html
> -{#include index-entry /}
Is it normal that this file is deleted?

2022-11-21 07:33 UTC, abhishekS14 commented
I think I will close this, and create a new PR.

2022-11-21 07:33 UTC, closed without merging