Add custom gRPC exception handling
quarkusio/quarkus pull request #29419
Opened 2022-11-22 18:44 UTC by alesj

This helps with the issue #26869.

It adds a way for user to map its (custom) non-gRPC exceptions to gRPC's Status exceptions.
There is a default ExceptionHandlerProvider with default ExceptionHandler.

ExceptionHandler is used in newly added ExceptionInterceptor - which wraps the calls / invocations,
whereas `ExceptionHandlerProvider::transformToStatusRuntimeException` is used in static calls to ServerCalls from Mutiny integration.

We test both - plain and mutiny type of services.

2022-11-23 09:20 UTC, geoand commented
CI failures definitely seem relates

2022-11-23 11:54 UTC, alesj commented
@geoand yeah ... will have a look asap

2022-11-25 12:01 UTC, cescoffier requested changes
LGTM, it would just require some documentation.

2022-12-05 07:51 UTC, cescoffier commented
@alesj any update about the documentation?

2023-01-09 07:33 UTC, cescoffier approved these changes

2023-01-09 12:33 UTC, merged

2023-01-17 02:50 UTC, hernael commented
@alesj Please, Could you show me an example to try this feature?

2023-01-17 05:46 UTC, alesj commented
> Please, Could you show me an example to try this feature?

* https://github.com/quarkusio/quarkus/blob/main/integration-tests/grpc-interceptors/src/main/java/io/quarkus/grpc/examples/interceptors/HelloExceptionHandlerProvider.java
* https://github.com/quarkusio/quarkus/commit/7284d5457ace4ba0c96efa4cfef9aaacf40da2e6#diff-fbd9a4f3e78757655a1714b9088704669e084a0354051a71a73465d98e022e9a

HTH

2023-02-07 18:01 UTC, SivaM07 commented
@alesj , incase of multiple custom exceptions then can we implement multiple ExceptionHandlerProvider(one for each custom exception)?
But based on the code it looks like we can have only one implementation and custom handling of each specific custom exception has to go into if else blocks of the transform method.

Could you please clarify?

2023-02-07 18:50 UTC, alesj commented
Yes, only one handler.
But then you have 1M options to impl custom handling. 😉

On Tue, 7 Feb 2023 at 19:02, Siva_M7 ***@***.***> wrote:

> @alesj <https://github.com/alesj> , incase of multiple custom exceptions
> then can we implement multiple ExceptionHandlerProvider(one for each custom
> exception)?
> But based on the code it looks like we can have only one implementation
> and custom handling of each specific custom exception has to go into if
> else blocks of the transform method.
>
> Could you please clarify?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/quarkusio/quarkus/pull/29419#issuecomment-1421223114>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACRA6DIOAGCTZRUY4F2MKTWWKE2BANCNFSM6AAAAAASIEMWR4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>