Exclude Netty's reflection configuration files
quarkusio/quarkus pull request #29493
Opened 2022-11-25 14:21 UTC by zakkak

These are causing warnigns during native image compilation as they try to access classes that are not on the
classpath (e.g. `net.jpountz.lz4.LZ4Exception`).

Closes #29413

2022-11-25 14:25 UTC, geoand approved these changes

2022-11-25 14:31 UTC, zakkak commented
Scheduled CI runs:

* Linux: https://github.com/graalvm/mandrel/actions/runs/3548741986
* Windows: https://github.com/graalvm/mandrel/actions/runs/3548757419

2022-11-25 19:34 UTC, zakkak commented
Windows run failed with:
```
The system cannot find the path specified.
```

I guess I am hitting [what Sanne described](https://github.com/quarkusio/quarkus/issues/29413#issuecomment-1327504398), I will create two separate build items instead of a single one with a complex regex.

2022-11-25 20:44 UTC, zakkak commented
Scheduled CI runs for native:

* Linux: https://github.com/graalvm/mandrel/actions/runs/3550620530
* Windows: https://github.com/graalvm/mandrel/actions/runs/3550623804

2022-11-26 06:56 UTC, zakkak commented
Windows still failing, this time with:

```
Error: Unknown argument: quarkus-integration-test-resteasy-jackson-999-SNAPSHOT-runner
```

I will come back to this next week

2022-11-28 22:17 UTC, zakkak commented
It looks like windows don't like `.*` in the exclude-config patterns.

@Sanne I changed the Oracle-JDBC pattern as well since it was also not working on windows. Please have a look.

It looks like an upstream issue to me so I will try to create a simple reproducer not relying on Quarkus and see where it takes me.

2022-11-29 06:34 UTC, geoand approved these changes

2022-11-29 09:51 UTC, Sanne commented
> @Sanne I changed the Oracle-JDBC pattern as well since it was also not working on windows. Please have a look.

are you sure of that? It was passing the tests AFAIK - or was this being disabled in some way?

2022-11-29 09:56 UTC, zakkak commented
> > @Sanne I changed the Oracle-JDBC pattern as well since it was also not working on windows. Please have a look.
> 
> are you sure of that? It was passing the tests AFAIK - or was this being disabled in some way?

The only native test being run on windows appears to be resteasy-jackson

https://github.com/quarkusio/quarkus/blob/6a2b1b4dc306a97f827cb0979dc35a40784b2085/.github/native-tests.json#L135-L140

and I think it has been that way since day one.

2022-11-29 10:10 UTC, zakkak commented on extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyOverrideMetadata.java
> +    static final String NETTY_CODEC_JAR_MATCH_REGEX = "io\\.netty\\.netty-codec";
Internally it uses `Pattern.compile(excludeJar).matcher(path).find()` which matches even without the `*` in the beginning or the end.

2022-11-29 10:11 UTC, zakkak commented on extensions/netty/deployment/src/main/java/io/quarkus/netty/deployment/NettyOverrideMetadata.java
> +    static final String NETTY_CODEC_JAR_MATCH_REGEX = "io\\.netty\\.netty-codec";
I think we can also just quote the regex though. I will be able to test it in the next couple of hours.

2022-11-29 10:14 UTC, Sanne requested changes
@zakkak many thanks for clarifying - I remember that before I separated the two exclusions it did fail on Windows, but I guess that was a compilation failure and not a test failure. Nice catch, thanks.

But in this case..  would you mind separating the two fixes? The oracle JDBC one might be important to backport, and even if we don't it would be nice to have it called out in the changelogs.

2022-11-29 11:43 UTC, zakkak commented
> But in this case.. would you mind separating the two fixes? The oracle JDBC one might be important to backport, and even if we don't it would be nice to have it called out in the changelogs.

Done in https://github.com/quarkusio/quarkus/pull/29552

I also updated this PR to only include the Netty fix, but it depends on #29552 so I am marking it as draft.

2022-11-29 20:18 UTC, zakkak commented
As mentioned in https://github.com/quarkusio/quarkus/pull/29552#discussion_r1034969718

> This turns out to be more complex than I thought. The `\"` works fine on windows but not on linux.
> As a result, for a quick-fix I am switching to my previous approach that does not rely on the quotes at the cost of using more expressions than one and avoiding the use of .*.

2022-11-29 23:02 UTC, Sanne approved these changes

2022-11-30 11:34 UTC, merged

2023-02-22 17:39 UTC, gsmet commented
Adding for backport to 2.13 because of https://github.com/quarkusio/quarkus/issues/30508