Add further details about podman
quarkusio/quarkus pull request #29651
Opened 2022-12-02 19:14 UTC by janderssonse

This adds further details about the fix and the discussion in https://github.com/quarkusio/quarkus/pull/29562. It clearifies that alias is also fine instead of podman-docker, just redirects the user to podman for install instructions ( they change over time, and more linux variant are shown there, no need duplicate and maintain), and finally,
it shows a way of running podman as service without systemd (relevant on wsl up until recently for example, and users a most likely stuck with slightly older wsl's in a few places).

Signed-off-by: Josef Andersson <josef.andersson@gmail.com>

2022-12-02 19:16 UTC, janderssonse commented
@gsmet Added a bit more helpful info (I use it myself on a slightly older wsl with no option of updating to get systemd running atm, corporate versions and all that). also alias works fine as alternatve, as podman-docker wrapper package is not availble on all systems

2022-12-05 09:03 UTC, gsmet requested changes
Thanks. I added a few suggestions. Could you incorporate them and squash them in a single commit?

Thanks!

2022-12-05 09:03 UTC, gsmet commented on docs/src/main/asciidoc/podman.adoc
> +Podman can in most be cases be used as an drop-in-replacement for docker, either with the `podman-docker` package, or by an alias (alias docker=podman).
```suggestion
Podman can in most cases be used as an drop-in-replacement for Docker, either with the `podman-docker` package, or using an alias (`alias docker=podman`).
```

2022-12-05 09:03 UTC, gsmet commented on docs/src/main/asciidoc/podman.adoc
> +NOTE: In both cases, you need to start the REST API by enabling the Podman socket service through systemd, or at least by making sure podman is running as a service
```suggestion
NOTE: In both cases, you need to start the REST API by enabling the Podman socket service through systemd, or at least by making sure Podman is running as a service.
```

2022-12-05 10:49 UTC, gsmet approved these changes

2022-12-05 10:49 UTC, merged

2022-12-05 10:50 UTC, gsmet commented
Merged, thanks!