Add quarkus property to set the hibernate flushmode Fix #29604
quarkusio/quarkus pull request #29678
Opened 2022-12-05 11:05 UTC by zedbeit

My attempt to fix #29604 @gsmet pls review.

2022-12-10 14:12 UTC, zedbeit commented
@gastaldi can you pls review.

2022-12-10 18:09 UTC, Beita05 commented on extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfigPersistenceUnit.java
> +    public Optional<String> flushMode;
I don't think there is

2022-12-10 18:11 UTC, zedbeit commented on extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfigPersistenceUnit.java
> +    public Optional<String> flushMode;
I don't think there is

2022-12-10 18:12 UTC, gastaldi commented on extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfigPersistenceUnit.java
> +    public Optional<String> flushMode;
https://docs.jboss.org/hibernate/orm/6.1/javadocs/org/hibernate/FlushMode.html

2022-12-10 20:52 UTC, zedbeit commented on extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfigPersistenceUnit.java
> +    public Optional<String> flushMode;
Made some changes now

2023-01-04 18:08 UTC, zedbeit commented
@gsmet @gastaldi pls can you review

2023-01-12 15:40 UTC, yrodiere requested changes
Thanks for your submission.

Your PR includes completely unrelated changes (padding stuff). You will have to remove that.

Also, I'm not sure we even want to allow multiple flush modes, as that might requires changes in other places. @Sanne any opinion on that?

2023-01-12 18:17 UTC, Sanne commented
I'm indeed a bit skeptical about this, I had just commented on https://github.com/quarkusio/quarkus/issues/29604#issuecomment-1380714695 (before seeing this, sorry).

Let's keep the discussion on the issue? N.B. I'm skeptical but I am not saying "no way" ..

2023-01-15 22:40 UTC, zedbeit commented
@Sanne @yrodiere based on the discussion on #29604, if the decision is to continue with the change, I'd like to continue working on this.

2023-01-16 10:03 UTC, Sanne commented
@zedbeit thanks that's very kind but I expect we will not want to expose this. In fact there are discussions in the Hibernate ORM project to deprecate and/or possibly remove  this property altogether.

I might change my mind depending on if someone on #29604 comes forward with a reasonable explanation about why having this is important, but this seems unlikely to happen - so I would suggest to not spend any time on this for now.

Thanks anyways!

2023-01-16 11:14 UTC, closed without merging