Change avro.codegen.stringType default from String to CharSequence
quarkusio/quarkus pull request #29923
Opened 2022-12-16 13:15 UTC by vsevel

This is a proposition to change `avro.codegen.stringType`'s default from `String` to `CharSequence`.
There are 2 reasons for this:
- `CharSequence` is already the default value in the official avro maven plugin: https://github.com/apache/avro/blob/master/lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/AbstractAvroMojo.java#L112
- `String` has side effects on the generated classes that do not play nice with the registry

on the second point, when you use `String`, the main generated class contains metadata `{\"type\":\"string\",\"avro.java.string\":\"String\"}` for `String` types, even if the original schema does not contain it:
```
public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",...,\"fields\":[{\"name\":\"a\",\"type\":\"int\"},{\"name\":\"b\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"c\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
```

if you register the original schema in the schema registry, the client will try to match its own view of the schema (with the metadata) against the schema in the registry (without the metadata), and fail to find its schema in the registry.

this can be solved by registering the schema with the metadata in the schema registry, but then this makes the schema technology specific, and might cause other technologies to fail if they have a view of the schema without `java` metadata.

for that reason, it sounds that `CharSequence` is a much better default value, inline with the behavior of the other java technologies using the maven plugin, such as SpringBoot.

2022-12-16 13:55 UTC, gastaldi submitted a review, later dismissed
LGTM, but let's wait for @cescoffier to have the final say on this

2022-12-16 14:12 UTC, cescoffier commented
I would be careful. This is a breaking change. @ozangunalp @alesj wdyt?

2022-12-16 14:22 UTC, gastaldi commented
Right, tests are failing: 
```
org.opentest4j.AssertionFailedError: expected: java.lang.String@3146c61d<neo> but was: org.apache.avro.util.Utf8@6321e29b<neo>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1142)
	at io.quarkus.it.kafka.KafkaAvroTestBase.testAvroProducer(KafkaAvroTestBase.java:65)
	at io.quarkus.it.kafka.KafkaAvroTestBase.testApicurioAvroProducer(KafkaAvroTestBase.java:48)
```

2022-12-16 17:08 UTC, vsevel commented
> Potential breaking change

indeed. the test is easy to fix. but the breajing change is the real question to address. what default value do we want?
the breaking change could be documented in a minor version, or we could take the opportunity in the `3.x`.

to be honest, I would rather have java strings, instead of instances of `org.apache.avro.util.Utf8` (which implement the `CharSequence`). but I think the issue is more on the avro generation side: they should put the normalized schema _without_ the technology specific metadatas in `SCHEMA$`. 

yet, in a multi-technology environment, with a schema registry, we do not have a choice: we can't technology-specific metadata  in the schema. that is why I believe the `CharSequence` is a better default value, and why it was also used in the maven plugin.

I do agree it is debatable.

2022-12-16 18:52 UTC, ozangunalp commented
For the generated schema issue there is https://issues.apache.org/jira/browse/AVRO-2838 but it is mostly stale.

AFAIU `CharSequence` is just a backwards-compatible default, between String and Utf8. I believe String is the easiest to use of the three. Bu I also understand why you wouldn't want to add metadata to the source schema

2022-12-17 07:41 UTC, cescoffier commented
Does anyone know what would be generated for JavaScript or Python if we switch to CharSequence? Would it still be compatible? 

I think we cannot switch blindly, and we should at least have a flag.

2022-12-17 12:36 UTC, vsevel commented
I don't know about other languages. I will reach out.
alternatively, we can leave it as is, and improve the documentation with a note.

2022-12-19 10:43 UTC, ozangunalp commented
I don't expect that it would affect other languages. Even if we left String and the changed schema gets uploaded to the registry it has "java" related metadata "avro.java.string" added. I don't think Utf8 thing is relevant for other languages.

2023-01-02 14:06 UTC, cescoffier commented
So, what about adding a flag?

2023-01-02 16:36 UTC, cescoffier commented
Looking at the test results - it's a breaking change. So, we need a flag and more tests.

2023-01-02 16:37 UTC, cescoffier requested changes
This feature must be behind a flag, and more tests must be implemented (as currently, it breaks some tests).
Of course, documentation should explain how to use that feature.

2023-01-03 08:48 UTC, ozangunalp commented
Isn't this flag already present with `avro.codegen.stringType`? I think we can close this unless @vsevel has an update.

2023-01-03 09:15 UTC, vsevel commented
> Isn't this flag already present with avro.codegen.stringType?

yes exactly. I agree @ozangunalp

2023-01-03 09:15 UTC, closed without merging