Allow configuring instanceId and instanceIdGenerator
quarkusio/quarkus pull request #30025
Opened 2022-12-22 00:27 UTC by brunolmfg

When using Quartz extension in cluster mode and DB store, the name of active instances can be checked in the corresponding `scheduler_state` table. The default generator use the machine hostname and current timestamp in millis to closely ensure unique identifiers. But that generated ids can difficult pairing with the container id on the cluster orchestration tools.

Per [Quartz official documentation](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/ConfigMain.html#configure-main-scheduler-settings) the instance ID generator can be defined by setting:

**`org.quartz.scheduler.instanceId`**
Can be any string, but must be unique for all schedulers working as if they are the same _logical_ Scheduler within a cluster. You may use the value `AUTO` as the `instanceId` if you wish the Id to be generated for you. Or the value `SYS_PROP` if you want the value to come from the system property `org.quartz.scheduler.instanceId`.

**`org.quartz.scheduler.instanceIdGenerator.class`**
Only used if `org.quartz.scheduler.instanceId` is set to `AUTO`. Defaults to `org.quartz.simpl.SimpleInstanceIdGenerator`, which generates an instance id based upon hostname and timestamp. Other `InstanceIdGenerator` implementations include `SystemPropertyInstanceIdGenerator` (which gets the instance id from the system property `"org.quartz.scheduler.instanceId"`, and `HostnameInstanceIdGenerator` which uses the local hostname (`InetAddress.getLocalHost().getHostName()`). You can also implement the `InstanceIdGenerator` interface your self.

**`org.quartz.scheduler.instanceIdGenerator.<propName>`**
Not documented but allow setting any properties on the _instanceId_ generator.

Considering Quarkus/quartz does not expose these properties as configurable, would it be possible to expose the above configuration.

The proposed implementation will allow that `instanceId` generators can be configured instead of the default `SimpleInstanceIdGenerator` when `instanceId` is `AUTO`. The configuration `quarkus.quartz.instance-id` can specify the explicit identifier or some of the configured `instaceId` generators.

### Configuration examples

Use the expansion of `HOST` environment variable or its default `AUTO` if `HOST` is not set.

```properties
quarkus.quartz.instance-id=${HOST:AUTO}
```
Use the builtin `HostnameInstanceIdGenerator` that use the machine hostname as identifier.

```properties
quarkus.quartz.instance-id=hostname
quarkus.quartz.instance-id-generators.hostname.class=org.quartz.simpl.HostnameInstanceIdGenerator
```

Use the builtin `SystemPropertyInstanceIdGenerator` that use the system property `jvmNode` as identifier.

```properties
quarkus.quartz.instance-id=jvm-node-sysprop
quarkus.quartz.instance-id-generators.jvm-node-sysprop.class=org.quartz.simpl.SystemPropertyInstanceIdGenerator
quarkus.quartz.instance-id-generators.jvm-node-sysprop.systemPropertyName=jvmNode
```

### Considerations

The property `instance-id` was created as runtime configuration and the `instance-id-generators` group was created as build time configuration. This allows configuring multiple _instanceId_ generators being included as reflective class and the selection of proper generator in runtime.

2022-12-22 14:33 UTC, mkouba requested changes
You should add some tests for the `quarkus.quartz.instance-id` and `quarkus.quartz.instance-id-generators` config properties.

2022-12-22 23:00 UTC, brunolmfg commented
> You should add some tests for the `quarkus.quartz.instance-id` and `quarkus.quartz.instance-id-generators` config properties.

Added one test in `extensions/quartz` configuring a specific instance ID and another one in `integration-tests/quartz` setting a dummy instance ID generator that use a fixed value received via `quarkus.quartz.instance-generators.<generator-name>.properties.*`.

2022-12-23 09:46 UTC, mkouba approved these changes
Looks good but I'd like to know what @machi1990 thinks too ;-)

2023-01-01 14:52 UTC, machi1990 approved these changes

2023-01-01 14:54 UTC, machi1990 commented
Thanks for the contribution @brunolmfg

2023-01-02 07:58 UTC, mkouba commented
@brunolmfg could you squash the commits pls?

2023-01-02 16:32 UTC, brunolmfg commented
@mkouba commits squashed and branch updated.

2023-01-03 07:13 UTC, merged