smallrye-reactive-messaging: Support connector config through envvars
quarkusio/quarkus pull request #30107
Opened 2022-12-30 17:06 UTC by mederel

Fixes #30106

This fix is based on the behaviour of smallrye-config with configuration comming from envvars.
All environment variables are transformed back into actuall config property names with lowercase and underscore to dot.
They are thus redefined in the config structure and returned in getPropertyNames() calls on the SmallryeConfig object.
There is a condition on the redefinition: there must not be another config source that already defines an property with the same lowercased and dotted name.
In this fix we add a new ConfigSource that looks up the SmallryeReactiveMessagingContext.
It looks at the environment variables defined and generates corresponding property names if they look like reactive messaging configuration.
A test doing an override with environment variable is added.

2023-01-02 14:17 UTC, cescoffier requested changes

2023-01-02 14:17 UTC, cescoffier commented on extensions/smallrye-reactive-messaging/deployment/src/test/java/io/quarkus/smallrye/reactivemessaging/config/ConnectorConfigSupportsEnvVarOverridesTest.java
> +@SetEnvironmentVariable(key = "MP_MESSAGING_INCOMING_WAY_IN_TRACING_ENABLED", value = "false")
Wasn't that an issue on Java 14+ because it uses an internal API and needs to be opened explicitly?

2023-01-02 14:17 UTC, cescoffier commented on extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/EnvironmentVariableRedefiningConfigSource.java
> +        return text.toLowerCase().replaceAll("_", ".");
We need to check this. We have connectors using `-`, some using `_`, and some using `.`.

2023-01-02 14:17 UTC, cescoffier commented on extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/EnvironmentVariableRedefiningConfigSource.java
> +        return null;
I don't believe that's compliant.

2023-01-02 14:17 UTC, cescoffier commented on extensions/smallrye-reactive-messaging/deployment/src/test/java/io/quarkus/smallrye/reactivemessaging/config/ConnectorConfigSupportsEnvVarOverridesTest.java
> +            .overrideConfigKey("mp.messaging.incoming.way-in.connector", "dummy");
Add tests with way_in and way.in

2023-01-02 14:18 UTC, cescoffier commented
Asking @radcortez (because of the config source impl) and @ozangunalp to have a look.

2023-01-05 11:49 UTC, radcortez requested changes
Just so you know, this shouldn't be required. The way we deal with such cases is to define the dashed property version in `application.properties` (or any other lower ordinal source) as empty (or with the desired default). 

This will give enough information to SmallRye Config to correctly map the environment variable name to the property name. Since the environment variable source is on a higher ordinal, it will override it.

Also check this: https://smallrye.io/smallrye-config/2.13.1/config/environment-variables/

2023-01-06 10:30 UTC, mederel commented
> Just so you know, this shouldn't be required. The way we deal with such cases is to define the dashed property version in `application.properties` (or any other lower ordinal source) as empty (or with the desired default).
> 
> This will give enough information to SmallRye Config to correctly map the environment variable name to the property name. Since the environment variable source is on a higher ordinal, it will override it.
> 
> Also check this: https://smallrye.io/smallrye-config/2.13.1/config/environment-variables/

Hi all, thanks for your quick inputs. Before I move on trying to fix the comments, I would need some clarifications regarding @radcortez input just above. Am I to understand that this fix will never be merged, because there is already another solution?

2023-01-06 12:32 UTC, ozangunalp commented
I prefer @radcortez 's solution in Smallrye Config to the custom solution brought by this PR.

2023-01-09 21:11 UTC, radcortez commented
> Hi all, thanks for your quick inputs. Before I move on trying to fix the comments, I would need some clarifications regarding @radcortez input just above. Am I to understand that this fix will never be merged, because there is already another solution?
> 
> (NB no animosity meant in my question, just being practical 😄 )

No worries. No animosity was taken. I hope the same from your side :)

If we adopt this style, each extension will have to custom handle the environment variables. I recommend using the current SmallRye Config proposal, which fits every case out of the box (with the small price to add the empty variable).

Anyway, the final word is from @cescoffier and @ozangunalp, since they maintain this extension.

2023-01-10 07:23 UTC, cescoffier commented
I would go with the smallrye config fix as it is very likely that other extension will need such kind of things. Typically, we will need the same trick for RabbitMQ.

2023-01-10 12:43 UTC, ozangunalp commented
I also think like @radcortez. The current way in Smallrye Config to match environment variables with config items should be enough to not have this issue in the first place.

2023-01-30 09:39 UTC, gsmet commented
@radcortez what's the status of this work? My understanding is that it should be closed but I might be mistaken.

2023-01-30 13:30 UTC, mederel commented
Hi yes, we close.

following a comment in the issue, started on working on another fix, related to QuarkusIntegrationTest and the way it passes configuration overrides to the docker container. I am lacking time to finalize a PR.

To conclude: closing in awaiting a better fix of the original pb.

2023-01-30 13:30 UTC, closed without merging