Support quoted and indexed properties during container launch
quarkusio/quarkus pull request #30247
Opened 2023-01-08 06:33 UTC by ranjanashish

Before launching a container, Quarkus converts property names to environment variables. These environment variables are then injected during the container launch.

Currently, Quarkus does not correctly convert quoted and indexed properties to their corresponding environment variables based on SmallRye Config's [environment variable names conversion rules](https://smallrye.io/smallrye-config/3.1.1/config/environment-variables/).

2023-01-09 10:25 UTC, geoand commented
@radcortez thinks looks good to me, but I would like to get your approval as well.

2023-01-09 21:04 UTC, radcortez requested changes
My recommendation is to use `io.smallrye.config.common.utils.StringUtil#replaceNonAlphanumericByUnderscores` and `toUpperCase`. This will keep consistency with the SmallRye Config implementation and also handle quoted keys (not handled by the proposed PR).

2023-01-09 23:10 UTC, ranjanashish commented
Thank you for the feedback @radcortez. I will update the PR with your recommendation.

2023-01-10 07:48 UTC, ranjanashish commented
I have updated the PR with recommended changes.

2023-01-10 13:20 UTC, radcortez approved these changes

2023-01-10 13:21 UTC, radcortez commented
Great! Thank you!

2023-01-10 13:21 UTC, merged