Document how to set an extension image
quarkusio/quarkus pull request #30459
Opened 2023-01-18 22:29 UTC by holly-cummins

Now that https://github.com/quarkusio/extensions.quarkus.io/issues/23 is implemented, we should document it. @maxandersen and @gastaldi , what do you think of the key I've chosen in the yaml? I can change it (and the implementation) if we want something else. 

The image display logic is 

- No release since we started adding metadata: we show a faded quarkiverse logo (because we don't have the richer information)
- No image information: we show the logo of the github org, usually quarkiverse or quarkus
- Github social media preview set: we crop and use that 
- Image override in `extension.yaml`: we use that 

I didn't want to burden the docs with all that information, but can if we think it adds something.

2023-01-18 22:39 UTC, gastaldi approved these changes
LGTM

2023-01-19 04:59 UTC, maxandersen commented
The priority is reversed if that list I assume? Ie. If metadata is set that is used over the feedback above? 

"Logo" I would refrain from using as not every image/icon used will be an actual logo. 

I would suggest "icon" or "image" ?

2023-01-19 05:00 UTC, maxandersen requested changes
.

2023-01-19 05:00 UTC, maxandersen requested changes
.

2023-01-19 05:04 UTC, maxandersen commented
Also, it's expected to be an external url not a reference inside the extension itself, correct?

2023-01-19 05:54 UTC, gastaldi commented
Ah good catch, probably should be `icon-url` for clarity

2023-01-19 08:54 UTC, holly-cummins commented
> Ah good catch, probably should be `icon-url` for clarity

I didn't do `icon-url` since the guide was a url, and didn't have 'url' tacked on the end. However, I guess there's more ambiguity with the logo, since someone could shove an image into their source control system and assume it would be used. I'll change it to `icon-url`.

2023-01-19 08:55 UTC, holly-cummins commented
And yes, @maxandersen, the logic list was in ascending order of importance, so reverse priority. No, I don't know why I thought that was a helpful order to write it in. :)

2023-01-19 11:51 UTC, gsmet commented
Oh, looking forward to add the nice icon created by @insectengine for Quarkus GitHub App :).

2023-01-23 10:02 UTC, maxandersen commented on docs/src/main/asciidoc/extension-metadata.adoc
> +<8> Link to an externally hosted image. This is used in the Quarkus dev tools as the extension icon. Alternatively, if you https://docs.github.com/en/repositories/managing-your-repositorys-settings-a
should we specify what kind of image? does it assume/recommend/require svg ? or is png etc okey?

2023-01-23 10:04 UTC, maxandersen requested changes
overall good but I would suggest we give bit of more requirements for the image.

especially type and if png/jpeg allowed then some size recommendations.

2023-01-23 10:47 UTC, holly-cummins commented
We don't really have any size requirements, since the framework resizes and crops for us, but I'll make that clear. Cropping also behaves differently for GitHub social media previews and images specified in the yaml, so I'll explain that. This is probably too much to squish into a one-liner annotation, so I'll add a section.

2023-01-23 10:51 UTC, gsmet commented
@holly-cummins is SVG allowed?

Also, while it does some cropping, how does it handle high DPI (i.e. how to not end up with a blurred image on macOS)?

2023-01-23 12:57 UTC, holly-cummins commented
I had to test SVG support, since I’m relying on the framework for image processing. By default, SVG doesn’t work, so I’ve added some [extra implementation](https://github.com/quarkusio/extensions.quarkus.io/pull/68) to support it. This only covers the case where the image is set in the extension yaml. If we’re getting the image from GitHub, they have their own rules, which exclude SVG. 

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/11509290/214044233-a89a6e6b-e0b0-45c5-b8a5-a9b60181483d.png">


@gsmet, do you have a link explaining the high DPI issue? I'm included to assume the sharp plugin does the right thing, but I couldn't search properly without understanding the issue better.

2023-01-23 13:15 UTC, holly-cummins commented
@gsmet @maxandersen do you have thoughts on adding a new section vs making the bullet point description of the field a whole paragraph? I feel like if I add more detail I'm getting to where it needs its own section, but looking at https://quarkus.io/guides/extension-metadata, the structure doesn't really have a place to put extra information.  So I could just add more specifics to the bullet point. There's not much people can do wrong, especially now that svg is supported too, but I can see they might like some reassurance that they can't get it wrong. :)

2023-01-25 09:51 UTC, gsmet approved these changes
I think we can merge it now but I'll let @maxandersen approve.

2023-01-30 09:14 UTC, merged

2023-01-30 09:14 UTC, gsmet commented
Let's get this in. Thanks.