Bump kubernetes-client-bom from 6.3 to 6.4
quarkusio/quarkus pull request #30480
Opened 2023-01-19 14:08 UTC by manusa

Kubernetes Client ~6.4.0~ 6.4.1 was just released: https://github.com/fabric8io/kubernetes-client/releases/tag/v6.4.1

This release of the client includes the new Vert.x `HttpClient` implementation. This PR includes changes in the `pom.xml` files to make use of this client instead of the default `OkHttp` implementation. If everything goes well, this should fix #29520

- Added an enforcer rule to ensure ~~OkHttp~~ that the `kubernetes-httpclient-okhttp` module is not mistakenly propagated, however, I'm not sure this is the right place. I can't directly block OkHttp since it is also used (server-side) in the MockServer.
- Modified the kubernetes-extension (creates kubernetes et al manifests and deploys them) to create and close KubernetesClient instances and avoid the leakages mentioned in some of the PR comments
- Modified the kubernetes-client-extension to implement an HttpClient.Factory that reuses the global Vert.x instance (uses CDI to retrieve it, maybe doesn't work, waiting for tests)

/cc @metacosm @maxandersen @shawkins @gastaldi @geoand

2023-01-19 14:12 UTC, gastaldi approved these changes
That's awesome! You can also add the exclusion to the `bom/application` pom.xml

2023-01-19 14:13 UTC, gastaldi commented
> That's awesome! You can also add the exclusion to the `bom/application` pom.xml

Ah but we only import the kubernetes-bom there, nevermind

2023-01-19 14:16 UTC, gsmet approved these changes
Awesome!

As a followup, I will try to remove okhttp from the BOM as it shouldn't be a dependency anymore.

2023-01-19 14:17 UTC, gastaldi submitted a review, later dismissed
I think it's safe to remove OkHttp from the list of managed dependencies too:
 https://github.com/quarkusio/quarkus/blob/main/bom/application/pom.xml#L171-L172

and 

https://github.com/quarkusio/quarkus/blob/main/bom/application/pom.xml#L4169-L4183

2023-01-19 14:21 UTC, gsmet commented
Yeah I think it's better to do it in a separate PR in case it breaks something and we have to revert it.

2023-01-19 15:29 UTC, geoand approved these changes
Very glad to see this!

2023-01-19 15:40 UTC, gsmet commented
An example of the enforcer failures:
```
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce) @ quarkus-kubernetes-client-internal ---
[18537](https://github.com/quarkusio/quarkus/actions/runs/3959243390/jobs/6781818473#step:10:18538)
Warning:  Rule 3: org.apache.maven.plugins.enforcer.ExternalRules failed with message:
[18538](https://github.com/quarkusio/quarkus/actions/runs/3959243390/jobs/6781818473#step:10:18539)
Found Banned Dependency: com.squareup.okhttp3:okhttp:jar:3.14.9
[18539](https://github.com/quarkusio/quarkus/actions/runs/3959243390/jobs/6781818473#step:10:18540)
Use 'mvn dependency:tree' to locate the source of the banned dependencies.
```

2023-01-20 15:26 UTC, manusa commented
It seems that we might need to bump Dekorate along with the client.

https://github.com/dekorateio/dekorate/pull/1131

2023-01-23 06:15 UTC, geoand commented
Including @Sgitario for awareness

2023-01-23 09:26 UTC, Sgitario commented
> Including @Sgitario for awareness

PR to bump dekorate: https://github.com/quarkusio/quarkus/pull/30533

2023-01-25 06:08 UTC, manusa commented
Log excerpt for failure:
```
2023-01-24T21:56:54.9279414Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.406 s <<< FAILURE! - in io.quarkus.it.kubernetes.BasicOpenshiftTest
2023-01-24T21:56:54.9292273Z [ERROR] io.quarkus.it.kubernetes.BasicOpenshiftTest  Time elapsed: 5.406 s  <<< ERROR!
2023-01-24T21:56:54.9292894Z java.lang.RuntimeException: 
2023-01-24T21:56:54.9293556Z java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
2023-01-24T21:56:54.9294898Z 	[error]: Build step io.quarkus.kubernetes.client.deployment.KubernetesClientBuildStep#process threw an exception: java.util.ServiceConfigurationError: io.fabric8.kubernetes.client.http.HttpClient$Factory: Provider io.fabric8.kubernetes.client.okhttp.OkHttpClientFactory not found
2023-01-24T21:56:54.9295775Z 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
2023-01-24T21:56:54.9296281Z 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1212)
2023-01-24T21:56:54.9296846Z 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
2023-01-24T21:56:54.9297378Z 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
2023-01-24T21:56:54.9298039Z 	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
2023-01-24T21:56:54.9298438Z 	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
2023-01-24T21:56:54.9299010Z 	at io.fabric8.kubernetes.client.utils.HttpClientUtils.getFactory(HttpClientUtils.java:163)
2023-01-24T21:56:54.9299602Z 	at io.fabric8.kubernetes.client.utils.HttpClientUtils.getHttpClientFactory(HttpClientUtils.java:149)
2023-01-24T21:56:54.9300449Z 	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:144)
2023-01-24T21:56:54.9301019Z 	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:56)
2023-01-24T21:56:54.9301747Z 	at io.quarkus.kubernetes.client.runtime.KubernetesClientUtils.createClient(KubernetesClientUtils.java:52)
2023-01-24T21:56:54.9302417Z 	at io.quarkus.kubernetes.client.deployment.KubernetesClientBuildStep.process(KubernetesClientBuildStep.java:16)
```

For some reason the SPI `META-INF/services` file including the `io.fabric8.kubernetes.client.okhttp.OkHttpClientFactory` seems to still be processed.

2023-01-25 06:10 UTC, geoand commented
I will have a look

2023-01-25 07:18 UTC, geoand commented
@Sgitario @iocanel the problem stems from the fact that io/dekorate/servicebinding-annotations/3.3.0/servicebinding-annotations-3.3.0-noapt.jar contains a `META-INF/services/io.fabric8.kubernetes.client.http.HttpClient$Factory` file (that uses `io.fabric8.kubernetes.client.okhttp.OkHttpClientFactory`)

2023-01-25 08:30 UTC, manusa commented
> @Sgitario @iocanel the problem stems from the fact that `io/dekorate/servicebinding-annotations/3.3.0/servicebinding-annotations-3.3.0-noapt.jar` contains a `META-INF/services/io.fabric8.kubernetes.client.http.HttpClient$Factory` file (that uses `io.fabric8.kubernetes.client.okhttp.OkHttpClientFactory`)

:+1: I'm not sure how were you able to trace that, I was getting crazy trying to discover the culprit jar.

I provided yet another commit switching to use an explicit factory instead of relying on SPI to provide it. This might do the job, WDYT?

2023-01-25 08:37 UTC, Sgitario commented
> > @Sgitario @iocanel the problem stems from the fact that `io/dekorate/servicebinding-annotations/3.3.0/servicebinding-annotations-3.3.0-noapt.jar` contains a `META-INF/services/io.fabric8.kubernetes.client.http.HttpClient$Factory` file (that uses `io.fabric8.kubernetes.client.okhttp.OkHttpClientFactory`)
> 
> +1 I'm not sure how were you able to trace that, I was getting crazy trying to discover the culprit jar.
> 
> I provided yet another commit switching to use an explicit factory instead of relying on SPI to provide it. This might do the job, WDYT?

I guess the problematic line in Dekorate is [this](https://github.com/dekorateio/dekorate/blob/ee7fa59beda60a6f6fb01c8d56be16b1dee0278b/annotations/servicebinding-annotations/pom.xml#L207). This was done as part of these changes: https://github.com/dekorateio/dekorate/pull/790
Though, I don't fully follow why is required and also I don't see it in all the annotations. Maybe @iocanel can provide some light on this.

2023-01-25 08:52 UTC, geoand commented
> I'm not sure how were you able to trace that, I was getting crazy trying to discover the culprit jar.

I basiically did `TCCL.getResources("META-INF/services/....")` (or `findResources`, I don't remember) and went through the `Enumeration` looking at each URL

2023-01-25 08:54 UTC, iocanel commented
> I guess the problematic line in Dekorate is [this](https://github.com/dekorateio/dekorate/blob/ee7fa59beda60a6f6fb01c8d56be16b1dee0278b/annotations/servicebinding-annotations/pom.xml#L207). This was done as part of these changes: [dekorateio/dekorate#790](https://github.com/dekorateio/dekorate/pull/790)
> Though, I don't fully follow why is required and also I don't see it in all the annotations. Maybe @iocanel can provide some light on this.

The fabric8 client does not provide support for service binding, so the code needed for serializing / deserializing etc is baked directly into dekorate. This also means that it has fallen out of sync with the client (and unfortunately more than once). Let's apply everything needed in dekorate and then create a proper service binding extension for the client.

2023-01-25 08:54 UTC, geoand commented
> I provided yet another commit switching to use an explicit factory instead of relying on SPI to provide it. This might do the job, WDYT?

That would break users who tried to exclude the Vert.x client and wanted to rely on OkHTTP though, wouldn't it?

2023-01-25 08:56 UTC, iocanel commented
There is still something that I don't get. In dekorate we only define a servcie for `KubenretesResource` that is not related in any way with http client factories and what not.

2023-01-25 08:57 UTC, manusa commented
> > I provided yet another commit switching to use an explicit factory instead of relying on SPI to provide it. This might do the job, WDYT?
> 
> That would break users who tried to exclude the Vert.x client and wanted to rely on OkHTTP though, wouldn't it?

I'm not sure if these methods to create the client are used outside of the build process. But yes, that would prevent users from providing alternative HttpClient implementations.

Shall I remove this commit and wait for a solution in Dekorate then?

2023-01-25 08:58 UTC, geoand commented
> Shall I remove this commit and wait for a solution in Dekorate then?

If @iocanel and @Sgitario think we can get a solution quickly, then yes, I would prefer that

2023-01-25 08:58 UTC, iocanel commented
Ohhhh now I get it. The shade plugin drags in more things than it needs. That's should be simple to fix.

2023-01-25 09:02 UTC, Sgitario commented
> > Shall I remove this commit and wait for a solution in Dekorate then?
> 
> If @iocanel and @Sgitario think we can get a solution quickly, then yes, I would prefer that

Fix https://github.com/dekorateio/dekorate/pull/1137

2023-01-26 08:49 UTC, Sgitario commented
Pull request with new Dekorate: https://github.com/quarkusio/quarkus/pull/30627

2023-01-28 05:56 UTC, manusa commented
```
[INFO] Running io.quarkus.it.kubernetes.KubernetesWithFlywayInitTest
[ERROR] Java heap space
```
Looking into this

2023-01-30 09:51 UTC, geoand commented
There is definitely some memory leak... The question is whether it was introduced by this PR or just exarbated for some reason

2023-01-30 09:58 UTC, manusa commented
I'm having a hard time figuring out what's causing the leak.

The heap dump reveals that the QuarkusClassLoader is getting huge:
```
48 instances of io.quarkus.bootstrap.classloading.QuarkusClassLoader, loaded by jdk.internal.loader.ClassLoaders$AppClassLoader @ 0xffe57508 occupy 1,127,281,408 (78.32%) bytes.
```

I delved around the `QuarkusProdModeTest` and the `QuarkusBootstrap`, but those seemed to take care of cleaning up after each test execution.

It would be good if someone smarter and more knowledgeable could also take a look into this.

2023-01-30 10:30 UTC, geoand commented
I don't have much time to look into it today, but a quick and dirty check shows that the current `main` does not suffer from a ClassLoader leak:

![main](https://user-images.githubusercontent.com/4374975/215452493-f3032a46-51b5-40b3-939a-489fae795766.png)

When trying to run the same test however with this PR, things get busted **really** quick.

2023-01-30 10:32 UTC, geoand commented
A really quick look points indicated that there might be an issue with Vert'x blocked thead checked, but I'll need to investigate more.

2023-01-30 12:50 UTC, geoand requested changes
@manusa I am starting to look into the Vert.x integration of the k8s client, but I immediately have a few observations:

It doesn't look like the Vertx object created by Quarkus is being used. This will be a problem for us - we really need to have a single Vertx object to have the best possible runtime footprint (among other things).

So we will either need:

* Our own Quarkus specific `VertxHttpClientFactory`
* Or a way to configure the client's `VertxHttpClientFactory` (perhaps another SPI)

2023-01-30 13:06 UTC, geoand commented
There is a chance the memory leak has to do with the `BlockedThreadChecker`. 
@cescoffier I don't see a way to turn that off completely, or am I missing something?

2023-01-30 13:12 UTC, cescoffier commented
you can't disable the thread checker altogether. You can increase the threshold. 

However, in that case, I may suggest making sure that the Vert.x HTTP clients are correctly closed after each usage. Also, I'm a bit surprised not to see it using the managed vert.x instance. Without that, it would:

- require to have that vert.x instance closes every time - that's probably the leak
- have a completely different configuration for that vert.x instance (disable async DNS at least)

2023-01-30 13:13 UTC, geoand commented
The problem seems to be that because the Fabric8 K8s client does **not** use our Vertx, the object is not getting closed, which means it ends up leaking a ton of stuff

2023-01-30 13:14 UTC, geoand commented
So as I mentioned before (and as Clement also implies), we really need to have the client use our Vert.x instance.

2023-01-30 13:17 UTC, geoand commented
> So as I mentioned before (and as Clement also implies), we really need to have the client use **our** Vert.x instance - anything else will be very problematic.

@manusa this is an action item for you :). Let me know if I can help

2023-01-30 13:20 UTC, metacosm commented
Well, technically, 6.4.0 update could be merged without the switch to the Vert.x client… but it would indeed be better with it 😉

2023-01-30 13:22 UTC, geoand commented
I'll leave that up to you guys, but my personal _feeling_ is that it would be better for both projects if the version bump included the working Vert.x integration.

2023-01-30 13:25 UTC, manusa commented
> > So as I mentioned before (and as Clement also implies), we really need to have the client use **our** Vert.x instance - anything else will be very problematic.
> 
> @manusa this is an action item for you :). Let me know if I can help

Thx for the analysis. I'm glad I could create a leak big enough to prove the `QuarkusProdTest` useful :sweat_smile: 

I'll give it a try and see if I can create a Quarkus-specific `HttpClient` factory to reuse the Vert.x object. I'll probably ping you with a few questions once I get my hands dirty.

2023-01-30 13:31 UTC, geoand commented
> I'll give it a try and see if I can create a Quarkus-specific HttpClient factory to reuse the Vert.x object. I'll probably ping you with a few questions once I get my hands dirty.

👍🏼

2023-01-30 13:33 UTC, geoand commented
Before I forget: We will probably also need a way to configure the `HttpClientOptions` being used 😉

2023-01-31 14:44 UTC, geoand commented
If this passes CI, I want to also have a closer look under debug

2023-01-31 15:14 UTC, geoand commented
I tested this and it works very nicely.

Great job!

2023-01-31 15:29 UTC, geoand commented
The one ask I have is to rebase on `main` as this is a little behind now

2023-01-31 16:30 UTC, manusa commented
> The one ask I have is to rebase on `main` as this is a little behind now

Yes, I also need to merge your changes to the Knative deployer.


Waiting to the CInin case there is anything else that needs to be addressed

2023-01-31 18:14 UTC, manusa commented
Native failure:
```
2023-01-31T17:20:51.7230714Z Caused by: java.lang.IllegalStateException: Unable to locate CDIProvider
2023-01-31T17:20:51.7239722Z 	at javax.enterprise.inject.spi.CDI.findAllProviders(CDI.java:121)
2023-01-31T17:20:51.7240540Z 	at javax.enterprise.inject.spi.CDI.getCDIProvider(CDI.java:82)
2023-01-31T17:20:51.7244500Z 	at javax.enterprise.inject.spi.CDI.current(CDI.java:64)
2023-01-31T17:20:51.7245274Z 	at io.quarkus.kubernetes.client.runtime.QuarkusHttpClientFactory.newBuilder(QuarkusHttpClientFactory.java:18)
2023-01-31T17:20:51.7246208Z 	at io.quarkus.kubernetes.client.runtime.QuarkusHttpClientFactory.newBuilder(QuarkusHttpClientFactory.java:10)
2023-01-31T17:20:51.7250102Z 	at io.fabric8.kubernetes.client.http.HttpClient$Factory.newBuilder(HttpClient.java:44)
2023-01-31T17:20:51.7251116Z 	at io.quarkus.kubernetes.client.runtime.QuarkusHttpClientFactory.newBuilder(QuarkusHttpClientFactory.java:13)
2023-01-31T17:20:51.7260232Z 	at io.fabric8.kubernetes.client.KubernetesClientBuilder.getHttpClient(KubernetesClientBuilder.java:88)
2023-01-31T17:20:51.7271532Z 	at io.fabric8.kubernetes.client.KubernetesClientBuilder.build(KubernetesClientBuilder.java:78)
2023-01-31T17:20:51.7272392Z 	at io.fabric8.kubernetes.client.server.mock.KubernetesMockServer.createClient(KubernetesMockServer.java:128)
2023-01-31T17:20:51.7281657Z 	at io.fabric8.kubernetes.client.server.mock.KubernetesMockServer.createClient(KubernetesMockServer.java:123)
2023-01-31T17:20:51.7285441Z 	at io.quarkus.test.kubernetes.client.KubernetesMockServerTestResource.getClient(KubernetesMockServerTestResource.java:17)
2023-01-31T17:20:51.7295700Z 	at io.quarkus.test.kubernetes.client.KubernetesMockServerTestResource.getClient(KubernetesMockServerTestResource.java:11)
2023-01-31T17:20:51.7300075Z 	at io.quarkus.test.kubernetes.client.AbstractKubernetesTestResource.start(AbstractKubernetesTestResource.java:28)
2023-01-31T17:20:51.7300879Z 	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:481)
2023-01-31T17:20:51.7301376Z 	... 4 more
``` 

Related to the following snippet:
```java
    @Override
    public VertxHttpClientBuilder<QuarkusHttpClientFactory> newBuilder() {
        return new VertxHttpClientBuilder<>(this, CDI.current().select(Vertx.class).get());
    }
```

Maybe doing the wrong thing here. Any suggestions? try-catch and use `Vertx.vertx()` in case of exception?

2023-01-31 18:34 UTC, geoand commented
This happens because the mock server is launched before Quarkus.

We'll need to fallback to creating Vertx if CDI is not available

2023-01-31 19:11 UTC, manusa commented
Ouch, didn't think about that one. Fixing.

2023-02-01 09:54 UTC, gsmet commented
Don't worry about the Gradle tests failing, it's unrelated to your patch.

2023-02-01 09:57 UTC, manusa commented
> Don't worry about the Gradle tests failing, it's unrelated to your patch.

Thx. Yes, I discussed internally with Georgios. I've rebased after the merge of #30758.

Hoping this time we get a completely green report :crossed_fingers: .

2023-02-01 19:58 UTC, geoand approved these changes

2023-02-01 19:59 UTC, merged