Added hibernate-orm property: quarkus.hibernate-orm.validation.mode t…
quarkusio/quarkus pull request #30617
Opened 2023-01-25 18:40 UTC by mfpc

…hat controls how the hibernate validator behaves

Co-Authored-By: George Gastaldi <gegastaldi@gmail.com>

2023-01-25 19:14 UTC, gastaldi commented on extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm/validation/JPAValidationDisabledTestCase.java
> +    EntityManager em;
You can remove this

2023-01-25 19:14 UTC, gastaldi commented on extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfigPersistenceUnit.java
> +         * This flag enable/disable hibernate validation.
```suggestion
         * Enables the Bean Validation integration
```

2023-01-25 19:32 UTC, mfpc commented on extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm/validation/JPAValidationDisabledTestCase.java
> +    EntityManager em;
removed

2023-01-25 19:32 UTC, mfpc commented on extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfigPersistenceUnit.java
> +         * This flag enable/disable hibernate validation.
done

2023-01-26 09:53 UTC, yrodiere requested changes

2023-01-26 09:53 UTC, yrodiere commented on extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm/validation/JPAValidationDisabledTestCase.java
> +        String entityName = MyEntity.ENTITY_NAME_TOO_LONG;
This constant is not a value that's too long to fit the entity name, but the message displayed when an entity name is too long.

To actually test that validation is disabled, see how the validation failure is triggered other tests:

```suggestion
        String entityName = "Post method should not persist an entity having a Size constraint of 50 on the name column.";
```

2023-01-26 11:07 UTC, gsmet approved these changes
I made a few minor changes and amended your commit. This should be good to go now.

2023-01-26 11:11 UTC, yrodiere approved these changes

2023-01-26 11:11 UTC, yrodiere commented
Looks good, let's merge once CI passes.

Thanks!

2023-01-26 12:44 UTC, merged