Dev UI 2
quarkusio/quarkus pull request #30734
Opened 2023-01-31 03:03 UTC by phillip-kruger

This is the initial PR for the new Dev UI.

There is still a lot of outstanding work, thus for now the old dev ui is still available. Once all extensions and features is ported the old code can be deleted. 

We can either merge this as is, and do follow up PRs that migrate the extensions, or add commits to this PR. I'll leave that up to the reviewers to decide.

You can see the new way of taking part in the dev ui by including this dummy extension:

https://github.com/phillip-kruger/quarkus-jokes

```
<dependency>
        <groupId>io.quarkiverse.jokes</groupId>
        <artifactId>quarkus-jokes</artifactId>
        <version>1.0.0-SNAPSHOT</version>
</dependency
```
(it might be useful to publish the above somewhere)

Any example application that includes above, for instance: https://github.com/phillip-kruger/devui-example will show the jokes extension:

![devui-jokes](https://user-images.githubusercontent.com/6836179/215635257-0c826785-1a5d-43c3-bce3-b641aa60b62f.gif)

**Core Extensions to be migrated:**

- [ ] arc (in progress - Phillip)
- [ ] cache
- [ ] container-image
- [ ] datasource
- [ ] flyway
- [ ] grpc
- [ ] hibernate-orm
- [ ] hibernate-search-orm-elasticsearch
- [ ] infinispan-client
- [ ] kafka-client
- [ ] kafka-streams
- [ ] kubernetes/openshift
- [ ] kubernetes/vanilla
- [ ] liquibase
- [ ] micrometer
- [ ] oidc
- [ ] qute
- [ ] resteasy-reactive/quarkus-resteasy-reactive
- [ ] resteasy-reactive/rest-client-reactive
- [ ] scheduler
- [ ] smallrye-fault-tolerance
- [ ] smallrye-graphql
- [ ] smallrye-health
- [ ] smallrye-metrics
- [ ] smallrye-openapi
- [ ] smallrye-reactive-messaging-rabbitmq
- [ ] smallrye-reactive-messaging
- [ ] ... more ?

**Quarkiverse extensions to be migrated:**

- [ ] quarkus-operator-sdk
- [ ] quarkus-neo4j
- [ ] quarkus-jpastreamer
- [ ] quarkus-jef
- [ ] quarkus-cxf
- [ ] quarkus-minio
- [ ] quarkus-dashbuilder
- [ ] quarkus-ngrok
- [ ] quarkus-logging-manager
- [ ] ... more ?

**Other things to do:**

- [ ] Documentation
- [ ] Add tests (using [playwright](https://playwright.dev/))
- [ ] Make the Menu section and bottom drawer more accessible for extensions.
- [ ] Add history to server log
- [ ] Investigate if dev-ui can be moved to it's own extension (out of vertx-http)
- [ ] Remove old dev ui.
- [ ] Add centralsync for mvnpm.org

Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>

2023-01-31 12:14 UTC, maxandersen commented
cool @phillip-kruger - would be good to know a few things:

1) did you manage to get to a point where extensions using old dev UI can show up in the new or somehow be linked to "old" page? whats the approach you suggest?
2) can an extension use devui without adding anything bug a qute template and/or the glue devui class? (i.e. no js/webjar required for basic extensions) ?

2023-01-31 12:16 UTC, phillip-kruger commented
1) Not yet no. 
2) Yes you can just use Java or Qute for basic pages

2023-01-31 12:27 UTC, gsmet commented
> 1. Not yet no.

If it's too complex, maybe we should focus on porting things to the new Dev UI.

2023-01-31 12:30 UTC, phillip-kruger commented
> > 1. Not yet no.
> 
> If it's too complex, maybe we should focus on porting things to the new Dev UI.

Yea, I am not sure how complex it would be, I have not yet had time to look into it.

2023-02-01 07:19 UTC, maxandersen commented
https://github.com/phillip-kruger/quarkus-jokes is giving me 404 - moved?

2023-02-01 07:41 UTC, maxandersen commented
> https://github.com/phillip-kruger/quarkus-jokes is giving me 404 - moved?

was private. now available.

new dev-ui is at `/q/dev-ui`.

currently does not work on safari,firefox nor edge (blocker issue) - only seem to load on chrome.

2023-02-01 07:48 UTC, maxandersen commented
going to `/q/dev-ui-configuration` just sits stuck on `Loading Configuration'

2023-02-01 07:49 UTC, phillip-kruger commented
> going to `/q/dev-ui/*` just sits stuck on `Loading Configuration|continous testing|dev services|build steps'

Yes, configuration is not implemented yet (see checklist in PR)

2023-02-01 07:52 UTC, maxandersen commented
looking at the jokes repo the feature of "external HTML" is cool; but I would not like us to have that available in devui as is as you can literally fake other parts of the devui making it a security issue.

2023-02-01 07:54 UTC, phillip-kruger commented
> looking at the jokes repo the feature of "external HTML" is cool; but I would not like us to have that available in devui as is as you can literally fake other parts of the devui making it a security issue.

We can limit that to localhost (so external is always also you - like swagger-ui)

2023-02-01 08:28 UTC, maxandersen commented
qute rendering - is it statically compiled qute or something else? 
not sure what current dev ui model does but we should enable it if possible.

2023-02-01 08:39 UTC, maxandersen commented
suggestion: separate notion of externalHtml into embedHtml that is allowed only on quarkus dev hosts (incl. future mgmt port) and externalHtml will explicitly show a "url banner" to make it clear it is not part of the main app or even force a separate open.

2023-02-01 09:22 UTC, phillip-kruger commented on extensions/vertx-http/deployment/src/main/java/io/quarkus/devui/deployment/BuiltTimeContentProcessor.java
> +                new MenuItem("qwc-build-steps", "hammer"));
@cescoffier f.y.i

2023-02-04 16:35 UTC, gsmet commented
@phillip-kruger let me know when I can rebase his one.

2023-02-04 21:32 UTC, phillip-kruger commented
Thanks @gsmet , I still have an issue with one test case, I'll let you know

2023-02-15 16:54 UTC, gsmet requested changes
Let's make sure we integrate https://github.com/quarkusio/quarkus/pull/31189 first and rebase on top of it as we need this change to be properly documented and not hidden in an unrelated PR.
If CI is greenish in this PR, I will do the rebase tomorrow morning.

2023-02-16 02:18 UTC, phillip-kruger commented
@gsmet I merged @mkouba 's PR and rebased this PR .

2023-02-17 13:43 UTC, phillip-kruger commented
@gsmet @cescoffier we have a green PR!! Now just someone who can review :)

2023-02-21 09:06 UTC, gsmet approved these changes
Let's merge and iterate in the `main` branch.

Very nice work @phillip-kruger , thanks for your dedication.

2023-02-21 09:06 UTC, merged

2023-02-21 09:07 UTC, gsmet commented on extensions/resteasy-classic/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/ClasspathResourceTestCase.java
> +                .log().all()
We whould probably remove the `.log().all()` in there in a follow-up PR.

2023-02-21 09:07 UTC, gsmet commented on extensions/resteasy-classic/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/files/StaticFileWithResourcesHttpRootTest.java
> +                .log().all()
Same here.

2023-02-21 09:08 UTC, gsmet commented on extensions/resteasy-classic/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/ClasspathResourceTestCase.java
> +                .log().all()
I will do it, I noticed a few other small things that I will address.