Ignore unprefixed properties when the matching capability is not present
quarkusio/quarkus pull request #30992
Opened 2023-02-08 09:33 UTC by Sgitario

Fix https://github.com/quarkusio/quarkus/issues/30850

2023-02-08 09:36 UTC, geoand commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesConfigUtil.java
> +    private static final Set<String> ALLOWED_GENERATORS = new HashSet<>(Arrays.asList(KUBERNETES, KNATIVE));
```suggestion
    private static final Set<String> ALLOWED_GENERATORS = Set.of(KUBERNETES, KNATIVE));
```

2023-02-08 09:40 UTC, Sgitario commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesConfigUtil.java
> +    private static final Set<String> ALLOWED_GENERATORS = new HashSet<>(Arrays.asList(KUBERNETES, KNATIVE));
Changed

2023-02-08 09:46 UTC, geoand approved these changes

2023-02-17 05:56 UTC, Sgitario commented
I think this fix was required for Kogito to be part of 2.16 @gsmet 
@iocanel can you have a look at the changes, please?

2023-02-17 15:32 UTC, iocanel reviewed
I only had the change to skim through it. 
It looks ok, but I don't see how it fixes the class cast issue.
I'll need to look it again.

2023-02-20 09:18 UTC, iocanel requested changes
I added a few minor naming remarks as I was reading carefully trying to understand what is going on.

It's still unclear to me why we `have to` do the capability filtering in order to prevent a `ClassCastException`. 

The filtering does sound like a reasonable approach at first, however, it does not exactly rhyme with dekorate where `kubernetes` brings in `docker`. This happens because the kubernetes bits optionally look up the docker config (if exists). 

Not sure what side effects this change might have. But I do feel that we should deal with the `ClassCastException` closer to the point it happens than solve it at the generator level.

2023-02-21 06:22 UTC, Sgitario commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesConfigUtil.java
> +    private static final Set<String> ALLOWED_GENERATORS = Set.of(KUBERNETES, KNATIVE);
Because OpenShift is an optional generator only available when having the `quarkus-openshift` extension present.

2023-02-21 06:25 UTC, Sgitario commented
> I added a few minor naming remarks as I was reading carefully trying to understand what is going on.
> 
> It's still unclear to me why we `have to` do the capability filtering in order to prevent a `ClassCastException`.
> 
> The filtering does sound like a reasonable approach at first, however, it does not exactly rhyme with dekorate where `kubernetes` brings in `docker`. This happens because the kubernetes bits optionally look up the docker config (if exists).
> 
> Not sure what side effects this change might have. But I do feel that we should deal with the `ClassCastException` closer to the point it happens than solve it at the generator level.

This is not to prevent `ClassCastException` errors, but not to read properties with prefixes `docker.xxx` which should never do it when the `quarkus-container-image-docker` extension is not present. And the same with the other generators in the map ALLOWED_GENERATORS_BY_CAPABILITY.

2023-02-21 08:32 UTC, Sgitario commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesConfigUtil.java
> +    private static final Map<String, String> ALLOWED_GENERATORS_BY_CAPABILITY = Map.of(
I've changed this map to have the capabilities as values, so the name makes more sense.

2023-02-21 08:33 UTC, Sgitario commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesConfigUtil.java
> +        for (Map.Entry<String, String> optionalGenerator : ALLOWED_GENERATORS_BY_CAPABILITY.entrySet()) {
Renamed to `generatorByCapability`

2023-02-23 13:02 UTC, iocanel commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesConfigUtil.java
> +    private static final Set<String> ALLOWED_GENERATORS = Set.of(KUBERNETES, KNATIVE);
This is not accurate, the openshift generator does not require `quarkus-openshift`. `quarkus-openshift` is just meant to provide some defaults. The full functionality is `quarkus-kubernetes`.

2023-02-23 13:04 UTC, Sgitario commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesConfigUtil.java
> +    private static final Set<String> ALLOWED_GENERATORS = Set.of(KUBERNETES, KNATIVE);
I'm not sure if we should process the `openshift.XX` properties, however these properties were not the issue, so I'm adding OPENSHIFT into the ALLOWED_GENERATORS.

2023-02-23 13:05 UTC, iocanel approved these changes
lgtm

2023-02-24 04:03 UTC, merged

2023-02-27 08:52 UTC, radtriste commented
@gsmet Can we expect a bug fix release with this fix ? if yes, you would have an estimated date ? :)