Remove relocations
quarkusio/quarkus pull request #31071
Opened 2023-02-10 13:55 UTC by gastaldi

- Fixes #31070

2023-02-10 13:56 UTC, gastaldi commented
Also we need to write something about this in the Migration Guide when the PR is merged

2023-02-10 14:18 UTC, gsmet requested changes
I had a look and I think we need to keep the `quarkus-opentelemetry-exporter-*` relocations.
They were added in 2.14 so 2.13 doesn't contain them.

2023-03-09 01:37 UTC, gastaldi commented
@gsmet gentle reminder to have a look at this PR 😉

2023-03-28 13:30 UTC, gsmet approved these changes

2023-03-28 13:30 UTC, merged