[fixes #3123] - Allow applications to customize how roles are decoded…
quarkusio/quarkus pull request #3124
Opened 2019-07-05 20:38 UTC by pedroigor

… from raw identity

2019-07-05 21:33 UTC, gsmet requested changes
There is a formatting error.

Please run `./mvnw process-sources` and amend your commit.

2019-07-08 09:49 UTC, gsmet commented
@pedroigor could you run the formatter and amend your commit, please?

Thanks!

2019-07-08 10:01 UTC, gsmet requested changes
Added 2 comments, could you take care of them?

FYI next release is on Wednesday at 12pm.

2019-07-08 13:44 UTC, pedroigor commented on extensions/elytron-security/runtime/src/main/java/io/quarkus/elytron/security/runtime/DefaultRoleDecoder.java
> +            return new Roles() {
I  realized that `Roles` provides a `fromSet` method that serves to the same purpose. Thanks for catching this.

2019-07-08 13:47 UTC, pedroigor commented on extensions/elytron-security/runtime/src/main/java/io/quarkus/elytron/security/runtime/DefaultRoleDecoder.java
> +        RoleDecoder delegate = getDelegate();
Yeah, but if we use the constructors we are assuming that app-defined instances are application-scoped and I'm not sure if that is always the case.

Or are you thinking about something else that I may be missing?

2019-07-08 14:04 UTC, gsmet commented on extensions/elytron-security/runtime/src/main/java/io/quarkus/elytron/security/runtime/DefaultRoleDecoder.java
> +        RoleDecoder delegate = getDelegate();
Hmmm. Right.

2019-07-08 14:29 UTC, pedroigor commented on extensions/elytron-security/runtime/src/main/java/io/quarkus/elytron/security/runtime/DefaultRoleDecoder.java
> +        RoleDecoder delegate = getDelegate();
If you think that we should worry about performance now, maybe we could check whether or not the first produced instance is application-scoped and then cache it?

Or maybe all this logic to use application provided instances into instances created during the build steps could be managed by Quarkus somehow? For instance, one drawback with the approach I'm using is that we may want to allow applications to provide instances for `RoleMapper` or `PermissionMapper`. For each of them we would need a similar instance as `DefaultRoleDecoder` just to use `Instance` to obtain the delegate.

2019-07-10 08:37 UTC, gsmet approved these changes

2019-07-10 08:38 UTC, gsmet commented
I force pushed a rebase due to conflicts with the recent s/template/recorder/ changes.

Let's wait to see what CI has to say.

2019-07-10 11:17 UTC, merged