Add more detail code and procedures on hibernate-orm-panache doc
quarkusio/quarkus pull request #31364
Opened 2023-02-23 04:55 UTC by chiroito

For beginners who unfamiliar with the development environment that quarkus is associated with, I have clearly stated imports and dependencies and added instructions on how to check the application.

2023-02-23 20:00 UTC, gastaldi commented on docs/src/main/asciidoc/hibernate-orm-panache.adoc
> +import javax.persistence.*;
We tend to avoid star imports. It would be nice to use only the classes needed in the snippet

2023-02-23 20:04 UTC, gastaldi commented on docs/src/main/asciidoc/hibernate-orm-panache.adoc
> +To make it easier to showcase some capabilities of Hibernate ORM with Panache on Quarkus, some test data should be inserted into the database by adding the following content to a new file named src/m
Maybe it's worth mentioning that this will only work when running in dev or test mode. See https://quarkus.io/guides/hibernate-orm#dev-mode

2023-02-28 03:29 UTC, gastaldi requested changes
Because the main branch is Quarkus 3, make sure you import the jakarta packages, since the javax won't be available

2023-02-28 03:29 UTC, gastaldi commented on docs/src/main/asciidoc/hibernate-orm-panache.adoc
> +import javax.persistence.Entity;
```suggestion
import jakarta.persistence.Entity;
```

2023-02-28 03:29 UTC, gastaldi commented on docs/src/main/asciidoc/hibernate-orm-panache.adoc
> +import javax.persistence.Entity;
```suggestion
import jakarta.persistence.Entity;
```

2023-02-28 03:29 UTC, gastaldi commented on docs/src/main/asciidoc/hibernate-orm-panache.adoc
> +import javax.persistence.Entity;
```suggestion
import jakarta.persistence.Entity;
```

2023-02-28 03:29 UTC, gastaldi commented on docs/src/main/asciidoc/hibernate-orm-panache.adoc
> +import javax.persistence.Entity;
```suggestion
import jakarta.persistence.Entity;
```

2023-02-28 03:29 UTC, gastaldi commented on docs/src/main/asciidoc/hibernate-orm-panache.adoc
> +import javax.inject.Inject;
```suggestion
import jakarta.inject.Inject;
```

2023-02-28 03:29 UTC, gastaldi commented on docs/src/main/asciidoc/hibernate-orm-panache.adoc
> +import javax.transaction.Transactional;
```suggestion
import jakarta.transaction.Transactional;
```

2023-02-28 03:29 UTC, gastaldi commented on docs/src/main/asciidoc/hibernate-orm-panache.adoc
> +import javax.ws.rs.core.Response;
Replace the `javax.ws` with `jakarta.ws`

2023-02-28 03:29 UTC, gastaldi commented on docs/src/main/asciidoc/hibernate-orm-panache.adoc
> +import javax.persistence.NamedQueries;
```suggestion
import jakarta.persistence.NamedQueries;
```

2023-02-28 03:29 UTC, gastaldi commented on docs/src/main/asciidoc/hibernate-orm-panache.adoc
> +import javax.persistence.ManyToOne;
```suggestion
import jakarta.persistence.ManyToOne;
```

2023-02-28 03:29 UTC, gastaldi commented on docs/src/main/asciidoc/hibernate-orm-panache.adoc
> +import javax.persistence.PersistenceException;
```suggestion
import jakarta.persistence.PersistenceException;
```

2023-02-28 07:47 UTC, gastaldi commented
Please squash all your commits before we trigger the CI again

2023-03-01 04:33 UTC, chiroito commented
I squashed all my commits. Could you review this again, please?

2023-03-08 03:05 UTC, chiroito commented
@gastaldi Could you review this again, please?

2023-03-08 08:41 UTC, gastaldi approved these changes

2023-03-08 08:42 UTC, merged

2023-03-08 08:42 UTC, gastaldi commented
Thanks! LGTM