Set default runtime profile to build profile
quarkusio/quarkus pull request #3153
Opened 2019-07-09 20:25 UTC by machi1990

Fixes #3147

2019-07-10 10:26 UTC, gsmet commented on docs/src/main/asciidoc/application-configuration-guide.adoc
> +mvn package -Pnative -Dquarkus-profile=prod-aws`
Note: we need to update this as soon as https://github.com/quarkusio/quarkus/pull/3159 is in.

2019-07-11 09:41 UTC, gsmet commented
This needs a rebase and we have some test failures.

2019-07-11 11:30 UTC, machi1990 commented
> This needs a rebase and we have some test failures.

Done.

2019-07-11 11:33 UTC, gsmet requested changes
Looks mostly good to me. I suggested some minor change to the doc. Could you take care of them?

2019-07-11 11:33 UTC, gsmet commented on docs/src/main/asciidoc/application-configuration-guide.adoc
> +<1> The command will run with the profile `prod-aws`. This can be overridden using `quarkus.profile` system property.
```suggestion
<1> The command will run with the `prod-aws` profile. This can be overridden using the `quarkus.profile` system property.
```

2019-07-11 11:41 UTC, machi1990 commented on docs/src/main/asciidoc/application-configuration-guide.adoc
> +<1> The command will run with the profile `prod-aws`. This can be overridden using `quarkus.profile` system property.
Thanks. Suggestion applied.

2019-07-11 12:45 UTC, gsmet approved these changes
Looks good to me now.

2019-07-11 16:54 UTC, merged