Allow configuring the deploy strategy to perform K8s deployments
quarkusio/quarkus pull request #31724
Opened 2023-03-09 10:04 UTC by Sgitario

Fix https://github.com/quarkusio/quarkus/issues/26789

2023-03-09 11:56 UTC, Sgitario commented
Note that I didn't add any test cases but I did test the four strategies manually and everything is working as expected.

2023-03-10 07:37 UTC, iocanel requested changes

2023-03-10 07:37 UTC, iocanel commented on extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftUtils.java
> +    private static final String OPENSHIFT_DEPLOY_STRATEGY = "quarkus.openshift.namespace";
This doesn't seem right

2023-03-10 09:39 UTC, iocanel approved these changes

2023-03-10 09:39 UTC, iocanel commented on extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftUtils.java
>      private static final String KUBERNETES_NAMESPACE = "quarkus.kubernetes.namespace";
This seems ok now

2023-03-10 13:20 UTC, merged