implement a NullEntityManager to prevent large NPE stacktraces when
quarkusio/quarkus pull request #3183
Opened 2019-07-10 23:16 UTC by evanchooly

there are no classes marked up with @Entity.

This is a case that bit me during a live demo.  If there are no @Entity classes, no EntityManager gets created/injected leading to unexpected NPEs trying to run queries.  This patch introduces a dummy EM that essentially only returns empty Lists so that user code at least gets something usable.

I know there are probably plenty of conversations to have about both this idea and my particular implementation.  This PR largely serves as a starting point for that conversation and, if I'm *really* lucky, its resolution as well.  :)

2019-07-11 09:02 UTC, gsmet commented
IMHO, this is going too far. I don't think generating mock objects in "production" code is a good idea.

Yeah, the first thing to do is to define your entities. But that sounds logical since you have to have their names, fields and so on to write your queries.

But I would have expected an injection error if don't have an EM, not a NPE. At least the error reporting should be improved.

2019-07-11 10:36 UTC, emmanuelbernard commented
Right, at best it should only be activated in DEV mode but I wonder about your demo and steps you build stuff on.
Were you writing queries before even defining your entities? That feels a bit unnatural.

2019-07-11 10:36 UTC, emmanuelbernard commented
Anyways I'm curious of the steps that led you there.

2019-07-11 11:05 UTC, stuartwdouglas commented
I don't understand how this really help's? NPE is not good, but IMHO Panache should throw an exception about the EM not being available.

If you actually tried to use a real entity manager before you have any entities you are always going to get an exception, we should make it meaningful, but IMHO we should definitely not just be faking it and returning null.

2019-07-11 11:58 UTC, evanchooly commented
In my case, I had the entity but forgot to put `@Entity` on it.  My first thought was to blow up the build but didn't think anyone would go for that.  After all there might be legitimate reasons for not having any entities defined (yet).  And so I went with something like this.  What if, instead of the `Null*` variants, if I throw an exception of some point when the `EM` comes back null.  It could have a meaningful message that would be better than just a random NPE when trying to run a query.

2019-07-11 12:13 UTC, stuartwdouglas commented
If you have a Panache Repository then I think that should blow up the build if there is no EM (if it does not already). For the static method case I think it should fail with a meaningful error message. Returning null would be way more confusing IMHO. If you are calling a query method then you clearly expect there to be entities, we should make it clear that you have stuffed something up, not silently do something else.

2019-07-11 12:44 UTC, evanchooly commented
OK.  I will update to throw an exception during the build phase about missing entities and repush.

2019-07-11 12:56 UTC, stuartwdouglas commented
Only in the case of using the Repository. If there is just a class that extends PanacheEntity on the class path that is not annotated @Entity then IMHO this should not be a build error, it should be a runtime error if you attempt to use it.

The difference is the repository is a CDI bean, while the (non)entity is not, and CDI beans are expected to have boot time validation applied to make sure they are valid.

2019-07-11 13:18 UTC, FroMage commented
> Only in the case of using the Repository. If there is just a class that extends PanacheEntity on the class path that is not annotated @entity then IMHO this should not be a build error, it should be a runtime error if you attempt to use it.

We could discuss this. IMO it has to have either `@Entity` or `@MappedSuperclass` on it. I don't think any other option is meaningful, is it @emmanuelbernard ?

If that's indeed the case, we could throw a meaningful error at build or runtime.

2019-07-11 13:25 UTC, emmanuelbernard commented
So yes we even considered adding @Entity on a panache entity by default as it's "redundant". Not sure we agreed to or decided to not go that far.

2019-07-11 13:36 UTC, evanchooly commented
Currently, the builds finds my `PanacheEntity` but no `EntityManager` gets injected because there is no `@Entity` on my class.  So I'm tracking down where that decision to not register the EM for injection is made and will throw the exception there.

2019-07-11 14:53 UTC, evanchooly commented
I'm not entirely sure of the placement or the exception type but this was the best place I could find to throw it. It's not in the panache bits but in the hibernate module which has me worrying it's not in the right place.  AFAICT, the panache build steps didn't even run in the case of no entities so this felt like the best place to error out.

2019-07-11 14:56 UTC, gsmet commented
It will really be a pain if, as soon as you add the extension, you can't start your app.

I agree we should improve the error message and not have NPE but I would keep the exception at runtime, not build.

2019-07-11 15:16 UTC, evanchooly commented
So what if we check for the null EM and rather using the `NullX` objects *there* we throw a `PersistenceException` ?  We can log the missing `@Entity` bits at build time and then throw an exception at runtime.

2019-07-11 16:46 UTC, evanchooly commented
I just pushed that change as mine was causing a test failure with the build time exception.

2019-07-17 21:31 UTC, gsmet requested changes
Added some comments inline.

2019-07-17 21:31 UTC, gsmet commented on extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java
> +            log.warn("No entities were found!");
I'm not a big fan of this warning as you will have it as soon as you add the ORM extension. I would remove it.

2019-07-17 21:31 UTC, gsmet commented on extensions/panache/hibernate-orm-panache/runtime/src/main/java/io/quarkus/hibernate/orm/panache/runtime/JpaOperations.java
> +            throw new PersistenceException("No EntityManager found.  Do you have any Entities defined?");
```suggestion
            throw new PersistenceException("No EntityManager found. Do you have any JPA entities defined?");
```

2019-07-17 21:31 UTC, gsmet commented on extensions/panache/hibernate-orm-panache/runtime/src/main/java/io/quarkus/hibernate/orm/panache/runtime/JpaOperations.java
> +        if (entityManager == null) {
I would use `isAvailable()` here instead of doing the `get()` directly.

It makes things more readable IMHO.

2019-07-31 08:25 UTC, gsmet commented
I pushed an update along the lines of what I asked for so that we can get this in finally.

Will wait for CI and merge.

2019-07-31 11:04 UTC, gsmet approved these changes

2019-07-31 11:04 UTC, merged

2019-07-31 12:35 UTC, evanchooly commented
hrm.  I'm not sure how I missed these comments.  I never got a notification about your requested changes.  At any rate, i'm glad this is going in.  Thanks.