WIP - Add more options to exclude classes from the default JAXBContext
quarkusio/quarkus pull request #31940
Opened 2023-03-17 12:28 UTC by gnieser

Following this [discussion](https://github.com/quarkusio/quarkus/discussions/31882), I would like to thank @Sgitario for his kind assistance and his invitation to try to contribute.

Here is a pull request with:
* A `quarkus.jaxb.exclude-packages` to exclude classes from given packages from the default JAXBContext
* A `quarkus.jaxb.exclude-pattern` to exclude classes whose names matches the pattern from the default JAXBContext

To reply to @Sgitario 's comment from the discussion:
> Though, I would merge the `exclude-classes` and `exclude-packages` into `exclude-classes` (and use the `startWith` matching).

I'm thinking of cases such as classes named User and UserAccount, a startWith matching may not work as intended, if only the User class is to be excluded for some reason.

> Moreover, I would not add pattern matching at least it's essential since we used not to try adding too many superficial configuration options.

The motivation behind pattern matching is to provide adequate tooling for developer using xjc with third-party XSD. The sheer number of classes can grow up pretty quickly and one have little control over them.

I agree having both exclude-packages and pattern matching is somehow redundant. Pattern matching can easily exclude packages.

Of course, I will proceed with what ever option you prefer. :)

2023-03-17 13:03 UTC, Sgitario requested changes
Thanks for your pull request! 
From my side, I have the same comments as in https://github.com/quarkusio/quarkus/discussions/31882#discussioncomment-5344280.

2023-03-17 13:32 UTC, gnieser commented
What would you think of dropping pattern matching (`exclude-pattern`) and changing `exclude-classes` behavior to the following?
  * if item ends with `.*` then assume it is a package and perform `startsWith` matching
  * otherwise assume it is a class and perform `equals` matching

It would avoid collision when exclusion of a User class would incidentally also exclude a UserAccount class.

2023-03-17 14:20 UTC, gnieser commented
I've committed these changes.

I should also rebase and squash my two commits and force-push into single one, shoudn't I?

2023-03-17 14:32 UTC, Sgitario commented
Yes, please

2023-03-20 05:16 UTC, Sgitario approved these changes
lgtm!

2023-03-20 05:16 UTC, merged