Move OTel configuration to use @ConfigMapping
quarkusio/quarkus pull request #32050
Opened 2023-03-22 18:41 UTC by radcortez

2023-03-22 19:13 UTC, brunobat requested changes
@radcortez Did you check if the properties will show properly in the docs?

2023-03-22 19:13 UTC, brunobat commented on extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/build/TracesBuildConfig.java
> -    @ConfigItem(defaultValue = "${quarkus.opentelemetry.tracer.enabled:true}")
Please update the documentation because `${quarkus.opentelemetry.tracer.enabled:true}` will no longer show.

2023-03-22 19:13 UTC, brunobat commented on extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/TracesRuntimeConfig.java
> -    @ConfigItem(name = "suppress-non-application-uris", defaultValue = "${opentelemetry.tracer.suppress-non-application-uris:true}")
Please update the documentation mentioning the old mapping

2023-03-22 19:13 UTC, brunobat commented on extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/TracesRuntimeConfig.java
> -    @ConfigItem(name = "include-static-resources", defaultValue = "${quarkus.opentelemetry.tracer.include-static-resources:false}")
Please update the documentation mentioning the old mapping

2023-03-22 19:13 UTC, brunobat commented on extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/config/runtime/exporter/OtlpExporterTracesConfig.java
> -    @ConfigItem(name = "legacy-endpoint", defaultValue = "${quarkus.opentelemetry.tracer.exporter.otlp.endpoint:" +
Please update the documentation mentioning the old mapping

2023-03-23 10:28 UTC, brunobat commented
Nope, the documentation is not picked up:
<img width="980" alt="image" src="https://user-images.githubusercontent.com/2318030/227175774-9e0b63b5-632a-4ca3-8846-27fe9af11d2c.png">

2023-03-23 17:04 UTC, radcortez commented
It requires https://github.com/quarkusio/quarkus/pull/32085 to generate the documentation correctly.

2023-03-27 08:49 UTC, brunobat approved these changes

2023-03-28 15:46 UTC, merged