Fix gRPC context propagation
quarkusio/quarkus pull request #32164
Opened 2023-03-27 15:47 UTC by alesj

This fixes #32046 issue.

2023-03-27 15:48 UTC, cescoffier approved these changes

2023-03-27 15:51 UTC, alesj commented
@cescoffier wait with the merge ... let me test this on blocking methods as well ...

2023-03-27 16:36 UTC, alesj commented
@cescoffier OK, added a blocking test, ad it worked ootb

2023-03-28 10:00 UTC, cescoffier requested changes
LGTM except the logger api

2023-03-28 10:00 UTC, cescoffier commented on extensions/grpc/runtime/src/main/java/io/quarkus/grpc/runtime/supports/blocking/BlockingServerInterceptor.java
> +import org.slf4j.Logger;
Should use jboss logging

2023-04-18 07:24 UTC, cescoffier commented
@alesj can you rebase, just to be sure?

2023-06-27 11:15 UTC, geoand commented
Whats the status of this? If it's ready to be merged, please rebase once more and then add the `waiting-for-ci` label

2023-06-27 11:19 UTC, cescoffier commented
No it's not. There is a race somewhere.

2023-06-27 11:21 UTC, geoand commented
Understood, thanks

2023-10-15 15:47 UTC, cescoffier commented
@alesj do you believe we can make the race more easily reproducible?

2023-10-15 16:01 UTC, alesj commented
It’s been a while, but I remember I saw it quite often.
As all race conditions, it’s not easy to reproduce though. :-)

On Sun, 15 Oct 2023 at 17:47, Clement Escoffier ***@***.***>
wrote:

> @alesj <https://github.com/alesj> do you believe we can make the race
> more easily reproducible?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/quarkusio/quarkus/pull/32164#issuecomment-1763429549>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACRA6ASB55AL5B6A2SMKODX7QARDANCNFSM6AAAAAAWJKKZF4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-23 08:15 UTC, cescoffier commented
@alesj I just pushed a one-line-fix. When creating a new context, you need to attach it explicitly. Thanks to the duplicated context handling, it will attach it to the duplicated context of the call.

2023-10-23 15:55 UTC, cescoffier approved these changes

2023-10-23 15:55 UTC, merged