Fixes and improvements for image build and deploy mojo and tasks
quarkusio/quarkus pull request #32256
Opened 2023-03-30 08:05 UTC by iocanel

Resolves: #32226

Also addresses a ton of issues spotted with I was on it:

- Deploy tasks was competely broken
- Both image build & deploy tasks/mojo didn't recognize `quarkus-openshift` as a container image extension.
- Both deploy tasks/mojo were getting confused by the presence of image builders in the project.
- A lot of code dublication.

2023-03-30 18:37 UTC, iocanel commented
I don't think that the failures are related as these seem to standard errors these days.

2023-04-03 12:52 UTC, Sgitario requested changes
Because of the refactoring changes, I can't easily see the actual fix, perhaps what fixes the linked issue is that you're filtering out the transitive dependencies?

Also, I tried these changes and `mvn quarkus:deploy` now does not fail, but the OpenShift S2i deployment is not triggered (using `mvn clean install -Dquarkus.kubernetes.deploy=true` does work). I expected that `mvn quarkus:deploy` was similar to `mvn clean install -Dquarkus.kubernetes.deploy=true`.

2023-04-03 12:52 UTC, Sgitario commented on devtools/maven/src/main/java/io/quarkus/maven/ImageBuilder.java
> +    public static Set<String> getProjecBuilder(MavenProject project) {
There is a typo here.

2023-04-05 13:16 UTC, iocanel commented
Just realized that this pull request hasn't been merged yet and I have already created a follow up request #32410 that does includes all the commitss of this one.

2023-04-05 13:18 UTC, closed without merging