Even more cli fixes
quarkusio/quarkus pull request #32410
Opened 2023-04-04 17:22 UTC by iocanel

The pull request deals with the following:

- latency issues related with cli plugins.
- allows adding directly aliases from remote catalogs (wihtout to install the alias locally).
- introduce java plugin types.
- add more descriptive messages
- bug fixes.

2023-04-05 13:15 UTC, iocanel commented
This pull request is a superset of #32256 so I will close that and apply requested changes to this one.

2023-04-11 10:35 UTC, Sgitario requested changes
I'm not very familiar with the changes in the CLI and Maven/Gradle modules, so will delegate the code review to Max.
However, doing `mvn quarkus:deploy` in a project that uses the OpenShift extension is not equivalent to do `mvn clean install -Dquarkus.kubernetes.deploy=true` (it does not fail, but the binary are not uploaded, and hence the build does not start).

2023-04-11 10:41 UTC, iocanel commented
> I'm not very familiar with the changes in the CLI and Maven/Gradle modules, so will delegate the code review to Max. However, doing `mvn quarkus:deploy` in a project that uses the OpenShift extension is not equivalent to do `mvn clean install -Dquarkus.kubernetes.deploy=true` (it does not fail, but the binary are not uploaded, and hence the build does not start).

The two commands are not equivallent. The `quarkus:deploy` does not perform a build by default.

2023-04-11 10:55 UTC, Sgitario commented
> > I'm not very familiar with the changes in the CLI and Maven/Gradle modules, so will delegate the code review to Max. However, doing `mvn quarkus:deploy` in a project that uses the OpenShift extension is not equivalent to do `mvn clean install -Dquarkus.kubernetes.deploy=true` (it does not fail, but the binary are not uploaded, and hence the build does not start).
> 
> The two commands are not equivallent. The `quarkus:deploy` does not perform a build by default.

Any technical reason why both commands behave differently?

2023-04-11 11:40 UTC, iocanel commented
> > > I'm not very familiar with the changes in the CLI and Maven/Gradle modules, so will delegate the code review to Max. However, doing `mvn quarkus:deploy` in a project that uses the OpenShift extension is not equivalent to do `mvn clean install -Dquarkus.kubernetes.deploy=true` (it does not fail, but the binary are not uploaded, and hence the build does not start).
> > 
> > 
> > The two commands are not equivallent. The `quarkus:deploy` does not perform a build by default.
> 
> Any technical reason why both commands behave differently?

Not a technical decsion. It's more a UX one.

2023-04-11 14:40 UTC, gsmet commented on devtools/cli/src/main/java/io/quarkus/cli/BuildToolDelegatingCommand.java
> +                context.getBuildOptions(),
@ia3andy @aloubyansky I'm not sure if this class is related to the plugins only or not. If not, I'd like to have your opinion on this change.

2023-04-11 15:02 UTC, aloubyansky approved these changes

2023-04-11 15:11 UTC, iocanel commented
> > > > I'm not very familiar with the changes in the CLI and Maven/Gradle modules, so will delegate the code review to Max. However, doing `mvn quarkus:deploy` in a project that uses the OpenShift extension is not equivalent to do `mvn clean install -Dquarkus.kubernetes.deploy=true` (it does not fail, but the binary are not uploaded, and hence the build does not start).
> > > 
> > > 
> > > The two commands are not equivallent. The `quarkus:deploy` does not perform a build by default.
> > 
> > 
> > Any technical reason why both commands behave differently?
> 
> Not a technical decsion. It's more a UX one.

@Jose given that this change is intended can you please change your review as it currently blocks the merge?

2023-04-12 07:48 UTC, gsmet approved these changes
I'm gonna merge this as it contains a lot of fixes. We can fine tune later.

2023-04-12 07:48 UTC, merged