Java 11: Disable Graphics for JAXB
quarkusio/quarkus pull request #3246
Opened 2019-07-16 14:51 UTC by dmlloyd

This allows native images to be built on Java 11 including JAXB.

2019-07-16 16:45 UTC, gsmet requested changes
I'm not a big fan of having global JDK substitutions in particular extensions as, as soon as you add the extension, you change the behavior of a global component.

I mean, if it doesn't work, it should be disabled globally in the same way as ImageIO for instance. Or is there a specific reason why it's disabled only for JAXB?

I also think it would be better to throw something like `throw new UnsupportedOperationException("Not implemented yet for GraalVM native images");` so that the error has a bit of context.

2019-07-16 16:49 UTC, dmlloyd commented
The problem came up under JAXB.  But I don't have a problem moving it either.

2019-07-16 16:57 UTC, gsmet commented
I would prefer having it together with the `ImageIO` substitution and have all the JDK-level substitution global.

2019-07-17 11:26 UTC, gsmet approved these changes

2019-07-17 11:26 UTC, merged

2019-07-17 11:26 UTC, gsmet commented
Merged, thanks!