Ensure the ServiceAccount/Role/ClusterRole resourcs are created in order
quarkusio/quarkus pull request #32651
Opened 2023-04-14 12:49 UTC by Sgitario

Fix https://github.com/quarkusio/quarkus/issues/32640 
Partially reverts https://github.com/quarkusio/quarkus/pull/32208

2023-04-14 12:56 UTC, iocanel commented
Given that we allow users to bring their own resources, it's possible to end up with dependency chains that are contains 3 or more items (e.g. Namespace -> ConfigMap -> Deployment).

I suggest we just order resources in a way similar to: https://github.com/superbrothers/ksort/blob/af6d8f61cdc596ef660c1ffd64c6ca8604b0cb91/kind_sorter.go#L29

2023-04-14 13:02 UTC, Sgitario commented
> Given that we allow users to bring their own resources, it's possible to end up with dependency chains that are contains 3 or more items (e.g. Namespace -> ConfigMap -> Deployment).
> 
> I suggest we just order resources in a way similar to: https://github.com/superbrothers/ksort/blob/af6d8f61cdc596ef660c1ffd64c6ca8604b0cb91/kind_sorter.go#L29

+100 
PR updated with this list.

2023-04-17 11:02 UTC, maxandersen commented
marking as backport as it result in app deployment error.

2023-04-18 06:24 UTC, iocanel requested changes
Looks good, but we should also include `ImageStream` and `BuildConfig` resources.

2023-04-18 06:24 UTC, iocanel commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/QuarkusFileWriter.java
> +            "Service",
```suggestion
            "Service",
            "ImageStream",
            "BuildConfig",
```

2023-04-18 06:40 UTC, Sgitario commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/QuarkusFileWriter.java
> +            "Service",
Done

2023-04-18 06:40 UTC, Sgitario commented
PR updated by adding the ImageStream and BuildConfig resources.

2023-04-18 08:31 UTC, gsmet commented
@iocanel I let you approve and merge if you're happy with the changes.

2023-04-18 10:52 UTC, iocanel approved these changes
lgtm

2023-04-18 10:53 UTC, merged