Only provide `quarkus.datasource.jdbc.url` from DevServices when Agroal is available
quarkusio/quarkus pull request #32723
Opened 2023-04-18 11:31 UTC by radcortez

- Fixes #32591

2023-04-18 14:26 UTC, geoand commented
CI is rather unhappy about it..

2023-04-18 14:47 UTC, gsmet requested changes
I added a few small suggestions.

2023-04-18 15:43 UTC, radcortez commented on extensions/datasource/deployment/src/main/java/io/quarkus/datasource/deployment/devservices/DevServicesDatasourceProcessor.java
> +        private static final boolean IS_AGROAL_EXTENSION_AVAILABLE = isClassPresentAtRuntime("io.quarkus.agroal.DataSource");
Guess, I'm still used in the old way :)

2023-04-19 07:45 UTC, gsmet approved these changes

2023-04-19 07:45 UTC, merged