Provide programmative transaction for MongoDB reactive with Panache
quarkusio/quarkus pull request #32794
Opened 2023-04-20 11:11 UTC by loicmathieu

Fixes #32156

2023-04-20 11:14 UTC, loicmathieu commented
@FroMage this is a PoC for MongoDB with Panache reactive transaction based on what you did for HIbernate with Panache. Before I implement the transaction support for all operations can you check the way I handle transactions is the new Panache class ?

2023-05-24 13:49 UTC, evanchooly approved these changes
The changes look fine.  The failing tests are odd, though.

2023-05-24 15:25 UTC, loicmathieu commented
@evanchooly thanks, I'll have a look at the failing test soon.

2023-05-30 12:23 UTC, loicmathieu commented
@evanchooly I fixed the tests, this was due to the fact that a Vert.x context was required for reactive transactions but it should not be required out of the context of a transaction so I updated the code accordingly (a Vert.x context is only required to in a transaction). I also added a small section on the documentation, can you have a look please?

2023-06-05 14:39 UTC, FroMage requested changes
This looks alright to me, minus the context removal question. 

What's the point about transactions in mongo again? IIRC they require replicas, right?

Do you think you should test transactions to run multiple things in isolation? I don't think the tests do that.

Also, do you intend to also provide the equivalent of `@WithTransaction`?

2023-06-05 14:46 UTC, loicmathieu commented
@FroMage 

> What's the point about transactions in mongo again? IIRC they require replicas, right?

They are lightweight transactions and require a replica set, but you can configure a replicaset of one node (our devservices is configured this way). Basically, you open a session and pass it to all calls to the MongoDB driver, and at the end you commit or rollback. So the only trick is to store the session somewhere, in the Vert.x context here.

> Do you think you should test transactions to run multiple things in isolation? I don't think the tests do that.

I agree test can be improved, but the transaction for the sync client has the same test. I don't remember in details the isolation model of MongoDB transactions, I can open a followup issue to improve our test coverage for it.

> Also, do you intend to also provide the equivalent of @WithTransaction?

Maybe someday depending on my todo list ;) I need to check how it was done on HIbernate reactive and take inspiration.

2023-06-05 15:25 UTC, FroMage commented
> They are lightweight transactions and require a replica set, but you can configure a replicaset of one node (our devservices is configured this way). Basically, you open a session and pass it to all calls to the MongoDB driver, and at the end you commit or rollback. So the only trick is to store the session somewhere, in the Vert.x context here.

OK thanks.

> > Do you think you should test transactions to run multiple things in isolation? I don't think the tests do that.
> 
> I agree test can be improved, but the transaction for the sync client has the same test. I don't remember in details the isolation model of MongoDB transactions, I can open a followup issue to improve our test coverage for it.

Well, at least you're testing that we can roll stuff back :) But yeah, isolation is probably worth testing.

> Maybe someday depending on my todo list ;) I need to check how it was done on HIbernate reactive and take inspiration.

You'd better check that this isn't what the original user wanted in https://github.com/quarkusio/quarkus/issues/32156, because otherwise you're both going to be disappointed ;)

2023-06-06 10:49 UTC, loicmathieu commented on extensions/panache/mongodb-panache-common/runtime/src/main/java/io/quarkus/mongodb/panache/common/reactive/Panache.java
> +        current.close();
Fixed, I remove the local in a try/finaly block to avoid any potential leak.

2023-06-06 10:51 UTC, loicmathieu commented
@FroMage if it's OK with the context local removal I want to proceed with the PR as is, I'll create followup issue for more test on MongoDB transaction support (both sync and reactive) and a followup to support annotation based transactions.

2023-06-08 09:37 UTC, FroMage approved these changes
Yup, all good, thanks!

2023-06-08 09:38 UTC, merged