Add possibility to parse days and milliseconds with config DurationConverter
quarkusio/quarkus pull request #32929
Opened 2023-04-26 19:28 UTC by manofthepeace

This adds the possibility to convert durations in milliseconds like `25ms` or days `7d`. Made the `START_WITH_DIGITS` case a bit more solid by allowing only valid units, case insensitive.

2023-05-02 08:42 UTC, gsmet approved these changes
I think it's an interesting addition but let's wait for @radcortez 's opinion before merging.

2023-05-02 09:33 UTC, radcortez approved these changes

2023-05-02 09:36 UTC, radcortez requested changes
I'm ok with the new feature, but the test failures are related.

2023-05-03 20:32 UTC, radcortez approved these changes

2023-05-08 12:34 UTC, manofthepeace commented
rebased, just in case.

2023-05-11 13:53 UTC, manofthepeace commented
@gsmet do you think it is possible to have that in 3.1?

2023-05-16 09:20 UTC, machi1990 requested changes
Nice addition, thanks @manofthepeace . Can we update the duration format note doc: https://github.com/quarkusio/quarkus/blob/f7b67786ab8d51c499227bcceee523eb96298e08/docs/src/main/asciidoc/_includes/duration-format-note.adoc? Thanks

2023-05-16 12:48 UTC, manofthepeace commented
> Nice addition, thanks @manofthepeace . Can we update the duration format note doc: https://github.com/quarkusio/quarkus/blob/f7b67786ab8d51c499227bcceee523eb96298e08/docs/src/main/asciidoc/_includes/duration-format-note.adoc? Thanks

@machi1990 thanks for the review. Updated the duration format note.

2023-05-16 21:57 UTC, machi1990 approved these changes

2023-05-17 15:22 UTC, radcortez approved these changes

2023-05-19 17:42 UTC, manofthepeace commented
@machi1990 went though the log but have trouble seeing anything related, would you know better?

2023-05-20 20:29 UTC, merged