[WIP] Make the update guide evergreen
quarkusio/quarkus pull request #33034
Opened 2023-05-01 18:52 UTC by rolfedh

I wonder how we can make the update guide evergreen so it doesn't need to be updated.
Here, I've removed almost all references to specific versions, or suggested using the "latest version". 
I believe the user can omit `--stream=3.0` from the `quarkus update --stream=3.0` command. The command seems to default to the latest version, too.

2023-05-04 11:47 UTC, rolfedh commented
@aloubyansky, would you review/approve this MR?

2023-05-04 12:16 UTC, aloubyansky approved these changes
Looks good to me. @gsmet wdyt?

2023-05-04 12:30 UTC, gsmet requested changes
Added a comment about the file name.

The other comment can be addressed now or later.

2023-05-04 19:58 UTC, rolfedh commented on docs/src/main/asciidoc/update-to-quarkus-3.adoc
>  https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
Updated. Thanks.

2023-05-04 20:06 UTC, rolfedh commented on docs/src/main/asciidoc/update-to-quarkus-3.adoc
> -quarkus update --stream=3.0
Updated. Thanks.

2023-05-05 09:07 UTC, gsmet approved these changes

2023-05-05 09:07 UTC, merged

2023-05-05 09:08 UTC, gsmet commented
Thanks!

Could you create a PR against the website to install a redirect? I will merge it when I release this change. Thanks!