Add QuarkusDevModeTest for testing hot reload
quarkusio/quarkus pull request #3317
Opened 2019-07-24 04:46 UTC by stuartwdouglas

This allows extensions to write unit test cases for hot reload that
do not require a new maven project

2019-07-24 12:10 UTC, stuartwdouglas commented
Looks like there is a race here, I will investigate.

2019-07-25 06:03 UTC, machi1990 commented
Can't wait to play with this. Thanks @stuartwdouglas. 

It should fix #3317

2019-07-25 07:28 UTC, mkouba commented
Would it make sense to add custom build chain customizers to `QuarkusDevModeTest`; i.e. something like https://github.com/quarkusio/quarkus/blob/master/test-framework/junit5-internal/src/main/java/io/quarkus/test/QuarkusUnitTest.java#L107-L110. This would basically allow an extension author to test a hot deployment feature based on a build item and not a concrete component (such as servlet).

2019-07-25 07:29 UTC, stuartwdouglas commented
I don't know, hot deployment is really a user facing feature, I think it makes sense to test it the same way a user would. Do you have a concrete example of where this would be useful?

2019-07-25 07:33 UTC, mkouba commented
The only example I have is a test for `HotDeploymentWatchedFileBuildItem.restartNeeded` - there is currently no built-in extension using this flag and so we can't verify the functionality inside the quarkus project.

2019-07-25 22:28 UTC, stuartwdouglas commented
I was thinking about creating a hot-deployment-tests module and moving some of the tests that are currently in DevMojoIT into this module to improve the build time. If we were going to do this we could likely just include some @BuildSteps in this module to test this functionality. 

Dev mode is not really setup for chain customisers, it would need to be passed down through a few different layers.

2019-07-26 05:22 UTC, stuartwdouglas commented
@emmanuelbernard can you review as you opened the original issue?

2019-07-26 14:58 UTC, kenfinnigan requested changes
Just some minor verbiage suggestions

2019-07-26 14:58 UTC, kenfinnigan commented on docs/src/main/asciidoc/extension-authors-guide.adoc
> +It is also possible to write tests that verify you extension works correctly in development mode and can correctly
"verify you" -> "verify an"

2019-07-26 14:58 UTC, kenfinnigan commented on docs/src/main/asciidoc/extension-authors-guide.adoc
> +For most extensions this will just work 'out of the box' however it is still a good idea to have a smoke test to
Add comma after 'out of the box'

2019-07-26 14:58 UTC, kenfinnigan commented on docs/src/main/asciidoc/extension-authors-guide.adoc
> +<1> This is the starting deployment, your test can modify it as part of the test suite. Quarkus will be restarted between
"This starts the deployment"

2019-07-26 14:58 UTC, kenfinnigan commented on docs/src/main/asciidoc/extension-authors-guide.adoc
> +<2> This method allows you to modify the source of a class file. The old source is passed into the function, and the source
"and the updated source is returned"

2019-08-07 12:23 UTC, geoand approved these changes

2019-08-07 12:24 UTC, merged

2019-08-07 12:29 UTC, geoand commented
@machi1990 would you like to check and see sometime if some the current maven dev mode tests could be replaced with the new test framework?

2019-08-14 20:20 UTC, gwenneg commented
@stuartwdouglas I tried to use `QuarkusDevModeTest` in a slightly different way from the example you added in the guide, but I got a NPE while using an injected bean:
```
public class DevModeCachedServiceChangeTest {

    @RegisterExtension
    final static QuarkusDevModeTest TEST = new QuarkusDevModeTest()
            .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class).addClass(DevModeCachedService.class));

    @Inject
    DevModeCachedService cachedService; // @ApplicationScoped bean

    @Test
    public void testServiceChange() throws InterruptedException {
        cachedService.doSomething(); // NPE thrown here
    }
}
```
Is this supposed to work or do I have to put my service behind a servlet or a JAX-RS resource?

2019-08-14 22:51 UTC, stuartwdouglas commented
You can't inject into dev mode tests, it would be complicated to do as dev
mode creates its own class loader for the beans (to allow restart) and
every restart the test would need to be re-injected.

On Thu, 15 Aug 2019 at 06:20, Gwenneg Lepage <notifications@github.com>
wrote:

> @stuartwdouglas <https://github.com/stuartwdouglas> I tried to use
> QuarkusDevModeTest in a slightly different way from the example you added
> in the guide, but I got a NPE while using an injected bean:
>
> public class DevModeCachedServiceChangeTest {
>
>     @RegisterExtension
>     final static QuarkusDevModeTest TEST = new QuarkusDevModeTest()
>             .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class).addClass(DevModeCachedService.class));
>
>     @Inject
>     DevModeCachedService cachedService; // @ApplicationScoped bean
>
>     @Test
>     public void testServiceChange() throws InterruptedException {
>         cachedService.doSomething(); // NPE thrown here
>     }
> }
>
> Is this supposed to work or do I have to put my service behind a servlet
> or a JAX-RS resource?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/quarkusio/quarkus/pull/3317?email_source=notifications&email_token=AACQG647L3BLMXJNWEASOUDQERSILA5CNFSM4IGMD2W2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4J7VSY#issuecomment-521403083>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AACQG62TR3LYXBQI4GFVSBDQERSILANCNFSM4IGMD2WQ>
> .
>

2019-08-15 07:54 UTC, gwenneg commented
I'll adapt my test then, thanks for your answer!

2019-08-15 12:26 UTC, gwenneg commented
I replaced the bean injection with a JAX-RS resource and now my hot reload test works like a charm. It could be helpful to add a few lines in the guide about the need to add the following dependency for extensions that don't already have `quarkus-resteasy` in their `compile` scope:

```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-resteasy-deployment</artifactId>
    <scope>test</scope>
</dependency>
```

Or the servlet equivalent.