Fix 'quarkus.otel.exporter.otlp.traces.timeout' default value
quarkusio/quarkus pull request #33326
Opened 2023-05-12 11:32 UTC by mazenkhalil

The default duration for timeout property is wrongly defined and causes runtime error.

2023-05-12 16:57 UTC, manofthepeace commented
This should work once this gets merged; https://github.com/quarkusio/quarkus/pull/32929 as I made the check case insensitive in the converter, also since Duration.parse does support both lowercase and uppercase.

2023-05-15 11:57 UTC, gsmet commented
@mazenkhalil what type of error do you have? Because it's not the only duration specific like that and IIRC it works OK.

2023-05-15 12:25 UTC, brunobat requested changes
Projects compile ok with this config.
What error do you see?
If we are going to perform this change, we also need to update `HibernateSearchOutboxPollingRuntimeConfigPersistenceUnit` and many other classes.

2023-05-15 13:46 UTC, brunobat approved these changes
Ok, that's the OTel SDK failing because it doesn't recognise the pattern. 
Let's fix this.

2023-05-15 13:49 UTC, gsmet requested changes, later dismissed
I'm not sure that's the right fix.

Isn't the problem that we do not format properly the duration we push to OTel? We need to support the user setting the duration to `5S`. That's supported by Quarkus.

So somehow, we need to make sure that the Duration we have in this field is pushed to OTel in a format OTel can understand.

2023-05-15 13:50 UTC, gsmet commented
@brunobat this comment is mostly for you ^

2023-05-15 14:09 UTC, gsmet commented
Well, my problem with this is that we have a `Duration` in the Quarkus config and that means it can come in a lot of different forms. I'm a bit unsure about how you actually pass the info but the user can set any value that is a valid `Duration`. Or at least that's what we document and how it works everywhere else.

If OTel doesn't support that, we need to format the Duration in a way that is understandable by it.

Sure, we can merge this PR and fix the default value but that won't solve the problem for the user-defined values.

I will remove my `change requested` review for now but I think there's more to it and that it probably warrants a proper issue.

2023-05-15 14:16 UTC, brunobat commented
@gsmet created this: https://github.com/quarkusio/quarkus/issues/33381

2023-05-15 14:17 UTC, merged

2023-05-15 14:18 UTC, gsmet commented
Thanks for raising the issue and providing a PR!