A few requested enhancements to the Ansible guide
quarkusio/quarkus pull request #33527
Opened 2023-05-22 14:14 UTC by rpelisse

See https://github.com/quarkusio/quarkus/issues/33256

2023-05-23 11:34 UTC, gsmet requested changes
Thanks. I spotted a few issues.

Note that using either:
```
NOTE: Your note.
```

or
```
[NOTE]
====
Your note.
====
```
will make the note an Asciidoc note with proper formatting.

2023-05-23 11:34 UTC, gsmet commented on docs/src/main/asciidoc/ansible.adoc
> +Note: the Ansible collection we just installed only supports RHEL, Fedora and other Linux distribution using RPMs. Ansible defines these as "RedHat family". Using the content on other platform (Windo
```suggestion
NOTE: The Ansible collection we just installed only supports RHEL, Fedora, and other Linux distribution using RPMs. Ansible defines these as "Red Hat family". Using the content on other platform (Windows, Debian, Ubuntu, ...), while not impossible, will require a few adjustments.
```

2023-05-23 11:34 UTC, gsmet commented on docs/src/main/asciidoc/ansible.adoc
> +Note: by default the Ansible collection for Quarkus will install and use the OpenJKD 17 available in the Yum repositories of the target host (or the controller). If you wish to use a different versio
```suggestion
NOTE: By default, the Ansible collection for Quarkus will install and use the OpenJDK 17 available in the Yum repositories of the target host (or the controller). If you want to use a different version of OpenJDK, define the following variable:
```

2023-05-23 12:19 UTC, rpelisse commented
@gsmet thanks! I did not realized there was a syntax for that. I also fixed the few typos you mentioned, expect for RedHat family, because that the value used by Ansible:

```
"ansible_os_family": "RedHat",
```

2023-06-06 15:18 UTC, gsmet approved these changes
I pushed an additional commit with some additional tweaks.

2023-06-22 13:40 UTC, merged