Improve log messages related to OIDC session cookie encryption secret
quarkusio/quarkus pull request #33550
Opened 2023-05-23 10:27 UTC by sberyozkin

Fixes #33532.

@geoand Can you please review and help to improve the wording ? No OIDC logic has been affected, only more log messages are added, and the warning is issued when the encryption key strength is low.

@rgmz FYI. 

Note, OIDC code could've avoided falling back to the configured secrets and just generated a random secret but that would increase the risk of the applications being broken (after restarts in devmode, multiple pods) and force users disable the encryption in any case. Seeing a log message is less intrusive. 

What I have also done is to log a warning when the key strength is very low (less than 16 chars) but only debug when the key is strong enough - thatr should improve the experience as the secrets generated by providers will most definitelybe at least 16 characters long. It looks like the warning message can frustrate quite a few users - the whole session cookie encryption is a hardening fix, so for users running securely over HTTPS or internal networks it can be a bit annoying having to go and disable the encryption just to get rid of the warning...

2023-05-23 10:30 UTC, geoand commented on extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java
> +         * Requires that the session cookie storing the tokens is encrypted.
```suggestion
         * Mandates that the session cookie that stores the tokens is encrypted.
```

2023-05-23 10:39 UTC, sberyozkin commented
I'll add another comment as proposed at https://github.com/quarkusio/quarkus/issues/33532#issuecomment-1558079944 after all a bit later :-)

2023-05-23 13:37 UTC, sberyozkin commented
Hi @gsmet @geoand, I'm pinging Pedro to have a quick look, but  if you think it is safe, please approve and may be it might get to 2.13. It is a pure doc clarification and log noise minimization for the out of the box OIDC user experience, no OIDC logic is affected

2023-05-30 08:05 UTC, gsmet requested changes, later dismissed

2023-05-30 11:05 UTC, sberyozkin commented on extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/TenantConfigContext.java
> +                            + " for the strongest cookie encryption be produced."
Hey Guillaume, yeah, I was not sure how to express in a simple way that the key matching the algorithm key size requirements will help producing the strongest encryption, and inevitably I got confused, thanks for fixing it

2023-05-31 15:02 UTC, pedroigor approved these changes

2023-05-31 16:00 UTC, merged