rename update-quarkus.adoc and tweak contents
quarkusio/quarkus pull request #33589
Opened 2023-05-24 20:44 UTC by rolfedh

2023-06-20 16:42 UTC, gsmet requested changes
I added a few suggestions.

2023-06-20 16:42 UTC, gsmet commented on docs/src/main/asciidoc/update-quarkus.adoc
> +// TBD: Rolfe, find out which strategy we want to employ for this link. Use ifdef?
Same comment here.

2023-06-20 16:56 UTC, rolfedh commented on docs/src/main/asciidoc/_attributes.adoc
> +:quarkus-platform-groupid: io.quarkus.platform
Updated. Thanks.

2023-06-20 16:57 UTC, rolfedh commented on docs/src/main/asciidoc/_attributes.adoc
>  :create-app-group-id: org.acme
You're right. I was just in the process of updating it when you gave this useful comment.

2023-06-20 16:57 UTC, rolfedh commented on docs/src/main/asciidoc/update-quarkus.adoc
> +// TBD: Rolfe, find out which strategy we want to employ for this link. Use ifdef?
I've removed these notes to myself.

2023-06-20 16:58 UTC, rolfedh commented on docs/src/main/asciidoc/update-quarkus.adoc
> +// TBD: Rolfe, find out which strategy we want to employ for this include. Use ifdef to include the "developer preview" or "technical preview" snippets?
Removed. Thanks.

2023-06-20 16:58 UTC, rolfedh commented on docs/src/main/asciidoc/update-quarkus.adoc
> +// TBD: Rolfe, find out which strategy we want to employ for this link. Use ifdef?
Removed. Thanks.

2023-06-22 13:47 UTC, gsmet approved these changes

2023-06-22 13:47 UTC, merged

2023-06-22 13:47 UTC, gsmet commented
Thanks!