[open-api] Consider 'mp.openapi.scan.disable' value when scanning annotations
quarkusio/quarkus pull request #3362
Opened 2019-07-29 05:42 UTC by jmini

See issue https://github.com/quarkusio/quarkus/issues/2907

Check the value of `mp.openapi.scan.disable` when computing the OpenAPI specification served by quarkus.

---
As mentioned in https://github.com/quarkusio/quarkus/issues/2907#issuecomment-512247927 if someone can point me the place and the workflow to add some test for this, I am happy to contribute something.

2019-07-29 06:14 UTC, machi1990 commented
Hi @jmini thanks for the contribution. You can take inspiration from tests located here - https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/OpenApiDefaultPathTestCase.java

and here here https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/OpenApiPathWithSegmentsTestCase.java if you want to vary the configuration property.

2019-07-29 08:40 UTC, jmini commented
@machi1990: thank you for the feedback, but this is exactly what I have tried:

---

I wanted to write a test, similar to [OpenApiDefaultPathTestCase](https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/OpenApiDefaultPathTestCase.java).

But when I run this:

```java
private static final String OPEN_API_PATH = "/openapi";

@RegisterExtension
static QuarkusUnitTest runner = new QuarkusUnitTest()
        .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class)
                .addClasses(OpenApiResource.class));

@Test
public void testOpenApiPathAccessResource() {
    String s = RestAssured.given().header("Accept", "application/json")
            .when().get(OPEN_API_PATH)
            .then().extract().asString();

    System.out.println(s);
}
```

I get:

```
RESTEASY003210: Could not find resource for full path: http://localhost:8081/openapi
```

Of course my plan for the test was also to add config files `.addAsManifestResource(..)` and `addAsResource(..)`

---

None of the tests in this module is checking the body of the openapi spec.

---

I have seen other OpenAPI tests called integration tests (in an other module). 

My question is:
_Is that the way to go to check several configurations options?_

2019-07-29 10:44 UTC, machi1990 commented
> ```
> RESTEASY003210: Could not find resource for full path: http://localhost:8081/openapi
> ```

Hmm strange as I do not see how you are getting a not found, this should work 
```
   private static final String OPEN_API_PATH = "/openapi";
    @RegisterExtension
    static QuarkusUnitTest runner = new QuarkusUnitTest()
            .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class)
                    .addClasses(OpenApiResource.class)
                    .addAsResource(new StringAsset("mp.openapi.scan.disable=true"), "application.properties"));
```

2019-07-29 10:46 UTC, machi1990 requested changes

2019-07-29 10:46 UTC, machi1990 commented on extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java
> +        Optional<Boolean> scanDisable = config.getOptionalValue(OASConfig.SCAN_DISABLE, Boolean.class);
```
boolean scanDisable = config.getOptionalValue(OASConfig.SCAN_DISABLE, Boolean.class).orElse(false);
if (resteasyJaxrsConfig.isPresent() && !scanDisable) {
..  
}  else {
...
}    
```

2019-07-29 11:26 UTC, jmini commented
> Hmm strange as I do not see how you are getting a not found, this should work

Have you tried to modify the test in `OpenApiDefaultPathTestCase`:

https://github.com/quarkusio/quarkus/blob/8bc2113789afd8102341c12b131eca3517623487/extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/OpenApiDefaultPathTestCase.java#L1-L17

to:

```java
    @Test
    public void testOpenApiPathAccessResource() {
        String s = RestAssured.given().header("Accept", "application/json")
                .when().get(OPEN_API_PATH)
                .then().extract().asString();

        System.out.println(s);
        Assert.assertTrue(s.contains("\"openapi\":"));
    }
```

What is the content of `s`?

In my case it is not the expected OpenAPI spec, this is why I am asking how I should test my change.

2019-07-29 11:46 UTC, machi1990 commented
> 
> What is the content of `s`?
Yes, I modified the test case.

Here is what I have with the proposed change. 

1. scan.disabled=true
```
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Generated API",
    "version" : "1.0"
  },
  "paths" : { }
}
```

2.scan.disabled=false or not set

```
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Generated API",
    "version" : "1.0"
  },
  "paths" : {
    "/resource" : {
      "get" : {
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/String"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "String" : {
        "type" : "string"
      }
    }
  }
}
```

2019-07-29 15:12 UTC, jmini commented
Thank you a lot, it works only for me from a maven build and not inside Eclipse IDE, but it is OK for me.

2019-07-29 19:36 UTC, jmini commented on extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java
> +        Optional<Boolean> scanDisable = config.getOptionalValue(OASConfig.SCAN_DISABLE, Boolean.class);
Changed

2019-07-30 08:02 UTC, jmini commented
@machi1990 I have pushed a new version with the requested change and some tests… 
Can you review?

2019-07-30 10:33 UTC, machi1990 commented on extensions/smallrye-openapi/deployment/src/test/java/io/quarkus/smallrye/openapi/test/OpenApiWithConfigTestCase.java
> +public class OpenApiWithConfigTestCase {
Maybe rename this to `AnnotationScanDisabledOpenApiTestCase`

2019-07-30 10:34 UTC, machi1990 commented
> @machi1990 I have pushed a new version with the requested change and some tests…
> Can you review?

@jmini thanks. I added a minor comment. Otherwise, LGTM. Maybe one of @kenfinnigan or @gsmet would like to review this also.

2019-07-30 12:33 UTC, kenfinnigan approved these changes

2019-07-30 12:33 UTC, merged