Add Config editor
quarkusio/quarkus pull request #33661
Opened 2023-05-29 00:08 UTC by phillip-kruger

2023-05-29 05:12 UTC, cescoffier requested changes

2023-05-29 05:12 UTC, cescoffier commented on extensions/vertx-http/runtime/src/main/java/io/quarkus/devui/runtime/config/ConfigJsonRPCService.java
> +                ex.printStackTrace();
Use a logger instead

2023-05-29 16:35 UTC, cescoffier approved these changes

2023-06-02 00:37 UTC, phillip-kruger commented
@gsmet @cescoffier The CI error seems unrelated and I can build this on my laptop. Are we ok to merge ?

2023-06-05 06:02 UTC, cescoffier approved these changes

2023-06-05 06:02 UTC, merged