Replace references of s2i with openshift
quarkusio/quarkus pull request #33824
Opened 2023-06-05 09:06 UTC by iocanel

The `container-image-s2i` extension has long been deprecated in favor of `container-image-openshift`. However, our container image documentation is still using the old one. 

This pull requests changes that.

2023-06-06 09:06 UTC, geoand approved these changes

2023-06-06 09:22 UTC, gsmet requested changes
Let's get the case right, please :).

2023-06-06 09:22 UTC, gsmet commented on docs/src/main/asciidoc/container-image.adoc
> +=== Openshift
```suggestion
=== OpenShift
```

2023-06-06 09:22 UTC, gsmet commented on docs/src/main/asciidoc/container-image.adoc
> +- <<#openshift,Openshift>>
```suggestion
- <<#openshift,OpenShift>>
```

2023-06-06 09:22 UTC, gsmet commented on docs/src/main/asciidoc/container-image.adoc
> +The extension `quarkus-container-image-openshift` is using Openshift binary builds in order to perform container builds inside the OpenShift cluster.
```suggestion
The extension `quarkus-container-image-openshift` is using OpenShift binary builds in order to perform container builds inside the OpenShift cluster.
```

2023-06-06 09:22 UTC, gsmet commented on docs/src/main/asciidoc/container-image.adoc
> +Openshift builds require creating a `BuildConfig` and two `ImageStream` resources, one for the builder image and one for the output image.
```suggestion
OpenShift builds require creating a `BuildConfig` and two `ImageStream` resources, one for the builder image and one for the output image.
```

2023-06-06 09:22 UTC, gsmet commented on docs/src/main/asciidoc/container-image.adoc
> +=== Openshift  Options
```suggestion
=== OpenShift  Options
```

2023-06-06 09:22 UTC, gsmet commented on docs/src/main/asciidoc/container-image.adoc
> +:summary: Learn how to build and push container images with Jib, Openshift or Docker as part of the Quarkus build.
```suggestion
:summary: Learn how to build and push container images with Jib, OpenShift or Docker as part of the Quarkus build.
```

2023-06-07 11:09 UTC, gsmet approved these changes

2023-06-07 11:09 UTC, gsmet commented
LGTM now, I squashed the commits and force pushed.

2023-06-08 06:47 UTC, merged