Fix parameter validation issue in classic rest-client
quarkusio/quarkus pull request #33918
Opened 2023-06-08 21:00 UTC by kahowell

URL parsing inside of `QuarkusRestClientBuilder.verifyInterface` used `ResteasyUriBuilderImpl.uri`, which works for most cases, but parsed in subtly wrong ways when the constructed path started with `//`. For example, a path of `//{id}` parses `{id}` as the hostname. Such a path was possible to trigger by a couple of scenarios:

1. Interface has `@Path("")`, and a method-level `@Path` value starting with `/`.
2. Interface has `@Path("/")`, and a method-level `@Path` value not starting with `/`.

Furthermore, if the first path component contained a path param, then it would not be counted, leading to incorrect validation results.

Fixes: #33915

2023-06-13 13:29 UTC, Sgitario requested changes
Can you add the same test in the REST Client Reactive extension? 
I could not confirm that after these changes, the reproducer in the linked issue behaved the same in the classic and the reactive REST clients.

2023-06-21 05:40 UTC, Sgitario commented
> @Sgitario I added a test for rest-client-reactive as requested. Please take another look when you have a chance.

Many thanks! You need to build the modules you changed using Maven, so the files get formatted, (`mvn clean install` will do it). Also, squash all the commits, so we can proceed with the merge after CI is green.

2023-06-21 17:15 UTC, kahowell commented
d0f6637 to 8c0e055: use `./mvnw process-sources` to fix formatting, rebase against main

2023-06-22 07:10 UTC, Sgitario approved these changes

2023-06-22 07:11 UTC, merged