Add optional native flag to build PIE binaries
quarkusio/quarkus pull request #33931
Opened 2023-06-09 09:44 UTC by galderz

Closes #33524. Adds `quarkus.native.pie` configuration option. Usage and verification:

```
$ mvn package -Dquarkus.native.pie=true -Dnative
...
file getting-started/target/getting-started-1.0.0-SNAPSHOT-runner
getting-started/target/getting-started-1.0.0-SNAPSHOT-runner: ELF 64-bit LSB pie executable, ...
```

Compared with:

```
$ mvn package -Dnative
file getting-started/target/getting-started-1.0.0-SNAPSHOT-runner
getting-started/target/getting-started-1.0.0-SNAPSHOT-runner: ELF 64-bit LSB executable, ...
```

Commits need squashing once review passes.

@zakkak is away so maybe @Karm or @jerboaa can review?

2023-06-12 05:48 UTC, galderz commented
The JVM test failure is unrelated.

2023-06-13 13:17 UTC, jerboaa approved these changes
Seems OK to me.

2023-06-20 16:54 UTC, gsmet reviewed
I added a suggestion and in any case could you squash the commits?

2023-06-20 16:54 UTC, gsmet commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java
> +     * Explicit configuration option to generate PIE native binaries.
I'm not sure I understand when PIE will be enabled, especially when this is not set. I think we should make it more explicit in the doc.

2023-06-23 08:10 UTC, zakkak requested changes
LGTM, other than the documentation part (see my suggestion)

2023-06-23 08:10 UTC, zakkak commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java
> +     * Explicit configuration option to generate PIE native binaries.
I agree with @gsmet that a more explicit (and consistent with the rest) documentation is needed.

```suggestion
     * If this build should build a Position Independent Executable (PIE). Not setting the option results in using the
     * underlying system's defaults.
```

2023-06-27 04:43 UTC, galderz commented
@gsmet @zakkak I've pushed an update for the javadoc option. How does that sound now?

2023-06-27 11:21 UTC, zakkak requested changes
I still don't find the doc clear enough. Added some suggestions.

2023-06-27 11:21 UTC, zakkak commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java
> +     * If the system supports, the default behaviour is to generate native binaries without PIE for
If the system supports what?

I suggest:
```suggestion
     * If the system we are building on supports PIE generation, the default behaviour is to disable it 
```

2023-06-27 11:21 UTC, zakkak commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java
> +     * so this option offers the opportunity to generate native executables with PIE instead.
Avoid redundant "executable" and reduce words:
```suggestion
     * Some systems, however, only support platform independent executables (PIEs),
     * this option enables the generation of such  native executables.
```

2023-06-28 09:42 UTC, galderz commented
Pushed another round of updates for the PIE option javadoc.

2023-06-28 11:50 UTC, zakkak approved these changes
LGTM, thanks @galderz

2023-06-28 16:39 UTC, galderz commented
Thx @zakkak. Squashed the commits and pushed.

2023-07-21 07:53 UTC, galderz commented
Rebased to resolve conflict. Can someone integrate this?

2023-07-21 19:16 UTC, merged

2023-07-21 19:17 UTC, zakkak commented
@galderz do you think it's worth backporting to 3.2?

2023-07-24 07:15 UTC, galderz commented
@zakkak Yeah I think it's worth it. I'll send a PR for it.

2023-07-24 07:26 UTC, zakkak commented
> See #34944 for the 3.2.x backport.

I added the `triage/backport?` label so that it doesn't get accidentally missed