ArC: implment equals/hashCode for TypeVariableImpl and WildcardTypeImpl
quarkusio/quarkus pull request #34098
Opened 2023-06-16 13:36 UTC by mkouba

2023-06-16 14:23 UTC, Ladicek requested changes
The hash functions here are not consistent with the JDK `TypeVariable` and `WildcardType` implementations. I know these are not a public contract, but it's the only sensible implementation, otherwise a type obtained from a `TypeLiteral` won't be usable. Guava for example does the same thing, see https://github.com/google/guava/blob/master/guava/src/com/google/common/reflect/Types.java

2023-06-16 14:25 UTC, Ladicek commented
Also, `equals` shouldn't assume that the other object is of the same class. Our `WildcardTypeImpl` must be equal to the corresponding wildcard type obtained e.g. again from `TypeLiteral`.

2023-06-16 20:53 UTC, mkouba commented
> Also, `equals` shouldn't assume that the other object is of the same class. Our `WildcardTypeImpl` must be equal to the corresponding wildcard type obtained e.g. again from `TypeLiteral`.

I'm not sure I'm following. We don't test that the `WildcardTypeImpl`  is of the same class but it must implement `WildcardType`... which is what Guava does as well.

2023-06-19 06:37 UTC, Ladicek commented
OK, my bad, the `equals` methods are fine. I probably got confused by the tests that only use our implementations of types. We could use `TypeLiteral` to obtain JDK implementations of types to test, for extra bonus points :-)

2023-06-19 07:05 UTC, mkouba commented
@Ladicek There's a problem with `io.quarkus.arc.impl.TypeVariableImpl.hashCode()` though - JDK/guava do use `genericDeclaration.hashCode() ^ name.hashCode()` but we don't support `genericDeclaration` at all. The same applies to `equals()`, bounds are ignored but the `name` and `genericDeclaration` are considered...

2023-06-19 09:26 UTC, Ladicek commented on independent-projects/arc/runtime/src/test/java/io/quarkus/arc/impl/ParameterizedTypeImplTest.java
> +        assertNotEquals(parameterizedType3, parameterizedType1);
Hash code for the 2nd and 3rd case, similarly to the 1st case?

2023-06-19 09:26 UTC, Ladicek approved these changes

2023-06-19 09:53 UTC, manovotn approved these changes

2023-06-19 10:26 UTC, Ladicek approved these changes

2023-06-19 15:58 UTC, merged