Add summary section for local kubernetes
quarkusio/quarkus pull request #34157
Opened 2023-06-20 09:35 UTC by iocanel

For some people it seems that the options for local kubernetes deployment are not obvious. So, let's add a section that summarizes the options for local kubernetes deployment and leads in to the sections for minikube and kind.

2023-06-20 09:56 UTC, geoand approved these changes

2023-06-20 13:36 UTC, gsmet requested changes
Spotted a few things that need fixing.

2023-06-20 13:36 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-kubernetes.adoc
> +If the list of extensions does not match the tool you are using (e.g. docker desktop, microk8s etc) then its suggested to use the `quarkus-minikube` extension
```suggestion
If the list of extensions does not match the tool you are using (e.g. Docker Desktop, microk8s etc) then it is suggested to use the `quarkus-minikube` extension.
```

2023-06-20 13:36 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-kubernetes.adoc
> +as it's default should be reasonable for most environments.
```suggestion
as its defaults should be reasonable for most environments.
```

2023-06-20 13:36 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-kubernetes.adoc
> +When deploying to local Kubernetes environments users often perform minor changes to their manifests that simplify the development process.
```suggestion
When deploying to local Kubernetes environments, users often perform minor changes to their manifests that simplify the development process.
```

2023-06-22 09:53 UTC, iocanel commented
@gsmet: applied your commits and squashed them. Thanks!

2023-09-22 14:00 UTC, gsmet approved these changes
Very nice, thanks!

2023-09-22 14:28 UTC, merged

2023-09-22 14:29 UTC, gsmet commented
I squashed the commits before merging.