Add @ClientFormParam to Reactive REST Client
quarkusio/quarkus pull request #34535
Opened 2023-07-05 01:51 UTC by Eng-Fouad

Resolves #34477

2023-07-05 07:41 UTC, Sgitario requested changes
The changes look amazing to me. Many thanks!
The only missing part is to update the documentation similar to what is mentioned to `@ClientQueryParam`: https://quarkus.io/guides/rest-client-reactive#using-clientqueryparam

I'm also running the CI.

2023-07-05 08:39 UTC, Sgitario commented
The test failures do seem related.

2023-07-06 05:02 UTC, Sgitario commented
I'm having a look into the test failures

2023-07-06 05:45 UTC, Sgitario commented
> I'm having a look into the test failures

The message was indeed misleading, though when running the test on debug mode, you add a breakpoint [here](https://github.com/quarkusio/quarkus/blob/8a0624822e522cd438781ee786355a1ce41d7f54/extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/JaxrsClientReactiveProcessor.java#L395), you will see the actual errors.

The problem is that the issue is found in the SubClient and that's why it could not identify the errors.

Anyway, the actual errors are:
- there are a couple of null pointers because formValues is null [here](https://github.com/quarkusio/quarkus/pull/34535/files#diff-3bf496e685c85459b6ad2b94694f39720676248db75e1bd2694cb9a21d9dc69bR541) and [here](https://github.com/quarkusio/quarkus/pull/34535/files#diff-3bf496e685c85459b6ad2b94694f39720676248db75e1bd2694cb9a21d9dc69bR435).
- the method definition in [here](https://github.com/quarkusio/quarkus/pull/34535/files#diff-3bf496e685c85459b6ad2b94694f39720676248db75e1bd2694cb9a21d9dc69bR131) is not correct, I think it should be:

```java
private static final MethodDescriptor MULTI_VALUED_MAP_ADD_ALL_METHOD = MethodDescriptor.ofMethod(MultivaluedMap.class,
            "addAll", void.class, Object.class, List.class);
```

After making these changes, still didn't work for me because the following exception at runtime:

```
java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    io/quarkus/rest/client/reactive/form/ClientFormParamFromMethodTest$Client$$QuarkusRestClientInterface.setFromFormParam(Ljava/lang/String;)Ljava/lang/String; @116: aload
  Reason:
    Type top (current frame, locals[6]) is not assignable to reference type
  Current Frame:
    bci: @116
    flags: { }
    locals: { 'io/quarkus/rest/client/reactive/form/ClientFormParamFromMethodTest$Client$$QuarkusRestClientInterface', 'java/lang/String', 'java/lang/reflect/Type', '[Ljava/lang/annotation/Annotation;', 'jakarta/ws/rs/core/MultivaluedMap', top, top, top, top, top, top, top, 'jakarta/ws/rs/client/WebTarget' }
    stack: { }
  Bytecode:
```

But I hope you can continue investigating after my findings.

2023-07-06 05:46 UTC, Sgitario requested changes
See my inline comments and last comment to fix the test failures.

2023-07-06 05:46 UTC, Sgitario commented on extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/MicroProfileRestClientEnricher.java
> +        String queryName = annotation.value("name").asString();
Please, rename it to `formName`

2023-07-06 05:46 UTC, Sgitario commented on extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/MicroProfileRestClientEnricher.java
> +        ResultHandle queryNameHandle = methodCreator.load(queryName);
Please, rename it to `formNameHandle`

2023-07-06 17:49 UTC, Eng-Fouad commented
Merged with latest commit from main branch, and now I am getting new error:

```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /mnt/c/Users/fouad/IdeaProjects/quarkus-fouad/extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/RestClientReactiveProcessor.java:[531,24] method isImplementorOf in class org.jboss.resteasy.reactive.common.processor.JandexUtil cannot be applied to given types;
  required: org.jboss.jandex.IndexView,org.jboss.jandex.ClassInfo,org.jboss.jandex.DotName
  found:    org.jboss.jandex.CompositeIndex,org.jboss.jandex.ClassInfo,org.jboss.jandex.DotName,java.util.Set<org.jboss.jandex.DotName>
  reason: actual and formal argument lists differ in length
```

I think it is caused by #34570 cc @geoand

2023-07-06 17:52 UTC, geoand commented
You need to rebased on main

2023-07-06 18:16 UTC, Eng-Fouad commented
> You need to rebased on main and update the code

Already did that. Same error.

2023-07-06 18:17 UTC, Eng-Fouad commented
> > I'm having a look into the test failures
> 
> The message was indeed misleading, though when running the test on debug mode, you add a breakpoint [here](https://github.com/quarkusio/quarkus/blob/8a0624822e522cd438781ee786355a1ce41d7f54/extensions/resteasy-reactive/jaxrs-client-reactive/deployment/src/main/java/io/quarkus/jaxrs/client/reactive/deployment/JaxrsClientReactiveProcessor.java#L395), you will see the actual errors.
> 
> The problem is that the issue is found in the SubClient and that's why it could not identify the errors.
> 
> Anyway, the actual errors are:
> 
> * there are a couple of null pointers because formValues is null [here](https://github.com/quarkusio/quarkus/pull/34535/files#diff-3bf496e685c85459b6ad2b94694f39720676248db75e1bd2694cb9a21d9dc69bR541) and [here](https://github.com/quarkusio/quarkus/pull/34535/files#diff-3bf496e685c85459b6ad2b94694f39720676248db75e1bd2694cb9a21d9dc69bR435).
> * the method definition in [here](https://github.com/quarkusio/quarkus/pull/34535/files#diff-3bf496e685c85459b6ad2b94694f39720676248db75e1bd2694cb9a21d9dc69bR131) is not correct, I think it should be:
> 
> ```java
> private static final MethodDescriptor MULTI_VALUED_MAP_ADD_ALL_METHOD = MethodDescriptor.ofMethod(MultivaluedMap.class,
>             "addAll", void.class, Object.class, List.class);
> ```
> 
> After making these changes, still didn't work for me because the following exception at runtime:
> 
> ```
> java.lang.VerifyError: Bad local variable type
> Exception Details:
>   Location:
>     io/quarkus/rest/client/reactive/form/ClientFormParamFromMethodTest$Client$$QuarkusRestClientInterface.setFromFormParam(Ljava/lang/String;)Ljava/lang/String; @116: aload
>   Reason:
>     Type top (current frame, locals[6]) is not assignable to reference type
>   Current Frame:
>     bci: @116
>     flags: { }
>     locals: { 'io/quarkus/rest/client/reactive/form/ClientFormParamFromMethodTest$Client$$QuarkusRestClientInterface', 'java/lang/String', 'java/lang/reflect/Type', '[Ljava/lang/annotation/Annotation;', 'jakarta/ws/rs/core/MultivaluedMap', top, top, top, top, top, top, top, 'jakarta/ws/rs/client/WebTarget' }
>     stack: { }
>   Bytecode:
> ```
> 
> But I hope you can continue investigating after my findings.

Thanks for your help. I applied all fixes you mentioned. I will try to figure out how to fix `java.lang.VerifyError: Bad local variable type`.

2023-07-06 19:04 UTC, Eng-Fouad commented
> You need to rebased on main and update the code

My bad. I had to recompile the project again.

2023-07-06 22:51 UTC, Eng-Fouad commented
Ok, I fixed `java.lang.VerifyError: Bad local variable type`. However, the tests still fail:

```
[ERROR] Failures:
[ERROR]   ClientFormParamFromMethodTest.shouldUseValuesOnlyFromClass:39
expected: "1/"
 but was: "/"
[INFO]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

It seems that the form params are not passed in the request.

2023-07-06 23:37 UTC, Eng-Fouad commented
Fixed. All tests should pass now.

2023-07-07 08:28 UTC, Sgitario requested changes
There are several concerns about the implementation:
- Generally speaking, we should be very careful when changing the signature of interfaces like JaxrsClientReactiveEnricher. In this case, we can avoid it (see the following points)
- `JaxrsClientReactiveEnricher.forWebTarget` and `JaxrsClientReactiveEnricher.forSubResourceWebTarget` is meant to enrich the webTarget and when handling the form params, we are not updating the web target. 
- You're using an array to hold a single instance of formParams (as if you were passing a reference parameter). 

To avoid these three points, I would create a new method in JaxrsClientReactiveEnricher like `handleFormParams` that returns the assignable result handle (to avoid the usage of arrays for doing this). 

Other comments:

- The method `MicroProfileRestClientEnricher.addFormParam` is too long and I think it can be refactored (eg reusing variables, etc).
- There are several conditions like `if (!multipart)`, I don't fully understand why you ended up with this condition, but form params are not incompatible with multipart. I guess your intention here is not to parse the annotations that are used in Multipart classes? If this scenario is not supported, we should throw an exception to let users that this is not a valid use case. If this was not your intention, I would need further clarification about this to better understand the condition.

2023-07-07 20:44 UTC, Eng-Fouad commented
> There are several concerns about the implementation:
> 
> * Generally speaking, we should be very careful when changing the signature of interfaces like JaxrsClientReactiveEnricher. In this case, we can avoid it (see the following points)
> * `JaxrsClientReactiveEnricher.forWebTarget` and `JaxrsClientReactiveEnricher.forSubResourceWebTarget` is meant to enrich the webTarget and when handling the form params, we are not updating the web target.
> * You're using an array to hold a single instance of formParams (as if you were passing a reference parameter).
> 
> To avoid these three points, I would create a new method in JaxrsClientReactiveEnricher like `handleFormParams` that returns the assignable result handle (to avoid the usage of arrays for doing this).
> 

I agree with you, using separate method `handleFormParams` is much better. I will do that.

> Other comments:
> 
> * The method `MicroProfileRestClientEnricher.addFormParam` is too long and I think it can be refactored (eg reusing variables, etc).

Do you mean like merging `addFormParam` with `addQueryParam` (e.g. new method `addParam`) and then pass method argument that specifies param type?

> * There are several conditions like `if (!multipart)`, I don't fully understand why you ended up with this condition, but form params are not incompatible with multipart. I guess your intention here is not to parse the annotations that are used in Multipart classes? If this scenario is not supported, we should throw an exception to let users that this is not a valid use case. If this was not your intention, I would need further clarification about this to better understand the condition.

In case of multipart, `forParams` is `QuarkusMultipartForm` not `MultivaluedHashMap`. With `MultivaluedHashMap`, we can simply add it as follows:

```
forParams.addAll(annotation.name(), Arrays.asList(annotation.value()));
```

However, with `QuarkusMultipartForm`, should I use `attribute(String name, String value, String filename)`? How to construct `filename`?

2023-07-20 11:28 UTC, Eng-Fouad commented
@geoand @Sgitario Any updates on this PR? Thanks.

2023-07-20 11:29 UTC, geoand commented
@Sgitario is on PTO, so let's wait for him to have the final say

2023-07-24 07:43 UTC, Sgitario reviewed
Back from my PTO. Only two comments to address. 
The rest of the changes look good to me. Thanks!

2023-07-24 07:43 UTC, Sgitario commented on extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/MicroProfileRestClientEnricher.java
> +                CLIENT_QUERY_PARAM, CLIENT_QUERY_PARAMS, "ClientQueryParam");
Please, move "ClientQueryParam" into a constant and/or provide a custom collectClientParamData method only for query params.

2023-07-24 07:43 UTC, Sgitario commented on extensions/resteasy-reactive/rest-client-reactive/deployment/src/main/java/io/quarkus/rest/client/reactive/deployment/MicroProfileRestClientEnricher.java
> +                CLIENT_FORM_PARAM, CLIENT_FORM_PARAMS, "ClientFormParam");
Please, move "ClientFormParam" into a constant and/or provide a custom collectClientParamData method only for form params.

2023-07-24 20:48 UTC, Eng-Fouad commented
> Back from my PTO. Only two comments to address. The rest of the changes look good to me. Thanks!

Welcome back. I updated the code according to your comments. Thanks.

2023-07-25 05:14 UTC, Sgitario approved these changes

2023-07-25 05:16 UTC, merged