Remove Old Dev UI: Datasource
quarkusio/quarkus pull request #34974
Opened 2023-07-25 02:58 UTC by phillip-kruger

This PR removes the old Dev UI from the datasource extension

2023-07-25 07:08 UTC, cescoffier commented
The CI failures are related.

2023-07-25 07:08 UTC, cescoffier requested changes
The CI issues are related.

2023-07-26 06:47 UTC, phillip-kruger commented
@cescoffier I rebased, let see what CI do

2023-07-26 07:31 UTC, cescoffier approved these changes

2023-07-27 03:39 UTC, merged