Narayana JTA: do not allow to use datasource XA transactions with JDBC object store
quarkusio/quarkus pull request #34996
Opened 2023-07-25 12:16 UTC by michalvavrik

closes: #33715

2023-07-26 17:32 UTC, gsmet requested changes
Thanks!

I'm not completely convinced by your approach of reading the configuration this way. I think we should add more info in the build item instead.

I will have a look tomorrow and add a commit to discuss this with you as it's going to be easier with some code.

2023-07-26 17:33 UTC, michalvavrik commented
Sure @gsmet , thanks.

2023-07-27 06:18 UTC, zhfeng approved these changes
Thanks @michalvavrik and these changes look good to me!. It could be better if we can find a easier way to read the configurations at build time.

2023-07-27 14:23 UTC, gsmet commented
@michalvavrik I rebased and pushed 2 additional commits. Let me know what you think.

(I haven't run all the tests, only those of Agroal and Narayana, we will see how it goes :))

2023-07-27 14:34 UTC, michalvavrik commented
I agree this is better than my version, I only mentioned one unused method parameter (please see comment). Tell me how to fix it (if you want to resolve it yourself, please do). Glad for your help.

2023-07-27 14:45 UTC, gsmet commented
Ah, yes, I'll fix it later today.

2023-07-28 09:45 UTC, gsmet commented
@michalvavrik sorry for the delay, I fixed the remaining issue, rebased and force pushed.

2023-07-28 12:30 UTC, michalvavrik commented
@gsmet I think OTEL failure is related, I am busy today, but I will look into it tomorrow unless you solve it first.

2023-07-28 12:46 UTC, gsmet commented
I don't see any dependency to Narayana or Datasource in this test but there might be something given it was triggered by GIB.

I have no idea how it could be related though. I will be busy on other things too so I let you have a look when you have some time. There's nothing pressing that requires you to have a look tomorrow, you can have a look on Monday.

2023-07-28 12:48 UTC, gsmet commented
It's failing here too: https://github.com/quarkusio/quarkus/pull/35067 so it's not related, I think we can merge.

2023-07-28 12:48 UTC, gsmet approved these changes

2023-07-28 12:49 UTC, merged