fix: delete on neo4j-guide
quarkusio/quarkus pull request #3524
Opened 2019-08-14 21:10 UTC by barata0

fixes #3523

2019-08-14 21:37 UTC, gsmet commented
@michael-simons can you have a look? Thanks!

2019-08-15 18:21 UTC, michael-simons commented
Hi, totally my bad, @barata0 is correct.

2019-08-15 18:28 UTC, michael-simons requested changes
Please see inline comment. Thanks.

2019-08-15 18:28 UTC, michael-simons commented on docs/src/main/asciidoc/neo4j-guide.adoc
> +            tx.runAsync("MATCH (a:Fruit) WHERE id(a) = $id DETACH DELETE a", Values.parameters("id", id))
```suggestion
            tx.runAsync("MATCH (f:Fruit) WHERE id(f) = $id DELETE f", Values.parameters("id", id))
```

2019-08-15 18:28 UTC, michael-simons commented on docs/src/main/asciidoc/neo4j-guide.adoc
> +            tx.runAsync("MATCH (a:Fruit) WHERE id(a) = $id DETACH DELETE a", Values.parameters("id", id))
I'd prefer that we use the same alias as in the other statements.

Your completely right in regards of the `DETACH` modifier, but as we didn't create relations, I'd rather keep it simple. If I remember correctly, I had the statement include the detach, but probably broke it when removing it. Embarrassing.

2019-08-16 08:41 UTC, gsmet approved these changes

2019-08-16 08:41 UTC, merged

2019-08-16 08:41 UTC, gsmet commented
Thanks!