Add Stargazers in Readme.md
quarkusio/quarkus pull request #35330
Opened 2023-08-12 16:56 UTC by shivam-sharma7

2023-08-12 16:58 UTC, shivam-sharma7 commented
@gsmet @gastaldi

2023-08-12 17:58 UTC, gastaldi commented
Cool, but I'd prefer having a single badge showing how many stars the repository has instead

2023-08-13 04:33 UTC, shivam-sharma7 commented
> Cool, but I'd prefer having a single badge showing how many stars the repository has instead.
> 
> Eg. ![GitHub Repo stars](https://camo.githubusercontent.com/98b4d2b589df06f1ff97c696cf1d7e4051883e166f9cf1b08fc16fba3366c11b/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f73746172732f717561726b7573696f2f717561726b7573)

@gastaldi should I add this in same place or on the Top where  all badges are present?

2023-08-13 04:59 UTC, gastaldi commented
Probably next to the other badges, with the same Look'n Feel

2023-08-13 05:35 UTC, shivam-sharma7 commented
@gastaldi see

2023-08-13 15:00 UTC, gastaldi commented on README.md
> +[![GitHub Repo stars](https://img.shields.io/github/stars/quarkusio/quarkus?style=for-the-badge)](https://img.shields.io/github/stars/quarkusio/quarkus)
```suggestion
[![GitHub Repo stars](https://img.shields.io/github/stars/quarkusio/quarkus?style=for-the-badge)](https://github.com/quarkusio/quarkus/stargazers)
```

2023-08-13 15:01 UTC, gastaldi requested changes
Pease squash your commits before we merge this

2023-08-15 14:47 UTC, gastaldi commented
LGTM, but I think the commit and the PR title need to be reworded?

2023-08-15 15:27 UTC, shivam-sharma7 commented
> LGTM, but I think the commit and the PR title need to be reworded?

@gastaldi any suggetion for `commit` and `tittle`

2023-08-15 15:45 UTC, shivam-sharma7 commented
@gastaldi done!

2023-08-15 16:07 UTC, gastaldi approved these changes

2023-08-15 16:08 UTC, merged