Override Oracle JDBC native-image metadata only when native image is used
quarkusio/quarkus pull request #35403
Opened 2023-08-17 13:55 UTC by mabartos

Closes #35402

2023-08-17 13:57 UTC, mabartos commented on extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/OracleMetadataOverrides.java
>                  Collections.singleton("oracle/nativeimage/Target_java_io_ObjectStreamClass.class"));
The `oracle/nativeimage/Target_java_io_ObjectStreamClass.class` is not part of the most recent Oracle JDBC Driver 23.2.0.0. Should it be removed, or is there any support for backward-compatible JDBC drivers?

2023-08-17 16:12 UTC, gsmet requested changes
Thanks. I added a few comments.

I don't think we want to make all of them specifically marked for native only as most of them will automatically be executed only for native. But I agree it would be better to add it for the methods producing `RemovedResourceBuildItem` which are executed always.

2023-08-17 16:12 UTC, gsmet commented on extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/OracleMetadataOverrides.java
>      void build(BuildProducer<ReflectiveClassBuildItem> reflectiveClass) {
I would expect these to be executed only when in native as `ReflectiveClassBuildItem` is only consumed in native.

2023-08-21 10:37 UTC, mabartos reviewed
@gsmet @Sanne The PR is ready to review. Just need to clarify one thing below. Thanks

2023-08-21 10:37 UTC, mabartos commented on extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/OracleMetadataOverrides.java
> -    }
The `oracle/nativeimage/Target_java_io_ObjectStreamClass.class` is not part of the most recent Oracle JDBC Driver 23.2.0.0. Should it be removed, or is there any support for backward-compatible JDBC drivers?

@gsmet @Sanne WDYT?

2023-08-21 13:15 UTC, yrodiere commented
> I don't think we want to make all of them specifically marked for native only as most of them will automatically be executed only for native. But I agree it would be better to add it for the methods producing `RemovedResourceBuildItem` which are executed always.

Well considering the whole class is about native image, we could just slap a `@BuildSteps(onlyIf = NativeOrNativeSourcesBuild.class)` at the class level: that would work and we'd never have to worry about it anymore.

But I suppose targeting just the few methods that matter like @gsmet requested works too :shrug: 

(No no I'm not trying to sell [my](https://github.com/quarkusio/quarkus/commit/c2eecd749d12f9bdc01209e210a37672b47ed3e0) lovely `@BuildSteps` annotation :D)

2023-08-22 10:33 UTC, mabartos commented
@yrodiere Yes, also a possible solution.

@gsmet @Sanne Any preference?

2023-08-23 09:03 UTC, gsmet commented
@mabartos sorry for the delay. I think @yrodiere 's suggestion of using `@BuildSteps` at the top of the class and drop the method annotations makes the most sense.

2023-08-23 09:22 UTC, mabartos commented
@gsmet Done

2023-08-23 09:51 UTC, yrodiere approved these changes
LGTM.

I also checked and [this change](https://github.com/quarkusio/quarkus/pull/35403/files#r1299933629) should work on Quarkus 3.2/3.3 as well, since those also use oracle-jdbc 23.2.0.0.

2023-08-23 10:00 UTC, mabartos commented on extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/OracleMetadataOverrides.java
> -    }
@yrodiere ok

If possible, it'd be great to backport it to Quarkus 3.2.

2023-08-23 10:12 UTC, gsmet commented
@yrodiere so we need to backport it, right?

2023-08-23 10:20 UTC, yrodiere commented
> @yrodiere so we need to backport it, right?

#35402 seems to affect 3.2/3.3 as well, so I'd say we do, yes.

2023-08-23 10:38 UTC, gsmet requested changes, later dismissed

2023-08-23 10:38 UTC, gsmet commented on extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/OracleMetadataOverrides.java
> +@BuildStep(onlyIf = NativeOrNativeSourcesBuild.class)
```suggestion
@BuildSteps(onlyIf = NativeOrNativeSourcesBuild.class)
```

2023-08-23 10:44 UTC, mabartos commented on extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/OracleMetadataOverrides.java
> +@BuildStep(onlyIf = NativeOrNativeSourcesBuild.class)
@gsmet Oops, you're right

2023-08-23 12:37 UTC, merged