Fix "my second guide" title, and cross-link
quarkusio/quarkus pull request #35571
Opened 2023-08-25 17:55 UTC by holly-cummins

I don't know how we didn't notice this in preview, but despite having a title, the title for ["my second application"](https://quarkus.io/guides/getting-started-dev-services) is generated nonsense: 

<img width="675" alt="image" src="https://github.com/quarkusio/quarkus/assets/11509290/db117275-77ad-4f57-8976-02543aa394a2">

The adoc looks fine in an adoc editor, so I'm not sure what's wrong. I've tried removing the id to see if that helps. 

I've also cross-linked from the first application guide to the second application guide.

2023-08-25 18:52 UTC, gsmet commented
Let me do some experiments on the website before merging this.

2023-08-25 19:04 UTC, gsmet requested changes

2023-08-25 19:04 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-dev-services.adoc
> -[id="getting-started-dev-services-tutorial"]
You can keep that, what you need is to get rid of the new line above.

See https://github.com/quarkusio/quarkusio.github.io/commit/a30a2d57989e994f2c90b57468ed52fad8f87116 and https://quarkus.io/guides/getting-started-dev-services

2023-09-20 07:39 UTC, gsmet approved these changes
I fixed the issue, it should be good to go now.

2023-09-20 07:57 UTC, holly-cummins commented
Thank you, @gsmet!

2023-09-20 08:36 UTC, merged