Exclude new GraalVM dependencies that are part of GraalVM/Mandrel
quarkusio/quarkus pull request #35873
Opened 2023-09-12 10:37 UTC by zakkak

https://github.com/oracle/graal/pull/7171 splits graal-sdk in 4 new
modules/artifacts. As a result starting with GraalVM for JDK 21 (23.1)
we need to remove those as well. Note that it's OK to have them marked
for removal even when using GraalVM < 23.1 despite them not actually
being present.

Closes https://github.com/quarkusio/quarkus/issues/35872

2023-09-12 13:18 UTC, zakkak commented
@jerboaa please review

2023-09-12 13:23 UTC, geoand approved these changes

2023-09-12 13:34 UTC, jerboaa requested changes
Almost. We need to account for the fact that `polyglot` is part of the dependencies too.

2023-09-12 14:18 UTC, zakkak commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java
> +            removedArtifacts.add("org.graalvm.sdk:collections");
Done

2023-09-12 14:21 UTC, jerboaa commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java
> +            removedArtifacts.add("org.graalvm.sdk:collections");
Thanks!

2023-09-12 14:21 UTC, jerboaa approved these changes

2023-09-12 14:21 UTC, jerboaa commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java
> +                classLoadingConfig.removedArtifacts = Optional.of(new ArrayList<>(5));
Nit: s/5/6/

2023-09-13 06:47 UTC, zakkak commented
`Native Tests - Virtual Thread - Main` times out, but I fail to see how it could be caused by this PR.

2023-09-13 07:30 UTC, merged