Add default tests when creating an extension with Maven Mojo
quarkusio/quarkus pull request #3595
Opened 2019-08-20 12:44 UTC by danielpetisme

Here is a proposal for #3585 

The only basic task we could do is ensure the extension is properly loaded (by scanning the startup output or programatically.

WDYT?

@gwenneg taked also to test hot reloading, I'm not sure to understand the goal.

2019-08-20 12:50 UTC, gwenneg commented
You'll find more info about hot reload tests here: https://quarkus.io/guides/extension-authors-guide#testing-hot-reload

This was introducer in Quarkus `0.21.0` and should be used in all extensions.

2019-08-20 13:16 UTC, danielpetisme commented
Thanks for the quick reply. I missed that point.

Open question, can we consider that the majority of the extensions will require HTTP and generate an opinionated  `Processor` which produce a Servlet + the corresponding `ProcessorTest` which will start the app in dev mode, verify the HTTP endpoint and verify hot reload.

It implies an opinionated vision but have the benefits to drive new extension development. That means **undertow-extension** and **Restassured** added by default in all the created extension.

Thoughts?

2019-08-20 17:24 UTC, gsmet commented
I don't know, I wouldn't clutter the template too much, tbh.

2019-08-20 18:11 UTC, danielpetisme commented
Me too...
I would like to provide a consistent experience between Quarkus app and extension generation:
- When generating an extension I should be able to run a smoke test right away

-  Enforce best practices (Like testing hot reloading for instance)

- Be self-documented/intuitive, the `FeatureBuildItem` is easy to understand and a simple test would be also helpful. 

I admit these objectives are to simple, there is a trade off to find.

Shall we only limit the current PR to the structure creation as is and complete the generation later on with more developer feedbacks?

2019-08-25 08:15 UTC, cescoffier requested changes
The templates should be kept minimal. So they are good right now.
However, generating comments so the user knows where hacking is required may significantly improve the experience.

2019-08-25 08:15 UTC, cescoffier commented on devtools/maven/src/test/resources/expected/create-extension-pom-minimal/minimal-extension/deployment/src/test/java/org/acme/my/project/minimal/extension/deployment/MinimalExtensionProcessorTest.java
> +        .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class));
Can you add comments to explain what the user should do in this code?

2019-08-26 09:24 UTC, cescoffier commented
@danielpetisme also, you would need to rebase your PR.

2019-08-26 11:24 UTC, danielpetisme commented
WDYT of [these comments].(https://github.com/quarkusio/quarkus/blob/3e08ec268c23bbe68555aaed252c0462c2b9672b/devtools/maven/src/main/resources/create-extension-templates/ProcessorTest.java)

2019-08-27 07:20 UTC, danielpetisme commented
@cescoffier rebase done.

2019-10-14 10:22 UTC, machi1990 commented
@danielpetisme hi, we have tests failing, since the Azure artifacts expired I cannot tell if it is related or not. Do you mind having a look?

2019-11-12 15:49 UTC, cescoffier commented
@danielpetisme ping? ^^^

2019-11-13 14:37 UTC, danielpetisme commented
Looks like @machi1990 has been faster cf. #5438
Feel free to close it if it makes sense.
Sorry for the delay

2019-11-13 18:32 UTC, machi1990 commented
Ah @danielpetisme I did not see this initial PR at all, otherwise I would not have opened my PR. Sorry about that. You feedbacks/comments are however welcomed on the PR #5438 I opened.

2019-11-13 20:16 UTC, danielpetisme commented
No problem. I prefer to see the issue to be tackled !!!

Le mer. 13 nov. 2019 à 19:32, Manyanda Chitimbo <notifications@github.com>
a écrit :

> Ah @danielpetisme <https://github.com/danielpetisme> I did not see this
> initial PR at all, otherwise I would not have opened my PR. Sorry about
> that. You feedbacks/comments are however welcomed on the PR #5438
> <https://github.com/quarkusio/quarkus/pull/5438> I opened.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/quarkusio/quarkus/pull/3595?email_source=notifications&email_token=AAEQ5HGTQGKDDKC32XVJ2XLQTRB4ZA5CNFSM4INV4OO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOED7FRKA#issuecomment-553539752>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEQ5HCJ66UVF4CEYDFIP4LQTRB4ZANCNFSM4INV4OOQ>
> .
>

2019-11-13 20:20 UTC, machi1990 commented
Superseded by #5438

2019-11-13 20:20 UTC, closed without merging