Upgrade to smallrye-config 1.3.9
quarkusio/quarkus pull request #3629
Opened 2019-08-21 19:27 UTC by dmlloyd

2019-08-22 08:49 UTC, gsmet commented
@dmlloyd coud you clarify why it's a Draft PR? You have identified some issues or you're waiting for something else?

2019-08-22 12:56 UTC, dmlloyd commented
Right now it's a draft because I wasn't sure it was going to work, and it didn't ;).  But I think we can make it a "real" PR as soon as I've fixed the problems, which I think I'm quite close to doing.

2019-08-22 18:39 UTC, dmlloyd commented
The TCK problem is at the heart of eclipse/microprofile-config#407.  If we decide to go ahead with this, we may have to disable some TCK tests.

2019-08-23 17:10 UTC, dmlloyd commented
Windows failure seems unrelated.

2019-08-23 19:16 UTC, gsmet requested changes
I added two very minor comments. Otherwise it looks good.

2019-08-23 19:16 UTC, gsmet commented on core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigInstantiator.java
> +                        if (fieldClass.equals(List.class)) {
You could reuse `fieldIsList` here, couldn't you?

2019-08-23 19:16 UTC, gsmet commented on tcks/microprofile-config/tck-suite.xml
> +                    <exclude name="testEnvironmentConfigSource"/>
Could you maybe copy the comment you removed above? It would be useful IMHO.

2019-08-26 19:07 UTC, gsmet approved these changes

2019-08-26 19:08 UTC, merged