Make it very obvious where Getting Started with Security tutorial is
quarkusio/quarkus pull request #36353
Opened 2023-10-09 12:22 UTC by sberyozkin

The latest independent review of Quarkus Security guides at https://quarkus.io/guides/ (Choose `Category:Security`) highlighted a problem: even the experienced reviewer could not see that `Secure a Quarkus Application with Basic Authentication and Jakarta Persistence` tutorial is in a `Getting Started` category, that it is meant to be seen as a `Getting Started with Security` guide, and therefore flagged it as a doc flaw.

The only visible indication that it is indeed the Getting Started with Security guide is in https://quarkus.io/guides/security-overview#getting-started-with-quarkus-security, but users looking at https://quarkus.io/guides/ (`Category:Security`) should get an immediate message where it really is.

This PR proposes 2 things:

* Highlight in the doc title and preamble that it is primarily about `Getting Started with Security` than about combining Basic Authentication and JPA - which are only basic tools in demonstrating how to get started and which have their own dedicated How-To/Concept docs. (Also added a minor clarification in the preamble text about the role of the identity provider)
* Renamed `security-basic-authentication-tutorial.adoc` to `security-getting-started-tutorial.adoc` - not critical but I think having an `https://quarkus.io/guides/security-getting-started-tutorial` link to represent a `Getting Started` tutorial.

2023-10-10 08:31 UTC, rsvoboda commented
re-triggered docs build which was aborted after 6 hours

2023-10-10 09:17 UTC, sberyozkin commented
Thanks @rsvoboda - but see #36349, it is a problem with most PRs affecting docs (those which have been mirrored in the product docs)

2023-10-10 14:08 UTC, rsvoboda requested changes
Renamed file need to be adjusted in many places

`security-basic-authentication-tutorial` occurences on Quarkus main:
```
git grep -l security-basic-authentication-tutorial
.github/quarkus-github-bot.yml
docs/downstreamdoc.yaml
docs/src/main/asciidoc/security-authentication-mechanisms.adoc
docs/src/main/asciidoc/security-authorize-web-endpoints-reference.adoc
docs/src/main/asciidoc/security-basic-authentication-howto.adoc
docs/src/main/asciidoc/security-basic-authentication-tutorial.adoc
docs/src/main/asciidoc/security-basic-authentication.adoc
docs/src/main/asciidoc/security-identity-providers.adoc
docs/src/main/asciidoc/security-jpa.adoc
docs/src/main/asciidoc/security-overview.adoc
```

2023-10-10 14:08 UTC, rsvoboda commented on docs/src/main/asciidoc/security-getting-started-tutorial.adoc
> +Get started with Quarkus Security by securing your Quarkus application endpoints with the built-in Quarkus xref:security-basic-authentication.adoc[Basic authentication] and the Jakarta Persistence id
```suggestion
Get started with Quarkus Security by securing your Quarkus application endpoints with the built-in Quarkus xref:security-basic-authentication.adoc[Basic authentication] and the Jakarta Persistence identity provider and enabling role-based access control.
```

Before:
<img width="1300" alt="Screenshot 2023-10-10 at 15 57 43" src="https://github.com/quarkusio/quarkus/assets/925259/1246431a-3344-4c55-897d-aa5bb85e4b11">

After:
<img width="1296" alt="Screenshot 2023-10-10 at 15 57 43-edit" src="https://github.com/quarkusio/quarkus/assets/925259/9b7630d8-d11e-4aa9-8c07-bfaa1d72bca4">

2023-10-10 21:37 UTC, sberyozkin commented
@rsvoboda This PR has indeed been fixed, thanks (#35897 still fails).
Please review again, 
But I'd like to wait for the Doc team to comment as well

2023-10-17 15:10 UTC, sberyozkin commented
@rsvoboda 3.5.0 is due tomorrow, so if you'd like this change to make it to 3.5.0 then please approve.
https://quarkus-pr-main-36353-preview.surge.sh/version/main/guides/ (Category: Security) looks good to me now with respect to this guide.

If Michelle will have concerns we can follow up with backports to 3.5.1 I guess.

Or may be we should keep this PR open until the Doc team gets back. Not sure if we should hurry up or not

2023-10-18 09:54 UTC, rsvoboda approved these changes
Approving, thanks for the update.

2023-10-18 09:58 UTC, rsvoboda commented
@sberyozkin I think this could be merged, this PR is open for more than a week

@michelle-purcell @MichalMaler @inoxx03 can comment later if they would appreciate other changes.

2023-10-20 09:47 UTC, sberyozkin commented
Thanks @rsvoboda, and yes, we will work with the Doc team to tune things as always

2023-10-20 09:47 UTC, merged

2023-10-20 09:49 UTC, sberyozkin commented
@rsvoboda Not sure if it can be backported now to 3.5.1 ? I suppose we will target 3.6.0 with this, CORS and other updates