Fix/liquibase 4.23 bug
quarkusio/quarkus pull request #36487
Opened 2023-10-15 10:59 UTC by appiepollo14

Fixes #36446

2023-10-15 11:00 UTC, appiepollo14 commented
Does Liquibase 4.23 need to be excluded somewhere?

2023-10-16 01:42 UTC, geoand commented
If CI is green, we can merge and backport to 3.5.

For 3.4, I'll leave it up to @gsmet to decide

2023-10-16 05:49 UTC, appiepollo14 commented
Can you explain how to do the backporting? Create a p.r. to tag 3.5?

2023-10-16 07:07 UTC, geoand commented
You don't need to do anything, we'll take care of it.

2023-10-16 07:28 UTC, gsmet requested changes
Thanks but could you please also update liquibase-mongodb?

2023-10-16 07:28 UTC, gsmet commented on bom/application/pom.xml
>          <liquibase-mongodb.version>4.23.1</liquibase-mongodb.version>
```suggestion
        <liquibase-mongodb.version>4.24.0</liquibase-mongodb.version>
```

2023-10-16 09:07 UTC, appiepollo14 commented
@gsmet will look into a testcase

2023-10-16 12:27 UTC, famod commented
I think we should now be able to remove that LabelExpression workaround I had to add to the previous Liquibase update PR.
IMO, that doesn't block this PR from being merged though.

PS: I'm on PTO for the rest of this month. So if anyone else wants to remove the workaround please feel free to do so.

2023-10-16 14:37 UTC, appiepollo14 commented
Build seems to be failing on other parts of the project...

2023-10-17 15:13 UTC, gsmet approved these changes
I squashed the commits.

Let's see what CI has to say. It might not be fully green but it looks good enough so it should be mergeable.

2023-10-18 01:15 UTC, appiepollo14 commented
Dependabot has opened the same PR on the meantime. I haven’t found the time looking for an IT but will focus on that!

2023-10-18 07:20 UTC, merged

2023-10-18 07:21 UTC, gsmet commented
@appiepollo14 I merged this but still interested if you can come up with an IT, just open a new PR. Thanks!