Allow default exporter with additional Quarkiverse exporters
quarkusio/quarkus pull request #36552
Opened 2023-10-18 11:34 UTC by azthec

Currently, when custom exporters are present the default exporter in not instantiated, this provides a configuration to always do so.

2023-10-18 16:18 UTC, brunobat requested changes

2023-10-18 21:28 UTC, azthec commented
I've done the changes you suggested

2024-05-16 09:08 UTC, azthec commented
@brunobat Hello, is this still needed or can the PR be closed?

2024-05-16 11:08 UTC, brunobat commented
I think it's a valuable feature, But we need tests.

2024-05-16 11:43 UTC, azthec commented
Would this be a different task that is blocked / ongoing?

2024-05-16 12:50 UTC, brunobat commented
No, there not another issue about this.

2024-11-10 17:03 UTC, cescoffier commented
@brunobat Where are we on this one?

2024-11-11 16:31 UTC, brunobat commented
It still needs IT tests.

2024-11-12 08:07 UTC, cescoffier commented
@azthec could you rebase and add ITs?

2025-01-07 09:26 UTC, brunobat commented
@azthec Will you still be working on this?

2025-06-25 07:35 UTC, brunobat commented
Closing for lack of feedback.

2025-06-25 07:35 UTC, closed without merging