Maven CLI: add wildcard matching into recipes detection
quarkusio/quarkus pull request #36578
Opened 2023-10-19 13:27 UTC by JiriOndrusek

fixes https://github.com/quarkusio/quarkus/issues/36573

Description:

1 - Implementation support only wildcard ('*') at the end of the artifactId name (directory representing artifactId name)
2 - Change is back-compatible with the recipes without wildcards ( which is probably common usage for extension recipes)
3 - Test covering several cases are present.
4 - I changed internal implementation from `List<String>` to Map<String, String> to avoid duplication of recipes loaded because of directories with wildcards. (I kept amending of the content in case it differs - can not happen in this implementation, but for the future changes it might be helpful)  
5 - If the quarkus CLI is used with the older recipes (without wildcards) - everything works as expected.
     If the Quakus CLI prior this change is used with the recipes using wildcards, recipes won't be matched, but no internal error will happen. I think that it is the desired behavior.

2023-10-19 13:28 UTC, JiriOndrusek commented
FYI @ia3andy

2023-10-24 08:10 UTC, ia3andy requested changes
Thanks, just a few comments

2023-10-24 08:10 UTC, ia3andy commented on independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/update/rewrite/QuarkusUpdatesRepository.java
> +            final Map<String, String> recipes = fetchRecipesAsList(resourceLoader, "quarkus-updates", recipeDirectoryNames);
just call it `fetchUpdateRecipes`

2023-10-24 10:36 UTC, JiriOndrusek commented on independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/update/rewrite/QuarkusUpdatesRepository.java
> +            final Map<String, String> recipes = fetchRecipesAsList(resourceLoader, "quarkus-updates", recipeDirectoryNames);
fixed

2023-10-24 10:39 UTC, JiriOndrusek commented on independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/update/rewrite/QuarkusUpdatesRepository.java
> +                                    String regexKey = toKey(path.relativize(dir).toString());
I extracted `applyWildcard` and `toKey` is already there, so it is possible to test. `applyWildcard` is already tested in `QuarkusUpdatesRepositoryTest.java`, for `toKey` there is an empty method (I have to find a parameters relevant for testing yet)

2023-10-25 07:07 UTC, JiriOndrusek commented on independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/project/update/rewrite/QuarkusUpdatesRepository.java
> +                                    String regexKey = toKey(path.relativize(dir).toString());
I wrote test content in `testToKey` method. 

Problem fixed.

2023-10-25 09:48 UTC, ia3andy approved these changes
cool!

2023-10-27 09:02 UTC, ia3andy commented
Ok, the problem is with `*` in directories path which is not ok on Windows. The idea to fix this is to change Wildcard by a startWith that we always use.

2023-10-27 09:02 UTC, ia3andy commented
@JiriOndrusek you will need to also update the PR on quarkus-updates

2023-10-27 10:44 UTC, JiriOndrusek commented
Thanks for the investigation. I'll refactor the solution to use `startsWith` and the change the related PR for Quarkus-updates

2023-10-27 12:00 UTC, JiriOndrusek commented
@ia3andy PR is refactored to use startsWith instead of ..*, PR in quarkus-updates is changed accordingly.

2023-10-27 12:24 UTC, ia3andy approved these changes
Thanks for the quick change @JiriOndrusek

2023-10-30 09:08 UTC, JiriOndrusek commented
@ia3andy I checked the failed CI build and I can still see `*` in the log, eventhough the cirrent change does not contain such folder anymore
`java.nio.file.InvalidPathException: Illegal char <*> at index 80: /home/app/target/classes/quarkus-updates/org.apache.camel.quarkus.camel-quarkus-*`

2023-10-30 09:09 UTC, JiriOndrusek commented
Sorry, I see the reason, my fault. I'll fix it shorthly

2023-10-30 09:21 UTC, JiriOndrusek commented
I'll also rebase the PR

2023-10-30 10:51 UTC, JiriOndrusek commented
@ia3andy There was 1 failing test because of the Windows system. I fixed it to work on windows (therefore failing on linux) and enabled it only on windows os.

The problem was happening in `toKey`  

``` 
org.opentest4j.AssertionFailedError: expected: <..:C::a:b:quarkus-updates:org.apache.camel.quarkus.camel-quarkus> but was: <..:b:quarkus-updates:org.apache.camel.quarkus.camel-quarkus>
```

2023-10-30 11:11 UTC, JiriOndrusek commented
Small typo in my last pushed was fixed, unfortunately the CI has to be approved again.

2023-10-31 08:24 UTC, JiriOndrusek commented
Hi @ia3andy , from the current failure I don't see any relation to the code of this PR (But I'm not able to find a reason of failure for 2 runs so far), WDYT?

2023-10-31 08:43 UTC, JiriOndrusek commented
I see:

JDK11
```
2023-10-30T16:45:44.8306526Z [INFO] Quarkus - Integration Tests - Hibernate ORM - Compatibility with databases meant for ORM 5.6 - MariaDB FAILURE [ 25.639 s]
2023-10-30T16:45:44.8308312Z [INFO] Quarkus - Integration Tests - Hibernate ORM - Compatibility with databases meant for ORM 5.6 - PostgreSQL FAILURE [ 19.750 s]
```

JDK17
```

```

JDK21
```

```

```
2023-10-30T16:30:29.0798092Z [INFO] Quarkus - Integration Tests - SmallRye Context Propagation FAILURE [ 34.797 s]
```

2023-10-31 09:02 UTC, JiriOndrusek commented
From the previous comment, none of the failures are not related to the change

2023-10-31 09:22 UTC, ia3andy commented
They don't seem to be related, I'll merge

2023-10-31 09:22 UTC, merged