Support of Embedded and ManyToOne nested object projection + Support of @ProjectedFieldName on class fields
quarkusio/quarkus pull request #36594
Opened 2023-10-20 10:55 UTC by humcqc

Support of Embedded and ManyToOne nested object projection + Support of @ProjectedFieldName on class fields

Documentation not updated yet, will do it when we agree on the code.

2023-11-17 11:49 UTC, loicmathieu commented
If I understand it correctly, the `@ProjectedClass` annotation allows for nested objects into a projection class. Can you provide a simple example?

Also, the documentation for projection should be updated.

2023-11-17 11:58 UTC, humcqc commented
https://github.com/quarkusio/quarkus/pull/36594/files#diff-41e4522791d7b2934d3189b9d2608d935564a31102f309bfb7f22e27e7aed968R56

2023-11-17 12:10 UTC, loicmathieu commented
What I don't understand in your example is why the PersonDTO extends PeronsName and why it has the annotation in it. That's why I asked for a simple example.

2023-11-17 12:24 UTC, humcqc commented
> What I don't understand in your example is why the PersonDTO extends PeronsName and why it has the annotation in it. That's why I asked for a simple example.

PersonName is the original DTO in integration test , I ve created PersonDTO that extend it to keep the original test and I've  included Embbeded (DescriptionDTO) and ManyToOne ( AdressDTO) elements in it. It allow me to test different case with this DTO. 

"Why there is an annotation in it ?" Good question. We have 3 choices:
1) Impose the @ProjectedClass for all projected class and test if it present ( breaking change )
2) Does not impose it, you can put it but the ProjectedClass annotation on main class have no impact -> what we have in the integration test.
3) Just use it in nested class , and I can remove it from Main class

2023-11-17 12:27 UTC, loicmathieu commented
> Just use it in nested class , and I can remove it from Main class

It is clearer to me, its behavior will be well defined.

> PersonName is the original DTO in integration test , I ve created PersonDTO that extend it to keep the original test and I've included Embbeded (DescriptionDTO) and ManyToOne ( AdressDTO) elements in it. It allow me to test different case with this DTO.

Please let the current test as is and add a new one so we test both a simple projection and a more complex one.

2023-11-17 12:43 UTC, humcqc commented
> > Just use it in nested class , and I can remove it from Main class
> 
> It is clearer to me, its behavior will be well defined.

---> Ok , perhaps we can rename it to NestedProjectedClass to be more precise ?

> > PersonName is the original DTO in integration test , I ve created PersonDTO that extend it to keep the original test and I've included Embbeded (DescriptionDTO) and ManyToOne ( AdressDTO) elements in it. It allow me to test different case with this DTO.
> 
> Please let the current test as is and add a new one so we test both a simple projection and a more complex one.

--> I didn't change the current test with simple Projection ( PersonName), it's just my test use a new DTO ( PersonDTO) that inherit from the simple (PersonName) to avoid to duplicate the projection of simple field. And to test the inheritance, I had some issue with inheritance with the constructor part. 
If you think it's simpler I can create a new class PersonName2 same as PersonName and PersonDTO will inherit this new Class ?

2023-11-17 16:36 UTC, humcqc commented
I've added simple example + doc, and renamed annotation.

2023-11-17 18:39 UTC, humcqc commented
Let me fix the jdk11 + native issue and i will come back to you.

2023-11-28 12:43 UTC, loicmathieu requested changes
Overall, the PR seems more complex than needed.
There seem to be multiple functionalities in one PR and the tests seem contain more than just what's needed for the functionality.

This makes it complex to review so I didn't finish it yet.

2023-11-28 12:43 UTC, loicmathieu commented on integration-tests/hibernate-reactive-panache/src/main/java/io/quarkus/it/panache/reactive/Person.java
> +        @ParamDef(name = "names", type = String.class) })
Why did you add those filter?

2023-11-28 12:43 UTC, loicmathieu commented on integration-tests/hibernate-reactive-panache/src/main/java/io/quarkus/it/panache/reactive/Person.java
> +    }
What is the purpose of this method?

2023-11-28 17:51 UTC, humcqc commented
> Overall, the PR seems more complex than needed. There seem to be multiple functionalities in one PR and the tests seem contain more than just what's needed for the functionality.
> 
> This makes it complex to review so I didn't finish it yet.

Yes you right , the PR is complex because it handles the recursivity of nested objects. And I included one test for #28844.
I will simplify and remove the test for #28844.

2023-12-10 11:34 UTC, humcqc commented
Hi @loicmathieu , It should be good now, could you have a look please?

2023-12-12 12:02 UTC, loicmathieu requested changes

2023-12-12 12:02 UTC, loicmathieu commented on extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/CommonPanacheQueryImpl.java
> +    private StringBuilder getParameterFromClass(Class<?> type, String parentParameter) {
```suggestion
    private StringBuilder getParametersFromClass(Class<?> type, String parentParameter) {
```

2023-12-27 17:23 UTC, humcqc commented
Hi @loicmathieu , could you check please to finalize this PR ? Thanks

2024-01-11 09:56 UTC, loicmathieu requested changes
Two points still to solve:
- A lot of tests are disabled in native, why didn't they work and is there a way to make them working?
- If a class is annotated by our own annotation, we can easily register them for reflection so we should not ask our user to do that. If it's needed to register them, you can do it in the processor, I can help for that.

2024-01-11 09:56 UTC, loicmathieu commented on integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/DogDto2.java
> +    @RegisterForReflection
Is it really needed?
If yes we should register for reflection all classes annotated by `@NestedProjectedClass`

2024-01-11 09:56 UTC, loicmathieu commented on integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/PersonDTO.java
> +    @RegisterForReflection
Same here

2024-01-11 09:56 UTC, loicmathieu commented on integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/PersonDTO.java
> +    @RegisterForReflection
Same here

2024-01-11 09:56 UTC, loicmathieu commented on integration-tests/hibernate-reactive-panache/src/main/java/io/quarkus/it/panache/reactive/DogDto.java
> +    @RegisterForReflection
Same here

2024-01-11 09:56 UTC, loicmathieu commented on integration-tests/hibernate-reactive-panache/src/main/java/io/quarkus/it/panache/reactive/PersonDTO.java
> +    @RegisterForReflection
Same here

2024-01-11 09:56 UTC, loicmathieu commented on integration-tests/hibernate-reactive-panache/src/main/java/io/quarkus/it/panache/reactive/PersonDTO.java
> +    @RegisterForReflection
Same here

2024-01-11 09:56 UTC, loicmathieu commented on integration-tests/hibernate-orm-panache/src/test/java/io/quarkus/it/panache/PanacheFunctionalityTest.java
> +                        " from Person2 where name = ?1",
I'm surprise by this, the project method should built the select clause so why adding it manually here?

2024-01-11 09:56 UTC, loicmathieu commented on integration-tests/hibernate-orm-panache/src/main/java/io/quarkus/it/panache/TestEndpoint.java
> +                        " from Person2 where name = ?1",
The select clause should be build by the project method so why add one here?

2024-01-11 14:35 UTC, humcqc commented
For the native test i've followed the same pattern in other test in PanacheFunctionalityTest : https://github.com/quarkusio/quarkus/blob/76a7ce15569b56fdacf88a4a4d42fd02e4bf551a/integration-tests/hibernate-orm-panache/src/test/java/io/quarkus/it/panache/PanacheFunctionalityTest.java#L108 , seems just Rest Tests are working in this test class. I can remove them from PanacheFunctionalityTest as they are tested through TestEnpoint in native mode ?

2024-01-11 14:50 UTC, loicmathieu commented
> Seems just Rest Tests are working in native mode in this test class.I would rather keep them , but if you really want i can remove them from PanacheFunctionalityTest as they are tested through TestEnpoint in native mode ?

Yes please

2024-01-11 16:19 UTC, humcqc commented
If a class is annotated by our own annotation, we can easily register them for reflection so we should not ask our user to do that. If it's needed to register them, you can do it in the processor, I can help for that.

I would appreciate some help for this one. I try a simple fix, but did not work :)

2024-01-27 17:03 UTC, humcqc commented
Hi @loicmathieu , could we try to finish this week to have it in 3.7 ?

2024-01-31 11:49 UTC, humcqc commented
Hi @loicmathieu @geoand ,
I think this PR will be fine when [38496](https://github.com/quarkusio/quarkus/pull/38496#issuecomment-1918938699) will ne done.
Could we try to have it in 3.7 ? 
Thanks

2024-02-01 07:40 UTC, geoand commented
Thanks for this. 

We will certainly need to the commits to be cleaned up / squashed

2024-02-01 11:45 UTC, loicmathieu approved these changes
LGTM, thanks for doing this and your patience for the long review process!

2024-02-01 11:46 UTC, loicmathieu commented
@humcqc can you please squash your commits in one commit so we can merge it?

2024-02-01 14:20 UTC, humcqc commented
> @humcqc can you please squash your commits in one commit so we can merge it?



> @humcqc can you please squash your commits in one commit so we can merge it?

Sure, Done!

2024-02-01 15:13 UTC, merged