Issue 32595 - Kafka Streams Dev UI migration to v2
quarkusio/quarkus pull request #36650
Opened 2023-10-23 21:50 UTC by dcotfr

Proposal of rewriting of Kafka Streams Dev UI for v2.

Replaces Mermaid usage by a wasm version of Graphviz (seems lighter and with less dependencies).

Still generates a mermaid graph definition (for backward compatibility) and adds a new digraph definition for Graphviz.

Warning : contains a direct link to https://cdn.jsdelivr.net/npm/@hpcc-js/wasm/dist/graphviz.js in qwc-kafka-streams-topology.js, because I don't know how to include this dependency with in a more cleaner / secured way.

fixes #32595

2023-10-24 07:56 UTC, gsmet commented
Thanks a lot, I pinged @phillip-kruger so that he can have a look.

2023-10-25 01:46 UTC, phillip-kruger requested changes
LGTM, I think we can merge once the change is made

2023-10-25 01:46 UTC, phillip-kruger commented on extensions/kafka-streams/deployment/src/main/resources/dev-ui/qwc-kafka-streams-topology.js
> +import { Graphviz } from "https://cdn.jsdelivr.net/npm/@hpcc-js/wasm/dist/graphviz.js";
Here you can use `import { Graphviz } from "@hpcc-js/wasm/graphviz";` and add this to deployment/pom.xml:

```
<dependency>
        <groupId>org.mvnpm.at.hpcc-js</groupId>
        <artifactId>wasm</artifactId>
        <version>2.14.1</version>
        <scope>runtime</scope>
      </dependency>
```

You can also add above to build parent pom dependency management and reference in the extension pom without the version

2023-10-25 21:24 UTC, phillip-kruger approved these changes

2023-10-25 21:27 UTC, phillip-kruger commented
@dcotfr Thanks for this ! Please rebase and squash your PR, and then on green CI we can merge

2023-10-25 23:10 UTC, phillip-kruger commented
@dcotfr seems like the wasm js dependency pulls in a lot of other dependencies with ranges. To make our build faster we lock these in the build-parent. I'll send you (a bit later) what needs to be added to the build parent.

2023-10-25 23:44 UTC, closed without merging