Allow * expression for quarkus:add-extension
quarkusio/quarkus pull request #3672
Opened 2019-08-23 13:17 UTC by Dufgui

fix #1234

2019-08-23 13:48 UTC, cescoffier requested changes
I've made a comment about the tests.
This should also be documented somewhere.

2019-08-23 13:48 UTC, cescoffier commented on devtools/common/src/test/java/io/quarkus/cli/commands/AddExtensionsTest.java
> +    }
We need to test with more complicated regexps as all the escapes are uncovered.
Also, we need to check with non matching regexp

2019-08-23 13:49 UTC, cescoffier commented on devtools/common/src/test/java/io/quarkus/cli/commands/AddExtensionsTest.java
> +    }
What does happen in the case of `**`?

2019-08-24 15:51 UTC, Dufgui commented
I add doc, and I fix the conf about the plugin in gradle and missing doc of addExtension
@cescoffier @aloubyansky

2019-08-25 08:09 UTC, cescoffier approved these changes

2019-08-25 08:09 UTC, merged