Add docs/src/main/asciidoc/security-oidc-auth0-tutorial.adoc to the l…
quarkusio/quarkus pull request #36905
Opened 2023-11-06 21:06 UTC by rolfedh

…ist of downstream files.

2023-11-06 21:59 UTC, sberyozkin commented
Thanks @rolfedh I'm not sure it has to be part of the product docs. This tutorial targets the Auth0 user community. My understanding  we should be focusing at Keycloak at  the RHBQ docs level.

2023-11-06 22:34 UTC, sberyozkin commented
Hi Rolfe, just to make sure there is no confusion, this is not about the OIDC authentication in general, it is there to help an Auth0 https://auth0.com/ users, while RHBQ customers will be getting Keycloak, besides this tutorial has my name all over it in its images :-), I'm not sure it is ready for the downstream inclusion yet or if we want it at all

2023-11-06 22:35 UTC, sberyozkin requested changes
Lets discuss first if this inclusion in the downstream docs is necessary

2023-11-07 08:26 UTC, closed without merging

2023-11-07 08:26 UTC, rolfedh commented
No problem, @sberyozkin. Thanks for letting me know about this.