Support Micrometer @MeterTag
quarkusio/quarkus pull request #36945
Opened 2023-11-08 12:53 UTC by computerlove

Micrometer defines a annotation @MeterTag, making it possible to add additional tags for methods annotated with @Counted and @Timed from method arguments. 

This is a minimal implementation, not supporting `MeterTag.expression` and `MeterTag.resolver`.

2023-11-13 10:11 UTC, computerlove commented
I have made a suggestion for how to support `@MeterTag`. 

MeterTag.resolver is supported, the application can define beans imlementing `ValueResolver` and refere to these classes in MeterTag.resolver=ValueResolverBean.class.

MeterTag.expression is also supported, the application can define a bean imlementing `ValueExpressionResolver` and it will be used to evaluate the expression.

2023-11-13 18:57 UTC, brunobat commented
There is an error in the docs that needs fixing

2023-11-13 20:33 UTC, computerlove commented
It's now fixed.

2023-11-14 12:23 UTC, gsmet submitted a review, later dismissed
Just a note that this will need a squash before merging. Please dismiss when done.

2023-11-15 08:06 UTC, computerlove commented
Commits has been squashed.

2023-11-15 14:57 UTC, brunobat reviewed
@computerlove would you be able to add an integration test to `integration-tests/micrometer-prometheus`?... Mimicking the usage you have in the docs would be perfect.

2023-11-15 15:30 UTC, computerlove commented
> @computerlove would you be able to add an integration test to `integration-tests/micrometer-prometheus`?... Mimicking the usage you have in the docs would be perfect.

Yes, will do!

2023-11-17 07:39 UTC, computerlove commented
Are the updated tests good enough?

I have been thinking about supporting `MeterTag.expression` with Qute(if present), validating the templates on build time. 
But that will have to be in a separate PR, I don't have any more spare time to work on this right now.

2023-11-27 13:16 UTC, ebullient requested changes
rebase and squash. This looks good, just some consistency changes.

2023-11-27 13:16 UTC, ebullient commented on extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/MicrometerTimedInterceptor.java
> +import java.util.*;
preserve original imports

2023-11-27 14:26 UTC, computerlove commented
I have fixed the comments for documentation and imports.

2023-11-27 22:54 UTC, ebullient approved these changes

2023-11-27 22:55 UTC, ebullient commented
@gsmet .. I think we're good to go.

2023-11-28 15:20 UTC, merged