Upgrade to Hibernate ORM 6.4, Hibernate Search 7.0, Hibernate Reactive next
quarkusio/quarkus pull request #36978
Opened 2023-11-09 14:05 UTC by yrodiere

Creating as draft for now, because:

* We need an ORM 6.4.0.CR2/Final.
* We still need a HR release and need to upgrade to that, because the current version doesn't work with ORM 6.4.
* We may need a Hibernate Search 7.0.0.CR2/Final, but just for good measure as it seems to work as is.

2023-11-09 15:42 UTC, FroMage commented
Excellent!

2023-11-20 11:19 UTC, FroMage commented
The 6.4.0-SNAPSHOT branch (after CR1) wants one extra method in `CustomMetadataBuilderContributor.HardcodedSuffixFunction`

2023-11-22 10:04 UTC, yrodiere commented
@beikov [this change](https://github.com/hibernate/hibernate-orm/commit/bfb9fcc0f6e2e273447af61818126e9816d4b50f) seems to introduce a backwards-incompatible API change for implementations of `AbstractSqmSelfRenderingFunctionDescriptor`: there is no default implementation for `render(SqlAppender sqlAppender, List<? extends SqlAstNode> sqlAstArguments, ReturnableType<?> returnType, SqlAstTranslator<?> walker)`. Should we fix this in ORM?

2023-11-22 10:08 UTC, yrodiere commented
Ah, all things SQM are considered incubating apparently:

https://docs.jboss.org/hibernate/orm/6.4/incubating/incubating.txt

```
org.hibernate.query.sqm.*
```

So... breaking changes are fair, please ignore me.

2023-11-24 11:29 UTC, yrodiere commented
I added the upgrade to Hibernate ORM 6.4.0.Final, Hibernate Reactive 2.2.0.Final and Hibernate Search 7.0.0.CR2.

The tests should pass now, though I can't run them locally right now, so I marked as ready for review and will see what CI has to say about it.

2023-11-24 13:16 UTC, yrodiere commented
Not sure what's going on, but CI skipped almost all jobs... I rebased and force-pushed, let's see how it goes.

2023-11-24 17:02 UTC, yrodiere commented
I tried to fix what I noticed in the previous CI run, let's try again...

@marko-bekhta you might be interested by commits 2, 3 and 4. Turns out the tests you added for FormatMappers were more complex than I thought when I reviewed them xD

2023-11-27 11:38 UTC, yrodiere commented
I think I addressed most failures, but the one in Panache Hibernate Reactive ITs puzzles me... I wonder if, maybe, Hibernate Reactive now parses queries asynchronously, resulting in some `catch` block in Panache no longer working (because we would need to use `Uni#onFailure` instead)?

@DavideD @FroMage Do you think you could have a look?

FTR, the failure:

```
2023-11-24T18:53:35.4762686Z [ERROR] Tests run: 23, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.961 s <<< FAILURE! -- in io.quarkus.it.panache.reactive.PanacheFunctionalityTest
2023-11-24T18:53:35.4764946Z [ERROR] io.quarkus.it.panache.reactive.PanacheFunctionalityTest.testPanacheFunctionality -- Time elapsed: 0.212 s <<< FAILURE!
2023-11-24T18:53:35.4766256Z java.lang.AssertionError: 
2023-11-24T18:53:35.4766734Z 1 expectation failed.
2023-11-24T18:53:35.4767266Z Response body doesn't match expectation.
2023-11-24T18:53:35.4767800Z Expected: is "OK"
2023-11-24T18:53:35.4889395Z   Actual: {"details":"Error id 247d4f49-eef7-4d6e-a987-785d741a0b5b-1, java.lang.IllegalArgumentException: org.hibernate.query.SyntaxException: At 1:70 and token '<EOF>', mismatched input '<EOF>', expecting one of the following tokens: '=', '.' [UPDATE io.quarkus.it.panache.reactive.Person SET Person.updateAllNames]","stack":"java.lang.IllegalArgumentException: org.hibernate.query.SyntaxException: At 1:70 and token '<EOF>', mismatched input '<EOF>', expecting one of the following tokens: '=', '.' [UPDATE io.quarkus.it.panache.reactive.Person SET Person.updateAllNames]\n\tat org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:143)\n\tat org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:167)\n\tat org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:173)\n\tat org.hibernate.reactive.session.impl.ReactiveExceptionConverter.convert(ReactiveExceptionConverter.java:30)\n\tat org.hibernate.reactive.session.impl.ReactiveSessionImpl.createReactiveQuery(ReactiveSessionImpl.java:377)\n\tat org.hibernate.reactive.session.impl.ReactiveSessionImpl.createReactiveQuery(ReactiveSessionImpl.java:358)\n\tat org.hibernate.reactive.mutiny.impl.MutinySessionImpl.createQuery(MutinySessionImpl.java:129)\n\tat io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.lambda$executeUpdate$30(AbstractJpaOperations.java:405)\n\tat io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:68)\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)\n\tat io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)\n\tat io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\n\tat io.smallrye.mutiny.operators.uni.UniOnFailureTransform.subscribe(UniOnFailureTransform.java:31)\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\n\tat io.smallrye.mutiny.operators.uni.UniOnItemConsume.subscribe(UniOnItemConsume.java:30)\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\n\tat io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap.subscribe(UniOnFailureFlatMap.java:31)\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)\n\tat io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)\n\tat io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)\n\tat io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:47)\n\tat io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)\n\tat java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)\n\tat java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)\n\tat java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2079)\n\tat org.hibernate.reactive.util.async.impl.AsyncTrampoline$TrampolineInternal.unroll(AsyncTrampoline.java:131)\n\tat org.hibernate.reactive.util.async.impl.AsyncTrampoline$TrampolineInternal.lambda$unroll$0(AsyncTrampoline.java:126)\n\tat java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)\n\tat java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)\n\tat java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2079)\n\tat io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:536)\n\tat io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)\n\tat io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)\n\tat io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)\n\tat io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)\n\tat io.vertx.sqlclient.impl.QueryResultBuilder.tryComplete(QueryResultBuilder.java:88)\n\tat io.vertx.sqlclient.impl.QueryResultBuilder.tryComplete(QueryResultBuilder.java:32)\n\tat io.vertx.core.Promise.complete(Promise.java:66)\n\tat io.vertx.core.Promise.handle(Promise.java:51)\n\tat io.vertx.core.Promise.handle(Promise.java:29)\n\tat io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)\n\tat io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)\n\tat io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)\n\tat io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)\n\tat io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)\n\tat io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)\n\tat io.vertx.sqlclient.impl.TransactionImpl.lambda$wrap$0(TransactionImpl.java:72)\n\tat io.vertx.core.impl.future.Future [...]

2023-11-27 11:57 UTC, DavideD commented
It seems that the update query is missing the parameter bit, the update query should end with ` := $1`  or something.

My guess is that this is an error in Panache

2023-11-27 12:38 UTC, DavideD commented
It's probably something simpler than that. I will have a look

2023-11-27 21:38 UTC, DavideD commented
Hibernate ORM now throws a different error that's ignored by Panache. This is true for Hibernate ORM too.
But, there's no similar test for Hibernate ORM and so there's no failure.

A fix like this should work: https://github.com/quarkusio/quarkus/pull/37338/commits/86d0040c5e066c970d0acdc0fe18047929dac3c8

I've added three commits on top of this PR here: https://github.com/quarkusio/quarkus/pull/37338

2023-11-28 08:37 UTC, yrodiere commented
> Hibernate ORM now throws a different error that's ignored by Panache. This is true for Hibernate ORM too. But, there's no similar test for Hibernate ORM and so there's no failure.
> 
> A fix like this should work: [86d0040](https://github.com/quarkusio/quarkus/commit/86d0040c5e066c970d0acdc0fe18047929dac3c8)
> 
> I've added three commits on top of this PR here: #37338

Thanks! I added your commits on top of this PR. Let's run CI again!

2023-11-28 10:57 UTC, yrodiere commented
@DavideD I think your cleanup commit actually breaks some tests... It looks like `Person::count` is actually compiled as `AbstractJpaOperations::count`, resulting in a runtime failure? @FroMage do you know anything about this?

Anyway, I'll remove that commit. Feel free to open a separate PR about it @DavideD , but I suspect this will also need a fix in Panache (if Panache can even do something about it).

2023-11-28 13:01 UTC, yrodiere commented
Alright, the build finally passed! :partying_face: 

Could I get an approval to get this merged, @gsmet?
Or @Sanne, but I think he's busy these days.

2023-11-28 13:19 UTC, gsmet requested changes
We will need a note in the migration guide about:

> Rename extension quarkus-hibernate-search-orm-coordination-outbox-polling to quarkus-hibernate-search-orm-outbox-polling

And if it's an extension that can be consumed by users, we should:
- keep it defined in the BOM for a while
- have redirections in place in the relocations/ module. They should be short given only the artifact changes.

This can be done once the PR is merged, I will merge it.

2023-11-28 13:21 UTC, gsmet approved these changes
Ah, I wanted to post an Approval review, and apparently clicked on the wrong checkbox.

As said, what I wrote above is not blocking, will merge!

2023-11-28 13:21 UTC, merged

2023-11-28 13:21 UTC, gsmet commented
Thanks everyone, nice to have the latest ORM in Quarkus!

2023-11-28 14:20 UTC, yrodiere commented
> We will need a note in the migration guide about:

I added relevant notes for both ORM and Search to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.7

> And if it's an extension that can be consumed by users, we should:
>
>    keep it defined in the BOM for a while
>    have redirections in place in the relocations/ module. They should be short given only the artifact changes.

I kept it in the BOM. Will submit a PR for relocations.