Fixing Jaxb unmarshalling error with native compilation
quarkusio/quarkus pull request #37643
Opened 2023-12-10 16:22 UTC by rysurd

Fix #36479

There is a warning throw stating that some classes are not indexed via Jandex. For instance : 
```logs
[WARNING] [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - com.sun.istack.FinalArrayList (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - com.sun.org.apache.xerces.internal.impl.dv.xs.SchemaDVFactoryImpl (source: JaxbProcessor > com.sun.org.apache.xerces.internal.impl.dv.xs.SchemaDVFactoryImpl)
        - com.sun.org.apache.xpath.internal.functions.FuncNot (source: JaxbProcessor > com.sun.org.apache.xpath.internal.functions.FuncNot)
        - com.sun.xml.internal.stream.XMLInputFactoryImpl (source: JaxbProcessor > com.sun.xml.internal.stream.XMLInputFactoryImpl)
        - com.sun.xml.internal.stream.XMLOutputFactoryImpl (source: JaxbProcessor > com.sun.xml.internal.stream.XMLOutputFactoryImpl)
        - jakarta.activation.MimeType (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - javax.xml.namespace.QName (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.annotation.AnnotationReader (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.annotation.Locatable (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.Adapter (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.BuiltinLeafInfo (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.ClassInfo (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.Element (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.ElementInfo (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.ElementPropertyInfo (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.EnumLeafInfo (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.ErrorHandler (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.ID (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.NonElement (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.PropertyInfo (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.PropertyKind (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.TypeInfo (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.TypeInfoSet (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.core.WildcardMode (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.model.nav.Navigator (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.runtime.IllegalAnnotationException (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.runtime.Location (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
        - org.glassfish.jaxb.core.v2.runtime.RuntimeUtil$ToStringAdapter (source: JaxbProcessor > org.glassfish.jaxb.core.v2.runtime.RuntimeUtil$ToStringAdapter)
        - org.xml.sax.Locator (source: JaxbProcessor > jakarta.xml.bind.annotation.XmlAccessorType)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
```

2023-12-10 19:12 UTC, rysurd commented
@gsmet @zakkak Hello ! I have opened the PR for the jaxb unmarshalling error. I included an integration test which reproduce the same issue and check if it works or not.

2023-12-11 12:51 UTC, gsmet requested changes
Thanks for having a look at this. I think we need to be more careful about when we use the hierachy feature: it should only be used on domain classes that will be serialized with JAXB, not on everything that was declared for reflection.
That's why you end up with all these warnings.

You can have a closer look if you want or I can have a look if you prefer, let me know.

In any case, it's nice to have a test case as we will be able to test that everything is fine if we make adjustments.

2023-12-11 12:51 UTC, gsmet commented on extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java
> +                    .build());
My guess is that this change should be reverted and that's probably what causes the warnings.

2023-12-11 12:51 UTC, gsmet commented on extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java
> +            BuildProducer<ReflectiveHierarchyBuildItem> reflectiveClass,
My guess is that this change should be reverted and that's probably what causes the warnings.

2023-12-11 12:51 UTC, gsmet commented on extensions/jaxb/deployment/src/main/java/io/quarkus/jaxb/deployment/JaxbProcessor.java
> +    private void addReflectiveClass(BuildProducer<ReflectiveHierarchyBuildItem> reflectiveClass, boolean methods,
The call sites of this method would have to checked. I'm really not sure it makes sense to replace it in all cases (and might not even be necessary depending on when it's called).

2023-12-11 12:51 UTC, gsmet commented on extensions/jaxb/runtime/pom.xml
> +            </plugin>
Why is this needed? The entity classes should be in the app, not in the extension, shouldn't they?

2023-12-12 13:17 UTC, rysurd commented
> Thanks for having a look at this. I think we need to be more careful about when we use the hierachy feature: it should only be used on domain classes that will be serialized with JAXB, not on everything that was declared for reflection. That's why you end up with all these warnings.
> 
> You can have a closer look if you want or I can have a look if you prefer, let me know.
> 
> In any case, it's nice to have a test case as we will be able to test that everything is fine if we make adjustments.

Thanks for your review! I did some changes according to your inputs but I still got the warning, even if now there are only jaxb classes involved. If you don't mind I would not say no to a little help to troubleshoot this ... :D Thanks a lot again!

2023-12-12 15:27 UTC, gsmet commented
I will have a look later this week. Thanks for pursuing this.

2023-12-16 14:40 UTC, rysurd commented
@gsmet I think I resolved the issue with the Jandex warning ... Build seems ok now (No specific warnings or errors) so maybe if you have some time could you check on this please ? 😄 The integration test seems to do its job too as it failed when using the main branch codebase and succeed when I use the fix.

2024-01-12 17:47 UTC, gsmet approved these changes
@rysurd sorry for the delay, your latest changes look good.

I made some very small changes to make it more consistent with code we already had in the tree but these were really micro changes.

Let's see what CI has to say and merge!

2024-01-12 18:23 UTC, merged

2024-01-12 18:23 UTC, gsmet commented
Merged, thanks for your contribution!

2024-01-12 20:20 UTC, rysurd commented
> Merged, thanks for your contribution!

Thanks !

2024-01-16 13:30 UTC, rysurd commented
Ah, sorry I should have catched that the extent of these changes would reach also into other libs ...

2024-01-16 14:34 UTC, ppalaga commented
Here is my proposal: https://github.com/quarkusio/quarkus/pull/38221

2024-01-16 14:35 UTC, ppalaga commented
@rysurd @turing85 could you perhaps check that https://github.com/quarkusio/quarkus/pull/38221 fixes your original issue?

2024-01-16 15:47 UTC, turing85 commented
@ppalaga Seems to work :+1: