Added  Access Log Configuration Sample Documentation
quarkusio/quarkus pull request #3792
Opened 2019-08-31 16:18 UTC by masini

Few lines to describe how-to

2019-09-02 14:42 UTC, rsvoboda commented on docs/src/main/asciidoc/undertow-reference.adoc
> +You can add HTTP request logging adding the AccessHandler configuration to the undertow-handler.conf file.
`undertow-handlers.conf`

2019-09-02 14:43 UTC, rsvoboda requested changes
Please fix the file name

2019-09-02 15:00 UTC, masini commented
Hi Rostislav, which file must be renamed ?

2019-09-02 15:15 UTC, rsvoboda commented on docs/src/main/asciidoc/undertow-reference.adoc
> +access-log(format='common', category='my.own.category')
Category is not recognized parameter 
```
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl2.<clinit>(ApplicationImpl2.zig:131)
	... 16 more
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: UT000045: Error parsing predicated handler string unknown parameter category:
access-log(format='common', category='my.own.category')
                                                     ^
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder.bootServletContainer(UndertowDeploymentRecorder.java:405)
	at io.quarkus.deployment.steps.UndertowBuildStep$build37.deploy_0(UndertowBuildStep$build37.zig:444)
	at io.quarkus.deployment.steps.UndertowBuildStep$build37.deploy(UndertowBuildStep$build37.zig:36)
	at io.quarkus.runner.ApplicationImpl2.<clinit>(ApplicationImpl2.zig:117)
	... 16 more
Caused by: java.lang.IllegalArgumentException: UT000045: Error parsing predicated handler string unknown parameter category:
access-log(format='common', category='my.own.category')
                                                     ^
	at io.undertow.server.handlers.builder.PredicatedHandlersParser.error(PredicatedHandlersParser.java:729)
	at io.undertow.server.handlers.builder.PredicatedHandlersParser.handleHandlerNode(PredicatedHandlersParser.java:171)
	at io.undertow.server.handlers.builder.PredicatedHandlersParser.handleNode(PredicatedHandlersParser.java:114)
	at io.undertow.server.handlers.builder.PredicatedHandlersParser.parse(PredicatedHandlersParser.java:91)
	at io.undertow.server.handlers.builder.PredicatedHandlersParser.parse(PredicatedHandlersParser.java:80)
	at io.quarkus.undertow.runtime.UndertowHandlersConfServletExtension.handleDeployment(UndertowHandlersConfServletExtension.java:33)
	at io.undertow.servlet.core.DeploymentManagerImpl.handleExtensions(DeploymentManagerImpl.java:300)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:155)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder.bootServletContainer(UndertowDeploymentRecorder.java:394)
	... 19 more
```

2019-09-02 15:16 UTC, rsvoboda commented
`undertow-handler.conf`
to
`undertow-handlers.conf`

2019-09-02 18:54 UTC, masini commented
Ok for the filename, I forgot the final "s".

Regarding the configuration, I pasted there my current config, I also looked at the configuration builder and I read this:

```java
@Override
public Map<String, Class<?>> parameters() {

    Map<String, Class<?>> params = new 
    params.put("format", String.class);
    params.put("category", String.class);
    return params;
}
```

I'm using 0.21.1, but I can see that master version is without category.

Should I document 0.21.1 or next version (the latter I think) ?

2019-09-03 06:06 UTC, rsvoboda commented
Maybe missing category is a bug ...
@stuartwdouglas can you look at this ?

@masini docs in master should be relevant to master, but first I think we need to know more about missing `category`

2019-11-05 07:56 UTC, masini commented
What about this PR ?

2019-11-05 07:59 UTC, machi1990 commented
@masini looks like there a conflicts, can you rebase on top of master? Thanks. 

@rsvoboda do you mind having another look if the PR is okay for you? Thanks.

2019-11-05 08:00 UTC, rsvoboda submitted a review, later dismissed
- This needs rebase because of onflicting files
 - Is `category='my.own.category'` working now ?
 - I still see undertow-handler.conf (missing `s` for handlers)

2019-11-12 15:14 UTC, cescoffier commented
Rebased required.

2019-11-25 15:48 UTC, gsmet commented
I force-pushed a rebase and some adjustments.

I _think_ the category issue was fixed in `quarkus-http`.  @rsvoboda could you see if you can still reproduce the issue?

Also, I don't know if this works without Undertow. If someone had the time to check, that would be nice.

2019-11-25 15:56 UTC, rsvoboda commented
added comments to https://github.com/quarkusio/quarkus/issues/4059 few days ago

2019-11-25 15:57 UTC, rsvoboda commented
category worked for `quarkus-http` based app ...

2019-11-25 16:42 UTC, gsmet approved these changes

2019-11-25 16:42 UTC, merged

2019-11-25 16:44 UTC, rsvoboda commented
@gsmet https://github.com/quarkusio/quarkus/issues/5556
currently it has bug label, could be changed to enhancement