#38078
quarkusio/quarkus pull request #38079
Opened 2024-01-07 00:32 UTC by YassinHajaj

Make OidcTestSecurityIdentityAugmentor WAY faster by making privateKey's generation final and static (thus unique for the test execution) #38078

2024-01-07 10:07 UTC, michalvavrik commented
So you want to use same private key whether the issuer config value has changed or not (like in a DEV mode)? Is `TestSecurityIdentityAugmentor` a `@Dependent` bean so you can achieve same with adding qualifier to `OidcTestSecurityIdentityAugmentorProducer` instead of static initialization?

Please wait for a review till @sberyozkin is available. Thank you

2024-01-07 15:10 UTC, YassinHajaj commented
Hey @michalvavrik,

The `privateKey` is not dependent on the issuer config, so I think we're good with the solution we've got.

Thinking about making the bean `@ApplicationScoped` as you mentioned. That could be a neat way to keep it more in line with CDI standards. Might give it a shot. Good idea !

We should indeed probably hold off until @sberyozkin weighs in. 

In the meantime, I've fixed up [my reproducer project](https://github.com/YassinHajaj/quarkus-slow-test-security). It was missing some parts before, but even with those fixes, the results are pretty much the same.

2024-01-15 11:48 UTC, sberyozkin approved these changes
Thanks @YassinHajaj @michalvavrik, PR looks fine, the actual signed token is only provided to meet the IdTokenCredential/etc constructor constraints, in case some application code may want to get the encoded token from it, otherwise it could've been omitted altogether

2024-01-15 14:48 UTC, sberyozkin commented
@YassinHajaj Why did you follow up with another commit, I was about to merge, did the previous run fail ? But now it looks like you'll need to recreate this PR by cherry-picking the first commit only into a new branch, or reverting this merge one.

@gsmet Would it make sense to update https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md with some guidance how to correctly rebase ? I can certainly create a PR but I won't be able to create as clear a recommendation as you can

2024-01-15 14:53 UTC, YassinHajaj commented
Hi @sberyozkin,

Sorry for the inconvenience. 

I synced my fork of quarkus using Github's Sync Fork feature, and instead of rebasing, it just created a merge commit (which I didn't expect I have to admit). 

I'll fix this this evening if it's fine for you (will rebase, squash and force push to modify my fork's history so you'll have only a single commit just like before).

2024-01-15 14:56 UTC, sberyozkin commented
@YassinHajaj Np at all, sure, take your time please

2024-01-15 16:28 UTC, sberyozkin commented
@YassinHajaj since you are planning to do a bit more work on this PR anyway, please move that static field declaration above the instance issuer one, I did not think it was critical for the test module, but the code formatter may fail it and makes sense to keep it consistent anyway

2024-01-17 09:28 UTC, sberyozkin approved these changes

2024-01-17 10:10 UTC, sberyozkin commented
@YassinHajaj See https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#formatting, or simply rebuild it locally with `mvn clean install`, or use a dedicate format goal (I keep forgetting the name though)

2024-01-18 22:58 UTC, YassinHajaj commented
Hi @sberyozkin ,
Yes, I had already configured the formatting in IDEA.
Here are also all the command line statements I used, but none finished in error like in the pipeline or made any change to the file, I wonder what could be wrong here.

- `mvn -DskipTests -DskipITs -DskipDocs -Dinvoker.skip -Dno-format -Dtcks -Prelocations clean install` (just like in the pipeline)
- `mvn -Dquickly`
- `mvn -f test-framework/security-oidc net.revelc.code.formatter:formatter-maven-plugin:2.23.0:format`

Not sure what more I could try out, but if you have any idea, I'm willing to try it out.

2024-01-24 08:12 UTC, YassinHajaj commented
Hello @sberyozkin ,
Do you maybe have any updates on this one ?
I'm clueless about why the build fails as the formatting "works" for me locally as far as I can see (see previous comment).

2024-02-07 16:14 UTC, michalvavrik requested changes
Please apply following patch to fix formatting, then rebase on current main and force push your commit again:
```
diff --git a/test-framework/security-oidc/src/main/java/io/quarkus/test/security/oidc/OidcTestSecurityIdentityAugmentor.java b/test-framework/security-oidc/src/main/java/io/quarkus/test/security/oidc/OidcTestSecurityIdentityAugmentor.java
index 855fa294a75..482300394a8 100644
--- a/test-framework/security-oidc/src/main/java/io/quarkus/test/security/oidc/OidcTestSecurityIdentityAugmentor.java
+++ b/test-framework/security-oidc/src/main/java/io/quarkus/test/security/oidc/OidcTestSecurityIdentityAugmentor.java
@@ -46,7 +46,7 @@ public class OidcTestSecurityIdentityAugmentor implements TestSecurityIdentityAu
             privateKey = KeyUtils.generateKeyPair(2048).getPrivate();
         } catch (NoSuchAlgorithmException ex) {
             throw new RuntimeException(ex);
-        }        
+        }
     }
 
     public OidcTestSecurityIdentityAugmentor(Optional<String> issuer) {
```

2024-02-08 09:53 UTC, michalvavrik commented
@sberyozkin time to merge

2024-02-10 11:44 UTC, merged