Update native configuration file best practices
quarkusio/quarkus pull request #38186
Opened 2024-01-15 08:37 UTC by galderz

Placing custom configuration files in `META-INF/native-image/<group-id>/<artifact-id>` is the best way. It doesn't get in the way of what Quarkus generates, works out of the box without additional configuration and does not produce any native build warnings. Alternative methods have been removed to avoid confusion.

2024-01-15 09:53 UTC, geoand commented
Is this related to https://github.com/quarkusio/quarkus/pull/38118?

2024-01-15 10:13 UTC, zakkak commented
> Is this related to #38118?

Yes, IMO we need a combination of these two PRs.

2024-01-18 08:33 UTC, zakkak commented
> This PR is the result of my own experiments.

@galderz sure, I think what @gsmet wanted to highlight here is that both PRs are touching the same issue. And IMO they should be combined to give the best result.

2024-01-18 08:34 UTC, geoand commented
@zakkak exactly

2024-01-19 16:17 UTC, Sanne approved these changes

2024-01-24 05:54 UTC, galderz commented
Hmm, looking at https://github.com/quarkusio/quarkus/pull/38118, the changes there are minimal and still suggests using an experimental flag that you get a warning with (`ResourceConfigurationFiles` et al). So I favour my changes instead of #38118.

2024-01-24 07:32 UTC, zakkak requested changes
As mentioned in https://github.com/quarkusio/quarkus/pull/38118#pullrequestreview-1840616344

@galderz it looks like @dliubars updated https://github.com/quarkusio/quarkus/pull/38118 and it now only includes the following changes (i.e. it no longer suggests using experimental options) which are currently missing from this PR:

1. replace references to resources-config.json with resource-config.json
2. replace references to reflection-config.json with reflect-config.json

I suggest you either:

1. merge https://github.com/quarkusio/quarkus/pull/38118 and rebase this PR
or
2. cherry-pick @dliubars commit (e911584bec477a80a3fb4ec86ead8ddbe1ce51f2) in your branch

2024-02-02 11:03 UTC, galderz commented
I merged #38118 and I've now rebased this PR with the changes there.

2024-02-07 10:05 UTC, zakkak approved these changes
LGTM. Just added a suggestion that IMO makes the corresponding sentence a bit easier to read.

2024-02-07 10:05 UTC, zakkak commented on docs/src/main/asciidoc/writing-native-applications-tips.adoc
> +By placing them there, there is no additional configuration parameters that need to be passed into the native build.
```suggestion
This way they will be automatically parsed by the native build, without additional configuration.
```

2024-02-09 16:28 UTC, geoand approved these changes

2024-02-09 16:28 UTC, merged