Bubble up WebApplicationExceptions in RestDataResourceMethodListener implementations
quarkusio/quarkus pull request #38281
Opened 2024-01-18 14:52 UTC by gastaldi

- Fixes #35169

2024-02-06 16:51 UTC, FroMage approved these changes, later dismissed
This looks logical.

2026-04-26 23:43 UTC, gastaldi commented
Fixed the reactive counterpart as well

2026-04-27 12:38 UTC, FroMage requested changes
I think the reactive side is not tested.

2026-04-27 15:09 UTC, FroMage submitted a review, later dismissed

2026-04-27 15:32 UTC, gastaldi commented
Oops, tests are failing, let me check again

2026-04-28 08:01 UTC, FroMage approved these changes

2026-04-28 08:01 UTC, merged