Avoid dots in config doc ids as it's causing issues for downstream
quarkusio/quarkus pull request #38430
Opened 2024-01-26 18:22 UTC by gsmet

I think I went through all the links pointing to generated config doc...

/cc @quarkusio/documentation 
/cc @yrodiere you might want to check I didn't break anything in your doc, even if I tried to be thorough and use cross references to enable the checks

2024-01-26 18:36 UTC, gsmet commented
@MichalMaler for now, I marked it for 3.7 only but I could be convinced to backport it to 3.2 if needed.

2024-01-26 19:07 UTC, MichalMaler approved these changes

2024-01-26 19:10 UTC, MichalMaler commented
@gsmet Hey! This is awesome!
Thank you so much!
Will test it on Monday. Yes, we will need this on 3.2, just for our testing and for others to get familiar with the PV1 publishing process and debugging.

2024-01-29 08:38 UTC, yrodiere requested changes
LGTM apart from a few oversights, see suggestions below.

Also, while I'm absolutely not blocking this PR for that reason, I don't like that pretty much all links to the Quarkus documentation that I've posted on the web so far will get broken because of this. IMO whatever bug in downstream tools led to this PR should be fixed in downstream tools instead.

2024-01-29 08:38 UTC, yrodiere commented on core/processor/src/main/java/io/quarkus/annotation/processor/generate_doc/DocFormatter.java
> +        string = string.replaceAll("[^\\w-_]", "-").replaceAll("-{2,}", "-");
So we're breaking every single link pointing to Quarkus configuration properties from other websites? I left quite a few of those out there, on stackoverflow, Zulip, Discourse, GitHub, ...

Can we add a secondary anchor for the deprecated, dot-containing id?

2024-01-29 08:38 UTC, yrodiere commented on docs/src/main/asciidoc/hibernate-search-orm-elasticsearch.adoc
> +by setting <<quarkus-hibernate-search-orm-elasticsearch_quarkus.hibernate-search-orm.coordination.strategy,`quarkus.hibernate-search-orm.coordination.strategy`>>
```suggestion
by setting <<quarkus-hibernate-search-orm-elasticsearch_quarkus-hibernate-search-orm-coordination-strategy,`quarkus.hibernate-search-orm.coordination.strategy`>>
```

2024-01-29 08:38 UTC, yrodiere commented on docs/src/main/asciidoc/hibernate-search-orm-elasticsearch.adoc
> +<<quarkus-hibernate-search-orm-elasticsearch_quarkus.hibernate-search-orm.indexing.plan.synchronization.strategy,`quarkus.hibernate-search-orm.indexing.plan.synchronization.strategy`>>
```suggestion
<<quarkus-hibernate-search-orm-elasticsearch_quarkus-hibernate-search-orm-indexing-plan-synchronization-strategy,`quarkus.hibernate-search-orm.indexing.plan.synchronization.strategy`>>
```

2024-01-29 08:38 UTC, yrodiere commented on docs/src/main/asciidoc/hibernate-search-orm-elasticsearch.adoc
> +* <<quarkus-hibernate-search-orm-outboxpolling_quarkus.hibernate-search-orm-coordination-entity-mapping-outbox-event-uuid-type,`quarkus.hibernate-search-orm.coordination.entity-mapping.outbox-event.u
This looks fine, but I couldn't check it because of #38443

2024-01-29 08:38 UTC, yrodiere commented on docs/src/main/asciidoc/hibernate-search-orm-elasticsearch.adoc
> +* <<quarkus-hibernate-search-orm-outboxpolling_quarkus.hibernate-search-orm-coordination-entity-mapping-outbox-event-uuid-type,`quarkus.hibernate-search-orm.coordination.entity-mapping.outbox-event.u
Well actually I could check it, dumb me. Please ignore this.

2024-01-29 08:53 UTC, yrodiere requested changes

2024-01-29 08:53 UTC, yrodiere commented on docs/src/main/asciidoc/hibernate-search-orm-elasticsearch.adoc
> +* <<quarkus-hibernate-search-orm-outboxpolling_quarkus.hibernate-search-orm-coordination-entity-mapping-outbox-event-uuid-type,`quarkus.hibernate-search-orm.coordination.entity-mapping.outbox-event.u
```suggestion
* <<quarkus-hibernate-search-orm-outboxpolling_quarkus-hibernate-search-orm-coordination-entity-mapping-agent-catalog,`quarkus.hibernate-search-orm.coordination.entity-mapping.agent.catalog`>>
* <<quarkus-hibernate-search-orm-outboxpolling_quarkus-hibernate-search-orm-coordination-entity-mapping-agent-schema,`quarkus.hibernate-search-orm.coordination.entity-mapping.agent.schema`>>
* <<quarkus-hibernate-search-orm-outboxpolling_quarkus-hibernate-search-orm-coordination-entity-mapping-agent-table,`quarkus.hibernate-search-orm.coordination.entity-mapping.agent.table`>>
* <<quarkus-hibernate-search-orm-outboxpolling_quarkus-hibernate-search-orm-coordination-entity-mapping-agent-uuid-gen-strategy,`quarkus.hibernate-search-orm.coordination.entity-mapping.agent.uuid-gen-strategy`>>
* <<quarkus-hibernate-search-orm-outboxpolling_quarkus-hibernate-search-orm-coordination-entity-mapping-agent-uuid-type,`quarkus.hibernate-search-orm.coordination.entity-mapping.agent.uuid-type`>>
* <<quarkus-hibernate-search-orm-outboxpolling_quarkus-hibernate-search-orm-coordination-entity-mapping-outbox-event-catalog,`quarkus.hibernate-search-orm.coordination.entity-mapping.outbox-event.catalog`>>
* <<quarkus-hibernate-search-orm-outboxpolling_quarkus-hibernate-search-orm-coordination-entity-mapping-outbox-event-schema,`quarkus.hibernate-search-orm.coordination.entity-mapping.outbox-event.schema`>>
* <<quarkus-hibernate-search-orm-outboxpolling_quarkus-hibernate-search-orm-coordination-entity-mapping-outbox-event-table,`quarkus.hibernate-search-orm.coordination.entity-mapping.outbox-event.table`>>
* <<quarkus-hibernate-search-orm-outboxpolling_quarkus-hibernate-search-orm-coordination-entity-mapping-outbox-event-uuid-gen-strategy,`quarkus.hibernate-search-orm.coordination.entity-mapping.outbox-event.uuid-gen-strategy`>>
* <<quarkus-hibernate-search-orm-outboxpolling_quarkus-hibernate-search-orm-coordination-entity-mapping-outbox-event-uuid-type,`quarkus.hibernate-search-orm.coordination.entity-mapping.outbox-event.uuid-type`>>
```

2024-01-29 11:53 UTC, MichalMaler commented
@yrodiere  Hello Yoann,

I think you at least deserve to know why this is happening. RHBQ was stuck for a long time on the old and unsupported publishing platform Pantheon II. We implemented a few workarounds to make publishing possible, yet operating on that tool was painful. Also, we were the last team there; the others had already fled to something else.

While the migration to the older, but technically savvier brother, Pantheon 1, offers many benefits and solves hundreds of small issues, it causes the one we are resolving right now.

I asked Guillaume if the transformation of these links and IDs could be part of our script, but he proposed this approach and unification. I am sorry to hear that it causes some problems, but once this is resolved, we should be in a much better position and operate on an overall better publishing tool.

On behalf of the entire docs team, I want to apologize for any additional workload and problem-solving these changes brings.

2024-01-29 12:37 UTC, yrodiere commented
I understand, Michal. Thanks for the details.

I'd simply suggest that moving forward, the docs team considers the impact of breaking links. And I don't mean just in this specific case: I suspect we've had several similar changes in the past, like renaming a guide, or simply changing headings that relied on [auto-generated anchors](https://docs.asciidoctor.org/asciidoc/latest/macros/xref/#anchors).

It's not that it causes additional work for upstream, it's more that it drastically reduces the amount of time that that work will remain useful. We have lots of discussions and questions/answers referencing upstream docs out there, and every time we make a change like this, we make a few of those discussions obsolete, by preventing people to follow relevant links. That's basically getting rid of part of the "documentation ecosystem", one piece at a time.

I understand we can't keep compatibility forever, but I think that problem needs to at least be considered, and mitigated where possible (which is not here, from what I understand).

2024-01-29 13:03 UTC, MichalMaler commented
@yrodiere 
The changes we need can be part of the script we are already using, so that Upstream content remains the same, and RHBQ repo will get what it needs. I am just not good in programming to propose something that could be applicable.
I sent you an email with our  bccutil's problem description, just so you have all the info you would need to make a call.

2024-01-29 13:19 UTC, MichalMaler commented
@gsmet Hello Guillaume. That 3.2 backport would be nice, but it is not mandatory.
If it will not be a fast forward merge that would required some additional work, please drop the initiative. Dont want to require your time on something that is not 100% needed, as this ID transformation.
If it is easy to do, I will be glad. 

Also, as I wrote in our email conversation, we will be good with both solutions:
1. Applying this transformation only on our RHBQ set of filles that will be applied during the single-sourcing.
2. Or direct patch as you are proposing here.

Much thanks.

2024-01-29 17:08 UTC, gsmet commented
> The changes we need can be part of the script we are already using, so that Upstream content remains the same

Unfortunately, it's not easy to identify these links in a reliable way, thus why I did the change for upstream too.

It's something we will have to live with.

2024-01-29 17:24 UTC, yrodiere commented on docs/src/main/asciidoc/hibernate-search-orm-elasticsearch.adoc
> +  <<quarkus-hibernate-search-orm-elasticsearch_quarkus-hibernate-search-orm-elasticsearch-version-check.enabled,`quarkus.hibernate-search-orm.elasticsearch.version-check.enabled`>>
@gsmet looks like you erased my commit, so I opened a separate PR: https://github.com/quarkusio/quarkus/pull/38459

You might still want to apply this:

```suggestion
  <<quarkus-hibernate-search-orm-elasticsearch_quarkus-hibernate-search-orm-elasticsearch-version-check-enabled,`quarkus.hibernate-search-orm.elasticsearch.version-check.enabled`>>
```

2024-01-30 09:36 UTC, yrodiere approved these changes

2024-01-30 18:18 UTC, merged

2024-01-31 22:02 UTC, ppalaga commented
Ouch, this hits also Camel Quarkus and Quarkus CXF. We can invest the work in our current branches, but pretty please do not backport this to 3.2.