Add Hibernate REST data codestart
quarkusio/quarkus pull request #38524
Opened 2024-02-01 11:21 UTC by aureamunoz

Since we are working with a Quarkus plugin for Backstage (qshift)we would like to be able to generate a project exposing a simple entity via REST resources.

cc @iocanel , @geoand

2024-02-01 11:23 UTC, geoand commented
cc @ia3andy

2024-02-05 09:21 UTC, ia3andy requested changes
It seems you need to:
- Add your codestart to the ignore list (as it require extra stuff to be tested): https://github.com/quarkusio/quarkus/blob/main/integration-tests/devtools/src/test/java/io/quarkus/devtools/codestarts/quarkus/QuarkusCodestartBuildIT.java#L39
- Generate the snapshots by running `testContent` with `-Dsnap` property enabled

2024-02-05 09:22 UTC, ia3andy commented on devtools/project-core-extension-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/hibernate-orm-rest-data-codestart/base/src/main/resources/import.sql
I think we shouldn't add this file as it could easily conflict with other codestarts

2024-02-05 09:23 UTC, ia3andy commented on integration-tests/devtools/src/test/java/io/quarkus/devtools/codestarts/quarkus/HibernateOrmRestDataCodestartIT.java
> +            .languages(JAVA, KOTLIN)
```suggestion
            .languages(JAVA)
```

2024-02-07 17:00 UTC, ia3andy approved these changes
Thanks!

2024-02-07 17:01 UTC, merged