Upgrade vaadin and related versions for Dev UI
quarkusio/quarkus pull request #38579
Opened 2024-02-05 02:37 UTC by phillip-kruger

2024-02-05 15:59 UTC, cescoffier approved these changes

2024-02-06 09:13 UTC, gsmet requested changes
I'd like us to not rush this as I'm not sure it actually solves the issue.

Your rationale for not enforcing the versions was that you wanted extensions like web bundler to be able to use other versions... and in the end we add a new BOM to actually enforce the versions.

I'm not entirely sure it brings us anything in the end.

Could you explain how having a separate BOM actually brings us anything compared to the previous situation of having things in the Quarkus BOM?

2024-02-06 09:37 UTC, phillip-kruger commented
The quarkus bom is used by the user's application, the new bom is only used in die extension deployment module. So now a user can add UI library without Dev UI influence (with or without the web bundler)

2024-02-06 10:05 UTC, maxandersen commented
Unless we want to keep "leaking" devmode only relevant dependencies into all extensions and user apps something gotta give and I think this solution of having a dev-ui bom is the most pragmatic/proper solution - even though it does require many extensions to get updated to have decent build reproducability.

I've asked @phillip-kruger to make a draft PR in a quarkiverse extension to show the exact impact.

Also asked to check how far back this actually impacts us - the assumption is before September quarkus-core was locked by bom and parent-bom but any non-quarkus ext was impacted unless they use quarkus core bom directly. 

And I suggest we write up the alternates in an ADR and make a recorded decision on how we deal with this because we do need those dependencies locked between releases.

2024-02-06 12:29 UTC, maxandersen commented on docs/src/main/asciidoc/writing-extensions.adoc
> +If your extension is NOT part of Quarkus core, you can add this BOM in the dependency management of your extension parent pom to lock the javascript versions:
```suggestion
If your extension is NOT part of Quarkus core, you should add this BOM in the dependency management of your extension parent pom to lock the javascript versions:
```

2024-02-06 17:45 UTC, metacosm commented
So, if I understand correctly, extension developers that wish to leverage components provided by the Dev UI will now need to import this new BOM, right?
If an extension doesn't provide any contribution to the Dev UI, this new BOM can be ignored, right?

2024-02-07 00:07 UTC, phillip-kruger commented
@metacosm no, it always have to be there if the extension use vertx-http. But rather than adding another bom, we might just create a new bom (we are still discussing). I am closing this PR for now, we are rolling back the bom move, and then I'll play with some options.

2024-02-07 00:07 UTC, closed without merging