MicroProfile Telemetry compatibility
quarkusio/quarkus pull request #38707
Opened 2024-02-09 11:35 UTC by radcortez

2024-02-12 10:00 UTC, brunobat requested changes

2024-02-14 12:06 UTC, radcortez commented on extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/TracerProducer.java
> +        return new Span() {
Check this: https://github.com/eclipse/microprofile-telemetry/blob/eefa3e7a8de4006f46f46b20f1cffd2a2e71b3f7/tracing/tck/src/main/java/org/eclipse/microprofile/telemetry/tracing/tck/cdi/SpanBeanTest.java#L56-L96

I think this makes sense.

2024-02-15 12:35 UTC, brunobat approved these changes

2024-02-15 12:35 UTC, brunobat commented on extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/TracerProducer.java
> +        return new Span() {
it does.

2024-02-15 12:35 UTC, merged