list static resources
quarkusio/quarkus pull request #3901
Opened 2019-09-06 07:57 UTC by Dufgui

fix #3851

2019-09-06 15:16 UTC, geoand commented
@emmanuelbernard would you like to verify this since you opened the original issue?

2019-09-07 07:02 UTC, Dufgui commented
ready for review @emmanuelbernard

2019-09-07 13:00 UTC, gsmet requested changes
Please wait for this PR https://github.com/quarkusio/quarkus/pull/3854/files to be in, before merging these changes.

2019-09-07 13:02 UTC, gsmet commented on core/runtime/src/main/java/io/quarkus/runtime/TemplateHtmlBuilder.java
> +            "<div class=\"container content\">\n";
These changes don't look related to the issue at hand and don't seem like an improvement to me.

2019-09-07 13:03 UTC, gsmet commented on core/runtime/src/main/java/io/quarkus/runtime/TemplateHtmlBuilder.java
> +    private static final String HTML_TEMPLATE_END = "</body>\n" +
Again, looks unrelated. Moreover, I think it's wrong because the header explicitly open a div for the content of the page.

Can you get rid of it?

2019-09-07 13:04 UTC, gsmet commented on core/runtime/src/main/java/io/quarkus/runtime/TemplateHtmlBuilder.java
> +            ".component-name {\n" +
This change should be reverted too.

2019-09-07 13:05 UTC, gsmet commented on extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/NotFoundExceptionMapper.java
> +            sb.header("Static Resources");
You're using the header for something it shouldn't be used. That's why you have all those unrelated changes.

2019-09-08 09:21 UTC, Dufgui commented
I remove the header, but I dislike the page layout now:
![image](https://user-images.githubusercontent.com/237211/64486242-cfe71c80-d22a-11e9-8673-632457790b40.png)

2019-09-09 00:22 UTC, stuartwdouglas commented
IMHO we should only be listing .htm and .html files, otherwise this will potentially list a massive amount of files that the developer is not interested in.

2019-09-09 12:14 UTC, emmanuelbernard commented
So a few things "Resource Not Found" is not enough, we need to add back the 404 too "404 - Resource Not Found".

I agree with Stuart that we should list the htm / html files as priority and if there are 0 of them, list the other ones @Dufgui

2019-09-09 19:22 UTC, Dufgui commented
Changed done ;o)
@gsmet @emmanuelbernard @stuartwdouglas

2019-09-11 13:42 UTC, Dufgui commented
@gsmet  any time to review ?

2019-09-11 15:58 UTC, gsmet commented
@Dufgui could you close this one and merge everything in the other one? (or the other way around)

It's really a bad idea to have 2 different PRs for more or less the same thing.

2019-09-11 16:22 UTC, closed without merging

2019-09-11 16:22 UTC, Dufgui commented
replace by https://github.com/quarkusio/quarkus/pull/3921