#39375 JAXB Exception handling
quarkusio/quarkus pull request #39503
Opened 2024-03-16 08:17 UTC by ketola

2024-03-19 14:08 UTC, ketola commented
I'm not sure should I discuss the proposed fix here or in the issue. But here's what I commented in the issue earlier:

Based on my tests in the Draft PR I noticed that the resteasy-reactive-jaxb and resteasy-jaxb behave differently. The reactive implementation returns 500 when an invalid xml is sent and the other one returns 400. My suggestion is that resteasy-reactive-jaxb would be modified to work like resteasy-reactive-jackson works when invalid json is sent -> WebApplicationException resulting in http 400.
I could go on and try to fix it if this sounds like a plan? I would also need to add an integration test module as I have done in the pr to bring up the issue and verify the fix.

2024-03-23 07:05 UTC, ketola commented
Well I went ahead and implemented the exception handling in a similar way that it is done in jackson as it was not a big task and I changed the status to ready for review. 
But for the future, if I would want some feedback for the plan on how I would do the fix before actually doing it, how should I go about it? Should I just change the status to ready for review even though the fix is not finished or tag the reviewer in a pr comment?

2024-03-25 12:14 UTC, gsmet requested changes
Thanks for the pull request.

I agree that the changes make sense and thank you for having a look into it and providing a pull request.

One minor gripe though: I would prefer if the test could be moved to https://github.com/quarkusio/quarkus/tree/main/extensions/resteasy-reactive/rest-jaxb/deployment/src/test/java/io/quarkus/resteasy/reactive/jaxb/deployment/test instead.

Adding an IT module means adding several minutes to the native build and I'm not sure it's worth it in this case.
A small test in the deployment module should be easier to add (you will have to adapt your test a bit though, have a look at the other tests that are already in the module).

Thanks!

2024-04-17 16:08 UTC, gsmet approved these changes
Looks great! Thanks.

Let's get CI to run and merge it once it is green.

2024-04-22 09:34 UTC, merged

2024-04-22 09:35 UTC, gsmet commented
Merged! Thanks for your contribution!