Use URL path template when tracing REST clients where possible
quarkusio/quarkus pull request #39534
Opened 2024-03-18 21:11 UTC by luneo7

Use URL path template in the REST client span names where possible.

Using raw Vert.x web client is not possible right now since all the instrumentation happens after `UriTemplate` is applied so we have only the full URI... this would make is have infinite cardinality since a path variable can lead to infinite URLs. Ideally the Vert.x web client could expose the used `UriTemplate` during tracing or for `metrics` (as we have with VertxRoute right now) so we could extract it and build the span name with the template as well.

Now RestEasy clients using Vert.x or not will be with a span name of `{method} {urlPathTemplate}` as we had before =]

- Closes https://github.com/quarkusio/quarkus/issues/39457

2024-03-18 22:06 UTC, douglasmelo approved these changes

2024-03-18 22:25 UTC, Filitz approved these changes

2024-03-19 09:11 UTC, brunobat commented
@luneo7 The IT tests using the client will need to be updated as well.

2024-03-19 09:13 UTC, brunobat requested changes
@luneo7 The IT tests using the client will need to be updated as well.

2024-03-19 16:00 UTC, luneo7 commented
> @luneo7 The IT tests using the client will need to be updated as well.

Done =]

2024-03-20 12:21 UTC, brunobat approved these changes
Thanks @luneo7!

2024-03-21 13:53 UTC, luneo7 commented
@brunobat @geoand do we need something more to get this merged? Thanks 😊

2024-03-21 13:54 UTC, geoand commented
@brunobat can merge it at his discression :)

2024-03-21 14:32 UTC, merged

2024-03-21 15:47 UTC, luneo7 commented
Thank you! Could this be backported as well?

2024-03-22 16:43 UTC, brunobat commented
Added the label.

2024-03-23 16:40 UTC, michalvavrik commented
This is breaking change and not exactly fun to look for what changed. Please add a note to the migration guide for people like me, thank you.

2024-03-23 16:58 UTC, michalvavrik commented
My point is that `operationNames` has changed, so every historical data that executes aggregation needs to add rules that  for period between x and y they should aggregate operation names xyz etc. So it is something users need to know.

2024-03-25 09:27 UTC, brunobat commented
Added a wiki entry. @michalvavrik

2024-03-25 09:28 UTC, michalvavrik commented
Thank you