Added setLocale for Qute Templates
quarkusio/quarkus pull request #39947
Opened 2024-04-08 11:59 UTC by geertvanleemputten

Added convenience method to indicate how to localize qute templates in cases where this needs to be done manually.

eg: mail templates

2024-04-08 12:42 UTC, gastaldi requested changes
Have you built the code locally? It looks incorrect to me

2024-04-08 13:47 UTC, geertvanleemputten commented
I was unable to build due to:
Could not find artifact io.quarkus:quarkus-enforcer-rules:jar:999-SNAPSHOT

Included your changes now.

2024-04-08 15:43 UTC, gastaldi commented
Looks good. Can you please squash all your commits into a single one? Thanks!

2024-04-08 18:12 UTC, geertvanleemputten commented
squashed

2024-04-09 16:04 UTC, gastaldi commented
There are conflicts. Can you make sure your branch is rebased onto the latest `main`?

2024-04-09 16:06 UTC, gastaldi commented on independent-projects/qute/core/src/main/java/io/quarkus/qute/TemplateInstance.java
> +        return setAttribute("locale", locale);
```suggestion
        return setAttribute(MessageBundles.ATTRIBUTE_LOCALE, locale);
```

2024-04-10 13:07 UTC, closed without merging