[3.8] -  Vert.x 4.5.7 update
quarkusio/quarkus pull request #40044
Opened 2024-04-12 12:22 UTC by cescoffier

2024-04-12 14:40 UTC, cescoffier commented
I'm not sure; I had to do specific things and didn't have to add a lot of stuff to that PR.

2024-04-12 14:43 UTC, cescoffier commented
Added another look to the backport branch, it seems OK - the 3.2 backport is way more tricky. 

I ran my tests against the 6 versions of GraalVM we "support" (22 EE / CE, 21 EE / CE, 17 EE / CE).

2024-04-12 14:44 UTC, cescoffier commented
@gsmet BTW, your PR had a runtime init that should not be necessary in the NettyProcessor. The JdkSslClientContext does not lead to a problematic build time initialization.

2024-04-12 14:56 UTC, gsmet requested changes
> BTW, your PR had a runtime init that should not be necessary in the NettyProcessor. The JdkSslClientContext does not lead to a problematic build time initialization.

I didn't invent it. It was part of the PRs I backported.
I would prefer we follow the usual process except if strictly necessary as diverging might cause unnecessary issues.

I had no issue backporting the PRs so that's what I did. I added several comments inline with questions as this PR has more changes than what I actually backported and I don't know if there are good reasons.

2024-04-12 14:56 UTC, gsmet commented on bom/application/pom.xml
> +        <jboss-threads.version>3.6.0.Final</jboss-threads.version>
Are these upgrades really necessary? They are not in my PR but I'm not sure they are?

2024-04-12 14:56 UTC, gsmet commented on independent-projects/resteasy-reactive/pom.xml
> +        <smallrye-common.version>2.3.0</smallrye-common.version>
Is this strictly necessary? I'm not sure it's in line with what we have in the BOM so this is problematic.

2024-04-14 16:52 UTC, cescoffier commented
@gsmet The problem is that the thing you backported has not being tested on all the variants and is likely going to break. Let's sync up tomorrow.

2024-04-16 06:27 UTC, cescoffier commented
The regular backport is good enough.

2024-04-16 06:27 UTC, closed without merging