Explain how logging can be configured in the smallrye-graphql-client guide
quarkusio/quarkus pull request #40073
Opened 2024-04-15 12:51 UTC by jmini

Based on this discussion: 
https://stackoverflow.com/questions/77184741/how-to-log-http-requests-made-by-quarkus-graphql-client/

2024-04-15 13:36 UTC, jmartisk requested changes

2024-04-15 13:36 UTC, jmartisk commented on docs/src/main/asciidoc/smallrye-graphql-client.adoc
> +For debbuging purpose, it is possible to log the request generated by the typesafe client and the response sent back by the server by changing the log level of the `io.smallrye.graphql.client` catego
Please fix debbuging to debugging

Otherwise, LGTM!

2024-04-15 15:10 UTC, gsmet requested changes
Thanks for this nice addition.

Please see @jmartisk and the two additional comments I added.
Nothing big really.

Thanks!

2024-04-15 15:10 UTC, gsmet commented on docs/src/main/asciidoc/smallrye-graphql-client.adoc
> +quarkus.log.category.\"io.smallrye.graphql.client\".min-level=TRACE
I'm surprised by the `\` here? I don't think they are needed?

2024-04-15 15:10 UTC, gsmet commented on docs/src/main/asciidoc/smallrye-graphql-client.adoc
> +```
Please use a source block here with `[source,properties]`.

We had a few issues with the Markdown style when pushing to the website.

2024-04-16 08:06 UTC, gsmet approved these changes
I adjusted things a bit, it should be ready to go once CI is green.

2024-04-16 09:30 UTC, jmartisk approved these changes

2024-04-16 09:30 UTC, merged