Fix Incorrect Kubernetes Port Annotation for Management Interface
quarkusio/quarkus pull request #40409
Opened 2024-05-02 08:20 UTC by BrunoSena97

resolves #37904

Changes include:
- Updated the `createAnnotations` method in the `KindProcessor` class to check if the management interface is enabled and if the annotation key is `"prometheus.io/port"`.
- If both conditions are true, the method now produces a new `KubernetesAnnotationBuildItem` with the key `k`, the value `managementPort`, and the target `KIND`.
- Otherwise, it produces a new `KubernetesAnnotationBuildItem` with the key `k`, the value `v`, and the target `KIND`.

2024-05-10 11:11 UTC, gsmet commented
@iocanel could you have a look at this one?

2024-05-14 13:23 UTC, iocanel requested changes
Thank you very much for taking a stub at it.

Is there a reason why this is specific to `kind`. My understanding is that this is something that should be applied to all targets and not just kind. So, I think that a better place for this might be somewhere around here: 

https://github.com/quarkusio/quarkus/blob/b8e7635db2483d79df024b561ba77ecaa87dbc85/extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java#L1006.

More specifically, I would just ensure that this line: https://github.com/quarkusio/quarkus/blob/b8e7635db2483d79df024b561ba77ecaa87dbc85/extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesCommonHelper.java#L1026 uses the right port.

Finally, we definitely need an integration test for this. Do let me know if you need a pointer for that.

2024-06-06 16:15 UTC, gsmet commented
@BrunoSena97 are you willing to pursue this? Thanks!

2024-11-10 17:15 UTC, cescoffier commented
@BrunoSena97 Are you having a look to @iocanel 's review?

2024-12-02 07:53 UTC, cescoffier commented
@iocanel What should be do here? Do we want this feature?

2024-12-05 14:50 UTC, iocanel commented
@cescoffier: I think that we do. I would keep this open, just in case someone will pick this up.

2025-03-21 11:29 UTC, elmodeer commented
Hello @iocanel I would like to give this a try. Could you point me to where the integration test should be or to a similar existing one ?

2025-03-21 12:18 UTC, iocanel commented
@elmodeer thank you for picking this up. Here's an example test that checks if the generated resources are as they are expected to be: https://github.com/quarkusio/quarkus/blob/main/integration-tests/kubernetes/quarkus-standard-way/src/test/java/io/quarkus/it/kubernetes/KubernetesWithMetricsNoAnnotationsTest.java

2025-03-21 21:53 UTC, elmodeer commented
thanks @iocanel. I opened a PR here: https://github.com/quarkusio/quarkus/pull/46947

2026-08-10 11:25 UTC, radcortez commented
Superseded by #46947

2026-08-10 11:25 UTC, closed without merging