Resteasy without Undertow
quarkusio/quarkus pull request #4052
Opened 2019-09-16 21:42 UTC by patriot1burke

* quarkus-resteasy no longer pulls in undertow. It instead runs directly on Vert.x Web
* To run resteasy within a servlet container just add quarkus-undertow to pom dependencies
* Adds vertx StaticHandler for META-INF/resources files.
* Keeps exception mappers

2019-09-17 04:39 UTC, stuartwdouglas requested changes

2019-09-17 04:39 UTC, stuartwdouglas commented on extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/standalone/VertxBlockingOutput.java
> +                event.printStackTrace();
This should use a logger

2019-09-18 19:36 UTC, patriot1burke commented on extensions/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java
> +            deployment.setRegisterBuiltin(true);
Will save this for another day, ok?

2019-09-18 19:40 UTC, patriot1burke commented on extensions/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java
> +            deployment.setRegisterBuiltin(true);
I'm just not sure if resteasy requires refactoring to support this.

2019-09-18 23:14 UTC, stuartwdouglas commented
I will see what others think, but I want to fork a 0.23 branch now and merge this ASAP so we can start to make progress

2019-09-19 08:47 UTC, stuartwdouglas approved these changes

2019-09-19 08:47 UTC, merged