Update panache documentation: zero-based page index fix
quarkusio/quarkus pull request #40703
Opened 2024-05-17 14:30 UTC by TyaraSchetgens

To fetch page 7, Page with index 6 needs to be provided as index is zero-based
![image](https://github.com/quarkusio/quarkus/assets/19426823/74211f29-95d9-4564-b5f0-306895cbfa1b)

2024-05-17 15:30 UTC, gsmet reviewed
LGTM from what I see of the code but I must admit, it's a bit weird to use 0-based pages.

As a user, you will always talk about page 1, not page 0.

2024-05-17 15:42 UTC, TyaraSchetgens commented
> LGTM from what I see of the code but I must admit, it's a bit weird to use 0-based pages.
> 
> As a user, you will always talk about page 1, not page 0.

Agreed. In our code we are doing page - 1 everywhere. It is a bit messy.

Would it be feasable to make the page index start at 1 instead of 0?

2024-05-17 15:51 UTC, gsmet commented
That would probably break all existing applications so that's probably something we won't be able to do unfortunately :/

2024-06-05 13:15 UTC, FroMage requested changes
I don't know about that. The javadocs of `Page` clearly mention it's zero-based. So "page 0" is the first page, and "page 7" is the eighth page. The comment you're refering to does not say "7th page" but "page 7", so it looks correct to me.

It's the same in most of the Java language. A `List`'s first element will be at index 0.

Of course, both 0-based and 1-based indexing are valid, and depend on where they're being used. Spoken languages tend to use 1-based indexing, while math and C-inspired programming languages use 0-based indexing.

Using 0-based indexing in Java is the most intuitive and regular.

Perhaps this comment in the docs would have been clearer?

```java
// get page 7 (pages are 0-based, so this is the 8th page in English)
List<Person> page7 = livingPersons.page(Page.of(7, 25)).list();
```

Would that help?

2024-06-07 09:00 UTC, gsmet commented
> I don't know about that. The javadocs of Page clearly mention it's zero-based. So "page 0" is the first page, and "page 7" is the eighth page. The comment you're refering to does not say "7th page" but "page 7", so it looks correct to me.

I think you're considering that from a programming POV whereas pages are more often than not used in the UI.

So the initial gripe was really about I have my pagination with page 1-7 (because that's what you have on the user side) and I have to translate it to 0-based pages before pushing it to Panache. It's not a big deal but pagination is a lot about UI and how you present the data.
Now I don't think either perpective is right or wrong, it's just not very intuitive when working on the UI side.

That being said, this ship has sailed so we just need to make sure the doc is clear.

2024-06-07 09:41 UTC, FroMage commented
From a UI perspective you're right, but that's not the job of backends or APIs. The same is true when iterating indexes using Qute, everyone is used to adding `+1` for humans.

2024-11-10 17:14 UTC, cescoffier commented
@gsmet @FroMage What should we do here?

2024-11-12 10:02 UTC, FroMage commented
I'd say we can close this 🤷

2024-11-14 06:14 UTC, cescoffier commented
Closing - see comment.

2024-11-14 06:14 UTC, closed without merging