Docker-build fails to detect podman
quarkusio/quarkus pull request #41100
Opened 2024-06-10 17:26 UTC by edeandrea

Although I can't reproduce #41085 I found some things which may cause it. See the conversation history in #41085.

Fixes #41085

2024-06-10 17:47 UTC, edeandrea commented
FYI this is an addition to #40729, so it'll have to land wherever that lands.

2024-06-11 05:26 UTC, cescoffier requested changes
Following the reported issue, I would add a warning when the docker extension is used and fallback on podman. Thus we inform the user that using the specific podman extension is better.

Now there are teams where some members use docker and some podman. In this case what happens if we use both extensions?

2024-06-11 11:46 UTC, edeandrea commented
> Now there are teams where some members use docker and some podman. In this case what happens if we use both extensions?

If they don't care about doing anything podman-specific (like building multi-arch images) then they can continue doing what they are doing today.

If they want to do things which deviate from common functionality (like building multi-arch images) then they would need both extensions & to configure both extensions, and then use `quarkus.container-image.builder=docker|podman` to set which one wins.

2024-06-11 12:05 UTC, edeandrea commented
> Following the reported issue, I would add a warning when the docker extension is used and fallback on podman. Thus we inform the user that using the specific podman extension is better

@cescoffier this is done. I've rebased my commits into a single commit.

2024-06-11 13:59 UTC, cescoffier approved these changes

2024-06-11 14:23 UTC, gsmet commented
Not sure what's going on but CI looks stuck on this one. I'll see what I can do.

2024-06-12 07:27 UTC, merged

2024-06-12 13:46 UTC, ppalaga commented on core/deployment/src/main/java/io/quarkus/deployment/util/ContainerRuntimeUtil.java
> +    public static ContainerRuntime detectContainerRuntime(ContainerRuntime... orderToCheckRuntimes) {
Due to this change, all callers of `detectContainerRuntime()` will fail with NoSuchMethodException unless they are recompiled. Let me send a PR to get the method back.