Introduce support for the TLS Registry in the REST Client
quarkusio/quarkus pull request #41153
Opened 2024-06-12 09:10 UTC by geoand

- Closes: #41005

2024-06-12 11:21 UTC, cescoffier requested changes
Just a typo in the javadoc.

2024-06-12 11:21 UTC, cescoffier commented on extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java
> +     * `quarkus.mailer` SSL configuration will be used.
Mailer?

2024-06-12 11:31 UTC, geoand commented on extensions/resteasy-classic/rest-client-config/runtime/src/main/java/io/quarkus/restclient/config/RestClientsConfig.java
> +     * `quarkus.mailer` SSL configuration will be used.
Mailer gets a lot of ❤️

2024-06-12 11:33 UTC, geoand commented
Typo fixed

2024-06-12 11:46 UTC, cescoffier approved these changes

2024-06-12 13:26 UTC, merged

2024-06-14 15:54 UTC, gsmet commented
@cescoffier I'm wondering if we should backport this one so that the TLS story is complete?

2024-06-14 15:55 UTC, cescoffier commented
We could. It's isolated enough so it's not too risky.

2024-06-14 16:22 UTC, geoand commented
Yeah, it's pretty much a different code path