add AI category
quarkusio/quarkus pull request #41425
Opened 2024-06-25 12:59 UTC by maxandersen

related to https://github.com/quarkiverse/quarkus-langchain4j/pull/704

@ia3andy the ai category won't be relevant for product nor is the pinned extension in platform so should I remove the pin?

2024-07-11 11:16 UTC, maxandersen commented on devtools/bom-descriptor-json/src/main/resources/catalog-overrides.json
> +      }
```suggestion
      
```

2024-09-20 11:33 UTC, maxandersen commented
@ia3andy any update here?

2024-09-20 12:11 UTC, ia3andy commented
@maxandersen I am not sure what you mean?

2024-09-26 14:48 UTC, maxandersen commented
@ia3andy ok to merge ?

2024-09-26 15:33 UTC, ia3andy approved these changes
LGTM

2024-09-26 15:34 UTC, ia3andy commented on devtools/bom-descriptor-json/src/main/resources/catalog-overrides.json
> +      "description": "Help making Artificial Intgelligence (AI)-infused applications using Large Language Models and more",
```suggestion
      "description": "Help making Artificial Intgelligence (AI)-infused applications using Large Language Models and more"
```

2024-09-26 15:34 UTC, ia3andy requested changes
invalid json

2024-11-10 17:13 UTC, cescoffier commented
@maxandersen Can you apply the suggestion and produce valid JSON :-)

2024-11-12 08:07 UTC, cescoffier commented
@ia3andy Can you do another quick review?

2024-11-12 08:10 UTC, ia3andy approved these changes
LGTM

2024-11-12 08:11 UTC, cescoffier commented
Thanks @ia3andy! That was fast (or very reactive ;-))

2024-11-12 08:11 UTC, merged