Created ad-hoc signed jar for testing filtering of jar file
quarkusio/quarkus pull request #41494
Opened 2024-06-26 19:40 UTC by DShivansh

as mentioned in #40156

2024-06-27 11:19 UTC, gastaldi requested changes
Added some comments. Can you please squash your commits?

2024-06-27 11:19 UTC, gastaldi commented on core/deployment/pom.xml
> +            <artifactId>bcpkix-jdk18on</artifactId>
They are both missing the `<scope>test</scope>`

2024-06-27 11:19 UTC, gastaldi commented on core/deployment/src/test/java/io/quarkus/deployment/pkg/steps/JarResultBuildStepTest.java
> +            jarFile.stream().map(JarEntry::getName).forEach(System.out::println);
This can be removed

2024-06-27 13:53 UTC, gastaldi commented on core/deployment/src/test/java/io/quarkus/deployment/pkg/steps/JarResultBuildStepTest.java
> +    void should_unsign_jar_when_filtered(@TempDir Path tmp) throws Exception {
Can you keep the same parameter name? That will make it easier to notice what really changed here

2024-06-27 13:54 UTC, gastaldi commented on core/deployment/src/test/java/io/quarkus/deployment/pkg/steps/JarResultBuildStepTest.java
> +        calendar.setTime(startDate);
AFAIK a Calendar is already initialized with the current time, why are you setting the time here?

2024-06-30 17:10 UTC, DShivansh commented
@gastaldi  can you please re-review it?

2024-07-01 02:34 UTC, gastaldi requested changes
The  ode looks okay, but you need to squash all your commits

2024-07-02 19:00 UTC, DShivansh commented
Hey @gastaldi 
I think I have messed something in git and I am not able to fix the history
can I create another pull request?

2024-07-02 19:07 UTC, gastaldi commented
You can simply force push `git push -f` to your `jar-on-the-fly` branch and this PR will be updated automatically

2024-07-03 06:33 UTC, DShivansh commented
force push from the new branch?

2024-07-03 07:20 UTC, DShivansh commented
@gastaldi I have squashed all the commits.

2024-07-03 10:26 UTC, gastaldi approved these changes
LGTM now, good job!

2024-07-03 10:32 UTC, gastaldi commented
@DShivansh you need to build the sources and force push again with `mvn process-sources `  to fix the formatting issues

2024-07-04 12:47 UTC, merged

2024-07-04 12:47 UTC, gastaldi commented
Thanks!

2024-07-10 05:20 UTC, galderz commented
Thanks @DShivansh!