Remove deprecated cloning pattern config which isn't really useful anymore
quarkusio/quarkus pull request #41621
Opened 2024-07-02 13:28 UTC by holly-cummins

#40601 dropped support for the class-clone-pattern configuration, but didn’t remove the documentation. The configuration wasn’t really needed anymore, since #40601 cloned almost everything. 

My amendment of #40601 to work around the “do not clone everything” problem clones less, and does reintroduce have the support for configuring the cloning. However, I think even in this scenario, the config is not useful. The config was introduced as part https://github.com/quarkusio/quarkus/pull/17306, to make Pact work, but I've run the Pact tests against a local quarkus build and Pact works fine without the config. 

I’ve searched through public codebases, and I do not believe this configuration is widely used. https://github.com/search?q=quarkus.test.class-clone-pattern%3D&type=code shows only 6 usages of `quarkus.test.class-clone-pattern` in configuration files, all in commented out boilerplate. Searching for the camel case version, `CLASS_CLONE_PATTERN=` gave no instances: https://github.com/search?q=CLASS_CLONE_PATTERN%3D&type=code
In my searches, I added the equals sign so filter out config documentation and forks of the quarkus repo, which do reference the property name. 

The default value of the configuration is `java.*`, so removing the config does mean we no longer attempt to clone `java.*` classes. I don’t see any benefit in doing that cloning, but be aware this is a functional change.

2025-03-13 16:04 UTC, dmlloyd approved these changes
LGTM

2025-03-13 17:49 UTC, holly-cummins commented
The windows job also failed on https://github.com/holly-cummins/quarkus/actions/runs/13838828052, my branch's run of this change, so I should probably investigate. 
Or optimistically rebase and see if I just rebased at a bad point last time. :)

2025-03-13 19:19 UTC, dmlloyd commented
The failure makes sense: `io.quarkus.it.main.ParameterResolverTest.testSerializableParameterResolverFallbackToXStream(List)` which presumably we would no longer need to test. In other words, the failure is a success! :-)

2025-03-13 19:22 UTC, holly-cummins commented
> The failure makes sense: `io.quarkus.it.main.ParameterResolverTest.testSerializableParameterResolverFallbackToXStream(List)` which presumably we would no longer need to test. In other words, the failure is a success! :-)

Good point! I'll double-check if there's anything of value in that test case, and if not, I'll remove the test case and respin. I should have waited for the summary before thinking about the failures.

2025-03-14 09:13 UTC, holly-cummins commented
Hmm, looking at the test, despite the name, it seems like the expectations in the test are perfectly reasonable. I also can't see, from staring at the diff, why my changes make them fail – so I'll have to step through in the debugger.

2025-03-14 14:28 UTC, holly-cummins commented
I've had a look at the code, and what's happening is that we have two ways of cloning. One is a complex set of checks, using a `Supplier` in some branches, and doing something else in some other branches. The other is using @dmlloyd's  `NewSerializingClassLoader`. 

If a class matches the clone pattern config, it always goes down the path of using `NewSerializingClassLoader`. Otherwise, on the other path, we sometimes clone and sometimes don't, depending how hard it looks. So the name of the config property is a bit confusing. 

The docs for the config parameter say that if a class name matches then it will be cloned into the Quarkus ClassLoader even if it is in a parent first artifact." Our default setting for the property is `java.*`, which means that we'd always try and clone `java.*` classes, which is a weird thing to do, because those classes will always be in the system classloader, so why would we want to try and clone them? 
     
But. What if the parameter is a Collection, which is what's happening for this test? On the `NewSerializingClassLoader` path we succeed in cloning it, and on the other path we decide it's too hard and don't try. That behaviour difference shouldn't exist, and isn't really related to the notional purpose of the config property, and it's all a bit of a mess and we should harmonise the two code paths. 

However, https://github.com/quarkusio/quarkus/pull/34681 makes all of the cloning code completely obsolete, so I don't think we need to worry about fixing it. I've updated things on this PR so that the test passes and we have the most correct behaviour, but the deprecated config option is removed. This saves users from themselves and also is useful prep for #34681.

2025-03-14 17:58 UTC, dmlloyd approved these changes

2025-03-19 16:50 UTC, gsmet requested changes

2025-03-19 17:43 UTC, holly-cummins commented on test-framework/junit5/src/main/java/io/quarkus/test/junit/internal/NewSerializingDeepClone.java
> +    private static final Pattern clonePattern = Pattern.compile("java\\..*");
I agree the Pattern is confusing. I've applied your suggestion and squashed.

2025-03-19 17:58 UTC, gsmet approved these changes
I fixed the import issue, it should be good to go.

2025-03-19 18:02 UTC, holly-cummins commented
> I fixed the import issue, it should be good to go.

Thanks! Our changes may have crossed. :)

2025-03-20 14:47 UTC, geoand commented
This is ready to go, correct?

2025-03-20 17:57 UTC, merged