Make mvnd 1.X work
quarkusio/quarkus pull request #41648
Opened 2024-07-02 23:45 UTC by manofthepeace

Fixes https://github.com/quarkusio/quarkus/issues/41323

This is a bit on a hack. But it works.

The codebase as a lot of references to `maven.multiModuleProjectDirectory` not sure if everything does work. But for futureproofness this should be changed, I think.

Occurences;
- core/processor/src/main/java/io/quarkus/annotation/processor/Constants.java
- docs/src/main/asciidoc/maven-tooling.adoc
- docs/src/main/asciidoc/tests-with-coverage.adoc
- independent-projects/parent/pom.xml
- independent-projects/resteasy-reactive/pom.xml
- tcks/resteasy-reactive/pom.xml
- Some places in the maven wrapper.

2024-07-03 12:26 UTC, gsmet commented
@manofthepeace did you test with `-f` and also when building inside a nested directory that contains a reference to this property?

2024-07-03 13:10 UTC, manofthepeace commented
> @manofthepeace did you test with `-f` and also when building inside a nested directory that contains a reference to this property?

What I tried is the following;
- Full build via mvn and mvnd
- from project root; mvnd/mvn -f tcks/resteasy-reactive clean install -Dquickly
- from  tcks/resteasy-reactive  mvnd/mvn clean install -Dquickly

2024-07-03 13:46 UTC, manofthepeace commented
If you want precises tests done please let me know. But I assume we will hit this somehow; https://github.com/apache/maven/pull/1589 . I think its still what can be done atm without downgrading.

but I think the fix proposed is still needed nevertheless as `maven.multiModuleProjectDirectory` is not coming back

2024-07-04 08:34 UTC, gsmet commented
Do you happen to know which versions support `session.rootDirectory`?

I stumbled upon https://issues.apache.org/jira/browse/MNG-7038 but it's only marked for Maven 4.

2024-07-04 14:52 UTC, manofthepeace commented
This PR actually uses `session.rootDirectory` which is puts in to `maven.multiModuleProjectDirectory` for things to just "work".

From what I understood from https://github.com/apache/maven-mvnd/issues/1031#issuecomment-2175917027 . Is that the value is only available in settings this needs to be used that way. In Maven 4 I believe this can be removed as it can be used as property, so we can change it in the poms and other places.

2024-07-04 16:40 UTC, gsmet commented
Yeah, my question was about when `session.rootDirectory` was introduced as to know if we would need to require a more recent version of Maven to build the project.

2024-07-04 18:38 UTC, manofthepeace commented
https://maven.apache.org/docs/3.9.2/release-notes.html

> Task [MNG-7774](https://issues.apache.org/jira/browse/MNG-7774) implemented interpolation for configuration and command line, but also provides two new properties usable in configuration interpolation: session.topDirectory (reactor top directory) and session.rootDirectory (project root directory, usually where .mvn directory reside). It is recommended to create .mvn directory in project root directory, as presence of this directory is used to detect root directory location. If .mvn directory does not exists, root directory will not be detected, and in such case attempted use of expression session.rootDirectory in interpolation will make Maven refuse to start (will report error). It is important to mention, that those two new properties, are only working within the maven.config file and via the command line. They are NOT usable as configuration properties within your plugin configuration in your pom.xml file.

does that answer?

2024-07-08 15:05 UTC, gsmet commented
@manofthepeace yes, perfect thanks.

I will require Maven 3.9.6+ to build Quarkus.

2024-07-09 21:05 UTC, gsmet commented
I ran some more tests and something is odd.

When running a `mvnd` build with this PR, I end up with a `${session.rootDirectory}` directory in my Quarkus directory with the following content:

```
${session.rootDirectory}/
└── target
    └── asciidoc
        └── generated
```
(and all the doc content is there).

So there something that needs fixing in the tree.

2024-07-09 23:08 UTC, manofthepeace commented
Interesting. Could it be something with asciidoctor itself, or the asciidoctor maven plugin? In anycase do you think this is major, is mvnd used in general internally/ to build the asciidoc?

I'll try to have a look eventually. If you have any pointers let me know.

2024-07-10 15:47 UTC, gsmet commented
It's essential to have it working. I'm working on a patch.

2024-07-10 16:17 UTC, manofthepeace commented
Ok, I figured it could be something like this, where the value was taken but not expanded by something out of maven.. This is unfortunate, I do not see a quick win at first glance. Not sure how far maven 4 is, but I would assume it would solve all of this.. and probably create a bunch of other things though..

> Note that the current behavior is very hackyish and we really need to do better

well.. I feel like removing a property like this in a minor version was not the best, so recourse to hacks to bring it back, as maven themselves dont have a way around this makes it somewhat necessary, to reinstate the old behaviour.. I was hoping the `maven.config` woult actually set an env, and not something just in maven, apparently it is not the case.

I'll try to take a look. But I am short on ideas.

2024-07-10 16:25 UTC, manofthepeace commented
@gsmet do you think this could potentially work? https://stackoverflow.com/questions/45723834/pass-argument-to-annotation-processor. i.e passing the arg to the annotation processor.

2024-07-10 20:48 UTC, gsmet commented
Yeah that's what I had in mind.
I don't think we will have a lot of other options unfortunately.

2024-07-10 20:49 UTC, gsmet commented
But long term, we actually need the extension processor to generate content in the module itself so that should probably be easier (we want to avoid writing things outside of the scope of the module, to make caching with Develocity possible).

I started working on that a while ago. I'll try to revive the PR and see if I can come up with something.

2024-08-08 13:54 UTC, gsmet commented
I hope I will soon merge the new extension annotation processor and then I'll see if I can revive this one.

2024-08-08 21:18 UTC, gsmet commented
Things look a lot better with the new extension annotation processor I just merged.

I force pushed a rebase and will merge once CI is green.

2024-08-08 21:19 UTC, gsmet approved these changes

2024-08-08 21:26 UTC, gsmet requested changes, later dismissed
Hmmm. I just had the following error:

> Caused by: java.io.FileNotFoundException: /home/gsmet/git/quarkus/independent-projects/resteasy-reactive/common/processor/${maven.multiModuleProjectDirectory}/.forbiddenapis/banned-signatures-common.txt (No such file or directory)

So this will need more work.

2024-08-09 07:46 UTC, gsmet approved these changes

2024-08-09 07:46 UTC, merged