[issue#2176] Register any additional necessary providers for server sent event @Produce(s)
quarkusio/quarkus pull request #4167
Opened 2019-09-24 05:09 UTC by jaikiran

The commit here introduces a way where any additional necessary `providers` are registered for any resource that `@Produces` `MediaType.SERVER_SENT_EVENTS`. This should allow for fixing the issue reported in https://github.com/quarkusio/quarkus/issues/2176 such that the `PriceResouce` in that example can now use:

```
@GET
    @Path("/stream")
    @Produces("text/event-stream;element-type=text/plain")
    public Publisher<Double> stream() {
        return prices;
    }
```
and will no longer require a (dummy) resource endpoint to register the basic `text/plain` type providers.

2019-09-24 08:44 UTC, gsmet commented
This is more correct but I doubt people will get it right.

Another option would be to include the text plain media type as soon as we have a `MediaType.SERVER_SENT_EVENTS`. Maybe we could have a generic method contributing additional media types based on a media type.

Typically, we would call `contributeAdditionalMediaTypes()` at these places:
- https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java#L188
- https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java#L198
- https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java#L208

and it would return an augmented list of elements in some cases (for now, only the `MediaType.SERVER_SENT_EVENTS` case).

Does it make sense to you?

2019-09-24 13:04 UTC, jaikiran commented
> This is more correct but I doubt people will get it right.

@gsmet, I understand what you mean.

> Another option would be to include the text plain media type as soon as we have a MediaType.SERVER_SENT_EVENTS. Maybe we could have a generic method contributing additional media types based on a media type.

Okay, so instead of expecting users to use an `element-type` `MediaType` parameter, we by default add the `text/plain` provider if and when we see the use of `MediaType.SERVER_SENT_EVENTS` in the application. That sounds fine to me.

> Typically, we would call contributeAdditionalMediaTypes() at these places: 

I have looked at the code that you pointed to (the 3 places) and do understand what you mean. However, those 3 places won't be the right place to do this logic, since those 3 places are processing the providers that have been found in the classpath, rather than the user's application resources which use those providers. That latter part happens later and I have updated this PR to use this common logic in that central place where it happens for `MessageWriter`, `MessageReader` and `ContextResolver`. 

The commit in this PR now adds the `text/plain` provider if it finds the usage of server sent events, plus also supports any additional `element-type` parameter if at all the user application has used such a construct.

Furthermore, I have included a test case to test the server sent events. Do note that this test case is ineffective in _reproducing_ the original reported issue because of the way we run our integration tests, where multiple other JaxRS endpoints are scanned and because of their usage of `text/plain`, the providers will anyway be registered and this issue won't be triggered. However, this test at least adds some amount of testing around server sent events.

2019-09-24 13:43 UTC, asoldano approved these changes
I think this proposal from Jaikiran is fine; see section 5 at https://docs.jboss.org/resteasy/docs/4.3.0.Final/userguide/html/Reactive.html#d4e2322

2019-09-24 14:00 UTC, geoand commented
If @asoldano agrees, then it I think we should merge. @gsmet ?

2019-09-24 14:07 UTC, gsmet commented
Please wait.

AFAICS there is also `@SseElementType` which seems to be used in this case - see example 1 here: https://docs.jboss.org/resteasy/docs/4.3.0.Final/userguide/html/Reactive.html#d4e2483

I think I would add `TEXT_PLAIN_TYPE` only if the element type is not defined one way or another.

What I'm unclear about is the precedence between the `;element-type` parameter and the `@SseElementType` annotation.

@asoldano could you shed some light on this?

2019-09-24 14:08 UTC, geoand commented
@gsmet up to you :)

2019-09-24 14:22 UTC, asoldano commented
@gsmet uh, thanks, I would need to run some tests, but you might have made me notice a "bug". So `@SeeElementType` is the RESTEasy annotation that controls the `;element-type` parameter, however it looks like a `@Produce("text/event-stream; element-type=foo/bar")` would result in a response with no parameter is the `@SseElementType` annotation is not there too. Anyway, for the Quarkus case, it's probably safe to check if the `element-type` parameter is defined in any way (directly or with the dedicated annotation), with the `@SseElementType` overriding the value from `@Produces`.

2019-09-24 14:35 UTC, gsmet commented
@asoldano OK, cool, thanks!

@jaikiran could you implement the above? (and defaults to text/plain if we don't have any meaningful information). I think it would greatly improve things in Quarkus.

2019-09-24 15:01 UTC, jaikiran commented
Thank you @asoldano for all these details and the review and thank you @gsmet for the patience with this review. I have now pushed a change to this PR which takes into account what we have discussed here. The comments in the code should summarize how we deal with it now (essentially the same as what we decided here).

2019-09-24 19:49 UTC, geoand commented
There are some formatting issues.

You can do `mvn process-resources` to fix them and then update the PR

2019-09-25 06:07 UTC, geoand commented
Clean install should do the trick. It has so often however that we commit before doing it 😅

2019-09-27 16:56 UTC, gsmet requested changes
@jaikiran I added a very minor comment but the main thing is that it needs a rebase (I would have merged as is if not).

Could you take care of the rebase and fix my minor remark along the way?

Other than that, it's perfect, thanks a lot for this.

Thanks!

2019-09-27 16:56 UTC, gsmet commented on extensions/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java
> +                if (mediaType.getParameters() != null
It's really very very minor but can it be a `else if` instead?

2019-09-27 17:13 UTC, jaikiran commented
Hi @gsmet, I've updated this PR after rebasing with latest and also incorporated the (valid) change that you mentioned in the latest comment.

2019-09-30 19:06 UTC, kenfinnigan approved these changes

2019-09-30 23:26 UTC, gsmet approved these changes

2019-09-30 23:27 UTC, merged

2019-09-30 23:27 UTC, gsmet commented
Merged, very nice improvement, thanks!