Avoid virtual thread pinning in RestClientsConfig
quarkusio/quarkus pull request #41926
Opened 2024-07-16 13:02 UTC by mariofusco

This is a fix for the virtual thread pinning problem reported [here](https://github.com/quarkusio/quarkus/issues/41313
).

As reported by @radcortez [here](https://github.com/quarkusio/quarkus/issues/41313#issuecomment-2225925541) the more structural fix there would be removing the implicit CDI dependency thus completely getting rid of the `ConcurrentHashMap`. However, as he also confirmed, a rewriting of the REST Client configuration could take a while, so I followed @franz1981's [suggestion](https://github.com/quarkusio/quarkus/issues/41313#issuecomment-2230517219) and fixed at least the symptom simply avoiding to call the `computeIfAbsent` method from a virtual thread.

2024-07-16 13:06 UTC, radcortez approved these changes

2024-07-16 16:00 UTC, franz1981 requested changes
I would avoid creating a new class (which implies a new class loaded) and using a single lock for all of them (even if virtual)...
given that the stack trace reported by the users is performing some blocking operation, it means that using a single lock will serialize all of the them regardless the "good" CHM concurrency allow...
Why not using a CompletableFuture value instead without caring if the caller is a virtual one?
It will reuse CHM and won't serialize the computes...

2024-07-16 16:13 UTC, mariofusco commented
> Why not using a CompletableFuture value instead without caring if the caller is a virtual one? It will reuse CHM and won't serialize the computes...

Do you mean having a `ConcurrentHashMap<String, CompletableFuture<RestClientConfig>>` ?

2024-07-16 17:24 UTC, franz1981 commented
Yep, clearly it would add some cost in term of footprint to everyone (non virtual threads), but there won't be any other adverse effects

2024-08-02 13:01 UTC, mariofusco commented
Made obsolete and unnecessary by https://github.com/quarkusio/quarkus/commit/4f31e0d923853fe15fc1da7664e52e2874a8b48b

2024-08-02 13:01 UTC, closed without merging