Move logging to @ConfigMapping
quarkusio/quarkus pull request #42157
Opened 2024-07-26 09:31 UTC by radcortez

- Partially Fixes #42114

2024-07-31 14:04 UTC, gsmet requested changes
Thanks! Let's not merge this too quickly.

I wonder if 3.14 is the right version to merge this, or it would be better to wait for 3.16 to get branched.

For now, I implemented a workaround to support mixed extensions.

2024-08-01 12:38 UTC, geoand commented
There is also a conflict in this

2024-10-07 12:45 UTC, gsmet approved these changes
Let's try to get this in for 3.16.

I rebased to get a fresh CI run.

@radcortez can you just have a look at my question?

2024-10-07 12:45 UTC, gsmet commented on integration-tests/vertx/src/main/resources/application.properties
> +quarkus.log.file.path=quarkus.log
This was a mistake in the config file or something changed?

2024-10-22 08:39 UTC, gsmet commented
I fixed an import conflict. Let's wait for CI and merge!

2024-10-22 08:51 UTC, radcortez commented
Thanks!

2024-10-22 14:14 UTC, merged