fix: considered the complete query in count query and links
quarkusio/quarkus pull request #42155
Opened 2024-07-26 05:51 UTC by j1myx

Issue https://github.com/quarkusio/quarkus/issues/41500

2024-07-26 05:54 UTC, j1myx commented
Hi @geoand , @gsmet . Issue https://github.com/quarkusio/quarkus/issues/41500 fixed!

2024-07-26 05:55 UTC, geoand commented
Thanks a lot for the conttibution!

It would be great if we could have some tests for this.

2024-07-26 09:11 UTC, geoand commented
Also keep in mind that when everything is done, this will need to be rebased onto main

2024-07-26 10:22 UTC, Sgitario commented on docs/src/main/asciidoc/rest-data-panache.adoc
> +IMPORTANT: If you have pagination enabled, using JOIN FETCH or others might prevent the query (`namedQuery`) from being reused for the count query. To resolve this you can add an additional query by
I don't see any tests that exercise/cover this. Can you add one?

2024-07-26 10:29 UTC, Sgitario requested changes
It's being a while since I don't see this code, but the changes look promising and even you improve the readibility of some tests. So, no objections about it, thanks a lot!

Yet I would like to see a test that reproduces the issue that is being addressed here (so the test should be failing without these changes). 
Also, I don't very like the approach of using an extra comma to specify the namedQuery only for the count (see my comment from the review), but I also don't fully follow the limitation that you mention. So, another test that exercises this is necessary from my point of view.

2024-07-26 10:29 UTC, Sgitario commented on docs/src/main/asciidoc/rest-data-panache.adoc
> +IMPORTANT: If you have pagination enabled, using JOIN FETCH or others might prevent the query (`namedQuery`) from being reused for the count query. To resolve this you can add an additional query by
I don't see any tests that exercise/cover this. Can you add one?
Also, I don't fully understand the limitation you describe here, but perhaps I could understand it better with an example in the test. 
In any case, I don't feel that using an extra comma is super intuitive, so perhaps a new namedQueryForCount query param would be a better solution.

2024-07-27 05:09 UTC, j1myx commented
> Hace tiempo que no veo este código, pero los cambios parecen prometedores e incluso mejoras la legibilidad de algunas pruebas. Así que no tengo objeciones al respecto, ¡muchas gracias!
> 
> Sin embargo, me gustaría ver una prueba que reproduzca el problema que se aborda aquí (por lo que la prueba debería fallar sin estos cambios). Además, no me gusta mucho el enfoque de usar una coma adicional para especificar la consulta con nombre solo para el recuento (consulte mi comentario de la revisión), pero tampoco sigo completamente la limitación que menciona. Por lo tanto, otra prueba que ejercite esto es necesaria desde mi punto de vista.

Hi @Sgitario, I got your recommendations. I'm going to implement it right now.

2024-07-29 12:50 UTC, closed without merging