Allow disabling health extension with configuration
quarkusio/quarkus pull request #42361
Opened 2024-08-07 13:11 UTC by xstefank

Fixes #42356

2024-08-07 13:14 UTC, xstefank commented
Also, it will probably supersede #38623 if @metacosm agrees.

2024-08-07 17:45 UTC, gsmet requested changes
Please see my comment inline.

2024-08-07 17:45 UTC, gsmet commented on extensions/smallrye-health/deployment/src/main/java/io/quarkus/smallrye/health/deployment/HealthBuildTimeConfig.java
> +    public boolean active;
If you disable the extension entirely, please use `enabled`, not `active`.

Also don't define a `name`, the convention will make it right.

See this issue for the overall context: https://github.com/quarkusio/quarkus/issues/42244

2024-08-08 08:33 UTC, xstefank commented
@gsmet fixed. I also aligned that it will always produce the feature so it will be displayed on startup to align with hibernate.

2024-08-08 09:50 UTC, gsmet approved these changes
Perfect, thanks.

I will merge it as soon as CI is green as I need to make changes in this class.

2024-08-08 09:51 UTC, merged