Remove reference to COLLECTOR_OTLP_ENABLED env var for Jaeger
quarkusio/quarkus pull request #42542
Opened 2024-08-14 10:40 UTC by mabartos

In the [OTel Tracing guide](https://quarkus.io/guides/opentelemetry-tracing#jaeger-to-see-traces-option), there is a reference to the `COLLECTOR_OTLP_ENABLED` env var, which should enable OTLP receivers. However, with regard to the more recent Jaeger documentation, it should not be needed.

Also, the link to the blog does not properly reflect the present as it is already quite old and users should rather visit official OTel docs.

Could you please check this small improvement? Thanks!

2024-08-16 14:54 UTC, brunobat requested changes
I've tried the PR and the code does not work well...
For some reason the lates jaeger-all-in-one does not ingest the spans and causes errors on the exporter.
Can you please take a look?

2024-08-28 16:28 UTC, mabartos commented
@brunobat Sorry, I'll take a look at it this week. When I tried it, everything was working as expected, but I'll verify it once again.

2024-08-30 12:14 UTC, mabartos commented
@brunobat I tried to start the image `all-in-one` without the `COLLECTOR_OTLP_ENABLED` env var, and everything works properly in our Keycloak environment. All traces/spans are successfully exported to the Jaeger, as I can see them in the Jaeger UI.

BTW. is there any reason why the docker-compose is used in the guide as it uses only one service/image? Might it be probably better to put some docker/podman example?

2024-11-10 17:17 UTC, cescoffier commented
@brunobat Did you have the time to look at it?

2024-11-11 09:55 UTC, brunobat commented
Sorry, no.

2025-09-15 06:17 UTC, cescoffier commented
@mabartos what's the status on this PR?

2026-03-02 07:19 UTC, cescoffier commented
@mabartos Ping?

2026-04-13 06:14 UTC, cescoffier commented
@brunobat what's the status on this one.

2026-04-13 14:29 UTC, brunobat commented
Closing this PR in favor of: https://github.com/quarkusio/quarkus/pull/53572

2026-04-13 14:29 UTC, closed without merging