GRPC pom: Adding operating system specific profiles
quarkusio/quarkus pull request #42993
Opened 2024-09-03 18:12 UTC by tmulle

This is for https://github.com/quarkusio/quarkus/issues/42931

In which this PR adds operating system specific profiles to pull only the dependencies needed for the machine being built.
This should help cut down on the pulling of extra files we don't need.

I've run the `./mvnw -Dquickly` from the root and all tests passed.
I verified on MacOS that ONLY the mac .exe gets pulled during the test by deleting the `~/.m2/repository/io/grpc/protoc-gen-gprc-java` folder prior to running the tests.

I've run the `/.mvnw -Dquickly` on my Fedora 39 Linux machine and all tests passed.
I verified on `Fedora Linux` that ONLY the `linux-x86_64.exe` gets pulled during the test by deleting the `~/.m2/repository/io/grpc/protoc-gen-gprc-java` folder prior to running the tests.

I also tried to cut down the file even further by just using the `os.detected.classifier` in the two protoc dependencies rather than spelling out each arch/os but I got an error from maven saying the `version` was missing.

I see the `os.detected.classifier` printed out at the beginning of the tests but it appears it's not available for the grpc tests?

Anyway, this change should work better by eliminating pulling down files for other operatings systems that aren't needed.

I could NOT verify the `s390` or `ppc` archictectures since I don't have those around.. I just had Linux, Mac and windows.

2024-09-03 18:13 UTC, melloware approved these changes
Welcome to the club!

2024-09-04 06:12 UTC, gsmet requested changes
Thanks! It looks good to me except I think I would drop the `name` for macOS and Windows as it doesn't bring anything.

Apart from that, I'm not sure how other unixes should be handled but I suppose we will have to wait for feedback from the field.

Could you adjust and squash? Thanks!

2024-09-04 06:12 UTC, gsmet commented on extensions/grpc/codegen/pom.xml
> +                    <name>Mac OS X</name>
I would drop the name here.

2024-09-04 06:12 UTC, gsmet commented on extensions/grpc/codegen/pom.xml
> +                    <name>Mac OS X</name>
Same here.

2024-09-04 06:12 UTC, gsmet commented on extensions/grpc/codegen/pom.xml
> +                    <name>Windows</name>
Same here.

2024-09-04 06:12 UTC, gsmet commented on extensions/grpc/codegen/pom.xml
> +                    <name>Windows</name>
Same here.

2024-09-04 17:39 UTC, gsmet approved these changes
For me, it's all good, thanks!

But I would also like the blessing of @cescoffier .

2024-09-04 18:01 UTC, cescoffier approved these changes

2024-09-04 20:13 UTC, merged

2024-09-04 20:13 UTC, gsmet commented
Nice improvement, thanks!

2024-09-05 07:35 UTC, gsmet commented
When we did that, I thought "will it work with Gradle?" and I was pleasantly surprised.

But actually it doesn't, see https://github.com/quarkusio/quarkus/pull/43038 for all the gory details and the revert.

2024-09-05 10:16 UTC, melloware commented
Yuck.  I guess I will keep my Gradle rant to myself...