Messaging extensions doc update for tls-registry usage
quarkusio/quarkus pull request #43087
Opened 2024-09-06 15:06 UTC by ozangunalp

Another PR to add a mention in TLS registry reference page following https://github.com/quarkusio/quarkus/pull/42706

2024-09-09 08:06 UTC, gsmet commented
@ozangunalp build fails with:

```
Unable to find cross reference for:
2024-09-06T15:32:57.1318313Z [ERROR] 
2024-09-06T15:32:57.1318742Z [ERROR] - messaging.adoc
2024-09-06T15:32:57.1320138Z [ERROR]     . ./tls-registry-reference.adoc#using-tls-registry in link xref:././tls-registry-reference.adoc#using-tls-registry[named TLS configuration]
```

2024-09-11 06:47 UTC, cescoffier requested changes

2024-09-11 06:47 UTC, cescoffier commented on docs/src/main/asciidoc/amqp-reference.adoc
> +To configure the TLS for an AMQP 1.0 channel, you need to provide a named TLS configuration (or `<default>`, for the default configuration) in the `application.properties`:
Following the ADR 0004 (https://github.com/quarkusio/quarkus/blob/main/adr/0004-using-the-tls-registry-for-clients.adoc) - it is recommended to use a named. So, I would remove the reference to `<default>`.

2024-09-11 06:47 UTC, cescoffier commented on docs/src/main/asciidoc/kafka.adoc
> +To configure the TLS for the default Kafka configuration, you need to provide a named TLS configuration (or `<default>`, for the default configuration) in the `application.properties`:
Following the ADR 0004 (https://github.com/quarkusio/quarkus/blob/main/adr/0004-using-the-tls-registry-for-clients.adoc) - it is recommended to use a named. So, I would remove the reference to `<default>`.

2024-09-11 06:47 UTC, cescoffier commented on docs/src/main/asciidoc/kafka.adoc
> +Make sure also to enable the SSL security protocol.
Can this be a callout?

2024-09-11 06:47 UTC, cescoffier commented on docs/src/main/asciidoc/messaging.adoc
> +Note that for the default TLS configuration, you can provide the value `<default>`.
Following the ADR 0004 (https://github.com/quarkusio/quarkus/blob/main/adr/0004-using-the-tls-registry-for-clients.adoc) - it is recommended to use a named. So, I would remove the reference to `<default>`.

2024-09-11 06:47 UTC, cescoffier commented on docs/src/main/asciidoc/messaging.adoc
> +At the time of writing, the following messaging extensions support configuration through the Quarkus TLS Registry:
```suggestion
Currently the following messaging extensions support configuration through the Quarkus TLS Registry:
```

2024-09-11 06:47 UTC, cescoffier commented on docs/src/main/asciidoc/pulsar.adoc
> +To configure the mTLS for a Pulsar channel, you need to provide a named TLS configuration (or `<default>`, for the default configuration) in the `application.properties`:
Following the ADR 0004 (https://github.com/quarkusio/quarkus/blob/main/adr/0004-using-the-tls-registry-for-clients.adoc) - it is recommended to use a named. So, I would remove the reference to `<default>`.

2024-09-11 06:47 UTC, cescoffier commented on docs/src/main/asciidoc/rabbitmq-reference.adoc
> +To configure the TLS for a channel, you need to provide a named TLS configuration (or `<default>`, for the default configuration) in the `application.properties`:
Following the ADR 0004 (https://github.com/quarkusio/quarkus/blob/main/adr/0004-using-the-tls-registry-for-clients.adoc) - it is recommended to use a named. So, I would remove the reference to `<default>`.

2024-09-11 15:02 UTC, cescoffier approved these changes

2024-09-11 15:03 UTC, merged