Fix visual studio code svg
quarkusio/quarkus pull request #43112
Opened 2024-09-07 14:22 UTC by mcruzdev

2024-09-07 15:27 UTC, gsmet reviewed
Thanks for the PR, I added a small comment.

2024-09-07 15:27 UTC, gsmet commented on docs/src/main/asciidoc/ide-tooling.adoc
>  :che-logo: https://simpleicons.org/icons/eclipseche.svg
Maybe we should have all the logos hosted in our website instead of linking external resources?

Could you take care of this?

2024-09-08 15:40 UTC, mcruzdev commented
Do not merge this one yet, see https://quarkus-pr-main-43112-preview.surge.sh/version/main/guides/ide-tooling. I will solve this one tomorrow! ;)

2024-09-09 12:18 UTC, gsmet requested changes

2024-09-09 12:18 UTC, gsmet commented on docs/src/main/asciidoc/ide-tooling.adoc
> +:vscode-logo: {imagesDir}/visualstudiocode.svg
AFAICS, it should be `imagesdir`.

2024-09-10 07:30 UTC, geoand commented
Thanks for this!

Once all is done, we'll need to commits squashed.

2024-09-10 07:44 UTC, gsmet approved these changes

2024-09-10 08:29 UTC, merged

2024-09-10 08:29 UTC, gsmet commented
Thanks a lot for catching this and fixing it!