Allows users to exclude DefaultMismatchedInputException
quarkusio/quarkus pull request #43126
Opened 2024-09-09 08:54 UTC by geoand

A few users have run into an issue where
they are trying to handle all Jackson exceptions
but the existence of `DefaultMismatchedInputException`
prevents that for `MismatchedInputException`
(as per JAX-RS / Jakarta REST rules).

This change allows users to do use:

```properties
quarkus.class-loading.removed-resources."io.quarkus\:quarkus-rest-jackson"=io/quarkus/resteasy/reactive/jackson/runtime/mappers/DefaultMismatchedInputException.class
```

in order to have Quarkus ignore the mapper.

`P.S. We could also introduce a specific property for this, but currently I am on the fence about that...`

2024-09-09 16:37 UTC, gsmet reviewed
Hmmm, I have a few comments here.

Should we rename the class to `DefaultMismatchedInputExceptionMapper` before documenting it somewhere? When I read the description, I thought it was an exception and had a hard time understanding the issue.

Second question: isn't it easier to create a mapper with a higher priority that specifically handles this exception?

And finally, I wonder if at some point, these dev modes features should be handled specifically after the exception mappers have been applied (and only be triggered if no ExceptionMapper handled the exception).

2024-09-09 17:20 UTC, geoand commented
> Should we rename the class to DefaultMismatchedInputExceptionMapper before documenting it somewhere? When I read the description, I thought it was an exception and had a hard time understanding the issue

How about `BuiltinMismatchedInputExceptionMapper`?

> Second question: isn't it easier to create a mapper with a higher priority that specifically handles this exception instead of promoting a rather obscure feature?

That doesn't work (as per JAX-RS / Jakarta REST) when users want to handle a super class of  `MismatchedInputException`.

2024-09-10 11:35 UTC, gsmet commented
> How about BuiltinMismatchedInputExceptionMapper?

Looks good.

> That doesn't work (as per JAX-RS / Jakarta REST) when users want to handle a super class of MismatchedInputException.

Maybe I wasn't clear but my understanding was that they would have to have a specific mapper for `MismatchedInputException`. I thought it might be easier to grasp from a user perspective.

But you can start your way and see how to make it easier to grasp later.

> I don't really understand this, can you elaborate a little?

I think it's not the first time we have dev mode features in the way of how you would expect a standard JAX-RS implementation to work.
Typically this feature we have is nice in dev mode but I think it shouldn't be in the way when you customize things on your side.

Thus why I was wondering if we should have a way to enable these features only if something from the user didn't catch things earlier.

Basically, we should find a way for our mappers (or not implement them as mappers) to be very last resort if nothing else from the users intervened first.

2024-09-10 11:38 UTC, geoand commented
> Maybe I wasn't clear but my understanding was that they would have to have a specific mapper for MismatchedInputException. I thought it might be easier to grasp from a user perspective.

That would work today without any configuration. What does not work as users would like, is handling all exceptions that are super classes of this exception. 

> Basically, we should find a way for our mappers (or not implement them as mappers) to be very last resort if nothing else from the users intervened first.

Yeah, that would be nice, but unfortunately the resolution rules don't really allow this - hence the ability to remove this one.

2024-09-10 11:47 UTC, geoand commented
PR updated

2024-09-10 15:53 UTC, gsmet requested changes
I will handle the comment given I'm already on this subject, no need for you to context switch.

2024-09-10 15:53 UTC, gsmet commented on docs/src/main/asciidoc/rest.adoc
> +quarkus.class-loading.removed-resources."io.quarkus\:quarkus-rest-jackson"=io/quarkus/resteasy/reactive/jackson/runtime/mappers/BuiltinMismatchedInputException.class
```suggestion
quarkus.class-loading.removed-resources."io.quarkus\:quarkus-rest-jackson"=io/quarkus/resteasy/reactive/jackson/runtime/mappers/BuiltinMismatchedInputExceptionMapper.class
```

2024-09-10 15:54 UTC, gsmet commented
Force pushed with the doc fix squashed!

2024-09-10 17:11 UTC, geoand commented
Thanks!

2024-09-10 18:08 UTC, gsmet approved these changes

2024-09-10 18:08 UTC, merged