cleanup & nitpicks on some of the code
quarkusio/quarkus pull request #43207
Opened 2024-09-11 05:41 UTC by nkolatsis

No major changes. Just a few cleanups and nitpicks on the security-jwt guide.

Line 87
Unnecessary import removed

Line 108
Circle brackets typo removed

Line 197, 210
RequestScoped import and annotation removed - unnecessary for this stage of the guide

Line 125, 175, 241, 458, 545, 571
String concatenation typo removed

2024-09-11 08:26 UTC, sberyozkin commented on docs/src/main/asciidoc/security-jwt.adoc
> +        return String.format("hello %s,"
Without the plus is better but the quickstart still has it: https://github.com/quarkusio/quarkus-quickstarts/blob/main/security-jwt-quickstart/src/main/java/org/acme/security/jwt/TokenSecuredResource.java#L71.

I don't think it is significant, the presence or absence of `+` in what is some sample response

2024-09-11 08:28 UTC, sberyozkin commented on docs/src/main/asciidoc/security-jwt.adoc
> -@RequestScoped
It will work with `@RequestScoped`, but what do you mean that this is not relevant at this stage of the guide ?

2024-09-11 08:32 UTC, sberyozkin commented on docs/src/main/asciidoc/security-jwt.adoc
> +        return String.format("hello %s,"
@nkolatsis If you'd like, please open a PR for quickstarts to remove it

2024-09-11 15:41 UTC, sberyozkin commented on docs/src/main/asciidoc/security-jwt.adoc
> -@RequestScoped
@nkolatsis Oh, sorry, there are a few `TokenSecuredResource` variations and the one you are updating would not be impacted. 
However, I'd prefer to use this context annotation here, as other resources below still have it, and there is a dedicated `Supported injection scopes` section below which talks about it.

May be it is worth expanding that section instead, currently it gives only a single example, and says you don't have to use `RequestScoped` for `JsonWebToken` - but the example is missing. So if you'd like add an example there showing how the same `birthday` claim can be accessed from `JsonWebToken` without `@RequestScoped`

2024-09-11 16:13 UTC, sberyozkin commented on docs/src/main/asciidoc/security-jwt.adoc
> -@RequestScoped
I only looked at the actual quickstart code where removing it would be a problem, so got confused, sorry about that

2024-09-13 21:37 UTC, sberyozkin requested changes
Please keep `@RequestScoped` to keep it aligned with the other code examples there, everything else look good, I can align the quickstart code, thanks @nkolatsis

2024-09-15 11:11 UTC, sberyozkin commented
@nkolatsis Let me push some minor updates as `@RequestScoped` is everywhere there in the doc where it may not be necessary

2024-09-15 11:40 UTC, sberyozkin commented
@nkolatsis I removed a few more RequestScoped and highlighted where it was really necessary. Thanks for starting this cleanup of the security-jwt docs

2024-09-15 11:40 UTC, sberyozkin approved these changes

2024-09-15 14:52 UTC, merged

2024-09-17 14:35 UTC, nkolatsis commented
Thanks for improving and merging the pull request @sberyozkin
I'm glad to see it was accepted.