fix(42563): Deprecate quarkus.datasource.jdbc.tracing
quarkusio/quarkus pull request #43416
Opened 2024-09-20 17:01 UTC by danielsoro

2024-09-23 08:09 UTC, brunobat requested changes
Thanks @danielsoro, but the idea is remove the deprecated property altogether, not its deprecation.

2024-09-24 08:45 UTC, gsmet reviewed
Thanks for the PR! See my small comment inline.

2024-09-24 08:45 UTC, gsmet commented on extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSourceJdbcRuntimeConfig.java
> +    @Deprecated(forRemoval = true)
Could you add `since = "3.16"` for both?

2024-09-24 10:05 UTC, gsmet commented
@brunobat maybe I'm missing something but this PR is marking the properties for deprecation? Which is kinda a necessary step before removing them.
Did I miss something?

2024-09-24 10:11 UTC, brunobat approved these changes
Sorry, yes @gsmet and @danielsoro. We need this PR deprecating the prop and later the one removing it

2024-09-24 13:24 UTC, danielsoro commented
@gsmet @brunobat PR updated to add `since = "3.16"`

2024-09-25 08:15 UTC, merged