Show nicer error when a @ConfigMapping class exists in the deployment module and set to the runtime phase
quarkusio/quarkus pull request #43513
Opened 2024-09-26 05:09 UTC by mcruzdev

- Fixes: #43394

2024-09-27 09:49 UTC, radcortez requested changes

2024-09-27 09:49 UTC, radcortez commented on core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java
> +                boolean isPresentAtDeployment = isClassAvailable(deploymentCl,
This should be checked in https://github.com/quarkusio/quarkus/blob/be4817d541882225767e9e3655ec5bf325045360/core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java#L98-L111.

2024-09-27 09:49 UTC, radcortez commented on core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java
> +                if (!mapping.getKlass().getName().startsWith("io.quarkus.runtime.")) {
Wouldn't it be easier to check, if mapping is `RUNTIME` and `QuarkusClassLoader.isClassPresentAtRuntime`? We may want to include `BUILD_AND_RUNTIME_FIXED` also.

2024-09-27 09:49 UTC, radcortez commented on core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java
> +                boolean isPresentAtDeployment = isClassAvailable(deploymentCl,
Or better yet in here:
https://github.com/quarkusio/quarkus/blob/be4817d541882225767e9e3655ec5bf325045360/core/deployment/src/main/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReader.java#L166-L184

Which already reports other checks.

2024-09-27 09:50 UTC, radcortez commented
Thank you for the PR; I've left a few comments.

2024-09-30 09:27 UTC, radcortez requested changes
The CI failure is related.

2024-09-30 17:03 UTC, radcortez requested changes
Can we add a test please? Thank you.

2024-10-07 11:10 UTC, radcortez commented on core/deployment/src/test/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReaderTest.java
> +class BuildTimeConfigurationReaderTest {
My recommendation is to add the test here: https://github.com/quarkusio/quarkus/tree/4e11ab3c285ff7568c693d47a515122a3e7503d4/integration-tests/test-extension/extension

And use a `QuarkusUnitTest`.

2024-10-15 16:06 UTC, radcortez commented on core/deployment/src/test/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReaderTest.java
> +class BuildTimeConfigurationReaderTest {
What was the issue?

2024-10-16 10:44 UTC, radcortez commented on core/deployment/src/test/java/io/quarkus/deployment/configuration/BuildTimeConfigurationReaderTest.java
> +class BuildTimeConfigurationReaderTest {
You can selectively create an inner class with the mapping local to the test class and then manually register it with:

```java
.addAsResource(new StringAsset("MAPPING_NAME"), "META-INF/quarkus-config-roots.list")
```

It should only affect the specific test and shouldn't leak to other tests.

2024-11-07 22:07 UTC, radcortez approved these changes

2024-11-08 12:18 UTC, radcortez commented
It seems that the CL check is not reliable at all. There is already a workaround for the configs in the `core` module, and now there are some related test failures. 

Maybe we should implement this in the annotation processor instead. We don't have a way to determine what kind of module we are analysing, but we can probably come up with some ideas.

2024-11-08 12:19 UTC, radcortez requested changes
Test failures are related.

2024-11-08 12:38 UTC, gsmet commented
I agree that maybe doing it in the extension annotation processor would be easier. I have some logic to detect runtime/deployment that I need to clean up anyway.

I'll have a look at making it more reliable and you could then use that instead for your patch.

2024-11-26 01:16 UTC, mcruzdev commented
Hi @gsmet and @radcortez I think it is ok now, could take a new review?

2024-12-01 16:29 UTC, gsmet commented
Looks like CI is passing! Could you squash the commits?

I'm traveling for 2 days, will have a look after that if noone beats me to it.

2024-12-01 17:21 UTC, radcortez commented
> I'm traveling for 2 days, will have a look after that if noone beats me to it.

Don't worry about it. I'll have a look.

2024-12-01 19:05 UTC, mcruzdev commented
> Looks like CI is passing! Could you squash the commits?

Done!

2024-12-03 12:07 UTC, radcortez approved these changes

2024-12-03 12:08 UTC, radcortez commented
I gave it a try, and it worked as expected. I think this last implementation is way better than what we had before.

Thank you for the work and patience @mcruzdev

2024-12-12 15:32 UTC, gastaldi commented on core/processor/src/main/java/io/quarkus/annotation/processor/documentation/config/scanner/AbstractConfigListener.java
> +                        "ConfigPhase.BUILD_AND_RUNTIME_FIXED phases, must be on runtime module.");
```suggestion
                        "ConfigPhase.BUILD_AND_RUNTIME_FIXED phases must be on runtime module.");
```

2024-12-12 15:32 UTC, gastaldi commented on core/processor/src/main/java/io/quarkus/annotation/processor/documentation/config/scanner/ConfigMappingListener.java
> +                configPhase);
```suggestion
        validateRuntimeConfigOnDeploymentModules(configPhase);
```

2024-12-12 15:36 UTC, gastaldi commented on core/processor/src/main/java/io/quarkus/annotation/processor/documentation/config/scanner/AbstractConfigListener.java
> +                        "ConfigPhase.BUILD_AND_RUNTIME_FIXED phases, must be on runtime module.");
Also I think we should log the offending `ConfigMapping` class name in the message

2024-12-12 17:00 UTC, mcruzdev commented on core/processor/src/main/java/io/quarkus/annotation/processor/documentation/config/scanner/ConfigMappingListener.java
> +                configPhase);
Thank you GOAT! suggestions applied :)

2024-12-12 17:23 UTC, gastaldi approved these changes

2024-12-13 04:25 UTC, merged