Provide the reactive route guide
quarkusio/quarkus pull request #4352
Opened 2019-10-03 12:38 UTC by cescoffier

2019-10-04 14:49 UTC, kenfinnigan requested changes

2019-10-04 14:49 UTC, kenfinnigan commented on docs/src/main/asciidoc/reactive-routes-guide.adoc
> +If you use `quarkus-reasteasy` or `quarkus-vertx-web`, the extension will be added automatically.
"resteasy"

2019-10-04 14:49 UTC, kenfinnigan commented on docs/src/main/asciidoc/reactive-routes-guide.adoc
> +This guide has introduced how you can use reactive routes to define HTTP endpoint.
"define an HTTP endpoint"

2019-10-05 12:58 UTC, cescoffier commented
@kenfinnigan Issues fixed.

2019-10-05 18:44 UTC, kenfinnigan approved these changes

2019-10-05 18:44 UTC, merged