Safely propagate the state of InvocationContextImpl accross threads
quarkusio/quarkus pull request #4356
Opened 2019-10-03 14:30 UTC by mkouba

- resolves #4355

2019-10-03 14:35 UTC, kenfinnigan approved these changes

2019-10-03 14:53 UTC, mkouba commented
There are some weird issues I need to investigate... :-(

2019-10-03 15:31 UTC, mkouba commented
It was actually a PEBKAC error... time to finish today ;-).

2019-10-04 00:26 UTC, stuartwdouglas requested changes

2019-10-04 00:26 UTC, stuartwdouglas commented on independent-projects/arc/runtime/src/main/java/io/quarkus/arc/InvocationContextImpl.java
> +    private final AtomicInteger position;
Can you change this to a volatile integer with an AtomicIntegerUpdater instead? This object can be created a lot so it is better to save the allocation.

2019-10-04 00:26 UTC, stuartwdouglas commented on independent-projects/arc/runtime/src/main/java/io/quarkus/arc/InvocationContextImpl.java
> +    private final List<Object> args;
Why not just use a volatile field for the array?

2019-10-04 00:27 UTC, stuartwdouglas commented on independent-projects/arc/runtime/src/main/java/io/quarkus/arc/InvocationContextImpl.java
> +    private final AtomicInteger position;
TBH I don't think you even need the updater, if you have multiple threads calling next() concurrently then you are into undefined territory anyway. Just making the field volatile should be enough to make sure the state is visible to a new thread.

2019-10-14 15:49 UTC, mkouba commented
Will be superseded by a PR for https://github.com/quarkusio/quarkus/issues/4552.

2019-10-14 15:49 UTC, closed without merging