Upgrade Avro to 1.11.4
quarkusio/quarkus pull request #43647
Opened 2024-10-02 09:18 UTC by aloubyansky

2024-10-02 09:41 UTC, gsmet requested changes

2024-10-02 09:41 UTC, gsmet commented on .mvn/.develocity/develocity-workspace-id
> +byn7ntkhzvelzg7bls5pjngk6a
Let's add .develocity to the .gitignore instead :).

2024-11-10 16:57 UTC, cescoffier commented
@aloubyansky @gsmet  3.2 is not being maintained anymore. Should we keep this PR?

2024-11-11 07:20 UTC, aloubyansky commented
I think it doesn't hurt merging in case we decide to release another patch.

2024-11-12 08:16 UTC, merged