Delegate detection of the database version to the Hibernate ORM dialect
quarkusio/quarkus pull request #43764
Opened 2024-10-08 08:54 UTC by yrodiere

Fixes #43703
Fixes #42255

Based on #41310 and #43762, which must be merged first. Critically, #41310 requires Hibernate ORM 7.0.0.Final to be released, so we won't be able to merge this PR for a while. I'm submitting it anyway as a draft, so that we remember it's that easy: only the last two commits will be needed after we rebase.

2025-01-08 16:08 UTC, DavideD requested changes, later dismissed
Before merging this, we should check that it works with Hibernate Reactive.

2025-05-12 16:16 UTC, yrodiere commented
I rebased on the ORM 7 upgrade PR (which upgrades to Reactive 3.0.0.CR1 too, now), and added tests to check DB version checking works with Hibernate Reactive, but so far it does not. I think `QuarkusRuntimeInitDialectFactory` is never used in reactive, leading to the DB version being unavailable and thus never checked.

I'll get back to this later, will try to fix it, and will update the Hibernate Reactive extension docs (since we need to document the DB version stuff there, too).

2025-05-15 15:27 UTC, yrodiere commented
@DavideD FYI, I updated the PR to _also_ perform version checks with Hibernate Reactive. It required a few changes, but it works! Thank you.

2025-06-05 14:42 UTC, yrodiere commented
FWIW this fixes #45263 as well.

Before:

```
[INFO] Running io.quarkus.it.hibernate.reactive.postgresql.HibernateReactiveFetchLazyTest	
2025-06-05 16:34:50,996 INFO  [org.hib.jpa.int.uti.LogHelper] (main) HHH000204: Processing PersistenceUnitInfo [name: default-reactive]	
2025-06-05 16:34:51,060 INFO  [org.hib.Version] (main) HHH000412: Hibernate ORM core version 7.0.0.Final	
2025-06-05 16:34:51,234 INFO  [org.hib.orm.con.pooling] (main) HHH10001005: Database info:	
	Database JDBC URL [undefined/unknown]	
	Database driver: undefined/unknown	
	Database version: 13.0	
	Autocommit mode: undefined/unknown	
	Isolation level: <unknown>	
	Pool: undefined/unknown	
	Minimum pool size: undefined/unknown	
	Maximum pool size: undefined/unknown	
2025-06-05 16:34:52,186 WARN  [io.qua.hib.orm.run.ser.QuarkusRuntimeInitDialectFactory] (JPA Startup Thread) Persistence unit default-reactive: Could not retrieve the database version to check it is at least 13.0.0	
2025-06-05 16:34:52,216 INFO  [io.quarkus] (main) quarkus-integration-test-hibernate-reactive-postgresql 999-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 3.906s. Listening on: http://localhost:8081/	
2025-06-05 16:34:52,216 INFO  [io.quarkus] (main) Profile test activated. 	
2025-06-05 16:34:52,216 INFO  [io.quarkus] (main) Installed features: [cdi, compose, hibernate-orm, hibernate-reactive, reactive-pg-client, rest, rest-jsonb, security, security-properties-file, smallrye-context-propagation, vertx]
```

After:

```
[INFO] Running io.quarkus.it.hibernate.reactive.postgresql.HibernateReactiveFetchLazyTest
2025-06-05 16:39:41,397 INFO  [org.hib.jpa.int.uti.LogHelper] (main) HHH000204: Processing PersistenceUnitInfo [name: default-reactive]
2025-06-05 16:39:41,483 INFO  [org.hib.Version] (main) HHH000412: Hibernate ORM core version 7.0.0.Final
2025-06-05 16:39:41,727 INFO  [org.hib.orm.con.pooling] (main) HHH10001005: Database info:
        Database JDBC URL [undefined/unknown]
        Database driver: undefined/unknown
        Database version: 13.0
        Autocommit mode: undefined/unknown
        Isolation level: <unknown>
        Pool: undefined/unknown
        Minimum pool size: undefined/unknown
        Maximum pool size: undefined/unknown
2025-06-05 16:39:43,337 INFO  [io.quarkus] (main) quarkus-integration-test-hibernate-reactive-postgresql 999-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 5.360s. Listening on: http://localhost:8081
2025-06-05 16:39:43,338 INFO  [io.quarkus] (main) Profile test activated. 
2025-06-05 16:39:43,338 INFO  [io.quarkus] (main) Installed features: [cdi, compose, hibernate-orm, hibernate-reactive, reactive-pg-client, rest, rest-jsonb, security, security-properties-file, smallrye-context-propagation, vertx]
```

(And yeah IDK why other info logs don't get filtered out, probably something to do with the integration test classloader?)

2025-06-10 15:47 UTC, yrodiere commented
Let's see what CI has to say, I'm seeing weird test failures for Gradle in my fork...

2025-06-10 16:06 UTC, gsmet approved these changes

2025-06-11 06:49 UTC, yrodiere commented
There's definitely something wrong, and fortunately my new `DbOfflineOnStartupTest` seems to reproduce that. I'll need to have a closer look, but we'll miss the Quarkus 3.24.0.CR1 release. Well, we'll catch the next one :)

2025-06-11 16:48 UTC, yrodiere commented
> There's definitely something wrong, and fortunately my new `DbOfflineOnStartupTest` seems to reproduce that. I'll need to have a closer look, but we'll miss the Quarkus 3.24.0.CR1 release. Well, we'll catch the next one :)

Should be good now.

2025-06-12 07:29 UTC, merged

2025-06-18 14:15 UTC, yrodiere commented
I added entries to the migration guide:

https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.25#database-versions-checks
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.25#database-versions-checks-1