Dev UI better reconnect
quarkusio/quarkus pull request #43841
Opened 2024-10-12 06:42 UTC by phillip-kruger

This PR does 2 things:

- Change the mouse pointer to wait when the server is restarting. This gives the user some more indication that the server is offline (other than the icon on the bottom left corner)
- Exponential backoff the retry attempts, with a max of 10. If the server is not up by then, it's not a normal restart, so we display a popup to allow manual reconnect.

![dev_ui_reconnect](https://github.com/user-attachments/assets/48479c29-13b0-4a98-b483-320d703f81dd)

2024-10-13 23:43 UTC, melloware approved these changes

2024-10-14 04:48 UTC, phillip-kruger commented
There is a grammar error in the pop up. Hold off merging let me fix it first

2024-10-14 06:00 UTC, cescoffier requested changes

2024-10-14 06:00 UTC, cescoffier commented on extensions/vertx-http/dev-ui-resources/src/main/resources/dev-ui/qwc/qwc-header.js
> +                When the server is back up, click retry to connect again.
```suggestion
                It looks like the application is currently unavailable. After several reconnection attempts, we’re unable to connect.
Once the application is back online, click “Retry” to reconnect.
```

2024-10-14 07:39 UTC, cescoffier approved these changes

2024-10-14 14:01 UTC, merged

2024-10-14 14:01 UTC, gsmet commented
Nice improvement!