Jandex quarkus-devtools-common
quarkusio/quarkus pull request #4386
Opened 2019-10-04 18:47 UTC by gastaldi

In code.quarkus.io, `BuildTool` is used as a JAX-RS parameter and this gets rid of the warning during the build:
```
[WARNING] [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- io.quarkus.generators.BuildTool
```

2019-10-04 18:49 UTC, gastaldi commented
@gsmet any chance to have this PR in time for 0.24.0?

2019-10-04 18:55 UTC, gsmet commented
@gastaldi can you point me where it's done? I'm not sure it's the right fix.

2019-10-04 19:04 UTC, gastaldi commented
@gsmet sure, it's in https://github.com/quarkusio/quarkus/pull/4386

And here is the friendly output with this fix: 

```bash
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:build (default) @ code.quarkus.io ---
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
[INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Final
[INFO] [io.quarkus.resteasy] Resteasy running without servlet container.
[INFO] [io.quarkus.resteasy] - Add quarkus-undertow to run Resteasy within a servlet container
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 2068ms
[INFO] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Building jar: /home/ggastald/workspace/code.quarkus.io/target/code.quarkus.io-1.0.0-runner.jar
```

2019-10-04 19:23 UTC, kenfinnigan commented
Is it easier just to use a processor to add `BuildTool` to Jandex rather than Jandex the whole module?

2019-10-04 23:08 UTC, gastaldi commented
> Is it easier just to use a processor to add BuildTool to Jandex rather than Jandex the whole module?

@kenfinnigan that makes sense I guess. Can you point me to an example where this is used?

2019-10-05 05:57 UTC, stuartwdouglas requested changes
We definitely don't want to do this. This will add this information to all user deployments, when really we only want this for one of our internal apps. 

code.quarkus.io should just use its own Enum and translate it to this internal one as required.

2019-10-05 05:57 UTC, stuartwdouglas commented
Closing, as we don't want to make these sort of changes to Quarkus based on the implementation details of code.quarkus.io.

2019-10-05 05:57 UTC, closed without merging