Add the hibernate `globally-quoted-identifiers` parameter.
quarkusio/quarkus pull request #4387
Opened 2019-10-04 20:51 UTC by ma1uta

I moved this option to the `database` section and set the default value is "false".

There are two test: first when value is false and check that you cannot work when entity names conflict with the database reserved words, and the second when value is true and all work.

2019-10-05 14:37 UTC, gsmet requested changes
Thanks. I added one minor comment and one about the tests that should be moved in the deployment module IMHO.

Could you have a look?

2019-10-05 14:37 UTC, gsmet commented on extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfig.java
> +         * Default value is false.
Can you remove the default value part of the java doc? We automatically generate the doc from the annotation.

2019-10-05 14:37 UTC, gsmet commented on integration-tests/hibernate-configuration/pom.xml
> +    <name>Quarkus - Integration Tests - JPA - Configuration</name>
I don't think we want a new module for that.

The tests should be added there: https://github.com/quarkusio/quarkus/tree/master/extensions/hibernate-orm/deployment/src/test/java/io/quarkus/hibernate/orm .

2019-10-06 13:45 UTC, ma1uta commented
Ok, I will look on the remaks.

2019-10-15 13:37 UTC, gsmet commented
@ma1uta any news? Do you need any help?

2019-10-22 21:26 UTC, ma1uta commented
@gsmet Sorry for delay. I am busy now but try to find time to fix remarks.

2019-10-24 14:21 UTC, Sanne commented
@ma1uta I see you pushed something. Is it ready for a new review?

2019-10-29 06:09 UTC, ma1uta commented
@Sanne Yes, you can review the code. Also I rewrote tests, but something strange happens. Native tests passes and in jvm tests my test io.quarkus.hibernate.orm.quoted_indentifiers.JPAQuotedTestCase passed but some other failed.
And I'm stuck on it for now.

2019-11-06 15:33 UTC, gsmet commented
I rebased your work and force-pushed. It seems to work for me locally and the CI builds were already removed so I couldn't see what happened there.

Let's see what CI has to say.

2019-12-02 14:02 UTC, gsmet commented
Current status of this one is: the tests are failing depending on the order of the tests. It looks like as soon as we enable the globally quoted identifier feature, it's enabled for all the tests after that one.

2020-01-08 14:14 UTC, gsmet commented
I have some good news for this PR: @gastaldi fixed the issue we had in the tests.

So as soon as https://github.com/quarkusio/quarkus/pull/6451 is merged, I'll rebase this one and hopefully tests will pass and we will be able to merge it too.

2020-01-08 22:02 UTC, gsmet commented
I rebased and force-pushed, let's see what CI has to say.

2020-01-09 06:47 UTC, ma1uta commented
All checks have passed. Could you please review this PR?

2020-01-09 08:16 UTC, gsmet approved these changes

2020-01-09 08:16 UTC, merged

2020-01-09 08:17 UTC, gsmet commented
Merged, thanks a lot for this (and your patience!).

2020-01-22 19:26 UTC, ma1uta commented
Thanks!