Avoid double registration of providers
quarkusio/quarkus pull request #44052
Opened 2024-10-23 16:03 UTC by radcortez

TODO

2024-10-24 08:05 UTC, gsmet commented
@cdsap The failure reported above look a bit concerning ^

2024-10-24 08:21 UTC, gsmet requested changes
I think this makes things a lot more confusing. I'm not saying the new logic is wrong, just that it's very hard to follow.

We need to make sure the purpose of the sets is understandable and the new code is mixing them all to make it work for what you want to achieve and we completely lost the initial semantic.

I can take a stab at it if you don't feel like it.

2024-10-24 08:21 UTC, gsmet commented on extensions/resteasy-classic/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java
> +            }
I think this is extremely confusing. If we have to do crazy things like that, we need to categorize the providers properly and not rely on names like `contributedProviders` or `availableProviders`. There's no way to actually figure out what's going on when reading this code without going line by line and try to figure out what they  could contain.

2024-10-24 08:21 UTC, gsmet commented on extensions/resteasy-classic/resteasy-common/deployment/src/main/java/io/quarkus/resteasy/common/deployment/ResteasyCommonProcessor.java
> +        contributedProviders.add(ServerFormUrlEncodedProvider.class.getName());
See my other comment. You're changing the semantic of `contributedProviders` by adding this class in it (it's one that is registered by RESTEasy, not a contributed one) and this is problematic IMO. It makes things extremely confusing.

2024-10-24 10:40 UTC, radcortez commented
> I think this makes things a lot more confusing. I'm not saying the new logic is wrong, just that it's very hard to follow.
> 
> We need to make sure the purpose of the sets is understandable and the new code is mixing them all to make it work for what you want to achieve and we completely lost the initial semantic.
> 
> I can take a stab at it if you don't feel like it.

I agree. I just wanted to minimize the changes. Let me rework this properly.

2024-10-24 14:08 UTC, cdsap commented
Hi @gsmet,
after analyzing one of the failing tests, we have for the last [28 days](https://ge.quarkus.io/scans/tests?search.relativeStartTime=P28D&search.timeZoneId=America%2FLos_Angeles&tests.container=io.quarkus.gradle.ImageTasksWithConfigurationCacheTest):
* 1 Flaky execution
* 2 Failing executions

The flaky execution is caused by a `503 Service Unavailable` when building the docker [image](https://ge.quarkus.io/s/fkf4eaitlfl7w/tests/goal/io.quarkus:quarkus-integration-test-gradle-plugin:surefire:test@default-test/details/io.quarkus.gradle.ImageTasksWithConfigurationCacheTest/shouldReuseConfigurationCacheWithProjectIsolationImageBuildIfTheExtensionIsAdded?focused-execution=1&page=eyJvdXRwdXQiOnsiMCI6NH19&top-execution=1#L616) on: 
```
ERROR: failed to solve: registry.access.redhat.com/ubi8/openjdk-21:1.18: failed to resolve source metadata for 
registry.access.redhat.com/ubi8/openjdk-21:1.18: unexpected status from HEAD request to 
https://registry.access.redhat.com/v2/ubi8/openjdk-21/manifests/1.18: 503 Service Unavailable
```

Similarly, the failing executions are related to a `502 Bad Gateway` when requesting `registry.access.redhat.com/ubi8/openjdk-21:1.18`:
```
ERROR: failed to solve: registry.access.redhat.com/ubi8/openjdk-21:1.18: failed to resolve source metadata for registry.access.redhat.com/ubi8/openjdk-21:1.18: unexpected status from HEAD request to 
https://registry.access.redhat.com/v2/ubi8/openjdk-21/manifests/1.18: 502 Bad Gateway
```

What are your thoughts on this? Is the service degradation a temporary issue, or should I avoid building the Docker images during these integration tests?

2024-11-25 15:59 UTC, gsmet approved these changes
I rebased and fixed a small typo, let's merge when CI is green.

2024-11-26 18:27 UTC, merged