Revise TLS registry documentation
quarkusio/quarkus pull request #44123
Opened 2024-10-27 22:37 UTC by sNiXx

Based on the discussion with @cescoffier [here](https://github.com/quarkusio/quarkus/discussions/43365), I tried to clarify a few aspects that were not yet in the documentation.

I hope this is helpful.

2024-10-28 07:15 UTC, cescoffier requested changes
LGTM,

Just a small suggestion.

2024-10-28 07:15 UTC, cescoffier commented on docs/src/main/asciidoc/tls-registry-reference.adoc
> +NOTE: In Quarkus dev mode, files are touched, which will trigger the `CertificateUpdatedEvent` much more frequently.
```suggestion
NOTE: In Quarkus dev mode, when files are touched, it will trigger the `CertificateUpdatedEvent` much more frequently.
```

2024-10-29 07:22 UTC, cescoffier approved these changes

2024-10-29 07:22 UTC, cescoffier commented
Can you rebase and squash your commit?

2024-10-30 09:28 UTC, geoand commented
I rebased and force-pushed

2024-10-30 10:09 UTC, merged