Adding Scm-Revision to quarkus-core jars
quarkusio/quarkus pull request #44187
Opened 2024-10-30 10:48 UTC by franz1981

This is following https://github.com/quarkusio/quarkus/pull/33614 but re-introducing `Scm-Revision` back to quarkus-core jar

2024-10-30 12:24 UTC, franz1981 commented
@gastaldi too

2024-10-30 12:25 UTC, gastaldi approved these changes
Good catch!

2024-10-30 12:35 UTC, gsmet requested changes
Actually, it's not a mistake. It has been removed and only activated on releases: https://github.com/quarkusio/quarkus/blob/main/independent-projects/parent/pom.xml#L535-L541 .

This to be more compatible with the Develocity cache.

2024-10-30 12:45 UTC, franz1981 commented
> This to be more compatible with the Develocity cache.

this is creating some problem in the quarkus startup perf tests (getting-started and config-quickstart) as we don't have anymore this information shipped with the built jars.

2024-10-30 12:59 UTC, gsmet commented
This explanation should probably have been in the description from the get go :).

I can see the requirement, but we cannot just reintroduce it like that. I'll have a look.

2024-10-30 13:03 UTC, gsmet commented
@jprinet this should be enough to allow us reintroducing `Scm-Revision` in the `MANIFEST.MF`, right?

https://github.com/quarkusio/quarkus-project-develocity-extension/pull/50

2024-10-30 13:04 UTC, franz1981 commented
thanks @gsmet I've updated the description :+1:

2024-10-30 13:07 UTC, gsmet commented
I'll drive this puppy home once I get the confirmation from @jprinet as it's something we did together a long time ago. Then I'll release the Develocity extension and will update this PR with the update.

2024-10-30 13:09 UTC, franz1981 commented
Many thanks @gsmet super fast and reactive!

2024-10-30 14:11 UTC, gsmet commented
> You could still have an impact if a Jar file containing such Manifest would be an input with RELATIVE_PATH normalization for instance.

I checked and I /think/ we should be fine...

2024-10-31 12:53 UTC, gsmet approved these changes
The Develocity Maven extension was updated in main so we can merge this one now.

2024-10-31 12:53 UTC, merged

2024-10-31 13:18 UTC, franz1981 commented
Many thanks @gsmet !!! highly appreciated!