Add nodeSelector capability to kubernetes extension
quarkusio/quarkus pull request #44273
Opened 2024-11-03 07:54 UTC by Vinche59

Fix https://github.com/quarkusio/quarkus/issues/44122

Another PR exists here:  https://github.com/Vinche59/quarkus/commit/36c7d2adade8e5c7617ac23d57f39c45eb4db73c but for that one, we'd need this dekorate PR: https://github.com/dekorateio/dekorate/pull/1299 to be merged and bumped in Quarkus

2024-11-07 14:44 UTC, geoand commented
@iocanel can you have a look at this one?

Thanks

2024-11-07 16:12 UTC, iocanel requested changes
I think that we could propably get away with just using two String fields in the decorator implementation rather than copying the whole NodeSelector and its generated builder.

While, this is no biggie I think that this change worths the effort.

2024-11-09 16:57 UTC, Vinche59 commented
@iocanel Thanks for the review and changes proposition.
I updated, I hope :-), the PR accordingly.

2024-11-09 17:02 UTC, iocanel approved these changes

2024-11-09 17:28 UTC, merged