fixed Timestamp not being set for otel log signals
quarkusio/quarkus pull request #44507
Opened 2024-11-14 12:51 UTC by Chris18230

When using the otel logging, the log messages where displayed wrong in the Elastic Stack because the Timestamp was not set to the Log Signal. The Reason for this is that APM-Server is using the Timestamp and not the ObservedTimestamp for displaying the Message. For this reason they where display in the year 1970 in Elastic Stack.

2024-11-14 13:09 UTC, geoand commented
Thanks for the contribution!

Please rebase the PR onto `main` so it does not include merge commits.

2024-11-14 13:10 UTC, gsmet commented
`git config --global pull.rebase true` might be helpful

2024-11-14 13:14 UTC, gsmet commented
I just rebased it with the GitHub UI.

2024-11-14 14:25 UTC, geoand reviewed
Seems reasonable to me, but let's let @brunobat decide

2024-11-14 16:11 UTC, brunobat approved these changes
Makes sense to me.

2024-11-14 16:13 UTC, brunobat commented on extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/logs/OpenTelemetryLogHandler.java
> +                .setTimestamp(record.getInstant())
Needs to be current time, not the record instant, that's the same as the observed from the line bellow.

2024-11-14 16:14 UTC, brunobat requested changes
Please check comments above.

2024-11-15 11:58 UTC, brunobat approved these changes
Thanks!

2024-11-15 12:52 UTC, gsmet commented
The history is problematic, I will fix it.

2024-11-15 14:00 UTC, merged

2024-11-15 14:00 UTC, gsmet commented
Thanks for the fix! It will be included in the next 3.16.