Coordinated Vert.x 4.5.11 upgrades
quarkusio/quarkus pull request #44515
Opened 2024-11-14 17:15 UTC by jponge

Upgrades to:

- Vert.x 4.5.11
- Vert.x Mutiny bindings 3.1.6.0
- Netty 4.1.115.Final

2024-11-14 17:27 UTC, cescoffier approved these changes
LGTM! 
Should we "undraft" it to run the full CI?

2024-11-14 17:29 UTC, jponge commented
I just want to have a look at https://github.com/eclipse-vertx/vert.x/pull/5387

2024-11-14 17:31 UTC, cescoffier commented
@mkouba could you help @jponge with https://github.com/eclipse-vertx/vert.x/pull/5387? We may also need to check Quarkus HTTP (Jakarta WebSocket)

2024-11-14 17:32 UTC, jponge commented
That being said the old API is still there but deprecated, so that might be another PR (at least @mkouba is aware that there's a change here)

2024-11-14 17:36 UTC, geoand approved these changes

2024-11-14 20:02 UTC, jponge commented
Looks like we have some failures, we'll see with the summary report what's to be investigated

2024-11-14 21:02 UTC, jponge commented
The issues are SSL-related, see `./mvnw verify -f integration-tests/vertx-http -Pnative`:

```
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.793 s <<< FAILURE! -- in io.quarkus.it.vertx.Http2TestCaseIT
[ERROR] io.quarkus.it.vertx.Http2TestCaseIT.testHttp2EnabledSsl -- Time elapsed: 0.112 s <<< ERROR!
java.util.concurrent.ExecutionException: io.vertx.core.VertxException: Connection was closed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.quarkus.it.vertx.Http2TestCase.runTest(Http2TestCase.java:108)
	at io.quarkus.it.vertx.Http2TestCase.runHttp2EnabledSsl(Http2TestCase.java:72)
	at io.quarkus.it.vertx.Http2TestCase.testHttp2EnabledSsl(Http2TestCase.java:42)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:805)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: io.vertx.core.VertxException: Connection was closed
```

and:

```
[ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.119 s <<< FAILURE! -- in io.quarkus.it.vertx.VertxProducerResourceIT
[ERROR] io.quarkus.it.vertx.VertxProducerResourceIT.testRouteRegistrationMTLS -- Time elapsed: 0.203 s <<< ERROR!
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
	at java.base/java.net.Socket$SocketInputStream.implRead(Socket.java:1108)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1095)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1462)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1068)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:161)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.jav

(--- snip ----)
```

2024-11-15 07:08 UTC, mkouba commented
> @mkouba could you help @jponge with [eclipse-vertx/vert.x#5387](https://github.com/eclipse-vertx/vert.x/pull/5387)? We may also need to check Quarkus HTTP (Jakarta WebSocket)

> That being said the old API is still there but deprecated, so that might be another PR (at least @mkouba is aware that there's a change here)

AFAIK we don't use the old API at all. Basically, the endpoint handler does not attempt to perform the upgrade if an [`HttpUpgradeCheck`](https://github.com/quarkusio/quarkus/blob/main/extensions/websockets-next/runtime/src/main/java/io/quarkus/websockets/next/HttpUpgradeCheck.java) does not permit to do so.

2024-11-15 07:14 UTC, mkouba commented
FTR the `io.quarkus.extest.OverrideBuildTimeConfigTes` fails with:
```
2024-11-15T02:09:25.5750882Z Caused by: java.util.NoSuchElementException: SRCFG00027: Could not find a mapping for io.quarkus.runtime.ConfigConfig
2024-11-15T02:09:25.5751959Z 	at io.smallrye.config.SmallRyeConfig.getConfigMapping(SmallRyeConfig.java:631)
2024-11-15T02:09:25.5752713Z 	at io.smallrye.config.SmallRyeConfig.getConfigMapping(SmallRyeConfig.java:621)
2024-11-15T02:09:25.5753553Z 	at io.quarkus.runtime.configuration.ConfigRecorder.handleConfigChange(ConfigRecorder.java:63)
2024-11-15T02:09:25.5754601Z 	at io.quarkus.deployment.steps.ConfigGenerationBuildStep$checkForBuildTimeConfigChange1532146938.deploy_8(Unknown Source)
2024-11-15T02:09:25.5755747Z 	at io.quarkus.deployment.steps.ConfigGenerationBuildStep$checkForBuildTimeConfigChange1532146938.deploy(Unknown Source)
```

CC @radcortez @gsmet

2024-11-15 07:42 UTC, cescoffier commented
I'm a bit worried about the SSL IT issues. It can come from a change in Netty (we know that that code changed) or the PR from Franz changing the allocator when using SSL (the PR should have been super defensive, but never know)

2024-11-15 07:43 UTC, cescoffier commented
`io.quarkus.smallrye.reactivemessaging.hotreload.ConnectorChangeTest.testUpdatingConnector` is unlikely related. @ozangunalp is this a flaky test?

2024-11-15 07:57 UTC, jponge commented
@mkouba I've tried running `./mvnw verify -f integration-tests/test-extension` across Java 22 / 21 / 17 locally and could indeed reproduce the failure on 21. In my case I got the following failure:

```
[INFO] --- surefire:3.5.0:test (default-test) @ quarkus-integration-test-test-extension-tests ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[ERROR] projects/project-using-test-template-from-extension-processed/target/test-classes/org/acme/TemplatedNormalTest (wrong name: org/acme/TemplatedNormalTest)
```

I'm not this relates to the changes in this PR, it might be a different issue IMHO.

2024-11-15 08:01 UTC, jponge commented
Edit: it failed also with 17

2024-11-15 08:04 UTC, jponge commented
/cc @franz1981

2024-11-15 08:19 UTC, franz1981 commented
> the PR from Franz changing the allocator when using SSL

It was passing the tests on Vertx, which by default was still using the default approach, so...it should be fine(tm).

I can take an additional look If you're blocked @jponge ?

2024-11-15 09:10 UTC, cescoffier requested changes
Some Test failures are related.

2024-11-15 09:17 UTC, ozangunalp commented
> `io.quarkus.smallrye.reactivemessaging.hotreload.ConnectorChangeTest.testUpdatingConnector` is unlikely related. @ozangunalp is this a flaky test?

Yes it is. I'd need to rewrite those tests when I find some time.

2024-11-15 09:33 UTC, cescoffier commented
Trying to reproduce it on my machine.

2024-11-15 10:06 UTC, jponge commented
Let's the new run on 17, and then I will need to edit the commits because it's not clean

2024-11-15 10:54 UTC, radcortez commented
> FTR the `io.quarkus.extest.OverrideBuildTimeConfigTes` fails with:

Strange. I did change that very recently in https://github.com/quarkusio/quarkus/pull/44079, which was merged yesterday, but the CI was green. I've just checked out the PR and run it locally, and it also passes.

Let me try to investigate it further.

2024-11-15 14:47 UTC, jponge commented
(let me redo my commits)

2024-11-15 14:52 UTC, jponge commented
Here's a single commit 🚀

2024-11-15 17:05 UTC, jponge commented
@cescoffier pending another CI run completes, do you still want to hold on?

2024-11-15 17:10 UTC, mkouba approved these changes

2024-11-15 18:51 UTC, cescoffier commented
Let's wait for that run to complete.

2024-11-17 14:53 UTC, cescoffier approved these changes
We are good to go. I would wait a bit before backporting 
(even if it will need backport)

2024-11-17 14:53 UTC, merged

2024-11-17 17:40 UTC, miguelborges99 commented
Will this be applied also in the LTS version?

2024-11-17 17:49 UTC, geoand commented
That's what the `backport-3.15` label is for 😉

2024-11-17 18:17 UTC, cescoffier commented
As I said in my last comment - yes, we want to backport it, but not immediately. There are some changes in Netty that need longer testing.

2024-11-17 19:44 UTC, franz1981 commented
Yep, i Will send the PRs (or delegate) next week