Support protoc Kotlin code generation
quarkusio/quarkus pull request #44552
Opened 2024-11-17 16:50 UTC by PhilKes

Closes #39127

This PR adds support to generate [Kotlin DSLs/Extensions for protoc](https://protobuf.dev/reference/kotlin/kotlin-generated/) via adding the `kotlin_out` parameter to the `protoc` command:

* By default, the Kotlin code generation is enabled if the dependency `io.quarkus:quarkus-kotlin` is present
* It can be explicetely en-/disabled via the `quarkus.generate-code.grpc.kotlin.generate` property

To test it I reused the `kotlin-grpc-project` integration-test to use the generated DSL for `HelloMsg`.
Now currently when running the `KotlinGRPCProjectBuildTest`, `compileKotlin` fails with:

```shell
e: file://.../quarkus/integration-tests/gradle/target/classes/kotlin-grpc-project/build/classes/java/quarkus-generated-sources/grpc/io/quarkus/example/HelloMsgKt.kt:15:17 Annotation argument must be a compile-time constant.
e: file://.../quarkus/integration-tests/gradle/target/classes/kotlin-grpc-project/build/classes/java/quarkus-generated-sources/grpc/io/quarkus/example/HelloMsgKt.kt:15:37 Unresolved reference 'kotlin'.
e: file://.../quarkus/integration-tests/gradle/target/classes/kotlin-grpc-project/build/classes/java/quarkus-generated-sources/grpc/io/quarkus/example/HelloMsgKt.kt:16:24 Unresolved reference 'kotlin'.
```

I am guessing this is because the generated kotlin code should not be in `build/classes/java` but rather `build/classes/kotlin`?
But if we provide a different output path for the `kotlin_out` than for `java_out` we would need a way to add this extra path also to the compile sources, which is done in `CodeGenerator.init()`, right?

2024-11-18 10:35 UTC, gsmet requested changes
This looks promising, thanks for the PR.

I suggested some minor doc changes and more importantly it seems some Gradle tests are failing and I think that's the important bit:

```
2024-11-17T17:13:44.2059374Z Options for KOTLIN DAEMON: IncrementalCompilationOptions(super=CompilationOptions(compilerMode=INCREMENTAL_COMPILER, targetPlatform=JVM, reportCategories=[0, 3], reportSeverity=2, requestedCompilationResults=[0], kotlinScriptExtensions=[]), areFileChangesKnown=false, modifiedFiles=null, deletedFiles=null, classpathChanges=NotAvailableForNonIncrementalRun, workingDir=/home/runner/work/quarkus/quarkus/integration-tests/gradle/target/kotlin-grpc-project12669661681070306965/build/kotlin/compileKotlin/cacheable, multiModuleICSettings=MultiModuleICSettings(buildHistoryFile=/home/runner/work/quarkus/quarkus/integration-tests/gradle/target/kotlin-grpc-project12669661681070306965/build/kotlin/compileKotlin/local-state/build-history.bin, useModuleDetection=false), usePreciseJavaTracking=true, icFeatures=IncrementalCompilationFeatures(withAbiSnapshot=false, preciseCompilationResultsBackup=true, keepIncrementalCompilationCachesInMemory=true, enableUnsafeIncrementalCompilationForMultiplatform=false), outputFiles=[/home/runner/work/quarkus/quarkus/integration-tests/gradle/target/kotlin-grpc-project12669661681070306965/build/classes/kotlin/main, /home/runner/work/quarkus/quarkus/integration-tests/gradle/target/kotlin-grpc-project12669661681070306965/build/kotlin/compileKotlin/cacheable, /home/runner/work/quarkus/quarkus/integration-tests/gradle/target/kotlin-grpc-project12669661681070306965/build/kotlin/compileKotlin/local-state])
2024-11-17T17:13:44.2061194Z e: file:///home/runner/work/quarkus/quarkus/integration-tests/gradle/target/kotlin-grpc-project12669661681070306965/build/classes/java/quarkus-generated-sources/grpc/io/quarkus/example/HelloMsgKt.kt:15:17 Annotation argument must be a compile-time constant.
2024-11-17T17:13:44.2063191Z e: file:///home/runner/work/quarkus/quarkus/integration-tests/gradle/target/kotlin-grpc-project12669661681070306965/build/classes/java/quarkus-generated-sources/grpc/io/quarkus/example/HelloMsgKt.kt:15:37 Unresolved reference 'kotlin'.
2024-11-17T17:13:44.2065030Z e: file:///home/runner/work/quarkus/quarkus/integration-tests/gradle/target/kotlin-grpc-project12669661681070306965/build/classes/java/quarkus-generated-sources/grpc/io/quarkus/example/HelloMsgKt.kt:16:24 Unresolved reference 'kotlin'.
2024-11-17T17:13:44.2065363Z Finished executing kotlin compiler using DAEMON strategy
```

2024-11-18 10:35 UTC, gsmet commented on docs/src/main/asciidoc/grpc-generation-reference.adoc
> +== Kotlin Code Generation
We try to avoid uppercasing the titles.
```suggestion
== Kotlin code generation
```

2024-11-18 10:35 UTC, gsmet commented on docs/src/main/asciidoc/grpc-generation-reference.adoc
> +By default, the Kotlin Code Generation is enabled if the dependency `io.quarkus:quarkus-kotlin` is present.
```suggestion
By default, the Kotlin code generation is enabled if the dependency `io.quarkus:quarkus-kotlin` is present.
```

2024-11-18 10:36 UTC, gsmet commented
@cdsap I'm not sure if it's related to this change but I have seen the following in the logs and it doesn't look like something we would want:

```
2024-11-17T17:13:44.2065823Z 2 problems were found storing the configuration cache.
2024-11-17T17:13:44.2068318Z - Task `:quarkusDev` of type `io.quarkus.gradle.tasks.QuarkusDev`: cannot serialize object of type 'org.gradle.api.internal.artifacts.configurations.DefaultUnlockedConfiguration', a subtype of 'org.gradle.api.artifacts.Configuration', as these are not supported with the configuration cache.
2024-11-17T17:13:44.2069077Z   See https://docs.gradle.org/8.9/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
2024-11-17T17:13:44.2071428Z - Task `:quarkusDev` of type `io.quarkus.gradle.tasks.QuarkusDev`: cannot serialize object of type 'org.gradle.api.internal.tasks.DefaultSourceSet', a subtype of 'org.gradle.api.tasks.SourceSet', as these are not supported with the configuration cache.
2024-11-17T17:13:44.2072168Z   See https://docs.gradle.org/8.9/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
```

2024-11-19 00:16 UTC, cdsap commented
@gsmet I tested with a version without the configuration cache changes ([3.15.1](https://ge.solutions-team.gradle.com/s/g33okmapudxeg/build-dependencies?toggled=W1swXSxbMCwwXSxbMCwwLFsyXV0sWzAsMCxbMiwzXV1d)), I'm observing the same log:
https://ge.solutions-team.gradle.com/s/g33okmapudxeg/console-log?page=1#L73

Note that I'm executing the build like: ` ./gradlew clean quarkusDev --configuration-cache --no-build-cache`

Will confirm with the team

2024-11-19 17:41 UTC, PhilKes commented on docs/src/main/asciidoc/grpc-generation-reference.adoc
> +By default, the Kotlin Code Generation is enabled if the dependency `io.quarkus:quarkus-kotlin` is present.
Done

2024-11-19 17:44 UTC, PhilKes commented
> This looks promising, thanks for the PR.
> 
> I suggested some minor doc changes and more importantly it seems some Gradle tests are failing and I think that's the important bit:
> 
> ```
> 2024-11-17T17:13:44.2059374Z Options for KOTLIN DAEMON: IncrementalCompilationOptions(super=CompilationOptions(compilerMode=INCREMENTAL_COMPILER, targetPlatform=JVM, reportCategories=[0, 3], reportSeverity=2, requestedCompilationResults=[0], kotlinScriptExtensions=[]), areFileChangesKnown=false, modifiedFiles=null, deletedFiles=null, classpathChanges=NotAvailableForNonIncrementalRun, workingDir=/home/runner/work/quarkus/quarkus/integration-tests/gradle/target/kotlin-grpc-project12669661681070306965/build/kotlin/compileKotlin/cacheable, multiModuleICSettings=MultiModuleICSettings(buildHistoryFile=/home/runner/work/quarkus/quarkus/integration-tests/gradle/target/kotlin-grpc-project12669661681070306965/build/kotlin/compileKotlin/local-state/build-history.bin, useModuleDetection=false), usePreciseJavaTracking=true, icFeatures=IncrementalCompilationFeatures(withAbiSnapshot=false, preciseCompilationResultsBackup=true, keepIncrementalCompilationCachesInMemory=true, enableUnsafeIncrementalCompilationForMultiplatform=false), outputFiles=[/home/runner/work/quarkus/quarkus/integration-tests/gradle/target/kotlin-grpc-project12669661681070306965/build/classes/kotlin/main, /home/runner/work/quarkus/quarkus/integration-tests/gradle/target/kotlin-grpc-project12669661681070306965/build/kotlin/compileKotlin/cacheable, /home/runner/work/quarkus/quarkus/integration-tests/gradle/target/kotlin-grpc-project12669661681070306965/build/kotlin/compileKotlin/local-state])
> 2024-11-17T17:13:44.2061194Z e: file:///home/runner/work/quarkus/quarkus/integration-tests/gradle/target/kotlin-grpc-project12669661681070306965/build/classes/java/quarkus-generated-sources/grpc/io/quarkus/example/HelloMsgKt.kt:15:17 Annotation argument must be a compile-time constant.
> 2024-11-17T17:13:44.2063191Z e: file:///home/runner/work/quarkus/quarkus/integration-tests/gradle/target/kotlin-grpc-project12669661681070306965/build/classes/java/quarkus-generated-sources/grpc/io/quarkus/example/HelloMsgKt.kt:15:37 Unresolved reference 'kotlin'.
> 2024-11-17T17:13:44.2065030Z e: file:///home/runner/work/quarkus/quarkus/integration-tests/gradle/target/kotlin-grpc-project12669661681070306965/build/classes/java/quarkus-generated-sources/grpc/io/quarkus/example/HelloMsgKt.kt:16:24 Unresolved reference 'kotlin'.
> 2024-11-17T17:13:44.2065363Z Finished executing kotlin compiler using DAEMON strategy
> ```

Thanks for the feedback. I am aware of the failing tests, as I described in the PR description I am not sure what the problem is since I dont have much experienced with mixed java/kotlin generated sources. Do the generated kotlin sources have to be in another folder than the generated java code? (see my original PR description)

2024-12-02 16:11 UTC, PhilKes commented
Any feedback on this, @geoand, @alesj, @cescoffier? 🙂

2025-02-19 19:27 UTC, PhilKes commented
> @PhilKes did you look at the gradle issue?

@cescoffier I looked at it, the generated `HelloMsgKt` needs the additional dependency [protobuf-kotlin](https://mvnrepository.com/artifact/com.google.protobuf/protobuf-kotlin) for some annotations:

```kotlin
// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: hello.proto
//...
public object HelloMsgKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
 //...
```
Now I am not sure how to proceed, should I add a check for the `protobuf-kotlin` dependency being present in `containsQuarkusKotlin()` or should `protobuf-kotlin` be added to `quarkus-kotlin` dependencies?

2025-02-24 07:20 UTC, cescoffier commented
> Should protobuf-kotlin be added to quarkus-kotlin dependencies

Does it need to be available at runtime or only at build time? If it's only build time, we can "just" document that when using Gradle this dependency is necessary.

2025-02-24 21:04 UTC, PhilKes commented
> > Should protobuf-kotlin be added to quarkus-kotlin dependencies
> 
> Does it need to be available at runtime or only at build time? If it's only build time, we can "just" document that when using Gradle this dependency is necessary.

Indeed it's only needed at build-time so I added it as a `compileOnly` dependency and added a note in the documentation

2025-02-25 06:37 UTC, cescoffier requested changes
Just a minor comment on the doc

2025-02-25 06:37 UTC, cescoffier commented on docs/src/main/asciidoc/grpc-generation-reference.adoc
> +You also have to include `com.google.protobuf:protobuf-kotlin` as a `compileOnly` dependency in your project.
I would move that into an admonition mentioning it's only for gradle.

2025-02-25 16:40 UTC, PhilKes commented on docs/src/main/asciidoc/grpc-generation-reference.adoc
> +You also have to include `com.google.protobuf:protobuf-kotlin` as a `compileOnly` dependency in your project.
Done

2025-02-25 17:38 UTC, cescoffier approved these changes
Thanks!

2025-02-25 17:39 UTC, cescoffier commented
Let's see what the CI says.

2025-02-26 16:55 UTC, PhilKes commented
@cescoffier looks like there is something wrong with the build pipeline?

`./mvnw: line 327: /c/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/17.0.14-7/x64/bin/java: Argument list too long`
https://github.com/quarkusio/quarkus/actions/runs/13529572158/job/37808886665?pr=44552#step:17:36

2025-02-26 17:11 UTC, cescoffier commented
Hum, no, on Windows we need to use  the file approach to workaround that issue. So, arguments are written in a file and passed as @file if I remember correctly

2025-02-27 21:50 UTC, PhilKes commented
> Hum, no, on Windows we need to use the file approach to workaround that issue. So, arguments are written in a file and passed as @file if I remember correctly

Well the build succeeded now after a n update via ebase

2025-02-28 07:56 UTC, merged

2025-02-28 07:56 UTC, cescoffier commented
Thanks!

2025-03-07 19:10 UTC, edeandrea commented
Hello. I think this is the culprit of what we're seeing in https://github.com/quarkusio/quarkus/issues/23612#issuecomment-2706478852

In the superheroes sample application, the `grpc-locations` application build is now failing since March 2.

Setting `quarkus.generate-code.grpc.kotlin.generate=false` does allow me to get around this problem, but there is definitely a problem here.

2025-04-25 18:47 UTC, edeandrea commented
Hi @PhilKes just a question about this as I've started integrating this into one of my apps. Does this change support the use of the [coroutine base impl](https://grpc.io/docs/languages/kotlin/quickstart/#update-the-server) for kotlin-based gRPC servers?

When I ran the compilation I didn't see the `CoroutineImplBase` class generated. Just the pojos using the kotlin builder dsl.

2025-04-27 12:38 UTC, PhilKes commented
> Hi @PhilKes just a question about this as I've started integrating this into one of my apps. Does this change support the use of the [coroutine base impl](https://grpc.io/docs/languages/kotlin/quickstart/#update-the-server) for kotlin-based gRPC servers?
> 
> When I ran the compilation I didn't see the `CoroutineImplBase` class generated. Just the pojos using the kotlin builder dsl.

From what I understand the `CoroutineImplBase` is generated by the [grpc-kotlin/protoc-gen-grpc-kotlin](https://github.com/grpc/grpc-kotlin/) plugin (see [GrpcCoroutineServerGenerator](https://github.com/grpc/grpc-kotlin/blob/6f774052d1d6923f8af2e0023886d69949b695ee/compiler/src/main/java/io/grpc/kotlin/generator/GrpcCoroutineServerGenerator.kt)), but so far `quarkus-grpc-codegen` only seems to use `protoc-gen-grpc-java`.

2025-04-27 21:58 UTC, edeandrea commented
Maybe that's something I can add in a future PR
----------
Sent from a mobile device

On Sun, Apr 27, 2025, 8:38 AM Phil ***@***.***> wrote:

> *PhilKes* left a comment (quarkusio/quarkus#44552)
> <https://github.com/quarkusio/quarkus/pull/44552#issuecomment-2833438874>
>
> Hi @PhilKes <https://github.com/PhilKes> just a question about this as
> I've started integrating this into one of my apps. Does this change support
> the use of the coroutine base impl
> <https://grpc.io/docs/languages/kotlin/quickstart/#update-the-server> for
> kotlin-based gRPC servers?
>
> When I ran the compilation I didn't see the CoroutineImplBase class
> generated. Just the pojos using the kotlin builder dsl.
>
> From what I understand the CoroutineImplBase is generated by the
> grpc-kotlin/protoc-gen-grpc-kotlin <https://github.com/grpc/grpc-kotlin/>
> plugin (see GrpcCoroutineServerGenerator
> <https://github.com/grpc/grpc-kotlin/blob/6f774052d1d6923f8af2e0023886d69949b695ee/compiler/src/main/java/io/grpc/kotlin/generator/GrpcCoroutineServerGenerator.kt>),
> but so far quarkus-grpc-codegen only seems to use protoc-gen-grpc-java.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/quarkusio/quarkus/pull/44552#issuecomment-2833438874>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACYXNYBQL7YNGHKLBBQMO323TFU3AVCNFSM6AAAAABR6DSPFCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDQMZTGQZTQOBXGQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-04-28 08:15 UTC, geoand commented
> I guess you could add protoc-gen-grpc-kotlin to quarkus-grpc-codegen but then we would again have the problem of conditional dependency if kotlin is used or not, which @geoand had in https://github.com/quarkusio/quarkus/pull/46698, right?

Correct