Update Kotlin to version 2.1.0
quarkusio/quarkus pull request #44809
Opened 2024-11-28 14:33 UTC by andreas-eberle

2024-11-29 14:30 UTC, gsmet commented
Thanks for taking care of this!

2024-12-03 12:59 UTC, andreas-eberle commented
Thanks for the reminder. I forgot I didn't push my last commit and undraft this. It should be updated and hopefully the CI passes now.

2024-12-03 13:02 UTC, geoand commented
Thanks!

2024-12-03 13:02 UTC, geoand approved these changes

2024-12-03 13:35 UTC, geoand commented
CI didn't really run on this which is really weird

2024-12-03 17:28 UTC, gsmet requested changes
Thanks for this effort, greatly appreciated.

I have a question though and I would like to get it sorted out before we merge. See inline.

2024-12-03 20:59 UTC, andreas-eberle commented on integration-tests/resteasy-reactive-kotlin/standard/src/main/kotlin/io/quarkus/it/resteasy/reactive/kotlin/CountryNamePayloadTransformer.kt
> +        return Country(country.name.lowercase(), country.capital)
Yes, this is actually required. The `toLowerCase` method has been deprecated with a warning for a while but now they removed it or changed it to an error (I don't remember exactly any more, but the project didn't compile any longer). So this is a needed fix and `lowercase()` is the intended replacement.

2024-12-04 08:37 UTC, geoand commented
Seems like `quarkus-integration-test-kotlin` is failing because of:

```
2024-12-04T07:18:19.3974147Z Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
2024-12-04T07:18:19.3977020Z 	[error]: Build step io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor#buildExecutionService threw an exception: java.lang.IllegalArgumentException: Provided Metadata instance has version 2.1.0, while maximum supported version is 2.0.0. To support newer versions, update the kotlinx-metadata-jvm library.
2024-12-04T07:18:19.3979808Z 	at kotlinx.metadata.jvm.KotlinClassMetadata$Companion.throwIfNotCompatible$kotlinx_metadata_jvm(KotlinClassMetadata.kt:609)
2024-12-04T07:18:19.3981342Z 	at kotlinx.metadata.jvm.KotlinClassMetadata$Companion.checkMetadataVersionForRead(KotlinClassMetadata.kt:600)
2024-12-04T07:18:19.3982604Z 	at kotlinx.metadata.jvm.KotlinClassMetadata$Companion.read(KotlinClassMetadata.kt:579)
2024-12-04T07:18:19.3983607Z 	at kotlinx.metadata.jvm.KotlinClassMetadata.read(KotlinClassMetadata.kt)
2024-12-04T07:18:19.3984939Z 	at io.smallrye.graphql.schema.creator.OperationCreator.toKotlinClassMetadata(OperationCreator.java:264)
2024-12-04T07:18:19.3986391Z 	at io.smallrye.graphql.schema.creator.OperationCreator.checkWrappedTypeKotlinNullability(OperationCreator.java:126)
2024-12-04T07:18:19.3987866Z 	at io.smallrye.graphql.schema.creator.OperationCreator.createOperation(OperationCreator.java:112)
2024-12-04T07:18:19.3989154Z 	at io.smallrye.graphql.schema.SchemaBuilder.addOperations(SchemaBuilder.java:448)
2024-12-04T07:18:19.3990221Z 	at io.smallrye.graphql.schema.SchemaBuilder.lambda$generateSchema$2(SchemaBuilder.java:159)
2024-12-04T07:18:19.3991175Z 	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:198)
2024-12-04T07:18:19.3992078Z 	at io.smallrye.graphql.schema.SchemaBuilder.generateSchema(SchemaBuilder.java:157)
2024-12-04T07:18:19.3993044Z 	at io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:109)
2024-12-04T07:18:19.3994359Z 	at io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor.buildExecutionService(SmallRyeGraphQLProcessor.java:363)
2024-12-04T07:18:19.3995779Z 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
2024-12-04T07:18:19.3996623Z 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
2024-12-04T07:18:19.3997400Z 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
2024-12-04T07:18:19.3998160Z 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
2024-12-04T07:18:19.3999290Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
2024-12-04T07:18:19.4000364Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
2024-12-04T07:18:19.4001695Z 	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
2024-12-04T07:18:19.4002858Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
2024-12-04T07:18:19.4003716Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-12-04T07:18:19.4004321Z 	at org.jboss.threads.JBossThread.run(JBossThread.java:499)
```

2024-12-04 09:30 UTC, jmartisk commented
Right, I'll try to upgrade `kotlinx.metadata.jvm` in smallrye-graphql, so this will have to wait until a smallrye-graphql upgrade is merged..

2024-12-04 09:30 UTC, geoand commented
Thanks!

2024-12-04 09:39 UTC, gsmet commented on integration-tests/resteasy-reactive-kotlin/standard/src/main/kotlin/io/quarkus/it/resteasy/reactive/kotlin/CountryNamePayloadTransformer.kt
> +        return Country(country.name.lowercase(), country.capital)
I would expect `uppercase()` to be the replacement for `toUpperCase()` :).

2024-12-04 10:40 UTC, andreas-eberle commented
Thanks! Sorry I wasn't able too look for the errors in time. I'm unfortunately a bit swamped right now.

2024-12-05 15:42 UTC, gsmet commented
Waiting for https://github.com/smallrye/smallrye-graphql/pull/2234 to land in Quarkus.

2024-12-20 08:37 UTC, gsmet commented
@andreas-eberle probably a good idea to include these two changes in this PR:
- https://github.com/quarkusio/quarkus/pull/45215/files
- https://github.com/quarkusio/quarkus/pull/45213/files

A new version of SmallRye GraphQL was released so hopefully we will be able to make progress on this one soon!

2024-12-20 09:26 UTC, gsmet commented
Yeah so the GraphQL one won't work as the update breaks things. We will have to wait for the SmallRye GraphQL team to push a proper update.

2024-12-20 09:29 UTC, andreas-eberle commented
Thanks for the info @gsmet. Then I'll rebase the PR as soon as the graphql update is properly integrated.

2024-12-20 10:54 UTC, jmartisk commented
@andreas-eberle I've submitted https://github.com/quarkusio/quarkus/pull/45228 that also incorporates your commit, I think we need to apply both upgrades at the same time. Please check it

2024-12-20 10:58 UTC, andreas-eberle commented
Thanks @jmartisk. Looks good for me from the kotlin update side. Let's see what CI says about your PR. I will close this one.

2024-12-20 10:58 UTC, closed without merging

2024-12-20 10:58 UTC, geoand commented
Closing in favor of #45228