Introduce property to disable default mapper per REST Client
quarkusio/quarkus pull request #44816
Opened 2024-11-28 16:09 UTC by geoand

The default mapper has a very confusing behavior where it throws an exception HTTP code >= 400 even if the method return type is Response.
This PR means to provide a way so users can disable this mapper per client instead of globally.

Closes: #44813

2024-11-28 16:09 UTC, geoand commented
Opening as a draft to if CI will complain on my fork

2024-12-02 06:59 UTC, cescoffier requested changes
Just a typo in the documentation.

The rest looks good.

2024-12-02 06:59 UTC, cescoffier commented on docs/src/main/asciidoc/rest-client.adoc
> +the default exception mapper can be disabled by setting `quarkus.rest-client.foo.disable-default-mapper=true`.
```suggestion
The default exception mapper can be disabled by setting `quarkus.rest-client.bar.disable-default-mapper=true` to disable the exception mapper for the REST Client configured with the key `bar`.
```

Should it be `foo` or `bar` in the property name?

2024-12-02 07:01 UTC, geoand commented
PR updated!

2024-12-02 07:02 UTC, cescoffier approved these changes

2024-12-02 07:02 UTC, cescoffier commented
Damn! You're fast for a Monday morning!

2024-12-02 07:02 UTC, geoand commented
😆

2024-12-02 08:31 UTC, merged