Remote development mode can be used on deployments with context path
quarkusio/quarkus pull request #44840
Opened 2024-11-29 21:09 UTC by albers

[Remote development mode](https://quarkus.io/guides/maven-tooling#remote-development-mode) currently cannot be used on deployments that have a [context path](https://quarkus.io/guides/http-reference#context-path) (aka root url) other than `/`.

Reasons:
1. The paths used by remote dev mode are [hard coded](https://github.com/quarkusio/quarkus/blob/e3ab6bd81c7b1d02b059b5454157bae69ac3279f/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/RemoteSyncHandler.java#L101-L106) and rooted on `/ `.
2. If you add a (context) path to `quarkus.live-reload.url`, it will be honoured by the `./mvnw quarkus remote-dev` command. But when changed files are uploaded, the url of the corresponding PUT request will be used to determine the file location in the image. The files will be placed in sub-folders of their expected location.

This PR fixes both issues. The dev mode endpoints may be prefixed by a context path, and the context path is stripped from file upload urls.

2024-12-02 07:47 UTC, cescoffier requested changes

2024-12-02 07:47 UTC, cescoffier commented on extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/RemoteSyncHandler.java
> +            if (event.path().endsWith(DEV)) {
Should we be more specific and check the root path too?

2024-12-02 12:39 UTC, cescoffier commented on extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/devmode/RemoteSyncHandler.java
> +            if (event.path().endsWith(DEV)) {
Yeah, that is probably fine. I was worried if someone forge a request against another path. But authentication will prevent this.

2024-12-02 12:40 UTC, cescoffier approved these changes

2024-12-03 07:18 UTC, geoand approved these changes
Thanks!

2024-12-03 07:18 UTC, merged