Remove redundant patterns compilations
quarkusio/quarkus pull request #4485
Opened 2019-10-09 20:23 UTC by gwenneg

While looking for the root cause of a bug involving regex, I noticed a few redundant patterns compilations during `String` splits. All modified splits in this PR are called from an enclosing loop.

2019-10-09 20:26 UTC, gwenneg commented
@cescoffier I also noticed there's a lot of duplicated code between `VertxCoreRecorder` and `VertxOptionsBuilder`, and I can't find any call to `VertxOptionsBuilder.buildVertxOptions()` in Quarkus. I was about to change that and then I saw `VertxOptionsBuilder` was added recently. Is there something in progress there or can I clean the duplicated code?

2019-10-09 20:28 UTC, gsmet requested changes
Looks good thanks, except some ``final``s are missing. Could you take care of it?

2019-10-09 20:28 UTC, gsmet commented on extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/runtime/MongoClientRecorder.java
> +    private static Pattern COLON_PATTERN = Pattern.compile(":");
`final`?

2019-10-09 20:28 UTC, gsmet commented on extensions/resteasy/runtime/src/main/java/io/quarkus/resteasy/runtime/standalone/VertxUtil.java
> +    private static Pattern COMMA_PATTERN = Pattern.compile(",");
`final`?

2019-10-09 20:28 UTC, gsmet commented on extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java
> +    private static Pattern COMMA_PATTERN = Pattern.compile(",");
`final`?

2019-10-09 20:28 UTC, gsmet commented on extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxOptionsBuilder.java
> +    private static Pattern COMMA_PATTERN = Pattern.compile(",");
`final`?

2019-10-09 20:32 UTC, gwenneg commented
Oops, that's fixed! Thanks @gsmet.

2019-10-09 20:35 UTC, gsmet approved these changes

2019-10-09 20:36 UTC, gsmet commented
I let @cescoffier give you an answer to your question. I think it's probably something we missed when we reorganized the Vert.x extensions.

2019-10-10 06:21 UTC, merged

2019-10-10 06:21 UTC, cescoffier commented
@gwenneg yes we need to do some cleanup. The split has introduced some duplications.