Add "location-path" to swagger-ui
quarkusio/quarkus pull request #44981
Opened 2024-12-07 12:05 UTC by alexey-plotnikoff

If the quarkus application behind proxy with custom location path swagger UI doesn't work correctly. This PR fix it.

2024-12-09 08:28 UTC, gsmet reviewed
Thanks for the pull request!

I think we need to clarify the semantic here, also because I suppose this part is probably not the only part that would need tweaking.

Question: would it be possible to use relative paths instead and thus avoiding entirely this issue?

2024-12-09 08:41 UTC, alexey-plotnikoff commented
> Question: would it be possible to use relative paths instead and thus avoiding entirely this issue?

Good point. I'll check it.

2024-12-09 12:52 UTC, alexey-plotnikoff commented
@gsmet current plugin generates all links with absolute path:

<img width="1421" alt="Screenshot 2024-12-09 at 19 45 41" src="https://github.com/user-attachments/assets/d3d3f3a5-aa11-4d8f-a844-2b088fb3ef26">

Do you mean I should change all these links to relative paths?

2024-12-11 16:50 UTC, michalvavrik commented
\cc @MikeEdgar

2024-12-11 18:48 UTC, MikeEdgar commented
I agree that this seems like something that would be handled at a high level than just the Swagger UI. For example, the one link being configured is the `backHref` that resolves to `/q/dev`. @alexey-plotnikoff have you tried using the [`quarkus.http.non-application-root-path`](https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus-http-non-application-root-path) configuration for this?

2024-12-13 06:56 UTC, alexey-plotnikoff commented
Thank you @MikeEdgar!
Yes, it works! But I should reconfigure nginx from:
```
server {
    listen  80;
    server_name quarkus.home.arpa;

    location /nginx/path/ {
        proxy_pass http://host.docker.internal:8080/;
    }
}
```
to:
```
server {
    listen  80;
    server_name quarkus.home.arpa;

    location /nginx/path/ {
        proxy_pass http://host.docker.internal:8080/nginx/path/;
    }
}
```

2024-12-16 04:12 UTC, alexey-plotnikoff commented
@MikeEdgar you solution with [quarkus.http.non-application-root-path](https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus-http-non-application-root-path) will change liveness and readiness probes in Kubernetes environment.
So all microservices in Kubernetes will have their own probes instead one for all. For me it is not good solution.
I think will be better add a new parameter for swagger UI only as in this PR.
What do you think?

2024-12-16 18:15 UTC, MikeEdgar commented
I'm not sure if there are other components that should participate with a configuration like the one proposed. I'll let the others chime in on that.

2025-01-16 17:01 UTC, gsmet commented
@cescoffier I think this one should be discussed with you. I'm not entirely sure how we can solve this issue globally.

2025-02-20 09:44 UTC, alexey-plotnikoff commented
@cescoffier What do you think about this PR?

2025-02-25 06:30 UTC, cescoffier requested changes

2025-02-25 06:30 UTC, cescoffier commented on extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiConfig.java
> +    Optional<String> locationPath;
Is it the root path for openapi?

2025-02-25 06:30 UTC, cescoffier commented on extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java
> +                openApiPath = swaggerUiConfig.locationPath.get() + openApiPath;
We may have to normalized the resulting path, or do we expect it to be consistent?

2025-02-25 06:34 UTC, cescoffier commented
I don't believe we can use a global setting here. The global setting will affect the probes, metrics... Now in such kind of setup, the openapi page is considered public, while the probes (and metrics) are considered private. 

The easiest is clearly to configure the extension. 

We could imagine another option to declare the openapi routes to be part of the public API and mounted differently, but it will complexify the routing code.

2025-03-05 15:39 UTC, alexey-plotnikoff commented on extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiConfig.java
> +    Optional<String> locationPath;
<img width="482" alt="Screenshot 2025-03-05 at 22 38 32" src="https://github.com/user-attachments/assets/a1999916-4ab6-436c-bc74-551de1af5619" />

2025-03-05 15:40 UTC, alexey-plotnikoff commented on extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java
> +                openApiPath = swaggerUiConfig.locationPath.get() + openApiPath;
Do you mean I should check a forward slash at the start of `swaggerUiConfig.locationPath.get()` if it doesn't exists?

2025-03-05 15:46 UTC, alexey-plotnikoff commented on extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiConfig.java
> +    Optional<String> locationPath;
Maybe I should rename `locationPath` to `rootPath`?

2025-03-10 07:26 UTC, cescoffier commented on extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiConfig.java
> +    Optional<String> locationPath;
Yes.

2025-03-10 07:27 UTC, cescoffier reviewed
I made some comments.

2025-03-10 19:06 UTC, alexey-plotnikoff commented on extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiConfig.java
> +    Optional<String> locationPath;
Done

2025-03-10 19:06 UTC, alexey-plotnikoff commented on extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java
> +                openApiPath = swaggerUiConfig.locationPath.get() + openApiPath;
Done

2025-03-10 19:07 UTC, alexey-plotnikoff commented
@cescoffier I made fixed. Take a look pls.

2025-03-11 11:51 UTC, cescoffier approved these changes, later dismissed

2025-03-11 12:20 UTC, gsmet requested changes
I suggested an improvement to the doc and asked a question.

2025-03-11 12:20 UTC, gsmet commented on extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java
> +        }
My problem with how it's implemented is that the value is fixed at build time.

Will it fly in standard setups? (Honest question, I don't have an answer)

2025-03-11 12:20 UTC, gsmet commented on extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiConfig.java
> +     * If application behind the proxy with custom root path.
```suggestion
     * Custom root path. Useful when the application is behind a proxy with a custom root path.
```

2025-03-11 13:24 UTC, cescoffier commented on extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java
> +        }
That's a good question.

@phillip-kruger what do you think?

2025-03-11 15:31 UTC, alexey-plotnikoff commented on extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiConfig.java
> +     * If application behind the proxy with custom root path.
Done

2025-03-11 15:39 UTC, alexey-plotnikoff commented on extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java
> +        }
I agree with @gsmet but we have same problem for all variables in `indexHtmlContent`:
1. `openApiPath = nonApplicationRootPathBuildItem.resolvePath(openapi.path());`
2. swaggerUiPath
3. swaggerUiConfig
4. launchMode
5. devServicesLauncherConfigResultBuildItem

2025-03-11 15:42 UTC, alexey-plotnikoff commented
Btw I can delete this dead code:
<img width="987" alt="Screenshot 2025-03-11 at 22 42 40" src="https://github.com/user-attachments/assets/bf664f9c-cc65-43b4-a565-0efa8ddcf21f" />

2025-03-12 01:25 UTC, phillip-kruger commented on extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java
> +        }
At this point swagger ui html is generated at build time. allowing dynamic creation at runtime will be a big change. We can maybe change the static generated html and js to allow some parameters that can change behavior at runtime, but even that is a much bigger change

2025-03-12 01:26 UTC, phillip-kruger approved these changes, later dismissed

2025-03-13 09:10 UTC, alexey-plotnikoff commented
> I suggested an improvement to the doc and asked a question.

1. Improvement is done
2. Question is answered

2025-03-14 12:38 UTC, alexey-plotnikoff commented
Fixed "Imports are not sorted".

2025-03-26 04:47 UTC, alexey-plotnikoff commented
@gsmet ?

2025-05-13 00:07 UTC, melloware approved these changes

2025-09-15 06:21 UTC, cescoffier commented
@alexey-plotnikoff can you rebase? 
@gsmet, can you re-check this PR once you're back? Probably @phillip-kruger too.

2026-02-16 07:39 UTC, cescoffier commented
@alexey-plotnikoff Any chance for you to rebase the PR?

2026-02-16 15:45 UTC, alexey-plotnikoff commented
> @alexey-plotnikoff Any chance for you to rebase the PR?

So much changes!
I'll try.

2026-02-17 15:23 UTC, alexey-plotnikoff commented
> @alexey-plotnikoff Any chance for you to rebase the PR?

@cescoffier could someone approve my changes to start GitHub Actions?

2026-02-19 06:12 UTC, alexey-plotnikoff commented
@cescoffier Merging is blocked by @gsmet from Mar 11, 2025. Looks like he doesn't like my PR 😢

2026-03-15 16:43 UTC, cescoffier commented
It looks like there are merge commits.

2026-07-22 06:13 UTC, closed without merging