[WebSockets Next] add support for ping message callbacks
quarkusio/quarkus pull request #45180
Opened 2024-12-17 22:09 UTC by emattheis

This PR adds an `@OnPingMessage` companion to `@OnPongMessage` for WebSockets Next endpoints. This is useful for endpoints that want to observe ping frames arriving from remote parties. Under the covers it uses the Vert.x frameHandler.

2025-01-06 09:20 UTC, mkouba requested changes
The PR looks good but we should also add a test for the `BasicWebSocketConnector` and a test for an `@OnPingMessage` callback declated on a server endpoint.

2025-01-06 09:20 UTC, mkouba commented on docs/src/main/asciidoc/websockets-next-reference.adoc
> +Endpoints declare <<callback-methods,_callback methods_>> annotated with `@OnTextMessage`, `@OnBinaryMessage`, `@OnPing`, `@OnPong`, `@OnOpen`, `@OnClose` and `@OnError`.
```suggestion
Endpoints declare <<callback-methods,_callback methods_>> annotated with `@OnTextMessage`, `@OnBinaryMessage`, `@OnPingMessage`, `@OnPongMessage`, `@OnOpen`, `@OnClose` and `@OnError`.
```

2025-01-06 09:20 UTC, mkouba commented on docs/src/main/asciidoc/websockets-next-reference.adoc
> +However, it is sometime useful to know when ping or pong messages are received by an endpoint.
```suggestion
However, it is sometimes useful to know when ping or pong messages are received by an endpoint.
```

2025-01-06 09:20 UTC, mkouba commented on docs/src/main/asciidoc/websockets-next-reference.adoc
> +The `@OnPingMessage` and `@OnPongMessage` annotations can be used to define callbacks that consumes ping or pong messages sent from the remote party.
```suggestion
The `@OnPingMessage` and `@OnPongMessage` annotations can be used to define callbacks that consume ping or pong messages sent from the remote party.
```

2025-01-06 09:20 UTC, mkouba commented on docs/src/main/asciidoc/websockets-next-reference.adoc
> +An endpoint may declare at most one callback method for each.
```suggestion
An endpoint may declare at most one `@OnPingMessage` callback and at most  one `@OnPongMessage` callback.
```

2025-01-06 13:54 UTC, emattheis commented
Thanks @mkouba. I accepted the documentation typo fixes and cleaned up the test coverage here: 5a13ed7c0d56f81b663623567e1e263a018e07eb. Let me know if you were looking for something else and I'll give it a shot.

2025-01-08 10:34 UTC, mkouba commented on extensions/websockets-next/deployment/src/main/java/io/quarkus/websockets/next/deployment/WebSocketProcessor.java
> +        if (KotlinUtils.isKotlinMethod(callback.method)) {
Thanks! Could you pls squash the commits?

2025-01-08 15:18 UTC, mkouba approved these changes

2025-01-08 15:18 UTC, merged

2025-01-08 15:33 UTC, gsmet commented
Nice contribution, thanks!