Avoid initializing Netty logger too early
quarkusio/quarkus pull request #45322
Opened 2024-12-31 10:14 UTC by geoand

When initializing `FastThreadLocal` eagerly `VertxCurrentContextFactory.VertxCurrentContext` we were inadvertently forcing the initialization of the logging infrastructure of Netty far too early. 

This can be seen in the following flamegraph (in purple on the right):

![Screenshot from 2024-12-31 12-10-28](https://github.com/user-attachments/assets/9336c864-edb8-426a-afb9-25af2c23f1d8)

This change shouldn't have much of an impact on its own, but it's a good thing as it moves the initialization of the Netty logging out of the main thread

2024-12-31 10:28 UTC, franz1981 commented
The supplier get can keep on creating new fast thread local threads?

2024-12-31 10:40 UTC, geoand commented
> The supplier get can keep on creating new fast thread locals?

Yes, as I did not want to change the existing behavior. 
We probably should change it along the lines you mention, but that is something to be done as a follow up, and something that @mkouba needs to sign off on.

FWIW, under normal circumstances we won't even need the FastThreadLocal (as its name implies)

2025-01-03 09:20 UTC, mkouba commented
> This change shouldn't have much of an impact on its own, but it's a good thing as it moves the initialization of the Netty logging out of the main thread

Well, it can slow down the fallback path a little bit because `LazyValue` wraps a `volatile` but it should not really matter because in most cases the fallback/`FastThreadLocal` is not used at all (i.e. the Vertx duplicated context is available in most cases).
 
> I am a bit surprised we have a non static final fast thread local there tbh, regardless...

It's ok here. There's only one `Context` object created per scope.

2025-01-03 09:22 UTC, mkouba requested changes

2025-01-03 09:22 UTC, mkouba commented on extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxCurrentContextFactory.java
> +        private final LazyValue<FastThreadLocal<T>> fallbackSupplier = new LazyValue<>(
I'd rather keep the `fallback` field name. `LazyValue` is not a supplier after all...

2025-01-03 09:24 UTC, geoand commented on extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxCurrentContextFactory.java
> +        private final LazyValue<FastThreadLocal<T>> fallbackSupplier = new LazyValue<>(
Fixed

2025-01-03 09:35 UTC, mkouba approved these changes

2025-01-03 14:28 UTC, merged