Change to only allow a single output type
quarkusio/quarkus pull request #4780
Opened 2019-10-23 00:24 UTC by stuartwdouglas

2019-10-23 11:58 UTC, gsmet requested changes
I think this is mostly good to go but here are a few fixes and suggestions.

2019-10-23 11:58 UTC, gsmet commented on docs/src/main/asciidoc/building-native-image-guide.adoc
> +These options can be seen in the link:all-config.html[All Config Documentation] under the prefix `quarkus.native.`.
I would rewrite this paragraph and include the properties directly with:
```
include::{generated-dir}/config/quarkus-core-native-config.adoc[opts=optional]
```

2019-10-23 23:34 UTC, stuartwdouglas commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/PackageTypeVerificationBuildStep.java
> +    ServiceStartBuildItem verify(List<PackageTypeBuildItem> items, PackageConfig config) {
So it is run at all

2019-10-23 23:35 UTC, stuartwdouglas commented on docs/src/main/asciidoc/building-native-image-guide.adoc
> +        </properties>
Yes, the current way still works, so existing projects will work as normal.

2019-10-23 23:38 UTC, stuartwdouglas commented on docs/src/main/asciidoc/building-native-image-guide.adoc
>  ====
The pom.xml way still works, and all the properties have the same name. We should definitely document this, but it is not something that should cause any breakage.

2019-10-23 23:47 UTC, dmlloyd commented
This is a bit of a major design change, did I miss the list discussion about this?

2019-10-24 00:01 UTC, stuartwdouglas commented
The problem is that without this change we don't really get much extra flexibility from doing native in a build step (and eventually in an extension). You can produce extra stuff that goes into the image, but that is it.

2019-10-24 00:22 UTC, stuartwdouglas commented
There are also quite a few other problems with the current build step approach:
- Anything that wants to consume the output (e.g. to zip it up into a deployment package) must pick the type of jar they want to consume. If the user has selected a different type both are generated.
- If there is the possibility of generating both we need different names for the uberjar and thin jar in the output dir.

If this PR is a problem then I would rather revert the change to building in build steps and worry about this post 1.0 than stick with the current approach of allowing multiple outputs, as I think it is very limiting and not something we want to get stuck supporting.

2019-10-24 00:25 UTC, dmlloyd commented
There are other ways to get the same kinds of additional flexibility (which we'd want to enumerate anyway).  I think we should have a discussion about whether we want to go this route.

In principle I *like* it because it's simpler - however it's also pretty different from what we had discussed previously from a usability standpoint.  We basically have to be OK with telling the user that they need multiple modules or profiles or something to build multiple output types.

I'm OK with revisiting it later though if nobody else objects.

2019-10-24 00:35 UTC, stuartwdouglas commented
You could do it by having some way of filtering particular build items so they only apply to particular output types, but it is much more complex.

Technically an extension could actually force the generation of multiple output types if required, e.g. by consuming both the JarBuildItem and NativeImageBuildItem. I can't really think of a valid use case where you would want both Uber and Thin jars though, at the moment you can't do it and AKAIK nobody has asked for it.

2019-10-28 21:52 UTC, stuartwdouglas commented
@dmlloyd are you ok with this now after our conversation the other day?

2019-10-28 22:25 UTC, dmlloyd commented
Yes I'm OK with it.  I think that even if we introduce the multi-augment strategy, this change would be a reasonable basis to start with.

2019-10-28 22:25 UTC, dmlloyd approved these changes

2019-10-28 23:07 UTC, gsmet approved these changes

2019-10-29 06:00 UTC, merged