idle timeout for blocking http
quarkusio/quarkus pull request #4963
Opened 2019-10-29 08:22 UTC by michalszynkiewicz

refs #4455

2019-10-29 08:53 UTC, gsmet commented
This uses a SNAPSHOT dependency, it shouldn't be merged.

2019-10-29 10:08 UTC, michalszynkiewicz commented
requires https://github.com/quarkusio/quarkus-http/pull/10

2019-10-29 13:44 UTC, gsmet commented
I force pushed the Beta3 version change as it has been pushed to Central.

let's see what CI has to say.

2019-10-29 14:04 UTC, michalszynkiewicz commented
@gsmet  the released version does not contain https://github.com/quarkusio/quarkus-http/pull/10 so the tests will fail

2019-10-31 03:49 UTC, stuartwdouglas requested changes
Can we get a version of this with just the vert.x idle timeout changes for the 28.0 release?

2019-10-31 03:49 UTC, stuartwdouglas commented on test-framework/common/src/main/java/io/quarkus/test/common/RestAssuredURLManager.java
> +    public static String getHost() {
You should not need these changes. Just inject the URL using @TestHTTPResource and then get the host and port from the URL.

2019-10-31 10:34 UTC, michalszynkiewicz commented
@stuartwdouglas uploaded setting the timeout only

2019-11-06 02:41 UTC, stuartwdouglas approved these changes

2019-11-06 02:42 UTC, merged