unlist unlisted in listextensions
quarkusio/quarkus pull request #5039
Opened 2019-10-30 15:45 UTC by maxandersen

jaeger was being listed via listExtensions.

With this fix any extension with a "unlisted" key in metadata gets unlisted.
i.e. the mere presence of the key makes it unlisted.

2019-10-30 15:47 UTC, maxandersen commented
@emmanuelbernard can you just confirm listExtensions should *always* hide "unlisted" extensions ?
addExtension will actually still work and wondering if should remove extensions completely even in add.

2019-10-30 16:03 UTC, emmanuelbernard requested changes

2019-10-30 16:07 UTC, aloubyansky requested changes
I agree with Emmanuel's remark. Let's check for the value of unlisted.

2019-10-30 20:59 UTC, maxandersen commented on independent-projects/tools/common/src/main/java/io/quarkus/cli/commands/ListExtensions.java
> +        return !e.getMetadata().containsKey("unlisted");
just that technically i can be both true (boolean) or a string 'true'. but sure let me add that together while making add honor it too.

2019-10-31 11:10 UTC, maxandersen commented
I've updated to have check be explicit for "true" or true and addExtension now ignores unlisted unless there is an exact match on artifactId (it never took into account groupid - something we probably want to fix/cleanup in future).

2019-10-31 11:22 UTC, merged