Docs - CDI guide - introduce the "Non-standard Features" section
quarkusio/quarkus pull request #5167
Opened 2019-11-04 12:12 UTC by mkouba

- also try to clarify "Native Executables and Private Members" section

2019-11-04 13:02 UTC, manovotn reviewed
Added few remarks, some of which belong to the docs that were already there. But you know, since you starting poking into it... ;-)

2019-11-04 13:02 UTC, manovotn commented on docs/src/main/asciidoc/cdi-reference.adoc
> +`@DefaultBean` allows extensions (or any other code for that matter) to provide defaults while backing off if beans of that type are supplied in any
This is a repetition of the above I think it could removed.

2019-11-04 13:33 UTC, mkouba commented on docs/src/main/asciidoc/cdi-reference.adoc
> +In CDI, if you declare a field injection point you need to use `@Inject` and optionally required qualifiers:
Ok. `required qualifiers` is an official term but I agree that your proposal read much better...

2019-11-04 13:34 UTC, mkouba commented on docs/src/main/asciidoc/cdi-reference.adoc
> +NOTE: `@Inject` is still required for constructor and method injection.
I don't think so. The point of this note is to clarify that `@Inject` is **still required** for constructors and initializers...

2019-11-04 13:38 UTC, mkouba commented on docs/src/main/asciidoc/cdi-reference.adoc
> +Quarkus adds a capability that CDI currently does not support which is to conditionally declare a bean if no such bean has been declared in the typical ways Quarkus supports.
Well, I'm not the original author of these senteces... my explanation would be even simpler: https://quarkus.io/blog/quarkus-dependency-injection/#default-beans

2019-11-04 13:39 UTC, mkouba commented
@manovotn would you care to propose changes directly in the PR?

2019-11-04 13:47 UTC, manovotn commented on docs/src/main/asciidoc/cdi-reference.adoc
> +NOTE: `@Inject` is still required for constructor and method injection.
Later on we state - `Also if there's only one constructor there is no need for `@Inject`.`
So I just thought the combination of the two can be rather confusing.

2019-11-04 13:55 UTC, mkouba commented
> [INFO] Quarkus - Integration Tests - Kafka ................ FAILURE [ 37.599 s]

and:

```
Caused by: java.util.NoSuchElementException
	at org.apache.kafka.common.utils.AbstractIterator.next(AbstractIterator.java:52)
	at io.quarkus.it.kafka.KafkaConsumerManager.receive(KafkaConsumerManager.java:40)
	at io.quarkus.it.kafka.KafkaConsumerManager_ClientProxy.receive(KafkaConsumerManager_ClientProxy.zig:51)
```
Anybody has a clue?

2019-11-04 14:01 UTC, mkouba commented on docs/src/main/asciidoc/cdi-reference.adoc
> +NOTE: `@Inject` is still required for constructor and method injection.
Eh, yes I forgot about this special use case.

2019-11-04 14:08 UTC, manovotn commented
> @manovotn would you care to propose changes directly in the PR?

Good point, I never seem to recall I can do that.

2019-11-04 14:19 UTC, manovotn reviewed
Tried adding the code suggestions.

2019-11-04 14:19 UTC, manovotn commented on docs/src/main/asciidoc/cdi-reference.adoc
> +In CDI, if you declare a field injection point you need to use `@Inject` and optionally required qualifiers:
```suggestion
In CDI, if you declare a field injection point you need to use `@Inject` and optionally a set of qualifiers:
```

2019-11-04 14:19 UTC, manovotn commented on docs/src/main/asciidoc/cdi-reference.adoc
> +NOTE: `@Inject` is still required for constructor and method injection.
```suggestion
NOTE: With the notable exception of one special case discussed below, `@Inject` is still required for constructor and method injection.
```

2019-11-04 14:19 UTC, manovotn commented on docs/src/main/asciidoc/cdi-reference.adoc
> +Quarkus adds a capability that CDI currently does not support which is to conditionally declare a bean if no such bean has been declared in the typical ways Quarkus supports.
```suggestion
Quarkus adds a capability that CDI currently does not support which is to conditionally declare a bean if no other bean with equal types and qualifiers was declared by any available means (bean class, producer, synthetic bean, ...)
```

2019-11-04 14:19 UTC, manovotn commented on docs/src/main/asciidoc/cdi-reference.adoc
> +`@DefaultBean` allows extensions (or any other code for that matter) to provide defaults while backing off if beans of that type are supplied in any
@mkouba apparently, I cannot suggest a multi line code change, but i would still delete this sentence as I think it just repeats what is said/implied from text and code above.

2019-11-04 14:31 UTC, gsmet requested changes
I added one small comment. Agreed it should be backported.

2019-11-04 14:31 UTC, gsmet commented on docs/src/main/asciidoc/cdi-reference.adoc
> +The idea is that the extension auto-configures things for user, eliminating a lot of boilerplate - we can just `@Inject` a `Tracer` wherever it is needed.
```suggestion
The idea is that the extension auto-configures things for the user, eliminating a lot of boilerplate - we can just `@Inject` a `Tracer` wherever it is needed.
```
?

2019-11-05 08:15 UTC, manovotn approved these changes

2019-11-06 12:33 UTC, mkouba commented
@gsmet Could we merge this one?

2019-11-14 16:21 UTC, gsmet approved these changes

2019-11-14 16:21 UTC, merged

2019-11-14 16:21 UTC, gsmet commented
@mkouba sorry, it took me some time but it's now in!

2019-11-14 16:22 UTC, gsmet commented
Hum, I've seen it too late but next time, please squash everything, it's easier to backport. Thanks!

2019-11-15 07:58 UTC, mkouba commented
Will do, sorry.