Use separate URLClassPath targets depending on the JDK version #5335
quarkusio/quarkus pull request #5336
Opened 2019-11-08 15:30 UTC by galderz

Thx @bobmcwhirter for pointers 😃

2019-11-08 16:10 UTC, gastaldi submitted a review, later dismissed

2019-11-08 16:12 UTC, gastaldi commented on extensions/vertx-core/runtime/src/main/java/io/quarkus/vertx/core/runtime/graal/JdkSubstitutions.java
> +@TargetClass(className = "jdk.internal.loader.URLClassPath$FileLoader")
This class doesn't exist in JDK8, is that missing a `onlyWith=JDK11OrLater.class`?

2019-11-08 16:56 UTC, gastaldi requested changes
Build Failed:

```
Error: substitution target for io.quarkus.vertx.core.runtime.graal.Target_jdk_internal_loader_URLClassPath$FileLoader is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
com.oracle.svm.core.util.UserError$UserException: substitution target for io.quarkus.vertx.core.runtime.graal.Target_jdk_internal_loader_URLClassPath$FileLoader is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:823)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:252)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:875)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:824)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:524)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
```

See comment above

2019-11-08 16:58 UTC, bobmcwhirter commented
Or use the `classNameProvider` annotation field https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/annotate/TargetClass.java#L103 if the substitution is identical between JDK9 and JDK11, and only the name/package of the class differs.

2019-11-10 11:01 UTC, gwenneg commented
This PR fixes #5335, right?

2019-11-12 11:09 UTC, galderz commented
@gwenneg Indeed it fixes it (or tries to), the commit contains that github issue id :)

@bobmcwhirter's suggestion seems better, I'll update the fix.

2019-11-12 16:46 UTC, galderz commented
Pushed an update. Note that `URLClassPath` still has different classes because `getLookupCache` method only exists in the Java 8 (or earlier) version.

2019-11-12 16:53 UTC, galderz commented
@gastaldi Was waiting for CI to finish first, is that Ok?

2019-11-13 09:41 UTC, galderz commented
CI passed, can we integrate this?

2019-11-13 12:18 UTC, gastaldi commented
@galderz sure, please squash the commits and I'll merge it. Thanks!

2019-11-14 07:19 UTC, galderz commented
Ah yes, squashed

2019-11-14 12:11 UTC, gastaldi approved these changes

2019-11-14 12:12 UTC, merged

2019-11-14 15:40 UTC, gsmet commented
I will not backport that one. There is a whole set of patches we need for GraalVM 19.3 support.