Provide a ModuleBuildItem that points to the module root.
quarkusio/quarkus pull request #5478
Opened 2019-11-14 14:49 UTC by iocanel

This is meant to fulfil #5474

2019-11-15 07:17 UTC, geoand commented
The test failure seems related:

```
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time:  4.912 s
[INFO] [INFO] Finished at: 2019-11-14T16:16:24Z
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (default) on project kubernetes-with-application-properties: Failed to build a runnable JAR: Failed to augment application classes: Build failure: Build failed due to errors
[INFO] [ERROR] 	[error]: Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: java.lang.NullPointerException
[INFO] [ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesProcessor.createProject(KubernetesProcessor.java:222)
[INFO] [ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesProcessor.build(KubernetesProcessor.java:118)
[INFO] [ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] [ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] [ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] [ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] [ERROR] 	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:948)
[INFO] [ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
[INFO] [ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[INFO] [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
[INFO] [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
[INFO] [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
[INFO] [ERROR] 	at java.lang.Thread.run(Thread.java:748)
[INFO] [ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[INFO] [ERROR] -> [Help 1]
[INFO] [ERROR] 
[INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[INFO] [ERROR] 
[INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] run post-build script verify.groovy
[INFO] Running post-build script: /home/vsts/work/1/s/integration-tests/kubernetes/target/it/kubernetes-with-application-properties/verify.groovy
[INFO]           kubernetes-with-application-properties/pom.xml ... FAILED (6.5 s)
[INFO]   The post-build script did not succeed. assert kubernetesYml.exists()
```

2019-11-15 14:18 UTC, dmlloyd commented
This change doesn't seem very clear to me designwise.  Are the existing archive build items somehow insufficient?  Was there an email thread about this?

2019-11-15 14:28 UTC, iocanel commented
> This change doesn't seem very clear to me designwise. Are the existing archive build items somehow insufficient? Was there an email thread about this?

I have asked about it via mailing list a while back, with no satisfying answer. If there is an alternative to get the module root, I'd gladly use it and save myself the trouble if fixing the tests :-D

2019-11-15 17:24 UTC, dmlloyd commented
I don't really understand what the "module root" is.  Do you mean the base project that is being built?  Sometimes what the user considers to be the "base project" could come from a dependency so really the main build module has to be considered to be an equal peer with all of the application archives in most respects.

2019-11-15 17:41 UTC, iocanel commented
> I don't really understand what the "module root" is. Do you mean the base project that is being built? 

By module root, I mean the module directory (the dir that contains the pom.xml for that particular module). If this is still not clear I mean the maven `project.baseDir`.

2019-11-15 17:46 UTC, dmlloyd commented
I see.  I have one more question then: what kinds of tasks are you performing on the build root which is not possible to perform generically across all the input archives?

2019-11-15 17:52 UTC, iocanel commented
I am not sure I understand the question, but I can try.
There have been two cases for me so far.

1. I needed to provide to dekorate the module directory.
2. I wanted to trigger a docker build while also needed to happen from within the module directory.

Does this answer the question?

2019-11-15 18:06 UTC, dmlloyd commented
Ah I see.  This is not what I expected, I was thinking it was something classloader related or something.

Might it not be better to make it configuration based?  This seems similar to `quarkus.application.name` in that the build system would have to propagate it and that its value would depend on the build system.  It would be nice to consolidate these things into one concept somehow.

2019-11-15 18:11 UTC, iocanel commented
Well, the module root is something fixed. It's not something that can change. And for the use cases mentioned above, it wouldn't make sense for the user to override it in some way.

It's not that we are talking for something like the output directory, which a user could possibly need to change.

2019-11-15 18:13 UTC, dmlloyd commented
That is very true.

2019-11-15 18:16 UTC, dmlloyd commented
My only concern with this patch would be misuse.  I can easily imagine an extension author using this path by mistake, and causing user builds to break because the user decided to move their packaging to a different submodule which includes the original one.

2019-11-15 18:22 UTC, iocanel commented
It shouldn't really matter. If the user moves the packaging to another submodule, then the suggested build item would point to that submodule and everyone would be happy. In fact that is one of the reasons I created the build item and didn't go with something like `new File(".")`.

2019-11-15 20:37 UTC, dmlloyd commented
Ah, sure, that makes sense.

2019-11-15 20:37 UTC, dmlloyd approved these changes

2019-11-15 22:43 UTC, geoand commented
Now you can fix the tests @iocanel 😎

2019-11-19 15:46 UTC, ppalaga requested changes
A couple of missing JavaDoc comments suggested inline.

2019-11-19 15:46 UTC, ppalaga commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/builditem/ModuleDirBuildItem.java
> +public final class ModuleDirBuildItem extends SimpleBuildItem {
Please add a class level JavaDoc, something like `A BuildItem holding the base directory of the current module (<code>${basedir}</code> for Maven projects or <code>${projectDir}</code> for Gradle projects).`

2019-11-19 15:46 UTC, ppalaga commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/builditem/ModuleDirBuildItem.java
> +    public Path getPath() {
JavaDoc: `@returns the base directory of the current module (<code>${basedir}</code> for Maven projects or <code>${projectDir}</code> for Gradle projects).`

2019-11-19 15:46 UTC, ppalaga commented on core/creator/src/main/java/io/quarkus/creator/CuratedApplicationCreator.java
> +         * @return this AppCreator instance
This method does not return an AppCreator instance

2019-11-19 15:46 UTC, ppalaga commented on core/creator/src/main/java/io/quarkus/creator/CuratedApplicationCreator.java
> +         * Base directory ofr the current module.
```suggestion
         * Base directory of the current module (<code>${basedir}</code> for Maven projects or <code>${projectDir}</code> for Gradle projects).
```

2019-11-21 06:10 UTC, iocanel commented
@ppalaga: These commits are also included in #5496. In that pull request there have been several discussions with @stuartwdouglas on wether we should add this change or not. At the momemnt I intend to explore alternative routes and close this pull request. 

Before I do close this, you might want to take some time and disucss your use cases, to see if they could also be worked around or if we `have to have` this change.

Thanks

2019-11-21 06:14 UTC, stuartwdouglas commented
The reason why I have concerns about this is that one of our use cases is to be able augment existing jars (e.g. to provide security updates by building an app against an updated version of the Quarkus platform). This build item would break that use case if build steps start relying on it.

2019-11-21 09:36 UTC, ppalaga commented
> These commits are also included in #5496

Thanks for the info, looking there.

> you might want to take some time and disucss your use cases

Yes, in Camel Quarkus we try to support as much as possible from Camel. In this particular case, plain Camel allows to declare XSL template files as either absolute paths or paths relative to the `baseDir`. We are compiling the templates to translets at build time so we have to resolve those relative paths there too. 

The XSL templates can also be declared as classpath resources (and we support that already) so if we are forced to ditch the support for relative files, the users could actually use classpath instead. 

@stuartwdouglas thanks for mentioning the patching use case. This probably means that we should also stop supporting `http://` and other external XSL template URIs. WDYT, @lburgazzoli ?

2019-11-21 09:52 UTC, lburgazzoli commented
> 
> @stuartwdouglas thanks for mentioning the patching use case. This probably means that we should also stop supporting `http://` and other external XSL template URIs. WDYT, @lburgazzoli ?

I've already said that we should  probably support only templates from the classpath but looks like you ignored my comment

2019-11-21 10:14 UTC, ppalaga commented
> I've already said that we should probably support only templates from the classpath but looks like you ignored my comment

Sorry, I was missing a good reason to do that. Now there is one.

So, let's conclude that we (Camel Quarkus) are fine without having a baseDir BuildItem for now. Thanks for the discussion!

2019-11-21 10:14 UTC, iocanel commented
So, it's seems that we can close this pull request then.

2019-11-21 10:14 UTC, closed without merging