Arc - support static producer methods.
quarkusio/quarkus pull request #5516
Opened 2019-11-15 14:15 UTC by manovotn

Fixes #5513

2019-11-15 14:30 UTC, mkouba requested changes
The issue mentions "static producers" which includes static producer fields ;-).

2019-11-15 14:30 UTC, mkouba commented on independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanGenerator.java
> +                if (Modifier.isStatic(producerMethod.flags())) {
For static producers we don't have to allocate the `declaringProviderInstanceHandle` at all. And we need to fix the reflection fallback for private methods too.

2019-11-15 17:40 UTC, manovotn reviewed
@mkouba how about this version?
Sorry for missing the fields initially, I was just coding without thinking :)

2019-11-15 20:43 UTC, manovotn commented
The CI failure looks very much unrelated.

2019-11-18 07:29 UTC, mkouba approved these changes

2019-11-18 10:01 UTC, merged