Specify keycloak version in tests
quarkusio/quarkus pull request #5547
Opened 2019-11-17 22:01 UTC by stuartwdouglas

2019-11-17 23:58 UTC, gsmet requested changes

2019-11-17 23:58 UTC, gsmet commented on integration-tests/oidc-code-flow/pom.xml
> +                                    <name>quay.io/keycloak/keycloak::7.0.1</name>
Double colons here.

2019-11-18 00:32 UTC, gsmet commented on integration-tests/keycloak-authorization/pom.xml
> +                                    <name>quay.io/keycloak/keycloak:7.0.1</name>
Couldn't we use a centralized property for that? It would have to be in the `build-parent` pom.xml.

2019-11-18 02:22 UTC, stuartwdouglas commented
It looks like https://github.com/quarkusio/quarkus/commit/60c4d44982b361907571f7b5b77dd6e47d6537c1 removed the fixed version number for keycloak

2019-11-18 03:43 UTC, merged