doc: document how to use 999-SNAPSHOT of quarkus
quarkusio/quarkus pull request #5736
Opened 2019-11-25 09:57 UTC by aureamunoz

Related to #5687

2019-11-25 09:59 UTC, aureamunoz commented
Hi, here the PR to doc how to be able to generate a project that uses locally built Quarkus. WDYT @geoand @maxandersen @aloubyansky ?

2019-11-25 10:26 UTC, aloubyansky requested changes
Thanks @aureamunoz There is a small misprint. Could you please fix it?
There actually are other relevant arguments.
`-DplatformGroupId` is the groupId of the target platform, the default value is `io.quarkus`, given that all the existing `platforms` are coming from `io.quarkus` this one won't practically be used explicitly. But it's still an option.
`-DplatformVersion` is the version of the platform you want the project to use. If it's not specified, the latest one will be resolved. It can also accept a version range, in which case the latest from the specified range will be used.
By default, the command will target the latest version of `quarkus-universe-bom` (unless specific coordinates have been specified). If you run offline however, it will look for the latest locally available. If `quarkus-universe-bom` (satisfying the default version range which is currently up to 2.0), it will fallback to the bundled platform based on `quarkus-bom` (the version will match the version of the plugin).
If you execute the command with

2019-11-25 10:26 UTC, aloubyansky commented on docs/src/main/asciidoc/maven-tooling.adoc
> +| The artifact id of the of the target platform BOM. It should be `quarkus-bom` in order to use the locally built Quarkus.
Please remove one `of the` in `The artifact id of the of the...`.

2019-11-25 20:51 UTC, aureamunoz commented
@aloubyansky do you want also add this paragraphe to the doc? or it's just for clarification?
_By default, the command will target the latest version of quarkus-universe-bom (unless specific coordinates have been specified). If you run offline however, it will look for the latest locally available. If quarkus-universe-bom (satisfying the default version range which is currently up to 2.0), it will fallback to the bundled platform based on quarkus-bom (the version will match the version of the plugin).
If you execute the command with_

2019-11-25 20:56 UTC, aloubyansky commented
I think it'd be good to mention it. Please correct this phrase
````
...available. If quarkus-universe-bom (satisfying the default version range which is currently up to 2.0),
````
to 
````
...available and if quarkus-universe-bom (satisfying the default version range which is currently up to 2.0) is not available locally,
````
Thank you!

2019-11-26 08:21 UTC, aloubyansky approved these changes

2019-11-26 08:21 UTC, merged