Issue5890/add ssl context customization to mongo db extension
quarkusio/quarkus pull request #5893
Opened 2019-12-01 07:12 UTC by maxday

Hello,

This is a PR to fix this issue : https://github.com/quarkusio/quarkus/issues/5890
Sample usage : 

1 - Create a Class which implements SSLContextConfig, here is a sample 
2 - Reference this class in the new property 

`quarkus.mongodb.ssl-context-class=io.maxday.MyCustomSSLContext`

```
    @RegisterForReflection
    public class MyCustomSSLContext implements SSLContextConfig {

    private final String KEYSTORE_PATH = "./ca-serti.jks";
    private final String KEYSTORE_PASSWORD = "changeit";

    @Override
    public SSLContext getSSLContext() {
        try {
            KeyStore keystore = KeyStore.getInstance(KeyStore.getDefaultType());
            try (InputStream in = new FileInputStream(KEYSTORE_PATH)) {
                keystore.load(in, KEYSTORE_PASSWORD.toCharArray());
            }
            KeyManagerFactory keyManagerFactory =
                    KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
            keyManagerFactory.init(keystore, KEYSTORE_PASSWORD.toCharArray());

            TrustManagerFactory trustManagerFactory =
                    TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
            trustManagerFactory.init(keystore);

            SSLContext sslContext = SSLContext.getInstance("TLS");
            sslContext.init(
                    keyManagerFactory.getKeyManagers(),
                    trustManagerFactory.getTrustManagers(),
                    new SecureRandom());
            return sslContext;
        } catch(Exception e) {
            return null;
        }
    }
```

If everything looks good for you, I'll add tests of course

Thanks

2019-12-01 12:48 UTC, cescoffier requested changes
Is there any way we could cover this with a test?

2019-12-01 13:47 UTC, gsmet commented
Thanks for your contribution. Could you squash the commits into one? We try to avoid broken commits in the tree.

Then, I think we probably need to take a step back and see how we could fix that one globally. Because there's a chance we will need to fix this issue for other extensions.

2019-12-01 15:02 UTC, maxday commented
Sure, I'll add a test + squash into one commit today

2019-12-02 09:49 UTC, loicmathieu commented
@maxday did you try it in native mode?

You cannot have an SSLContext inside the image snapshoted heap when building a native image so I'm not sure you can create an SSLContext inside a recorder ...

When creating the OAuth2 extension, I favor offering a way to sepcify a certificate file instead of a whole SSLContext, this is the more common use case of creating our own SSLContext. Maybe we need to provides this (and maybe at Quarkus core level to avoid doing it for all extensions).
This is the OAuth2 extension implementation (not working in native mode): https://github.com/quarkusio/quarkus/blob/master/extensions/elytron-security-oauth2/runtime/src/main/java/io/quarkus/elytron/security/oauth2/runtime/OAuth2Recorder.java#L67

2019-12-02 10:05 UTC, maxday commented
@loicmathieu yes it works in native mode :) maybe I can push the tests and we'll discuss if we want to restrict and allow specifying just a certificate ?

I wrote "deployments" tests but I also want to push **an integration test with real certificates**. 
Is that OK if a create a new module under the integration-tests (mongo-client-ssl) ? @cescoffier 
I need to change the content of application.properties in the existing mongo-client but adding ssl=true breaks existing tests and I could not find an easy way to "swap" properties file in integration tests (see : https://groups.google.com/forum/#!searchin/quarkus-dev/multiple$20application$20properties%7Csort:date/quarkus-dev/Rsy30WZKv80/0py7_GHjDAAJ)

2019-12-04 16:56 UTC, maxday commented
Hi @gsmet @cescoffier 
I’ve added tests (unit + integration)
Let me know if I need to make additional changes :)

2020-01-06 08:09 UTC, cescoffier requested changes

2020-01-06 08:09 UTC, cescoffier commented on extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/runtime/MongoClientRecorder.java
> +            Class clazz = Class.forName(className);
the Class.forName might be a problem. @stuartwdouglas WDYT? Would that work with your ongoing changes?

2020-01-06 08:09 UTC, cescoffier commented on extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/runtime/MongoClientRecorder.java
> +                SSLContextConfig SSLContextConfig = (SSLContextConfig) clazz.getDeclaredConstructor().newInstance();
This won't work in native if the class is not registered for reflection.

2020-01-06 08:09 UTC, cescoffier commented on integration-tests/mongodb-client-ssl/src/test/java/io/quarkus/it/mongodb/SSLMongoTest.java
> +@DisabledOnOs(OS.LINUX)
It would be great to get that tested on our CI (using linux).
@evanchooly any idea about this?

2020-10-12 09:49 UTC, gsmet commented
This one is outdated. Please open a new PR if you want to revisit this.

2020-10-12 09:49 UTC, closed without merging