Feature/create artemis test module
quarkusio/quarkus pull request #5900
Opened 2019-12-01 17:24 UTC by uaihebert

Fixes #3833
The idea of this pr is:
1) create the test module with ArtemisResourceTest
1) expose it to be used by the developers that use Quarkus
1) replace integration tests that used the test class

2019-12-02 03:51 UTC, aguibert reviewed
Overall looks good, my only comment is on placement of the new module

2019-12-02 03:51 UTC, aguibert commented on extensions/artemis-test/pom.xml
> +    <artifactId>quarkus-artemis-test</artifactId>
we should put this test module under `quarkus/test-framework/` with the other test modules, and set the pom parent to `quarkus-test-framework`

2019-12-02 12:32 UTC, gastaldi requested changes
I agree with @aguibert's comment in https://github.com/quarkusio/quarkus/pull/5900/files#r352410389. The module should be moved under `quarkus-test-framework`

2019-12-02 15:35 UTC, gsmet commented
Agreed and you will need to name it `quarkus-test-artemis` to be consistent with the others.

2019-12-03 22:04 UTC, uaihebert commented
Thank you for the feedback @aguibert @gastaldi @gsmet 

I updated it as requested.

2019-12-03 22:05 UTC, gastaldi commented
That looks good. Can you squash all your commits in a single one? Thank you!

2019-12-03 22:28 UTC, uaihebert commented
@gastaldi sure, no problem.

2019-12-04 00:36 UTC, gastaldi approved these changes

2019-12-04 10:42 UTC, uaihebert commented
hello @gastaldi the build failed on the windows test.

any tip for what should I look in the log? the logs are huge and I could not find the error in there.

2019-12-04 11:40 UTC, gastaldi commented
@uaihebert it doesn't seem related to your changes, let me see if I can trigger the build again

2019-12-04 13:14 UTC, uaihebert commented
hello @gastaldi indeed it was not related.

let me know if you need anything else.

2019-12-04 13:15 UTC, merged

2019-12-04 13:15 UTC, gastaldi commented
@uaihebert Merged. Thank you!

2019-12-04 13:24 UTC, uaihebert commented
thank you too.