Update KC authorization test to return the data only if 'from-body' key exists
quarkusio/quarkus pull request #6053
Opened 2019-12-09 13:39 UTC by sberyozkin

Fixes #6037

2019-12-09 18:35 UTC, pedroigor requested changes
Sorry for this one @sberyozkin. It should be a `||` to also check if the body is null so that we make sure that even if the body is parsed before reaching that method it will be available to the application.

2019-12-10 00:30 UTC, sberyozkin commented
@pedroigor np :-), updated...

2019-12-10 10:05 UTC, pedroigor approved these changes

2019-12-11 16:41 UTC, sberyozkin commented
@gsmet Hi Guillaume can you approve it please for it to be merged ? Pedro has already approved

2019-12-12 12:10 UTC, gsmet approved these changes

2019-12-12 12:10 UTC, merged