Micro versions bump
quarkusio/quarkus pull request #6076
Opened 2019-12-10 15:28 UTC by rsvoboda

Micro versions bump for
 * opentracing-tracerresolver
 * smallrye-metrics
 * smallrye-fault-tolerance
 * postgresql-jdbc
 * test-containers

2019-12-10 16:00 UTC, gsmet requested changes
I think a rebase is needed as some of them were upgraded this morning.

2019-12-10 16:09 UTC, kenfinnigan commented on bom/runtime/pom.xml
> +        <smallrye-fault-tolerance.version>2.1.3</smallrye-fault-tolerance.version>
@Ladicek is probably best placed on this one

2019-12-10 16:11 UTC, rsvoboda commented on test-framework/vault/pom.xml
> +        <test-containers.version>1.12.4</test-containers.version>
It's used here: https://github.com/quarkusio/quarkus/blob/master/test-framework/vault/pom.xml#L34

You mean to remove that dep ?

2019-12-10 16:14 UTC, rsvoboda commented
@gsmet rebased
I rebased in the morning and moved to different stuff and forgot how quick quarkus is :)

2019-12-10 16:18 UTC, gsmet commented on test-framework/vault/pom.xml
> +        <test-containers.version>1.12.4</test-containers.version>
No, I mean it's now in the BOM so I think we can remove this local version.

It was recently included in the BOM.

2019-12-10 17:04 UTC, Ladicek commented on bom/runtime/pom.xml
> +        <smallrye-fault-tolerance.version>2.1.3</smallrye-fault-tolerance.version>
SmallRye FT 2.1.3 aligns with SmallRye Metrics, so I guess yes, but there's also a bunch of other component updates.

2019-12-10 17:21 UTC, rsvoboda commented on test-framework/vault/pom.xml
> +        <test-containers.version>1.12.4</test-containers.version>
I tried to remove that property definition and it failed, I can retry tmr, not at my machine now.

2019-12-10 17:28 UTC, gsmet commented on test-framework/vault/pom.xml
> +        <test-containers.version>1.12.4</test-containers.version>
And removing the version from the dependency too?

2019-12-11 11:33 UTC, jmartisk commented on bom/runtime/pom.xml
> +        <smallrye-fault-tolerance.version>2.1.3</smallrye-fault-tolerance.version>
These upgrades are specifically required for my PR https://github.com/quarkusio/quarkus/pull/5272/ to work and supersede some things from that PR (if the FT upgrade is merged, I can remove a workaround in my PR), so go ahead, it looks like my PR might take a bit longer to get reviewed and merged.

2019-12-11 11:41 UTC, rsvoboda commented on test-framework/vault/pom.xml
> +        <test-containers.version>1.12.4</test-containers.version>
```diff
diff --git a/test-framework/vault/pom.xml b/test-framework/vault/pom.xml
index 7dc8d1492..f9e87cd7d 100644
--- a/test-framework/vault/pom.xml
+++ b/test-framework/vault/pom.xml
@@ -14,9 +14,9 @@
     <artifactId>quarkus-vault-test</artifactId>
     <name>Quarkus - Vault - Test</name>

-    <properties>
-        <test-containers.version>1.12.4</test-containers.version>
-    </properties>
+<!--    <properties>-->
+<!--        <test-containers.version>1.12.4</test-containers.version>-->
+<!--    </properties>-->

     <dependencies>

@@ -31,7 +31,7 @@
         <dependency>
             <groupId>org.testcontainers</groupId>
             <artifactId>postgresql</artifactId>
-            <version>${test-containers.version}</version>
+            <!-- <version>${test-containers.version}</version> -->
             <exclusions>
                 <exclusion>
                     <groupId>javax.xml.bind</groupId>
```

gives 

```
$ mvn clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.testcontainers:postgresql:jar is missing. @ line 31, column 21
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project io.quarkus:quarkus-vault-test:999-SNAPSHOT (/Users/rsvoboda/git/quarkus/test-framework/vault/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.testcontainers:postgresql:jar is missing. @ line 31, column 21
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

2019-12-11 11:45 UTC, rsvoboda commented on test-framework/vault/pom.xml
> +        <test-containers.version>1.12.4</test-containers.version>
BOM defines dependency `org.testcontainers:testcontainers`, but that module uses `org.testcontainers:postgresql`
Trying `org.testcontainers:testcontainers` in test-framework/vault/pom.xml

2019-12-11 11:49 UTC, rsvoboda commented on test-framework/vault/pom.xml
> +        <test-containers.version>1.12.4</test-containers.version>
PostgreSQLContainer / POSTGRESQL_PORT are used in vault, so org.testcontainers:postgresql is really needed

2019-12-11 11:49 UTC, gsmet commented on test-framework/vault/pom.xml
> +        <test-containers.version>1.12.4</test-containers.version>
Just add it to the BOM with the other then. Better that than having 2 versions wandering around.

2019-12-11 12:40 UTC, rsvoboda commented on test-framework/vault/pom.xml
> +        <test-containers.version>1.12.4</test-containers.version>
PR updated

2019-12-12 12:17 UTC, gsmet approved these changes

2019-12-12 12:17 UTC, merged

2019-12-12 12:17 UTC, gsmet commented
Thanks!