WIP Added Documentation for YAML configuration
quarkusio/quarkus pull request #6116
Opened 2019-12-11 17:21 UTC by alexzimmer96

This PR adds a section of how to use YAML instead of a application.properties like mentioned in #6106.

I marked this as WIP because i cannot test with the new version at the moment. If someone can confirm i got this right, feel free to comment  and/or merge.

2019-12-11 17:28 UTC, gsmet requested changes
Thanks! I added a few suggestions.

2019-12-11 17:28 UTC, gsmet commented on docs/src/main/asciidoc/config.adoc
> +=== Add YAML-Config Support
```suggestion
=== Add YAML Config Support
```

2019-12-11 17:28 UTC, gsmet commented on docs/src/main/asciidoc/config.adoc
> +Sometimes you want to use YAML over properties for configuration.
```suggestion
You might want to use YAML over properties for configuration.
```

2019-12-11 17:28 UTC, gsmet commented on docs/src/main/asciidoc/config.adoc
> +Since link:https://github.com/smallrye/smallrye-config[smallrye-config] brings support for YAML
```suggestion
Since link:https://github.com/smallrye/smallrye-config[SmallRye Config] brings support for YAML
```

2019-12-11 17:28 UTC, gsmet commented on docs/src/main/asciidoc/config.adoc
> +First you will need to add the YAML-Extension to your POM-File.
```suggestion
First you will need to add the YAML extension to your POM-File:
```

2019-12-11 17:28 UTC, gsmet commented on docs/src/main/asciidoc/config.adoc
> +Now Quarkus can read YAML-Files.
```suggestion
Now Quarkus can read YAML configuration files.
```

2019-12-11 17:28 UTC, gsmet commented on docs/src/main/asciidoc/config.adoc
> +NOTE: Quarkus will choose a `application.properties` over a `application.yaml`.
```suggestion
NOTE: Quarkus will choose an `application.properties` over an `application.yaml`.
```

2019-12-11 17:28 UTC, gsmet commented on docs/src/main/asciidoc/config.adoc
> +YAML-Files are just an alternative way to configure your application.
```suggestion
YAML files are just an alternative way to configure your application.
```

2019-12-11 17:28 UTC, gsmet commented on docs/src/main/asciidoc/config.adoc
> +===== Configuration Example
```suggestion
==== Configuration Example
```

2019-12-11 17:28 UTC, gsmet commented on docs/src/main/asciidoc/config.adoc
> +    - John
Maybe it would be better to add the datasource settings that was in the original issue?

2019-12-11 17:28 UTC, gsmet commented on docs/src/main/asciidoc/config.adoc
> +Just add the `%profile` wrapped in quotation marks before defining the key-value paires.
```suggestion
Just add the `%profile` wrapped in quotation marks before defining the key-value pairs:
```

2019-12-11 18:34 UTC, alexzimmer96 commented
@gsmet Thanks for the improvements. I've added also added the original example, like you suggested.

2019-12-12 06:37 UTC, alexzimmer96 commented
Okay, i can say that this is working now. Tested it on a newly created project.

2019-12-12 11:51 UTC, gsmet approved these changes

2019-12-12 11:51 UTC, merged

2019-12-12 11:52 UTC, gsmet commented
@alexzimmer96 thanks for taking the time to contribute this!