Exclude integration-tests module if skipITs is set
quarkusio/quarkus pull request #6315
Opened 2019-12-23 01:58 UTC by gastaldi

2019-12-23 07:44 UTC, oscerd approved these changes

2019-12-23 09:13 UTC, gsmet requested changes
I'm not convinced by this one: even if you don't run the ITs, it's good to know everything compiles.

I'm pretty sure it happened to me a few times that the ITs didn't compile anymore and I had to fix them.

Let's wait for some more opinions. @geoand WDYT?

2019-12-23 09:17 UTC, geoand commented
I am very much on the fence about this one, but I'm probably 60 - 40 in favor of what @gsmet says. I would personally leave it as it is

2019-12-23 09:27 UTC, gastaldi commented
>even if you don't run the ITs, it's good to know everything compiles

In this case you don't specify `-DskipITs`. If you still want to compile the ITs but don't want to run them you just specify `-DskipTests`

2019-12-23 09:58 UTC, gsmet commented
AFAIK, `-DskipTests` still runs the ITs. At least that was the case at the beginning of the project.

To skip running the ITs, you needed `-DskipITs`.

In any case, it's very different not running something and potentially have compilation errors.

I'm really not about having a common setup allowing for compilation errors. That will require unnecessary CI runs and we certainly don't want that. I think you will waste less time just running the compilation of everything.

2019-12-23 10:01 UTC, geoand commented
One more thing to consider perhaps: Do IDEs properly recognize the `!....` syntax, or would this make it harder to get good IDE warnings for the integration tests?
I am pretty sure IntelliJ works as expected, but I have no idea about the rest

2020-01-02 12:30 UTC, gsmet commented
I decided to not merge that one.

If we had unlimited CI resources, we could consider it but resources are scarce right now. We can reconsider if one day we get sufficient CI resources so don't drop the branch and keep it around :).

2020-01-02 12:30 UTC, closed without merging

2020-01-02 12:47 UTC, gastaldi commented
>If we had unlimited CI resources, we could consider it but resources are
scarce right now

Not sure how that relates to this PR but that's fine ;)

2020-01-02 13:05 UTC, gsmet commented
I explained it here:

> I'm really not about having a common setup allowing for compilation errors. That will require unnecessary CI runs and we certainly don't want that. I think you will waste less time just running the compilation of everything.

Basically, if you have a compilation issue in the IT, you will have a CI run for ~40 mn until it gets to the compilation error.

I think it's better to waste ~1mn on your box in the current situation.