Add JSON-B and Jackson serialization to the Kafka guide
quarkusio/quarkus pull request #6387
Opened 2020-01-03 09:15 UTC by loicmathieu

2020-01-03 09:58 UTC, gsmet requested changes
Thanks, I added some suggestions.

2020-01-03 09:58 UTC, gsmet commented on docs/src/main/asciidoc/kafka.adoc
> +Quarkus has built-in capabilities to deals with JSON Kafka messages.
```suggestion
Quarkus has built-in capabilities to deal with JSON Kafka messages.
```

2020-01-03 09:58 UTC, gsmet commented on docs/src/main/asciidoc/kafka.adoc
> +Imagine we have a `Fruit` pojo as following:
```suggestion
Imagine we have a `Fruit` pojo as follows:
```

2020-01-03 09:58 UTC, gsmet commented on docs/src/main/asciidoc/kafka.adoc
> +First, you need to include the `quarkus-jsonb` dependency (if you already use the `quarkus-resteasy-jsonb` dependency this is not needed).
```suggestion
First, you need to include the `quarkus-jsonb` extension (if you already use the `quarkus-resteasy-jsonb` extension, this is not needed).
```

2020-01-03 09:58 UTC, gsmet commented on docs/src/main/asciidoc/kafka.adoc
> +Now, your Kafka messages will contains a JSON-B serialized representation of your Fruit pojo !
```suggestion
Now, your Kafka messages will contain a JSON-B serialized representation of your Fruit pojo.
```

2020-01-03 09:58 UTC, gsmet commented on docs/src/main/asciidoc/kafka.adoc
> +First, you need to include the `quarkus-jackson` dependency (if you already use the `quarkus-jackson-jsonb` dependency this is not needed).
```suggestion
First, you need to include the `quarkus-jackson` extension (if you already use the `quarkus-jackson-jsonb` extension, this is not needed).
```

2020-01-03 09:58 UTC, gsmet commented on docs/src/main/asciidoc/kafka.adoc
> +
Let's get rid of the blank lines.

2020-01-03 09:58 UTC, gsmet commented on docs/src/main/asciidoc/kafka.adoc
> +Now, your Kafka messages will contains a Jackson serialized representation of your Fruit pojo !
```suggestion
Now, your Kafka messages will contain a Jackson serialized representation of your Fruit pojo.
```

2020-01-03 11:07 UTC, gsmet commented
BTW, I think mentioning `@SseElementType(MediaType.APPLICATION_JSON)` here might be worth it.

2020-01-03 11:07 UTC, loicmathieu commented on docs/src/main/asciidoc/kafka.adoc
> +
done

2020-01-03 11:20 UTC, loicmathieu commented
@gsmet I applied your suggestion and add a section about SSE

2020-01-03 12:41 UTC, gsmet requested changes
I added a very small suggestion.

Could you adjust and then I think we're good to go.

Thanks!

2020-01-03 12:41 UTC, gsmet commented on docs/src/main/asciidoc/kafka.adoc
> +If you want Resteasy to send JSON Server-Sent Events, you need to use the `@SseElementType` annotation to define the content type of the events,
```suggestion
If you want RESTEasy to send JSON Server-Sent Events, you need to use the `@SseElementType` annotation to define the content type of the events,
```

2020-01-03 12:56 UTC, loicmathieu commented
@gsmet I applied your last suggestion.

2020-01-03 13:02 UTC, gsmet approved these changes

2020-01-03 13:02 UTC, merged

2020-01-03 13:02 UTC, gsmet commented
Merged, thanks!

2020-01-06 07:05 UTC, cescoffier reviewed
Late on this, but thanks!