Introduce Elytron Security Filesystem
quarkusio/quarkus pull request #6496
Opened 2020-01-10 15:01 UTC by gastaldi

Fixes #624

2020-01-10 15:06 UTC, gastaldi commented
Filesystem documentation for posterity: https://github.com/wildfly/wildfly/blob/master/docs/src/main/asciidoc/_elytron/components/Filesystem_Security_Realm.adoc

2020-01-11 09:52 UTC, dmlloyd commented on extensions/elytron-security-filesystem/deployment/src/test/java/io/quarkus/security/test/BasicAuthTestCase.java
> +                    .addAsResource(new StringAsset("quarkus.security.filesystem.path=" + tempDir),
It looks like the path name will need to be escaped here.

2020-01-13 10:08 UTC, gsmet requested changes
I'm pretty sure it will require some doc updates? IIRC there's a list of Elytron extensions somewhere in the doc.

2020-01-13 17:40 UTC, sberyozkin commented
Hi @gastaldi @geoand sorry for a delay, back from a trip home.

@gastaldi IMHO this is also very neatly done similarly to the proposed LDAP extension.
But in this case I have a small doubt.
We already have `elytron-security-properties-file` with the configuration like [this one](https://github.com/quarkusio/quarkus/blob/master/integration-tests/elytron-security/src/main/resources/META-INF/microprofile-config.properties).
This PR supports what looks like the same type of configuration but in the external XML file, is it correct ?

2020-01-13 17:41 UTC, gastaldi commented
> This PR supports what looks like the same type of configuration but in the external XML file, is it correct ?

Yes, that's correct

2020-01-13 18:05 UTC, sberyozkin commented
@gastaldi OK thanks. I suppose it fits with the current strategy for all the elytron extensions. My minor concern was, that the properties file is also on the filesystem and XML file sets the properties too :-) so it is not obvious what the difference is between `elytron-security-properties-file` and `elytron-security-filesystem`.
I don't really mind, but perhaps an alternative name for this extension could be considered ?

2020-01-13 18:11 UTC, gastaldi commented
> I don't really mind, but perhaps an alternative name for this extension could be considered ?

I'm not opposed to it, but do you have anything in mind? I'm not really good at naming things :)

2020-01-13 18:29 UTC, sberyozkin commented
@gastaldi may be `quarkus-security-filesystem-identity` (because the root XML element is `identity`) ? Or may be `quarkus-security-identity-xml`
Not sure it could confuse the elytron users who already know about `filesystem`. Let me ask Stuart @stuartwdouglas opinion as well. Guillaume @gsmet always have some name ideas too :-)
If you decide not to rename then I won't mind, thanks

2020-01-13 18:30 UTC, sberyozkin approved these changes

2020-01-14 10:04 UTC, sberyozkin commented
@gastaldi Hi, if it is not `WIP` any longer then please remove it

2020-01-14 10:12 UTC, gastaldi commented
@sberyozkin I am working in the documentation for this extension (guide).
I'll remove the WIP once I push my changes

Em Ter, 14 de jan de 2020 07:04, sberyozkin <notifications@github.com>
escreveu:

> @gastaldi <https://github.com/gastaldi> Hi, if it is not WIP any longer
> then please remove it
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/quarkusio/quarkus/pull/6496?email_source=notifications&email_token=AAANG5I76KFJYY464UEK7CTQ5WE3HA5CNFSM4KFJATV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEI4AU5Q#issuecomment-574098038>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAANG5J5H4JRIJCM7TDWULTQ5WE3HANCNFSM4KFJATVQ>
> .
>

2020-01-14 10:21 UTC, sberyozkin commented
@gastaldi OK, thanks, I thought it was ready for a merge

2020-04-06 17:40 UTC, sberyozkin commented
@gastaldi Hi George, is it ready to go ? Can you please resolve the conflicts ?

2020-04-06 18:29 UTC, gastaldi commented
@sberyozkin hey! I rebased the conflicts. The only thing missing is a guide/documentation for this extension.  I haven't been able to write that down yet, would you like to take a stab and add it to my PR?

2020-10-09 16:23 UTC, gastaldi commented
Closing this for now

2020-10-09 16:23 UTC, closed without merging