Properly show configuration errors in the output
quarkusio/quarkus pull request #6505
Opened 2020-01-11 08:32 UTC by geoand

Fixes: #6466

With this change, the output of  `myapp -Dquarkus.profile= -Dquarkus.http.port=foo` is:

```
Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:194)
        at io.quarkus.runtime.Application.start(Application.java:87)
        at io.quarkus.runtime.Application.run(Application.java:210)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: io.quarkus.runtime.configuration.ConfigurationException: One or more configuration errors has prevented the application from starting. The errors are:
Configuration key "quarkus.profile" is required, but its value is empty/missing: Property quarkus.profile not found
An invalid value was given for configuration key "quarkus.http.port": For input string: "foo"
```

2020-01-11 09:44 UTC, dmlloyd requested changes
One minor fix.  Otherwise looks good!

2020-01-11 09:44 UTC, dmlloyd commented on core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigDiagnostic.java
> +    private static List<String> errorsMessages = new CopyOnWriteArrayList<>();
This should be final.

2020-01-11 09:44 UTC, dmlloyd commented on core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigDiagnostic.java
> +    private static List<String> errorsMessages = new CopyOnWriteArrayList<>();
```suggestion
    private static final List<String> errorsMessages = new CopyOnWriteArrayList<>();
```

2020-01-11 09:45 UTC, dmlloyd commented on core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigDiagnostic.java
> +    private static List<String> errorsMessages = new CopyOnWriteArrayList<>();
Trying out "suggested change" :)

2020-01-11 09:46 UTC, geoand commented on core/runtime/src/main/java/io/quarkus/runtime/configuration/ConfigDiagnostic.java
> +    private static List<String> errorsMessages = new CopyOnWriteArrayList<>();
It worked :)

2020-01-11 09:48 UTC, dmlloyd approved these changes

2020-01-11 11:31 UTC, merged

2020-01-11 18:35 UTC, gsmet commented
@geoand is it normal that the logger doesn't look like our standard logger?

2020-01-11 18:38 UTC, geoand commented
Yeah, I followed @dmlloyd's suggestion in the issue to create a good error message and remove the (useless) stacktrace

2020-01-11 18:48 UTC, gsmet commented
I was talking about our logging prefix? It looks like it's gone here.

2020-01-11 18:50 UTC, geoand commented
I am guessing that logging isn't entirely set up at that point.
But the application fails to starts, so perhaps it's not that important?

2020-01-12 00:36 UTC, dmlloyd commented
Yeah this isn't logging, it's putting the raw exception text into the final exception.  Logging is completely separate.