Make tests more stable by using LinkedHashSet for deterministic iterations
quarkusio/quarkus pull request #6839
Opened 2020-01-28 21:59 UTC by testfixer

The tests `io.quarkus.dev.CompilerFlagsTest#redundancyReduction` and `io.quarkus.dev.CompilerFlagsTest#defaulting` compare a `HashSet `with a `List`,  but `HashSet` does not guarantee any specific order of entries. Thus, tests can fail due to a different iteration order.
This PR uses a `LinkedHashSet` to guarantee the iteration order.

2020-01-29 09:28 UTC, gsmet requested changes
Makes sense but there is a compilation error:
```
[ERROR] /home/vsts/work/1/s/core/devmode/src/main/java/io/quarkus/dev/CompilerFlags.java:[30,80] cannot find symbol
  symbol:   class HashSet
  location: class io.quarkus.dev.CompilerFlags
```

2020-01-30 06:37 UTC, geoand approved these changes
Thanks for the contribution!

2020-01-30 09:48 UTC, gsmet approved these changes

2020-01-30 09:49 UTC, merged

2020-01-30 09:49 UTC, gsmet commented
Merged, thanks!