Enable the use of GCP Stackdriver
quarkusio/quarkus pull request #6984
Opened 2020-02-04 08:05 UTC by jtama-op

Todos:

- [ ] Documentation
- [ ] Testing with InMemoryExporter

2020-02-04 12:17 UTC, gsmet requested changes
Thanks. I added a bunch of comments.

What's really missing is the big picture and what you are trying to achieve with all that. I have no idea what I reviewed :).

2020-02-04 12:17 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-google-cloud.adoc
> +The first two don't need anymore details, simply connect to you database following the link:datasource.adoc[datasource guide].
```suggestion
The first two don't need anymore details, simply connect to your database following the link:datasource[datasource guide].
```

2020-02-04 12:17 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-google-cloud.adoc
> +* Connecting to a CloudSQL postgresql instance with quarkus-agroal and service account using CloudRun
```suggestion
* Connecting to a CloudSQL PostgreSQL instance with quarkus-agroal and service account using CloudRun
```
Maybe let's not use bullets for only one item?

2020-02-04 12:17 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-google-cloud.adoc
> +This guide will take as input an application developed in the link:datasource.adoc[datasource guide].
```suggestion
This guide will take as input an application developed in the link:datasource[datasource guide].
```

2020-02-04 12:17 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-google-cloud.adoc
> +The third allows you to connect as if locally, but is not available for AppEngine or CloudRun where you only deploy one artefact.
```suggestion
The third allows you to connect as if locally, but is not available for AppEngine or CloudRun where you only deploy one artifact.
```

2020-02-04 12:17 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-google-cloud.adoc
> +This guide will help you through the fourth possibility : connecting using service account.
```suggestion
This guide will help you through the fourth possibility : connecting using a service account.
```

2020-02-04 12:17 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-google-cloud.adoc
> +You will need to add the _Cloud SQL Postgres Socket Factory_ and postgresql driver dependencies.
```suggestion
You will need to add the _Cloud SQL Postgres Socket Factory_ and PostgreSQL driver dependencies.
```

2020-02-04 12:17 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-google-cloud.adoc
> +<!-- https://mvnrepository.com/artifact/org.postgresql/postgresql -->
Could we point to the more standard https://search.maven.org/ (or remove the links altogether)?

2020-02-04 12:17 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-google-cloud.adoc
> +// https://mvnrepository.com/artifact/org.postgresql/postgresql
Same here.

2020-02-04 12:17 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-google-cloud.adoc
> +If you haven't already please follow the link::https://cloud.google.com/sql/docs/postgres/create-instance[Creating instances guide].
```suggestion
If you haven't already, please follow the https://cloud.google.com/sql/docs/postgres/create-instance[Creating instances guide].
```

2020-02-04 12:17 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-google-cloud.adoc
> +Prefere the use of environment variables that will allow you to connect to all your env depending on your runtime values
```suggestion
Prefere the use of environment variables that will allow you to connect to all your environment depending on your runtime values.
```

2020-02-04 12:17 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-google-cloud.adoc
> +NOTE: `$PORT` value will be injected automatically by CloudRun and is to be used for HealthCheck
```suggestion
NOTE: `$PORT` value will be injected automatically by CloudRun and is to be used for HealthCheck.
```

2020-02-04 12:17 UTC, gsmet commented on docs/src/main/asciidoc/deploying-to-google-cloud.adoc
> +quarkus.datasource.password = ${DB_PASSWORD}
It looks like you don't use the configuration properties you introduced in the extension? It is expected?

2020-02-04 12:17 UTC, gsmet commented on extensions/agroal/deployment/src/test/java/io/quarkus/agroal/test/GcpDataSourceConfigTest.java
> +    //end::injection[]
I don't think you need the tag here.

2020-02-04 12:17 UTC, gsmet commented on extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSourceRuntimeConfig.java
> +    public Optional<String> cloudSqlInstance;
I'm not entirely sure we will want to include those very specific properties in a generic extension. We need to discuss this.

2020-02-04 12:17 UTC, gsmet commented on extensions/arc/runtime/pom.xml
>  </project>
Please don't reformat files.

2020-02-04 12:17 UTC, gsmet commented on extensions/arc/runtime/src/main/resources/META-INF/quarkus-extension.yaml
>    unlisted: true
Same here.

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/deployment/pom.xml
> +    <name>Opencensus - Stackdriver configurer - Deployment</name>
Please follow the conventions for the name of the extension.

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/deployment/pom.xml
> +            <version>${project.version}</version>
The version should be in the BOM and not here.

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/deployment/pom.xml
> +                            <version>1.1.0.Final</version>
This needs to be a variable.

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/pom.xml
> +    <name>Opencensus - Stackdriver configurer - Parent</name>
Same here about the conventions.

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/runtime/pom.xml
> +    <name>Opencensus - Stackdriver configurer - Runtime</name>
Conventions.

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/runtime/pom.xml
> +        <opencensus.version>0.24.0</opencensus.version>
This should be in the BOM.

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/runtime/pom.xml
> +            <version>0.33.0</version>
Same here.

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/runtime/pom.xml
> +        <!-- On démerde le caca de google -->
Hum, I don't think we want that sort of comments.

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/runtime/pom.xml
> +            <version>0.16.2</version>
All the versions should be in the BOM

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/runtime/pom.xml
> +                            <version>1.1.0.Final</version>
Same here about the version.

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/runtime/src/main/java/io/quarkus/stackdriver/filter/SpanWrapper.java
> + * @author Pavol Loffay
We don't do `@author` tags.

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/runtime/src/main/java/io/quarkus/stackdriver/runtime/StackdriverProducer.java
> +import org.slf4j.LoggerFactory;
This should be JBoss Logging.

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/runtime/src/main/java/io/quarkus/stackdriver/runtime/configuration/StackdriverConfiguration.java
> +    @ConfigItem(name = "project-id", defaultValue = "!")
You don't need a name here.

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/runtime/src/main/java/io/quarkus/stackdriver/runtime/configuration/StackdriverConfiguration.java
> +     * The GCP project ID
Documentation is incorrect.

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/runtime/src/main/java/io/quarkus/stackdriver/runtime/configuration/StackdriverConfiguration.java
> +    @ConfigItem(name = "credentials")
No need for the name attribute here.

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/runtime/src/main/resources/META-INF/quarkus-gcp-stackdriver.yml
> +  status: "draft"
it should be experimental.

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/runtime/src/main/resources/META-INF/quarkus-gcp-stackdriver.yml
> +  guide: "https://quarkus.io/guides/stackdrvier"
Typo in `stackdrvier`

2020-02-04 12:17 UTC, gsmet commented on extensions/stackdriver/runtime/src/main/resources/META-INF/quarkus-gcp-stackdriver.yml
> +name: "GCP - Stackdriver extension"
```suggestion
name: "GCP - Stackdriver"
```

2020-02-05 08:15 UTC, jtama-op commented
> Thanks. I added a bunch of comments.
> 
> What's really missing is the big picture and what you are trying to achieve with all that. I have no idea what I reviewed :).

@gsmet: Yes I agree, I need to add a proper documentation.
The extension is mimicking the opencensus extension to automate the use of opentrace with stackdriver exporter.

That said Opentrace and Opensencus are beeing merged into OpenTelemetry, and I am thinking to bump all dependencies.

In the meantime, quarkus is clearly missing extension to work with GCP which is sad considaring the cloud native nature of quarkus.

2020-10-12 09:56 UTC, gsmet commented
Closing as out of date. Open a new PR if you still need that.

2020-10-12 09:56 UTC, closed without merging