guide updates for knative quick start update
quarkusio/quarkus pull request #7100
Opened 2020-02-09 13:44 UTC by kameshsampath

The guide has been updated for the https://github.com/quarkusio/quarkus-quickstarts/issues/112

2020-02-12 20:55 UTC, gsmet requested changes
Thanks. I added a bunch of comments, can you have a look?

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +* having access to a Kubernetes cluster. Minikube are valid options.
```suggestion
* having access to a Kubernetes cluster. Minikube is a valid option.
```

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +* The deployment of the application to Knative
Maybe let's remove the bullet list if you have only one item (and add a dot at the end of the sentence)?

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +== Setup Kubernetes Cluster
```suggestion
== Set up Kubernetes Cluster
```

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +<1> Make the current docker context to be that of minikube
```suggestion
<1> Make the current Docker context to be that of minikube
```

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +== Setup Nexus(Optional)
```suggestion
== Set up Nexus (Optional)
```

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +Nexus is used for caching maven artifacts so that Apache Maven builds are faster.
```suggestion
Nexus is used for caching Maven artifacts so that Apache Maven builds are faster.
```

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +Wait for some time to have nexus initialize and run. You can watch the status via `kubectl get pods -w`, use kbd:[Ctrl+c] to terminate the watch
```suggestion
Wait for some time to have Nexus initialized and run. You can watch the status via `kubectl get pods -w`, use kbd:[Ctrl+c] to terminate the watch.
```

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +As vanilla Kubernetes does not have a easy and developer friendly way to build and deploy application to local cluster, without the need to push the image to external container registry. We will be u
```suggestion
As vanilla Kubernetes does not have an easy and developer friendly way to build and deploy applications to a local cluster without the need to push the image to an external container registry, we will be using Skaffold to help us build and deploy the Quarkus application onto Kubernetes.
```

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +The container image will not be pushed to remote container registry, and hence the container image url has to be `dev.local`, to make Knative deploy it without trying to pull it from external contain
```suggestion
The container image will not be pushed to a remote container registry, and hence the container image url has to be `dev.local`, to make Knative deploy it without trying to pull it from an external container registry.
```

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +To run Knative Quarkus application, we need to use the multi stage docker build; to build the quarkus application container image and use it in Kubernetes application deployment.
```suggestion
To run Knative Quarkus applications, we need to use the multi-stage Docker build to build the Quarkus application container image and use it in the Kubernetes application deployment.
```

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +The following commands starts a one time deployment of Quarkus application and runs starts the Knative service after successful container image build.
```suggestion
The following commands start a one time deployment of the Quarkus application and starts the Knative service after successfully building the container image.
```

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +If you want to deploy Quarkus JVM image then run the following command before running skaffold:
```suggestion
If you want to deploy a Quarkus JVM-based application then run the following command before running Skaffold:
```

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +If you want to deploy Quarkus Native image then run the following command before running skaffold:
```suggestion
If you want to deploy a Quarkus native executable (using GraalVM) then run the following command before running Skaffold:
```

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +It is very important to note that the Dockerfile in src/main/docker folder has been modified to support
```suggestion
It is very important to note that the Dockerfile in the `src/main/docker` folder has been modified to support 
```

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +It is very important to note that the Dockerfile in src/main/docker folder has been modified to support
to support what?

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +As it will take few minutes for the build and deploy to be completed you can watch the status using:
```suggestion
As it will take a few minutes for the build and deployment to complete, you can watch the status using:
```

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +NOTE: The deployment name could differ in your environment
```suggestion
NOTE: The deployment name could differ in your environment.
```

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +A successful Knative Service deployment will show the following pods in the current namespace:
```suggestion
A successful Knative service deployment will show the following pods in the current namespace:
```

2020-02-12 20:55 UTC, gsmet commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +Once the Knative service is successfully running, you can call the service it using the script `./bin/call.sh`, which should return a response like `hello`. Allowing it to idle for approximately 60-6
```suggestion
Once the Knative service is successfully running, you can call the service using the script `./bin/call.sh`, which should return a response like `hello`. Allowing it to idle for approximately 60-65 seconds - that is without any further requests -, you will see it automatically scales down to zero pods.
```

2020-02-13 03:10 UTC, kameshsampath commented
@gsmet thank you for quick review, I have updated your comments and pushed it back .  It will be great of you can check and merge the related code https://github.com/quarkusio/quarkus-quickstarts/issues/112

2020-02-17 14:29 UTC, gsmet commented
@kameshsampath I think you missed the hidden ones (there are 9 of them hidden by GH). At least they are not marked as outdated.

2020-02-18 06:39 UTC, kameshsampath commented
@gsmet 

> @kameshsampath I think you missed the hidden ones (there are 9 of them hidden by GH). At least they are not marked as outdated.

Not sure how I missed them , sorry about. They are all addressed in the latest commit.

2020-02-21 11:49 UTC, gsmet approved these changes

2020-02-21 11:49 UTC, merged

2020-02-21 11:49 UTC, gsmet commented
Squashed and merged, thanks!

2020-02-22 09:41 UTC, lordofthejars commented on docs/src/main/asciidoc/getting-started-knative.adoc
> +== Why Skaffold ?
Why Skaffold? Shouldn't we offer an integral solution? Now that we have Jib support maybe the guide should be updated to use Jib? At least let's offer a single way of doing things to not confuse the users.