updated gradle to 6.2
quarkusio/quarkus pull request #7252
Opened 2020-02-18 10:09 UTC by SR-Lut3t1um

2020-02-18 10:18 UTC, gastaldi commented
Weird, Gradle 6.2 reports #7249 as `BUILD SUCCESSFUL` after the failure, need to investigate why

2020-02-18 10:24 UTC, gastaldi commented
Hm, same with 6.0.1, seems to be unrelated

2020-02-18 10:26 UTC, SR-Lut3t1um commented
Yes I'm pretty sure it is. Just wanted to make sure and does no harm either.

2020-02-18 10:27 UTC, gastaldi commented
You also need to update https://github.com/quarkusio/quarkus/blob/49ea44edc9e591ce6681013835f9d230b1646958/independent-projects/tools/pom.xml#L30 if you want Gradle 6.2 to be used in new projects

2020-02-18 10:29 UTC, gastaldi commented
BTW the following files may also be modified:

```
	modified:   gradle/wrapper/gradle-wrapper.jar
	modified:   gradle/wrapper/gradle-wrapper.properties
	modified:   gradlew
	modified:   gradlew.bat
```

2020-02-18 10:31 UTC, gastaldi commented
code.quarkus.io does not use `gradle wrapper` and has the wrapper sources here: https://github.com/quarkusio/code.quarkus.io/tree/master/src/main/resources/creator/gradlew

2020-02-18 10:32 UTC, SR-Lut3t1um commented
ah ok makes sense. Gonne fix now

2020-02-18 10:35 UTC, gastaldi commented
Are you sure the files in https://github.com/quarkusio/quarkus/tree/3c4885f943622b28283ee4a44be80e677dc2f84b/devtools/gradle/gradle/wrapper + the gradlew scripts don't change? 

Also can you squash your commits in a single commit for this PR?

2020-02-18 10:37 UTC, SR-Lut3t1um commented
1. I'm also going to make a PR there to bump the gradle version.
2. Sure

2020-02-18 10:45 UTC, SR-Lut3t1um commented
I did 1.

2020-02-18 11:29 UTC, gastaldi commented
There is also https://github.com/quarkusio/quarkus/blob/13c28058423690b17bcac384c9433a27f50aac52/build-parent/pom.xml#L58 which needs to be updated

2020-02-18 13:29 UTC, SR-Lut3t1um commented
So I changed the last file that needed change and also crated the final pull request.

https://github.com/quarkusio/code.quarkus.io/pull/298

2020-02-18 15:48 UTC, SR-Lut3t1um commented
I guess the pipeline crashed...

2020-02-18 18:44 UTC, SR-Lut3t1um commented
Can this PR be accepted?

2020-02-18 18:50 UTC, gastaldi submitted a review, later dismissed

2020-02-18 21:42 UTC, aloubyansky requested changes
Please revert everything except for the gradle version upgrade. Thanks!

2020-02-18 21:42 UTC, aloubyansky commented on devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java
> +                if (dependency == null) {
Revert this change, please.

2020-02-18 21:42 UTC, aloubyansky commented on devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusDev.java
> +                appDependency.getArtifact().getKey();
Revert this change please.

2020-02-18 21:42 UTC, aloubyansky commented on independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/unused/RemoveUnusedBeansTest.java
> +        Long unusedLong = 0L;
Revert this change please.

2020-02-18 21:42 UTC, aloubyansky commented on independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java
> +                    .getDeclaredConstructor().newInstance();
Revert this change, please.

2020-02-18 21:42 UTC, aloubyansky commented on independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/app/CuratedApplication.java
> +            BiConsumer<CuratedApplication, Map<String, Object>> biConsumer = clazz.getDeclaredConstructor().newInstance();
Revert this change, please.

2020-02-18 21:42 UTC, aloubyansky commented on independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/BootstrapWagonProvider.java
> +            wagon = cls.getDeclaredConstructor().newInstance();
Revert this change, please.

2020-02-18 21:42 UTC, aloubyansky commented on independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/BootstrapWagonProvider.java
> +        return (Wagon) wagon;
Revert this change, please.

2020-02-19 06:55 UTC, SR-Lut3t1um commented
I did.

2020-02-19 07:17 UTC, aloubyansky approved these changes
Thanks!

2020-02-19 07:19 UTC, aloubyansky commented
BTW, if you do open a PR with those kind of changes, please, let me know. Thanks.

2020-02-19 20:32 UTC, gsmet commented
This PR needs a rebase unfortunately.

Once it's done, @gastaldi can you validate everything is OK for you?

2020-02-20 01:43 UTC, gastaldi commented
@SR-Lut3t1um you need to rebase your branch: 

- `git rebase master`
- `git push -f`

2020-02-20 11:12 UTC, gastaldi commented
Seems that there are conflicts. Can you `git pull` your master branch and rebase again?

2020-02-20 22:43 UTC, gsmet commented
I rebased and fixed the conflicts.

2020-02-20 22:49 UTC, merged

2020-02-20 22:49 UTC, gastaldi commented
Thanks! I tested locally and the Gradle build works great