Add oidc-code-flow dev mode test
quarkusio/quarkus pull request #7285
Opened 2020-02-19 16:14 UTC by sberyozkin

Fixes #6965.

2020-02-19 16:22 UTC, sberyozkin commented
It does not run in a native mode which is expected for the devmode tests

2020-02-19 16:26 UTC, gastaldi approved these changes
LGTM, but I'd rather wait for @pedroigor to approve before merging ;)

2020-02-19 16:48 UTC, sberyozkin commented
@gastaldi Hi, thanks; sure, lets wait for Pedro and/or Stuart to check

2020-02-19 21:14 UTC, stuartwdouglas requested changes
This should really be in oidc/deployment, dev mode tests should not get their own 'integration-tests' module (we already have hundreds of modules, so we need to resist adding any that are not needed).

2020-02-19 23:12 UTC, sberyozkin commented
Hi @stuartwdouglas 
The reason I've added it there is that it requires a docker starting KC. I've tried initially allocate it in the `integration/oidc-code-flow` but it was interfering with the main `CodeFlowTest` (KC was failing to create the realms).
If I move it to `extensions/oidc/deployment`, will it be actually tested in CI (it depends on `docker-keycloak` and `test-keycloak` profiles).
CC @gsmet

2020-02-19 23:25 UTC, stuartwdouglas commented
Yes, it will still be tested, keycloak is still started for the JVM mode tests.

2020-02-20 13:18 UTC, sberyozkin commented
Hi @stuartwdouglas, how does it look now ?

2020-02-20 14:23 UTC, sberyozkin commented
`http://localhost:8180` is not available in CI. How to identify the problem ? Looks lie Keycloak has not completed its own initialization yet by the time the test starts contacting Keycloak.

2020-02-20 18:21 UTC, sberyozkin commented
@stuartwdouglas The same test works in `integration-tests/`, so I wonder if there is some timing issue.

2020-02-24 01:34 UTC, stuartwdouglas commented
It looks like you have fixed the timing issue?

2020-02-24 01:35 UTC, stuartwdouglas requested changes

2020-02-24 01:35 UTC, stuartwdouglas commented on extensions/oidc/deployment/pom.xml
> +                <artifactId>maven-failsafe-plugin</artifactId>
Failsafe is not used here, as there are no native image tests

2020-02-24 01:35 UTC, stuartwdouglas commented on extensions/oidc/deployment/pom.xml
> +                        <artifactId>maven-failsafe-plugin</artifactId>
same here

2020-02-24 01:35 UTC, stuartwdouglas commented on extensions/oidc/deployment/pom.xml
> +                        <groupId>io.quarkus</groupId>
This should not be here.

2020-02-24 10:18 UTC, sberyozkin commented
Hi @stuartwdouglas I've only added a `keycloak.url` maven property and the resource filtering as used in the integration tests, but the main 'fix' was about rebasing and force-pushing repeatedly :-).
Let me take care of the new comments and see what happens :-)

2020-02-24 10:21 UTC, stuartwdouglas commented
Does that mean it it likely intermittently failing, and just happened to pass this time?

2020-02-24 12:46 UTC, sberyozkin commented
Windows build failure is unrelated: ` Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project quarkus-resteasy-deployment: There are test failures.`

2020-02-25 17:15 UTC, sberyozkin commented
@stuartwdouglas It has passed again, so please merge if all looks good to you

2020-02-25 17:23 UTC, sberyozkin commented
@stuartwdouglas It has passed again, so please merge if all looks good to you

2020-02-26 10:58 UTC, stuartwdouglas approved these changes

2020-02-26 10:58 UTC, merged