fix: increase reactive test SSE wait time
quarkusio/quarkus pull request #7456
Opened 2020-02-27 13:11 UTC by loicmathieu

@geoand this PR increase the wait time for the SSE test as discussed on Zulip.
I could be interesting to merged it asap to avoid CI issues

2020-02-27 13:13 UTC, loicmathieu commented
The PR #7443 contains the same fix so if merged this one could be closed.

2020-02-27 13:22 UTC, geoand commented
Let's merge this one first since it's pretty important

2020-02-27 13:22 UTC, geoand approved these changes

2020-02-27 13:49 UTC, gsmet requested changes

2020-02-27 13:49 UTC, gsmet commented on integration-tests/mongodb-panache/src/test/java/io/quarkus/it/mongodb/panache/reactive/ReactiveMongodbPanacheResourceTest.java
> +            Thread.sleep(150);//wait a little for the events to comes in
Can't we use awaitility instead of this? We would wait for longer but still be more reactive as it would poll the result automatically.

2020-02-28 06:53 UTC, geoand commented
Closing in favor of #7475

2020-02-28 06:53 UTC, closed without merging