Quarkus recommended labels
quarkusio/quarkus pull request #7501
Opened 2020-03-01 14:36 UTC by iocanel

Fixes: #7482 

This pull request brings in the following changes:

i) Adopts the recommended kubernetes labels (`app.kubernetes.io/name` & `app.kubernetes.io/version`).
ii) Adopts the recommended openshift annotations (`app.openshift.io/vcs-url`).
iii) Adds and groups other annotations under `app.quarkus.io` (e.g. `app.quarkus.io/commit-id` and `app.quarkus.io/build-timestamp).

Additionally, it replaces the `group` property from `KubernetesConfig`, `OpenshiftConfig` and `KnativeConfig` to `part-of` so that that it matches the label `app.kubernetes.io/part-of` and also to limit confusion the the `quarkus.container-image.group`.

Last it documents all the above and align the kubernetes docs with all the changes of the last couple of weeks.

2020-03-01 14:38 UTC, iocanel commented
@maxandersen: If feel that this change is going to "standardize" things around labels and annotations and also will simplify things alot. The `group` was affecting many things and was quite confusing (cc @lordofthejars).

2020-03-01 16:07 UTC, geoand requested changes
I added some comments about the docs. I can't really check the code changes yet since I'm on a phone.
I also can't yet vouch for the heading changes in the docs.

2020-03-01 16:07 UTC, geoand commented on docs/src/main/asciidoc/kubernetes.adoc
> +To add addtional Labels, for example `foo=bar`:
`addtiinal` -> `additional`

2020-03-01 16:07 UTC, geoand commented on docs/src/main/asciidoc/kubernetes.adoc
> +Kubernetes provides multiple ways of defining environment varialbes:
`varialbes` -> `variables`

2020-03-01 16:07 UTC, geoand commented on docs/src/main/asciidoc/kubernetes.adoc
> +To add a key value pair as an environmnet variable in the generated resources:
`environmnet` -> `environment`

2020-03-01 16:07 UTC, geoand commented on docs/src/main/asciidoc/kubernetes.adoc
> +To change the number of replicas from 1 to  3:
There is an extra space before `3`

2020-03-01 16:08 UTC, geoand commented
@iocanel IIRC group was added recently so there won't be existing code that uses it, right?

2020-03-01 17:06 UTC, iocanel commented
> @iocanel IIRC group was added recently so there won't be existing code that uses it, right?

Right.

2020-03-02 06:36 UTC, geoand requested changes
I added some more small comments

2020-03-02 06:36 UTC, geoand commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KnativeConfig.java
> +     * The name of the group this component belogs too
```suggestion
     * The name of the group this component belongs too
```

2020-03-02 06:36 UTC, geoand commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesConfig.java
> +     * The name of the group this component belogs too
```suggestion
     * The name of the group this component belongs too
```

2020-03-02 06:36 UTC, geoand commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/OpenshiftConfig.java
> +     * The name of the group this component belogs too
```suggestion
     * The name of the group this component belongs too
```

2020-03-02 06:36 UTC, geoand commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesProcessor.java
> -        //TODO: This is needed until https://github.com/dekorateio/dekorate/issues/456 is resolved.
This comment seems to have been removed from the code that adds `ApplyContainerImageDecorator`. Should it be re-added sicne the issue is still open or has the issue been side-stepped?

2020-03-02 06:36 UTC, geoand commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesProcessor.java
> -        kubernetesGroup.ifPresent(v -> System.setProperty(APP_GROUP_PROPERTY, v));
With these changes `DOCKER_REGISTRY_PROPERTY` and `APP_GROUP_PROPERTY` are no longer used

2020-03-02 06:36 UTC, geoand commented on extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/KubernetesProcessor.java
> +        session.resources().decorate(target, new RemoveAnnotationDecorator(Annotations.COMMIT_ID));
Can we have a comment here please explaining that `dekorate` adds these automatically and we want to replace them with more specific ones?

2020-03-02 06:36 UTC, geoand commented on docs/src/main/asciidoc/kubernetes.adoc
> +By adding this dependency, we enable the generation of kubernetes manifests each time we perform a build.
I think we should probably use `Kubernetes` (upper-case `K`) in all instances of the doc that aren't referring to code

2020-03-02 06:36 UTC, geoand commented on docs/src/main/asciidoc/kubernetes.adoc
> +            "image" : "yourDockerUsernmae/test-quarkus-app:1.0-SNAPSHOT",
This change doesn't look right :)

2020-03-02 06:36 UTC, geoand commented on docs/src/main/asciidoc/kubernetes.adoc
> +The image is not the only thing that can be cusotmized in the generated manifests. The kubernetes extension provides a rich set of configuration properties, that allow customization.
This hasn't been fixed

2020-03-02 06:36 UTC, geoand commented on docs/src/main/asciidoc/kubernetes.adoc
> +To add a key value pair as an environmnet variable in the generated resources:
Same here

2020-03-02 06:36 UTC, geoand commented on docs/src/main/asciidoc/kubernetes.adoc
> +You may also noticed that in contrast to labels, and annotations for environment variables you don't just use a key=value approach.
```suggestion
You may also noticed that in contrast to labels and annotations for environment variables you don't just use a key=value approach.
```

2020-03-02 06:36 UTC, geoand commented on docs/src/main/asciidoc/kubernetes.adoc
> +That is because for environment variables there are additional options rather than just value.
```suggestion
That is because for environment variables there are additional options rather than just setting a value.
```

2020-03-03 13:55 UTC, geoand approved these changes

2020-03-03 13:56 UTC, maxandersen commented
idea looks good - just checking here - wasn't .group introduced in 1.3 or sooner ?

2020-03-03 13:57 UTC, geoand commented
> idea looks good - just checking here - wasn't .group introduced in 1.3 or sooner ?

I asked the same question myself :)

@iocanel says it was not part of 1.2.x

2020-03-03 13:59 UTC, maxandersen commented
I could have sworn I read about those earlier....:)

2020-03-03 13:59 UTC, maxandersen commented
but if that’s not the case I'm all for cleaning this up.

2020-03-03 14:06 UTC, iocanel commented
> idea looks good - just checking here - wasn't .group introduced in 1.3 or sooner ?

In 1.2 we had the old `prefixless` properties. For example `kubernetes.name`, `kubernetes.version`  and `kubernetes.group`. These properties are deprecated but still available.

The `quarkus.kubernetes.group` was added like two weeks ago.
So, since we are not touching the old properties and renaming a newly introduced one I think we are fine.

@maxandersen @geoand: wdyt?

2020-03-03 15:00 UTC, maxandersen commented
ag - if we can keep the old and improve the new then I'm +1 on this.

something to add for migration guide ;)

2020-03-03 15:01 UTC, geoand commented
Question: will `kubernetes.group` still work?

2020-03-03 15:23 UTC, iocanel commented
> Question: will `kubernetes.group` still work?
Checked, the code and it doesn't seem likely. If we agree I will map it to the new label.

2020-03-03 15:27 UTC, geoand commented
Yeah, I think we should make it work

2020-03-03 17:53 UTC, gsmet requested changes
I did some proofreading of the documentation.

2020-03-03 17:53 UTC, gsmet commented on docs/src/main/asciidoc/kubernetes.adoc
> +The name of the image is controlled by the container-image extension and can be customized using the usual `applcation.properties`.
```suggestion
The name of the image is controlled by the container-image extension and can be customized using the usual `application.properties`.
```

2020-03-03 17:53 UTC, gsmet commented on docs/src/main/asciidoc/kubernetes.adoc
> +=== Defining a docker registry
```suggestion
=== Defining a Docker registry
```

2020-03-03 17:53 UTC, gsmet commented on docs/src/main/asciidoc/kubernetes.adoc
> +The docker registry can be specified, with the following property:
```suggestion
The Docker registry can be specified with the following property:
```

2020-03-03 17:53 UTC, gsmet commented on docs/src/main/asciidoc/kubernetes.adoc
> +By adding this property along the rest of the container-image properties of the previous section, the generated manifests will use the image `http://my.docker-registry.net/quarkus/demo-app:1.0`.
```suggestion
By adding this property along with the rest of the container-image properties of the previous section, the generated manifests will use the image `http://my.docker-registry.net/quarkus/demo-app:1.0`.
```

2020-03-03 17:53 UTC, gsmet commented on docs/src/main/asciidoc/kubernetes.adoc
> +The image is not the only thing that can be customized in the generated manifests. The kubernetes extension provides a rich set of configuration properties, that allow customization.
```suggestion
The image is not the only thing that can be customized in the generated manifests. The kubernetes extension provides a rich set of configuration properties that allow customization.
```

2020-03-03 17:53 UTC, gsmet commented on docs/src/main/asciidoc/kubernetes.adoc
> +To add additional Labels, for example `foo=bar`:
```suggestion
To add additional custom labels, for example `foo=bar`:
```

2020-03-03 17:53 UTC, gsmet commented on docs/src/main/asciidoc/kubernetes.adoc
> +Out of the box the generated resources will be annotated with version control related information that can be used either by tooling, or by the user for troubleshooting purposes.
```suggestion
Out of the box, the generated resources will be annotated with version control related information that can be used either by tooling, or by the user for troubleshooting purposes.
```

2020-03-03 17:53 UTC, gsmet commented on docs/src/main/asciidoc/kubernetes.adoc
> +Custom annotations can be added in way similar to labels. For example to add the annotation `foo=bar`:
```suggestion
Custom annotations can be added in a way similar to labels. For example to add the annotation `foo=bar`:
```

2020-03-03 17:53 UTC, gsmet commented on docs/src/main/asciidoc/kubernetes.adoc
> +You may also noticed that in contrast to labels and annotations for environment variables you don't just use a key=value approach.
```suggestion
You may also have noticed that in contrast to labels and annotations for environment variables you don't just use a `key=value` approach.
```

2020-03-03 17:53 UTC, gsmet commented on docs/src/main/asciidoc/kubernetes.adoc
> +This will add a mount to my pod for volume `my-voume` to path `/where/to/mount`
```suggestion
This will add a mount to my pod for volume `my-volume` to path `/where/to/mount`.
```

2020-03-03 17:53 UTC, gsmet commented on docs/src/main/asciidoc/kubernetes.adoc
> +By default the Kubernetes resources do not contain readiness and liveness probes in the generated `Deployment`. Adding them however is just a matter of adding the Smallrye Health extension like so:
```suggestion
By default the Kubernetes resources do not contain readiness and liveness probes in the generated `Deployment`. Adding them however is just a matter of adding the SmallRye Health extension like so:
```

2020-03-03 17:53 UTC, gsmet commented on docs/src/main/asciidoc/kubernetes.adoc
> +Applications that are deployed to Kubernetes and need to access the API server, will usually make use of the `kubernetes-client` extension:
```suggestion
Applications that are deployed to Kubernetes and need to access the API server will usually make use of the `kubernetes-client` extension:
```

2020-03-04 13:22 UTC, geoand commented
@gsmet is this good now for you?

2020-03-05 10:01 UTC, iocanel commented
@gsmet: ping

2020-03-05 12:40 UTC, gsmet approved these changes

2020-03-05 12:40 UTC, merged

2020-03-05 12:40 UTC, gsmet commented
Feel free to dismiss my reviews when they are just about typos and you fixed them. I merged it.

2020-03-05 12:43 UTC, geoand commented
OK thanks :)