Use mongo started from docker instead of flapdoodle
quarkusio/quarkus pull request #7625
Opened 2020-03-06 07:58 UTC by geoand

2020-03-06 09:06 UTC, loicmathieu commented
As I remember the issue is that Windows CI previously didn't have a docker engine.

If now it has one, maybe using Testcontainers is easier ?

To run a replica set (it will also be mandatory for mongodb with Panache as transaction support may lands some days) it's not yet possible easily with testcontainers but it can be done via https://github.com/silaev/mongodb-replica-set/

2020-03-06 09:11 UTC, geoand commented
That looks interesting indeed!

2020-03-06 09:29 UTC, geoand commented
I'll update the PR to use testcontainers since it does indeed seem easier to use

2020-03-06 10:01 UTC, geoand commented
@loicmathieu PR updated to use test containers

2020-03-06 10:40 UTC, loicmathieu requested changes
It appears you start MongoDB but never stop it, I know Ryuk will close it at the end of the test but this can slighly delay the close so maybe you should manually close.

Also, MongoDB client can reconnect, so you can safely use the standard integration way (via annotations https://www.testcontainers.org/test_framework_integration/junit_5/), with it the container will be started after Quarkus but before any test so it will works (I did that in my first implementation of the MongoDB with Panache IT and go back to flapdoodle as Testcontainers didn't works on Quarkus windows CI builds at this time).

2020-03-06 10:40 UTC, loicmathieu commented on integration-tests/mongodb-client/pom.xml
> +            </exclusions>
Missing the test scope ?

2020-03-06 10:40 UTC, loicmathieu commented on integration-tests/mongodb-panache/pom.xml
> +            </exclusions>
Missing test scope ?

2020-03-06 10:48 UTC, geoand commented on integration-tests/mongodb-client/pom.xml
> +            </exclusions>
Fixed, thanks

2020-03-06 10:48 UTC, geoand commented on integration-tests/mongodb-panache/pom.xml
> +            </exclusions>
Fixed

2020-03-06 10:50 UTC, geoand commented
> It appears you start MongoDB but never stop it, I know Ryuk will close it at the end of the test but this can slighly delay the close so maybe you should manually close.
> 

Not sure what you mean here because Mongo does get closed: https://github.com/geoand/quarkus/blob/5b490b99bebc0bfcc3cf6589f528e3daa1af07bc/integration-tests/mongodb-panache/src/test/java/io/quarkus/it/mongodb/panache/MongoTestResource.java#L25

> Also, MongoDB client can reconnect, so you can safely use the standard integration way (via annotations https://www.testcontainers.org/test_framework_integration/junit_5/), with it the container will be started after Quarkus but before any test so it will works (I did that in my first implementation of the MongoDB with Panache IT and go back to flapdoodle as Testcontainers didn't works on Quarkus windows CI builds at this time).

Using the Quarkus way of integrating with test containers works under all circumstances, @cescoffier can tell you more since he has had to deal with multiple related issues

2020-03-06 11:19 UTC, geoand commented
I played with `silaev/mongodb-replica-set` and although it seems exactly like what we want, I couldn't get it to work reliably

2020-03-06 12:34 UTC, gsmet commented
Does it mandate Docker for the default build? Because we don't want that.

2020-03-06 12:35 UTC, geoand commented
It does

2020-03-06 13:16 UTC, loicmathieu commented
> Not sure what you mean here because Mongo does get closed:

My bad, didn't saw it as I didn't open the full class ...

> Using the Quarkus way of integrating with test containers works under all circumstances, @cescoffier can tell you more since he has had to deal with multiple related issues

It works in both way so it's OK for me

2020-03-06 13:19 UTC, geoand commented
@gsmet this is only for the integration tests which require docker anyway

2020-03-31 17:30 UTC, geoand commented
I'll close this since we haven't had issues with Mongo in CI lately

2020-03-31 17:30 UTC, closed without merging