Fix #7700: Actually use the JBoss Nexus artifacts in the Azure mvn se…
quarkusio/quarkus pull request #7701
Opened 2020-03-09 14:43 UTC by Sanne

…ttings

Assigning to @gsmet to make sure we're not going back and forth on this one: we already changed approaches a couple of times and might be missing something.

2020-03-09 14:44 UTC, gsmet commented
I have only one small question: how come CI works OK with this? (and it started from scratch quite a few times)

2020-03-09 14:45 UTC, Sanne commented
> I have only one small question: how come CI works OK with this? (and it started from scratch quite a few times)

right I was puzzled by that too. I'd say it's because we use aggressive copies of the maven repo as a cache?

WhatI can see is that the current setup doesn't work for me locally: having a clean repo and no settings.xml

2020-03-09 14:47 UTC, Sanne commented
BTW this allows me to build much faster. Apparently the previous setup was getting me throttled somehow; I'm not going to measure accurately but the progress is visible in the terminal.

2020-03-09 14:50 UTC, gsmet requested changes
I added a few comments.

You have missed the original intent: the Google mirror is not in our hands and is updated quite infrequently. Thus the second level of proxying to JBoss Nexus which acts more as a proxy so is usually more up to date (but slower).

As for downloading custom JBoss jars, they are usually coming from the JBoss parent and it comes with its own repository thus it should work OK.

CI works OK with that setup and it often starts from a totally empty repository.

If you have issue with that, we need to keep the JBoss Central mirror and add a new one, not replace it.

I know it's cumbersome but as soon as you hit Maven Central, your build is mostly dead so we need to put as many chances as possible on our side to avoid that. At least, that was the case on Azure. Currently unsure what the situation is on GH CI and if they are throttled at the Maven Central level as Azure is.

2020-03-09 14:50 UTC, gsmet commented on azure-mvn-settings.xml
>            <id>jboss-maven-central-proxy</id>
This would need an update.

2020-03-09 14:50 UTC, gsmet commented on azure-mvn-settings.xml
>            <name>JBoss Maven Central proxy</name>
The id and the name should be updated too.

2020-03-09 14:53 UTC, Sanne commented
> You have missed the original intent: the Google mirror is not in our hands and is updated quite infrequently. Thus the second level of proxying to JBoss Nexus which acts more as a proxy so is usually more up to date (but slower).

you're right - sorry I forgot. So we still need the full group then, or both repositories explicitly listed.

> As for downloading custom JBoss jars, they are usually coming from the JBoss parent and it comes with its own repository thus it should work OK.

well that doesn't seem to work.

2020-03-09 15:00 UTC, Sanne commented
steps to reproduce:

1. _cd ~/.m2/repository/org/apache/maven/plugins_
2. _rm -Rf maven-compiler-plugin_
3. switch to Quarkus directory
4. _mvn dependency:go-offline -s azure-mvn-settings.xml_

2020-03-09 15:14 UTC, gsmet commented
Do you know which artifact it can't find? I wonder if we have a regression here.

2020-03-09 15:18 UTC, Sanne commented
> Do you know which artifact it can't find? I wonder if we have a regression here.

sure, it's the usual one, the compiler-plugin:

    org.eclipse.aether.resolution.DependencyResolutionException: Failure to find org.apache.maven.plugins:maven-compiler-plugin:jar:3.8.0-jboss-1

I'll amend this PR to include both repositories.

2020-03-09 15:22 UTC, gsmet commented
Hmm, so this one should come from the repositories defined in the JBoss
parent. At least that's how it worked on my box and has worked until now.

I should probably check what's going on.

On Mon, Mar 9, 2020 at 4:18 PM Sanne Grinovero <notifications@github.com>
wrote:

> Do you know which artifact it can't find? I wonder if we have a regression
> here.
>
> sure, it's the usual one, the compiler-plugin:
>
> org.eclipse.aether.resolution.DependencyResolutionException: Failure to find org.apache.maven.plugins:maven-compiler-plugin:jar:3.8.0-jboss-1
>
> I'll amend this PR to include both repositories.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/quarkusio/quarkus/pull/7701?email_source=notifications&email_token=AAJYOBOHNYPC2WBBHSOZBWLRGUCFVA5CNFSM4LEKI3G2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOHU6RY#issuecomment-596594503>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJYOBN5J7OZNLEQA3AJ42DRGUCFVANCNFSM4LEKI3GQ>
> .
>

2020-03-09 15:26 UTC, Sanne commented
I would be surprised if relying on repositories defined "somewhere" in your dependency tree would not be affected by various limitations, such as ordering issues or problematic priority semantics.

So I'd recommend to make such a dependency to a different repository explicit; BTW this has always been a policy in jboss projects.

2020-03-09 16:02 UTC, Sanne commented
spotted one more thing: if I only list the additional repository as a `pluginRepository` it still fails. 

The `jboss-parent-36.pom` lists it exclusively as a `pluginRepository`, but we have a fully fledged dependency to it via module `IDE/Tools`.  So I guess it's really missing.

2020-03-09 16:04 UTC, Sanne commented
fixed, added some comments for our future selves and push forced

2020-03-10 14:28 UTC, gsmet commented
What's a bit weird is that I build from a totally empty Maven repo for each release. And it works. That's why I'm wondering what's going on there.

2020-03-10 15:07 UTC, Sanne commented
You might have a custom settings.xml ?

I normally have one, only spotted this as I happened to build on a clean
machine.

On Tue, 10 Mar 2020, 14:28 Guillaume Smet, <notifications@github.com> wrote:

> What's a bit weird is that I build from a totally empty Maven repo for
> each release. And it works. That's why I'm wondering what's going on there.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/quarkusio/quarkus/pull/7701?email_source=notifications&email_token=AAAKMTMN5UJCUFP7ETPSLELRGZFCLA5CNFSM4LEKI3G2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOLULTQ#issuecomment-597116366>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAKMTJHGN5LXAVLX7N5G3LRGZFCLANCNFSM4LEKI3GQ>
> .
>

2020-03-12 12:35 UTC, gastaldi commented
This PR needs to be rebased since https://github.com/quarkusio/quarkus/pull/7790 was merged

2020-10-09 17:29 UTC, gastaldi commented
Doesn't seem to be needed by CI. Closing for now

2020-10-09 17:29 UTC, closed without merging