Document MDC trace IDs
quarkusio/quarkus pull request #7728
Opened 2020-03-10 12:31 UTC by pavolloffay

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

2020-03-10 13:08 UTC, cescoffier approved these changes

2020-03-10 22:54 UTC, gsmet requested changes

2020-03-10 22:54 UTC, gsmet commented on docs/src/main/asciidoc/opentracing.adoc
> +import org.slf4j.LoggerFactory;
This should be changed to use JBoss Logging.

2020-03-10 22:54 UTC, gsmet commented on docs/src/main/asciidoc/opentracing.adoc
> +    private static final Logger LOG = LoggerFactory.getLogger(TracedResource.class);
Please check that line too.

2020-03-11 08:44 UTC, pavolloffay commented
@gsmet changed to jboss logging.

2020-03-11 12:48 UTC, gsmet approved these changes

2020-03-11 12:48 UTC, merged

2020-03-11 12:48 UTC, gsmet commented
Thanks, merged!

2020-03-11 13:09 UTC, pavolloffay commented
Could you merge also https://github.com/quarkusio/quarkus-quickstarts/pull/485?