Fixes #5388
quarkusio/quarkus pull request #7849
Opened 2020-03-13 13:53 UTC by ShubhamRwt

Rebased PR (#5489)

2020-03-13 14:21 UTC, kunal-kushwaha commented on extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java
>  import java.util.stream.Collectors;
Can you please remove wildcard imports?

2020-03-13 14:52 UTC, dmlloyd requested changes

2020-03-13 14:52 UTC, dmlloyd commented on core/deployment/src/main/java/io/quarkus/deployment/JniProcessor.java
> +        boolean enable;
This changes the default value from `true` to `false`; we don't want that! I'd suggest to leave this one alone; it was correct already.

2020-03-13 14:52 UTC, dmlloyd commented on core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java
> +    @ConfigItem
Same here.  Only remove the default values if they're `false` or `0`.

2020-03-13 14:52 UTC, dmlloyd commented on core/test-extension/runtime/src/main/java/io/quarkus/extest/runtime/config/AllValuesConfig.java
> -    public Optional<Long> optionalLongValue;
This should not be changed: it is like this deliberately in order to test `Optional`.  If we change it to `OptionalLong` then we won't be testing that anymore.

2020-03-13 14:52 UTC, dmlloyd commented on extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/FlywayDataSourceBuildTimeConfig.java
> +    public Optional<String[]> locations;
This one shouldn't change to an array (almost every usage of this property treats it as a list).  And, it wasn't `Optional` before so it should not become `Optional` now.

2020-03-13 14:52 UTC, dmlloyd commented on extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java
> +                }
Maybe instead go with the original but slightly modified:
```suggestion
                hibernateConfig.jdbc.statementFetchSize.ifPresent(
                        fetchSize -> desc.getProperties().setProperty(AvailableSettings.STATEMENT_FETCH_SIZE,
                                Integer.toString(fetchSize));
```
Smaller diffs are usually preferred.

2020-03-13 14:52 UTC, dmlloyd commented on extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java
> +                }
Same here.

2020-03-13 14:52 UTC, dmlloyd commented on extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/ServerSslConfig.java
> +    public Optional<String[]> cipherSuites;
This one doesn't need to change: it's being used as a list, not an array.

2020-03-13 14:52 UTC, dmlloyd commented on extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSConfig.java
> +    public Optional<HttpMethod[]> methods;
These ones don't need to change, since they're being used as lists not arrays.

2020-03-13 14:52 UTC, dmlloyd commented on extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSConfig.java
> +    public Optional<String[]> headers;
These ones don't need to change, since they're being used as lists not arrays.

2020-03-13 14:52 UTC, dmlloyd commented on extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/cors/CORSConfig.java
> +    public Optional<String[]> exposedHeaders;
These ones don't need to change, since they're being used as lists not arrays.

2020-05-04 11:35 UTC, gsmet commented
Closing this one. Too many conflicts. Please open a new PR if you want to pursue.

2020-05-04 11:35 UTC, closed without merging