Make @QuarkusTest play nicely with @ParameterizedTest
quarkusio/quarkus pull request #7881
Opened 2020-03-16 10:59 UTC by geoand

Fixes: #7877

2020-03-16 11:00 UTC, gsmet requested changes
Spotted a small typo. Otherwise looks good.

2020-03-16 11:00 UTC, gsmet commented on test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java
> +     * Return true if we are need a parameter for constructor injection
```suggestion
     * Return true if we need a parameter for constructor injection
```

2020-03-16 11:01 UTC, gsmet commented
@geoand I added the backport label? I think we would want to backport this, no? I have a vague recollection this went into 1.3.

Please remove the label if I'm wrong!

2020-03-16 11:04 UTC, gastaldi approved these changes
LGTM

2020-03-16 11:04 UTC, geoand commented
@gsmet it was not backported to 1.3: https://github.com/quarkusio/quarkus/pull/7714

2020-03-16 11:04 UTC, geoand commented on test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java
> +     * Return true if we are need a parameter for constructor injection
Thanks, fixed!

2020-03-16 11:30 UTC, gsmet commented
Ah yes, now I remember, you told me it wasn't critical. Thanks for correcting me!

2020-03-16 11:30 UTC, gsmet approved these changes

2020-03-16 11:31 UTC, geoand commented
Thanks for being thorough :wink:

2020-03-16 13:19 UTC, merged

2020-03-18 07:24 UTC, geoand commented
I actually added the backport label to both this and #7714