Increase kafka client test coverage
quarkusio/quarkus pull request #8237
Opened 2020-03-28 16:36 UTC by cescoffier

Fixes #8025 

add a few tests related to the Kafka client.

Unfortunately, Avro does not work in native mode (fields written using unsafe). 
I will create an issue to track this.

2020-03-31 08:38 UTC, cescoffier commented
Forgot to disable the test if docker is not enabled. Will fix that.

2020-04-10 09:08 UTC, gunnarmorling approved these changes
LGTM, a few minor comments inline.

2020-04-10 09:08 UTC, gunnarmorling commented on integration-tests/kafka/pom.xml
> +            <artifactId>kafka-avro-serializer</artifactId>
Have you considered using the serializer from the Apicurio project?

2020-04-10 09:08 UTC, gunnarmorling commented on integration-tests/kafka/src/main/java/io/quarkus/it/kafka/avro/AvroEndpoint.java
> +        props.put(AbstractKafkaAvroSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, registry);
Same thought as above: use the Apicurio SerDe?

2020-04-10 09:08 UTC, gunnarmorling commented on integration-tests/kafka/src/main/java/io/quarkus/it/kafka/sasl/SaslKafkaEndpoint.java
> +    private static void addSSL(Properties props) {
`addSsl`, to be consistent with other abbreviation casing in this test?

2020-04-10 09:08 UTC, gunnarmorling commented on integration-tests/kafka/src/test/java/io/quarkus/it/kafka/SaslKafkaConsumerTest.java
> +    private static void addSSL(Properties props) {
```suggestion
    private static void addSsl(Properties props) {
```

2020-04-10 16:15 UTC, gsmet commented
@cescoffier can you check Gunnar's comments?

2020-04-12 07:30 UTC, cescoffier commented
@gunnarmorling I need to look at the Apicurio version of the Avro serde. So far the need was the "original" Avro. I can see an opportunity here if it works flawlessly in native. 
I have created https://github.com/quarkusio/quarkus/issues/8541.

2020-04-14 17:41 UTC, gsmet requested changes
I really don't like the fact that we have versions in the pom files. They should either be in the BOM if it makes sense or in the build-parent.

2020-04-14 18:03 UTC, cescoffier commented
As these artifacts are not available from Maven Central it's tricky to add them to the dependency management from the parent. That's why I put the version there on purpose.

Someone not aware of this would add the dependency that won't get resolved. 
Note that we should NOT declare the repository in the parent either.

2020-04-24 08:21 UTC, gsmet approved these changes

2020-04-24 08:22 UTC, gsmet commented
I rebased and force pushed as it was an old PR. I'm a bit worried about the external repository. We'll see if it causes problems and reevaluate.

2020-04-24 12:48 UTC, merged