Honor the environment variable for verifying the host at which the server is listening
quarkusio/quarkus pull request #8240
Opened 2020-03-28 19:48 UTC by roguexz

2020-03-28 20:45 UTC, gastaldi commented
You can inject the config property in the test instead:

```java
    @ConfigProperty(name="quarkus.http.host", defaultValue="0.0.0.0")
    String host;
```

2020-03-29 00:57 UTC, gastaldi approved these changes
LGTM

2020-03-29 00:59 UTC, gastaldi requested changes
Hum, sorry, looks like it doesn't work with native :disappointed: 

```java
[ERROR] Failures: 
[ERROR]   JaxRSITCase>JaxRSTestCase.testConfigInjectionOfPort:40 1 expectation failed.
Response body doesn't match expectation.
Expected: is null
  Actual: 0.0.0.0
```

2020-03-29 01:01 UTC, gastaldi commented
What happens if you change to `Instance<String> host` and call `host.get()` in the test instead of `String host`?

2020-03-29 01:09 UTC, machi1990 commented
Injection is not yet supported in Native tests - https://quarkus.io/guides/getting-started-testing#native-executable-testing

2020-03-29 01:45 UTC, roguexz commented
so, would you recommend that I move it back to checking for environment variables? That is what I started with originally.

2020-03-29 02:09 UTC, gastaldi commented
@roguexz yeah maybe that would be the best in this case, WDYT @dmlloyd ?

2020-03-29 02:26 UTC, roguexz commented
For a reference, my original commit had the following change,
```
RestAssured.when().get("/test/config/host").then()
            .body(is(System.getenv().getOrDefault("QUARKUS_HTTP_HOST", "0.0.0.0")));
```
If you are ok with it, I can update the commit.

2020-03-29 02:59 UTC, gastaldi commented
Isn't easier to just check if the body response is not empty or null?

2020-03-29 03:32 UTC, roguexz commented
@gastaldi The original test was checking for `0.0.0.0`. As part of debugging another issue, I noticed this scenario.

2020-03-29 03:38 UTC, gastaldi commented
I know, I mean that the possible values for this test are `localhost` or `0.0.0.0`, so I wonder if isn't easier to just check if the result matches one of those values

2020-03-29 03:43 UTC, gastaldi commented
Just another shot: try getting the `quarkus.http.host` from `ConfigProvider.getConfig()`.

2020-03-29 03:45 UTC, gastaldi commented
The reason is that we should avoid reading from `System.getenv()` or `System.getProperties()` and use MP Config where possible

2020-03-29 07:40 UTC, roguexz commented
Agreed. Wouldn't the suggested fix do the same, giving the additional possibility of honoring a system environment value? I am good either ways. What would you recommend?

2020-03-29 10:39 UTC, gastaldi commented
I'm fine with either TBH ;)

2020-03-29 22:09 UTC, roguexz commented
@gastaldi Done. I have switched to using MP config instead.

2020-03-30 08:42 UTC, geoand approved these changes
Thanks for this!

2020-03-30 11:51 UTC, gastaldi approved these changes

2020-03-30 11:51 UTC, merged