Move the Security API to Mutiny
quarkusio/quarkus pull request #8352
Opened 2020-04-02 11:46 UTC by stuartwdouglas

2020-04-02 14:04 UTC, gsmet commented
Looks like CI is consistently unhappy :).

2020-04-02 16:50 UTC, sberyozkin commented
Wow, I can finally learn few things about Mutiny :-)

2020-04-02 16:54 UTC, sberyozkin commented on bom/runtime/pom.xml
> +        <quarkus-security.version>1.1.0.Beta1</quarkus-security.version>
Hi Stuart, it is not really related to this PR, would it make sense to move `quarkus-security` into `quarkus` eventually ? I've added a couple of exceptions into `quarkus-vertx-http` which should probably be in `quarkus-security`, and we can tweak things faster there

2020-04-02 22:12 UTC, sberyozkin commented on bom/runtime/pom.xml
> +        <quarkus-security.version>1.1.0.Beta1</quarkus-security.version>
by the way, I'm not asking to move it now :-), only a question/suggestion as I recall you were contemplating it at some point

2020-04-03 10:02 UTC, sberyozkin commented
@stuartwdouglas Hi Stuart I've looked through all the PR and it looks fine, I guess somewhere the UNI replacement may need to be tweaked a bit for the tests to pass, otherwise LGTM

2020-04-06 03:41 UTC, stuartwdouglas commented
CI is happy now, one of the integration tests was missing a dependency on quarkus-resteasy-mutiny

2020-04-06 09:46 UTC, sberyozkin commented
@stuartwdouglas Hi, thanks, I can't see anything wrong really with the PR even though it is the first time I'm looking closely at the Mutiny code :-), so I'll be happy to approve.

2020-04-06 09:46 UTC, sberyozkin approved these changes

2020-04-06 13:49 UTC, cescoffier requested changes
The new version of Mutiny provides a better way to create Uni with `null`. That would replace a bunch of empty optionals.

2020-04-06 13:49 UTC, cescoffier commented on extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/QuarkusErrorHandler.java
> +                }).subscribeAsCompletionStage();
Not totally sure what you are doing here.
The subscription will trigger the computation.
But you may want to be sure that an error has not been emitted.

2020-04-06 13:59 UTC, sberyozkin commented on extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java
> +                    return authenticate(request, vertxContext).await().indefinitely();
@cescoffier the expectation here has been that Vertx client will not block itself if establishing a connection to OIDC is required. Can it block ?

2020-04-07 04:43 UTC, stuartwdouglas commented
I have updated as per @cescoffier 's comments.

2020-04-10 06:30 UTC, cescoffier approved these changes
Just a very small simplification that could be done.

2020-04-10 06:30 UTC, cescoffier commented on extensions/security/runtime/src/main/java/io/quarkus/security/runtime/QuarkusSecurityIdentity.java
> +                        if (val) {
`return val`?

2020-04-10 06:31 UTC, cescoffier commented on extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java
> +                    return authenticate(request, vertxContext).await().indefinitely();
this code waits for an item, even if the underlying communication and processing in non-blocking, this code is waiting for the result.

2020-04-10 12:47 UTC, gsmet commented
I rebased and force pushed. I don't think Clément's comment is blocking so I'll merge as soon as CI is green.

2020-04-10 14:55 UTC, gsmet commented
The JDK 8 build failed in the AMQP tests with:
```
[ERROR] testCodeUpdate  Time elapsed: 5.585 s  <<< ERROR!
java.lang.IllegalStateException: Arc context propagation was attempted but the container is not running.
    at io.quarkus.arc.runtime.context.ArcContextProvider.lambda$currentContext$2(ArcContextProvider.java:35)
    at io.smallrye.context.impl.ActiveContextState.<init>(ActiveContextState.java:18)
    at io.smallrye.context.impl.CapturedContextState.begin(CapturedContextState.java:35)
    at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:213)
    at io.smallrye.context.propagators.rxjava2.ContextPropagatorOnFlowableCreateAction$ContextCapturerFlowable.onNext(ContextPropagatorOnFlowableCreateAction.java:50)
    at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:506)
    at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:371)
    at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:670)
    at io.smallrye.context.propagators.rxjava2.ContextPropagatorOnFlowableCreateAction$ContextCapturerFlowable.lambda$onNext$2(ContextPropagatorOnFlowableCreateAction.java:50)
    at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:215)
    at io.smallrye.context.propagators.rxjava2.ContextPropagatorOnFlowableCreateAction$ContextCapturerFlowable.onNext(ContextPropagatorOnFlowableCreateAction.java:50)
    at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:117)
    at io.reactivex.processors.AsyncProcessor.subscribeActual(AsyncProcessor.java:242)
    at io.reactivex.Flowable.subscribe(Flowable.java:14935)
    at io.reactivex.Flowable.subscribe(Flowable.java:14882)
    at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
    at io.smallrye.context.propagators.rxjava2.ContextPropagatorOnFlowableCreateAction$ContextCapturerFlowable.lambda$onNext$2(ContextPropagatorOnFlowableCreateAction.java:50)
    at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:215)
    at io.smallrye.context.propagators.rxjava2.ContextPropagatorOnFlowableCreateAction$ContextCapturerFlowable.onNext(ContextPropagatorOnFlowableCreateAction.java:50)
    at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
```
there must be a race condition somewhere.

/cc @FroMage @cescoffier 

Not blocking for this PR though.

2020-04-10 15:09 UTC, FroMage commented
I'm not sure what that has to do with AMQP, or why they use rxjava2, or why the container stopped running.

2020-04-10 15:32 UTC, merged