Add deprecate warning for buildNative task
quarkusio/quarkus pull request #8458
Opened 2020-04-07 19:44 UTC by glefloch

@gastaldi, here is a pull request for the documentation. I was thinking of adding all available native properties. Something like https://quarkus.io/guides/building-native-image#configuration-reference

WDYT? Should I update the other pull request with something like that?

2020-04-07 20:09 UTC, gastaldi requested changes
I added a minor suggestion, see if that makes sense. 

You can add the following snippet to the documentation if you want all available native properties as a table: 

```asciidoc
include::{generated-dir}/config/quarkus-native-pkg-native-config.adoc[opts=optional]
```

2020-04-07 20:09 UTC, gastaldi commented on docs/src/main/asciidoc/gradle-tooling.adoc
> +The `buildNative` task has been deprecated in favor of task +
```suggestion
The `buildNative` task has been deprecated in favor of
```

2020-04-07 20:21 UTC, glefloch commented
@gastaldi thanks for the review, it totally makes sense. I updated the doc. 
Thanks for the snippet, I will add it in the other pull request.

2020-04-07 20:24 UTC, gastaldi approved these changes
LGTM

2020-04-08 04:07 UTC, geoand approved these changes

2020-04-08 09:53 UTC, merged

2020-04-15 10:58 UTC, andreas-eberle commented
What was the reasoning behind the deprecation of the buildNative task? If I have a gradle project with many microservices, I was able to use the buildNative task to configure common properties for all of them in the parent gradle file. Now I'll have to it for every module/every microservice.