Add 'go give a start on github' on start page
quarkusio/quarkus pull request #8496
Opened 2020-04-09 09:31 UTC by maxandersen

2020-04-09 09:37 UTC, geoand commented
Strictly speaking, only the `index.ftl` file change is needed

2020-04-09 09:41 UTC, maxandersen commented
just fearing smoe tests would fail if output wasn't properly matched and by doing a regular expression replacement i could ensure all was updated wither .ftl or .html

2020-04-09 09:43 UTC, geoand commented
Yeah, it's not a problem at all

2020-04-09 10:33 UTC, geoand approved these changes

2020-04-09 11:44 UTC, gastaldi approved these changes

2020-04-09 14:13 UTC, gastaldi commented on independent-projects/tools/common/src/test/resources/templates/index.ftl
> +        <p>Go give it a star on <a href="https://github.com/quarkusio/quarkus">github</a>.</p>
```suggestion
        <p>Go give it a star on <a href="https://github.com/quarkusio/quarkus">GitHub</a>.</p>
```

2020-04-09 14:14 UTC, gastaldi commented
Looks good, but I'd go with `GitHub`, not `github` :)

2020-04-14 17:39 UTC, gsmet requested changes
See @gastaldi comment and mine. Those should be applied everywhere.

Also I would like @emmanuelbernard 's blessing on this type of things.

2020-04-14 17:39 UTC, gsmet commented on devtools/gradle/src/functionalTest/resources/add-extension-multi-module/application/src/main/resources/META-INF/resources/index.html
> +        <h2>Do you like Quarkus ?</h2>
```suggestion
        <h2>Do you like Quarkus?</h2>
```

2020-04-14 17:39 UTC, gsmet commented on devtools/gradle/src/functionalTest/resources/basic-java-library-module/application/src/main/resources/META-INF/resources/index.html
> +        <h2>Do you like Quarkus ?</h2>
```suggestion
        <h2>Do you like Quarkus?</h2>
```

2020-04-14 17:39 UTC, gsmet commented on devtools/gradle/src/functionalTest/resources/basic-multi-module-project/application/src/main/resources/META-INF/resources/index.html
> +        <h2>Do you like Quarkus ?</h2>
```suggestion
        <h2>Do you like Quarkus?</h2>
```

2020-04-14 17:39 UTC, gsmet commented on devtools/platform-descriptor-json/src/main/resources/templates/index.ftl
> +        <h2>Do you like Quarkus ?</h2>
```suggestion
        <h2>Do you like Quarkus?</h2>
```

2020-04-14 17:39 UTC, gsmet commented on independent-projects/tools/common/src/test/resources/templates/index.ftl
> +        <h2>Do you like Quarkus ?</h2>
```suggestion
        <h2>Do you like Quarkus?</h2>
```

2020-04-14 17:39 UTC, gsmet commented on integration-tests/kotlin/src/test/resources/projects/classic-kotlin/src/main/resources/META-INF/resources/index.html
> +        <h2>Do you like Quarkus ?</h2>
```suggestion
        <h2>Do you like Quarkus?</h2>
```

2020-04-17 09:40 UTC, closed without merging

2020-04-17 09:43 UTC, maxandersen commented
okey thats just weird - I pushed master to this fork and github decides to close it and now can't reopen it....guess I'll have to make another pullreuqest then