fix compiler errors in kafka-streams guide
quarkusio/quarkus pull request #8520
Opened 2020-04-10 13:00 UTC by jharting

2020-04-10 14:52 UTC, gsmet requested changes

2020-04-10 14:52 UTC, gsmet commented on docs/src/main/asciidoc/kafka-streams.adoc
> +import org.slf4j.LoggerFactory;
Hmmm, no this is not good. We want to use JBoss Logging.

2020-04-10 14:52 UTC, gsmet commented
@cescoffier I let you have a look at that one? Looks related to your Kafka changes.

2020-04-10 14:57 UTC, gsmet commented
Thanks btw!

2020-04-10 14:57 UTC, gsmet commented
/cc @gunnarmorling too

2020-04-10 15:08 UTC, gunnarmorling commented
LGTM, apart from the logging change. Actual example needs updating, too?

2020-04-10 15:14 UTC, jharting commented
@gunnarmorling this PR is aligning the docs with what's in the quickstart https://github.com/quarkusio/quarkus-quickstarts/blob/master/kafka-streams-quickstart/producer/src/main/java/org/acme/kafka/streams/producer/generator/ValuesGenerator.java#L16

2020-04-10 15:22 UTC, gunnarmorling commented
Gotcha; note it might well have been an oversight on my part to use the
wrong logger types there. As per @gsmet it seems the quickstart should be
using JBoss Logging, too?

>

2020-04-10 15:34 UTC, gsmet commented
Yes, the quickstart should use JBoss Logging. Can you prepare a PR for the quickstart and adjust this one?

Thanks!

2020-04-14 08:11 UTC, gsmet approved these changes

2020-04-14 08:11 UTC, merged

2020-04-14 08:17 UTC, gsmet commented
I pushed a change along those lines and also fixes the quickstart.

Thanks!