Remove obsolete -DskipITs from documentation
quarkusio/quarkus pull request #8550
Opened 2020-04-13 12:30 UTC by zakkak

2020-04-13 12:33 UTC, geoand commented
Thanks @zakkak! 

I think it's fine, but @gsmet would know for sure

2020-04-13 12:55 UTC, gastaldi approved these changes

2020-04-14 07:34 UTC, gsmet requested changes
Could someone compare a run with and without?

It used to ignore some invoker tests that were still running with `-DskipTests`. Maybe the situation has changed but we need to be sure, run both with master and compare the time spent.

Once it's done we can proceed.

2020-04-14 10:49 UTC, zakkak commented
As pointed out by @mkouba in [zulip](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/is.20-DskipITs.20still.20valid.3F/near/193878919) the `-DskipITs` is actually honoured by the [maven failsafe plugin](https://maven.apache.org/surefire/maven-failsafe-plugin/examples/skipping-tests.html).

2020-04-14 10:49 UTC, closed without merging