Rest client integration test added
quarkusio/quarkus pull request #8577
Opened 2020-04-14 20:13 UTC by irenakezic

Rest client integration test added as agreed in [#8420](https://github.com/quarkusio/quarkus/pull/8420)

2020-04-14 20:30 UTC, gsmet requested changes
Cool, thanks!

I added a bunch of comments, mostly minor nitpicking!

2020-04-14 20:30 UTC, gsmet commented on integration-tests/pom.xml
> +        <module>resteasy-client</module>
Let's be consistent with the name of the extension: it should be `rest-client`.

2020-04-14 20:30 UTC, gsmet commented on integration-tests/resteasy-client/pom.xml
> +	<artifactId>quarkus-integration-tests-resteasy-client</artifactId>
```suggestion
	<artifactId>quarkus-integration-tests-rest-client</artifactId>
```

2020-04-14 20:30 UTC, gsmet commented on integration-tests/resteasy-client/pom.xml
> +	<name>Quarkus - Integration Tests - Resteasy client</name>
```suggestion
	<name>Quarkus - Integration Tests - REST Client</name>
```

2020-04-14 20:30 UTC, gsmet commented on integration-tests/pom.xml
>      </modules>
Also the module needs to be added here: https://github.com/quarkusio/quarkus/blob/master/.github/workflows/ci-actions.yml#L392 (and please add 10 minutes to the timeout a few lines above)

2020-04-14 20:30 UTC, gsmet commented on integration-tests/resteasy-client/src/test/java/org/acme/rest/client/multipart/MultipartResourceIT.java
> +package org.acme.rest.client.multipart;
The package should be consistent with the other classes.

2020-04-14 20:30 UTC, gsmet commented on integration-tests/resteasy-client/src/test/java/org/acme/rest/client/multipart/MultipartResourceTest.java
> +package org.acme.rest.client.multipart;
Same here.

2020-04-15 15:28 UTC, irenakezic commented
@gsmet pushed another commit with the suggested changes

2020-04-21 12:32 UTC, gsmet approved these changes
Looks good to me, thanks!

2020-04-21 12:32 UTC, merged