Add Quarkus Vault Authentication Guide - Fixes #4846
quarkusio/quarkus pull request #8615
Opened 2020-04-16 10:30 UTC by vsevel

This provides a dedicated guide that covers all currently supported Vault Authentication methods:
 - direct token (including variant with response wrapping)
 - userpass
 - approle (including variant with response wrapping)
 - kubernetes

2020-04-16 10:42 UTC, lordofthejars approved these changes
Really nice document that will allow us to add more strategies in the future.

2020-04-16 10:43 UTC, lordofthejars commented
@vsevel one comment shouldn't this PR contains removing the lines of the previous docs?

2020-04-16 11:00 UTC, sberyozkin commented
@lordofthejars 

> one comment shouldn't this PR contains removing the lines of the previous docs?

Can you clarify please ? Thanks

2020-04-16 11:11 UTC, lordofthejars commented
@sberyozkin I mean that some of the content added in this doc is duplicated in other Vault guides, so maybe they should be removed as well, and this PR could be used for this.

2020-04-16 14:32 UTC, sberyozkin commented
@lordofthejars Good point, I suppose the those docs can provide some basic relevant info with the link to the main Vault authentication doc

2020-04-16 14:44 UTC, vsevel commented
@lordofthejars @sberyozkin thanks for your encouraging comments :-)

> Really nice document that will allow us to add more strategies in the future.

yes definitely. for instance for the cert auth.

> I mean that some of the content added in this doc is duplicated in other Vault guides, so 
maybe they should be removed as well, and this PR could be used for this.

actually there is almost no overlap, because in the base guide I activate the `userpass` auth method and set up the user with a note specifying that other auth methods exist but without any details (client token, approle and k8s); and in the vault-auth guide I say in the `userpass` section that I expect the `userpass` method to be already enabled from the base guide. if we consider the quarkus documentation to be guides (and not reference doc), then I think it is fine.

also in the vault-auth guide I set the base guide to be a prerequisite (allowing to reuse the configured vault + the app). because I think the base guide is what people will want to discover first. and we need to provide a minimal vault auth setup (`userpass` in this case). the base guide needs to be standalone.

one thing we could do in the base guide is to remove the _The Vault extension also supports alternate authentication methods such as:_ note and replace it with: _Other auth methods are supported. Check the vault auth guide for details_.

what yo you think?

2020-04-16 17:52 UTC, gsmet requested changes
Awesome! I added some very minor comments.

2020-04-16 17:52 UTC, gsmet commented on docs/src/main/asciidoc/vault-auth.adoc
> +* Start using Vault using the client token, within the limits of what is allowed in policies associated with the token
```suggestion
* Start using Vault using the client token, within the limits of what is allowed by the policies associated with the token
```
?

2020-04-16 17:52 UTC, gsmet commented on docs/src/main/asciidoc/vault-auth.adoc
> +* For the Kubernetes authentication: A Kubernetes distribution to deploy the Quarkus application (minishift, k3s, docker desktop, …​)
```suggestion
* For the Kubernetes authentication: A Kubernetes distribution to deploy the Quarkus application (Minishift, K3s, Docker Desktop, …​)
```

2020-04-16 17:52 UTC, gsmet commented on docs/src/main/asciidoc/vault-auth.adoc
> +We assume there is a Vault container and a PostgresQL container running from the {base-guide}, and the root token is known.
```suggestion
We assume there is a Vault container and a PostgreSQL container running from the {base-guide}, and the root token is known.
```

2020-04-16 17:52 UTC, gsmet commented on docs/src/main/asciidoc/vault-auth.adoc
> +Create a token for policy `vault-quickstart-policy`:
```suggestion
Create a token for the `vault-quickstart-policy` policy:
```

2020-04-16 17:52 UTC, gsmet commented on docs/src/main/asciidoc/vault-auth.adoc
> +One drawback of this approach is that you expose a secret piece of information (.i.e the token) that can give access
```suggestion
One drawback of this approach is that you expose a secret piece of information (i.e. the token) that can give access
```

2020-04-16 17:52 UTC, gsmet commented on docs/src/main/asciidoc/vault-auth.adoc
> +With that in mind, let’s create a new token and wrap it inside a _Wrapping Token_ with a ttl of 1 minute:
```suggestion
With that in mind, let’s create a new token and wrap it inside a _Wrapping Token_ with a TTL of 1 minute:
```

2020-04-16 17:52 UTC, gsmet commented on docs/src/main/asciidoc/vault-auth.adoc
> +Stop the application, and execute tests with `./mvnw test`. They should fail with error:
```suggestion
Stop the application, and execute tests with `./mvnw test`. They should fail with the following error:
```

2020-04-16 17:52 UTC, gsmet commented on docs/src/main/asciidoc/vault-auth.adoc
> +unsual to use this approach as response wrapping typically involves a technical workflow,
```suggestion
unusual to use this approach as response wrapping typically involves a technical workflow,
```
or usual? but I would say the former.

2020-04-16 17:52 UTC, gsmet commented on docs/src/main/asciidoc/vault-auth.adoc
> +Kubernetes jwt token located in `/var/run/secrets/kubernetes.io/serviceaccount`.
```suggestion
Kubernetes JWT token located in `/var/run/secrets/kubernetes.io/serviceaccount`.
```

2020-04-16 17:52 UTC, gsmet commented on docs/src/main/asciidoc/vault-auth.adoc
> +to the master api to be able to validate the jwt token that the application will authenticate with.
```suggestion
to the master API to be able to validate the JWT token that the application will authenticate with.
```

2020-04-16 17:52 UTC, gsmet commented on docs/src/main/asciidoc/vault-auth.adoc
> +role that Vault will use to communicate with the master api.
```suggestion
role that Vault will use to communicate with the master API.
```

2020-04-16 17:52 UTC, gsmet commented on docs/src/main/asciidoc/vault-auth.adoc
> +Once the objects are created, we need to capture the jwt token of this service account,
```suggestion
Once the objects are created, we need to capture the JWT token of this service account,
```

2020-04-16 17:52 UTC, gsmet commented on docs/src/main/asciidoc/vault-auth.adoc
> +plus replace `<host>` by the ip or name of the local host that is running the Vault and PostgresQL containers,
```suggestion
plus replace `<host>` by the ip or name of the local host that is running the Vault and PostgreSQL containers,
```

2020-04-16 17:53 UTC, gsmet commented
@vsevel should I backport this document to 1.4? Are all the elements here in CR1? Do I need to backport more things? Thanks!

2020-04-16 19:18 UTC, vsevel commented
dear all 

@lordofthejars @sberyozkin I modified the vault guide to refer to the vault auth guide in the following note: _Quarkus supports additional Vault Authentication methods. Check the {vault-auth-guide} for details._

I also added this precision in the `userpass` section of the vault auth guide: _Normally the userpass auth method should already be enabled from the {base-guide}. If not, execute the following commands now: ..._

> and also link to this doc from the main index page

are you talking about `index.adoc`? I thought this file was obsolete. Is there a place where I should list all vault guides?

@gsmet I have done all the suggested modifications. I have pushed and squashed so if everybody is fine, you can go ahead and merge. you can backport it too, since all the code is already in 1.4 (the last feature was _response wrapping_).

thanks for your comments.

2020-04-17 09:08 UTC, gsmet approved these changes

2020-04-17 09:08 UTC, merged

2020-04-17 09:08 UTC, gsmet commented
Thanks, great addition!