Add gradle wrapper into platform-descriptor
quarkusio/quarkus pull request #8706
Opened 2020-04-20 15:15 UTC by glefloch

When generating a project with gradle as build tool, the wrapper is generated using the `gradle wrapper` command. If gradle is not installed on the machine, the project creation will fail.

This branch adds a fallback such as, in case of failure, gradle wrapper's files are copied from `platform-descriptor-json` artifact. 

Gradle wrapper's file are embedded in the `platform-descriptor-json` artifact at build time. 

This branch can be tested using a docker container: 

    docker run --rm -v ~/.m2:/root/.m2 maven:3.6.3-jdk-11 mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
                -DprojectGroupId=org.acme \
                -DprojectArtifactId=my-gradle-project \        
                -DclassName="org.acme.quickstart.GreetingResource" \
                -DplatformArtifactId=quarkus-bom \
                -Dpath="/hello" \
                -DbuildTool=gradle

close #4982

2020-04-20 16:35 UTC, gsmet requested changes
Looks interesting. I added some suggestions though.

2020-04-20 16:35 UTC, gsmet commented on devtools/platform-descriptor-json/pom.xml
> +                            </arguments>
Two comments here. I think we should use `./gradlew`. Maybe we could reuse the one in `devtools/gradle`. We would need to support both Unix-based OSes and Windows (so use the `gradlew.bat`).

Also, I think we should specify the version by using the `gradle-wrapper.version` property defined in `build-parent/pom.xml`.

2020-04-20 16:35 UTC, gsmet commented
/cc @gastaldi

2020-04-20 18:10 UTC, gastaldi commented
I agree with @gsmet' suggestions

2020-04-20 18:59 UTC, glefloch commented
Thanks for the review, I will update the code ASAP.

2020-04-21 09:59 UTC, gsmet requested changes
Looks mostly good. I added two other things I missed when first reviewing.

I think we should always copy the files and be done with it. Having a local Gradle is really not that common given everybody uses the wrapper.

2020-04-21 09:59 UTC, gsmet commented on devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java
> +            copyGradleWrapperFiles(platform, writer);
Shouldn't we just drop the part where we try to use a local Gradle? I think copying things is better.

2020-04-21 09:59 UTC, gsmet commented on devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java
> +            getLog().error("Unable to copy Gradle wrapper from platform descriptor");
We don't want to lose the exception.

2020-04-22 08:03 UTC, gsmet approved these changes
Looks good to me now, thanks!

@gastaldi I let you check it works as expected before merging?

2020-04-22 12:33 UTC, gastaldi approved these changes
Works as advertised. Good job! :+1:

2020-04-22 12:33 UTC, merged