Add context propagation section in the cache extension guide
quarkusio/quarkus pull request #8968
Opened 2020-04-29 23:11 UTC by gwenneg

Follow-up of #8227, related to #8166.

2020-05-01 15:04 UTC, gsmet requested changes
Added some small suggestions.

2020-05-01 15:04 UTC, gsmet commented on docs/src/main/asciidoc/cache.adoc
> +You can find more information about context propagation in Quarkus in the link:context-propagation.html[dedicated guide].
```suggestion
You can find more information about context propagation in Quarkus in the link:context-propagation[dedicated guide].
```

2020-05-01 15:04 UTC, gsmet commented on docs/src/main/asciidoc/cache.adoc
> +The context propagation can be enabled for this extension by simply including the `quarkus-smallrye-context-propagation` dependency into your project.
```suggestion
The context propagation can be enabled for this extension by simply adding the `quarkus-smallrye-context-propagation` extension to your project.
```

2020-05-01 23:06 UTC, gwenneg commented
Thanks for the review @gsmet! Your suggestions have been applied.

2020-05-04 11:56 UTC, gsmet approved these changes

2020-05-04 11:56 UTC, merged

2020-05-04 11:56 UTC, gsmet commented
Merged, thanks!