[fixes #8508] - mTLS client authentication support
quarkusio/quarkus pull request #8991
Opened 2020-04-30 19:25 UTC by pedroigor

2020-04-30 19:29 UTC, pedroigor commented
@stuartwdouglas I'm not sure about your suggestion on creating a default identity provider bean. This one is not here.

But the other points we discussed in https://github.com/quarkusio/quarkus/issues/8508 are implemented.

I sent a PR to https://github.com/quarkusio/quarkus-security/pull/8 with the `CertificateCredential` and `CertificateAuthenticationRequest`.

2020-05-04 18:19 UTC, pedroigor commented
@stuartwdouglas Added the `X509IdentityProvider` to `quarkus-security`.

The doc is failing to build due to a duplicate id. The reason is that I've copied the `client-auth` config option to `HttpBuildTimeConfig` so I can get the value at build time. I did not want to change anything else as this simple change works fine except for doc generation.

2020-05-05 06:14 UTC, stuartwdouglas commented
You can't have a property as both build and runtime, that does not work, it would need to be removed from the runtime config.

2020-05-05 06:18 UTC, stuartwdouglas requested changes

2020-05-05 06:18 UTC, stuartwdouglas commented on extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/MtlsAuthenticationMechanism.java
> +            return Uni.createFrom().failure(new AuthenticationCompletionException());
This should just return an empty identity, it is still possible for the user to authenticate via another mechanism.

2020-05-05 06:18 UTC, stuartwdouglas commented on extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/MtlsAuthenticationMechanism.java
> +            return Uni.createFrom().optional(Optional.empty());
Uni now has a better API for this (createFrom().empty() I think).

2020-05-06 04:00 UTC, stuartwdouglas commented on bom/runtime/pom.xml
> +        <quarkus-security.version>1.1.2.Final-SNAPSHOT</quarkus-security.version>
I have released this.

2020-05-06 18:22 UTC, pedroigor commented
@stuartwdouglas I've moved the property from runtime to build time config. The reason why I didn't do it before is that the hot reload logic manually create the runtime config when handling a failure during the initial start. So I did not want to touch that part given that just copying the config from runtime to build time seemed to work (except for the doc generation).

I tried to write a test for a hot reload test to check if the change to the config is OK. But I did not figure out how to test the scenario where the application fails the initial start.

2020-05-08 00:40 UTC, stuartwdouglas commented
The failure to start is tested in the maven integration tests, io.quarkus.maven.it.DevMojoIT#testThatApplicationRecoversStartupIssue

2020-06-03 08:19 UTC, stuartwdouglas approved these changes

2020-06-03 08:19 UTC, stuartwdouglas commented
lgtm but needs a rebase

2020-06-03 22:08 UTC, pedroigor commented
@stuartwdouglas failures do not seem to be related:

```
[ERROR] Failures: 
[ERROR]   TestEndpointRunner.overrides:65->invokeNonOverload:81 This method should have been replaced
[INFO] 
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0
```

Re-running jobs.

2020-06-17 14:56 UTC, merged

2020-06-22 09:19 UTC, Ladicek commented
I don't see documentation changes in this PR. Is there another PR with documentation? Thanks!

2020-06-22 12:20 UTC, pedroigor commented
@Ladicek Yeah, I was supposed to send it on Fri. Will send it today.

2020-06-22 20:44 UTC, pedroigor commented
@Ladicek See https://github.com/quarkusio/quarkus/pull/10172. I also found this great blog https://quarkus.io/blog/quarkus-mutual-tls/.

2020-06-23 07:38 UTC, Ladicek commented
Great, thanks!