Quarkus bom manage smallrye-reactive-messaging-api
quarkusio/quarkus pull request #9034
Opened 2020-05-03 21:47 UTC by vietk

Fixes #9033

2020-05-03 22:01 UTC, gsmet requested changes

2020-05-03 22:01 UTC, gsmet commented on bom/runtime/pom.xml
> +                <version>${smallrye`-reactive-messaging.version}</version>
```suggestion
                <version>${smallrye-reactive-messaging.version}</version>
```

2020-05-04 04:49 UTC, geoand approved these changes
LGTM, thanks!

2020-05-04 08:20 UTC, gsmet approved these changes
I squashed the 2 commits.

2020-05-04 09:29 UTC, gsmet commented
Superseded by https://github.com/quarkusio/quarkus/pull/9041 .

2020-05-04 09:29 UTC, closed without merging