Add QUARKUS_CONFIG_LOCATION environment variable
quarkusio/quarkus pull request #9290
Opened 2020-05-14 06:54 UTC by glefloch

This pull request adds the ability to set the directory of external configuration. By default, it will still be `config/`

close #8820

2020-05-14 08:39 UTC, geoand commented
Seems reasonable but perhaps @dmlloyd has something in the pipeline that would make this obsolete?

2020-05-14 09:30 UTC, gsmet requested changes

2020-05-14 09:30 UTC, gsmet commented on docs/src/main/asciidoc/config.adoc
> +  * The `$PWD/config` directory can be override by setting `QUARKUS_CONFIG_LOCATION` environment variable.
```suggestion
  * The `$PWD/config` directory can be overriden by setting the `QUARKUS_CONFIG_LOCATION` environment variable.
```

2020-05-14 13:16 UTC, dmlloyd commented
IMO this (and things like it) should not be done solely via sys prop/env var.  All config should be configured by config, one way or another.  So the external file configuration source should be set up via interceptor which loads the location from a config key like `quarkus.config.path`.

2020-05-14 13:29 UTC, geoand commented
@dmlloyd and that would be possible with the current version of Smallrye Config?

2020-05-14 13:35 UTC, dmlloyd commented
I think so, yeah.

2020-05-14 13:36 UTC, geoand commented
Thanks for the info @dmlloyd.

@glefloch would you like to take a look at the approach David proposes?

2020-05-14 14:40 UTC, glefloch commented
@geoand yes I will!

2020-05-20 13:21 UTC, glefloch commented
@geoand, @dmlloyd I came across this thread https://github.com/smallrye/smallrye-config/issues/215
 
Could we consider using the `Bootstrap` phase introduced by this pull request https://github.com/quarkusio/quarkus/pull/6913 to get the `quarkus.config.path` configuration and then producing a `ConfigSourceProvider` ?

2020-05-20 13:27 UTC, geoand commented
I hadn't thought of that option at all! I like the idea personally (since it would make the property settable in all the usual Quarkus ways), but let's see what @dmlloyd thinks.

2020-05-20 17:21 UTC, dmlloyd commented
At this point we *might* not need the bootstrap phase anymore at all.  Any steps that need to set up configuration could yield config interceptors, which in turn can read "bootstrap" properties to configure themselves (@radcortez is working on making interceptors and config sources be fundamentally equal peers, so you can implement a config source using the interceptor API if you wanted to).

2020-05-20 17:27 UTC, radcortez commented
Actually that is already done here:
https://github.com/smallrye/smallrye-config/pull/313

You can see an example, where we configure the Zookeeper ConfigSource with other configs.

If this is required, we can definitely merge it after @dmlloyd review and make a release.

2020-05-20 17:32 UTC, geoand commented
That's cool!

When that it is in, I can look into tearing out the bootstrap config and supporting this feature

2020-05-20 17:38 UTC, radcortez commented
Also, you may want to look into this: 
https://github.com/quarkusio/quarkus/pull/9184

We backported some of the features supported by Quarkus into SmallRye Config, so they don't have to be in Quarkus anymore.

2020-05-21 12:31 UTC, glefloch commented
That looks great!
@geoand, should we close this pull request and wait for smallrye-config to be released?

2020-05-21 12:33 UTC, geoand commented
Sure yeah.

Thanks for your work and for bringing this up @glefloch

2020-05-21 12:33 UTC, closed without merging