Make quarkus.kafka-streams.topics optional
quarkusio/quarkus pull request #9381
Opened 2020-05-17 14:11 UTC by rquinio

Closes #8909

- Default to discovering the topics directly from the Topology, excluding internal topics
- Support having no topics to check, in case the topology is fully dynamic and topics are not known at startup (i.e. topic pattern & TopicNameExtractor) and bypass admin client calls in such cases

2020-05-18 08:13 UTC, gsmet commented
Thanks @rquinio !

@gunnarmorling I would also be interested in your wisdom for this one!

2020-05-18 11:39 UTC, gunnarmorling requested changes
Hey @rquinio, really liking this change 👍 

My inline comments relate to the question whether sink topics should be part of the awaited topics list, too. I don't think they should, as it'd lead to dead-locks potentially when relying on auto-creation of those topics by means of running the stream processing application. When auto-creation is turned off and a sink topic actually is missing, Kafka Streams should raise an exception, which I think is ok and acceptable.

2020-05-18 11:39 UTC, gunnarmorling commented on extensions/kafka-streams/runtime/src/test/java/io/quarkus/kafka/streams/runtime/TopologyHelperTest.java
> +        assertThat(topics).containsOnly("topic1", "topic2", "topic3");
Shouldn't topic3 *not* be part of this, as it's a sink topic?

2020-05-18 11:39 UTC, gunnarmorling commented on integration-tests/kafka-streams/src/test/java/io/quarkus/it/kafka/streams/KafkaStreamsTest.java
> +                .body("checks[0].data.missing_topics",
Why is the processed topic expected now? It somehow seems that now also sink topics are awaited? If so, I don't think that'd be adviseable, as they only might be created by running the app itself, causing a dead-lock effectively.

2020-05-18 11:39 UTC, gunnarmorling commented on extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/TopologyHelper.java
> +                if (node instanceof Sink) {
Shouldn't sink topics be excluded?

2020-05-18 11:39 UTC, gunnarmorling commented on docs/src/main/asciidoc/kafka-streams.adoc
> +* a readiness health check to validate that all topics statically declared in the Topology are created.
```suggestion
* a readiness health check to validate that all source topics statically declared in the Topology have been created.
```

2020-05-18 12:47 UTC, rquinio commented
> My inline comments relate to the question whether sink topics should be part of the awaited topics list, too. I don't think they should, as it'd lead to dead-locks potentially when relying on auto-creation of those topics by means of running the stream processing application. When auto-creation is turned off and a sink topic actually is missing, Kafka Streams should raise an exception, which I think is ok and acceptable.

Indeed I didn't consider auto-creation of topics since Confluent recommendation is to disable it (cf https://docs.confluent.io/current/streams/developer-guide/manage-topics.html ).
What we're doing is that a microservice is the owner of its sink topics, and so the Strimzi KafkaTopic resource is packaged in the same helm chart as the pod Deployment resource.

Do you know what the state of Kafka Streams will be in the case of this missing sink topic exception and if it can recover from it once the sink topic is created ~20s later by an operator like Strimzi ? I'll need to dig into that case more. I guess it could work if the problem is still detected by the liveness probe (i.e. state is not RUNNING), so the deployment is eventually rolled back.

2020-05-21 00:59 UTC, rquinio commented
I've confirmed the behavior (cf https://github.com/rquinio/quarkus/commit/c2f4d74deffbc2366f19d31e29df3cff4c837856): 

1) With `auto.create.topics.enable=true` on the broker (and `allow.auto.create.topics=false on the test Kafka consumer`):
If waiting only for the input topic(s) before starting Kafka streams, the output topic gets created automatically by Kafka Streams producer - 

2) With`auto.create.topics.enable=false` on the broker: 
If waiting for both input AND output topics before starting Kafka streams, state is in ERROR and it does not recover by itself, even if the output topic is created afterwards.

2020-05-21 01:06 UTC, rquinio commented
There is a problem using the liveness failure: liveness doesn't trigger a rollback of a deployment by itself (at least not via helm `upgrade --wait --atomic`, not sure about `kubectl rollout`). So we would still need the readiness probe to check for sink topics, otherwise some deployment referencing a bad topic could end up in CrashLoopBackOff.

Rather than splitting `quarkus.kafka-streams.topics` into two lists (startup vs readiness), how about having a flag which tells to not wait for any sink topics from `quarkus.kafka-streams.topics` at startup ? 
It would default to false (since auto-creation of topics is not recommended in production) but could be overridden in a dev/test profile ?

2020-06-16 10:53 UTC, gunnarmorling commented
Circling back to this, sorry for the delay.

Could we query the broker whether topic auto creation is enabled or not? If so, then we could do the following:

* if auto creation is enabled, only await all source topics of the topology
* if auto creation is _not_ enabled, await all source and sink topics of the topology

WDYT?

2020-06-16 12:17 UTC, rquinio commented
No problem, interesting idea !
It seems there's an API (flagged "evolving") to query this - [Admin#describeConfigs](https://kafka.apache.org/25/javadoc/org/apache/kafka/clients/admin/Admin.html#describeConfigs-java.util.Collection-org.apache.kafka.clients.admin.DescribeConfigsOptions-), I'll try it.

2020-10-12 12:28 UTC, gsmet commented
This is way outdated. If you still want this in (and it looked interesting), please open a new PR or reopen this one with an update.

2020-10-12 12:28 UTC, closed without merging

2020-10-12 12:58 UTC, gunnarmorling commented
Uff, I thought this one had been merged long time ago :( +1 for reviving
this based on current master; not sure what's even missing at this point?

>

2020-10-12 14:31 UTC, rquinio commented
@gunnarmorling I had no success so far using Admin#describeConfigs to get the value of `allow.auto.create.topics` at startup when testing with the emedded broker. :/

Thinking about this again, I could add a runtime setting:
quarkus.kafka-streams.topics.auto-created=false(default)/true
This would cover the testing/demo cases and tell the startup to ignore any check on sink topics. WYT ?