[fixes #8469] - Configuration properties references for keycloak-authorization extension
quarkusio/quarkus pull request #9583
Opened 2020-05-25 13:40 UTC by pedroigor

2020-05-25 14:02 UTC, gsmet requested changes

2020-05-25 14:02 UTC, gsmet commented on extensions/keycloak-authorization/runtime/src/main/java/io/quarkus/keycloak/pep/runtime/KeycloakPolicyEnforcerConfig.java
>          @ConfigItem(defaultValue = "ENFORCING")
Could you make `enforcing` lowercase? For enums, the doc will advertise the values in lowercase with dashes so better have the default value consistent.

2020-05-25 16:33 UTC, sberyozkin approved these changes
@pedroigor Hey Pedro, thanks for a quick fix

2020-05-26 09:06 UTC, gsmet approved these changes

2020-05-26 09:06 UTC, gsmet commented
I pushed an additional commit with the case change. Let's wait for CI.

2020-05-26 12:19 UTC, merged