Properly support defining env vars from secret/configmap keys
quarkusio/quarkus pull request #9758
Opened 2020-06-03 19:42 UTC by metacosm

- [ ] Restore (undocumented) behavior that was broken with the new style configuration
- [ ] Provide new style configuration for defining env vars from secret/configmap keys

2020-06-07 20:30 UTC, metacosm commented
@iocanel this is ready for review

2020-06-09 11:00 UTC, iocanel requested changes
Looks great.

The only thing I'd like to be added is to slightly extend the coverage. See details in the comments.

2020-06-09 12:14 UTC, metacosm commented on integration-tests/kubernetes/quarkus-standard-way/src/test/resources/kubernetes-with-env-from-configmap.properties
> +quarkus.kubernetes.env.configmaps=my-configmap
I assume you're talking about the `1.3` branch, right? Commit ccb3574d17034ee6b09098eb5b51cdeac2829d90?

2020-06-09 14:56 UTC, geoand commented
@metacosm is this ready? If so, we should try and get it in tomorrow's release.

@iocanel can you please review?

2020-06-09 15:00 UTC, metacosm commented
> @metacosm is this ready? If so, we should try and get it in tomorrow's release.
> 
> @iocanel can you please review?

That's ready from my side. I just need to squash the last commits. One thing I'm not too sure about are the `vars-from-configmap` and `vars-from-secret` names which kind of are a mouthful so I'm willing to change them if people have better names for this… :)

2020-06-09 15:04 UTC, geoand commented
I absolutely suck at naming, so I won't be able to provide any better one :)

2020-06-09 15:17 UTC, geoand commented
@metacosm can you please squash the commits in order  to make the commit ready for merging?

2020-06-09 15:19 UTC, metacosm commented
@geoand done

2020-06-09 15:21 UTC, geoand commented
Thanks!

2020-06-11 12:47 UTC, metacosm commented
Decision was made to use
```properties
quarkus.kubernetes.env.mapping.db-password.from-secret=db-secret
quarkus.kubernetes.env.mapping.db-password.with-key=database.password
```
syntax.

2020-06-11 13:02 UTC, geoand commented
@iocanel please review since you've been following more than me

2020-06-11 15:40 UTC, iocanel approved these changes
LGTM

2020-06-11 16:11 UTC, metacosm commented
I guess I didn't go through the Java 14 tests… 🤷

2020-06-11 16:27 UTC, geoand commented
Java 14 has been a thorn in our side the past few days...

2020-06-11 16:27 UTC, merged

2020-06-11 16:28 UTC, metacosm commented
> Java 14 has been a thorn in our side the past few days when it comes to CI...

Yep, I know 😉