First step to extract Maven-specific parts from the bootstrap core
quarkusio/quarkus pull request #9828
Opened 2020-06-05 13:32 UTC by aloubyansky

This PR extracts the following from `bootstrap-core`:
*  AppModel API to `app-model` module;
*  the Maven resolver impl to `maven-resolver` module (this one depends on `app-model`).

`bootstrap-core` still depends on `maven-resolver` though at this point, so anything that depends on `bootstrap-core` will still work w/o adding extra dependencies.

2020-06-06 06:09 UTC, aloubyansky commented
I also included a few interfaces in `app-model` module package `io.quarkus.bootstrap.resolver.workspace` as a start to represent the Maven and Gradle projects from a workspace.

2020-06-09 03:19 UTC, stuartwdouglas requested changes
LGTM except for the extra file.

2020-06-09 04:18 UTC, aloubyansky commented on devtools/gradle/deps.log
> +> Task :dependencies
Oh, you're right. Removing it.

2020-06-09 04:45 UTC, stuartwdouglas approved these changes

2020-06-09 21:00 UTC, merged