[WIP] add kotlin allopen transformation
quarkusio/quarkus pull request #9856
Opened 2020-06-08 11:27 UTC by RotBolt

cc @evanchooly @geoand 

Currently it is able to transform only classes with annotation
 but if a class (which is to be opened) extends a class (which also needs to be opened) than it fails

For example `class NativeImageTest : GreetingResourceTest`  then it fails 
probably because GreetingResourceTest has not been opened by transformer yet

2020-06-08 11:28 UTC, RotBolt commented
Also one thing It came to mind 
to also check for super class and perform transformation for that too

2020-06-08 11:33 UTC, geoand commented
This is a good start, but I think we need to have Quarkus automatically figure out which (Kotlin) classes need to be opened and not have this be driven by user config.
We should always know when a class needs to be opened (if it's a Hibernate entity or a JAX-RS resource for example).
How best to do this is up for discussion

2020-06-08 12:49 UTC, RotBolt commented
Might be wrong path way to do

If we put the all the annotations for which we want the classes to be ooen. I guess it would solve the issue 

A better way to do would 
- check the dependencies (if includes hibernate or resteasy) 
- enable annotations for those dependencies
- perform transformation

2020-06-08 12:54 UTC, geoand commented
There are 2 ways of figuring out what needs to be opened:

1) Each extension publishes this data (essentially pushes a build item)
2) The Kotlin extension has all the lookup logic.

Obviously 1) is better, but it requires changes to more extensions

2020-06-08 15:05 UTC, RotBolt commented
Even if each extension pushes its own buildItem that build item has to be injected in the processor AFAIU.
So wouldn't this be kinda similar to "all lookup logic in kotlin" ?

2020-06-08 15:07 UTC, geoand commented
The difference lies in where the logic of determining which classes need to be opened lies.

Also, one could think that making a class open (or non-final in Java terms) is a more general concern, not limited to Kotlin.

2020-06-08 15:17 UTC, evanchooly commented
We might just be overthinking it, too.  Java is not closed by default where kotlin is.  We could simply apply this transformation to all Kotlin classes (check the for the kotlin metadata annotation) and all the get/set/is methods on the classes.  This would treat the cases where a Java dev marks a class as final as a user error to be cleaned up by the dev rather than silently sweep it under a rug.

2020-06-08 15:23 UTC, geoand commented
Yeah, that's definitely an option as well.

The only problem I foresee with that approach is that applying this transformation to all Kotlin classes has the potential to slow down the build.

2020-06-08 15:28 UTC, evanchooly requested changes

2020-06-08 15:28 UTC, evanchooly commented on extensions/kotlin/deployment/src/main/java/io/quarkus/kotlin/deployment/AllOpenConfig.java
> +    public final List<String> defaultAnnotations = Arrays.asList(
use DotName instead

2020-06-08 15:28 UTC, evanchooly commented on extensions/kotlin/deployment/src/main/java/io/quarkus/kotlin/deployment/KotlinProcessor.java
> +//                    System.out.println("Target " + annotationInstance.target().toString());
debug should come out

2020-06-08 15:28 UTC, evanchooly commented on extensions/kotlin/deployment/src/main/java/io/quarkus/kotlin/deployment/KotlinProcessor.java
> +                            classesToTransform.add(classInfo.name().toString());
using DotNames a simple .equals would suffice

2020-06-08 15:28 UTC, evanchooly commented on extensions/kotlin/deployment/src/main/java/io/quarkus/kotlin/deployment/KotlinProcessor.java
> +                        if (annotationInstance.name().toString().equals(customAnnotation)) {
same

2020-06-08 15:28 UTC, evanchooly commented on extensions/kotlin/deployment/src/main/java/io/quarkus/kotlin/deployment/KotlinProcessor.java
> +                                    System.out.println("ACC_FINAL " + Opcodes.ACC_FINAL + " Access" + access);
debug

2020-06-08 15:38 UTC, evanchooly commented
if we wanted to generalize it, we could add a, say, `NonFinalBuildItem` that indicates an annotation that requires non-final classes and methods.  We could couple that with the kotlin metadata annotation to speed things up.

At that point the question becomes do we just always unmask the final for java classes, too?  It'd be the "neighborly" thing to do but i'm loathe to automatically, silently undo conscious decisions on the part of the Java developer.  We could, perhaps, just apply the filter to kotlin and java classes alike and log a `warning` for non-kotlin classes to direct the java devs to remove those final keywords.  This would mean each extension would have to publish that new build item but it would future proof this transformer against new extensions/annotations.

2020-06-08 15:40 UTC, geoand commented
> if we wanted to generalize it, we could add a, say, `NonFinalBuildItem` that indicates an annotation that requires non-final classes and methods.  We could couple that with the kotlin metadata annotation to speed things up.
> 
 Exactly what I was thinking

2020-06-08 15:40 UTC, geoand commented
@evanchooly yeah, I'm not sure what the best solution is, just pondering options

2020-06-09 04:29 UTC, RotBolt commented
> if we wanted to generalize it, we could add a, say, `NonFinalBuildItem` that indicates an annotation that requires non-final classes and methods.  We could couple that with the kotlin metadata annotation to speed things up.


Would the extension push these `NonFinalBuildItem` ? And we would just unmask the final for the classes which has `kotlin metadata` and these `NonFinalBuildItem` ?

2020-06-09 04:34 UTC, evanchooly commented
Well, if the extensions were publishing these theoretical `NonFinalBuildItem`s we would simply mask away final on any classes so marked regardless of the kotlin metadata annotation.  We could optionally log that we were masking away final modifiers and either use the kotlin metadata annotation to limit that or not.

2020-06-30 14:30 UTC, evanchooly commented
adding to epic  #10377

2020-10-12 12:25 UTC, gsmet commented
@evanchooly is it still needed with all the work you did? I would be in favor of closing this one and revisit in another PR if need be. Could you confirm?

2020-10-12 17:16 UTC, evanchooly commented
I agree.  so far quarkus makes what changes it needs and the fewer assumptions we can make about external configurations the simpler we can make things internally.

2020-10-25 15:44 UTC, gastaldi commented
Closing as described above

2020-10-25 15:44 UTC, closed without merging