OIDC JWK refresh support
quarkusio/quarkus pull request #9891
Opened 2020-06-09 16:48 UTC by sberyozkin

Fixes #5003 
Fixes #7286

This PR:
- Supports a forced JWK refresh based on a `missingKeyHandler` Vertx Auth 3.9.1 feature with a controlled refresh interval period (10 mins by default). Right now, if the rotation happens and the current token has no local JWK with a matching `kid` to verify it then 2 requests will go to OIDC server, 1 JWK refresh from our handler and one fallback introspection request - this is not really a problem for now as it will happen only once in some long enough irregular rotation interval in a long running application 
- Along the way the opaque access tokens are now also supported
- adds a test `OidcResource` server endpoint to emulate Keycloak
- adds a test that confirms that a JWK refresh alone, without the introspection, is enough to verify a token after the key rotation, plus checks the fallback introspection is effective for the opaque token 

CC @plopes

2020-06-10 11:22 UTC, stuartwdouglas requested changes
LGTM except for some minor changes.

2020-06-10 11:22 UTC, stuartwdouglas commented on extensions/oidc/runtime/src/main/java/io/quarkus/oidc/OidcTenantConfig.java
> +        public long forcedJwkRefreshInterval = 10;
I think this should be a Duration, so our standard time based converters work.

2020-06-10 11:22 UTC, stuartwdouglas commented on extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcUtils.java
> +        return JWT_PARTS_PATTERN.split(token).length != 3;
Wouldn't it be a lot more efficient to just use a loop? Using a regex to count the number of '.' characters in a string feels like overkill.

2020-06-10 14:01 UTC, pedroigor requested changes

2020-06-10 23:58 UTC, stuartwdouglas approved these changes

2020-06-12 13:03 UTC, pedroigor approved these changes

2020-06-15 11:22 UTC, merged